(*******************************************************************************
Customized Variable mapping for the plant communication

This code is confidential and proprietary to the INNIO Company.
It may not be used in any form, or reproduced in any manner, without the express
written permission of the INNIO Company.
Copyright, INNIO Company, 2024

Customized modifications: -
------------------------
 
History:
-------
V4.14.0	26.11.2024	Astner	Created Task

						
Instructions for use: -
--------------------
Outstandings: -
------------

*******************************************************************************)


PROGRAM _INIT
	(* Insert code here *)
	 
END_PROGRAM