(********************************************************************
 * COPYRIGHT -- INNIO Company
 ********************************************************************
 * PROGRAM: c_coupl
 * File: c_couplInit.st
 * Author: Denk Mathias
 * Created: Nov 20, 2013
 ********************************************************************
 * Implementation of program c_ctr
 ********************************************************************)

PROGRAM _INIT

	InData2[1];  	(*ToDo: -> Denk? *)
	
END_PROGRAM

