(********************************************************************
 * COPYRIGHT -- INNIO Company
 ********************************************************************
 * Package: ATD
 * File: perm_ATD.typ
 * Author: 105026853
 * Created: November 18, 2015
 ********************************************************************
 * Data types of package ATD
 ********************************************************************)

TYPE
	perm_FDT : 	STRUCT 
		Pr_Knck_TH_MDN : REAL;
		PBCSlowDriftCheck_CNT : USINT;
		IT_TH_MDN : REAL;
		Pmax_TH_MDN : REAL;
		IMEP_TH_MDN : REAL;
		Pr_49bTDC_TH_MDN : REAL;
		Pr_49aTDC_TH_MDN : REAL;
		T_Exh_TH_MDN : REAL;
		AI50_TH_MDN : REAL;
		CA_PI_Duration_TH_MDN : REAL;
		T_Rod_TH_MDN : REAL;
		integrator_increment : REAL;
		filter_INT1_TH : REAL;
		P_Act_Min_TH_REF : REAL;
		P_Act_Min_TH_s1_MAX : REAL;
		P_Act_Max_TH_REF : REAL;
		P_Act_Max_TH_s1_MAX : REAL;
		P_Set_Min_TH_s1_MAX : REAL;
		P_Set_Max_TH_s1_MAX : REAL;
		Pr_P2s_A_Min_TH_REF : REAL;
		Pr_P2s_A_Min_TH_s1_MAX : REAL;
		Pr_P2s_A_Max_TH_REF : REAL;
		Pr_P2s_A_Max_TH_s1_MAX : REAL;
		Pr_P2s_B_Min_TH_REF : REAL;
		Pr_P2s_B_Min_TH_s1_MAX : REAL;
		Pr_P2s_B_Max_TH_REF : REAL;
		Pr_P2s_B_Max_TH_s1_MAX : REAL;
		Pr_Leanox_Set_Min_TH_s1_MAX : REAL;
		Pr_Leanox_Set_Max_TH_s1_MAX : REAL;
		Pr_GR_Act_Min_TH_REF : REAL;
		Pr_GR_Act_Min_TH_s1_MAX : REAL;
		Pr_GR_Act_Max_TH_REF : REAL;
		Pr_GR_Act_Max_TH_s1_MAX : REAL;
		Pr_GR_Set_Min_TH_s1_MAX : REAL;
		Pr_GR_Set_Max_TH_s1_MAX : REAL;
		Pr_PC_Act_Min_TH_REF : REAL;
		Pr_PC_Act_Min_TH_s1_MAX : REAL;
		Pr_PC_Act_Max_TH_REF : REAL;
		Pr_PC_Act_Max_TH_s1_MAX : REAL;
		Pr_PC_Set_Min_TH_s1_MAX : REAL;
		Pr_PC_Set_Max_TH_s1_MAX : REAL;
		Pr_Crank_Case_Min_TH_s1_MAX : REAL;
		Pr_Crank_Case_Max_TH_s1_MAX : REAL;
		Pr_Crank_Case_Min_TH_REF : REAL;
		Pr_Crank_Case_Max_TH_REF : REAL;
		Pos_CBV_A1_Min_TH_REF : REAL;
		Pos_CBV_A1_Min_TH_s1_MAX : REAL;
		Pos_CBV_A1_Max_TH_REF : REAL;
		Pos_CBV_A1_Max_TH_s1_MAX : REAL;
		Pos_CBV_B1_Min_TH_REF : REAL;
		Pos_CBV_B1_Min_TH_s1_MAX : REAL;
		Pos_CBV_B1_Max_TH_REF : REAL;
		Pos_CBV_B1_Max_TH_s1_MAX : REAL;
		Pos_CBV_Set_Min_TH_s1_MAX : REAL;
		Pos_CBV_Set_Max_TH_s1_MAX : REAL;
		Speed_NOM : REAL;
		Speed_Min_TH_NOM_CNT : USINT;
		Speed_Min_TH_s1_CNT : USINT;
		Speed_Max_TH_NOM : REAL;
		Speed_Max_TH_s1_MAX : REAL;
		T_T2s_NOM : REAL;
		T_T2s_TH_NOM_CNT : USINT;
		T_T2s_TH_s1_CNT : USINT;
		Lam_Set_Min_NOM : REAL;
		Lam_Set_Min_TH_NOM_CNT : USINT;
		Lam_Set_Min_TH_s1_CNT : USINT;
		Lam_Set_Max_NOM : REAL;
		Lam_Set_Max_TH_NOM_CNT : USINT;
		Lam_Set_Max_TH_s1_CNT : USINT;
		U_L1L2_Min_NOM : REAL;
		U_L1L2_Min_TH_NOM_CNT : USINT;
		U_L1L2_Min_TH_s1_CNT : USINT;
		U_L1L2_Max_NOM : REAL;
		U_L1L2_Max_TH_NOM_CNT : USINT;
		U_L1L2_Max_TH_s1_CNT : USINT;
		U_L2L3_Min_NOM : REAL;
		U_L2L3_Min_TH_NOM_CNT : USINT;
		U_L2L3_Min_TH_s1_CNT : USINT;
		U_L2L3_Max_NOM : REAL;
		U_L2L3_Max_TH_NOM_CNT : USINT;
		U_L2L3_Max_TH_s1_CNT : USINT;
		U_L3L1_Min_NOM : REAL;
		U_L3L1_Min_TH_NOM_CNT : USINT;
		U_L3L1_Min_TH_s1_CNT : USINT;
		U_L3L1_Max_NOM : REAL;
		U_L3L1_Max_TH_NOM_CNT : USINT;
		U_L3L1_Max_TH_s1_CNT : USINT;
		I_L1_Min_NOM : REAL;
		I_L1_Min_TH_NOM_CNT : USINT;
		I_L1_Min_TH_s1_CNT : USINT;
		I_L1_Max_NOM : REAL;
		I_L1_Max_TH_NOM_CNT : USINT;
		I_L1_Max_TH_s1_CNT : USINT;
		I_L2_Min_NOM : REAL;
		I_L2_Min_TH_NOM_CNT : USINT;
		I_L2_Min_TH_s1_CNT : USINT;
		I_L2_Max_NOM : REAL;
		I_L2_Max_TH_NOM_CNT : USINT;
		I_L2_Max_TH_s1_CNT : USINT;
		I_L3_Min_NOM : REAL;
		I_L3_Min_TH_NOM_CNT : USINT;
		I_L3_Min_TH_s1_CNT : USINT;
		I_L3_Max_NOM : REAL;
		I_L3_Max_TH_NOM_CNT : USINT;
		I_L3_Max_TH_s1_CNT : USINT;
		Q_Min_NOM : REAL;
		Q_Min_TH_NOM_CNT : USINT;
		Q_Min_TH_s1_CNT : USINT;
		Q_Max_NOM : REAL;
		Q_Max_TH_NOM_CNT : USINT;
		Q_Max_TH_s1_CNT : USINT;
		Freq_Min_NOM : REAL;
		Freq_Min_TH_NOM_CNT : USINT;
		Freq_Min_TH_s1_CNT : USINT;
		Freq_Max_NOM : REAL;
		Freq_Max_TH_NOM_CNT : USINT;
		Freq_Max_TH_s1_CNT : USINT;
		CosPhi_Min_NOM : REAL;
		CosPhi_Min_TH_NOM_CNT : USINT;
		CosPhi_Min_TH_s1_CNT : USINT;
		CosPhi_Max_NOM : REAL;
		CosPhi_Max_TH_NOM_CNT : USINT;
		CosPhi_Max_TH_s1_CNT : USINT;
		T_Main_TH_NOM : REAL;
		T_Main_TH_s1_MAX : REAL;
		Lam_Set_Min_filter_H_MAX : REAL;
		Lam_Set_Min_filter_H_Tconst : REAL;
		Lam_Set_Max_filter_H_MAX : REAL;
		Lam_Set_Max_filter_H_Tconst : REAL;
		Pr_Knck_TH_MDN_CNT : USINT;
		IT_TH_MDN_CNT : USINT;
		Pmax_TH_MDN_CNT : USINT;
		IMEP_TH_MDN_CNT : USINT;
		Pr_49bTDC_TH_MDN_CNT : USINT;
		Pr_49aTDC_TH_MDN_CNT : USINT;
		T_Exh_TH_MDN_CNT : USINT;
		AI50_TH_MDN_CNT : USINT;
		CA_PI_Duration_TH_MDN_CNT : USINT;
		T_Rod_TH_MDN_CNT : USINT;
		integrator_decay : REAL;
		P_Act_Min_TH_REF_CNT : USINT;
		P_Act_Min_TH_s1_CNT : USINT;
		P_Act_Max_TH_REF_CNT : USINT;
		P_Act_Max_TH_s1_CNT : USINT;
		P_Set_Min_TH_s1_CNT : USINT;
		P_Set_Max_TH_s1_CNT : USINT;
		Pr_P2s_A_Min_TH_REF_CNT : USINT;
		Pr_P2s_A_Min_TH_s1_CNT : USINT;
		Pr_P2s_A_Max_TH_REF_CNT : USINT;
		Pr_P2s_A_Max_TH_s1_CNT : USINT;
		Pr_P2s_B_Min_TH_REF_CNT : USINT;
		Pr_P2s_B_Min_TH_s1_CNT : USINT;
		Pr_P2s_B_Max_TH_REF_CNT : USINT;
		Pr_P2s_B_Max_TH_s1_CNT : USINT;
		Pr_Leanox_Set_Min_TH_s1_CNT : USINT;
		Pr_Leanox_Set_Max_TH_s1_CNT : USINT;
		Pr_GR_Act_Min_TH_REF_CNT : USINT;
		Pr_GR_Act_Min_TH_s1_CNT : USINT;
		Pr_GR_Act_Max_TH_REF_CNT : USINT;
		Pr_GR_Act_Max_TH_s1_CNT : USINT;
		Pr_GR_Set_Min_TH_s1_CNT : USINT;
		Pr_GR_Set_Max_TH_s1_CNT : USINT;
		Pr_PC_Act_Min_TH_REF_CNT : USINT;
		Pr_PC_Act_Min_TH_s1_CNT : USINT;
		Pr_PC_Act_Max_TH_REF_CNT : USINT;
		Pr_PC_Act_Max_TH_s1_CNT : USINT;
		Pr_PC_Set_Min_TH_s1_CNT : USINT;
		Pr_PC_Set_Max_TH_s1_CNT : USINT;
		Pr_Crank_Case_Min_TH_s1_CNT : USINT;
		Pr_Crank_Case_Max_TH_s1_CNT : USINT;
		Pr_Crank_Case_Min_TH_REF_CNT : USINT;
		Pr_Crank_Case_Max_TH_REF_CNT : USINT;
		Pos_CBV_A1_Min_TH_REF_CNT : USINT;
		Pos_CBV_A1_Min_TH_s1_CNT : USINT;
		Pos_CBV_A1_Max_TH_REF_CNT : USINT;
		Pos_CBV_A1_Max_TH_s1_CNT : USINT;
		Pos_CBV_B1_Min_TH_REF_CNT : USINT;
		Pos_CBV_B1_Min_TH_s1_CNT : USINT;
		Pos_CBV_B1_Max_TH_REF_CNT : USINT;
		Pos_CBV_B1_Max_TH_s1_CNT : USINT;
		Pos_CBV_Set_Min_TH_s1_CNT : USINT;
		Pos_CBV_Set_Max_TH_s1_CNT : USINT;
		Speed_Min_TH_NOM : REAL;
		Speed_Min_TH_s1_MAX : REAL;
		Speed_Max_TH_NOM_CNT : USINT;
		Speed_Max_TH_s1_CNT : USINT;
		T_T2s_TH_NOM : REAL;
		T_T2s_TH_s1_MAX : REAL;
		Lam_Set_Min_TH_NOM : REAL;
		Lam_Set_Min_TH_s1_MAX : REAL;
		Lam_Set_Max_TH_NOM : REAL;
		Lam_Set_Max_TH_s1_MAX : REAL;
		U_L1L2_Min_TH_NOM : REAL;
		U_L1L2_Min_TH_s1_MAX : REAL;
		U_L1L2_Max_TH_NOM : REAL;
		U_L1L2_Max_TH_s1_MAX : REAL;
		U_L2L3_Min_TH_NOM : REAL;
		U_L2L3_Min_TH_s1_MAX : REAL;
		U_L2L3_Max_TH_NOM : REAL;
		U_L2L3_Max_TH_s1_MAX : REAL;
		U_L3L1_Min_TH_NOM : REAL;
		U_L3L1_Min_TH_s1_MAX : REAL;
		U_L3L1_Max_TH_NOM : REAL;
		U_L3L1_Max_TH_s1_MAX : REAL;
		I_L1_Min_TH_NOM : REAL;
		I_L1_Min_TH_s1_MAX : REAL;
		I_L1_Max_TH_NOM : REAL;
		I_L1_Max_TH_s1_MAX : REAL;
		I_L2_Min_TH_NOM : REAL;
		I_L2_Min_TH_s1_MAX : REAL;
		I_L2_Max_TH_NOM : REAL;
		I_L2_Max_TH_s1_MAX : REAL;
		I_L3_Min_TH_NOM : REAL;
		I_L3_Min_TH_s1_MAX : REAL;
		I_L3_Max_TH_NOM : REAL;
		I_L3_Max_TH_s1_MAX : REAL;
		Q_Min_TH_NOM : REAL;
		Q_Min_TH_s1_MAX : REAL;
		Q_Max_TH_NOM : REAL;
		Q_Max_TH_s1_MAX : REAL;
		Freq_Min_TH_NOM : REAL;
		Freq_Min_TH_s1_MAX : REAL;
		Freq_Max_TH_NOM : REAL;
		Freq_Max_TH_s1_MAX : REAL;
		CosPhi_Min_TH_NOM : REAL;
		CosPhi_Min_TH_s1_MAX : REAL;
		CosPhi_Max_TH_NOM : REAL;
		CosPhi_Max_TH_s1_MAX : REAL;
		T_Main_TH_NOM_CNT : USINT;
		T_Main_TH_s1_CNT : USINT;
		T_Main_NOM : ARRAY[0..10]OF REAL;
		U_Ign_TH_MDN : REAL;
		U_Ign_TH_MDN_CNT : USINT;
		U_Ign_TH_s1_MAX : REAL;
		U_Ign_TH_s1_CNT : USINT;
		I_L_jumpThresh : REAL;
		P_Act_jumpThresh : REAL;
		I_L_jumpTol : REAL;
		Pr_IMEP_rangeThresh : REAL;
		P_Set_Max_TH_SP : REAL;
		P_Set_Max_TH_SP_CNT : USINT;
		Pr_Peak_TH_MDN : REAL;
		Pr_Peak_TH_MDN_CNT : USINT;
		Pr_Peak2_TH_MDN : REAL;
		Pr_Peak2_TH_MDN_CNT : USINT;
		IMEP2_TH_MDN : REAL;
		IMEP2_TH_MDN_CNT : USINT;
		Pr_GR_Act_Max2_TH_REF : REAL;
		Pr_GR_Act_Max2_TH_REF_CNT : USINT;
		CA_PI_Duration2_TH_MDN : REAL;
		CA_PI_Duration2_TH_MDN_CNT : USINT;
		CA_PI_Dur_PID_Offs_TH_s1_MAX : REAL;
		CA_PI_Dur_PID_Offs_TH_s1_MAX_CNT : USINT;
		Pr_Peak_TH_LIM : REAL;
		Pr_Peak_TH_LIM_CNT : USINT;
		N_TCHP_A_Max_TH_REF : REAL;
		N_TCHP_A_Max_TH_REF_CNT : USINT;
		N_TCLP_A_Max_TH_REF : REAL;
		N_TCLP_A_Max_TH_REF_CNT : USINT;
	END_STRUCT;
	perm_FAM : 	STRUCT 
		tPU : ARRAY[0..199]OF pu_idx; (*effected power unit*)
		iObser_per : USINT; (*observation period*)
		iIdx_Log : USINT; (*index for the ring buffer*)
		iCnt_OpHours : ARRAY[0..199]OF UDINT; (*operating hours*)
		iOpHours_Min : ARRAY[0..199]OF USINT; (*minutes inforamtion @ related operating hour*)
		iAction : ARRAY[0..199]OF USINT; (*action number related to the "catalogue of recommended actions"*)
		bAcknow : ARRAY[0..199]OF BOOL; (*feedback form the  HMI*)
	END_STRUCT;
	pu_idx : 	STRUCT 
		pu : ARRAY[0..20]OF BOOL;
	END_STRUCT;
	perm_LOM : 	STRUCT 
		logicMatrix_1 : ARRAY[0..1799]OF INT;
		logicMatrix_2 : ARRAY[0..1799]OF INT;
		splitVec : ARRAY[0..59]OF INT;
		shiftVec : ARRAY[0..39]OF INT;
	END_STRUCT;
	strct_FAM : 	STRUCT 
		mcc : ARRAY[0..19]OF REAL;
		cost_repair : ARRAY[0..19]OF USINT;
		cost_not_repair : ARRAY[0..19]OF USINT;
		tCHL : ARRAY[0..19]OF chl_mem;
	END_STRUCT;
	chl_mem : 	STRUCT 
		chl : ARRAY[0..9]OF USINT;
	END_STRUCT;
END_TYPE
