(*******************************************************************************
AGGR: custom IO channels	(init)

This code is confidential AND proprietary to the INNIO Company.
It may NOT be used in any form, or reproduced in any manner, without the express
written permission of the INNIO Company.
Copyright, INNIO Company, 2019

- list addidtional customized IO channels

Customized modifications: -
------------------------
 
History:
-------
V3.99	05-07-2012	Weitzer, generated FOR modular software	
V4.00	14-02-2014	Weitzer, change version number
								
Instructions FOR use:
--------------------
- list IO channels which are configured in the IOcgf.dat data module

Outstandings:
------------

*******************************************************************************)

PROGRAM _INIT

;

END_PROGRAM

