(*********************************************************************************************
AGGR: ERDF task (init)

This code is confidential AND proprietary to the INNIO Company.
It may NOT be used in any form, or reproduced in any manner, without the express
written permission of the INNIO Company.
Copyright, INNIO Company, 2019


Customized modifications: -
------------------------
 
History:
-------

V4.00.0 28-04-2014  Maxhera,   	implementation OF the module FOR modular software
V4.03.0	15.03.2016	Perktold,	update FOR 4.3.0.0

Instructions FOR use:
--------------------
- 
Outstandings:
-------------
*********************************************************************************************)
PROGRAM _INIT

;

END_PROGRAM

