
TYPE
	ParaSDT_typ : 	STRUCT  (*OldName: new PV; Cycle: 5;*) (* *) (*V04.01.00.00*)
		ucIndexSDT : USINT;
		SlowdownTime : ARRAY[0..19]OF tSlowdownTime;
		bMsg3368_Save : BOOL; (* *) (* *) (*V04.07.00.00*)
		rPermValue01 : REAL; (*spare permanent value - replace with new vars of same lenght, when needed*) (*OldName: new PV; Cycle:5*) (*V04.07.00.00*)
		rPermValue02 : REAL; (*spare permanent value - replace with new vars of same lenght, when needed*) (*OldName: new PV; Cycle:5*) (*V04.07.00.00*)
		rPermValue03 : REAL; (*spare permanent value - replace with new vars of same lenght, when needed*) (*OldName: new PV; Cycle:5*) (*V04.07.00.00*)
		rPermValue04 : REAL; (*spare permanent value - replace with new vars of same lenght, when needed*) (*OldName: new PV; Cycle:5*) (*V04.07.00.00*)
		rPermValue05 : REAL; (*spare permanent value - replace with new vars of same lenght, when needed*) (*OldName: new PV; Cycle:5*) (*V04.07.00.00*)
		rPermValue06 : REAL; (*spare permanent value - replace with new vars of same lenght, when needed*) (*OldName: new PV; Cycle:5*) (*V04.07.00.00*)
		rPermValue07 : REAL; (*spare permanent value - replace with new vars of same lenght, when needed*) (*OldName: new PV; Cycle:5*) (*V04.07.00.00*)
		rPermValue08 : REAL; (*spare permanent value - replace with new vars of same lenght, when needed*) (*OldName: new PV; Cycle:5*) (*V04.07.00.00*)
		rPermValue09 : REAL; (*spare permanent value - replace with new vars of same lenght, when needed*) (*OldName: new PV; Cycle:5*) (*V04.07.00.00*)
		rPermValue10 : REAL; (*spare permanent value - replace with new vars of same lenght, when needed*) (*OldName: new PV; Cycle:5*) (*V04.07.00.00*)
	END_STRUCT;
	tSlowdownTime : 	STRUCT  (*OldName: new PV; Cycle: 5;*) (* *) (*V04.01.00.00*)
		SDT : REAL;
		T_ECW_Avg : REAL;
		T_EO_Avg : REAL;
		U_Exc_Avg : REAL;
		day : UINT;
		month : UINT;
		year : UINT;
		hour : UINT;
		minute : UINT;
		bTrip : BOOL; (* *) (* *) (*V04.09.00.00*)
	END_STRUCT;
	rtctime_typ : 	STRUCT  (*OldName: new PV; Cycle: 5;*) (* *) (*V04.01.00.00*)
		year : UINT;
		month : USINT;
		day : USINT;
		reserve : USINT;
		hour : USINT;
		minute : USINT;
		second : USINT;
		millisec : UINT;
		microsec : UINT;
	END_STRUCT;
	IN_EG_Struct : 	STRUCT 
		bDeflagrationPrct : BOOL; (*deflagration protection (Verpuffung)*) (*OldName: PUFF; Cycle: 5;*) (*V04.00.00.00*)
		bEng_Aux_Dem : BOOL; (*demand auxillaries *) (*OldName: M_ANFHBT; Cycle: 5;*) (*V04.04.00.00*)
		bEng_Aux_Dem_CDR : BOOL; (*SAFETY PLC: Engine auxiliaries demand with cool down run*) (*OldName:ANFHBT; Cycle:5*) (*V04.25.00.00*)
		bEng_Dem_Aut : BOOL; (*demand automatic mode*) (*OldName: M_ANF_A; Cycle: 5;*) (*V04.00.00.00*)
		bEng_Dem_Man : BOOL; (*demand manual mode*) (*OldName: M_ANF_H; Cycle: 5;*) (*V04.00.00.00*)
		bEng_Start : BOOL; (*engine start*) (*OldName: M_STRT; Cycle: 5;*) (*V04.05.00.00*)
		bERV_ColdCountry : BOOL; (*SAFETY PLC: From Ventilation - Cold country mode is active*) (*OldName:new PV; Cycle:6;*) (*V04.25.00.00*)
		bERV_Lou_PC_CL : BOOL; (*SAFETY PLC: From Ventilation - Plausibility check for closing the louvres*) (*OldName:new PV; Cycle:6;*) (*V04.25.00.00*)
		bERV_Lou_PC_OP : BOOL; (*SAFETY PLC: From Ventilation - Plausibility check for opening the louvres*) (*OldName:new PV; Cycle:6;*) (*V04.25.00.00*)
		bGV_On : BOOL; (*command open gas valves *) (*OldName: M_GASV; Cycle: 5;*) (*V04.01.00.00*)
		bKnockSig : ARRAY[0..24]OF BOOL; (*SAFI KLS measurement signal error [-]*) (*OldName: new PV; Cycle: 6;*) (*V04.11.00.00*)
		bMsg1120 : BOOL; (*signal failure engine speed measuring*) (*OldName: M_MSDREHZ; Cycle: 5;*) (*V04.01.00.00*)
		bMsg2101 : BOOL; (*signal failure cooling water temperature*) (*OldName: M_MSKWT; Cycle:5;*) (*V04.09.00.00*)
		bMsg2102 : BOOL; (*signal failure engine oil temperature*) (*OldName: M_MSOTP; Cycle: 5;*) (*V04.01.00.00*)
		bReqMaintenance : BOOL; (*group message because of maintenance counter*) (*OldName: WART; Cycle: 5;*) (*V04.00.00.00*)
		bServiceMode : BOOL; (*service mode*) (*OldName: bServiceBegin; Cycle: 5;*) (*V04.04.00.00*)
		bSimWinMOD_Active : BOOL; (*WinMOD simulation active *) (*OldName: new PV; Cycle:5*) (*V04.10.00.00*)
		iCAN_CB_us_ident : UDINT; (*CAN user ident for conrod bearing system*) (*OldName: new PV; Cycle: 5;*) (*V04.03.00.00*)
		iIdx_Gtyp_Dem : INT; (*actual gassort 1..4*) (*OldName: gasart; Cycle: 5;*) (*V04.03.00.00*)
		iIdx_OMSS : INT; (*operationg mode selection switch (0= OFF / 1=Hand / 2= Auto / 3=Test / 4=Spülen)*) (*OldName: BWS_HA; Cycle: 5;*) (*V04.03.00.00*)
		iPassLevel : INT; (*pass level actual*) (*OldName: ucPassLevel; Cycle: 5;*) (*V04.01.00.00*)
		iSt_OpMode : UDINT; (*Engine operation mode*) (*OldName: StopM; Cycle:5*) (*V04.10.00.00*)
		rCust_SparePara : ARRAY[0..200]OF REAL; (*SPS_REZP1 to SPS_REZP200*) (*OldName: SPS_REZP1...; Cycle: 5;*) (*V04.00.02.00*)
		rKnck_Noise : ARRAY[0..24]OF REAL; (*cylinder value for knocking noise [mV]*) (*OldName: Fenst1; Cycle: 6;*) (*V04.11.00.00*)
		rN_EngAct : REAL; (*actual engine Speed [rpm]*) (*OldName: n_ist; Cycle: 5;*) (*V04.00.00.00*)
		rN_EngAct_TC6 : REAL; (*actual engine Speed [rpm]*) (*OldName: n_ist; Cycle: 6;*) (*V04.14.00.00*)
		rPos_TV : REAL; (*throttle valve position [%]*) (*OldName: drkl_y; Cycle: 5;*) (*V04.04.00.00*)
		rPr_Ch_P2s_Avg : REAL; (*average charge pressure p2' [bar]*) (*OldName: new PV; Cycle: 5;*) (*V04.04.00.00*)
		rP_Act_Norm : REAL; (*unfiltered actual power related to rP_Nom [%Pnom]*) (*OldName: ssPowerEx; Cycle: 5;*) (*V04.00.00.00*)
		rP_Ramp_DecGrad_Norm_Gtyp0 : REAL; (*rP_Ramp_DecGrad_Norm value for gas type 0 from EngineController module*)
		tAB2EG : AmmBase2MM; (*AMM structure*) (*OldName: new PV; Cycle: 5;*) (*V04.00.00.00*)
		tCustAnaIn : ARRAY[0..120]OF HALioAi_Type; (*replacement for RAN_KANAL...*) (*OldName: ANA_RAN; Cycle: 5;*) (*V04.00.01.00*)
		tCustDigIn : ARRAY[0..200]OF HALioDi_Type; (*new, reserved for project specific use*) (*OldName: new PV; Cycle: 5;*) (*V04.00.01.00*)
		tDCGA_GV_Open : HALioDo_Type; (*SAFETY PLC: DO open gas valve for decentral gas addition*) (*OldName: new PV; Cycle: 5;*) (*V04.25.00.00*)
		tECWP1Dem : HALioDo_Type; (*SAFETY PLC: DO engine cooling water pump 1 demand *) (*OldName:A_MKWP; Cycle:5*) (*V04.14.00.00*)
		tECWP2Dem : HALioDo_Type; (*SAFETY PLC: DO engine cooling water pump 2 demand *) (*OldName:A_MKWP2; Cycle:5*) (*V04.14.00.00*)
		tECWP_PreH_Dem : HALioDo_Type; (*SAFETY PLC: DO engine cooling water preheating pump demand *) (*OldName:A_VORW; Cycle:5*) (*V04.14.00.00*)
		tEmStop_AUX : HALioDi_Type; (*SAFETY PLC: Emergency stop push button - Auxiliaries control panel*) (*OldName: new PV; Cycle: 5;*) (*V04.25.00.00*)
		tEmStop_CoolRun : HALioDi_Type; (*DI emergency stop with after cool run*) (*OldName: new PV; Cycle: 5;*) (*V04.03.00.00*)
		tEmStop_EGAT : HALioDi_Type; (*SAFETY PLC: Emergency stop push button - Exhaust gas after treatment control panel*) (*OldName: new PV; Cycle: 5;*) (*V04.25.00.00*)
		tEmStop_ENGIA : HALioDi_Type; (*DI emergency stop push button - engine interface panel bank A (+ENGIA)*) (*OldName: new PV; Cycle: 5;*) (*V04.04.00.00*)
		tEmStop_ER1 : HALioDi_Type; (*SAFETY PLC: Emergency stop push button - Engine room button 1*) (*OldName: new PV; Cycle: 5;*) (*V04.25.00.00*)
		tEmStop_ER2 : HALioDi_Type; (*SAFETY PLC: Emergency stop push button - Engine room button 2*) (*OldName: new PV; Cycle: 5;*) (*V04.25.00.00*)
		tEmStop_ER3 : HALioDi_Type; (*SAFETY PLC: Emergency stop push button - Engine room button 3*) (*OldName: new PV; Cycle: 5;*) (*V04.25.00.00*)
		tEmStop_ER4 : HALioDi_Type; (*SAFETY PLC: Emergency stop push button - Engine room button 4*) (*OldName: new PV; Cycle: 5;*) (*V04.25.00.00*)
		tEmStop_EXT : HALioDi_Type; (*SAFETY PLC: Emergency stop push button - External*) (*OldName: new PV; Cycle: 5;*) (*V04.25.00.00*)
		tEmStop_GENI : HALioDi_Type; (*DI emergency stop push button - generator interface panel (+GENI)*) (*OldName: new PV; Cycle: 5;*) (*V04.04.00.00*)
		tEmStop_IP : HALioDi_Type; (*SAFETY PLC: Emergency stop push button - Interlock control panel*) (*OldName: new PV; Cycle: 5;*) (*V04.25.00.00*)
		tEmStop_IS : HALioDi_Type; (*DI emergency stop push button - interlock panel (+IS)*) (*OldName: new PV; Cycle: 5;*) (*V04.04.00.00*)
		tEmStop_JWMI : HALioDi_Type; (*DI emergency stop push button - jacket water module interface panel (+JWMI)*) (*OldName: new PV; Cycle: 5;*) (*V04.04.00.00*)
		tEmStop_M : HALioDi_Type; (*DI emergency stop push button - module interface panel (+M)*) (*OldName: new PV; Cycle: 5;*) (*V04.04.00.00*)
		tEmStop_MC : HALioDi_Type; (*DI emergency stop push button - module control panel (+A/+MC)*) (*OldName: new PV; Cycle: 5;*) (*V04.04.00.00*)
		tEmStop_MCP : HALioDi_Type; (*SAFETY PLC: Emergency stop push button - Master control panel*) (*OldName: new PV; Cycle: 5;*) (*V04.25.00.00*)
		tEmStop_OILMI : HALioDi_Type; (*DI emergency stop push button - oil module interface panel (+OILMI)*) (*OldName: new PV; Cycle: 5;*) (*V04.04.00.00*)
		tEmStop_PCGC : HALioDi_Type; (*SAFETY PLC: Emergency stop push button - Prechamber gas compressor*) (*OldName: new PV; Cycle: 5;*) (*V04.25.00.00*)
		tEmStop_SCR : HALioDi_Type; (*DI emergency stop push button - exhaust gas after treatment control panel (+SCR)*) (*OldName: new PV; Cycle: 5;*) (*V04.04.00.00*)
		tEmStop_ST : HALioDi_Type; (*DI emergency stop push button - master control panel (+ST)*) (*OldName: new PV; Cycle: 5;*) (*V04.04.00.00*)
		tEmStop_TCMI : HALioDi_Type; (*DI emergency stop push button - turbocharger module interface panel (+TCMI)*) (*OldName: new PV; Cycle: 5;*) (*V04.04.00.00*)
		tEmStop_TCMSCAV : HALioDi_Type; (*DI emergency stop push button - exhaust gas scavenging system (+TCMSCAV)*) (*OldName: new PV; Cycle: 5;*) (*V04.07.00.00*)
		tEmStop_TR : HALioDi_Type; (*SAFETY PLC: Emergency stop push button - Thermal reactor control panel*) (*OldName: new PV; Cycle: 5;*) (*V04.25.00.00*)
		tEmStop_TS : HALioDi_Type; (*DI emergency stop push button - thermal reactor control panel (+TS)*) (*OldName: new PV; Cycle: 5;*) (*V04.04.00.00*)
		tEng_Run : HALioDo_Type; (*engine is running*) (*OldName: M_BTRB; Cycle: 5;*) (*V04.00.00.00*)
		tEOP1AC_Dem : HALioDo_Type; (*SAFETY PLC: DO engine oil pump 1 AC (M.03-P-002)*) (*OldName:DO_EOP1AC; Cycle:5*) (*V04.14.00.00*)
		tEOP1DC_Dem : HALioDo_Type; (*SAFETY PLC: DO engine oil pump 1 DC (M.03-P-003)*) (*OldName:DO_EOP1DC; Cycle:5*) (*V04.14.00.00*)
		tERV_INL1_Fan_Run : HALioDi_Type; (*SAFETY PLC: DI engine room ventilation - Inlet air group 1 - Fan is operating*) (*OldName:new PV; Cycle:6;*) (*V04.25.00.00*)
		tERV_INL1_Lou_CL : HALioDi_Type; (*SAFETY PLC: DI engine room ventilation - Inlet air group 1 - Louvre closed*) (*OldName:new PV; Cycle:6;*) (*V04.25.00.00*)
		tERV_INL1_Lou_OP : HALioDi_Type; (*SAFETY PLC: DI engine room ventilation - Inlet air group 1 - Louvre opened*) (*OldName:new PV; Cycle:6;*) (*V04.25.00.00*)
		tERV_INL2_Fan_Run : HALioDi_Type; (*SAFETY PLC: DI engine room ventilation - Inlet air group 2 - Fan is operating*) (*OldName:new PV; Cycle:6;*) (*V04.25.00.00*)
		tERV_INL2_Lou_CL : HALioDi_Type; (*SAFETY PLC: DI engine room ventilation - Inlet air group 2 - Louvre closed*) (*OldName:new PV; Cycle:6;*) (*V04.25.00.00*)
		tERV_INL2_Lou_OP : HALioDi_Type; (*SAFETY PLC: DI engine room ventilation - Inlet air group 2 - Louvre opened*) (*OldName:new PV; Cycle:6;*) (*V04.25.00.00*)
		tERV_INL3_Fan_Run : HALioDi_Type; (*SAFETY PLC: DI engine room ventilation - Inlet air group 3 - Fan is operating*) (*OldName:new PV; Cycle:6;*) (*V04.25.00.00*)
		tERV_INL3_Lou_CL : HALioDi_Type; (*SAFETY PLC: DI engine room ventilation - Inlet air group 3 - Louvre closed*) (*OldName:new PV; Cycle:6;*) (*V04.25.00.00*)
		tERV_INL3_Lou_OP : HALioDi_Type; (*SAFETY PLC: DI engine room ventilation - Inlet air group 3 - Louvre opened*) (*OldName:new PV; Cycle:6;*) (*V04.25.00.00*)
		tERV_INL4_Fan_Run : HALioDi_Type; (*SAFETY PLC: DI engine room ventilation - Inlet air group 4 - Fan is operating*) (*OldName:new PV; Cycle:6;*) (*V04.25.00.00*)
		tERV_INL4_Lou_CL : HALioDi_Type; (*SAFETY PLC: DI engine room ventilation - Inlet air group 4 - Louvre closed*) (*OldName:new PV; Cycle:6;*) (*V04.25.00.00*)
		tERV_INL4_Lou_OP : HALioDi_Type; (*SAFETY PLC: DI engine room ventilation - Inlet air group 4 - Louvre opened*) (*OldName:new PV; Cycle:6;*) (*V04.25.00.00*)
		tERV_INL5_Fan_Run : HALioDi_Type; (*SAFETY PLC: DI engine room ventilation - Inlet air group 5 - Fan is operating*) (*OldName:new PV; Cycle:6;*) (*V04.25.00.00*)
		tERV_INL5_Lou_CL : HALioDi_Type; (*SAFETY PLC: DI engine room ventilation - Inlet air group 5 - Louvre closed*) (*OldName:new PV; Cycle:6;*) (*V04.25.00.00*)
		tERV_INL5_Lou_OP : HALioDi_Type; (*SAFETY PLC: DI engine room ventilation - Inlet air group 5 - Louvre opened*) (*OldName:new PV; Cycle:6;*) (*V04.25.00.00*)
		tERV_INL6_Fan_Run : HALioDi_Type; (*SAFETY PLC: DI engine room ventilation - Inlet air group 6 - Fan is operating*) (*OldName:new PV; Cycle:6;*) (*V04.25.00.00*)
		tERV_INL6_Lou_CL : HALioDi_Type; (*SAFETY PLC: DI engine room ventilation - Inlet air group 6 - Louvre closed*) (*OldName:new PV; Cycle:6;*) (*V04.25.00.00*)
		tERV_INL6_Lou_OP : HALioDi_Type; (*SAFETY PLC: DI engine room ventilation - Inlet air group 6 - Louvre opened*) (*OldName:new PV; Cycle:6;*) (*V04.25.00.00*)
		tERV_OTL1_Lou_CL : HALioDi_Type; (*SAFETY PLC: DI engine room ventilation - Outlet air group 1 - Louvre closed*) (*OldName:new PV; Cycle:6;*) (*V04.25.00.00*)
		tERV_OTL1_Lou_OP : HALioDi_Type; (*SAFETY PLC: DI engine room ventilation - Outlet air group 1 - Louvre opened*) (*OldName:new PV; Cycle:6;*) (*V04.25.00.00*)
		tERV_OTL2_Lou_CL : HALioDi_Type; (*SAFETY PLC: DI engine room ventilation - Outlet air group 2 - Louvre closed*) (*OldName:new PV; Cycle:6;*) (*V04.25.00.00*)
		tERV_OTL2_Lou_OP : HALioDi_Type; (*SAFETY PLC: DI engine room ventilation - Outlet air group 2 - Louvre opened*) (*OldName:new PV; Cycle:6;*) (*V04.25.00.00*)
		tERV_OTL3_Lou_CL : HALioDi_Type; (*SAFETY PLC: DI engine room ventilation - Outlet air group 3 - Louvre closed*) (*OldName:new PV; Cycle:6;*) (*V04.25.00.00*)
		tERV_OTL3_Lou_OP : HALioDi_Type; (*SAFETY PLC: DI engine room ventilation - Outlet air group 3 - Louvre opened*) (*OldName:new PV; Cycle:6;*) (*V04.25.00.00*)
		tERV_OTL4_Lou_CL : HALioDi_Type; (*SAFETY PLC: DI engine room ventilation - Outlet air group 4 - Louvre closed*) (*OldName:new PV; Cycle:6;*) (*V04.25.00.00*)
		tERV_OTL4_Lou_OP : HALioDi_Type; (*SAFETY PLC: DI engine room ventilation - Outlet air group 4 - Louvre opened*) (*OldName:new PV; Cycle:6;*) (*V04.25.00.00*)
		tERV_OTL5_Lou_CL : HALioDi_Type; (*SAFETY PLC: DI engine room ventilation - Outlet air group 5 - Louvre closed*) (*OldName:new PV; Cycle:6;*) (*V04.25.00.00*)
		tERV_OTL5_Lou_OP : HALioDi_Type; (*SAFETY PLC: DI engine room ventilation - Outlet air group 5 - Louvre opened*) (*OldName:new PV; Cycle:6;*) (*V04.25.00.00*)
		tERV_OTL6_Lou_CL : HALioDi_Type; (*SAFETY PLC: DI engine room ventilation - Outlet air group 6 - Louvre closed*) (*OldName:new PV; Cycle:6;*) (*V04.25.00.00*)
		tERV_OTL6_Lou_OP : HALioDi_Type; (*SAFETY PLC: DI engine room ventilation - Outlet air group 6 - Louvre opened*) (*OldName:new PV; Cycle:6;*) (*V04.25.00.00*)
		tER_DoorClosed : HALioDi_Type; (*SAFETY PLC: DI engine room doors closed*) (*OldName:DI_ER_DoorClosed; Cycle:5;*) (*V04.25.00.00*)
		tGCB_Off : HALioDi_Type; (*SAFETY PLC: DI generator circuit breaker OPENED *) (*OldName: DI_GCB_OFF; Cycle:5;*) (*V04.14.00.00*)
		tGCB_On : HALioDi_Type; (*generator circuit breaker CLOSED*) (*OldName: GCB_ON; Cycle: 5;*) (*V04.00.00.00*)
		tGCB_RUC : HALioDo_Type; (*SAFETY PLC: DO generator circuit breaker release undervoltage coil*) (*OldName: USP; Cycle: 5;*) (*V04.14.00.00*)
		tGV1_Open : HALioDo_Type; (*SAFETY PLC: DO open gas valve 1*) (*OldName:GASV1; Cycle:5*) (*V04.14.00.00*)
		tGV2_Open : HALioDo_Type; (*SAFETY PLC: DO open gas valve 2*) (*OldName:GASV2; Cycle:5*) (*V04.14.00.00*)
		tGV3_Open : HALioDo_Type; (*SAFETY PLC: DO open gas valve 3*) (*OldName: new PV; Cycle: 5;*) (*V04.14.00.00*)
		tGV4_Open : HALioDo_Type; (*SAFETY PLC: DO open gas valve 4*) (*OldName: new PV; Cycle: 5;*) (*V04.14.00.00*)
		tIgn_Run_Hal : HALioDi_Type; (*SAFETY PLC: DI: Ignition system running*) (*OldName:ZIB;Cycle:2;*) (*V04.14.00.00*)
		tImp_OpHour : HALioDo_Type; (*impulse for operation hour counter *) (*OldName: M_BTRIMP, H_IMP; Cycle: 5;*) (*V04.04.00.00*)
		tMonitoringOn : HALioDo_Type; (*monitoring on pulse(safety loop)*) (*OldName: UW_EIN; Cycle: 5;*) (*V04.00.00.00*)
		tPB2MM : ParaBase2MM_type; (*para structure*) (*OldName: new PV; Cycle: 5;*) (*V04.00.00.00*)
		tPr_Baro : HALioAi_Type; (*barometric pressure [bar (abs)] (M.05-PI-100)*) (*OldName: AI_p_Baro; Cycle: 5;*) (*V04.03.00.00*)
		tPr_CC : HALioAi_Type; (*crankcase pressure [mbar]*) (*OldName: AI_KGD; Cycle: 6;*) (*V04.11.00.00*)
		tRel_Sync_Load : HALioDo_Type; (*release of synchronisation and load*) (*OldName: SY_LFG; Cycle: 5;*) (*V04.00.00.00*)
		tSafetyLoop_EmStop : HALioDi_Type; (*safety loop - emergency stop push button*) (*OldName: DI_SIS; Cycle: 5;*) (*V04.00.00.00*)
		tSafetyLoop_Eng : HALioDi_Type; (*safety loop - engine*) (*OldName: RUHE, DI_RUHE_TC1; Cycle: 5;*) (*V04.00.00.00*)
		tSL_TS_ECW : HALioDi_Type; (*SAFETY PLC: DI Safety loop - Engine cooling water temperature switch - Engine outlet (M.04-TI-001)*) (*OldName: new PV; Cycle: 6;*) (*V04.25.00.00*)
		tSL_TS_HW_Su_Unit : HALioDi_Type; (*SAFETY PLC: DI Safety loop - Heating water supply temperature switch - Unit (M.06-TI-003)*) (*OldName: new PV; Cycle: 6;*) (*V04.25.00.00*)
		tT_CBearing_Hi : HALioDi_Type; (*conrod bearing temperature high - DI from kongsberg*) (*OldName: new PV; Cycle: 5;*) (*V04.03.00.00*)
		tT_CBearing_HiHi : HALioDi_Type; (*conrod bearing temperature high high - DI from kongsberg*) (*OldName: new PV; Cycle: 5;*) (*V04.03.00.00*)
		tT_ECW : HALioAi_Type; (*engine cooling water temperature [degC] (M.04-TI-001)*) (*OldName: ANA.KWT; Cycle: 5;*) (*V04.01.00.00*)
		tT_EO : HALioAi_Type; (*oil temperature [degC] (M.03-TI-001)*) (*OldName: ANA.OTP; Cycle: 5;*) (*V04.01.00.00*)
		tT_MBearing : ARRAY[0..11]OF HALioAi_Type; (*main bearing temperatures [degC] (E.00-TI-201 - E.00-TI-211)*) (*OldName: new PV; Cycle: 5;*) (*V04.03.00.00*)
		tU_Gen_Exc : HALioAi_Type; (*actual excitation voltage signal, filtered and scaled [V]*) (*OldName: ANA.ERREG; Cycle: 5;*) (*V04.01.00.00*)
	END_STRUCT;
	OUT_EG_Struct : 	STRUCT 
		bAMM_Pr_Baro_Internal : BOOL; (*warning - value for barometric pressure not valid*) (*OldName: new PV; Cycle: 5;*) (*V04.05.00.00*)
		bERV_PC_Forced : BOOL; (*SAFETY PLC: Forced ERV (Engine room ventilation) plausibility check*) (*OldName: new PV; Cycle: 5;*) (*V04.25.00.00*)
		bMsg1026 : BOOL; (*shutdown failure*) (*OldName: M_ANSTAB; Cycle: 5;*) (*V04.00.00.00*)
		bMsg1026_Test : BOOL; (*shutdown failure - TEST*) (*OldName: new PV; Cycle: 5;*) (*V04.00.00.00*)
		bMsg1031 : BOOL; (*safety loop - emergency stop push button*) (*OldName: M_SIS; Cycle: 5;*) (*V04.00.00.00*)
		bMsg1056 : BOOL; (*safety loop - engine*) (*OldName: M_RUHE; Cycle: 5;*) (*V04.00.00.00*)
		bRel_HWP_Dem : BOOL; (*Release heating water pump from SAFETY PLC*) (*OldName: new PV; Cycle: 5;*) (*V04.25.00.00*)
		bSafeOUT_DCGA_SafeDevOK : BOOL; (*SAFETY PLC: Gas safety device decentral gas addition OK*) (*OldName: new PV; Cycle: 5;*) (*V04.25.00.00*)
		bSafeOUT_DCGA_SD_Dem_PS : BOOL; (*SAFETY PLC: Demand for gas safety device DCGA - Physical state*) (*OldName: new PV; Cycle: 5;*) (*V04.25.00.00*)
		bSafeOUT_GT1_SafeDevOK : BOOL; (*SAFETY PLC: Gas safety device 1 OK*) (*OldName: new PV; Cycle: 5;*) (*V04.25.00.00*)
		bSafeOUT_GT1_SD_Dem_PS : BOOL; (*SAFETY PLC: Demand for gas safety device 1 - Physical state*) (*OldName: new PV; Cycle: 5;*) (*V04.25.00.00*)
		bSafeOUT_GT2_SafeDevOK : BOOL; (*SAFETY PLC: Gas safety device 2 OK*) (*OldName: new PV; Cycle: 5;*) (*V04.25.00.00*)
		bSafeOUT_GT2_SD_Dem_PS : BOOL; (*SAFETY PLC: Demand for gas safety device 2 - Physical state*) (*OldName: new PV; Cycle: 5;*) (*V04.25.00.00*)
		bSafeOUT_GT3_SafeDevOK : BOOL; (*SAFETY PLC: Gas safety device 3 OK*) (*OldName: new PV; Cycle: 5;*) (*V04.25.00.00*)
		bSafeOUT_GT3_SD_Dem_PS : BOOL; (*SAFETY PLC: Demand for gas safety device 3 - Physical state*) (*OldName: new PV; Cycle: 5;*) (*V04.25.00.00*)
		bSafeOUT_GT4_SafeDevOK : BOOL; (*SAFETY PLC: Gas safety device 4 OK*) (*OldName: new PV; Cycle: 5;*) (*V04.25.00.00*)
		bSafeOUT_GT4_SD_Dem_PS : BOOL; (*SAFETY PLC: Demand for gas safety device 4 - Physical state*) (*OldName: new PV; Cycle: 5;*) (*V04.25.00.00*)
		bSafeOUT_GV_Open : BOOL; (*SAFETY PLC: At least one gas valve opened*) (*OldName: new PV; Cycle: 5;*) (*V04.25.00.00*)
		bSafeOUT_Purge_OK : BOOL; (*SAFETY PLC: Purge state OK*) (*OldName: new PV; Cycle: 5;*) (*V04.25.00.00*)
		bSafeOUT_SafetyLoop_EmStop : BOOL; (*SAFETY PLC: Safety loop - Emergency stop push button OK*) (*OldName: new PV; Cycle: 5;*) (*V04.25.00.00*)
		bSafeOUT_SafetyLoop_Eng : BOOL; (*SAFETY PLC: Safety loop - Engine OK*) (*OldName: new PV; Cycle: 5;*) (*V04.25.00.00*)
		bSafetyPLC_Active : BOOL; (*SAFETY PLC: SafetyPLC is active*) (*OldName: new PV; Cycle: 5;*) (*V04.14.00.00*)
		rPr_Baro_Internal : REAL; (*internal value for barometric pressure [bar (abs)]*) (*OldName: new PV; Cycle: 5;*) (*V04.03.00.00*)
		rVol_PurgeAir_SafeOUT : REAL; (*SAFETY PLC: Purge air volume [l]*) (*OldName: new PV; Cycle: 5;*) (*V04.25.00.00*)
		rT_CBearing : ARRAY[0..24]OF REAL; (*conrod bearing temperature [degC]*) (*OldName: new PV; Cycle: 5;*) (*V04.03.00.00*)
		rT_MBearing : ARRAY[0..11]OF REAL; (*filtered main bearing temperature [degC]*) (*OldName: new PV; Cycle: 5;*) (*V04.03.00.00*)
		tEG2AB : MM2AmmBase; (*AMM structure*) (*OldName: new PV; Cycle: 5;*) (*V04.00.00.00*)
		tEG2PB : MM2ParaBase_type; (*para structure*) (*OldName: new PV; Cycle: 5;*) (*V04.00.00.00*)
	END_STRUCT;
	MM2VIS_Struct : 	STRUCT 
		bMsg1026 : BOOL; (*shutdown failure*) (*OldName: M_ANSTAB; Cycle: 5;*) (*V04.00.00.00*)
		bMsg1031 : BOOL; (*safety loop - emergency stop push button*) (*OldName: M_SIS; Cycle: 5;*) (*V04.00.00.00*)
		bMsg1056 : BOOL; (*safety loop - engine*) (*OldName: M_RUHE; Cycle: 5;*) (*V04.00.00.00*)
		bMsg1168 : BOOL; (*group message because of maintenance counter*) (*OldName: M_WART; Cycle: 5;*) (*V04.00.00.00*)
		bMsg2190 : BOOL; (*emergency stop push button - module control panel (+A/+MC)*) (*OldName: new PV; Cycle: 5;*) (*V04.04.00.00*)
		bMsg2191 : BOOL; (*emergency stop push button - module interface panel (+M)*) (*OldName: new PV; Cycle: 5;*) (*V04.04.00.00*)
		bMsg2192 : BOOL; (*emergency stop push button - master control panel (+ST)*) (*OldName: new PV; Cycle: 5;*) (*V04.04.00.00*)
		bMsg2193 : BOOL; (*emergency stop push button - interlock panel (+IS)*) (*OldName: new PV; Cycle: 5;*) (*V04.04.00.00*)
		bMsg2194 : BOOL; (*emergency stop push button - thermal reactor control panel (+TS)*) (*OldName: new PV; Cycle: 5;*) (*V04.04.00.00*)
		bMsg2195 : BOOL; (*emergency stop push button - generator interface panel (+GENI)*) (*OldName: new PV; Cycle: 5;*) (*V04.04.00.00*)
		bMsg2196 : BOOL; (*emergency stop push button - engine interface panel bank A (+ENGIA)*) (*OldName: new PV; Cycle: 5;*) (*V04.04.00.00*)
		bMsg2197 : BOOL; (*emergency stop push button - turbocharger module interface panel (+TCMI)*) (*OldName: new PV; Cycle: 5;*) (*V04.04.00.00*)
		bMsg2198 : BOOL; (*emergency stop push button - jacket water module interface panel (+JWMI)*) (*OldName: new PV; Cycle: 5;*) (*V04.04.00.00*)
		bMsg2199 : BOOL; (*emergency stop push button - oil module interface panel (+OILMI)*) (*OldName: new PV; Cycle: 5;*) (*V04.04.00.00*)
		bMsg2200 : BOOL; (*emergency stop push button - exhaust gas after treatment control panel (+SCR)*) (*OldName: new PV; Cycle: 5;*) (*V04.04.00.00*)
		bMsg2227 : BOOL; (*measuring signal failure main bearing temperature --> NOT USED*) (*OldName: ALM[2227].Q; Cycle: 5;*) (*V04.03.00.00*)
		bMsg2228 : BOOL; (*main bearing temperature high*) (*OldName: ALM[2228].Q; Cycle: 5;*) (*V04.03.00.00*)
		bMsg2229 : BOOL; (*conrod bearing montoring CAN communication failure*) (*OldName: ALM[2229].Q; Cycle: 5;*) (*V04.03.00.00*)
		bMsg2230 : BOOL; (*conrod bearing temperature high*) (*OldName: ALM[2230].Q; Cycle: 5;*) (*V04.03.00.00*)
		bMsg2232 : BOOL; (*measuring signal failure barometric pressure *) (*OldName: ALM[2232].Q; Cycle: 5;*) (*V04.03.00.00*)
		bMsg2270 : BOOL; (*measuring signal failure conrod bearing temperature --> NOT USED*) (*OldName: ALM[2270].Q; Cycle: 5;*) (*V04.03.00.00*)
		bMsg2285 : BOOL; (*main bearing temperature - positive deviation from average value*) (*OldName: ALM[2285].Q; Cycle: 5;*) (*V04.03.00.00*)
		bMsg2286 : BOOL; (*conrod bearing temperature - positive deviation from average value*) (*OldName: ALM[2286].Q; Cycle: 5;*) (*V04.03.00.00*)
		bMsg2300 : BOOL; (*idle friction too high*) (*OldName: new PV; Cycle: 5;*) (*V04.04.00.00*)
		bMsg2362 : BOOL; (*PU scuffing detection - alarm*) (*OldName: new PV; Cycle: 6;*) (*V04.11.00.00*)
		bMsg2383 : BOOL; (*SAFETY - Exhaust gas backpressure high*) (*SAFETY PLC*) (*V04.25.00.00*)
		bMsg2384 : BOOL; (*SAFETY - Speed deviation to ignition speed*) (*SAFETY PLC*) (*V04.14.00.00*)
		bMsg2385 : BOOL; (*SAFETY - Ignition system failure*) (*SAFETY PLC*) (*V04.14.00.00*)
		bMsg2386 : BOOL; (*SAFETY - Oil pressure minimum*) (*SAFETY PLC*) (*V04.14.00.00*)
		bMsg2387 : BOOL; (*SAFETY - Oil pressure measuring signal failure*) (*SAFETY PLC*) (*V04.14.00.00*)
		bMsg2388 : BOOL; (*SAFETY - Oil pressure implausible value*) (*SAFETY PLC*) (*V04.14.00.00*)
		bMsg2389 : BOOL; (*SAFETY - Oil pressure deviation between the sensors*) (*SAFETY PLC*) (*V04.14.00.00*)
		bMsg2390 : BOOL; (*SAFETY - Oil pressure maximum (sensor drift)*) (*SAFETY PLC*) (*V04.14.00.00*)
		bMsg2391 : BOOL; (*SAFETY - Oil pressure sensor value frozen*) (*SAFETY PLC*) (*V04.14.00.00*)
		bMsg2392 : BOOL; (*SAFETY - Oil pressure after pump maximum*) (*SAFETY PLC*) (*V04.14.00.00*)
		bMsg2393 : BOOL; (*SAFETY - Oil pressure after pump measuring signal failure*) (*SAFETY PLC*) (*V04.14.00.00*)
		bMsg2394 : BOOL; (*SAFETY - Oil pressure after pump implausible value*) (*SAFETY PLC*) (*V04.14.00.00*)
		bMsg2395 : BOOL; (*SAFETY - Oil pressure after pump sensor value frozen*) (*SAFETY PLC*) (*V04.14.00.00*)
		bMsg2396 : BOOL; (*SAFETY - Engine cooling water pressure minimum*) (*SAFETY PLC*) (*V04.14.00.00*)
		bMsg2397 : BOOL; (*SAFETY - Engine cooling water pressure measuring signal failure*) (*SAFETY PLC*) (*V04.14.00.00*)
		bMsg2398 : BOOL; (*SAFETY - Engine cooling water pressure deviation between the sensors*) (*SAFETY PLC*) (*V04.14.00.00*)
		bMsg2542 : BOOL; (*main bearing temperature high*) (*OldName: ALM[2542].Q; Cycle: 5;*) (*V04.03.00.00*)
		bMsg2544 : BOOL; (*conrod bearing temperature high*) (*OldName: ALM[2544].Q; Cycle: 5;*) (*V04.03.00.00*)
		bMsg2552 : BOOL; (*warning barometric pressure low *) (*OldName: ALM[2552].Q; Cycle: 5;*) (*V04.03.00.00*)
		bMsg2553 : BOOL; (*warning barometric pressure high *) (*OldName: ALM[2553].Q; Cycle: 5;*) (*V04.03.00.00*)
		bMsg2561 : BOOL; (*barometric pressure unequal gas rail pressure - lockout start sequence *) (*OldName: p_GT1_ok; Cycle: 5;*) (*V04.03.00.00*)
		bMsg2790 : BOOL; (*measuring signal failure conrod bearing temperature*) (*OldName: new PV; Cycle: 5;*) (*V04.04.00.00*)
		bMsg2794 : BOOL; (*conrod bearing temperature calibration unsuccessful*) (*OldName: new PV; Cycle: 5;*) (*V04.04.00.00*)
		bMsg2804 : BOOL; (*measuring signal failure main bearing temperature*) (*OldName: new PV; Cycle: 5;*) (*V04.03.00.00*)
		bMsg2805 : BOOL; (*main bearing temperature high*) (*OldName: new PV; Cycle: 5;*) (*V04.03.00.00*)
		bMsg2806 : BOOL; (*measuring signal failure conrod bearing temperature*) (*OldName: new PV; Cycle: 5;*) (*V04.03.00.00*)
		bMsg2807 : BOOL; (*conrod bearing temperature high*) (*OldName: new PV; Cycle: 5;*) (*V04.03.00.00*)
		bMsg2822 : BOOL; (*conrod bearing signal intensity minimum*) (*OldName: new PV; Cycle: 5;*) (*V04.03.00.00*)
		bMsg2904 : BOOL; (*main bearing temperature - positive MEDIAN deviation maximum*) (*OldName: new PV; Cycle: 5;*) (*V04.04.00.00*)
		bMsg2905 : BOOL; (*conrod bearing temperature - positive MEDIAN deviation maximum*) (*OldName: new PV; Cycle: 5;*) (*V04.04.00.00*)
		bMsg2909 : BOOL; (*conrod bearing temperature calibration successful*) (*OldName: new PV; Cycle: 5;*) (*V04.05.00.00*)
		bMsg2958 : BOOL; (*main bearing temperature - negative MEDIAN deviation maximum*) (*OldName: new PV; Cycle: 5;*) (*V04.05.01.00*)
		bMsg2959 : BOOL; (*conrod bearing temperature - negative MEDIAN deviation maximum*) (*OldName: new PV; Cycle: 5;*) (*V04.05.01.00*)
		bMsg2981 : BOOL; (*PU scuffing detection - operating message*) (*OldName: new PV; Cycle: 6;*) (*V04.11.00.00*)
		bMsg3368 : BOOL; (*Slow down time too short*) (*OldName: new PV; Cycle: 5;*) (*V04.01.00.00*)
		bMsg3378 : BOOL; (*conrod bearing temperature calibration unsuccessful*) (*OldName: new PV; Cycle: 5;*) (*V04.03.00.00*)
		bMsg3396 : BOOL; (*Emergency stop with after cool run*) (*OldName: new PV; Cycle: 5;*) (*V04.03.00.00*)
		bMsg3449 : BOOL; (*warning Gas pressure before gas compressor measuring signal failure *) (*OldName: new PV; Cycle: 5;*) (*V04.03.00.00*)
		bMsg3559 : BOOL; (*warning conrod bearing signal intensity minimum*) (*OldName: new PV; Cycle: 5;*) (*V04.03.00.00*)
		bMsg9038 : BOOL; (*emergency stop push button - exhaust gas scavenging system control panel (+TCMSCAV)*) (*OldName: new PV; Cycle: 5;*) (*V04.07.00.00*)
		bMsg9217 : BOOL; (*measuring signal failure main bearing temperature*) (*OldName: new PV; Cycle: 5;*) (*V04.05.01.00*)
		bMsg9218 : BOOL; (*Main bearing temperature - negative deviation from average value*) (*OldName: new PV; Cycle: 5;*) (*V04.05.01.00*)
		bMsg9219 : BOOL; (*Conrod bearing temperature - negative deviation from average value*) (*OldName: new PV; Cycle: 5;*) (*V04.05.01.00*)
		bMsg9408 : BOOL; (*SAFETY - Engine cooling water pressure maximum (sensor drift)*) (*SAFETY PLC*) (*V04.14.00.00*)
		bMsg9409 : BOOL; (*SAFETY - Engine cooling water pressure sensor value frozen*) (*SAFETY PLC*) (*V04.14.00.00*)
		bMsg9410 : BOOL; (*SAFETY - Engine cooling water pressure after pump maximum*) (*SAFETY PLC*) (*V04.14.00.00*)
		bMsg9411 : BOOL; (*SAFETY - Engine cooling water pressure after pump measuring signal failure*) (*SAFETY PLC*) (*V04.14.00.00*)
		bMsg9412 : BOOL; (*SAFETY - Engine cooling water pressure after pump sensor value frozen*) (*SAFETY PLC*) (*V04.14.00.00*)
		bMsg9413 : BOOL; (*SAFETY - Generator circuit breaker opening failure*) (*SAFETY PLC*) (*V04.14.00.00*)
		bMsg9414 : BOOL; (*SAFETY - Generator circuit breaker position feedback error*) (*SAFETY PLC*) (*V04.14.00.00*)
		bMsg9415 : BOOL; (*SAFETY - Generator overload/short circuit*) (*SAFETY PLC*) (*V04.14.00.00*)
		bMsg9416 : BOOL; (*SAFETY - Generator protection trip*) (*SAFETY PLC*) (*V04.14.00.00*)
		bMsg9417 : BOOL; (*SAFETY - Collective fault in room ventilation*) (*SAFETY PLC*) (*V04.25.00.00*)
		bMsg9418 : BOOL; (*SAFETY - Emergency stop push button - Module interface panel*) (*SAFETY PLC*) (*V04.14.00.00*)
		bMsg9419 : BOOL; (*SAFETY - Emergency stop push button*) (*SAFETY PLC*) (*V04.14.00.00*)
		bMsg9420 : BOOL; (*SAFETY - Safety loop 1 tripped - Module control panel*) (*SAFETY PLC*) (*V04.14.00.00*)
		bMsg9421 : BOOL; (*SAFETY - Failure gas train 1*) (*SAFETY PLC*) (*V04.14.00.00*)
		bMsg9422 : BOOL; (*SAFETY - Failure gas train 2*) (*SAFETY PLC*) (*V04.14.00.00*)
		bMsg9423 : BOOL; (*SAFETY - Failure gas train 3*) (*SAFETY PLC*) (*V04.14.00.00*)
		bMsg9424 : BOOL; (*SAFETY - Failure gas train 4*) (*SAFETY PLC*) (*V04.14.00.00*)
		bMsg9425 : BOOL; (*SAFETY - Safety functions module interface panel - output not valid*) (*SAFETY PLC*) (*V04.14.00.00*)
		bMsg9426 : BOOL; (*SAFETY - Safety functions module control panel - output not valid*) (*SAFETY PLC*) (*V04.14.00.00*)
		bMsg9427 : BOOL; (*SAFETY - Engine type mismatch*) (*SAFETY PLC*) (*V04.14.00.00*)
		bMsg9428 : BOOL; (*SAFETY - Room ventilation failure - Plausibility check pending*) (*SAFETY PLC*) (*V04.25.00.00*)
		bMsg9429 : BOOL; (*SAFETY - Software handshake not valid*) (*SAFETY PLC*) (*V04.14.00.00*)
		bMsg9430 : BOOL; (*SAFETY - Software not valid - Wrong CRC checksum*) (*SAFETY PLC*) (*V04.14.00.00*)
		bMsg9431 : BOOL; (*SAFETY - Parameter mismatch*) (*SAFETY PLC*) (*V04.14.00.00*)
		bMsg9433 : BOOL; (*SAFETY - Malfunction of safe communication channel *) (*SAFETY PLC*) (*V04.14.00.00*)
		bMsg9434 : BOOL; (*SAFETY - Engine cooling water pump - Difference pressure minimum*) (*SAFETY PLC*) (*V04.25.00.00*)
		bMsg9437 : BOOL; (*SAFETY - Scavenging flap not closed*) (*SAFETY PLC*) (*V04.25.00.00*)
		bMsg9438 : BOOL; (*SAFETY - Scavenging flap failure*) (*SAFETY PLC*) (*V04.25.00.00*)
		bMsg9439 : BOOL; (*SAFETY - Engine cooling water temperature after engine maximum*) (*SAFETY PLC*) (*V04.25.00.00*)
		bMsg9440 : BOOL; (*SAFETY - Heating water supply temperature unit maximum*) (*SAFETY PLC*) (*V04.25.00.00*)
		bMsg9441 : BOOL; (*SAFETY - Customer heating water circuit failure*) (*SAFETY PLC*) (*V04.25.00.00*)
		bMsg9442 : BOOL; (*SAFETY - High temperature heating water level minimum*) (*SAFETY PLC*) (*V04.25.00.00*)
		bMsg9443 : BOOL; (*SAFETY - High temperature heating water pressure 1 maximum*) (*SAFETY PLC*) (*V04.25.00.00*)
		bMsg9444 : BOOL; (*SAFETY - High temperature heating water pressure 2 maximum*) (*SAFETY PLC*) (*V04.25.00.00*)
		bMsg9445 : BOOL; (*SAFETY - High temperature heating water pressure 1 minimum*) (*SAFETY PLC*) (*V04.25.00.00*)
		bMsg9446 : BOOL; (*SAFETY - High temperature heating water pressure 2 minimum*) (*SAFETY PLC*) (*V04.25.00.00*)
		bMsg9447 : BOOL; (*SAFETY - High temperature heating water temperature 1 maximum*) (*SAFETY PLC*) (*V04.25.00.00*)
		bMsg9448 : BOOL; (*SAFETY - High temperature heating water temperature 2 maximum*) (*SAFETY PLC*) (*V04.25.00.00*)
		bMsg9449 : BOOL; (*SAFETY - High temperature heating water flow minimum*) (*SAFETY PLC*) (*V04.25.00.00*)
		bMsg9450 : BOOL; (*SAFETY - Low temperature heating water level minimum*) (*SAFETY PLC*) (*V04.25.00.00*)
		bMsg9451 : BOOL; (*SAFETY - Low temperature heating water pressure 1 maximum*) (*SAFETY PLC*) (*V04.25.00.00*)
		bMsg9452 : BOOL; (*SAFETY - Low temperature heating water pressure 2 maximum*) (*SAFETY PLC*) (*V04.25.00.00*)
		bMsg9453 : BOOL; (*SAFETY - Low temperature heating water pressure 1 minimum*) (*SAFETY PLC*) (*V04.25.00.00*)
		bMsg9454 : BOOL; (*SAFETY - Low temperature heating water pressure 2 minimum*) (*SAFETY PLC*) (*V04.25.00.00*)
		bMsg9455 : BOOL; (*SAFETY - Low temperature heating water temperature 1 maximum*) (*SAFETY PLC*) (*V04.25.00.00*)
		bMsg9456 : BOOL; (*SAFETY - Low temperature heating water temperature 2 maximum*) (*SAFETY PLC*) (*V04.25.00.00*)
		bMsg9457 : BOOL; (*SAFETY - Low temperature heating water flow minimum*) (*SAFETY PLC*) (*V04.25.00.00*)
		bMsg9458 : BOOL; (*SAFETY - Safety loop 2 tripped - Module control panel*) (*SAFETY PLC*) (*V04.25.00.00*)
		bMsg9459 : BOOL; (*SAFETY - Safety loop tripped - Module interface panel*) (*SAFETY PLC*) (*V04.25.00.00*)
		bMsg9460 : BOOL; (*SAFETY - Emergency stop push button - Module control panel*) (*SAFETY PLC*) (*V04.25.00.00*)
		bMsg9461 : BOOL; (*SAFETY - Emergency stop push button - Engine room button 1*) (*SAFETY PLC*) (*V04.25.00.00*)
		bMsg9462 : BOOL; (*SAFETY - Emergency stop push button - Engine room button 2*) (*SAFETY PLC*) (*V04.25.00.00*)
		bMsg9463 : BOOL; (*SAFETY - Emergency stop push button - Engine room button 3*) (*SAFETY PLC*) (*V04.25.00.00*)
		bMsg9464 : BOOL; (*SAFETY - Emergency stop push button - Engine room button 4*) (*SAFETY PLC*) (*V04.25.00.00*)
		bMsg9465 : BOOL; (*SAFETY - Emergency stop push button - External*) (*SAFETY PLC*) (*V04.25.00.00*)
		bMsg9466 : BOOL; (*SAFETY - Emergency stop push button - Thermal reactor control panel*) (*SAFETY PLC*) (*V04.25.00.00*)
		bMsg9467 : BOOL; (*SAFETY - Emergency stop push button - Interlock control panel*) (*SAFETY PLC*) (*V04.25.00.00*)
		bMsg9468 : BOOL; (*SAFETY - Emergency stop push button - Master control panel*) (*SAFETY PLC*) (*V04.25.00.00*)
		bMsg9469 : BOOL; (*SAFETY - Emergency stop push button - Exhaust gas after treatment control panel*) (*SAFETY PLC*) (*V04.25.00.00*)
		bMsg9470 : BOOL; (*SAFETY - Emergency stop push button - Prechamber gas compressor*) (*SAFETY PLC*) (*V04.25.00.00*)
		bMsg9471 : BOOL; (*SAFETY - Emergency stop push button - Auxiliaries control panel*) (*SAFETY PLC*) (*V04.25.00.00*)
		bMsg9480 : BOOL; (*SAFETY - Room ventilation failure - Doors*) (*SAFETY PLC*) (*V04.25.00.00*)
		bMsg9481 : BOOL; (*SAFETY - Room ventilation failure - Inlet air fan*) (*SAFETY PLC*) (*V04.25.00.00*)
		bMsg9482 : BOOL; (*SAFETY - Room ventilation failure - Inlet air louvre*) (*SAFETY PLC*) (*V04.25.00.00*)
		bMsg9483 : BOOL; (*SAFETY - Room ventilation failure - Outlet air louvre*) (*SAFETY PLC*) (*V04.25.00.00*)
		bMsg9484 : BOOL; (*SAFETY - Failure gas train for decentral gas addition*) (*SAFETY PLC*) (*V04.25.00.00*)
		bMsg9508 : BOOL; (*SAFETY - Malfunction of safe communication channel - Node 210*) (*SAFETY PLC*) (*V04.25.00.00*)
		bMsg9514 : BOOL; (*SAFETY - Speed signal not valid*) (*SAFETY PLC*) (*V04.14.00.00*)
		bMsg9515 : BOOL; (*SAFETY - Ignition plausibility check failure*) (*SAFETY PLC*) (*V04.14.00.00*)
		bMsg9516 : BOOL; (*SAFETY - Ignition system running - signal not valid*) (*SAFETY PLC*) (*V04.14.00.00*)
		bMsg9517 : BOOL; (*SAFETY - Release of synchronizing and load - output not valid*) (*SAFETY PLC*) (*V04.14.00.00*)
		bMsg9518 : BOOL; (*SAFETY - Generator circuit breaker release undervoltage trip coil - output not valid*) (*SAFETY PLC*) (*V04.14.00.00*)
		bMsg9519 : BOOL; (*SAFETY - Generator circuit breaker position ON - signal not valid*) (*SAFETY PLC*) (*V04.14.00.00*)
		bMsg9520 : BOOL; (*SAFETY - Generator circuit breaker position OFF - signal not valid*) (*SAFETY PLC*) (*V04.14.00.00*)
		bMsg9521 : BOOL; (*SAFETY - Generator overload/short circuit - signal not valid*) (*SAFETY PLC*) (*V04.14.00.00*)
		bMsg9522 : BOOL; (*SAFETY - Generator protection trip - signal not valid*) (*SAFETY PLC*) (*V04.14.00.00*)
		bMsg9523 : BOOL; (*SAFETY - Collective fault in room ventilation - plausibility check failure*) (*SAFETY PLC*) (*V04.25.00.00*)
		bMsg9524 : BOOL; (*SAFETY - Collective fault in room ventilation - signal not valid*) (*SAFETY PLC*) (*V04.25.00.00*)
		bMsg9525 : BOOL; (*SAFETY - Emergency stop push button - Module interface panel - signal not valid*) (*SAFETY PLC*) (*V04.14.00.00*)
		bMsg9526 : BOOL; (*SAFETY - Emergency stop push button - signal not valid*) (*SAFETY PLC*) (*V04.14.00.00*)
		bMsg9527 : BOOL; (*SAFETY - Safety loop 1 - Module control panel - signal not valid*) (*SAFETY PLC*) (*V04.14.00.00*)
		bMsg9528 : BOOL; (*SAFETY - Release gas valve 1a - output not valid*) (*SAFETY PLC*) (*V04.14.00.00*)
		bMsg9529 : BOOL; (*SAFETY - Release gas valve 1b - output not valid*) (*SAFETY PLC*) (*V04.14.00.00*)
		bMsg9530 : BOOL; (*SAFETY - Release gas valve 2a - output not valid*) (*SAFETY PLC*) (*V04.14.00.00*)
		bMsg9531 : BOOL; (*SAFETY - Release gas valve 2b - output not valid*) (*SAFETY PLC*) (*V04.14.00.00*)
		bMsg9532 : BOOL; (*SAFETY - Release gas valve 3a - output not valid*) (*SAFETY PLC*) (*V04.14.00.00*)
		bMsg9533 : BOOL; (*SAFETY - Release gas valve 3b - output not valid*) (*SAFETY PLC*) (*V04.14.00.00*)
		bMsg9534 : BOOL; (*SAFETY - Release gas valve 4a - output not valid*) (*SAFETY PLC*) (*V04.14.00.00*)
		bMsg9535 : BOOL; (*SAFETY - Release gas valve 4b - output not valid*) (*SAFETY PLC*) (*V04.14.00.00*)
		bMsg9536 : BOOL; (*SAFETY - Gas safety device 1 - signal not valid*) (*SAFETY PLC*) (*V04.14.00.00*)
		bMsg9537 : BOOL; (*SAFETY - Gas safety device 2 - signal not valid*) (*SAFETY PLC*) (*V04.14.00.00*)
		bMsg9538 : BOOL; (*SAFETY - Gas safety device 3 - signal not valid*) (*SAFETY PLC*) (*V04.14.00.00*)
		bMsg9539 : BOOL; (*SAFETY - Gas safety device 4 - signal not valid*) (*SAFETY PLC*) (*V04.14.00.00*)
		bMsg9540 : BOOL; (*SAFETY - Gas safety device 1 - output not valid*) (*SAFETY PLC*) (*V04.14.00.00*)
		bMsg9541 : BOOL; (*SAFETY - Gas safety device 2 - output not valid*) (*SAFETY PLC*) (*V04.14.00.00*)
		bMsg9542 : BOOL; (*SAFETY - Gas safety device 3 - output not valid*) (*SAFETY PLC*) (*V04.14.00.00*)
		bMsg9543 : BOOL; (*SAFETY - Gas safety device 4 - output not valid*) (*SAFETY PLC*) (*V04.14.00.00*)
		bMsg9544 : BOOL; (*SAFETY - Malfunction of safe communication channel - Node 101*) (*SAFETY PLC*) (*V04.14.00.00*)
		bMsg9545 : BOOL; (*SAFETY - Malfunction of safe communication channel - Node 102*) (*SAFETY PLC*) (*V04.14.00.00*)
		bMsg9546 : BOOL; (*SAFETY - Malfunction of safe communication channel - Node 103*) (*SAFETY PLC*) (*V04.14.00.00*)
		bMsg9547 : BOOL; (*SAFETY - Malfunction of safe communication channel - Node 104*) (*SAFETY PLC*) (*V04.14.00.00*)
		bMsg9548 : BOOL; (*SAFETY - Malfunction of safe communication channel - Node 201*) (*SAFETY PLC*) (*V04.14.00.00*)
		bMsg9549 : BOOL; (*SAFETY - Malfunction of safe communication channel - Node 202*) (*SAFETY PLC*) (*V04.14.00.00*)
		bMsg9550 : BOOL; (*SAFETY - Malfunction of safe communication channel - Node 203*) (*SAFETY PLC*) (*V04.14.00.00*)
		bMsg9551 : BOOL; (*SAFETY - Malfunction of safe communication channel - Node 204*) (*SAFETY PLC*) (*V04.14.00.00*)
		bMsg9552 : BOOL; (*SAFETY - Malfunction of safe communication channel - Node 205*) (*SAFETY PLC*) (*V04.14.00.00*)
		bMsg9553 : BOOL; (*SAFETY - Malfunction of safe communication channel - Node 206*) (*SAFETY PLC*) (*V04.14.00.00*)
		bMsg9554 : BOOL; (*SAFETY - Malfunction of safe communication channel - Node 207*) (*SAFETY PLC*) (*V04.14.00.00*)
		bMsg9555 : BOOL; (*SAFETY - Malfunction of safe communication channel - Node 208*) (*SAFETY PLC*) (*V04.14.00.00*)
		bMsg9556 : BOOL; (*SAFETY - Malfunction of safe communication channel - Node 209*) (*SAFETY PLC*) (*V04.14.00.00*)
		bMsg9562 : BOOL; (*SAFETY - Scavenging flap plausibility check failure*) (*SAFETY PLC*) (*V04.25.00.00*)
		bMsg9563 : BOOL; (*SAFETY - Scavenging flap closed feedback - signal not valid*) (*SAFETY PLC*) (*V04.25.00.00*)
		bMsg9564 : BOOL; (*SAFETY - Scavenging flap temperature switch - signal not valid*) (*SAFETY PLC*) (*V04.25.00.00*)
		bMsg9565 : BOOL; (*SAFETY - Customer heating water circuit failure - signal not valid*) (*SAFETY PLC*) (*V04.25.00.00*)
		bMsg9566 : BOOL; (*SAFETY - High temperature heating water flow minimum - plausibility check failure*) (*SAFETY PLC*) (*V04.25.00.00*)
		bMsg9567 : BOOL; (*SAFETY - High temperature heating water level minimum - signal not valid*) (*SAFETY PLC*) (*V04.25.00.00*)
		bMsg9568 : BOOL; (*SAFETY - High temperature heating water pressure 1 maximum - signal not valid*) (*SAFETY PLC*) (*V04.25.00.00*)
		bMsg9569 : BOOL; (*SAFETY - High temperature heating water pressure 2 maximum - signal not valid*) (*SAFETY PLC*) (*V04.25.00.00*)
		bMsg9570 : BOOL; (*SAFETY - High temperature heating water pressure 1 minimum - signal not valid*) (*SAFETY PLC*) (*V04.25.00.00*)
		bMsg9571 : BOOL; (*SAFETY - High temperature heating water pressure 2 minimum - signal not valid*) (*SAFETY PLC*) (*V04.25.00.00*)
		bMsg9572 : BOOL; (*SAFETY - High temperature heating water temperature 1 maximum - signal not valid*) (*SAFETY PLC*) (*V04.25.00.00*)
		bMsg9573 : BOOL; (*SAFETY - High temperature heating water temperature 2 maximum - signal not valid*) (*SAFETY PLC*) (*V04.25.00.00*)
		bMsg9574 : BOOL; (*SAFETY - High temperature heating water flow minimum - signal not valid*) (*SAFETY PLC*) (*V04.25.00.00*)
		bMsg9575 : BOOL; (*SAFETY - Low temperature heating water flow minimum - plausibility check failure*) (*SAFETY PLC*) (*V04.25.00.00*)
		bMsg9576 : BOOL; (*SAFETY - Low temperature heating water level minimum - signal not valid*) (*SAFETY PLC*) (*V04.25.00.00*)
		bMsg9577 : BOOL; (*SAFETY - Low temperature heating water pressure 1 maximum - signal not valid*) (*SAFETY PLC*) (*V04.25.00.00*)
		bMsg9578 : BOOL; (*SAFETY - Low temperature heating water pressure 2 maximum - signal not valid*) (*SAFETY PLC*) (*V04.25.00.00*)
		bMsg9579 : BOOL; (*SAFETY - Low temperature heating water pressure 1 minimum - signal not valid*) (*SAFETY PLC*) (*V04.25.00.00*)
		bMsg9580 : BOOL; (*SAFETY - Low temperature heating water pressure 2 minimum - signal not valid*) (*SAFETY PLC*) (*V04.25.00.00*)
		bMsg9581 : BOOL; (*SAFETY - Low temperature heating water temperature 1 maximum - signal not valid*) (*SAFETY PLC*) (*V04.25.00.00*)
		bMsg9582 : BOOL; (*SAFETY - Low temperature heating water temperature 2 maximum - signal not valid*) (*SAFETY PLC*) (*V04.25.00.00*)
		bMsg9583 : BOOL; (*SAFETY - Low temperature heating water flow minimum - signal not valid*) (*SAFETY PLC*) (*V04.25.00.00*)
		bMsg9584 : BOOL; (*SAFETY - Safety loop 2 - Module control panel - signal not valid*) (*SAFETY PLC*) (*V04.25.00.00*)
		bMsg9585 : BOOL; (*SAFETY - Safety loop - Module interface panel - signal not valid*) (*SAFETY PLC*) (*V04.25.00.00*)
		bMsg9586 : BOOL; (*SAFETY - Exhaust gas backpressure high - signal not valid*) (*SAFETY PLC*) (*V04.25.00.00*)
		bMsg9587 : BOOL; (*SAFETY - Emergency stop signalling - output not valid*) (*SAFETY PLC*) (*V04.25.00.00*)
		bMsg9593 : BOOL; (*SAFETY - Nominal speed mismatch*) (*SAFETY PLC*) (*V04.25.00.00*)
		bMsg9597 : BOOL; (*SAFETY - Malfunction of safe communication channel - Node 300*) (*SAFETY PLC*) (*V04.25.00.00*)
		bMsg9598 : BOOL; (*SAFETY - Malfunction of safe communication channel - Node 301*) (*SAFETY PLC*) (*V04.25.00.00*)
		bMsg9600 : BOOL; (*SAFETY - Malfunction of safe communication channel - Node 105*) (*SAFETY PLC*) (*V04.25.00.00*)
		bMsg9627 : BOOL; (*SAFETY - Room ventilation failure - Doors - plausibility check failure*) (*SAFETY PLC*) (*V04.25.00.00*)
		bMsg9628 : BOOL; (*SAFETY - Room ventilation failure - Doors - signal not valid*) (*SAFETY PLC*) (*V04.25.00.00*)
		bMsg9629 : BOOL; (*SAFETY - Room ventilation failure - Inlet air fan group 1*) (*SAFETY PLC*) (*V04.25.00.00*)
		bMsg9630 : BOOL; (*SAFETY - Room ventilation failure - Inlet air fan group 1 - plausibility check failure*) (*SAFETY PLC*) (*V04.25.00.00*)
		bMsg9631 : BOOL; (*SAFETY - Room ventilation failure - Inlet air fan group 1 - signal not valid*) (*SAFETY PLC*) (*V04.25.00.00*)
		bMsg9632 : BOOL; (*SAFETY - Room ventilation failure - Inlet air fan group 2*) (*SAFETY PLC*) (*V04.25.00.00*)
		bMsg9633 : BOOL; (*SAFETY - Room ventilation failure - Inlet air fan group 2 - plausibility check failure*) (*SAFETY PLC*) (*V04.25.00.00*)
		bMsg9634 : BOOL; (*SAFETY - Room ventilation failure - Inlet air fan group 2 - signal not valid*) (*SAFETY PLC*) (*V04.25.00.00*)
		bMsg9635 : BOOL; (*SAFETY - Room ventilation failure - Inlet air fan group 3*) (*SAFETY PLC*) (*V04.25.00.00*)
		bMsg9636 : BOOL; (*SAFETY - Room ventilation failure - Inlet air fan group 3 - plausibility check failure*) (*SAFETY PLC*) (*V04.25.00.00*)
		bMsg9637 : BOOL; (*SAFETY - Room ventilation failure - Inlet air fan group 3 - signal not valid*) (*SAFETY PLC*) (*V04.25.00.00*)
		bMsg9638 : BOOL; (*SAFETY - Room ventilation failure - Inlet air fan group 4*) (*SAFETY PLC*) (*V04.25.00.00*)
		bMsg9639 : BOOL; (*SAFETY - Room ventilation failure - Inlet air fan group 4 - plausibility check failure*) (*SAFETY PLC*) (*V04.25.00.00*)
		bMsg9640 : BOOL; (*SAFETY - Room ventilation failure - Inlet air fan group 4 - signal not valid*) (*SAFETY PLC*) (*V04.25.00.00*)
		bMsg9641 : BOOL; (*SAFETY - Room ventilation failure - Inlet air fan group 5*) (*SAFETY PLC*) (*V04.25.00.00*)
		bMsg9642 : BOOL; (*SAFETY - Room ventilation failure - Inlet air fan group 5 - plausibility check failure*) (*SAFETY PLC*) (*V04.25.00.00*)
		bMsg9643 : BOOL; (*SAFETY - Room ventilation failure - Inlet air fan group 5 - signal not valid*) (*SAFETY PLC*) (*V04.25.00.00*)
		bMsg9644 : BOOL; (*SAFETY - Room ventilation failure - Inlet air fan group 6*) (*SAFETY PLC*) (*V04.25.00.00*)
		bMsg9645 : BOOL; (*SAFETY - Room ventilation failure - Inlet air fan group 6 - plausibility check failure*) (*SAFETY PLC*) (*V04.25.00.00*)
		bMsg9646 : BOOL; (*SAFETY - Room ventilation failure - Inlet air fan group 6 - signal not valid*) (*SAFETY PLC*) (*V04.25.00.00*)
		bMsg9647 : BOOL; (*SAFETY - Room ventilation failure - Inlet air louvre group 1 - opened signal*) (*SAFETY PLC*) (*V04.25.00.00*)
		bMsg9648 : BOOL; (*SAFETY - Room ventilation failure - Inlet air louvre group 1 - closed signal*) (*SAFETY PLC*) (*V04.25.00.00*)
		bMsg9649 : BOOL; (*SAFETY - Room ventilation failure - Inlet air louvre group 1 - opened signal not valid*) (*SAFETY PLC*) (*V04.25.00.00*)
		bMsg9650 : BOOL; (*SAFETY - Room ventilation failure - Inlet air louvre group 1 - closed signal not valid*) (*SAFETY PLC*) (*V04.25.00.00*)
		bMsg9651 : BOOL; (*SAFETY - Room ventilation failure - Inlet air louvre group 1 - plausibility check failure*) (*SAFETY PLC*) (*V04.25.00.00*)
		bMsg9652 : BOOL; (*SAFETY - Room ventilation failure - Inlet air louvre group 2 - opened signal*) (*SAFETY PLC*) (*V04.25.00.00*)
		bMsg9653 : BOOL; (*SAFETY - Room ventilation failure - Inlet air louvre group 2 - closed signal*) (*SAFETY PLC*) (*V04.25.00.00*)
		bMsg9654 : BOOL; (*SAFETY - Room ventilation failure - Inlet air louvre group 2 - opened signal not valid*) (*SAFETY PLC*) (*V04.25.00.00*)
		bMsg9655 : BOOL; (*SAFETY - Room ventilation failure - Inlet air louvre group 2 - closed signal not valid*) (*SAFETY PLC*) (*V04.25.00.00*)
		bMsg9656 : BOOL; (*SAFETY - Room ventilation failure - Inlet air louvre group 2 - plausibility check failure*) (*SAFETY PLC*) (*V04.25.00.00*)
		bMsg9657 : BOOL; (*SAFETY - Room ventilation failure - Inlet air louvre group 3 - opened signal*) (*SAFETY PLC*) (*V04.25.00.00*)
		bMsg9658 : BOOL; (*SAFETY - Room ventilation failure - Inlet air louvre group 3 - closed signal*) (*SAFETY PLC*) (*V04.25.00.00*)
		bMsg9659 : BOOL; (*SAFETY - Room ventilation failure - Inlet air louvre group 3 - opened signal not valid*) (*SAFETY PLC*) (*V04.25.00.00*)
		bMsg9660 : BOOL; (*SAFETY - Room ventilation failure - Inlet air louvre group 3 - closed signal not valid*) (*SAFETY PLC*) (*V04.25.00.00*)
		bMsg9661 : BOOL; (*SAFETY - Room ventilation failure - Inlet air louvre group 3 - plausibility check failure*) (*SAFETY PLC*) (*V04.25.00.00*)
		bMsg9662 : BOOL; (*SAFETY - Room ventilation failure - Inlet air louvre group 4 - opened signal*) (*SAFETY PLC*) (*V04.25.00.00*)
		bMsg9663 : BOOL; (*SAFETY - Room ventilation failure - Inlet air louvre group 4 - closed signal*) (*SAFETY PLC*) (*V04.25.00.00*)
		bMsg9664 : BOOL; (*SAFETY - Room ventilation failure - Inlet air louvre group 4 - opened signal not valid*) (*SAFETY PLC*) (*V04.25.00.00*)
		bMsg9665 : BOOL; (*SAFETY - Room ventilation failure - Inlet air louvre group 4 - closed signal not valid*) (*SAFETY PLC*) (*V04.25.00.00*)
		bMsg9666 : BOOL; (*SAFETY - Room ventilation failure - Inlet air louvre group 4 - plausibility check failure*) (*SAFETY PLC*) (*V04.25.00.00*)
		bMsg9667 : BOOL; (*SAFETY - Room ventilation failure - Inlet air louvre group 5 - opened signal*) (*SAFETY PLC*) (*V04.25.00.00*)
		bMsg9668 : BOOL; (*SAFETY - Room ventilation failure - Inlet air louvre group 5 - closed signal*) (*SAFETY PLC*) (*V04.25.00.00*)
		bMsg9669 : BOOL; (*SAFETY - Room ventilation failure - Inlet air louvre group 5 - opened signal not valid*) (*SAFETY PLC*) (*V04.25.00.00*)
		bMsg9670 : BOOL; (*SAFETY - Room ventilation failure - Inlet air louvre group 5 - closed signal not valid*) (*SAFETY PLC*) (*V04.25.00.00*)
		bMsg9671 : BOOL; (*SAFETY - Room ventilation failure - Inlet air louvre group 5 - plausibility check failure*) (*SAFETY PLC*) (*V04.25.00.00*)
		bMsg9672 : BOOL; (*SAFETY - Room ventilation failure - Inlet air louvre group 6 - opened signal*) (*SAFETY PLC*) (*V04.25.00.00*)
		bMsg9673 : BOOL; (*SAFETY - Room ventilation failure - Inlet air louvre group 6 - closed signal*) (*SAFETY PLC*) (*V04.25.00.00*)
		bMsg9674 : BOOL; (*SAFETY - Room ventilation failure - Inlet air louvre group 6 - opened signal not valid*) (*SAFETY PLC*) (*V04.25.00.00*)
		bMsg9675 : BOOL; (*SAFETY - Room ventilation failure - Inlet air louvre group 6 - closed signal not valid*) (*SAFETY PLC*) (*V04.25.00.00*)
		bMsg9676 : BOOL; (*SAFETY - Room ventilation failure - Inlet air louvre group 6 - plausibility check failure*) (*SAFETY PLC*) (*V04.25.00.00*)
		bMsg9677 : BOOL; (*SAFETY - Room ventilation failure - Outlet air louvre group 1 - closed signal*) (*SAFETY PLC*) (*V04.25.00.00*)
		bMsg9678 : BOOL; (*SAFETY - Room ventilation failure - Outlet air louvre group 1 - opened signal not valid*) (*SAFETY PLC*) (*V04.25.00.00*)
		bMsg9679 : BOOL; (*SAFETY - Room ventilation failure - Outlet air louvre group 1 - closed signal not valid*) (*SAFETY PLC*) (*V04.25.00.00*)
		bMsg9680 : BOOL; (*SAFETY - Room ventilation failure - Outlet air louvre group 1 - plausibility check failure*) (*SAFETY PLC*) (*V04.25.00.00*)
		bMsg9681 : BOOL; (*SAFETY - Room ventilation failure - Outlet air louvre group 2 - closed signal*) (*SAFETY PLC*) (*V04.25.00.00*)
		bMsg9682 : BOOL; (*SAFETY - Room ventilation failure - Outlet air louvre group 2 - opened signal not valid*) (*SAFETY PLC*) (*V04.25.00.00*)
		bMsg9683 : BOOL; (*SAFETY - Room ventilation failure - Outlet air louvre group 2 - closed signal not valid*) (*SAFETY PLC*) (*V04.25.00.00*)
		bMsg9684 : BOOL; (*SAFETY - Room ventilation failure - Outlet air louvre group 2 - plausibility check failure*) (*SAFETY PLC*) (*V04.25.00.00*)
		bMsg9685 : BOOL; (*SAFETY - Room ventilation failure - Outlet air louvre group 3 - closed signal*) (*SAFETY PLC*) (*V04.25.00.00*)
		bMsg9686 : BOOL; (*SAFETY - Room ventilation failure - Outlet air louvre group 3 - opened signal not valid*) (*SAFETY PLC*) (*V04.25.00.00*)
		bMsg9687 : BOOL; (*SAFETY - Room ventilation failure - Outlet air louvre group 3 - closed signal not valid*) (*SAFETY PLC*) (*V04.25.00.00*)
		bMsg9688 : BOOL; (*SAFETY - Room ventilation failure - Outlet air louvre group 3 - plausibility check failure*) (*SAFETY PLC*) (*V04.25.00.00*)
		bMsg9689 : BOOL; (*SAFETY - Room ventilation failure - Outlet air louvre group 4 - closed signal*) (*SAFETY PLC*) (*V04.25.00.00*)
		bMsg9690 : BOOL; (*SAFETY - Room ventilation failure - Outlet air louvre group 4 - opened signal not valid*) (*SAFETY PLC*) (*V04.25.00.00*)
		bMsg9691 : BOOL; (*SAFETY - Room ventilation failure - Outlet air louvre group 4 - closed signal not valid*) (*SAFETY PLC*) (*V04.25.00.00*)
		bMsg9692 : BOOL; (*SAFETY - Room ventilation failure - Outlet air louvre group 4 - plausibility check failure*) (*SAFETY PLC*) (*V04.25.00.00*)
		bMsg9693 : BOOL; (*SAFETY - Room ventilation failure - Outlet air louvre group 5 - closed signal*) (*SAFETY PLC*) (*V04.25.00.00*)
		bMsg9694 : BOOL; (*SAFETY - Room ventilation failure - Outlet air louvre group 5 - opened signal not valid*) (*SAFETY PLC*) (*V04.25.00.00*)
		bMsg9695 : BOOL; (*SAFETY - Room ventilation failure - Outlet air louvre group 5 - closed signal not valid*) (*SAFETY PLC*) (*V04.25.00.00*)
		bMsg9696 : BOOL; (*SAFETY - Room ventilation failure - Outlet air louvre group 5 - plausibility check failure*) (*SAFETY PLC*) (*V04.25.00.00*)
		bMsg9697 : BOOL; (*SAFETY - Room ventilation failure - Outlet air louvre group 6 - closed signal*) (*SAFETY PLC*) (*V04.25.00.00*)
		bMsg9698 : BOOL; (*SAFETY - Room ventilation failure - Outlet air louvre group 6 - opened signal not valid*) (*SAFETY PLC*) (*V04.25.00.00*)
		bMsg9699 : BOOL; (*SAFETY - Room ventilation failure - Outlet air louvre group 6 - closed signal not valid*) (*SAFETY PLC*) (*V04.25.00.00*)
		bMsg9700 : BOOL; (*SAFETY - Room ventilation failure - Outlet air louvre group 6 - plausibility check failure*) (*SAFETY PLC*) (*V04.25.00.00*)
		bMsg9701 : BOOL; (*SAFETY - Release gas valve A for decentral gas addition - output not valid*) (*SAFETY PLC*) (*V04.25.00.00*)
		bMsg9702 : BOOL; (*SAFETY - Release gas valve B for decentral gas addition - output not valid*) (*SAFETY PLC*) (*V04.25.00.00*)
		bMsg9703 : BOOL; (*SAFETY - Gas safety device for decentral gas addition - signal not valid*) (*SAFETY PLC*) (*V04.25.00.00*)
		bMsg9704 : BOOL; (*SAFETY - Gas safety device for decentral gas addition - output not valid*) (*SAFETY PLC*) (*V04.25.00.00*)
		bPUscf_LearnEna : BOOL; (*PU scuffing detection - release learning function [-]*) (*OldName: new PV; Cycle: 6;*) (*V04.11.00.00*)
		bPUscf_RelTrip : BOOL; (*PU scuffing detection - trip release [-]*) (*OldName: new PV; Cycle: 6;*) (*V04.11.00.00*)
		iNum_Cyl : INT; (*number of cylinder*) (*OldName: ucNumberOfCylinder; Cycle: 5;*) (*V04.00.00.00*)
		iNum_Msg2981 : USINT; (*PU scuffing detection - affected cylinder [-]*) (*OldName: new PV; Cycle: 6;*) (*V04.11.00.00*)
		iNum_T_CBearing_Hi : USINT; (*conrod bearing temperature maximum - bearing position (number)*) (*OldName: new PV; Cycle: 5;*) (*V04.03.00.00*)
		iNum_T_CBearing_MDev_HiHi : USINT; (*conrod bearing temperature - positive deviation from MEDIAN maximum - bearing position (number)*) (*OldName: new PV; Cycle: 5;*) (*V04.04.00.00*)
		iNum_T_CBearing_MDev_Lo : USINT; (*conrod bearing temperature - negative deviation from MEDIAN maximum - bearing position (number)*) (*OldName: new PV; Cycle: 5;*) (*V04.05.01.00*)
		iNum_T_CBearing_MsMs : USINT; (*conrod bearing temperature measurement signal failure - bearing position (number)*) (*OldName: new PV; Cycle: 5;*) (*V04.03.00.00*)
		iNum_T_CBearing_Sig_Lo : USINT; (*conrod bearing signal intensity minimum - bearing position (number)*) (*OldName: new PV; Cycle: 5;*) (*V04.03.00.00*)
		iNum_T_MBearing_Hi : USINT; (*main bearing temperature maximum - bearing position (number)*) (*OldName: new PV; Cycle: 5;*) (*V04.03.00.00*)
		iNum_T_MBearing_MDev_HiHi : USINT; (*main bearing temperature - positive deviation from MEDIAN maximum - bearing position (number)*) (*OldName: new PV; Cycle: 5;*) (*V04.04.00.00*)
		iNum_T_MBearing_MDev_Lo : USINT; (*main bearing temperature - negative deviation from MEDIAN maximum - bearing position (number)*) (*OldName: new PV; Cycle: 5;*) (*V04.05.01.00*)
		iNum_T_MBearing_MsMs : USINT; (*main bearing temperature measurement signal failure - bearing position (number)*) (*OldName: new PV; Cycle: 5;*) (*V04.03.00.00*)
		iOpM_Pc_T_CBearing_Sig : INT; (*operating message - signal strength of tripped conrod bearing [%]*) (*OldName: new PV; Cycle: 5;*) (*V04.03.00.00*)
		iPc_T_CBearing_Gain : ARRAY[0..24]OF INT; (*receiver gain level from conrod bearing temperature sensor [%]*) (*OldName: new PV; Cycle: 5;*) (*V04.05.00.00*)
		iPc_T_CBearing_Gain_Avg : INT; (*average receiver gain level from conrod bearing temperature sensor [%]*) (*OldName: new PV; Cycle: 5;*) (*V04.05.00.00*)
		iPc_T_CBearing_Gain_Max : INT; (*maximum receiver gain level from conrod bearing temperature sensor [%]*) (*OldName: new PV; Cycle: 5;*) (*V04.05.00.00*)
		iPc_T_CBearing_Gain_Min : INT; (*minimum receiver gain level from conrod bearing temperature sensor [%]*) (*OldName: new PV; Cycle: 5;*) (*V04.05.00.00*)
		iPc_T_CBearing_Sig : ARRAY[0..24]OF INT; (*strength of signal from conrod bearing temperature sensor [%]*) (*OldName: new PV; Cycle: 5;*) (*V04.03.00.00*)
		iPc_T_CBearing_Sig_Avg : INT; (*average strength of signal from conrod bearing temperature sensor [%]*) (*OldName: new PV; Cycle: 5;*) (*V04.03.00.00*)
		iPc_T_CBearing_Sig_Max : INT; (*maximum strength of signal from conrod bearing temperature sensor [%]*) (*OldName: new PV; Cycle: 5;*) (*V04.03.00.00*)
		iPc_T_CBearing_Sig_Min : INT; (*minimum strength of signal from conrod bearing temperature sensor [%]*) (*OldName: new PV; Cycle: 5;*) (*V04.03.00.00*)
		iSt_T_CBearing_Calib : ARRAY[0..24]OF INT; (*state for conrod bearing temperature calibration*) (*OldName: new PV; Cycle: 5;*) (*V04.03.00.00*)
		rF_VibSens_CenterBand1 : REAL; (*center frequency band 1 [Hz]*) (*OldName: new PV; Cycle: 1;*) (*V04.11.00.00*)
		rF_VibSens_CenterBand2 : REAL; (*center frequency band 2 [Hz]*) (*OldName: new PV; Cycle: 1;*) (*V04.11.00.00*)
		rF_VibSens_CenterBand3 : REAL; (*center frequency band 3 [Hz]*) (*OldName: new PV; Cycle: 1;*) (*V04.11.00.00*)
		rF_VibSens_CenterBand4 : REAL; (*center frequency band 4 [Hz]*) (*OldName: new PV; Cycle: 1;*) (*V04.11.00.00*)
		rF_VibSens_CenterBand5 : REAL; (*center frequency band 5 [Hz]*) (*OldName: new PV; Cycle: 1;*) (*V04.11.00.00*)
		rF_VibSens_CenterBand6 : REAL; (*center frequency band 6 [Hz]*) (*OldName: new PV; Cycle: 1;*) (*V04.11.00.00*)
		rF_VibSens_CenterBand7 : REAL; (*center frequency band 7 [Hz]*) (*OldName: new PV; Cycle: 1;*) (*V04.11.00.00*)
		rF_VibSens_CenterBand8 : REAL; (*center frequency band 8 [Hz]*) (*OldName: new PV; Cycle: 1;*) (*V04.11.00.00*)
		rF_VibSens_Max : ARRAY[0..12]OF REAL; (*frequency at velocity vibration sensors maximum [mm/s]*) (*OldName: new PV; Cycle: 1;*) (*V04.11.00.00*)
		rPr_Baro : REAL; (*barometric pressure [bar (abs)]*) (*OldName: p_Baro; Cycle: 5;*) (*V04.03.00.00*)
		rPr_CC_pred : REAL; (*PU scuffing detection - expected crank case pressure [mbar]*) (*OldName: new PV; Cycle: 6;*) (*V04.11.00.00*)
		rSDT : REAL; (*recent aligned slow down time (from 95% engine speed to 5% engine speed) [s]*) (*OldName: new PV; Cycle: 5;*) (*V04.01.00.00*)
		rT_CBearing : ARRAY[0..24]OF REAL; (*conrod bearing temperature [degC]*) (*OldName: new PV; Cycle: 5;*) (*V04.03.00.00*)
		rT_CBearing_Avg : REAL; (*average conrod bearing temperature [degC]*) (*OldName: new PV; Cycle: 5;*) (*V04.03.00.00*)
		rT_CBearing_Max : REAL; (*maximum conrod bearing temperature [degC]*) (*OldName: new PV; Cycle: 5;*) (*V04.03.00.00*)
		rT_CBearing_Min : REAL; (*minimum conrod bearing temperature [degC]*) (*OldName: new PV; Cycle: 5;*) (*V04.03.00.00*)
		rT_ECW_Avg : REAL; (*recent average engine cooling water temperature [degC]*) (*OldName: new PV; Cycle: 5;*) (*V04.01.00.00*)
		rT_EO_Avg : REAL; (*recent average engine oil temperature [degC]*) (*OldName: new PV; Cycle: 5;*) (*V04.01.00.00*)
		rT_MBearing : ARRAY[0..11]OF REAL; (*filtered main bearing temperature [degC]*) (*OldName: new PV; Cycle: 5;*) (*V04.03.00.00*)
		rT_MBearing_Avg : REAL; (*average main bearing temperature [degC]*) (*OldName: new PV; Cycle: 5;*) (*V04.03.00.00*)
		rT_MBearing_Max : REAL; (*maximum main bearing temperature [degC]*) (*OldName: new PV; Cycle: 5;*) (*V04.03.00.00*)
		rT_MBearing_Min : REAL; (*minimum main bearing temperature [degC]*) (*OldName: new PV; Cycle: 5;*) (*V04.03.00.00*)
		rU_Exc_Avg : REAL; (*recent average excitation voltage [V]*) (*OldName: new PV; Cycle: 5;*) (*V04.01.00.00*)
		rVel_VibSens : ARRAY[0..12]OF REAL; (*velocity vibration sensors [mm/s]*) (*OldName: new PV; Cycle: 1;*) (*V04.11.00.00*)
		rVel_VibSens_Band1 : ARRAY[0..12]OF REAL; (*velocity vibration sensors frequency band 1 [mm/s]*) (*OldName: new PV; Cycle: 1;*) (*V04.11.00.00*)
		rVel_VibSens_Band2 : ARRAY[0..12]OF REAL; (*velocity vibration sensors frequency band 2 [mm/s]*) (*OldName: new PV; Cycle: 1;*) (*V04.11.00.00*)
		rVel_VibSens_Band3 : ARRAY[0..12]OF REAL; (*velocity vibration sensors frequency band 3 [mm/s]*) (*OldName: new PV; Cycle: 1;*) (*V04.11.00.00*)
		rVel_VibSens_Band4 : ARRAY[0..12]OF REAL; (*velocity vibration sensors frequency band 4 [mm/s]*) (*OldName: new PV; Cycle: 1;*) (*V04.11.00.00*)
		rVel_VibSens_Band5 : ARRAY[0..12]OF REAL; (*velocity vibration sensors frequency band 5 [mm/s]*) (*OldName: new PV; Cycle: 1;*) (*V04.11.00.00*)
		rVel_VibSens_Band6 : ARRAY[0..12]OF REAL; (*velocity vibration sensors frequency band 6 [mm/s]*) (*OldName: new PV; Cycle: 1;*) (*V04.11.00.00*)
		rVel_VibSens_Band7 : ARRAY[0..12]OF REAL; (*velocity vibration sensors frequency band 7 [mm/s]*) (*OldName: new PV; Cycle: 1;*) (*V04.11.00.00*)
		rVel_VibSens_Band8 : ARRAY[0..12]OF REAL; (*velocity vibration sensors frequency band 8 [mm/s]*) (*OldName: new PV; Cycle: 1;*) (*V04.11.00.00*)
		rVel_VibSens_Max : ARRAY[0..12]OF REAL; (*velocity vibration sensors maximum [mm/s]*) (*OldName: new PV; Cycle: 1;*) (*V04.11.00.00*)
		SlowdownTime : ARRAY[0..19]OF tSlowdownTime; (*circular buffer*) (*OldName: new PV; Cycle: 5;*) (*V04.01.00.00*)
	END_STRUCT;
	VIS2MM_Struct : 	STRUCT 
		bDem_T_CBearing_Calib : BOOL := FALSE; (*demand for conrod bearing temperature calibration*) (*OldName: new PV; Cycle: 5;*) (*V04.03.00.00*)
		iNum_T_CBearing_Calib : INT := 0; (*conrod bearing position (number) to calibrate [0 = all]*) (*OldName: new PV; Cycle: 5;*) (*V04.03.00.00*)
	END_STRUCT;
	PARA_EG_Struct : 	STRUCT 
		bIdleFrictionMon : BOOL; (*PARA [13856]: idle friction monitoring activation *) (*OldName: new PV; Cycle: 5;*) (*V04.04.00.00*)
		bPr_Baro_Exist : BOOL; (*PARA [12719]: barometric pressure exist*) (*OldName: p_Baro_a; Cycle: 5;*) (*V04.03.00.00*)
		bT_CBearing_Exist : BOOL; (*PARA [12659]: conrod bearing temperature measurement exist*) (*OldName: new PV; Cycle: 5;*) (*V04.03.00.00*)
		bT_MBearing_Exist : BOOL; (*PARA [12655]: main bearing temperature measurement exist*) (*OldName: new PV; Cycle: 5;*) (*V04.03.00.00*)
		iEng_Motortype : INT; (*PARA [00000]: motortype of the engine*) (*OldName: motortyp; Cycle: 5;*) (*V04.00.00.00*)
		iPc_T_CBearing_Sig_Lo : INT; (*PARA [13459]: strength of conrod bearing sensor signal minimum - warning [%]*) (*OldName: new PV; Cycle: 5;*) (*V04.03.00.00*)
		rN_EngNom : REAL; (*PARA [12128]: engine nominal speed [rpm]*) (*OldName: n_nenn; Cycle:5*) (*V04.01.00.00*)
		rN_EngStart_HyHi : REAL; (*PARA [11295]: engine speed start limit high hysteresis [rpm]*) (*OldName: HY_DREHZ; Cycle: 5;*) (*V04.00.00.00*)
		rN_EngStart_LimHi : REAL; (*PARA [11296]: engine speed start limit high [rpm]*) (*OldName: GW_DREHZ; Cycle: 5;*) (*V04.00.00.00*)
		rP_HyLo : REAL; (*PARA [12206]: power signal missing limit low hysteresis [%Pnom]*) (*OldName: HY_LSA; Cycle: 5;*) (*V04.00.00.00*)
		rP_Island_Split_DecGrad_Norm : ARRAY[0..4]OF REAL; (*PARA [13373]: gradient for decrease of load sharing line output [%]*) (*OldName: new PV; Cycle:5;*) (*V04.10.00.00*)
		rP_LimLo : REAL; (*PARA [12208]: power signal missing limit low [%Pnom]*) (*OldName: GW_LSA; Cycle: 5;*) (*V04.00.00.00*)
		rP_Ramp_DecGrad_Norm : ARRAY[0..4]OF REAL; (*PARA [12100]: gradient for decrease of power ramp in grid mode [%Pnom/s] *) (*OldName: t_down; Cycle: 5;*) (*V04.03.00.00*)
		rPr_Baro_site : REAL; (*PARA [12720]: barometric pressure at site [bar (abs)]*) (*OldName: new PV; Cycle: 5;*) (*V04.03.00.00*)
		rPr_Baro_siteDevMax : REAL; (*PARA [12721]: barometric pressure at site deviation maximum - warning [bar]*) (*OldName: new PV; Cycle: 5;*) (*V04.03.00.00*)
		rSDT_Avg_LoLo : REAL; (*PARA [12454]: slow down time minimum according to the average slow down time  [%]*) (*OldName: new PV; Cycle: 5;*) (*V04.01.00.00*)
		rT_CBearing_Hi : REAL; (*PARA [12660]: conrod bearing temperature maximum - warning [degC]*) (*OldName: new PV; Cycle: 5;*) (*V04.03.00.00*)
		rT_CBearing_Hi_Offset : REAL; (*PARA [13684]: conrod bearing temperature maximum - offset during low load operation [degC]*) (*OldName: new PV; Cycle: 5;*) (*V04.04.00.00*)
		rT_CBearing_HiHi : REAL; (*PARA [12661]: conrod bearing temperature maximum - error [degC]*) (*OldName: new PV; Cycle: 5;*) (*V04.03.00.00*)
		rT_CBearing_MDev_HiHi : REAL; (*PARA [12662]: conrod bearing temperature deviation from MEDIAN maximum - error [degC]*) (*OldName: new PV; Cycle: 5;*) (*V04.03.00.00*)
		rT_MBearing_Hi : REAL; (*PARA [12656]: main bearing temperature maximum - warning [degC]*) (*OldName: new PV; Cycle: 5;*) (*V04.03.00.00*)
		rT_MBearing_HiHi : REAL; (*PARA [12657]: main bearing temperature maximum - error [degC]*) (*OldName: new PV; Cycle: 5;*) (*V04.03.00.00*)
		rT_MBearing_MDev_HiHi : REAL; (*PARA [12658]: main bearing temperature deviation from MEDIAN maximum - Error [degC]*) (*OldName: new PV; Cycle: 5;*) (*V04.03.00.00*)
		bVibSens_Act : BOOL; (*PARA [14565]:vibration monitoring engine & generator exist*) (*OldName: new PV; Cycle: 1;*) (*V04.11.00.00*)
		rIdx_VibSens_BandOrder1 : REAL; (*PARA [14566]:vibration order of frequency band 1 [-]*) (*OldName: new PV; Cycle: 1;*) (*V04.11.00.00*)
		rIdx_VibSens_BandOrder2 : REAL; (*PARA [14567]:vibration order of frequency band 2 [-]*) (*OldName: new PV; Cycle: 1;*) (*V04.11.00.00*)
		rIdx_VibSens_BandOrder3 : REAL; (*PARA [14568]:vibration order of frequency band 3 [-]*) (*OldName: new PV; Cycle: 1;*) (*V04.11.00.00*)
		rIdx_VibSens_BandOrder4 : REAL; (*PARA [14569]:vibration order of frequency band 4 [-]*) (*OldName: new PV; Cycle: 1;*) (*V04.11.00.00*)
		rIdx_VibSens_BandOrder5 : REAL; (*PARA [14570]:vibration order of frequency band 5 [-]*) (*OldName: new PV; Cycle: 1;*) (*V04.11.00.00*)
		rIdx_VibSens_BandOrder6 : REAL; (*PARA [14571]:vibration order of frequency band 6 [-]*) (*OldName: new PV; Cycle: 1;*) (*V04.11.00.00*)
		rIdx_VibSens_BandOrder7 : REAL; (*PARA [14572]:vibration order of frequency band 7 [-]*) (*OldName: new PV; Cycle: 1;*) (*V04.11.00.00*)
		rIdx_VibSens_BandOrder8 : REAL; (*PARA [14573]:vibration order of frequency band 8 [-]*) (*OldName: new PV; Cycle: 1;*) (*V04.11.00.00*)
		rIdx_VibSens_BandWidth : REAL; (*PARA [14574]:frequency bandwith around center order [Hz]*) (*OldName: new PV; Cycle: 1;*) (*V04.11.00.00*)
		bPUscf_Ena : BOOL; (*PARA [14596]: PU scuffing scuffing detection active*) (*OldName: new PV; Cycle: 6;*) (*V04.11.00.00*)
		rPUscf_Eps_scale : REAL; (*PARA [14597]: sensitivity scaling of the knock noise signal anomaly detection*) (*OldName: new PV; Cycle: 6;*) (*V04.11.00.00*)
		rTiPUscf_EnaDelay : REAL; (*PARA [14598]: activation delay after generator circuit breaker on [s]*) (*OldName: new PV; Cycle: 6;*) (*V04.11.00.00*)
		rPr_CC_PUscf_Dev_HiHi : REAL; (*PARA [14599]: limit crankcase pressure difference [mbar]*) (*OldName: new PV; Cycle: 6;*) (*V04.11.00.00*)
		rTiPUscf_LearnReactDelay : REAL; (*PARA [14600]: learning function activation delay after knock event [s]*) (*OldName: new PV; Cycle: 6;*) (*V04.11.00.00*)
		rPUscf_LearnScale : REAL; (*PARA [14601]: release threshold scaling for the learning function*) (*OldName: new PV; Cycle: 6;*) (*V04.11.00.00*)
		bSA_KLS_Active : BOOL; (*PARA [12118]: TRUE = SAFI KLS function is enabled/active *) (* OldName:bSAFIKLS_Act; Cycle: 6;*) (*V04.11.00.00*)
		rSafe_N_EngNom : REAL; (*PARA [15087]: Speed - Nominal speed [rpm]*) (*SAFETY PLC; Cycle: 6;*) (*V04.14.00.00*)
		rSafe_N_EngAct_HiHi_Diff : REAL; (*PARA [15086]: Speed - Maximum deviation to ignition speed [rpm]*) (*SAFETY PLC; Cycle: 6;*) (*V04.14.00.00*)
		rSafe_Pr_EO_LoLo_LimN1 : REAL; (*PARA [15098]: Oil pressure - Minimum at speed point 1 [mbar]*) (*SAFETY PLC; Cycle: 6;*) (*V04.14.00.00*)
		rSafe_Pr_EO_LoLo_LimN2 : REAL; (*PARA [15099]: Oil pressure - Minimum at speed point 2 [mbar]*) (*SAFETY PLC; Cycle: 6;*) (*V04.14.00.00*)
		rSafe_N_Pr_EO_LoLo_Lim1 : REAL; (*PARA [15088]: Oil pressure - Minimum - Speed point 1 [rpm]*) (*SAFETY PLC; Cycle: 6;*) (*V04.14.00.00*)
		rSafe_N_Pr_EO_LoLo_Lim2 : REAL; (*PARA [15089]: Oil pressure - Minimum - Speed point 2 [rpm]*) (*SAFETY PLC; Cycle: 6;*) (*V04.14.00.00*)
		rSafe_Pr_EO_Diff_EngStop : REAL; (*PARA [15094]: Oil pressure - Minimum difference to standstill [mbar]*) (*SAFETY PLC; Cycle: 6;*) (*V04.14.00.00*)
		rSafe_Pr_EO_HiHi_EngStop : REAL; (*PARA [15097]: Oil pressure - Maximum at standstill [mbar]*) (*SAFETY PLC; Cycle: 6;*) (*V04.14.00.00*)
		rSafe_Pr_EO_HiHi_Diff : REAL; (*PARA [15096]: Oil pressure - Maximum deviation between the sensors [mbar]*) (*SAFETY PLC; Cycle: 6;*) (*V04.14.00.00*)
		rSafe_Pr_EO_HiHi_Check : REAL; (*PARA [15095]: Oil pressure - Maximum (sensor drift) [mbar]*) (*SAFETY PLC; Cycle: 6;*) (*V04.14.00.00*)
		rSafe_Pr_EOaP_HiHi : REAL; (*PARA [15101]: Oil pressure after pump - Maximum [mbar]*) (*SAFETY PLC; Cycle: 6;*) (*V04.14.00.00*)
		rSafe_Pr_EOaP_Diff_EngStop : REAL; (*PARA [15100]: Oil pressure after pump - Minimum difference to standstill [mbar]*) (*SAFETY PLC; Cycle: 6;*) (*V04.14.00.00*)
		rSafe_Pr_EOaP_HiHi_EngStop : REAL; (*PARA [15102]: Oil pressure after pump - Maximum at standstill [mbar]*) (*SAFETY PLC; Cycle: 6;*) (*V04.14.00.00*)
		rSafe_Pr_ECW_LoLo : REAL; (*PARA [15092]: Engine cooling water pressure - Minimum [mbar]*) (*SAFETY PLC; Cycle: 6;*) (*V04.14.00.00*)
		rSafe_Pr_ECW_HiHi_Diff : REAL; (*PARA [15091]: Engine cooling water pressure - Maximum deviation between the sensors [mbar]*) (*SAFETY PLC; Cycle: 6;*) (*V04.14.00.00*)
		rSafe_Pr_ECW_HiHi_Check : REAL; (*PARA [15090]: Engine cooling water pressure - Maximum (sensor drift) [mbar]*) (*SAFETY PLC; Cycle: 6;*) (*V04.14.00.00*)
		rSafe_Pr_ECWaP_HiHi : REAL; (*PARA [15093]: Engine cooling water pressure after pump - Maximum [mbar]*) (*SAFETY PLC; Cycle: 6;*) (*V04.14.00.00*)
		bSafe_GT2_Exist : BOOL; (*PARA [15082]: Gas train 2 existing*) (*SAFETY PLC; Cycle: 6;*) (*V04.14.00.00*)
		bSafe_GT3_Exist : BOOL; (*PARA [15083]: Gas train 3 existing*) (*SAFETY PLC; Cycle: 6;*) (*V04.14.00.00*)
		bSafe_GT4_Exist : BOOL; (*PARA [15103]: Gas train 4 existing*) (*SAFETY PLC; Cycle: 6;*) (*V04.14.00.00*)
		iSafe_Eng_Motortype : INT; (*PARA [15084]: Motortype*) (*SAFETY PLC; Cycle: 6;*) (*V04.14.00.00*)
		rSafe_DPr_ECWP_LoLo : REAL; (*PARA [15104]: Engine cooling water pump - Difference pressure minimum [bar]*) (*SAFETY PLC; Cycle: 6;*) (*V04.25.00.00*)
		bSafe_SysPurge_MonActive : BOOL; (*PARA [15107]: System purge - Monitoring active*) (*SAFETY PLC; Cycle: 6;*) (*V04.25.00.00*)
		rSafe_Vol_SysPurge_Stroke : REAL; (*PARA [15105]: System purge - Stroke volume per crankshaft turn [l/turn]*) (*SAFETY PLC; Cycle: 6;*) (*V04.25.00.00*)
		rSafe_Vol_SysPurge_MinAir : REAL; (*PARA [15106]: System purge - Minimum air volume [l]*) (*SAFETY PLC; Cycle: 6;*) (*V04.25.00.00*)
		bSafe_HWcirc_Cust_Exist : BOOL; (*PARA [15108]: Customer heating water circuit - Monitoring active*) (*SAFETY PLC; Cycle: 6;*) (*V04.25.00.00*)
		bSafe_PS_HW_Lo_MuteActive : BOOL; (*PARA [15109]: Muting heating water minimum pressure switches at engine standstill active*) (*SAFETY PLC; Cycle: 6;*) (*V04.25.00.00*)
		bSafe_LS_HWHT_Lo_Exist : BOOL; (*PARA [15110]: High temperature heating water - Minimum level switch available*) (*SAFETY PLC; Cycle: 6;*) (*V04.25.00.00*)
		bSafe_PS1_HWHT_Hi_Exist : BOOL; (*PARA [15111]: High temperature heating water - Maximum pressure switch 1 available*) (*SAFETY PLC; Cycle: 6;*) (*V04.25.00.00*)
		bSafe_PS2_HWHT_Hi_Exist : BOOL; (*PARA [15112]: High temperature heating water - Maximum pressure switch 2 available*) (*SAFETY PLC; Cycle: 6;*) (*V04.25.00.00*)
		bSafe_PS1_HWHT_Lo_Exist : BOOL; (*PARA [15113]: High temperature heating water - Minimum pressure switch 1 available*) (*SAFETY PLC; Cycle: 6;*) (*V04.25.00.00*)
		bSafe_PS2_HWHT_Lo_Exist : BOOL; (*PARA [15114]: High temperature heating water - Minimum pressure switch 2 available*) (*SAFETY PLC; Cycle: 6;*) (*V04.25.00.00*)
		bSafe_TS1_HWHT_Hi_Exist : BOOL; (*PARA [15115]: High temperature heating water - Maximum temperature switch 1 available*) (*SAFETY PLC; Cycle: 6;*) (*V04.25.00.00*)
		bSafe_TS2_HWHT_Hi_Exist : BOOL; (*PARA [15116]: High temperature heating water - Maximum temperature switch 2 available*) (*SAFETY PLC; Cycle: 6;*) (*V04.25.00.00*)
		bSafe_FS_HWHT_Lo_Exist : BOOL; (*PARA [15117]: High temperature heating water - Minimum flow switch available*) (*SAFETY PLC; Cycle: 6;*) (*V04.25.00.00*)
		bSafe_LS_HWLT_Lo_Exist : BOOL; (*PARA [15118]: Low temperature heating water - Minimum level switch available*) (*SAFETY PLC; Cycle: 6;*) (*V04.25.00.00*)
		bSafe_PS1_HWLT_Hi_Exist : BOOL; (*PARA [15119]: Low temperature heating water - Maximum pressure switch 1 available*) (*SAFETY PLC; Cycle: 6;*) (*V04.25.00.00*)
		bSafe_PS2_HWLT_Hi_Exist : BOOL; (*PARA [15120]: Low temperature heating water - Maximum pressure switch 2 available*) (*SAFETY PLC; Cycle: 6;*) (*V04.25.00.00*)
		bSafe_PS1_HWLT_Lo_Exist : BOOL; (*PARA [15121]: Low temperature heating water - Minimum pressure switch 1 available*) (*SAFETY PLC; Cycle: 6;*) (*V04.25.00.00*)
		bSafe_PS2_HWLT_Lo_Exist : BOOL; (*PARA [15122]: Low temperature heating water - Minimum pressure switch 2 available*) (*SAFETY PLC; Cycle: 6;*) (*V04.25.00.00*)
		bSafe_TS1_HWLT_Hi_Exist : BOOL; (*PARA [15123]: Low temperature heating water - Maximum temperature switch 1 available*) (*SAFETY PLC; Cycle: 6;*) (*V04.25.00.00*)
		bSafe_TS2_HWLT_Hi_Exist : BOOL; (*PARA [15124]: Low temperature heating water - Maximum temperature switch 2 available*) (*SAFETY PLC; Cycle: 6;*) (*V04.25.00.00*)
		bSafe_FS_HWLT_Lo_Exist : BOOL; (*PARA [15125]: Low temperature heating water - Minimum flow switch available*) (*SAFETY PLC; Cycle: 6;*) (*V04.25.00.00*)
		bSafe_Pr_EG_sMonActive : BOOL; (*PARA [15085]: Exhaust gas backpressure - Safety monitoring active*) (*SAFETY PLC; Cycle: 6;*) (*V04.25.00.00*)
		bSafe_SafetyLoop_A2_Exist : BOOL; (*PARA [15143]: Safety loop 2 in the module control panel existing*) (*SAFETY PLC; Cycle: 6;*) (*V04.25.00.00*)
		bSafe_ERV_Cust_Active : BOOL; (*PARA [15188]: Customer room ventilation - Monitoring active*) (*SAFETY PLC; Cycle: 6;*) (*V04.25.00.00*)
		bSafe_ERV_ColdCountry_Active : BOOL; (*PARA [15189]: Cold country mode active*) (*SAFETY PLC; Cycle: 6;*) (*V04.25.00.00*)
		bSafe_ER_Door_MonActive : BOOL; (*PARA [15212]: Door switch - Monitoring active*) (*SAFETY PLC; Cycle: 6;*) (*V04.25.00.00*)
		iSafe_Nr_ERV_INL_Fan : INT; (*PARA [15190]: Number of inlet air fans*) (*SAFETY PLC; Cycle: 6;*) (*V04.25.00.00*)
		iSafe_Nr_ERV_INL_Lou : INT; (*PARA [15191]: Number of inlet air louvres*) (*SAFETY PLC; Cycle: 6;*) (*V04.25.00.00*)
		iSafe_Nr_ERV_OTL_Lou : INT; (*PARA [15192]: Number of outlet air louvres*) (*SAFETY PLC; Cycle: 6;*) (*V04.25.00.00*)
		iSafe_NrMaxErr_ERV_INL_Fan : INT; (*PARA [15193]: Maximum allowed number of failed inlet air fans*) (*SAFETY PLC; Cycle: 6;*) (*V04.25.00.00*)
		iSafe_NrMaxErr_ERV_INL_Lou : INT; (*PARA [15194]: Maximum allowed number of failed inlet air louvres*) (*SAFETY PLC; Cycle: 6;*) (*V04.25.00.00*)
		iSafe_NrMaxErr_ERV_OTL_Lou : INT; (*PARA [15195]: Maximum allowed number of failed outlet air louvres*) (*SAFETY PLC; Cycle: 6;*) (*V04.25.00.00*)
		bSafe_DCGA_Exist : BOOL; (*PARA [15196]: Gas train for decentral gas addition existing*) (*SAFETY PLC; Cycle: 6;*) (*V04.25.00.00*)
	END_STRUCT;
END_TYPE
