(********************************************************************
 * COPYRIGHT -- INNIO Company
 ********************************************************************
 * Package: HAL_IO
 * File: HAL_IO.typ
 * Author: 105046866
 * Created: August 23, 2011
 ********************************************************************
 * Data types of package HAL_IO
 ********************************************************************)

TYPE
	Para_HA_struct : 	STRUCT 
		iT_EGaHE1_SensorType : INT; (*PARA[15052] MultiSignalTemp V4.14*)
		rT_EGaHE1_ScalMin : REAL; (*PARA[15053] MultiSignalTemp V4.14*)
		rT_EGaHE1_ScalMax : REAL; (*PARA[15054] MultiSignalTemp V4.14*)
		iT_EGaHE2_SensorType : INT; (*PARA[15055] MultiSignalTemp V4.14*)
		rT_EGaHE2_ScalMin : REAL; (*PARA[15056] MultiSignalTemp V4.14*)
		rT_EGaHE2_ScalMax : REAL; (*PARA[15057] MultiSignalTemp V4.14*)
		iT_EGaTC_SensorType : INT; (*PARA[15058] MultiSignalTemp V4.14*)
		rT_EGaTC_ScalMin : REAL; (*PARA[15059] MultiSignalTemp V4.14*)
		rT_EGaTC_ScalMax : REAL; (*PARA[15060] MultiSignalTemp V4.14*)
		iT_PlateHE_SensorType : INT; (*PARA[15061] MultiSignalTemp V4.14*)
		rT_PlateHE_ScalMin : REAL; (*PARA[15062] MultiSignalTemp V4.14*)
		rT_PlateHE_ScalMax : REAL; (*PARA[15063] MultiSignalTemp V4.14*)
		iFreshOilTank_SensorType : INT; (*PARA [14895]  OilTank V24*)
		rFreshOilTank_ScalMin : REAL; (*PARA [14872]  OilTank V24*)
		rFreshOilTank_ScalMax : REAL; (*PARA [14873]  OilTank V24*)
		iWasteOilTank_SensorType : INT; (*PARA [14896]  OilTank V24*)
		rWasteOilTank_ScalMin : REAL; (*PARA [14881]  OilTank V24*)
		rWasteOilTank_ScalMax : REAL; (*PARA [14882]  OilTank V24*)
		iDayOilTank_SensorType : INT; (*PARA [14897]  OilTank V24*)
		rDayOilTank_ScalMin : REAL; (*PARA [14890]  OilTank V24*)
		rDayOilTank_ScalMax : REAL; (*PARA [14891]  OilTank V24*)
		bThR_Active : BOOL; (*PARA [12223]: thermal reactor active *) (* OldName:bExhReactor; Cycle: *)
		iHA_Pt100InputFilter : INT; (*PARA [13756]: 0=20ms(50Hz) 1=16.7ms(60Hz) *) (* OldName:new PV; Cycle: *)
		bU_Range : ARRAY[0..2]OF BOOL; (* PARA [11716]/[11717]: TRUE=400V, FALSE=100V input  *) (* OldName:bVoltRange; Cycle: *)
		bU_RangeBus : ARRAY[0..2]OF BOOL; (* PARA [11718]/[11719]: TRUE=400V, FALSE=100V input  *) (* OldName:bVoltRangeBus; Cycle: *)
		bU_RangeSync1 : ARRAY[0..2]OF BOOL; (* PARA [11720]/[11721]: TRUE=400V, FALSE=100V input  *) (* OldName:bVoltRangeSync1; Cycle: *)
		bU_RangeSync2 : ARRAY[0..2]OF BOOL; (* PARA [11722]/[11723]: TRUE=400V, FALSE=100V input  *) (* OldName:bVoltRangeSync1; Cycle: *)
		bI_CurrRange : ARRAY[0..2]OF BOOL; (* PARA [11711]/[11712]: TRUE=5A, FALSE=1A current input  *) (* OldName:bCurrRange; Cycle: *)
		bAron_Act : ARRAY[0..2]OF BOOL; (* PARA [11705]/[11706]: TRUE = aron input used  *) (* OldName:bAron; Cycle: *)
		bGen3PhaseCircuit_Act : ARRAY[0..2]OF BOOL; (* PARA [11709]/[11710]: TRUE= 3 wire circuit, FALSE= V circuit *) (* OldName:bGen3PhaseCircuit; Cycle: *)
		bBus3PhaseCircuit_Act : ARRAY[0..2]OF BOOL; (* PARA [11707]/[11708]: TRUE= 3 wire circuit, FALSE= V circuit *) (* OldName:bBus3PhaseCircuit; Cycle: *)
		bMMD2_Act : BOOL; (*PARA [11713]: Activation of 2nd MMD device *) (* OldName:bMMU2Act; Cycle: *)
		bMMDSynch_Act : ARRAY[0..2]OF BOOL; (* PARA [11714]/[11715]: synchronization of MMDsynch active *) (* OldName:bMMUSynchAct; Cycle: *)
		rMul_UL1L3 : ARRAY[0..2]OF REAL; (* PARA [11778]/[11779]: voltage input multiplikator *) (* OldName:usMulUL1L3; Cycle: *)
		rMul_IL1I3 : ARRAY[0..2]OF REAL; (* PARA [11768]/[11769]: current input multiplikator *) (* OldName:usMulIL1L3; Cycle: *)
		rU_Gen_Nom : ARRAY[0..2]OF REAL; (* PARA [11597]/[11598]: nominal voltage generator [70V..65kV] *) (* OldName:usUNennGen; Cycle: *)
		rV_Over : ARRAY[0..2]OF REAL; (* PARA [11861]/[11862]: monitoring limit over voltage *) (* OldName:usOVolt; Cycle: *)
		rTi_V_Over : ARRAY[0..2]OF REAL; (* PARA [11843]/[11844]: delay over voltage monitoring *) (* OldName:usOVoltDel; Cycle: *)
		rV_Under : ARRAY[0..2]OF REAL; (* PARA [11863]/[11864]: monitoring limit under voltage *) (* OldName:usUVolt; Cycle: *)
		rTi_V_Under : ARRAY[0..2]OF REAL; (* PARA [11845]/[11846]: delay under voltage monitoring *) (* OldName:usUVoltDel; Cycle: *)
		rV_Under2 : ARRAY[0..2]OF REAL; (* PARA [11865]/[11866]: monitoring limit under voltage *) (* OldName:usUVolt2; Cycle: *)
		rTi_V_Under2 : ARRAY[0..2]OF REAL; (* PARA [11847]/[11848]: delay under voltage monitoring *) (* OldName:usUVolt2Del; Cycle: *)
		rF_Nom : ARRAY[0..2]OF REAL; (* PARA [11736]/[11737]: nominal frequency [48..62Hz] *) (* OldName:usFreqNenn; Cycle: *)
		rF_Over : ARRAY[0..2]OF REAL; (* PARA [11738]/[11739]: monitoring limit over frequency *) (* OldName:usOFreq; Cycle: *)
		rTi_F_OverDel : ARRAY[0..2]OF REAL; (* PARA [11825]/[11826]: delay over frequency monitoring *) (* OldName:usOFreqDel; Cycle: *)
		rF_Under : ARRAY[0..2]OF REAL; (* PARA [11742]/[11743]: monitoring limit under frequency *) (* OldName:usUFreq; Cycle: *)
		rTi_F_UnderDel : ARRAY[0..2]OF REAL; (* PARA [11827]/[11828]: delay under frequncy monitoring *) (* OldName:usUFreqDel; Cycle: *)
		rU_Asym : ARRAY[0..2]OF REAL; (* PARA [11849]/[11850]: monitoring limit volt. asymetrie *) (* OldName:usVAsym; Cycle: *)
		rC_Asym : REAL;	(* PARA [15069]: monitoring limit current asymetrie *)
		rTi_U_AsymDel : ARRAY[0..2]OF REAL; (* PARA [11841]/[11842]: last monit. limit. volt. asymetrie *) (* OldName:usVAsymDel; Cycle: *)
		rTi_I_AsymDel : ARRAY[0..2]OF REAL; (* PARA [11829]/[11830]: delay current asymetrie monitoring *) (* OldName:usCAsymDel; Cycle: *)
		rI_GenNom : ARRAY[0..2]OF REAL; (* PARA [11750]/[11751]: nominal current generator [0..65kA] *) (* OldName:usINennGen; Cycle: *)
		rI_NomMax : ARRAY[0..2]OF REAL; (* PARA [11756]/[11757]: monitoring limit neutral current *) (* OldName:usCNMax; Cycle: *)
		rTi_I_NomMaxDel : ARRAY[0..2]OF REAL; (* PARA [11831]/[11832]: delay neutral current monitoring *) (* OldName:usCNMaxDel; Cycle: *)
		rI_Short : ARRAY[0..2]OF REAL; (* PARA [11762]/[11763]: monitoring limit short circuit *) (* OldName:usShort; Cycle: *)
		rTi_I_ShortDel : ARRAY[0..2]OF REAL; (* PARA [11833]/[11834]: delay short current monitoring *) (* OldName:usShortDel; Cycle: *)
		rI_Therm : ARRAY[0..2]OF REAL; (* PARA [11764]/[11765]: monitoring limit thermal overload *) (* OldName:usCTherm; Cycle: *)
		rInt_ThermOver : ARRAY[0..2]OF REAL; (* PARA [11766]/[11767]: integrator thermal overload monit. *) (* OldName:usIntValue; Cycle: *)
		rQ_Min : ARRAY[0..2]OF REAL; (* Para: min. reactive power monit. limit *) (* OldName:ssReactMin; Cycle: *)
		rTi_Q_MinDel : ARRAY[0..2]OF REAL; (* PARA [11835]/[11836]: delay reactive power monitoring *) (* OldName:usReactDel; Cycle: *)
		rMul_ImpValue : ARRAY[0..2]OF REAL; (* PARA [11770]/[11771]: work impulse factor [kW/imp] *) (* OldName:usImpVal; Cycle: *)
		rU_SyncNom : ARRAY[0..2]OF REAL; (* PARA [11859]/[11860]: nominal voltage sync1 & sync2 [70V..65kV] *) (* OldName:usUNennSync; Cycle: *)
		rU_BusNom : ARRAY[0..2]OF REAL; (* PARA [11851]/[11852]: nominal voltage bus [70V..65kV] *) (* OldName:usUNennBus; Cycle: *)
		rMul_U_Bus : ARRAY[0..2]OF REAL; (* PARA [11772]/[11773]: voltage input multiplikator bus *) (* OldName:usMulUBus; Cycle: *)
		rMul_U_Sync1 : ARRAY[0..2]OF REAL; (* PARA [11774]/[11775]: voltage input multiplikator synch 1 *) (* OldName:usMulUSync1; Cycle: *)
		rMul_U_Sync2 : ARRAY[0..2]OF REAL; (* PARA [11776]/[11777]: voltage input multiplikator synch 2 *) (* OldName:usMulUSync2; Cycle: *)
		rAng_PhiSync1 : ARRAY[0..2]OF REAL; (* PARA [11726]/[11727]: phase shift of sync1 *) (* OldName:usPhiSync1; Cycle: *)
		rF_DiffMax : ARRAY[0..2]OF REAL; (* PARA [11732]/[11733]: maximum frequence difference (positive) [0,02..0,49Hz] *) (* OldName:usFreqDiffMax; Cycle: *)
		rF_DiffMax_FSync : REAL; (* PARA [14863]: Maximal positive frequency difference for ultra fast synchronization [0,02..0,49Hz] *) (* OldName:new PV; Cycle: *)
		rF_DiffMin : ARRAY[0..2]OF REAL; (* PARA [11734]/[11735]: maximum frequence difference (negative) [-0,49..0,00Hz] *) (* OldName:ssFreqDiffMin; Cycle: *)
		rF_DiffMin_FSync : REAL; (* PARA [14864]: Maximal negative frequency difference for ultra fast synchronization [-0,49..0,00Hz] *) (* OldName:new PV; Cycle: *)
		rU_DiffMax : ARRAY[0..2]OF REAL; (* PARA [11857]/[11858]: maximum voltage difference [0,1% - 30% usUNennSync] *) (* OldName:usUDiffMax; Cycle: *)
		rAng_DiffMax : ARRAY[0..2]OF REAL; (* PARA [11724]/[11725]: maximum phase shift [0..60°] *) (* OldName:usPhiDiffMax; Cycle: *)
		rAng_DiffMax_FSync : REAL; (* PARA [14865]: Phase angle difference maximum for ultra fast synchronization [0.1..60°] *) (* OldName:new PV; Cycle: *)
		rTi_SynchImpMin : ARRAY[0..2]OF REAL; (* PARA [11837]/[11838]: minimum impulse width of DO4 [0,04..0,5s] *) (* OldName:usImpDO4Min; Cycle: *)
		rTi_SynchSwitchDel : ARRAY[0..2]OF REAL; (* PARA [11839]/[11840]: witching delay of the relay switched with DO4 [40..300ms] *) (* OldName:usSwitchDelDO4; Cycle: *)
		rU_DeadBus : ARRAY[0..2]OF REAL; (* PARA [11853]/[11854]: maximum voltage for dead bus detection DO3 *) (* OldName:usUdeadBus; Cycle: *)
		rU_DeadSync : ARRAY[0..2]OF REAL; (* PARA [11855]/[11856]: maximum voltage for sync mode 'dead bus' detection *) (* OldName:usUdeadSync; Cycle: *)
		rGT_CH4ScalMin : REAL; (*PARA [11745]: measure range start CH4 signal *) (* OldName:MBA_CH4; Cycle: *)
		rGT_CH4ScalMax : REAL; (*PARA [11744]: measure range end CH4 signal *) (* OldName:MBE_CH4; Cycle: *)
		rGT_CVScalMin : REAL; (*PARA [11747]: measure range start CV signal *) (* OldName:MBA_CV; Cycle: *)
		rGT_CVScalMax : REAL; (*PARA [11746]: measure range end CV signal *) (* OldName:MBE_CV; Cycle: *)
		rPr_GT_GasPrScalMin : REAL; (*PARA [11811]: measure range start GD signal *) (* OldName:MBA_GD; Cycle: *)
		rPr_GT_GasPrScalMax : REAL; (*PARA [11810]: measure range end GD signal *) (* OldName:MBE_GD; Cycle: *)
		rVol_GT_ScalMin : REAL; (*PARA [11868]: measure range start GM signal *) (* OldName:MBA_GM; Cycle: *)
		rVol_GT_ScalMax : REAL; (*PARA [11867]: measure range end GM signal *) (* OldName:MBE_GM; Cycle: *)
		rT_GT_ScalMin : REAL; (*PARA [11821]: measure range start GT signal *) (* OldName:MBA_GT; Cycle: *)
		rT_GT_ScalMax : REAL; (*PARA [11820]: measure range end GT signal *) (* OldName:MBE_GT; Cycle: *)
		rGT_O2ScalMin : REAL; (*PARA [11749]: measure range start O2 signal *) (* OldName:MBA_O2; Cycle: *)
		rGT_O2ScalMax : REAL; (*PARA [11748]: measure range end O2 signal *) (* OldName:MBE_O2; Cycle: *)
		rPr_GT_SuctPrScalMin : REAL; (*PARA [11813]: measure range start SD signal *) (* OldName:MBA_SD; Cycle: *)
		rPr_GT_SuctPrScalMax : REAL; (*PARA [11812]: measure range end SD signal *) (* OldName:MBE_SD; Cycle: *)
		rP_Red_NormScalMinI : REAL; (*PARA [11792]: measure range start P red mA signal *) (* OldName:loads_i1; Cycle: *)
		rP_Red_NormScalMaxI : REAL; (*PARA [11790]: measure range end P red mA  signal *) (* OldName:loads_i2; Cycle: *)
		rP_Red_NormScalMinP : REAL; (*PARA [11793]: measure range start P red P signal *) (* OldName:loads_p1; Cycle: *)
		rP_Red_NormScalMaxP : REAL; (*PARA [11791]: measure range end P red P  signal *) (* OldName:loads_p2; Cycle: *)
		rPr_EngLubOilScalMax : REAL; (*PARA [11807]: measure range end oil pressure  signal *) (* OldName:MBE_ODR; Cycle: *)
		rPr_ECWScalMax : REAL; (*PARA [11806]: measure range end cooling water pressure  signal *) (* OldName:MBE_KWD; Cycle: *)
		rPr_Ch_P2sScalMin : REAL; (*PARA [11805]: measure range start charge pressure signal *) (* OldName:anp_pl.y1; Cycle: *)
		rPr_Ch_P2sScalMax : REAL; (*PARA [11804]: measure range end charge pressure signal *) (* OldName:anp_pl.y2; Cycle: *)
		rPr_CCScalMin : REAL; (*PARA [11799]: pressure crank case measuring signal range begin *) (* OldName:MBA_p_CC; Cycle: *)
		rPr_CCScalMax : REAL; (*PARA [11798]: pressure crank case measuring signal range end *) (* OldName:MBE_p_CC; Cycle: *)
		rPr_Ch_P2ScalMin : REAL; (*PARA [11803]: measure range start charge pressure signal *) (* OldName:anp_p2.y1; Cycle: *)
		rPr_Ch_P2ScalMax : REAL; (*PARA [11802]: measure range end charge pressure signal *) (* OldName:anp_p2.y2; Cycle: *)
		rPr_Ch_P2LPScalMin : REAL; (*PARA [13485]: measure range start charge pressure signal *) (* OldName:new PV; Cycle: *) (*V04.04.00.00*)
		rPr_Ch_P2LPScalMax : REAL; (*PARA [13486]: measure range end charge pressure signal *) (* OldName:new PV; Cycle: *) (*V04.04.00.00*)
		rPr_Ch_P2HPScalMin : REAL; (*PARA [13482]: measure range start charge pressure signal *) (* OldName:new PV; Cycle: *) (*V04.04.00.00*)
		rPr_Ch_P2HPScalMax : REAL; (*PARA [13483]: measure range end charge pressure signal *) (* OldName:new PV; Cycle: *) (*V04.04.00.00*)
		rPr_Ch_P2bFAScalMin : REAL; (*PARA [13479]: measure range start charge pressure signal *) (* OldName:new PV; Cycle: *) (*V04.04.00.00*)
		rPr_Ch_P2bFAScalMax : REAL; (*PARA [13480]: measure range end charge pressure signal *) (* OldName:new PV; Cycle: *) (*V04.04.00.00*)
		rPr_EOF_DiffMonScalMin : REAL; (*PARA [11809]: Oil pressure at 4mA *) (* OldName:ssOilPbFilter4mA; Cycle: *)
		rPr_EOF_DiffMonScalMax : REAL; (*PARA [11808]: Oil pressure at 20mA *) (* OldName:ssOilPbFilter20mA; Cycle: *)
		rT_HW_ReScalMin : REAL; (*PARA [xxxxx11823]: temperature heat water return at min mA *) (* OldName:NewPV V4.14; Cycle: *)
		rT_HW_ReScalMax : REAL; (*PARA [11823]: temperature heat water return at 20mA *) (* OldName:MBE_RLTP; Cycle: *)
		rT_HW_ReAfECScalMin : REAL; (*PARA [xxxxxx11822]: temperature heat water return after emergency cooler at min mA *) (* OldName:NewPV V4.14; Cycle: *)
		rT_HW_ReAfECScalMax : REAL; (*PARA [11822]: temperature heat water return after emergency cooler at 20mA *) (* OldName:MBE_RLT_NK; Cycle: *)
		rT_HW_SuScalMin : REAL; (*PARA [xxxxx11824]: temperature heat water supply at min mA *) (* OldName:MBE_VLTP; Cycle: *)
		rT_HW_SuScalMax : REAL; (*PARA [11824]: temperature heat water supply at 20mA *) (* OldName:MBE_VLTP; Cycle: *)
		rI_IgnP_SetScalMin : REAL; (*PARA [11753]: timing point  mA point 1 *) (* OldName:zzp_i1; Cycle: *)
		rI_IgnP_SetScalMax : REAL; (*PARA [11752]: timing point  mA point 2 *) (* OldName:zzp_i2; Cycle: *)
		rCA_IgnP_SetScalMin : REAL; (*PARA [11729]: timing point °CA point 1 *) (* OldName:zzp_p1; Cycle: *)
		rCA_IgnP_SetScalMax : REAL; (*PARA [11728]: timing point °CA point 2 *) (* OldName:zzp_p2; Cycle: *)
		rDPr_AirFiltScalMin : REAL; (*PARA [11731]: charge air filter difference pressure at 4mA *) (* OldName:MBA_dp_AirInFilt; Cycle: *)
		rDPr_AirFiltScalMax : REAL; (*PARA [11730]: charge air filter difference pressure at 20mA *) (* OldName:MBE_dp_AirInFilt; Cycle: *)
		rN_TCHPScalMin : REAL; (*PARA [11783]: High pressure turbocharger speed at 4mA *) (* OldName:ssTurboSpdA4mA, ssTurboSpdB4mA; Cycle: *)
		rN_TCHPScalMax : REAL; (*PARA [11782]: High pressure turbocharger speed at 20mA *) (* OldName:ssTurboSpdA20mA, ssTurboSpdB20mA; Cycle: *)
		rN_TCLPScalMin : REAL; (*PARA [11785]: Low pressure turbocharger speed at 4mA *) (* OldName:ssTurboSpd_LP_A4mA, ssTurboSpd_LP_B4mA; Cycle: *)
		rN_TCLPScalMax : REAL; (*PARA [11784]: Low pressure turbocharger speed at 20mA *) (* OldName:ssTurboSpd_LP_A20mA, ssTurboSpd_LP_B20mA; Cycle: *)
		rPr_Ch_P1LPScalMin : REAL; (*PARA [13487]: charge pressure before  low press TC at 4mA *) (* OldName:new PV; Cycle: *) (*V04.04.00.00*)
		rPr_Ch_P1LPScalMax : REAL; (*PARA [13488]: charge pressure before  low press TC at 20mA *) (* OldName:new PV; Cycle: *) (*V04.04.00.00*)
		rPr_Ch_P1HPScalMin : REAL; (*PARA [11801]: charge pressure before high press TC at 4mA *) (* OldName:new PV; Cycle: *)
		rPr_Ch_P1HPScalMax : REAL; (*PARA [11800]: charge pressure before high press TC at 20mA *) (* OldName:new PV; Cycle: *)
		rF_stepGM1 : REAL; (*PARA [11740]: half-step frequency [Hz]  *) (* OldName:lox_speed; Cycle: *)
		rF_stepGM2 : REAL; (*PARA [11741]: half-step frequency [Hz]  *) (* OldName:lox_speed1; Cycle: *)
		iNum_GM : INT; (*PARA [11357]: number of gasmixer  *) (* OldName:AnzGasm; Cycle: *)
		rPr_PCScalMin : REAL; (*PARA [11819]: pressure prechamber measuring signal at 4mA *) (* OldName:MBA_PDIFF; Cycle: *)
		rPr_PCScalMax : REAL; (*PARA [11818]: pressure prechamber measuring signal at 20mA *) (* OldName:MBE_PDIFF; Cycle: *)
		rPr_BaroScalMin : REAL; (*PARA [11797]: barometric pressure at 4mA *) (* OldName:MBA_p_Baro; Cycle: *)
		rPr_BaroScalMax : REAL; (*PARA [11796]: barometric pressure at 20mA *) (* OldName:MBE_p_Baro; Cycle: *)
		rPr_GT1ScalMin : REAL; (*PARA [11815]: gas pressure gas train 1 after filter at 4mA *) (* OldName:MBA_p_GT1; Cycle: *)
		rPr_GT1ScalMax : REAL; (*PARA [11814]: gas pressure gas train 1 after filter at 20mA *) (* OldName:MBE_p_GT1; Cycle: *)
		rP_Act_AOScalMin : REAL; (*PARA [11787]: Actual power at  4mA *) (* OldName:ssPow0mA; Cycle: *)
		rP_Act_AOScalMax : REAL; (*PARA [11786]: Actual power at 20mA *) (* OldName:ssPow20mA; Cycle: *)
		rI_P_Red_AI_NormScalMin : REAL; (*PARA [11759]: power reduction by analog input mA at point 1 *) (* OldName: p_red_i1; Cycle: *)
		rI_P_Red_AI_NormScalMax : REAL; (*PARA [11758]: power reduction by analog input mA at point 2 *) (* OldName:p_red_i2; Cycle: *)
		rP_Red_AI_NormScalMin : REAL; (*PARA [11789]: power reduction by analog input P at point 1 *) (* OldName:p_red_p1; Cycle: *)
		rP_Red_AI_NormScalMax : REAL; (*PARA [11788]: power reduction by analog input P at point 2 *) (* OldName:p_red_p2; Cycle: *)
		rI_P_Set_ExtAI_NormScalMin : REAL; (*PARA [11761]: external power setpoint via analog input related to rP_Nom mA at point 1 *) (* OldName:p_soll_i1; Cycle: *)
		rI_P_Set_ExtAI_NormScalMax : REAL; (*PARA [11760]: external power setpoint via analog input related to rP_Nom mA at point 2 *) (* OldName:p_soll_i2; Cycle: *)
		rP_Set_ExtAI_NormScalMin : REAL; (*PARA [11795]: external power setpoint via analog input related to rP_Nom P at point 1 *) (* OldName:p_soll_p1; Cycle: *)
		rP_Set_ExtAI_NormScalMax : REAL; (*PARA [11794]: external power setpoint via analog input related to rP_Nom P at point 2 *) (* OldName:p_soll_p2; Cycle: *)
		rI_N_Set_ExtAI_NormScalMin : REAL; (*PARA [11755]: external speed setpoint via analog input related to rN_EngNom mA at point 1 *) (* OldName:n_i1; Cycle: *)
		rI_N_Set_ExtAI_NormScalMax : REAL; (*PARA [11754]: external speed setpoint via analog input related to rN_EngNom mA at point 2 *) (* OldName:n_i2; Cycle: *)
		rN_Set_ExtAI_NormScalMin : REAL; (*PARA [11781]: external speed setpoint via analog input related to rN_EngNom N at point 1 *) (* OldName:n_p1; Cycle: *)
		rN_Set_ExtAI_NormScalMax : REAL; (*PARA [11780]: external speed setpoint via analog input related to rN_EngNom N at point 2 *) (* OldName:n_p2; Cycle: *)
		iEng_Motortype : INT; (* Para: Engine type *) (* OldName:motortyp; Cycle: *)
		bCustAnaIn_Set4mA : ARRAY[0..120]OF BOOL; (* = RAN1_lz to RAN16_lz	-	reserve channel bit to activate 4-20mA scaling (0=0-20mA)	*) (*OldName: RAN1_lz, RAN2_lz, RAN1_l6z; Cycle:;*)
		rCustAnaIn_ScalMax : ARRAY[0..120]OF REAL; (* = OBGR_RAN1 to OBERGR_RAN16	-	reserve channel raw signal scaling	*) (*OldName: OBGR_RAN1, OBGR_RAN2, OBGR_RAN16; Cycle:;*)
		rCustAnaIn_ScalMin : ARRAY[0..120]OF REAL; (* = 	UNGR_RAN1 to UNERGR_RAN16	-	reserve channel raw signal scaling	*) (*OldName: UNGR_RAN1, UNGR_RAN2, UNGR_RAN16; Cycle:;*)
		rCustAnaOut_ScalMin : ARRAY[0..60]OF REAL; (* =  AnalogOUT reserve channel raw signal scaling*) (*OldName: new PV; Cycle:;*)
		rCustAnaOut_ScalMax : ARRAY[0..60]OF REAL; (* =  AnalogOUT reserve channel raw signal scaling	*) (*OldName: new PV; Cycle:;*)
		rCtr_CustOut_ScalMin : ARRAY[0..45]OF REAL; (* AnalogOUT reserve CONTROLLER signal scaling (outdated)*) (*OldName: new PV; Cycle:;*)
		rCtr_CustOut_ScalMax : ARRAY[0..45]OF REAL; (*AnalogOUT reserve CONTROLLER signal scaling (outdated)*) (*OldName: new PV; Cycle:;*)
		rPr_PCGTScalMin : REAL; (*PARA [11817]: measure range start gas pressure pre chamber gas train after filter signal *) (* OldName:MBA_PCGT; Cycle: *)
		rPr_PCGTScalMax : REAL; (*PARA [11816]: measure range end gas pressure pre chamber gas train after filter signal *) (* OldName:MBE_PCGT; Cycle: *)
		zz_V4_0_ParaVersionEnd : REAL := 4.0; (*! ADD NEW PARAMETER ONLY BELOW THIS LINE ! This is the end of base version parameter and has to stay unchanged. DO NOT CHANGE SORT ORDER of Para!*) (* OldName: new PV; Cycle:; *)
		rI_CustAnaOut_ScalMin : ARRAY[0..60]OF REAL; (*Hardware Side scaling 0-20mA in [mA]*) (* OldName: new PV; Cycle:; *)
		rI_CustAnaOut_ScalMax : ARRAY[0..60]OF REAL; (*Hardware Side scaling 0-20mA in [mA]*) (* OldName: new PV; Cycle:; *)
		rI_Ctr_CustOut_ScalMin : ARRAY[0..45]OF REAL; (*Hardware Side scaling 0-20mA in [mA]*) (* OldName: new PV; Cycle:; *)
		rI_Ctr_CustOut_ScalMax : ARRAY[0..45]OF REAL; (*Hardware Side scaling 0-20mA in [mA]*) (* OldName: new PV; Cycle:; *)
		szOrderID : STRING[17]; (*Para: application ID string*) (*OldName:szApplication; Cycle: *)
		rPr_HW_Su_LT_ScalMax : REAL; (*PARA [12617]: supply water LT pressure at 20mA*) (* OldName:new PV; Cycle: *)
		rPr_HW_Su_HT_ScalMax : REAL; (*PARA [12646]: supply water HT pressure at 20mA*) (* OldName:new PV; Cycle: *)
		rPr_PCGT_OutScalMin : REAL; (*PARA [12479]: AI gas pressure after pre chamber gas pressure regulator at 4mA *) (* OldName: AI_p_PCGT_Out; Cyclic:; *)
		rPr_PCGT_OutScalMax : REAL; (*PARA [12480]: AI gas pressure after pre chamber gas pressure regulator at 4mA *) (* OldName: AI_p_PCGT_Out; Cyclic:; *)
		rPr_GR_IScalMin : REAL; (*PARA [12803]: AI Gas Pressure in Gas Rail number 1 at 4mA *) (* OldName: AIPressGasRail	; Cyclic:; *)
		rPr_GR_IScalMax : REAL; (*PARA [12804]: AI Gas Pressure in Gas Rail number 1 at 4mA *) (* OldName: AIPressGasRail	; Cyclic:; *)
		rPr_MGT_spScalMin : REAL; (*PARA [12466]: AO pressure gas rail set point with Offset considered at 4mA*) (*OldName:rPr_MGT_sp; Cycle:;*)
		rPr_MGT_spScalMax : REAL; (*PARA [12467]: AO pressure gas rail set point with Offset considered at 4mA*) (*OldName:rPr_MGT_sp; Cycle:;*)
		rPr_PCGT_spScalMin : REAL; (*PARA [12525]: AO main gas train pressure - set point with Offset considered at 4mA*) (*OldName:rPr_PCGT_sp; Cycle:;*)
		rPr_PCGT_spScalMax : REAL; (*PARA [12526]: AO main gas train pressure - set point with Offset considered at 4mA*) (*OldName:rPr_PCGT_sp; Cycle:;*)
		rFlow_OilSkid_DEScalMax : REAL; (*PARA [12545]: Oil flow to DE storage at 20mA	*) (*OldName:newPv; Cycle:;*)
		rFlow_OilSkid_DEScalMin : REAL; (*PARA [12544]: Oil flow to DE storage at 4mA	*) (*OldName:newPv; Cycle:;*)
		rFlow_OilSkid_NDEScalMax : REAL; (*PARA [12550]: Oil flow to NDE storage at 20mA	*) (*OldName:newPv; Cycle:;*)
		rFlow_OilSkid_NDEScalMin : REAL; (*PARA [12549]: Oil flow to NDE storage at 4mA	*) (*OldName:newPv; Cycle:;*)
		rLev_OilSkid_TankScalMax : REAL; (*PARA [12531]: Oil tank level at 20mA	*) (*OldName:newPv; Cycle:;*)
		rLev_OilSkid_TankScalMin : REAL; (*PARA [12530]: Oil tank level  at 4mA	*) (*OldName:newPv; Cycle:;*)
		rPr_OilSkid_HPScalMax : REAL; (*PARA [12555]: Oil pressure in high pressure circle at 20mA	*) (*OldName:newPv; Cycle:;*)
		rPr_OilSkid_HPScalMin : REAL; (*PARA [12554]: Oil pressure in high pressure circle at 0mA	*) (*OldName:newPv; Cycle:;*)
		rT_OilSkid_SupplyScalMax : REAL; (*PARA [12540]: Oil pre-temperaure active 20mA (Ã–lvorlauftemperatur) 	*) (*OldName:newPv; Cycle:;*)
		rT_OilSkid_SupplyScalMin : REAL; (*PARA [12539]: Oil pre-temperaure at 4mA (Ã–lvorlauftemperatur) 	*) (*OldName:newPv; Cycle:;*)
		rT_OilSkid_TankScalMax : REAL; (*PARA [12536]: Oil tank temperature at 20mA	*) (*OldName:newPv; Cycle:;*)
		rT_OilSkid_TankScalMin : REAL; (*PARA [12535]: Oil tank temperature at 4mA	*) (*OldName:newPv; Cycle:;*)
		rPr_f_BbFiltScalMin : REAL; (*PARA [12567]: Druck vor Blow-by Filter bei 4mA, Pressure befor Blow-by filter	*) (* Oldname: newPv, Cycle: *)
		rPr_f_BbFiltScalMax : REAL; (*PARA [12568]: Druck vor Blow-by Filter bei 20mA, Pressure befor Blow-by filter 	*) (* Oldname: newPv, Cycle:*)
		rPr_a_BbFiltScalMin : REAL; (*PARA [12570]: Druck nach Blow-by Filter bei 4mA, Pressure after Blow-by filter	*) (* Oldname: newPv, Cycle:*)
		rPr_a_BbFiltScalMax : REAL; (*PARA [12569]: Druck nach Blow-by Filter bei 20mA, Pressure after Blow-by filter	*) (* Oldname: newPv, Cycle:*)
		szEng_Motorversion : STRING[17]; (* Para: Engine version *) (* OldName:newPv; Cycle: *)
		rPr_AirStarter_TankScalMin : REAL; (*PARA [12649]: air starter tank pressure at 4mA [bar]*) (* OldName:newPv; Cycle: *)
		rPr_AirStarter_TankScalMax : REAL; (*PARA [12650]: air starter tank pressure at 20mA [bar]*) (* OldName:newPv; Cycle: *)
		rPr_AirStarter_SupplyScalMin : REAL; (*PARA [12652]: air starter supply pressure at 4mA [bar]	*) (* OldName:newPv; Cycle: *)
		rPr_AirStarter_SupplyScalMax : REAL; (*PARA [12653]: air starter supply pressure at 20mA [bar] *) (* OldName:newPv; Cycle: *)
		rF_GenBear_ScalMin : REAL; (*PARA [12710]: vibration generator bearing at 4mA *) (* Oldname: MBA_v_GenBear, Cycle:*)
		rF_GenBear_ScalMax : REAL; (*PARA [12711]: vibration generator bearing at 20mA *) (* Oldname: MBE_v_GenBear, Cycle:*)
		rPr_ECWaEng_ScalMax : REAL; (*PARA [12740]: cool water pressure after engine at 20mA *) (* Oldname: MBE_v_GenBear, Cycle:*)
		rPr_EOF_After_ScalMin : REAL; (*PARA [12745]: oil pressure after filter at 4mA *) (* Oldname: newPv, Cycle:*)
		rPr_EOF_After_ScalMax : REAL; (*PARA [12746]: oil pressure after filter at 20mA *) (* Oldname: newPv, Cycle:*)
		rPr_TCObF_ScalMin : REAL; (*PARA [12743]: Oil pressure in front of turbocharger oil filter at 4mA *) (* Oldname: newPv, Cycle:*)
		rPr_TCObF_ScalMax : REAL; (*PARA [12744]: Oil pressure in front of turbocharger oil filter at 20mA *) (* Oldname: newPv, Cycle:*)
		rCO_SCR_EMLine1ScalMax : REAL; (*PARA [13936]: SCR Emission measurement line 1 - CO at 20mA [ppm]*) (*OldName: rCO_SCR_ScalMax; Cycle: 1;*) (*V04.05.00.00*)
		rCO_SCR_EMLine1ScalMin : REAL; (*PARA [13935]: SCR Emission measurement line 1 - CO at 4mA [ppm]*) (*OldName: rCO_SCR_ScalMin; Cycle: 1;*) (*V04.05.00.00*)
		rFlow_SCR_UreaDosingOutScalMax : REAL; (*PARA [13881]: SCR Urea flow rate after dosing at 20mA [l/h]*) (*OldName: rFlow_Urea_ScalMax; Cycle: 1;*) (*V04.05.00.00*)
		rFlow_SCR_UreaDosingOutScalMin : REAL; (*PARA [13880]: SCR Urea flow rate after dosing at 4mA [l/h]*) (*OldName: rFlow_Urea_ScalMin; Cycle: 1;*) (*V04.05.00.00*)
		rNO_SCR_EMLine1ScalMax : REAL; (*PARA [13929]: SCR Emission measurement line 1 - NO at 20mA [ppm]*) (*OldName: rNO_SCR_ScalMax; Cycle: 1;*) (*V04.05.00.00*)
		rNO_SCR_EMLine1ScalMin : REAL; (*PARA [13928]: SCR Emission measurement line 1 - NO at 4mA [ppm]*) (*OldName: rNO_SCR_ScalMin; Cycle: 1;*) (*V04.05.00.00*)
		rNO_SCR_EMLine2ScalMax : REAL; (*PARA [13943]: SCR Emission measurement line 2 - NO at 20mA [ppm]*) (*OldName: rNO_Ctrl_SCR_ScalMax; Cycle: 1;*) (*V04.05.00.00*)
		rNO_SCR_EMLine2ScalMin : REAL; (*PARA [13942]: SCR Emission measurement line 2 - NO at 4mA [ppm]*) (*OldName: rNO_Ctrl_SCR_ScalMin; Cycle: 1;*) (*V04.05.00.00*)
		rNO2_SCR_EMLine1ScalMax : REAL; (*PARA [13932]: SCR Emission measurement line 1 - NO2 at 20mA [ppm]*) (*OldName: rNO2_SCR_ScalMax; Cycle: 1;*) (*V04.05.00.00*)
		rNO2_SCR_EMLine1ScalMin : REAL; (*PARA [13931]: SCR Emission measurement line 1 - NO2 at 4mA [ppm]*) (*OldName: rNO2_SCR_ScalMin; Cycle: 1;*) (*V04.05.00.00*)
		rNO2_SCR_EMLine2ScalMax : REAL; (*PARA [13946]: SCR Emission measurement line 2 - NO2 at 20mA [ppm]*) (*OldName: new PV; Cycle: 1;*) (*V04.05.00.00*)
		rNO2_SCR_EMLine2ScalMin : REAL; (*PARA [13945]: SCR Emission measurement line 2 - NO2 at 4mA [ppm]*) (*OldName: new PV; Cycle: 1;*) (*V04.05.00.00*)
		rO2_SCR_EMLine1ScalMax : REAL; (*PARA [13939]: SCR Emission measurement line 1 - O2 at 20mA [Vol-%]*) (*OldName: new PV; Cycle: 1;*) (*V04.05.00.00*)
		rO2_SCR_EMLine1ScalMin : REAL; (*PARA [13938]: SCR Emission measurement line 1 - O2 at 4mA [Vol-%]*) (*OldName: new PV; Cycle: 1;*) (*V04.05.00.00*)
		rPr_SCR_CatScalMax : REAL; (*PARA [13904]: SCR Exhaust pressure CAT at 20mA [bar]*) (*OldName: rPr_SCR_In_ScalMax, rPr_SCR_Out_ScalMax; Cycle: 1;*) (*V04.05.00.00*)
		rPr_SCR_CatScalMin : REAL; (*PARA [13903]: SCR Exhaust pressure CAT at 4mA [bar]*) (*OldName: rPr_SCR_In_ScalMin, rPr_SCR_Out_ScalMin; Cycle: 1;*) (*V04.05.00.00*)
		rPr_SCR_ComprAirSupplyScalMax : REAL; (*PARA [13893]: SCR Compressed air supply pressure urea injection at 20mA [bar]*) (*OldName: rPr_AirSupply_ScalMax; Cycle: 1;*) (*V04.05.00.00*)
		rPr_SCR_ComprAirSupplyScalMin : REAL; (*PARA [13892]: SCR Compressed air supply pressure urea injection at 4mA [bar]*) (*OldName: rPr_AirSupply_ScalMin; Cycle: 1;*) (*V04.05.00.00*)
		rPr_SCR_UreaDosingInScalMax : REAL; (*PARA [13864]: SCR Urea pressure before dosing at 20mA [bar]*) (*OldName: new PV; Cycle: 1;*) (*V04.05.00.00*)
		rPr_SCR_UreaDosingInScalMin : REAL; (*PARA [13863]: SCR Urea pressure before dosing at 4mA [bar]*) (*OldName: new PV; Cycle: 1;*) (*V04.05.00.00*)
		rPr_SCR_UreaDosingOutScalMax : REAL; (*PARA [13876]: SCR Urea pressure after dosing at 20mA [bar]*) (*OldName: rPr_Urea_ScalMax; Cycle: 1;*) (*V04.05.00.00*)
		rPr_SCR_UreaDosingOutScalMin : REAL; (*PARA [13875]: SCR Urea pressure after dosing at 4mA [bar]*) (*OldName: rPr_Urea_ScalMin; Cycle: 1;*) (*V04.05.00.00*)
		rT_SCR_CatScalMax : REAL; (*PARA [13898]: SCR Exhaust temperature CAT at 20 mA [°C]*) (*OldName: rT_SCR_In_ScalMax, rT_SCR_Out_ScalMax; Cycle: 1;*) (*V04.05.00.00*)
		rT_SCR_CatScalMin : REAL; (*PARA [13897]: SCR Exhaust temperature CAT at 4mA [°C]*) (*OldName: rT_SCR_In_ScalMin, rT_SCR_Out_ScalMin; Cycle: 1;*) (*V04.05.00.00*)
		rPos_InlLou1_ScalMin : REAL; (*PARA [13070]: position air inlet louver 1 at 4mA*) (* Oldname: newPv, Cycle:*) (*STM*)
		rPos_InlLou1_ScalMax : REAL; (*PARA [13071]: position air inlet louver 1 at 20mA*) (* Oldname: newPv, Cycle:*) (*STM*)
		rPos_InlLou2_ScalMin : REAL; (*PARA [13073]: position air inlet louver 2 at 4mA*) (* Oldname: newPv, Cycle:*) (*STM*)
		rPos_InlLou2_ScalMax : REAL; (*PARA [13074]: position air inlet louver 2 at 20mA*) (* Oldname: newPv, Cycle:*) (*STM*)
		rPos_OutlLou1_ScalMin : REAL; (*PARA [13081]: position air outlet louver 1 at 4mA*) (* Oldname: newPv, Cycle:*) (*STM*)
		rPos_OutlLou1_ScalMax : REAL; (*PARA [13080]: position air outlet louver 1 at 20mA*) (* Oldname: newPv, Cycle:*) (*STM*)
		rPos_OutlLou2_ScalMin : REAL; (*PARA [13083]: position air outlet louver 2 at 4mA*) (* Oldname: newPv, Cycle:*) (*STM*)
		rPos_OutlLou2_ScalMax : REAL; (*PARA [13082]: position air outlet louver 2 at 20mA*) (* Oldname: newPv, Cycle:*) (*STM*)
		rPos_CircLou1_ScalMin : REAL; (*PARA [13139]: position air circulation louver at 4mA*) (* Oldname: newPv, Cycle:*) (*STM*)
		rPos_CircLou1_ScalMax : REAL; (*PARA [13140]: position air circulation louver at 20mA*) (* Oldname: newPv, Cycle:*) (*STM*)
		rPos_CircLou2_ScalMin : REAL; (*PARA [13141]: position air circulation louver at 4mA*) (* Oldname: newPv, Cycle:*) (*STM*)
		rPos_CircLou2_ScalMax : REAL; (*PARA [13142]: position air circulation louver at 20mA*) (* Oldname: newPv, Cycle:*) (*STM*)
		rPrDiff_ER_ScalMin : REAL; (*PARA [13086]: engine room difference pressure at 4mA*) (* Oldname: newPv, Cycle:*) (*STM 2*)
		rPrDiff_ER_ScalMax : REAL; (*PARA [13087]: engine room difference pressure at 20mA*) (* Oldname: newPv, Cycle:*) (*STM 2*)
		rPos_HW_ReValve_ScalMin : REAL; (*PARA [13149]: position heating water return temperature regulation valve at 4mA*) (* Oldname: newPv, Cycle:*) (*STM*)
		rPos_HW_ReValve_ScalMax : REAL; (*PARA [13150]: position heating water return temperature regulation valve at 20mA*) (* Oldname: newPv, Cycle:*) (*STM*)
		rPos_HW_EC_ReValve_ScalMin : REAL; (*PARA [13151]: position heating water return temperature after cooler regulation valve at 4mA*) (* Oldname: newPv, Cycle:*) (*STM*)
		rPos_HW_EC_ReValve_ScalMax : REAL; (*PARA [13152]: position heating water return temperature after cooler regulation valve at 20mA*) (* Oldname: newPv, Cycle:*) (*STM*)
		rPos_ChC_Valve_ScalMin : REAL; (*PARA [13153]: position charge temperature regulation valve at 4mA*) (* Oldname: newPv, Cycle:*) (*STM*)
		rPos_ChC_Valve_ScalMax : REAL; (*PARA [13154]: position charge temperature regulation valve at 20mA*) (* Oldname: newPv, Cycle:*) (*STM*)
		rP_Heat_ScalMin : REAL; (*PARA [13168]: heating power engine heat water circuit at 4mA*) (* Oldname: newPv, Cycle:*) (*STM 2*)
		rP_Heat_ScalMax : REAL; (*PARA [13169]: heating power engine heat water circuit at 20mA*) (* Oldname: newPv, Cycle:*) (*STM 2*)
		rPr_EO_Mod_Out_ScalMin : REAL; (*PARA [12905]: pressure engine oil module outlet 4mA M.03-PI-006*) (* Oldname: newPv, Cycle:*)
		rPr_EO_Mod_Out_ScalMax : REAL; (*PARA [12906]: pressure engine oil module outlet 20mA M.03-PI-006*) (* Oldname: newPv, Cycle:*)
		rPr_HW_Re_LT_ScalMin : REAL; (*PARA [12893]: pressure heat water return low temp.circuit 4mA M.07-PI-002*) (* Oldname: newPv, Cycle:*)
		rPr_HW_Re_LT_ScalMax : REAL; (*PARA [12894]: pressure heat water return low temp.circuit 20mA M.07-PI-002*) (* Oldname: newPv, Cycle:*)
		rPr_HW_Re_HT_ScalMin : REAL; (*PARA [12896]: pressure heat water return high temp.circuit 4mA M.06-PI-002*) (* Oldname: newPv, Cycle:*)
		rPr_HW_Re_HT_ScalMax : REAL; (*PARA [12897]: pressure heat water return high temp.circuit 20mA M.06-PI-002*) (* Oldname: newPv, Cycle:*)
		rPr_HW_Re_PreH_ECW_ScalMin : REAL; (*PARA [12899]: pressure heat water return preheating engine cooling water 4mA M.04-PI-005*) (* Oldname: newPv, Cycle:*)
		rPr_HW_Re_PreH_ECW_ScalMax : REAL; (*PARA [12900]: pressure heat water return preheating engine cooling water 20mA M.04-PI-005*) (* Oldname: newPv, Cycle:*)
		rPr_HW_Re_PreH_EO_ScalMin : REAL; (*PARA [12902]: pressure heat water return preheating engine oil 4mA M.03-PI-005*) (* Oldname: newPv, Cycle:*)
		rPr_HW_Re_PreH_EO_ScalMax : REAL; (*PARA [12903]: pressure heat water return preheating engine oil 20mA M.03-PI-005*) (* Oldname: newPv, Cycle:*)
		rPr_OFUbFilt_ScalMin : REAL; (*PARA [13472]: pressure oil filter unit before filter at 4mA M.03-PI-011*) (* Oldname: newPv, Cycle:*)
		rPr_OFUbFilt_ScalMax : REAL; (*PARA [13473]: pressure oil filter unit before filter at 20mA M.03-PI-011*) (* Oldname: newPv, Cycle:*)
		rPr_OFUaFilt_ScalMin : REAL; (*PARA [13475]: pressure oil filter unit after filter at 4mA M.03-PI-012*) (* Oldname: newPv, Cycle:*)
		rPr_OFUaFilt_ScalMax : REAL; (*PARA [13476]: pressure oil filter unit after filter at 20mA M.03-PI-012*) (* Oldname: newPv, Cycle:*)
		rPr_OFUbCentrifuge_ScalMin : REAL; (*PARA [13632]: pressure oil filter unit before centrifuge at 4mA M.03-PI-008*) (* Oldname: newPv, Cycle:*)
		rPr_OFUbCentrifuge_ScalMax : REAL; (*PARA [13633]: pressure oil filter unit before centrifuge at 20mA M.03-PI-008*) (* Oldname: newPv, Cycle:*)
		iCustAnaIn_Typ : ARRAY[0..120]OF INT; (*= code to define the type  to reserve channel: 1 ... 0-20mA, 2 ... 4-20mA, 3 ... 0-10V, 4 ... 2-10V, 5 ... Pt100, 6 ... NiCr-Ni, 7 ... 0-5V, 8 ... -10/10V*) (*OldName: RAN1_TYP, RAN2_TYP, RAN16_TYP; Cycle: *)
		rP_DEIE_ScalMin : REAL; (*PARA [13689]: [kW] Power limitation DEIE - power at 4mA *) (* Oldname: newPv, Cycle:*)
		rP_DEIE_ScalMax : REAL; (*PARA [13690]: [kW] Power limitation DEIE - power at 20mA *) (* Oldname: newPv, Cycle:*)
		rPr_TCO_ScalMin : REAL; (*PARA [14115]: oil pressure before turboscharger M.03-PI-063*)
		rPr_TCO_ScalMax : REAL; (*PARA [14116]: oil pressure before turboscharger M.03-PI-063*)
		bP_Mns_AnaIn_Set4mA : BOOL; (*PARA [13621]: V4.4 Netzbezugsregler*)
		rP_Mns_AnaIn_ScalMin : REAL; (*PARA [13619]: V4.4 Netzbezugsregler*)
		rP_Mns_AnaIn_ScalMax : REAL; (*PARA [13843]: V4.4 Netzbezugsregler*)
		bCtr_Mns_Setp_Set4mA : BOOL; (*PARA [13617]: V4.4 Netzbezugsregler*)
		rCtr_Mns_Setp_ScalMin : REAL; (*PARA [13842]: V4.4 Netzbezugsregler*)
		rCtr_Mns_Setp_ScalMax : REAL; (*PARA [13618]: V4.4 Netzbezugsregler*)
		iN_GMU_Devices : INT; (*PARA [11352]: Number of installed gas metering devices*) (*OldName: ucNrOfTJ; Cycle: 5*)
		rT_OXIcat_In_ScalMin : REAL; (*PARA [14118]: OXIcat Inlet temperature scale at 4mA*) (*OldName: newPV; Cycle: 5*)
		rT_OXIcat_In_ScalMax : REAL; (*PARA [14119]: OXIcat Inlet temperature scale at 20mA*) (*OldName: newPV; Cycle: 5*)
		rT_OXIcat_Out_ScalMin : REAL; (*PARA [14122]: OXIcat Outlet temperature scale at 4mA*) (*OldName: newPV; Cycle: 5*)
		rT_OXIcat_Out_ScalMax : REAL; (*PARA [14123]: OXIcat Outlet temperature scale at 20mA*) (*OldName: newPV; Cycle: 5*)
		rPr_OXIcat_In_ScalMin : REAL; (*PARA [14126]: OXIcat Inlet pressure scale at 4mA*) (*OldName: newPV; Cycle: 5*)
		rPr_OXIcat_In_ScalMax : REAL; (*PARA [14127]: OXIcat Inlet pressure scale at 20mA*) (*OldName: newPV; Cycle: 5*)
		rPr_OXIcat_Out_ScalMin : REAL; (*PARA [14129]: OXIcat Outlet pressure scale at 4mA*) (*OldName: newPV; Cycle: 5*)
		rPr_OXIcat_Out_ScalMax : REAL; (*PARA [14130]: OXIcat Outlet pressure scale at 20mA*) (*OldName: newPV; Cycle: 5*)
		rPr_OXIcat_In_Fast_ScalMin : REAL; (*PARA [14133]: OXIcat Exhaust gas inlet pressure fast scale at 4mA*) (*OldName: newPV; Cycle: 5*)
		rPr_OXIcat_In_Fast_ScalMax : REAL; (*PARA [14134]: OXIcat Exhaust gas inlet pressure fast scale at 20mA*) (*OldName: newPV; Cycle: 5*)
		rV_Over2 : ARRAY[0..2]OF REAL; (*PARA [14143]/-: over voltage 2 one phase[V]*) (*Oldname:newPv;Cycle:*)
		rTi_V_Over2 : ARRAY[0..2]OF REAL; (*PARA [14144]/-: over voltage 2 one phase[V]*) (*Oldname:newPv;Cycle:*)
		tiUnbLoadReset_EngStop : TIME; (*PARA [14354]: Reset time of current asymmetry at engine stop*) (*OldName: newPV; Cycle: 5*)
		rPos_ChC2_Valve_ScalMin : REAL; (*PARA [14269]: position temperature-regulation-valve charge cooler circuit 2 (T1-HP) at 4mA*) (* Oldname: newPv, Cycle:*)
		rPos_ChC2_Valve_ScalMax : REAL; (*PARA [14270]: position temperature-regulation-valve charge cooler circuit 2 (T1-HP) at 20mA*) (* Oldname: newPv, Cycle:*)
		tiFilt_LSL_In : TIME; (*PARA [14383]: Filter time constant for load sharing line input signal*) (* Oldname: newPv, Cycle:*)
		rT_GT_NG_ScalMin : REAL; (*PARA: Measuring range of gas temperature at 4 mA*)
		rT_GT_NG_ScalMax : REAL; (*PARA: Measuring range of gas temperature at 20 mA*)
		rPr_GT_NG_ScalMin : REAL; (*PARA: Measuring range of gas pressure at 4 mA*)
		rPr_GT_NG_ScalMax : REAL; (*PARA: Measuring range of gas pressure at 20 mA*)
		rVol_GT_NG_ScalMin : REAL; (*PARA: Measuring range of gas volume at 4 mA*)
		rVol_GT_NG_ScalMax : REAL; (*PARA: Measuring range of gas volume at 20 mA*)
		iP_ThermOverChar : ARRAY[0..2]OF INT; (*PARA [14443]/[14444]: Thermic overload protection characteristic(0= IEC invers(default), 1= IEC Stark invers, 2= IEC Extrem invers)*)
		rPr_AirST_Engage_ScalMax : REAL; (*PARA [14446]: Air starter engagement pressure at 20 mA*)
		rPr_ECWaP1_ScalMax : REAL; (*PARA [14426]: Cooling water pressure after ECW pump 1 at 20mA*)
		rPr_ECWaP2_ScalMax : REAL; (*PARA [14427]: Cooling water pressure after ECW pump 2 at 20mA*)
		bOverUnderVoltMode : ARRAY[0..2]OF BOOL; (*PARA [14506]/[14507]: Generator over-/under-voltage monitoring mode (0= Phase-Neutral, 1= Phase-Phase(default) )*)
		bSA_Active : BOOL; (*PARA [12114]: TRUE = SAFI is enabled/active *) (* OldName:bSAFI_Act; Cycle: *)
		bSA_PI_Active : BOOL; (*PARA [12120]: TRUE = SAFI port injection is enabled/active *) (* OldName:bSAFIPI_Act; Cycle: *)
		rGT_H2ScalMin : REAL; (*PARA [14903]: Measuring range of H2 at 4 mA *)
		rGT_H2ScalMax : REAL; (*PARA [14904]: Measuring range of H2 at 20 mA *)
		rLev_SCR_UreaTankScalMax : REAL; (*PARA [14954]: SCR Urea tank level at 20mA [%] (P.29-LI-001)*) (*OldName: newPV; Cycle: 5*) (*V04.13.00.00*)
		rLev_SCR_UreaTankScalMin : REAL; (*PARA [14953]: SCR Urea tank level at 4mA [%] (P.29-LI-001)*) (*OldName: newPV; Cycle: 5*) (*V04.13.00.00*)
		rCtr_ChC_Set_ScalMin : REAL; (*PARA [14971]: AnalogOUT Charge temperature channel raw signal scaling min *)
		rCtr_ChC_Set_ScalMax : REAL; (*PARA [14972]: AnalogOUT Charge temperature channel raw signal scaling max *)
		rCtr_HWRe_Set_ScalMin : REAL; (*PARA [14973]: AnalogOUT Return water temperature channel raw signal scaling min *)
		rCtr_HWRe_Set_ScalMax : REAL; (*PARA [14974]: AnalogOUT Return water temperature channel raw signal scaling max *)
		rCtr_EC_Set_ScalMin : REAL; (*PARA [14975]: AnalogOUT Return water temperature after cooler channel raw signal scaling min *)
		rCtr_EC_Set_ScalMax : REAL; (*PARA [14976]: AnalogOUT Return water temperature after cooler channel raw signal scaling max *)
		rER_FC_Set_ScalMin : REAL; (*PARA [14977]: AnalogOUT Room temperature channel raw signal scaling min *)
		rER_FC_Set_ScalMax : REAL; (*PARA [14978]: AnalogOUT Room temperature channel raw signal scaling max *)
		rCtr_HWSu_Set_ScalMin : REAL; (*PARA [14979]: AnalogOUT Supply water temperature channel raw signal scaling min *)
		rCtr_HWSu_Set_ScalMax : REAL; (*PARA [14980]: AnalogOUT Supply water temperature channel raw signal scaling max *)
		rCtr_ChCV_Set_ScalMin : REAL; (*PARA [14981]: AnalogOUT Charge temperature ventilation - fan channel raw signal scaling min *)
		rCtr_ChCV_Set_ScalMax : REAL; (*PARA [14982]: AnalogOUT Charge temperature ventilation - fan channel raw signal scaling max *)
		rCtr_ECW_Set_ScalMin : REAL; (*PARA [14983]: AnalogOUT Engine cooling water temperature channel raw signal scaling min *)
		rCtr_ECW_Set_ScalMax : REAL; (*PARA [14984]: AnalogOUT Engine cooling water temperature channel raw signal scaling max *)
		rCtr_ChCHP_Set_ScalMin : REAL; (*PARA [14985]: AnalogOUT Charge cooler temperature - high pressure channel raw signal scaling min *)
		rCtr_ChCHP_Set_ScalMax : REAL; (*PARA [14986]: AnalogOUT Charge cooler temperature - high pressure channel raw signal scaling max *)
		rCtr_GC_Set_ScalMin : REAL; (*PARA [14987]: AnalogOUT Gas compressor channel raw signal scaling min *)
		rCtr_GC_Set_ScalMax : REAL; (*PARA [14988]: AnalogOUT Gas compressor channel raw signal scaling max *)
		rEOVal_LT_Set_ScalMin : REAL; (*PARA [14989]: AnalogOUT Oil temperature controller low temperature channel raw signal scaling min *)
		rEOVal_LT_Set_ScalMax : REAL; (*PARA [14990]: AnalogOUT Oil temperature controller low temperature channel raw signal scaling max *)
		rCtr_InlLou_Set_ScalMin : REAL; (*PARA [14991]: AnalogOUT Inlet louvre - Room temperature channel raw signal scaling min *)
		rCtr_InlLou_Set_ScalMax : REAL; (*PARA [14992]: AnalogOUT Inlet louvre - Room temperature channel raw signal scaling max *)
		rCtr_OutlLou_RT_Set_ScalMin : REAL; (*PARA [14993]: AnalogOUT Outlet louvre - Room temperature channel raw signal scaling min *)
		rCtr_OutlLou_RT_Set_ScalMax : REAL; (*PARA [14994]: AnalogOUT Outlet louvre - Room temperature channel raw signal scaling max *)
		rCtr_OutlLou_RDP_Set_ScalMin : REAL; (*PARA [14995]: AnalogOUT Outlet louvre - Room difference pressure channel raw signal scaling min *)
		rCtr_OutlLou_RDP_Set_ScalMax : REAL; (*PARA [14996]: AnalogOUT Outlet louvre - Room difference pressure channel raw signal scaling max *)
		rCtr_CircLou_Set_ScalMin : REAL; (*PARA [14997]: AnalogOUT Circulation louvre - Intake air temperature channel raw signal scaling min *)
		rCtr_CircLou_Set_ScalMax : REAL; (*PARA [14998]: AnalogOUT Circulation louvre - Intake air temperature channel raw signal scaling max *)
		rCtr_CDSu_Set_ScalMin : REAL; (*PARA [14999]: AnalogOUT Supply water temperature condenser channel raw signal scaling min *)
		rCtr_CDSu_Set_ScalMax : REAL; (*PARA [15000]: AnalogOUT Supply water temperature condenser channel raw signal scaling max *)
		rCtr_OutlVE_RT_Set_ScalMin : REAL; (*PARA [15001]: AnalogOUT Outlet air fan - Room temperature channel raw signal scaling min *)
		rCtr_OutlVE_RT_Set_ScalMax : REAL; (*PARA [15002]: AnalogOUT Outlet air fan - Room temperature channel raw signal scaling max *)
		rCtr_OutlVE_RDP_Set_ScalMin : REAL; (*PARA [15003]: AnalogOUT Outlet air fan - Room difference pressure channel raw signal scaling min *)
		rCtr_OutlVE_RDP_Set_ScalMax : REAL; (*PARA [15004]: AnalogOUT Outlet air fan - Room difference pressure channel raw signal scaling max *)
		rCtr_ChC2_Valve_Set_ScalMin : REAL; (*PARA [15005]: AnalogOUT Charge temperature before HP TC (T1) channel raw signal scaling min *)
		rCtr_ChC2_Valve_Set_ScalMax : REAL; (*PARA [15006]: AnalogOUT Charge temperature before HP TC (T1) channel raw signal scaling max *)
		rPF_GrC_SetEUI1 : REAL; (*PARA [11668]: [mA] Current point 1 *) (* OldName: ssPF_evu_i1; Cycle: 5 *)
		rPF_GrC_SetEUI2 : REAL; (*PARA [11669]: [mA] Current point 2 *) (* OldName: ssPF_evu_i2; Cycle: 5 *)
		rPF_GrC_SetEUP1 : REAL; (*PARA [11670]: Power factor point 1 *) (* OldName: ssPF_evu_P1; Cycle: 5 *)
		rPF_GrC_SetEUP2 : REAL; (*PARA [11671]: Power factor point 2 *) (* OldName: ssPF_evu_P2; Cycle: 5 *)
		rQ_GrC_SetEUI1 : REAL; (*PARA [11683]: [mA] Current for reactive power point 1 *) (* OldName: ssQset_evu_i1; Cycle: 5 *)
		rQ_GrC_SetEUI2 : REAL; (*PARA [11685]: [mA] Current for reactive power point 2 *) (* OldName: ssQset_evu_i2; Cycle: 5 *)
		rQ_GrC_SetEUP1 : REAL; (*PARA [11687]: [kVAr] Reactive power point 1 *) (* OldName: ssQset_evu_P1; Cycle: 5 *)
		rQ_GrC_SetEUP2 : REAL; (*PARA [11689]: [kVAr] Reactive power point 2 *) (* OldName: ssQset_evu_P2; Cycle: 5 *)
		rQ_GrC_SetEUI1_Lim : REAL; (*PARA [11684]: [mA] Current point 1 *) (* OldName: ssQlim_evu_i1; Cycle: 5 *)
		rQ_GrC_SetEUI2_Lim : REAL; (*PARA [11686]: [mA] Current point 2 *) (* OldName: ssQlim_evu_i2; Cycle: 5 *)
		rQ_GrC_SetEUP1_Lim : REAL; (*PARA [11688]: [kVAr] Reactive power point 1 *) (* OldName: ssQlim_evu_P1; Cycle: 5 *)
		rQ_GrC_SetEUP2_Lim : REAL; (*PARA [11690]: [kVAr] Reactive power point 2 *) (* OldName: ssQlim_evu_P2; Cycle: 5 *)
		rU_GrC_SetEUI1 : REAL; (*PARA [11697]: [mA] Current point 1 *) (* OldName: ssUset_evu_i1; Cycle: 5 *)
		rU_GrC_SetEUI2 : REAL; (*PARA [11698]: [mA] Current point 2 *) (* OldName: ssUset_evu_i2; Cycle: 5 *)
		rU_GrC_SetEUP1 : REAL; (*PARA [11699]: Voltage point 1 *) (* OldName: ssUset_evu_P1; Cycle: 5 *)
		rU_GrC_SetEUP2 : REAL; (*PARA [11700]: Voltage point 2 *) (* OldName: ssUset_evu_P2; Cycle: 5 *)
		rP_GrC_SetEUI1 : REAL; (*PARA [11646]: [mA] Current point 1 *) (* OldName: p_soll_evu_i1; Cycle: 5 *)
		rP_GrC_SetEUI2 : REAL; (*PARA [11648]: [mA] Current point 2 *) (* OldName: p_soll_evu_i2; Cycle: 5 *)
		rP_GrC_SetEUP1 : REAL; (*PARA [11650]: [kW] Power point 1 *) (* OldName: p_soll_evu_p1; Cycle: 5 *)
		rP_GrC_SetEUP2 : REAL; (*PARA [11652]: [kW] Power point 2 *) (* OldName: p_soll_evu_p2; Cycle: 5 *)
		rP_GrC_SetEUI1_Lim : REAL; (*PARA [11647]: [mA] Current point 1 *) (* OldName: p_red_evu_i1; Cycle: 5 *)
		rP_GrC_SetEUI2_Lim : REAL; (*PARA [11649]: [mA] Current point 2 *) (* OldName: p_red_evu_i2; Cycle: 5 *)
		rP_GrC_SetEUP1_Lim : REAL; (*PARA [11651]: [kW] Power point 1 *) (* OldName: p_red_evu_p1; Cycle: 5 *)
		rP_GrC_SetEUP2_Lim : REAL; (*PARA [11653]: [kW] Power point 2 *) (* OldName: p_red_evu_p2; Cycle: 5 *)
		rU_SetExtAI_SetI1 : REAL; (*PARA [14707]: voltage external setpoint AI, current point 1*)
		rU_SetExtAI_SetI2 : REAL; (*PARA [14708]: voltage external setpoint AI, current point 2*)
		rU_SetExtAI_SetP1 : REAL; (*PARA [14709]: voltage external setpoint AI, voltage point 1*)
		rU_SetExtAI_SetP2 : REAL; (*PARA [14710]: voltage external setpoint AI, voltage point 2*)
		rQ_Droop_Set_SetI1 : REAL; (*PARA [14715]: reactive power external setpoint AI, current point 1*)
		rQ_Droop_Set_SetI2 : REAL; (*PARA [14716]: reactive power external setpoint AI, current point 2*)
		rQ_Droop_Set_SetP1 : REAL; (*PARA [14717]: reactive power external setpoint AI, reactive power point 1, -x[underexcited]/+x[overexcited]*)
		rQ_Droop_Set_SetP2 : REAL; (*PARA [14718]: reactive power external setpoint AI, reactive power point 2, -x[underexcited]/+x[overexcited]*)
		tPlantComm : tPlantComm_Para; (*Parameters for the OpcUA Plant Communication*)
		bSA_Ign_Active : BOOL; (*PARA [12117]: TRUE = SAFI ignition function is enabled/active *) (* OldName:bSAFIIgn_Act; Cycle: *)
		rPr_ThR2_InletOutlet_ScalMin : REAL; (*PARA [15041]: Thermal reactor inlet/outlet pressure scaling at 4mA [mbar]*) (*V04.14.00.00*)
		rPr_ThR2_InletOutlet_ScalMax : REAL; (*PARA [15042]: Thermal reactor inlet/outlet pressure scaling at 20mA [mbar]*) (*V04.14.00.00*)
		rPr_H2_GT_b_Reg_ScalMin : REAL; (*PARA [tbd]: Gas pressure before pressure regulator 4mA *) 
		rPr_H2_GT_b_Reg_ScalMax : REAL; (*PARA [tbd]: Gas pressure before pressure regulator 20mA *) 
		rPr_H2_GT_a_Reg_ScalMin : REAL; (*PARA [tbd]: Gas pressure after pressure regulator 4mA *) 
		rPr_H2_GT_a_Reg_ScalMax : REAL; (*PARA [tbd]: Gas pressure after pressure regulator 20mA *) 
		rPr_N2_GT_ScalMin : REAL; (*PARA [tbd]: Gas pressure N2 4mA *) 
		rPr_N2_GT_ScalMax : REAL; (*PARA [tbd]: Gas pressure N2 20mA *) 
		bCAsym_Ena : BOOL; (*PARA [15070]: Enable unbalance current monitoring*)
	END_STRUCT;
END_TYPE