(********************************************************************
 * COPYRIGHT -- INNIO Company
 ********************************************************************
 * Package: Knocking
 * File: module_Knocking.typ
 * Author: WaldharM
 * Created: October 03, 2011
 ********************************************************************
 * Data types of package Knocking
 ********************************************************************)

TYPE
	IN_KN_Struct : 	STRUCT  (* general*)
		tMS_PBC0 : ARRAY[0..12]OF _tSAFImdatas; (* Pressure based control measuring data 0*) (* OldName: DMR_md1; Cycle:2; *)
		tMS_PBC1 : ARRAY[0..12]OF _tSAFImdatas; (* Pressure based control measuring data 1 *) (* OldName: DMR_md1; Cycle:2; *)
		tMS_PBC2 : ARRAY[0..12]OF _tSAFImdatas; (* Pressure based control measuring data 2 *) (* OldName: DMR_md2; Cycle:2; *)
		tMS_PBC3 : ARRAY[0..12]OF _tSAFImdatas; (* Pressure based control measuring data 3 *) (* OldName: DMR_md3; Cycle:2; *)
		tMS_PBC4 : ARRAY[0..12]OF _tSAFImdatas; (* Pressure based control measuring data 4 *) (* OldName: DMR_md4; Cycle:2; *)
		tMS_PBC5 : ARRAY[0..12]OF _tSAFImdatas; (* Pressure based control measuring data 5 *) (* OldName: DMR_md5; Cycle:2; *)
		tMS_PBC6 : ARRAY[0..12]OF _tSAFImdatas; (* Pressure based control measuring data 6 *) (* OldName: DMR_md6; Cycle:2; *)
		tMS_PBC7 : ARRAY[0..12]OF _tSAFImdatas; (* Pressure based control measuring data 7 *) (* OldName: DMR_md7; Cycle:2; *)
		tMS_PBC8 : ARRAY[0..12]OF _tSAFImdatas; (* Pressure based control measuring data 8 *) (* OldName: DMR_md8; Cycle:2; *)
		tMS_PBC9 : ARRAY[0..12]OF _tSAFImdatas; (* Pressure based control measuring data 9 *) (* OldName: DMR_md9; Cycle:2; *)
		tMS_PBC10 : ARRAY[0..12]OF _tSAFImdatas; (* Pressure based control measuring data 10 *) (* OldName: DMR_md10; Cycle:2; *)
		tMS_PBC11 : ARRAY[0..12]OF _tSAFImdatas; (* Pressure based control measuring data 11 *) (* OldName: DMR_md11; Cycle:2; *)
		tMS_PBC12 : ARRAY[0..12]OF _tSAFImdatas; (* Pressure based control measuring data 12 *) (* OldName: DMR_md12; Cycle:2; *)
		tMS_PBC13 : ARRAY[0..12]OF _tSAFImdatas; (* Pressure based control measuring data 13 *) (* OldName: DMR_md13; Cycle:2; *)
		tMS_PBC14 : ARRAY[0..12]OF _tSAFImdatas; (* Pressure based control measuring data 14 *) (* OldName: DMR_md14; Cycle:2; *)
		tMS_PBC15 : ARRAY[0..12]OF _tSAFImdatas; (* Pressure based control measuring data 15 *) (* OldName: DMR_md15; Cycle:2; *)
		tMS_PBC16 : ARRAY[0..12]OF _tSAFImdatas; (* Pressure based control measuring data 16 *) (* OldName: DMR_md16; Cycle:2; *)
		tMS_PBC17 : ARRAY[0..12]OF _tSAFImdatas; (* Pressure based control measuring data 17 *) (* OldName: DMR_md17; Cycle:2; *)
		tMS_PBC18 : ARRAY[0..12]OF _tSAFImdatas; (* Pressure based control measuring data 18 *) (* OldName: DMR_md18; Cycle:2; *)
		tMS_PBC19 : ARRAY[0..12]OF _tSAFImdatas; (* Pressure based control measuring data 19 *) (* OldName: DMR_md19; Cycle:2; *)
		rP_Act_Norm_Filt : REAL; (* actual power related to rP_Nom filtered T=1s  [%/P_Nom] *) (* OldName: P_IST; Cycle:2; *)
		tAB2KN : AmmBase2MM; (* 0 *) (* OldName: 0; Cycle:2; *)
		rN_EngAct : REAL; (* engine speed *) (* OldName: n_ist; Cycle:2; *)
		iSt_OpMode : UDINT; (* engine operation mode *) (* OldName: 0; Cycle:2; *)
		tP_Act : ARRAY[0..2]OF HALioAi_Type; (* actual electric power [KW] *) (*OldName:ssPAct;Cycle:2;*)
		rP_Nom : REAL; (* nominal power *) (* OldName: 0; Cycle:2; *)
		rKLS98_X_Window1 : ARRAY[0..24]OF REAL; (* cylinder values of KLS98 window 1 *) (* OldName: Fenst1; Cycle:2; *)
		rKLS98_X_Window2 : ARRAY[0..24]OF REAL; (* cylinder values of KLS98 window 2 *) (* OldName: Fenst2; Cycle:2; *)
		rKLS98_X_Window3 : ARRAY[0..24]OF REAL; (* cylinder values of KLS98 window 3 *) (* OldName: Fenst3; Cycle:2; *)
		rKLS98_X_Window4 : ARRAY[0..24]OF REAL; (* cylinder values of KLS98 window 4 *) (* OldName: Fenst4; Cycle:2; *)
		tGCB_On_TC2 : HALioDi_Type; (* DI: Generator circuit breaker closed, TC2 synchron *) (* OldName: GCB_ON_TC1 ; Cycle:2; *)
		iU_SAFI_Win1 : ARRAY[0..24]OF INT; (* cylinder values of KLS window 1 *) (* OldName: Fenst1; Cycle:2; *)
		iU_SAFI_Win2 : ARRAY[0..24]OF INT; (* cylinder values of KLS window 2 *) (* OldName: Fenst2; Cycle:2; *)
		iU_SAFI_Win3 : ARRAY[0..24]OF INT; (* cylinder values of KLS window 3 *) (* OldName: Fenst3; Cycle:2; *)
		iU_SAFI_Win4 : ARRAY[0..24]OF INT; (* cylinder values of KLS window 4 *) (* OldName: Fenst4; Cycle:2; *)
		tPB2MM : ParaBase2MM_type; (* Messages from parametercheck module parameter are OK *) (* OldName: new PV; Cycle:2; *)
		tKLS90_1 : HALioAi_Type; (* AI: KLS90 sensor 1 signal *) (* OldName: ssKLS_Signal1; Cycle:2; *)
		tKLS90_2 : HALioAi_Type; (* AI: KLS90 sensor 1 signal *) (* OldName: ssKLS_Signal2; Cycle:2; *)
		tEng_Run : HALioDo_Type; (* engine operating state *) (* OldName: M_BTRB; Cycle:5; *)
		iIdx_OMSS : INT; (* index of operation mode selector switch *) (* OldName: BWS_HA; Cycle:2; *)
		iPassLevel : INT; (*pass level actual*) (*OldName:ucPassLevel; Cycle:5;*)
		bGasTyp1_Act : BOOL; (* gas type 1 active *) (*OldName:AN_GAS1,AW_ZZP1;Cycle:2;*)
		bGasTyp2_Act : BOOL; (* gas type 2 active *) (*OldName:AN_GAS2,AW_ZZP2;Cycle:2;*)
		bGasTyp3_Act : BOOL; (* gas type 3 active *) (*OldName:AN_GAS3,AW_ZZP3;Cycle:2;*)
		bGasTyp4_Act : BOOL; (* gas type 4 active *) (*OldName:AN_GAS4,AW_ZZP4;Cycle:2;*)
		bGasTypMix1_2_Act : BOOL; (* gas type mix 1-2 active *) (*OldName:AN_GAS1_2,AW_ZZP1_2;Cycle:2;*)
		bSCO_Active : BOOL; (* safety cut out gas valves glow ignition prevention *) (* OldName: SICH_SCHL; Cycle:5; *)
		bIPC_MSF : ARRAY[0..24]OF BOOL; (* in-cylinder pressure sensor measuring signal failure *) (* OldName: bDMRFault; Cycle: 2 *)
		bTimingRedActMx : ARRAY[0..24]OF BOOL; (* *) (* OldName: bTimingRedActMx; Cycle: 2 *)
		bKLS98_Fault : ARRAY[0..24]OF BOOL; (* TRUE= faulty cyl. knocking signal *) (*OldName:bKLS98Fault; Cycle: 2*)
		bKLS98_Signal : ARRAY[0..24]OF BOOL; (* KLS Measurement Signal Knock Sensor *) (*OldName:KLSMS; Cycle: 2*)
		bPBCSlowDriftCheck : ARRAY[0..24]OF BOOL; (* error info for PBC *) (* OldName: bPBCSlowDriftCheck; Cycle:2; *)
		iNum_KnckFiltEngCyc : INT; (* Engine cycles for knock containment V2*) (* OldName: newPV; Cycle: 2;*)
		rGT_RatioMix : REAL; (*Gas mixture rate after ramp fub [%], e.g. 0.5 = 50%*) (* OldName: 	ssRatioMix	; Cyclic:2; *)
		rGT_QualMix_1_2 : REAL; (*Mixture ratio bet. gas 1 and 2 [%], e.g. value 0.75 =75%*) (* OldName: 	ssMisch1_2	; Cyclic: ; *)
		bPBCSensErr : ARRAY[0..24]OF BOOL; (* error info for PBC *) (* OldName:bZM_PBCSensErr; Cycle:2 *)
		bPBCCompLineCheck : ARRAY[0..24]OF BOOL; (* error info for PBC *) (* OldName:bPBCCompLineCheck; Cycle:2 *)
		bPBCNegVoltCheck : ARRAY[0..24]OF BOOL; (* error info for PBC *) (* OldName:bPBCNegVoltCheck; Cycle:2 *)
		bPBCNegPresCheck : ARRAY[0..24]OF BOOL; (* error info for PBC *) (* OldName:bPBCNegPresCheck; Cycle:2 *)
		bPBCPresSlopeCheck : ARRAY[0..24]OF BOOL; (* error info for PBC *) (* OldName:bPBCPresSlopeCheck; Cycle:2 *)
		tiSFIKW_OffDelay : TIME; (* Hold On Delay for SFIKW Bit, default 100ms*) (* OldName: newPV; Cycle: 2;*)
		bPFPDR_Act : BOOL; (* PFPDR active *) (* OldName: new PV; Cycle: 2; *)
		bPFPDR_Knck_Slow : BOOL; (* PFPDR slow knock time *) (* OldName: new PV; Cycle: 2; *)
		bSimWinMOD_Active : BOOL; (*WinMOD simulation active*) (* OldName: new PV; Cycle: 5;*)
		PermRKS : tRKS_Perm; (* RKS Perm structure, values stored in EC Module *) (* OldName: newPV; Cycle: 2;*)
		bLimpHomeCylRKS : ARRAY[0..24]OF BOOL; (* Cylinders in LimpHomeRKS *) (* OldName: newPV; Cycle: 2;*)
		bSA_VCD_Active : BOOL; (*Enable visualization of VCD parameters for legacy versions*)
		bSA_Win1FrozenAltern : ARRAY[0..24]OF BOOL; (*Knock noise signal frozen or alternating*)
	END_STRUCT;
	tRKS_Perm : 	STRUCT 
		bEna : BOOL; (* Enables RKS Knock Control *)
		iTable : ARRAY[0..15]OF USINT; (* Logic Table *)
		rCA_IP_Red : REAL;
		rDur_Downset : REAL; (* Duration downset in [%] *)
		iNum_EngCyc_Limp_Recover : INT; (* amount of engine cycles without limphom to switch to PBC *)		
	END_STRUCT;
	OUT_KN_Struct : 	STRUCT  (* general*)
		tKN2AB : MM2AmmBase; (* 0 *) (* OldName: 0; Cycle:   *)
		iKls98_KnckValue_Max : UINT; (* maximum knocking value *) (* OldName: Fenst1Max ; Cycle: 2 *)
		iKls98_KnckValue_Min : UINT; (* minimum knocking value *) (* OldName: Fenst1Min ; Cycle: 2 *)
		iKls98_KnckValue_Avg : UINT; (* knocking value average *) (* OldName: Fenst1Avg ; Cycle: 2 *)
		iKls98_VNValue_Max : UINT; (* maximum valve noise *) (* OldName: Fenst2Max ; Cycle: 2 *)
		iKls98_VNValue_Min : UINT; (* minimum valve noise *) (* OldName: Fenst2Min ; Cycle: 2 *)
		iKls98_VNValue_Avg : UINT; (* valve noise average *) (* OldName: Fenst2Avg ; Cycle: 2 *)
		rKnck_Intgr_Max : REAL; (* maximum integrated knock value *) (* OldName: IntKlopfMx ; Cycle: 2 *)
		rKnck_Intgr_Min : REAL; (* minimum integrated knock value *) (* OldName: IntKlopfMn ; Cycle: 2 *)
		rKnck_Intgr_Avg : REAL; (* integrated knock value average  *) (* OldName: IntKlopfAv ; Cycle: 2 *)
		iIdx_Cyl_Knck_Max : INT; (* cyl. with highest knock signal *) (* OldName: ucKlopfMxZyl ; Cycle: 2 *)
		rKnck_Intgr : ARRAY[0..24]OF REAL; (* integrated cylinder knock values *) (* OldName: IntKlopf ; Cycle: 2 *)
		rKno_IP_Red : REAL; (* timing reduction by knocking *) (* OldName: klreg_dz ; Cycle: 2 *)
		rKno_P_Red : REAL; (* power red. by knocking *) (* OldName: klreg_dp ; Cycle: 2 *)
		rKno_T2s_Red : REAL; (* mixture temp. red. by knocking *) (* OldName: klreg_dt2 ; Cycle: 2 *)
		rP_Red_Knck_Norm : REAL; (* power reduction by knocking *) (* OldName: ssPowerRedKlopf ; Cycle: 2 *)
		rCA_Knck_Red : ARRAY[0..24]OF REAL; (* cylinder timing reduction by knocking *) (* OldName: ssKlRegdZZP ; Cycle: 2 *)
		bKLS98_MSF : ARRAY[0..24]OF BOOL; (* knocking sensor measuring signal failure *) (* OldName: bKLS98Fault; Cycle: 2 *)
		tKN2PB : MM2ParaBase_type; (* Data exchange structure to ParaBase *) (* OldName: new; Cycle: 5 *)
		rVNValue : ARRAY[0..24]OF REAL; (* cylinder values for valve noise *) (* OldName: Fenst2; Cycle: 2 *)
		rKnck_Noise : ARRAY[0..24]OF REAL; (* cylinder value for knocking noise *) (* OldName: Fenst1; Cycle: 2 *)
		rKnck_KPressure : ARRAY[0..24]OF REAL; (* cylinder value for knocking pressure *) (* OldName: Klopfen; Cycle: 2 *)
		tFastAO_KN_A : HALioAo_Type; (* fast analog output signals for validation *) (* OldName: AOFast_BuR_A; Cycle: 2 *)
		tFastAO_KN_B : HALioAo_Type; (* fast analog output signals for validation *) (* OldName: AOFast_BuR_B; Cycle: 2 *)
		rPr_Knck_Lim : ARRAY[0..24]OF REAL; (* knock limit*) (* OldName: knockFilt; Cycle 2;*)
		rPr_Knck_Filt : ARRAY[0..24]OF REAL; (* filtred knock signal with containment V2*) (* OldName: knockFilt; Cycle 2;*)
		iState_RKS : ARRAY[0..24]OF USINT; (* state for every cylinder, 1 = PBC, 2 = RKS, 3= FTC *) (* OldName: 0; Cycle:2; *)
		rPr_P2s_Knck_Offs : REAL; (* Offset for charge pressure due Knock *) (* OldName: 0; Cycle:2; *)
		rPmax_Knck_Red : ARRAY[0..24]OF REAL; (* cylinder Pmax reduction by knocking *) (* OldName: 0 ; Cycle: 2 *)
		rIntSignal : REAL; (*Knockintegrator level KLS90*)
		bTExh_Mon_UseNarrowWindow : ARRAY[0..24]OF BOOL; (*narrower threshold activation for exhaust temperature monitoring*)
		bP_Red_SAErr : BOOL; (*Trigger SAFI power reduction*)
		bKnockSig : ARRAY[0..24]OF BOOL; (*SAFI KLS measurement signal error [-]*)
	END_STRUCT;
	Para_Struct : 	STRUCT 
		rKno_IP_Red_StP : REAL; (* start point for ignition point reduction for knocking   *) (* OldName: kl_dz_li ; Cycle:   *)
		rKno_IP_Red_EnP : REAL; (*  end point for ignition point reduction for knocking   *) (* OldName: kl_dz_e ; Cycle:   *)
		rKno_P_Red_StP : REAL; (*  start point power reduction for knocking   *) (* OldName: kl_dp_li ; Cycle:   *)
		rKno_P_Red_EnP : REAL; (*  end point power reduction for knocking   *) (* OldName: kl_dp_e ; Cycle:   *)
		rKno_T2s_Red_StP : REAL; (*  start point t2s reduction for knocking   *) (* OldName: kl_dt2_li ; Cycle:   *)
		rKno_T2s_Red_EnP : REAL; (*  end point t2s reduction for knocking   *) (* OldName: kl_dt2_e ; Cycle:   *)
		bKLS98_Active : BOOL; (*  TRUE = KLS98 active  *) (* OldName: kls98_vis ; Cycle:   *)
		tiKnck_Intgr_Down : TIME; (*PARA [12084]: knock integrator decreasing factor  *) (* OldName: int_down ; Cycle:   *)
		tiKnck_Intgr_Up : TIME; (*PARA [12085]: knock integrator increasing factor  *) (* OldName: int_up; Cycle:   *)
		tiKnck_Intgr_Up_CylOpt : TIME; (*PARA [12086]: knock integrator increasing factor for timing point optimisation  *) (* OldName: int_up_CylOpt ; Cycle:   *)
		iKlS_KnckValue_Limit : UINT; (*  limit for knocking detection [mV]  *) (* OldName: Fenst2LiMx ; Cycle:   *)
		rCA_Ign_OP_Max : ARRAY[0..4]OF REAL; (*  maximum allowed ingnition point  *) (* OldName: ssMinKlZZP ; Cycle:   *)
		rU_Knck_Lim : REAL; (*  limit value for knock detection  *) (* OldName: KlopfLimit ; Cycle:   *)
		rP_Eng_KC_Act_Lim : REAL; (* power output start knock control *) (* OldName: klopf_akt ; Cycle:   *)
		rP_Knck_Act_Hy : REAL; (*  hyst power start knock control   *) (* OldName: klopf_hys ; Cycle:   *)
		bIgnP_Opt_Exist : BOOL; (*  TURE =  igniton timing point optimisation is active  *) (* OldName: bCylOpt ; Cycle:   *)
		bSA_PBC_Active : BOOL; (*PARA [12119]: TRUE = SAFI PBC function is enabled/active  *) (* OldName: bSAFIDMR_Act; Cycle:   *)
		bSA_KLS_Active : BOOL; (*PARA [12118]: TRUE = SAFI KLS function is enabled/active *) (* OldName: bSAFIKLS_Act; Cycle: 0 *)
		bKLS90_Exist : BOOL; (* Para: TRUE = KLS90 is enabled/active  *) (* OldName: 0; Cycle: 0 *)
		iKlS_MSFailure_Limit : UINT; (*PARA [12074]: limit for measuring signal failue [mV]  *) (* OldName: Fenst2LiMn; Cycle: 0 *)
		rKLS90_KnckValue_LimitB : REAL; (*PARA [14505]: limit for KLS90 knocking detection - BankB [mA] *) (* OldName: kl_limit_1, kl_limit_2; Cycle: 0 *)
		rKLS90_KnckValue_Limit : REAL; (*PARA [12075]: limit for KLS90 knocking detection - BankA [mA] *) (* OldName: kl_limit_1, kl_limit_2; Cycle: 0 *)
		iEng_Motortype : INT; (* 0 *) (* OldName: 0; Cycle: 0 *)
		bGlowIgnPrevActive : BOOL; (*PARA [12089]: TRUE = glow ignition prevention activ *) (* OldName: sel_GlowIgnPrevent; Cycle: 2 *)
		rPr_PBC_Knck_Lim : REAL; (*PARA [12776]: PBC Knock Limit [bar] *) (* OldName: KlopfLimitDMR; Cycle: 2 *)
		rN_EngNom : REAL; (* nominal speed *) (* OldName: n_nenn ; Cycle: 2 *)
		bSA_PI_Active : BOOL; (*PARA [12120]: TRUE = SAFI port injection is enabled/active  *) (* OldName: bSAFIPI_Act; Cycle: 2 *)
		rKno_Int_MinLim : REAL; (*PARA [13460]: lower knock integrator limit for PI Engines *)
		rKno_IP_Scale_StP : REAL; (*PARA [13461]: start point for ignition timing point scaling for knocking   *)
		rCA_IP_Knck_Max : REAL; (*PARA [13466]: maximum ignition timing point reduction *)
		rKno_Pmax_Red_StP : REAL; (*PARA [13462]: start point for Pmax reduction for knocking   *) (* OldName: newPV ; Cycle:   *)
		rKno_Pmax_Red_EnP_dlt : REAL; (*PARA [13463]: end point for Pmax reduction for knocking   *) (* OldName: newPV ; Cycle:   *)
		rPmax_Knck_Max : REAL; (*PARA [13468]: maximum Pmax reduction *)
		rKno_P2s_Inc_StP : REAL; (*PARA [13464]: start point for charging pressure increase for knocking   *) (* OldName: newPV ; Cycle:   *)
		rKno_P2s_Inc_EnP : REAL; (*PARA [13465]: end point for charging pressure increase for knocking   *) (* OldName: newPV ; Cycle:   *)
		rPr_P2s_Knck_Max : REAL; (*PARA [13467]: maximum charging pressure increase *)
		iKno_Pmax_CylMax : USINT; (*PARA [13469]: max number of cylinders for Pmax reduction *)
		rPr_PBC_Knck_Heavy : REAL; (*PARA [13501]: PBC Heavy Knock Limit [bar] *) (* OldName: newPV; Cycle: 2 *)
		bType6BlockAfterTrip : BOOL; (*BOOL: Block Engine after Knock trip in combination with measurung signal failure knock sensor (type 6 only)*)
		bMeNoi_Activation : BOOL; (*Para [14415]: Mechanical noise monitoring active*)
		rP_Marg_MeNoiAL_Dev : REAL; (*Para [14417]: Deviation limit to apply increased temperature monitoring sensitivity*)
		rFiltTimeCnt_MeNoi : REAL; (*Para [14416]: Filter constant operation point detection*)
		bSA_Ign_Active : BOOL; (*PARA [12117]: TRUE = SAFI ignition function is enabled/active  *)
	END_STRUCT;
	MM2VIS_Struct : 	STRUCT  (*OPC variables from module to VIS*)
		bMeNoi_Mon_vis : BOOL; (*Activation MeNoi Mon Para folder in HMI*)
		bMsg3053 : BOOL; (* Trip: KLS valve noise cylinder 1 *) (* OldName: KLSVEN[1]; Cycle: 0 *)
		bMsg3054 : BOOL; (* Trip: KLS valve noise cylinder 2 *) (* OldName: KLSVEN[2]; Cycle: 0 *)
		bMsg3055 : BOOL; (* Trip: KLS valve noise cylinder 3 *) (* OldName: KLSVEN[3]; Cycle: 0 *)
		bMsg3056 : BOOL; (* Trip: KLS valve noise cylinder 4 *) (* OldName: KLSVEN[4]; Cycle: 0 *)
		bMsg3057 : BOOL; (* Trip: KLS valve noise cylinder 5 *) (* OldName: KLSVEN[5]; Cycle: 0 *)
		bMsg3058 : BOOL; (* Trip: KLS valve noise cylinder 6 *) (* OldName: KLSVEN[6]; Cycle: 0 *)
		bMsg3059 : BOOL; (* Trip: KLS valve noise cylinder 7 *) (* OldName: KLSVEN[7]; Cycle: 0 *)
		bMsg3060 : BOOL; (* Trip: KLS valve noise cylinder 8 *) (* OldName: KLSVEN[8]; Cycle: 0 *)
		bMsg3061 : BOOL; (* Trip: KLS valve noise cylinder 9 *) (* OldName: KLSVEN[9]; Cycle: 0 *)
		bMsg3062 : BOOL; (* Trip: KLS valve noise cylinder 10 *) (* OldName: KLSVEN[10]; Cycle: 0 *)
		bMsg3063 : BOOL; (* Trip: KLS valve noise cylinder 11 *) (* OldName: KLSVEN[11]; Cycle: 0 *)
		bMsg3064 : BOOL; (* Trip: KLS valve noise cylinder 12 *) (* OldName: KLSVEN[12]; Cycle: 0 *)
		bMsg3065 : BOOL; (* Trip: KLS valve noise cylinder 13 *) (* OldName: KLSVEN[13]; Cycle: 0 *)
		bMsg3066 : BOOL; (* Trip: KLS valve noise cylinder 14 *) (* OldName: KLSVEN[14]; Cycle: 0 *)
		bMsg3067 : BOOL; (* Trip: KLS valve noise cylinder 15 *) (* OldName: KLSVEN[15]; Cycle: 0 *)
		bMsg3068 : BOOL; (* Trip: KLS valve noise cylinder 16 *) (* OldName: KLSVEN[16]; Cycle: 0 *)
		bMsg3069 : BOOL; (* Trip: KLS valve noise cylinder 17 *) (* OldName: KLSVEN[17]; Cycle: 0 *)
		bMsg3070 : BOOL; (* Trip: KLS valve noise cylinder 18 *) (* OldName: KLSVEN[18]; Cycle: 0 *)
		bMsg3071 : BOOL; (* Trip: KLS valve noise cylinder 19 *) (* OldName: KLSVEN[19]; Cycle: 0 *)
		bMsg3072 : BOOL; (* Trip: KLS valve noise cylinder 20 *) (* OldName: KLSVEN[20]; Cycle: 0 *)
		bMsg3073 : BOOL; (* Trip: KLS98 knocking failure cylinder 1 *) (* OldName: KLOPF[1]; Cycle: 0 *)
		bMsg3074 : BOOL; (* Trip: KLS98 knocking failure cylinder 2 *) (* OldName: KLOPF[2]; Cycle: 0 *)
		bMsg3075 : BOOL; (* Trip: KLS98 knocking failure cylinder 3 *) (* OldName: KLOPF[3]; Cycle: 0 *)
		bMsg3076 : BOOL; (* Trip: KLS98 knocking failure cylinder 4 *) (* OldName: KLOPF[4]; Cycle: 0 *)
		bMsg3077 : BOOL; (* Trip: KLS98 knocking failure cylinder 5 *) (* OldName: KLOPF[5]; Cycle: 0 *)
		bMsg3078 : BOOL; (* Trip: KLS98 knocking failure cylinder 6 *) (* OldName: KLOPF[6]; Cycle: 0 *)
		bMsg3079 : BOOL; (* Trip: KLS98 knocking failure cylinder 7 *) (* OldName: KLOPF[7]; Cycle: 0 *)
		bMsg3080 : BOOL; (* Trip: KLS98 knocking failure cylinder 8 *) (* OldName: KLOPF[8]; Cycle: 0 *)
		bMsg3081 : BOOL; (* Trip: KLS98 knocking failure cylinder 9 *) (* OldName: KLOPF[9]; Cycle: 0 *)
		bMsg3082 : BOOL; (* Trip: KLS98 knocking failure cylinder 10 *) (* OldName: KLOPF[10]; Cycle: 0 *)
		bMsg3083 : BOOL; (* Trip: KLS98 knocking failure cylinder 11 *) (* OldName: KLOPF[11]; Cycle: 0 *)
		bMsg3084 : BOOL; (* Trip: KLS98 knocking failure cylinder 12 *) (* OldName: KLOPF[12]; Cycle: 0 *)
		bMsg3085 : BOOL; (* Trip: KLS98 knocking failure cylinder 13 *) (* OldName: KLOPF[13]; Cycle: 0 *)
		bMsg3086 : BOOL; (* Trip: KLS98 knocking failure cylinder 14 *) (* OldName: KLOPF[14]; Cycle: 0 *)
		bMsg3087 : BOOL; (* Trip: KLS98 knocking failure cylinder 15 *) (* OldName: KLOPF[15]; Cycle: 0 *)
		bMsg3088 : BOOL; (* Trip: KLS98 knocking failure cylinder 16 *) (* OldName: KLOPF[16]; Cycle: 0 *)
		bMsg3089 : BOOL; (* Trip: KLS98 knocking failure cylinder 17 *) (* OldName: KLOPF[17]; Cycle: 0 *)
		bMsg3090 : BOOL; (* Trip: KLS98 knocking failure cylinder 18 *) (* OldName: KLOPF[18]; Cycle: 0 *)
		bMsg3091 : BOOL; (* Trip: KLS98 knocking failure cylinder 19 *) (* OldName: KLOPF[19]; Cycle: 0 *)
		bMsg3092 : BOOL; (* Trip: KLS98 knocking failure cylinder 20 *) (* OldName: KLOPF[20]; Cycle: 0 *)
		bMsg3279 : BOOL; (* OP Message: Knocking failure *) (* OldName: bBKnockErr; Cycle: 0 *)
		bMsg3281 : BOOL; (* OP Message: Valve noise high *) (* OldName: bBValveErr; Cycle: 0 *)
		bMsg3282 : BOOL; (* OP Message: Knock sensor measuring signal failure *) (* OldName: bBKnockSigErr; Cycle: 0 *)
		bMsg3339 : BOOL; (* Trip: Knocking failure *) (* OldName: bAKnockErr; Cycle: 0 *)
		bMsg3341 : BOOL; (* Trip: Valve noise high *) (* OldName: bAKnockErr; Cycle: 0 *)
		bMsg3342 : BOOL; (* Trip: Knock sensor measuring sensor failure *) (* OldName: bAKnockSigErr; Cycle: 0 *)
		bMsg3541 : BOOL; (* Warning: Knock sensor measuring sensor failure *) (* OldName: bWKnockSigErr; Cycle: 0 *)
		iKls98_KnckValue_Max : UINT; (* maximum knocking value *) (* OldName: Fenst1Max ; Cycle: 0 *)
		iKls98_KnckValue_Min : UINT; (* minimum knocking value *) (* OldName: Fenst1Min ; Cycle: 0 *)
		iKls98_KnckValue_Avg : UINT; (* knocking value average *) (* OldName: Fenst1Avg ; Cycle: 0 *)
		iKls98_VNValue_Max : UINT; (* maximum valve noise *) (* OldName: Fenst2Max ; Cycle: 0 *)
		iKls98_VNValue_Min : UINT; (* minimum valve noise *) (* OldName: Fenst2Min ; Cycle: 0 *)
		iKls98_VNValue_Avg : UINT; (* valve noise average *) (* OldName: Fenst2Avg ; Cycle: 0 *)
		rKnck_Intgr_Max : REAL; (* maximum integrated knock value *) (* OldName: IntKlopfMx ; Cycle: 0 *)
		rKnck_Intgr_Min : REAL; (* minimum integrated knock value *) (* OldName: IntKlopfMn ; Cycle: 0 *)
		rKnck_Intgr_Avg : REAL; (* integrated knock value average  *) (* OldName: IntKlopfAv ; Cycle: 0 *)
		iIdx_Cyl_Knck_Max : INT; (* cyl. with highest knock signal *) (* OldName: ucKlopfMxZyl ; Cycle: 0 *)
		rKnck_Intgr : ARRAY[0..24]OF REAL; (* integrated cylinder knock values *) (* OldName: IntKlopf ; Cycle: 0 *)
		rKno_IP_Red : REAL; (* timing reduction by knock permill *) (* OldName: klreg_dz ; Cycle: 0 *)
		rKno_P_Red : REAL; (* power red. by knocking *) (* OldName: klreg_dp ; Cycle: 0 *)
		rKno_T2s_Red : REAL; (* mixture temp. red. by knocking *) (* OldName: klreg_dt2 ; Cycle: 0 *)
		rP_Red_Knck_Norm : REAL; (* power reduction by knocking *) (* OldName: ssPowerRedKlopf ; Cycle: 0 *)
		rCA_Knck_Red : ARRAY[0..24]OF REAL; (* cylinder timing reduction *) (* OldName: ssKlRegdZZP ; Cycle: 0 *)
		iMsg3279 : INT; (* ACM: Knocking failure *) (* OldName: iIdx_Err_Knock; Cycle: 0 *)
		iMsg3281 : INT; (* ACM: Vavle noise high *) (* OldName: iIdx_Err_Valve; Cycle: 0 *)
		iMsg3282 : INT; (* ACM: Knock sensor measuring signal failure *) (* OldName: iIdx_Err_KnockSig; Cycle: 0 *)
		rVNValue : ARRAY[0..24]OF REAL; (* cylinder values for valve noise *) (* OldName: Fenst2; Cycle: 0 *)
		rKnck_Noise : ARRAY[0..24]OF REAL; (* cylinder value for knocking noise *) (* OldName: Fenst1; Cycle: 0 *)
		rKnck_KPressure : ARRAY[0..24]OF REAL; (* cylinder value for knocking noise *) (* OldName: Klopfen; Cycle: 0 *)
		rKLS90_Knck_Noise_1 : REAL; (* KLS90 cylinder 1 value for knocking noise  *) (* OldName: kl_ist_1; Cycle: 0 *)
		rKLS90_Knck_Noise_2 : REAL; (* KLS90 cylinder 2 value for knocking noise  *) (* OldName: kl_ist_2; Cycle: 0 *)
		bMsg1081 : BOOL; (* Trip: Knock sensor measuring signal failure KLS90 *) (* OldName: new PV; Cycle: 0 *)
		bMsg2111 : BOOL; (* Warning: Knock sensor measuring signal failure KLS90 *) (* OldName: new PV; Cycle: 0 *)
		bMsg1048 : BOOL; (* Trip: Knocking failure KLS90 *) (* OldName: new PV; Cycle: 0 *)
		rKnck_Noise_Avg : REAL; (* average value for knocking noise *) (* OldName: Fenst1Avg; Cycle: 0 *)
		rKnck_Noise_Max : REAL; (* maximum value for knocking noise *) (* OldName: Fenst1Max; Cycle: 0 *)
		rKnck_Noise_Min : REAL; (* minimum value for knocking noise *) (* OldName: Fenst1Min; Cycle: 0 *)
		bMsg2492 : BOOL; (*W2492 - Knocking in combination with a knock sensor failure – contact the service hotline*)
		iRKS_KnckSens_Color : ARRAY[0..24]OF INT;
		bMsg2440 : BOOL; (* W2440: RKS G2 unit Bank A CAN signal failure *) (* OldName: new PV; Cycle: 0 *)
		bMsg2441 : BOOL; (* W2441: RKS G2 unit Bank B CAN signal failure *) (* OldName: new PV; Cycle: 0 *)
		bKLS90_2_Exist: BOOL; (* Enables 2nd KLS90 sensor on HMI *)
	END_STRUCT;
	_tSAFImdatas : 	STRUCT 
		data1 : UINT;
		data2 : UINT;
		data3 : UINT;
	END_STRUCT;
	_tSAFIHardware : 	STRUCT 
		HW_OPTION : USINT;
		HW_VERSION : USINT;
	END_STRUCT;
	tPIopen : 	STRUCT 
		timing : UINT;
		duration : UINT;
	END_STRUCT;
	rtctime_typ : 	STRUCT 
		year : UINT;
		month : USINT;
		day : USINT;
		reserve : USINT;
		hour : USINT;
		minute : USINT;
		second : USINT;
		millisec : UINT;
		microsec : UINT;
	END_STRUCT;
END_TYPE
