
TYPE
	PROGRAMMER_INFO : 	STRUCT 
		DO_NOT_SORT_PARA : STRING[40] := 'DO NOT CHANGE PARAMETER SORTING!'; (*DO NOT CHANGE PARAMETER SORTING!*) (*ADD NEW PARAMETER ONLY AT THE END OF THE Para STRUCTURE. DO NOT DELETE existing Para items.*)
	END_STRUCT;
	Para_Exhaust_Struct : 	STRUCT  (*! Add new tags only at the end OF the pm structure!*)
		bCodinox_Active : BOOL; (*PARA [11300]: CODINOX enable *) (*OldName:bCodinox;Cycle:5*)
		bPurgecycle_Active : BOOL; (*PARA [12256]: purge cycle enable *) (*OldName:bPurgecycle;Cycle:5*)
		bEGValveEnable : BOOL; (*PARA [11305]: exhaust gas flap enable*) (*OldName:new parameter;Cycle:5*)
		bEGValveRegulation : BOOL; (*PARA [11306]: exhaust gas flap regulation enable*) (*OldName:new parameter;Cycle:5*)
		tiCO2_ExPSp_StopOffTime : TIME; (*PARA [11350]: Codinox ext.power setpoint stop - Off time*) (*OldName:new parameter;Cycle:5*)
		tiCO2_ExPSp_StartOffTime : TIME; (*PARA [11349]: Codinox ext.power setpoint start - Off time*) (*OldName:new parameter;Cycle:5*)
		iEng_Motortype : INT; (*Para motortype*) (*OldName:motortyp;Cycle:5*)
		bEGScav_ifAuxV_ok : BOOL; (*PARA [11304]: exhaust gas scavenging if auxiliaries voltage supply ok*) (*OldName:sel_EGScav_if_AuxV_ok;Cycle:5*)
		bT_EGaLPTC_B_Active : BOOL; (*PARA [11320]: exhaust gas temperature after low pressure turbo charger active*) (*OldName:t_EGaLPTC_B_a;Cycle:5*)
		bT_EGaLPTC_A_Active : BOOL; (*PARA [11319]: exhaust gas temperature after low pressure turbo charger active*) (*OldName:t_EGaLPTC_A_a;Cycle:5*)
		rT_EGaTC_LimHi : REAL; (*PARA [11337]: exhaust gas temperature after turbo charger limit high*) (*OldName:GW_VABK;Cycle:5*)
		bN2_NoScavGas1 : BOOL; (*PARA [11307]: no N2 scavenging for gas type/gas train 1*) (*OldName:new parameter;Cycle:5*)
		bN2_NoScavGas2 : BOOL; (*PARA [11308]: no N2 scavenging for gas type/gas train 2*) (*OldName:new parameter;Cycle:5*)
		rPr_Prel1EOP_LimHi : REAL; (*PARA [10076]: pressure prelubrication 1 engine oil  pump limit high*) (*OldName:GW_VSD1;Cycle:5*)
		rPr_Prel1EOP_HyHi : REAL; (*PARA [10075]: pressure prelubrication 1 engine oil  pump hysteresis high*) (*OldName:HY_VSD1;Cycle:5*)
		rN_EngNom : REAL; (*PARA [12128]: engine nominal speed*) (*OldName:n_nenn;Cycle:5*)
		rN_EngStart_LimHi : REAL; (*PARA [11296]: speed engine start limit high*) (*OldName:GW_DREHZ;Cycle:5*)
		rN_EngStart_HyHi : REAL; (*PARA [11295]: speed engine start limit high hysteresis*) (*OldName:HY_DREHZ;Cycle:5*)
		rN_EngStartMon_LimHi : REAL; (*PARA [12068]: speed engine start monitoring limit high*) (*OldName:GW_STRDRE;Cycle:5*)
		rN_EngStartMon_HyHi : REAL; (*PARA [12067]: speed engine start monitoring limit high hysteresis*) (*OldName:HY_STRDRE;Cycle:5*)
		bSel_EGVa_Torque : BOOL; (*PARA [11311]: exhaust gas flap with torque closing*) (*OldName:new parameter;Cycle:5*)
		bSel_EGVa_Combi : BOOL; (*PARA [11309]: exhaust gas flap with combined bypass/boiler valve actuator*) (*OldName:KOMBI_KL;Cycle:5*)
		bSel_EGVa_ROTORK : BOOL; (*PARA [11310]: exhaust gas flap = ROTORK*) (*OldName:ROTORK;Cycle:5*)
		bSel_N2 : BOOL; (*PARA [11312]: select exhaust gas scavenging with nitrogen(N2)*) (*OldName:sel_N2;Cycle:5*)
		bSel_TwoN2Valves : BOOL; (*PARA [11313]: select exhaust gas scavenging with 2 nitrogen(N2) gas valves*) (*OldName:sel_TwoN2Valves;Cycle:5*)
		bEGScav_Active : BOOL; (*PARA [11303]: exhaust gas scavenging active *) (*OldName:sel_EGScav;Cycle:5*)
		tiEGScavMin : TIME; (*PARA [11351]: time exhaust gas scavenging duration minimum*) (*OldName:ssTW_T_SPUEL;Cycle:5*)
		bT_EGaHE1_Active : BOOL; (*PARA [11317]: exhaust gas temperature after heat exchanger 1 active *) (*OldName:NWTT1_a;Cycle:5*)
		bT_EGaHE2_Active : BOOL; (*PARA [11318]: exhaust gas temperature after heat exchanger 2 active *) (*OldName:NWTT2_a;Cycle:5*)
		bCO2_PneumVal : BOOL; (*PARA [11299]: Codinox with pneumatic valve*) (*OldName:CO2_VENTIL;Cycle:5*)
		bT_EGaTC_Active : BOOL; (*PARA [11321]: exhaust gas temperature after turbo charger active *) (*OldName:v_abhk_a;Cycle:5*)
		bT_EGaHE_Active : BOOL; (*PARA [11316]: exhaust gas temperature after heat exchanger active *) (*OldName:n_abhk_a;Cycle:5*)
		rT_EGaHE_LimHi : REAL; (*PARA [11335]: exhaust gas temperature after heat exchanger limit high *) (*OldName:GW_NABK;Cycle:5*)
		rT_EGaHE_HyHi : REAL; (*PARA [11334]: exhaust gas temperature after heat exchanger limit high hysteresis*) (*OldName:HY_NABK;Cycle:5*)
		bT_PlateHE_Active : BOOL; (*PARA [11324]: plate temperature heat exchanger active *) (*OldName:rohr_a;Cycle:5*)
		rT_PlateHE_LimHi : REAL; (*PARA [11347]: plate temperature heat exchanger limit high *) (*OldName:GW_ROHR;Cycle:5*)
		rT_PlateHE_LimHiHi : REAL; (*PARA [11348]: plate temperature heat exchanger limit high high*) (*OldName:GW_ROHRA;Cycle:5*)
		rT_PlateHE_HyHi : REAL; (*PARA [11344]: plate temperature heat exchanger limit high hysteresis*) (*OldName:HY_ROHR;Cycle:5*)
		rT_PlateHE_InpLimMin : REAL; (*PARA [11346]: plate temperature heat exchanger input limit minimum*) (*OldName:t_rohr_gw_min;Cycle:5*)
		rT_PlateHE_InpLimMax : REAL; (*PARA [11345]: plate temperature heat exchanger input limit maximum*) (*OldName:t_rohr_gw_max;Cycle:5*)
		bT_EGbTC_Active : BOOL; (*PARA [11323]: exhaust gas temperature before turbo charger active *) (*OldName:T3_a;Cycle:5*)
		rT_EGbTC_LimHi : REAL; (*PARA [11342]: exhaust gas temperature before turbo charger limit high *) (*OldName:GW_T3W;Cycle:5*)
		rT_EGbTC_LimHiHi : REAL; (*PARA [11343]: exhaust gas temperature before turbo charger limit high high*) (*OldName:GW_T3;Cycle:5*)
		rT_EGbTC_HyHi : REAL; (*PARA [11340]: exhaust gas temperature before turbo charger limit high hysteresis*) (*OldName:HY_T3W;Cycle:5*)
		rT_EGbTC_HyHiHi : REAL; (*PARA [11341]: exhaust gas temperature before turbo charger limit high high hysteresis*) (*OldName:HY_T3;Cycle:5*)
		bEngTyp3_Prelub_Active : BOOL; (*PARA [10009]: prelubrication for engine typ 3 active *) (*OldName:BR3_VS_aktiv; Cycle:5*)
		bEG_BoVa_Visible : BOOL; (*PARA [11301]: exhaust gas boiler valve visible*) (*OldName:bExhGasValveHeatEx; Cycle:5*)
		bEG_ByVa_Visible : BOOL; (*PARA [11302]: exhaust gas bypass valve visible*) (*OldName:bExhGasValveBypass; Cycle:5*)
		bScavBeStart_Active : BOOL; (*PARA [12777]: exhaust gas scavenging before engine start active*) (*OldName:new pv;Cycle:5*)
		bT_EGbHPTC_A_Active : BOOL; (*PARA [12663]: exhaust gas temperature before high-pressure turbocharger A active(M.02-TI-166)*) (*OldName:new pv;Cycle:5*)
		bT_EGbHPTC_B_Active : BOOL; (*PARA [12664]: exhaust gas temperature before high-pressure turbocharger B active(M.02-TI-266)*) (*OldName:new pv;Cycle:5*)
		bT_EGaHPTC_A_Active : BOOL; (*PARA [12665]: exhaust gas temperatur after high-pressure turbocharger A active(M.02-TI-167)*) (*OldName:new pv;Cycle:5*)
		bT_EGaHPTC_B_Active : BOOL; (*PARA [12666]: exhaust gas temperatur after high-pressure turbocharger B active(M.02-TI-267)*) (*OldName:new pv;Cycle:5*)
		bPr_EGbHPTC_A_Active : BOOL; (*PARA [12667]: exhaust gas pressure before high-pressure turbocharger A active(M.02-PI-152)*) (*OldName:new pv;Cycle:5*)
		bPr_EGbHPTC_B_Active : BOOL; (*PARA [12668]: exhaust gas pressure before high-pressure turbocharger B active(M.02-PI-252)*) (*OldName:new pv;Cycle:5*)
		bPr_EGaHPTC_A_Active : BOOL; (*PARA [12669]: exhaust gas pressure after high-pressure turbocharger A active(M.02-PI-153)*) (*OldName:new pv;Cycle:5*)
		bPr_EGaHPTC_B_Active : BOOL; (*PARA [12670]: exhaust gas pressure after high-pressure turbocharger B active(M.02-PI-253)*) (*OldName:new pv;Cycle:5*)
		bPr_EGaLPTC_A_Active : BOOL; (*PARA [12671]: exhaust gas pressure after low-pressure turbocharger A active(M.02-PI-154)*) (*OldName:new pv;Cycle:5*)
		bPr_EGaLPTC_B_Active : BOOL; (*PARA [12672]: exhaust gas pressure after low-pressure turbocharger B active(M.02-PI-254)*) (*OldName:new pv;Cycle:5*)
		rT_EGaHE1_LimHi_Trip : REAL; (*PARA [13039]: exhaust gas temperature after exhaust heat exchanger 1 limit high trip*) (*OldName:new pv;Cycle:5*) (*STM*)
		rT_EGaHE1_HyHi_Trip : REAL; (*PARA [13040]: exhaust gas temperature after exhaust heat exchanger 1 limit high trip hysteresis*) (*OldName:new pv;Cycle:5*) (*STM*)
		rT_EGaHE2_LimHi_Trip : REAL; (*PARA [13041]: exhaust gas temperature after exhaust heat exchanger 2 limit high trip *) (*OldName:new pv;Cycle:5*) (*STM*)
		rT_EGaHE2_HyHi_Trip : REAL; (*PARA [13042]: exhaust gas temperature after exhaust heat exchanger 2 limit high trip hysteresis*) (*OldName:new pv;Cycle:5*) (*STM*)
		rT_EGaHE1_LimHi_Warn : REAL; (*PARA [13043]: exhaust gas temperature after exhaust heat exchanger 1 limit high warning*) (*OldName:new pv;Cycle:5*) (*STM*)
		rT_EGaHE1_HyHi_Warn : REAL; (*PARA [13044]: exhaust gas temperature after exhaust heat exchanger 1 limit high warning hysteresis*) (*OldName:new pv;Cycle:5*) (*STM*)
		rT_EGaHE2_LimHi_Warn : REAL; (*PARA [13045]: exhaust gas temperature after exhaust heat exchanger 2 limit high warning*) (*OldName:new pv;Cycle:5*) (*STM*)
		rT_EGaHE2_HyHi_Warn : REAL; (*PARA [13046]: exhaust gas temperature after exhaust heat exchanger 2 limit high warning hysteresis*) (*OldName:new pv;Cycle:5*) (*STM*)
		bPr_Diff_ExGCooler_Active : BOOL; (*PARA [13310]: activation differential pressure exhaust gas cooler*) (*OldName:bCodinox;Cycle:5*)
		bPr_Diff_ExGFilter_Active : BOOL; (*PARA [13313]: activation differential pressure exhaust gas filter*) (*OldName:bCodinox;Cycle:5*)
		rT_EGaHE1_Hi : REAL; (*Para temperature after exhaust gas heat exchanger 1  high*) (*OldName:bCodinox;Cycle:5*)
		rT_EGaHE2_Hi : REAL; (*Para temperature after exhaust gas heat exchanger 2  high*) (*OldName:bCodinox;Cycle:5*)
		rPr_Diff_ExGCooler_Hi : REAL; (*PARA [13311]: Limit maximum differential pressure exhaust gas cooler*) (*OldName:bCodinox;Cycle:5*)
		rPr_Diff_ExGCooler_HyHi : REAL; (*PARA [13312]: Hysterese differential pressure exhaust gas cooler*) (*OldName:bCodinox;Cycle:5*)
		rPr_Diff_ExGFilter_Hi1 : REAL; (*PARA [13314]: Limit maximum differential pressure exhaust gas filter*) (*OldName:bCodinox;Cycle:5*)
		rPr_Diff_ExGFilter_Hi2 : REAL; (*PARA [13315]: Limit maximum 2 differential pressure exhaust gas filter*) (*OldName:bCodinox;Cycle:5*)
		rPr_Diff_ExGFilter_Hi : REAL; (*PARA [13316]: Limit maximum differential pressure exhaust gas filter shut down*) (*OldName:bCodinox;Cycle:5*)
		rPr_Diff_ExGFilter_Lo : REAL; (*PARA [13317]: Limit minimum differential pressure exhaust gas filter*) (*OldName:bCodinox;Cycle:5*)
		rPr_Diff_ExGFilter_HyHi : REAL; (*PARA [13318]: Hysterese differential pressure exhaust gas filter*) (*OldName:bCodinox;Cycle:5*)
		bBOP_ExhGasSys_Act : BOOL; (*PARA [13837]: -Visu: Plant display exhaust gas system active*) (*OldName:newPv; Cycle:5;*)
		bT_bScavValve_Active : BOOL; (*PARA [13969]: air temperature before exhaust gas scavening valve active *)
		rT_bScavValve_LimHi : REAL; (*PARA [13970]: air temperature before exhaust gas scavening valve limit high *)
		rPr_PC_Diff_LimHi : REAL; (*PARA [13971]: pre chamber differential pressure high during engine stop limit high*)
		bOXIcat_Exist : BOOL; (*PARA [14113]: OXIcat active*) (*OldName: newPV; Cycle: 5*)
		bT_OXIcat_In_Exist : BOOL; (*PARA [14117]: OXIcat Inlet temperature active*) (*OldName: newPV; Cycle: 5*)
		rT_OXIcat_In_Hi : REAL; (*PARA [14120]: OXIcat Inlet temperature maximum - Warning*) (*OldName: newPV; Cycle: 5*)
		bT_OXIcat_Out_Exist : BOOL; (*PARA [14121]: OXIcat Outlet temperature active*) (*OldName: newPV; Cycle: 5*)
		rT_OXIcat_Out_HiHi : REAL; (*PARA [14124]: OXIcat Outlet temperature maximum - Shutdown*) (*OldName: newPV; Cycle: 5*)
		bPr_OXIcat_In_Exist : BOOL; (*PARA [14125]: OXIcat Inlet pressure active*) (*OldName: newPV; Cycle: 5*)
		bPr_OXIcat_Out_Exist : BOOL; (*PARA [14128]: OXIcat Outlet pressure active*) (*OldName: newPV; Cycle: 5*)
		rPR_OXIcat_Diff_Hi : REAL; (*PARA [14131]: OXIcat Differential pressure minimum - Warning*) (*OldName: newPV; Cycle: 5*)
		bPr_OXIcat_In_Fast_Exist : BOOL; (*PARA [14132]: OXIcat Exhaust gas inlet pressure fast active*) (*OldName: newPV; Cycle: 5*)
		bT_EGaLPTC_HiTrip : BOOL; (*PARA [14153]: exhaust gas temperature after low pressure turbo charger active*) (*OldName:newPV;Cycle:5*)
		rT_EGaTC_LimHiHi : REAL; (*PARA [14151]: exhaust gas temperature after turbo charger limit high high*) (*OldName:newPV;Cycle:5*)
		tiEGaTC_LimHiHi : TIME; (*PARA [14152]: exhaust gas temperature after turbo charger limit high high - delay time*) (*OldName:newPV;Cycle:5*)
		rT_bScavValve_LimHi1 : REAL; (*PARA [14183]: air temperature before exhaust gas scavening valve limit high - warning//SWAT920/5*)
		rPr_EG_Deflag_Fast_HiHi : REAL; (*PARA [14301]: Exhaust gas pressure fast maximum - Shutdown*) (*OldName: newPV; Cycle: 5*)
		bT_EG_PrReliefVa1_Active : BOOL; (*temperature exhaust gas pressure relief valve 1 active (P.02-TI-039)*)
		bT_EG_PrReliefVa2_Active : BOOL; (*temperature exhaust gas pressure relief valve 2 active (P.02-TI-040)*)
		rT_EG_PrReliefVa_LimHi : REAL; (*temperature high warning exhaust gas pressure relief valve 1/2 (P.02-TI-039/040)*)
		rT_EG_PrReliefVa_LimHiHi : REAL; (*temperature high shutdown exhaust gas pressure relief valve 1/2 (P.02-TI-039/040)*)
		rPr_OXIcat_In_Fast_ScalMax : REAL; (*PARA [14134]: OXIcat Exhaust gas inlet pressure fast scale at 20mA*)
		bSafe_Pr_EG_sMonActive : BOOL; (*PARA [15085]: Exhaust gas backpressure - Safety monitoring active (Additional Plc Tag from EG)*) (*SAFETY PLC; Cycle: 5*) (*V04.25.00.00*)
	END_STRUCT;
END_TYPE
