
TYPE
	OUT_Exhaust_Struct : 	STRUCT 
		bDemScavVa : BOOL; (*demand scavenging valve*) (*OldName:ANF_SPKL;Cycle:5*)
		bEG_BoVaClosed : BOOL; (*exhaust gas boiler valve closed*) (*OldName:M_KKZU;Cycle:5*)
		bEG_BoVaOpened : BOOL; (*exhaust gas boiler valve opened*) (*OldName:M_KKAUF;Cycle:5*)
		bEG_ByVaClosed : BOOL; (*exhaust gas bypass valve closed*) (*OldName:M_BKZU;Cycle:5*)
		bEG_ByVaOpened : BOOL; (*exhaust gas bypass valve opened*) (*OldName:M_BKAUF;Cycle:5*)
		bEGScav_Rdy : BOOL; (*release delayed demand auxiliaries from exhaust gas scavenging*) (*OldName:T_VERZ_ANF;Cycle:5*)
		bInAirER_FanSet100 : BOOL; (*demand engine room fan 100% speed*) (*OldName:LUE100;Cycle:5*)
		bN2_ScavCoPrelubeOn : BOOL; (*N2 scavenging command prelubrication ON*) (*OldName:PRELUBE_SC;Cycle:5*)
		bN2_ScavCoStarterOn : BOOL; (*N2 scavening command starter ON*) (*OldName:STARTER_SC;Cycle:5*)
		bPr_N2_LoTon : BOOL; (*pressure N2 low with TON*) (*OldName:ZM_GDMI_N2;Cycle:5*)
		bRel_ScavN2 : BOOL; (*conditions for scavenge with N2*) (*OldName:FG_N2;Cycle:5*)
		bScavFinished : BOOL; (*scavenging cycle finished*) (*OldName:SPUEL_AB;Cycle:5*)
		rT_EGaHE1 : REAL; (*exhaust gas temperature after heat exchanger 1*) (*OldName:ANA_NWTT1; Cycle:5*)
		rT_EGaHE2 : REAL; (*exhaust gas temperature after heat exchanger 2*) (*OldName:ANA_NWTT2; Cycle:5*)
		tCO2_Alarm : HALioDo_Type; (*CO2 alarm*) (*OldName:ST_CO2;Cycle:5*)
		tCO2_DemCodinox : HALioDo_Type; (*CO2 demand CODINOX*) (*OldName:ANF_CODI;Cycle:5*)
		tCO2_FanCoOn : HALioDo_Type; (*CO2 demand fan*) (*OldName:CO2_VENT;Cycle:5*)
		tCO2_MPMode : HALioDo_Type; (*CO2 set CODINOX to mains parallel mode*) (*OldName:CO2_2;Cycle:5*)
		tCO2_Rdy : HALioDo_Type; (*CO2 ready*) (*OldName:BER_CO2;Cycle:5*)
		tCO2_VaCoClose : HALioDo_Type; (*CO2 valve command close*) (*OldName:CO2KZU;Cycle:5*)
		tCO2_VaCoOpen : HALioDo_Type; (*CO2 valve command open*) (*OldName:CO2KAUF;Cycle:5*)
		tCO2_WD : HALioDo_Type; (*CO2 watchdog*) (*OldName:WD_CO2_OK;Cycle:5*)
		tEG_BoVaCoClose : HALioDo_Type; (*exhaust gas boiler valve command close*) (*OldName:KKZU;Cycle:5*)
		tEG_BoVaCoOpen : HALioDo_Type; (*exhaust gas boiler valve command open*) (*OldName:KKAUF;Cycle:5*)
		tEG_ByVaCoClose : HALioDo_Type; (*exhaust gas bypass valve command close*) (*OldName:BKZU;Cycle:5*)
		tEG_ByVaCoOpen : HALioDo_Type; (*exhaust gas bypass valve command open*) (*OldName:BKAUF;Cycle:5*)
		tEX2AB : MM2AmmBase; (*AMM structure*) (*OldName:new pv; Cycle:5;*)
		tEX2PB : MM2ParaBase_type; (*para structure*) (*OldName:new pv; Cycle:5;*)
		tN2_ScavGV_CoOpen : HALioDo_Type; (*N2 Gas Valves vommand open*) (*OldName:N2_GASV;Cycle:5*)
		tN2_ScavSigLampOn : HALioDo_Type; (*Signal lamp for scavenging*) (*OldName:SP_EIN;Cycle:5*)
		tScavFan_Sp : HALioAo_Type; (*scavenging fan setpoint*) (*OldName:sp_spuelv;Cycle:5*)
		tScavFanCoOn : HALioDo_Type; (*scavenging fan comand ON*) (*OldName:SPUELV;Cycle:5*)
		tScavVaCoClose : HALioDo_Type; (*scavenging valve command close*) (*OldName:SPKZU;Cycle:5*)
		tScavVaCoOpen : HALioDo_Type; (*scavenging valve command open*) (*OldName:SPKAUF;Cycle:5*)
		rT_EGbTC : REAL; (*exhaust gas temperature after turbo charger*) (*OldName:NewPv;Cycle:5*)
		rT_EGaTC : REAL; (*exhaust gas temperature after turbo charger*) (*OldName:NewPv;Cycle:5*)
		rT_EGaLPTC_Avg : REAL; (*exhaust gas temperature after low pressure turbo charger - average*) (*OldName:NewPv;Cycle:5*)
		rT_EGbHPTC_Avg : REAL; (*exhaust gas temperature before high pressure turbo charger - average*) (*OldName:NewPv;Cycle:5*)
		rT_EGaHPTC_Avg : REAL; (*exhaust gas temperature after high pressure turbo charger - average*) (*OldName:NewPv;Cycle:5*)
		bAMM_T_EGbTC : BOOL; (*exhaust gas temperature before turbo charger - signal not valid*) (*OldName:NewPv;Cycle:5*)
		bAMM_T_EGaTC : BOOL; (*exhaust gas temperature after turbo charger - signal not valid*) (*OldName:NewPv;Cycle:5*)
		bAMM_T_EGaLPTC_Avg : BOOL; (*exhaust gas temperature after low pressure turbo charger - average not valid*) (*OldName:NewPv;Cycle:5*)
		bAMM_T_EGbHPTC_Avg : BOOL; (*exhaust gas temperature before high pressure turbo charger - average not valid*) (*OldName:NewPv;Cycle:5*)
		bAMM_T_EGaHPTC_Avg : BOOL; (*exhaust gas temperature after high pressure turbo charger - average not valid*) (*OldName:NewPv;Cycle:5*)
		bMsg1165 : BOOL; (*exhaust gas scavenging fan failure//SWAT920/5*) (*OldName:AMM_W11xx;Cycle:5*)
		bMsg9249 : BOOL; (*exhaust gas pressure fast measurement signal failure*) (*OldName:NewPv;Cycle:5*)
		bEngBloc_EX : BOOL; (*engine blockage from EX*)
		bInLouDemEX : BOOL; (*Inlet louver demand for scavenging*)
	END_STRUCT; (*END_OUT*)
	IN_Exhaust_Struct : 	STRUCT 
		bEGValCtr_HeatOutputDown : BOOL; (*exhaust gas flap control - pulse heat output DOWN*) (*OldName:new pv;Cycle:5*)
		bEGValCtr_HeatOutputUp : BOOL; (*exhaust gas flap control - pulse heat output UP*) (*OldName:new pv;Cycle:5*)
		bEng_Dem : BOOL; (*module demanded*) (*OldName:M_AGFD;Cycle:5*)
		bEng_Dem_EPS : BOOL; (*engine demand for emergency operation*) (*OldName:M_NANF;Cycle:5*)
		bEng_Start : BOOL; (*engine start*) (*OldName:M_STRT;Cycle:5*)
		bEng_Start_TC1 : BOOL; (*engine start*) (*OldName:M_STRT;Cycle:1*)
		bFS_Act : BOOL; (* FastStart activated (enabled and required from customer) *)
		bGT2_Select : BOOL; (*Selection gas train 2*) (*OldName:ANW_GST2;Cycle:5*)
		bGV_On : BOOL; (*command open gas valves*) (*OldName:M_GASV;Cycle:5*)
		bIgn_Run : BOOL; (*Ignition in Operation*) (*OldName:ZIB;Cycle:5*)
		bMsg1023 : BOOL; (*Alarm start up failure*) (*OldName:M_ANSTAN;Cycle:5*)
		bMsg1027 : BOOL; (*failure gas train 1*) (*OldName:M_GST1;Cycle:5*)
		bMsg1029 : BOOL; (*failure gas train 2*) (*OldName:M_GST2;Cycle:5*)
		bMsg1031 : BOOL; (*safety loop - ermergency stop*) (*OldName: M_SIS; Cycle: 5;*)
		bMsg1054 : BOOL; (*Fire Alarm*) (*OldName:M_BAL;Cycle:5*)
		bMsg1056 : BOOL; (*safety loop - engine*) (*OldName:M_RUHE;Cycle:5;*)
		bMsg1060 : BOOL; (*Prelube  oil pressure  failure*) (*OldName:M_VSD;Cycle:5*)
		bMsg1078 : BOOL; (*signal failure charge pressure*) (*OldName:newPv;Cycle:5*)
		bMsg1084 : BOOL; (*Measuring signal failure prechamber gas pressure*) (*OldName:M_MS_VKDR;Cyclic:5;*)
		bMsg1108 : BOOL; (*Power process value deviation high*) (*OldName:M_PDIFF;Cycle:5*)
		bMsg3359 : BOOL; (*failure gas train 1 - line 2*) (*OldName:M_GST1_2;Cyclic:5;*)
		bMsg3360 : BOOL; (*failure gas train 1 - line 3*) (*OldName:M_GST1_3;Cyclic:5;*)
		bMsg3361 : BOOL; (*failure gas train 1 - line 4*) (*OldName:M_GST1_4;Cyclic:5;*)
		bPurgeER_Rdy : BOOL; (*purge cycle ready*) (*OldName:purge_rdy;Cycle:5*)
		bRelEngTurn_OilSkid : BOOL; (*release engine turn gear (Durchdrehvorrichtung) from Oil Skid*) (*OldName:newPv;Cycle:5*)
		rN_EngAct : REAL; (*engine speed actual (1/min)*) (*OldName:n_ist, ANA.DREHZ;Cycle:5*)
		rN_EngAct_TC1 : REAL; (*engine speed actual (1/min)*) (*OldName:n_ist, ANA.DREHZ;Cycle:1*)
		iIdx_OMSS : INT; (*index of operation mode selector switch*) (*OldName:BWS_HA;Cycle:5*)
		rCust_SparePara : ARRAY[0..200]OF REAL; (*SPS_REZP1 to SPS_REZP200*) (*OldName: SPS_REZP1, SPS_REZP2, SPS_REZP70; Cycle: 5;*)
		tAB2EX : AmmBase2MM; (*AMM structure*) (*OldName:new pv;Cycle:5*)
		tAuxV_Eng_ok : HALioDi_Type; (*auxiliaries voltage engine ok*) (*OldName:DI_AuxV_Eng_ok;Cycle:5*)
		tCO2_Demand : HALioDi_Type; (*CO2 demand*) (*OldName:ANF_CO2;Cycle:5*)
		tCO2_DevFailure : HALioDi_Type; (*CO2 device failure*) (*OldName:CO2;Cycle:5*)
		tCO2_FanFailure : HALioDi_Type; (*CO2 fan failure*) (*OldName:COV;Cycle:5*)
		tCO2_VaClosed : HALioDi_Type; (*CO2 valve closed*) (*OldName:CO2K_ZU;Cycle:5*)
		tCO2_VaFailure : HALioDi_Type; (*CO2 valve failure*) (*OldName:CO2KST;Cycle:5*)
		tCO2_VaLockout : HALioDi_Type; (*lockout CO2 valve*) (*OldName:BLO_CO2K;Cycle:5*)
		tCO2_VaOpened : HALioDi_Type; (*CO2 valve opened*) (*OldName:CO2K_AUF;Cycle:5*)
		tCodinox_Rdy : HALioDi_Type; (*CODINOX ready for operation*) (*OldName:FG_CODI;Cycle:5*)
		tCustAnaIn : ARRAY[0..120]OF HALioAi_Type; (*Replacement for RAN_KANAL...*) (*OldName: ANA_RAN; Cycle: 5;*)
		tCustDigIn : ARRAY[0..200]OF HALioDi_Type; (*new, reserved for Project specific use*) (*OldName: newPV; Cycle: 5;*)
		tEG_BoVaClosed : HALioDi_Type; (*exhaust gas boiler valve closed*) (*OldName:KK_ZU;Cycle:5*)
		tEG_BoVaClosedTo : HALioDi_Type; (*exhaust gas boiler valve closed torch*) (*OldName:KK_ZU1;Cycle:5*)
		tEG_BoVaFailure : HALioDi_Type; (*exhaust gas boiler valve failure*) (*OldName:KKST;Cycle:5*)
		tEG_BoVaOpened : HALioDi_Type; (*exhaust gas boiler valve opened*) (*OldName:KK_AUF;Cycle:5*)
		tEG_BypassDemand : HALioDi_Type; (*demand exhaust gas bypass*) (*OldName:ABGUM;Cycle:5*)
		tEG_ByVaClosed : HALioDi_Type; (*exhaust gas bypass valve closed*) (*OldName:BK_ZU;Cycle:5*)
		tEG_ByVaClosedTo : HALioDi_Type; (*exhaust gas bypass valve closed torch*) (*OldName:BK_ZU1;Cycle:5*)
		tEG_ByVaFailure : HALioDi_Type; (*exhaust gas bypass valve failure*) (*OldName:BKST;Cycle:5*)
		tEG_ByVaOpened : HALioDi_Type; (*exhaust gas bypass valve opened*) (*OldName:BK_AUF;Cycle:5*)
		tEGScavStart_Ext : HALioDi_Type; (*exhaust gas scavenging start from external*) (*OldName:ANF_SPLV;Cycle:5*)
		tEng_Run : HALioDo_Type; (*engine operating state*) (*OldName:M_BTRB;Cycle:5*)
		tGCB_On : HALioDi_Type; (*generator circuit breaker closed*) (*OldName:GCB_ON;Cycle:5*)
		tManAuxCtr : tManAuxCtr_typ; (*Manual operating auxiliaries control - Handbedienebene*) (*OldName: newPV; Cycle: 5;*)
		tMCB_On : HALioDi_Type; (*mains circuit breaker closed*) (*OldName:MCB_ON;Cycle:5*)
		tN2_GV1_Closed : HALioDi_Type; (*N2 gas valve 1 closed status*) (*OldName:N2V1_ZU;Cycle:5*)
		tN2_GV2_Closed : HALioDi_Type; (*N2 gas valve 2 closed status*) (*OldName:N2V2_ZU;Cycle:5*)
		tP_GenC_SetEUCOf : HALioDi_Type; (*request power value from EU - off (deactivate)*) (*OldName: DI_GCP_P_R; Cycle:HALioDi_Type; Cycle:5;*)
		tP_GenC_SetEUCOn : HALioDi_Type; (*request power value from EU - on (activate)*) (*OldName: DI_GCP_P_S; Cycle:HALioDi_Type; Cycle:5;*)
		tP_GenC_SetFix1EU : HALioDi_Type; (*power value - P- fixvalue 1 from EU*) (*OldName: DI_GCP_P_FIX1; Cycle:HALioDi_Type; Cycle:5;*)
		tP_GenC_SetFix2EU : HALioDi_Type; (*power value - P- fixvalue 2 from EU*) (*OldName: DI_GCP_P_FIX2; Cycle:HALioDi_Type; Cycle:5;*)
		tP_GenC_SetFix3EU : HALioDi_Type; (*power value - P- fixvalue 3 from EU*) (*OldName: DI_GCP_P_FIX3; Cycle:HALioDi_Type; Cycle:5;*)
		tP_GenC_SetFix4EU : HALioDi_Type; (*power value - P- fixvalue 4 from EU*) (*OldName: DI_GCP_P_FIX4; Cycle:HALioDi_Type; Cycle:5;*)
		tP_GenC_SetFix5EU : HALioDi_Type; (*power value - P- fixvalue 5 from EU*) (*OldName: DI_GCP_P_FIX5; Cycle:HALioDi_Type; Cycle:5;*)
		tPB2MM : ParaBase2MM_type; (*para struct*) (*OldName:new pv;Cycle:5*)
		tPLim_GenC_SetEUCOf : HALioDi_Type; (*setpoint power limitation (Plim) from EU - off (deactivate)*) (*OldName: DI_GCP_Plim_R; Cycle:HALioDi_Type; Cycle:5;*)
		tPLim_GenC_SetEUCOn : HALioDi_Type; (*setpoint power limitation (Plim) from EU - on (activate)*) (*OldName: DI_GCP_Plim_S; Cycle:HALioDi_Type; Cycle:5;*)
		tPLim_GenC_SetEUPFix1 : HALioDi_Type; (*power limitation fixvalue 1*) (*OldName: DI_EVU_1; Cycle:HALioDi_Type; Cycle:5;*)
		tPLim_GenC_SetEUPFix2 : HALioDi_Type; (*power limitation fixvalue 2*) (*OldName: DI_EVU_2; Cycle:HALioDi_Type; Cycle:5;*)
		tPLim_GenC_SetEUPFix3 : HALioDi_Type; (*power limitation fixvalue 3*) (*OldName: DI_EVU_3; Cycle:HALioDi_Type; Cycle:5;*)
		tPLim_GenC_SetEUPFix4 : HALioDi_Type; (*power limitation fixvalue 4*) (*OldName: DI_EVU_4; Cycle:HALioDi_Type; Cycle:5;*)
		tPLim_GenC_SetEUPFix5 : HALioDi_Type; (*power limitation fixvalue 5*) (*OldName: DI_EVU_5; Cycle:HALioDi_Type; Cycle:5;*)
		tPr_Ch_P2s : HALioAi_Type; (*actual charge pressure before throttle valve(P2s)[bar]*) (*OldName:pl_ist; Cycle:5;*)
		tPr_Ch_P2s_A : HALioAi_Type; (*actual charge pressure before throttle valve(P2s)bank A[bar]*) (*OldName:pl_ist; Cycle:5;*)
		tPr_Ch_P2s_B : HALioAi_Type; (*actual charge pressure before throttle valve(P2s)bank B[bar]*) (*OldName:pl_ist; Cycle:5;*)
		tPr_Diff_ExGCooler : HALioAi_Type; (*differential pressure exhaust gas cooler*) (*OldName:VABK_WE;Cycle:5*)
		tPr_Diff_ExGFilter : HALioAi_Type; (*differential pressure exhaust gas filter*) (*OldName:VABK_WE;Cycle:5*)
		tPr_EG_Hi : HALioDi_Type; (*exhaust gas back pressure high*) (*OldName:ABGD;Cycle:5*)
		tPr_EGaHPTC_A : HALioAi_Type; (*exhaust gas pressure after high-pressure turbocharger A (M.02-PI-153)*) (*OldName:new pv;Cycle:5*)
		tPr_EGaHPTC_B : HALioAi_Type; (*exhaust gas pressure after high-pressure turbocharger B (M.02-PI-253)*) (*OldName:new pv;Cycle:5*)
		tPr_EGaLPTC_A : HALioAi_Type; (*exhaust gas pressure after low-pressure turbocharger A (M.02-PI-154)*) (*OldName:new pv;Cycle:5*)
		tPr_EGaLPTC_B : HALioAi_Type; (*exhaust gas pressure after low-pressure turbocharger B (M.02-PI-254)*) (*OldName:new pv;Cycle:5*)
		tPr_EGbHPTC_A : HALioAi_Type; (*exhaust gas pressure before high-pressure turbocharger A (M.02-PI-152)*) (*OldName:new pv;Cycle:5*)
		tPr_EGbHPTC_B : HALioAi_Type; (*exhaust gas pressure before high-pressure turbocharger B (M.02-PI-252)*) (*OldName:new pv;Cycle:5*)
		tPr_EngLubOil : HALioAi_Type; (*engine lubricating oil pressure*) (*OldName:ANA.ODR;Cycle:5*)
		tPr_N2_Hi : HALioDi_Type; (*pressure N2 high*) (*OldName:GDMA_N2;Cycle:5*)
		tPr_N2_Lo : HALioDi_Type; (*pressure N2 low*) (*OldName:GDMI_N2;Cycle:5*)
		tPr_PC : HALioAi_Type; (*Pressure prechamber*) (*OldName:ANA_VKDR;Cyclic:5;*)
		tScavFanCB_trip : HALioDi_Type; (*exhaust gas scavenging fan circuit breaker tripped*) (*OldName:SPV_CB_trip;Cycle:5*)
		tScavFanFC_P_Lo : HALioDi_Type; (*exhaust gas scavenging fan frequency converter power low*) (*OldName:SPV_FU_Po_lo;Cycle:5*)
		tScavFanFC_Rdy : HALioDi_Type; (*exhaust gas scavenging fan frequency converter ready for operation*) (*OldName:SPV_FU_rdy;Cycle:5*)
		tScavFanOp : HALioDi_Type; (*exhaust gas scavenging fan operating*) (*OldName:RM_SPUELV;Cycle:5*)
		tScavVaClosed : HALioDi_Type; (*scavenging valve closed*) (*OldName:SPK_ZU;Cycle:5*)
		tScavVaFailure : HALioDi_Type; (*scavenging valve failure*) (*OldName:SPKST;Cycle:5*)
		tScavVaOpened : HALioDi_Type; (*scavenging valve opened*) (*OldName:SPK_AUF;Cycle:5*)
		tT_bScavValve : HALioAi_Type; (*air temperature before exhaust gas scavenging valve*)
		tT_EGbCat : HALioAi_Type; (*OXIcat Inlet temperature (P.02-TI-046)*) (*OldName: VKAT_WE; Cycle: 5*)
		tT_EGaCat : HALioAi_Type; (*OXIcat Outlet temperature (P.02-TI-047)*) (*OldName: NKAT_WE; Cycle: 5*)
		tPr_OXIcat_In : HALioAi_Type; (*OXIcat Inlet pressure (P.02-PI-003)*) (*OldName: newPV; Cycle: 5*)
		tPr_OXIcat_Out : HALioAi_Type; (*OXIcat Outlet pressure (P.02-PI-004)*) (*OldName: newPV; Cycle: 5*)
		tPr_EG_Deflag_Fast : HALioAi_Type; (*Exhaust gas pressure fast (deflagration detection) (P.02-PI-010)*) (*OldName: tPr_OXIcat_In_Fast; Cycle: 1*)
		tPr_EG_Deflag_Fast_TC1 : HALioAi_Type; (*Exhaust gas pressure fast (deflagration detection) (P.02-PI-010)*) (*OldName: tPr_OXIcat_In_Fast; Cycle: 1*)
		rP_Act_Norm_Filt : REAL; (*Actual power related to rP_Nom [%Pnom] filtered T=1s*) (*OldName: P_IST_PROM; Cycle:5*)
		tT_CO2_Hi : HALioDi_Type; (*CO2 temperature reactor chamber high*) (*OldName:CO2TP;Cycle:5*)
		tT_EGaHE : HALioAi_Type; (*exhaust gas temperature after heat exchanger*) (*OldName:NABK_WE;Cycle:5*)
		tT_EGaHE1 : HALioAi_Type; (*exhaust gas temperature after heat exchanger 1*) (*OldName:NWTT1_WE;Cycle:5*)
		tT_EGaHE2 : HALioAi_Type; (*exhaust gas temperature after heat exchanger 2*) (*OldName:NWTT2_WE;Cycle:5*)
		tT_EGaHPTC_A : HALioAi_Type; (*exhaust gas temperatur after high-pressure turbocharger A (M.02-TI-167)*) (*OldName:new pv;Cycle:5*)
		tT_EGaHPTC_B : HALioAi_Type; (*exhaust gas temperatur after high-pressure turbocharger B (M.02-TI-267)*) (*OldName:new pv;Cycle:5*)
		tT_EGaLPTC_A : HALioAi_Type; (*exhaust gas temperature after low pressure turbo charger A (M.02-TI-168)*) (*OldName:t_EGaLPTC_A;Cycle:5*)
		tT_EGaLPTC_B : HALioAi_Type; (*exhaust gas temperature after low pressure turbo charger B (M.02-TI-268)*) (*OldName:t_EGaLPTC_B;Cycle:5*)
		tT_EGaTC : HALioAi_Type; (*exhaust gas temperature after turbo charger*) (*OldName:VABK_WE;Cycle:5*)
		tT_EGbHPTC_A : HALioAi_Type; (*exhaust gas temperature before high-pressure turbocharger A (M.02-TI-166)*) (*OldName:new pv;Cycle:5*)
		tT_EGbHPTC_B : HALioAi_Type; (*exhaust gas temperature before high-pressure turbocharger B (M.02-TI-266)*) (*OldName:new pv;Cycle:5*)
		tT_EGbTC : HALioAi_Type; (*exhaust gas temperature before turbo charger*) (*OldName:T3_WE;Cycle:5*)
		tT_PlateHE : HALioAi_Type; (*plate temperature heat exchanger*) (*OldName:ROHR_WE;Cycle:5*)
		tT_EG_PrReliefVa1 : HALioAi_Type; (*temperature exhaust gas pressure relief valve 1 (P.02-TI-039)*)
		tT_EG_PrReliefVa2 : HALioAi_Type; (*temperature exhaust gas pressure relief valve 2 (P.02-TI-040)*)
		tBurstingDisk1_Ok : HALioDi_Type; (*DI exhaust Monitoring bursting disc 1 (P.02-GS-001)*)
		tBurstingDisk2_Ok : HALioDi_Type; (*DI exhaust Monitoring bursting disc 2 (P.02-GS-002)*)
		bInLouRelVE : BOOL; (*inlet louvers open or not closed*)
		bMsg2295 : BOOL; (*engine room ventilation failure inlet air*)
	END_STRUCT; (*END_IN*)
	VIS2MM_Struct : 	STRUCT 
		bEGScavStart : BOOL; (*start manual EG scavenging - button*) (*OldName: ANF_SPLV_MAN; Cycle: 5*)
		bEGScavStop : BOOL; (*stop manual EG scavenging - button*) (*OldName: newPV; Cycle: 5*)
		bN2ScavStart : BOOL; (*start manual N2 scavenging - button*) (*OldName: START_SP; Cycle: 5*)
		bN2ScavStop : BOOL; (*stop manual N2 scavenging - button*) (*OldName: newPV; Cycle: 5*)
		iCnt_OpHours_Oxi : DINT; (*op.hours oxi cat*) (*OldName:new pv;Cycle:5*)
		bEGValve_Remote : BOOL; (*exhaust gas flap remote control*)
		bBypassDemand : BOOL; (*demand exhaust gas bypass from vis*)
	END_STRUCT;
	MM2VIS_Struct : 	STRUCT 
		bCO2_FanCoOn : BOOL; (*CO2 fan comand on*) (*OldName:CO2_VENT;Cycle:5*)
		bCO2_VaOpened : BOOL; (*CO2 valve opened*) (*OldName:CO2K_AUF;Cycle:5*)
		bCodinox_Rdy : BOOL; (*CODINOX ready for operation*) (*OldName:FG_CODI;Cycle:5*)
		bEG_BoVaOpened : BOOL; (*exhaust gas boiler valve opened*) (*OldName:B_SV[31];Cycle:5*)
		bEG_ByVaOpened : BOOL; (*exhaust gas bypass valve opened*) (*OldName:B_SV[32];Cycle:5*)
		bMsg1045 : BOOL; (*catalyst temperature high - disabled*) (*OldName:AMM_A10xx;Cycle:5*)
		bMsg1046 : BOOL; (*exhaust gas flap failure*) (*OldName:AMM_A10xx;Cycle:5*)
		bMsg1069 : BOOL; (*catalyst temperature signal failure - disabled*) (*OldName:AMM_A10xx;Cycle:5*)
		bMsg1092 : BOOL; (*exhaust gas scavenging valve failure*) (*OldName:AMM_A10xx;Cycle:5*)
		bMsg1104 : BOOL; (*plate temperature heat exchanger high*) (*OldName:AMM_A11xx;Cycle:5*)
		bMsg1106 : BOOL; (*plate temperature heat exchanger signal failure*) (*OldName:AMM_A11xx;Cycle:5*)
		bMsg1161 : BOOL; (*exhaust gas temperature before catalyst signal failure - disabled*) (*OldName:AMM_W11xx;Cycle:5*)
		bMsg1162 : BOOL; (*exhaust gas temperature after catalyst signal failure - disabled*) (*OldName:AMM_W11xx;Cycle:5*)
		bMsg1163 : BOOL; (*exhaust gas temperature before heat exchanger signal failure*) (*OldName:AMM_W11xx;Cycle:5*)
		bMsg1164 : BOOL; (*exhaust gas temperature after exhaust heat exchanger measuring signal failure*) (*OldName:AMM_W11xx;Cycle:5*)
		bMsg1165 : BOOL; (*exhaust gas scavenging fan failure*) (*OldName:AMM_W11xx;Cycle:5*)
		bMsg1169 : BOOL; (*exhaust gas temperature before catalyst high - disabled*) (*OldName:AMM_W11xx;Cycle:5*)
		bMsg1170 : BOOL; (*exhaust gas temperature after catalyst high - disabled*) (*OldName:AMM_W11xx;Cycle:5*)
		bMsg1171 : BOOL; (*exhaust gas temperature after turbo charger high*) (*OldName:AMM_W11xx;Cycle:5*)
		bMsg1172 : BOOL; (*exhaust gas temperature after heat exchanger high*) (*OldName:AMM_W11xx;Cycle:5*)
		bMsg1173 : BOOL; (*plate temperature heat exchanger high*) (*OldName:AMM_W11xx;Cycle:5*)
		bMsg1174 : BOOL; (*catalyst temperature high high - disabled*) (*OldName:AMM_W11xx;Cycle:5*)
		bMsg1273 : BOOL; (*demand exhaust gas scavenging flap open*) (*OldName:NewPv; Cycle:5*)
		bMsg1274 : BOOL; (*demand exhaust gas scavenging flap close*) (*OldName:NewPv; Cycle:5*)
		bMsg1275 : BOOL; (*exhaust gas scavenging flap opened*) (*OldName:NewPv; Cycle:5*)
		bMsg1276 : BOOL; (*exhaust gas scavenging flap closed*) (*OldName:NewPv; Cycle:5*)
		bMsg1277 : BOOL; (*demand exhaust gas scavenging fan on*) (*OldName:NewPv; Cycle:5*)
		bMsg1278 : BOOL; (*demand exhaust gas scavenging fan off*) (*OldName:NewPv; Cycle:5*)
		bMsg1279 : BOOL; (*demand exhaust gas scavenging fan operation on*) (*OldName:NewPv; Cycle:5*)
		bMsg1280 : BOOL; (*demand exhaust gas scavenging fan operation off*) (*OldName:NewPv; Cycle:5*)
		bMsg1288 : BOOL; (*CO2 flap open*) (*OldName:NewPv; Cycle:5*)
		bMsg1289 : BOOL; (*CO2 flap closed*) (*OldName:NewPv; Cycle:5*)
		bMsg1290 : BOOL; (*CO2 demand on*) (*OldName:NewPv; Cycle:5*)
		bMsg1291 : BOOL; (*CO2 demand off*) (*OldName:NewPv; Cycle:5*)
		bMsg2098 : BOOL; (*exhaust gas flap failure*) (*OldName:AMM_W20xx;Cycle:5*)
		bMsg2112 : BOOL; (*catalyst temperature signal failure - disabled*) (*OldName:AMM_W21xx;Cycle:5*)
		bMsg2113 : BOOL; (*plate temperature heat exchanger signal failure*) (*OldName:AMM_W21xx;Cycle:5*)
		bMsg2310 : BOOL; (*exhaust gas temperature after low pressure turbo charger A high*) (*OldName:NewPv;Cycle:5*)
		bMsg2311 : BOOL; (*exhaust gas temperature after low pressure turbo charger B high*) (*OldName:NewPv;Cycle:5*)
		bMsg2312 : BOOL; (*exhaust gas temperature after low pressure turbo charger A signal failure*) (*OldName:NewPv;Cycle:5*)
		bMsg2313 : BOOL; (*exhaust gas temperature after low pressure turbo charger B signal failure*) (*OldName:NewPv;Cycle:5*)
		bMsg2315 : BOOL; (*air temperature before exhaust gas scavening valve maximum*)
		bMsg2319 : BOOL; (*OXIcat Outlet temperature measurement signal failure*) (*OldName: newPV; Cycle: 5*)
		bMsg2320 : BOOL; (*OXIcat Outlet temperature maximum*) (*OldName: newPV; Cycle: 5*)
		bMsg2321 : BOOL; (*exhaust gas temperature after turbo charger high*)
		bMsg2322 : BOOL; (*exhaust gas temperature after turbo charger signal failure*)
		bMsg2337 : BOOL; (*temperature high exhaust gas pressure relief valve 1*)
		bMsg2338 : BOOL; (*temperature high exhaust gas pressure relief valve 2*)
		bMsg2340 : BOOL; (*exhaust gas pressure fast maximum*)
		bMsg2374 : BOOL; (*Bursting disc triggered (P.02-GS-001/P.02-GS-002)*)
		bMsg2468 : BOOL; (*air temperature before exhaust gas scavening valve maximum signal failure*)
		bMsg2469 : BOOL; (*air temperature before exhaust gas scavening valve maximum plausibility check*)
		bMsg2494 : BOOL; (*OXIcat Inlet pressure measurement signal failure*) (*OldName: newPV; Cycle: 5*)
		bMsg2495 : BOOL; (*OXIcat Outlet pressure measurement signal failure*) (*OldName: newPV; Cycle: 5*)
		bMsg2496 : BOOL; (*OXIcat Differential pressure minimum*) (*OldName: newPV; Cycle: 5*)
		bMsg2497 : BOOL; (*OXIcat Exhaust gas inlet pressure fast measurement signal failure*) (*OldName: newPV; Cycle: 5*)
		bMsg2498 : BOOL; (*OXIcat Exhaust gas inlet pressure fast maximum*) (*OldName: newPV; Cycle: 5*)
		bMsg2499 : BOOL; (*OXIcat Inlet temperature measurement signal failure*) (*OldName: newPV; Cycle: 5*)
		bMsg2500 : BOOL; (*OXIcat Inlet temperature maximum*) (*OldName: newPV; Cycle: 5*)
		bMsg2546 : BOOL; (*exhaust gas temperature after low pressure turbo charger A high*) (*OldName:AMM_W25xx;Cycle:5*)
		bMsg2547 : BOOL; (*exhaust gas temperature after low pressure turbo charger B high*) (*OldName:AMM_W25xx;Cycle:5*)
		bMsg2549 : BOOL; (*exhaust gas temperature after low pressure turbo charger A signal failure*) (*OldName:AMM_W25xx;Cycle:5*)
		bMsg2551 : BOOL; (*exhaust gas temperature after low pressure turbo charger B signal failure*) (*OldName:AMM_W25xx;Cycle:5*)
		bMsg2601 : BOOL; (*exhaust gas scavenging fan circuit breaker tripped*) (*OldName:AMM_W26xx;Cycle:5*)
		bMsg2622 : BOOL; (*exhaust gas temperature high after low pressure turbo charger*) (*OldName:AMM_W26xx;Cycle:5*)
		bMsg2623 : BOOL; (*signal failure exhaust gas temperature after low pressure turbo charger*) (*OldName:AMM_W26xx;Cycle:5*)
		bMsg2655 : BOOL; (*signal failure exhaust gas temperature before high-pressure turbocharger A (M.02-TI-166)*) (*OldName:new pv;Cycle:5*)
		bMsg2656 : BOOL; (*signal failure exhaust gas temperature before high-pressure turbocharger B (M.02-TI-266)*) (*OldName:new pv;Cycle:5*)
		bMsg2657 : BOOL; (*signal failure exhaust gas temperatur after high-pressure turbocharger A (M.02-TI-167)*) (*OldName:new pv;Cycle:5*)
		bMsg2658 : BOOL; (*signal failure exhaust gas temperatur after high-pressure turbocharger B (M.02-TI-267)*) (*OldName:new pv;Cycle:5*)
		bMsg2659 : BOOL; (*signal failure exhaust gas pressure before high-pressure turbocharger A (M.02-PI-152)*) (*OldName:new pv;Cycle:5*)
		bMsg2660 : BOOL; (*signal failure exhaust gas pressure before high-pressure turbocharger B (M.02-PI-252)*) (*OldName:new pv;Cycle:5*)
		bMsg2661 : BOOL; (*signal failure exhaust gas pressure after high-pressure turbocharger A (M.02-PI-153)*) (*OldName:new pv;Cycle:5*)
		bMsg2662 : BOOL; (*signal failure exhaust gas pressure after high-pressure turbocharger B (M.02-PI-253)*) (*OldName:new pv;Cycle:5*)
		bMsg2663 : BOOL; (*signal failure exhaust gas pressure after low-pressure turbocharger A (M.02-PI-154)*) (*OldName:new pv;Cycle:5*)
		bMsg2664 : BOOL; (*signal failure exhaust gas pressure after low-pressure turbocharger B (M.02-PI-254)*) (*OldName:new pv;Cycle:5*)
		bMsg2743 : BOOL; (*signal failure differential pressure exhaust gas filter*) (*OldName:AMM_W35xx;Cycle:5*)
		bMsg2744 : BOOL; (*signal failure differential pressure exhaust gas cooler*) (*OldName:AMM_W35xx;Cycle:5*)
		bMsg2745 : BOOL; (*differential pressure exhaust gas filter maximum 1*) (*OldName:AMM_W35xx;Cycle:5*)
		bMsg2746 : BOOL; (*differential pressure exhaust gas filter maximum 2*) (*OldName:AMM_W35xx;Cycle:5*)
		bMsg2747 : BOOL; (*differential pressure exhaust gas filter minimum*) (*OldName:AMM_W35xx;Cycle:5*)
		bMsg2748 : BOOL; (*differential pressure exhaust gas cooler maximum*) (*OldName:AMM_W35xx;Cycle:5*)
		bMsg2793 : BOOL; (*exhaust gas scavenging fan not ready*) (*OldName:new pv;Cycle:5*)
		bMsg2847 : BOOL; (*N2 gas valves opened*) (*OldName:AMM_B28xx; Cycle:5*)
		bMsg2848 : BOOL; (*N2 gas valves closed*) (*OldName:AMM_B28xx; Cycle:5*)
		bMsg3100 : BOOL; (*exhaust gas temperature before turbo charger high*) (*OldName:AMM_A31xx;Cycle:5*)
		bMsg3214 : BOOL; (*exhaust gas temperature before turbo charger signal failure*) (*OldName:AMM_W32xx;Cycle:5*)
		bMsg3215 : BOOL; (*exhaust gas temperature before turbo charger high*) (*OldName:AMM_W32xx;Cycle:5*)
		bMsg3313 : BOOL; (*CODINOX: CO2 reactor chamber temperature high*) (*OldName:AMM_A33xx;Cycle:5*)
		bMsg3314 : BOOL; (*CODINOX: CO2 valve failure*) (*OldName:AMM_A33xx;Cycle:5*)
		bMsg3349 : BOOL; (*N2 gas valves position failure*) (*OldName:AMM_W33xx;Cycle:5*)
		bMsg3366 : BOOL; (*exhaust gas scavenging fan failure*) (*OldName:newPv;Cycle:5*)
		bMsg3394 : BOOL; (*exhaust gas temperature after exhaust heat exchanger 1 high*) (*OldName: new PV; Cycle: 5;*)
		bMsg3395 : BOOL; (*exhaust gas temperature after exhaust heat exchanger 2 high*) (*OldName: new PV; Cycle: 5;*)
		bMsg3397 : BOOL; (*differential pressure exhaust gas filter maximum shut down*) (*OldName:AMM_W35xx;Cycle:5*)
		bMsg3417 : BOOL; (*pre chamber diff.press.high during engine stop (exh.gas scav.required before next start)*) (*OldName:newPv;Cycle:5*)
		bMsg3490 : BOOL; (*exhaust gas temperature after exhaust heat exchanger 1 high*) (*OldName: new PV; Cycle: 5;*)
		bMsg3491 : BOOL; (*Exhaust gas temperature after exhaust heat exchanger 2 high*) (*OldName: new PV; Cycle: 5;*)
		bMsg3510 : BOOL; (*CODINOX: CO2 Ventilation fan failure*) (*OldName:AMM_W35xx;Cycle:5*)
		bMsg3511 : BOOL; (*CODINOX: CO2 station failure*) (*OldName:AMM_W35xx;Cycle:5*)
		bMsg3512 : BOOL; (*CODINOX: CO2 valve failure*) (*OldName:AMM_W35xx;Cycle:5*)
		bMsg3513 : BOOL; (*CODINOX: exhaust gas temperature after heat exchanger 1 measuring signal failure*) (*OldName:AMM_W35xx;Cycle:5*)
		bMsg3514 : BOOL; (*CODINOX: exhaust gas temperature after heat exchanger 2 measuring signal failure*) (*OldName:AMM_W35xx;Cycle:5*)
		bMsg3528 : BOOL; (*exhaust gas back pressure high*) (*OldName:AMM_W35xx;Cycle:5*)
		bMsg3580 : BOOL; (*N2 gas pressure low*) (*OldName:AMM_W35xx;Cycle:5*)
		bMsg3581 : BOOL; (*N2 gas pressure high*) (*OldName:AMM_W35xx;Cycle:5*)
		bMsg3582 : BOOL; (*N2 scavenging run failure*) (*OldName:AMM_W35xx;Cycle:5*)
		bMsg9215 : BOOL; (*air temperature before exhaust gas scavening valve maximum *) (*SWAT920/5*)
		bMsg9249 : BOOL; (*exhaust gas pressure fast measuring signal failure*)
		bMsg9305 : BOOL; (*temperature high exhaust gas pressure relief valve 1*)
		bMsg9306 : BOOL; (*temperature high exhaust gas pressure relief valve 2*)
		bMsg9307 : BOOL; (*temperature high exhaust gas pressure relief valve 1 signal failure*)
		bMsg9308 : BOOL; (*temperature high exhaust gas pressure relief valve 2 signal failure*)
		bMsg9310 : BOOL; (*OXIcat Outlet temperature measurement signal failure*)
		bMsg9347 : BOOL; (*exhaust gas flaps - module standstill position not reached*)
		bMsg9348 : BOOL; (*exhaust gas flaps - status signal failure*)
		bN2_ScavGV_CoOpen : BOOL; (*N2 Gas Valves command open*) (*OldName:N2_GASV;Cycle:5*)
		bN2_ScavSigLampOn : BOOL; (*N2 scavenging running*) (*OldName:SP_EIN;Cycle:5*)
		bScavFanCoOn : BOOL; (*scavenging fan command on*) (*OldName:B_SV[41];Cycle:5*)
		bScavVaOpened : BOOL; (*scavenging valve is open*) (*OldName:B_SV[40];Cycle:5*)
		bT_EGaHE1_Active : BOOL; (*exhaust gas temperature after heat exchanger active*) (*OldName:usNWTT1_a;Cycle:5*)
		bT_EGaHE2_Active : BOOL; (*exhaust gas temperature after heat exchanger active*) (*OldName:usNWTT2_a;Cycle:5*)
		rPr_Diff_ExGCooler : REAL; (*differential pressure exhaust gas cooler*) (*OldName:NWTT1_WE;Cycle:5*)
		rPr_Diff_ExGFilter : REAL; (*differential pressure exhaust gas filter*) (*OldName:NWTT1_WE;Cycle:5*)
		rPr_EGaHPTC_A : REAL; (*exhaust gas pressure after high-pressure turbocharger A (M.02-PI-153)*) (*OldName:new pv;Cycle:5*)
		rPr_EGaHPTC_B : REAL; (*exhaust gas pressure after high-pressure turbocharger B (M.02-PI-253)*) (*OldName:new pv;Cycle:5*)
		rPr_EGaLPTC_A : REAL; (*exhaust gas pressure after low-pressure turbocharger A (M.02-PI-154)*) (*OldName:new pv;Cycle:5*)
		rPr_EGaLPTC_B : REAL; (*exhaust gas pressure after low-pressure turbocharger B (M.02-PI-254)*) (*OldName:new pv;Cycle:5*)
		rPr_EGbHPTC_A : REAL; (*exhaust gas pressure before high-pressure turbocharger A (M.02-PI-152)*) (*OldName:new pv;Cycle:5*)
		rPr_EGbHPTC_B : REAL; (*exhaust gas pressure before high-pressure turbocharger B (M.02-PI-252)*) (*OldName:new pv;Cycle:5*)
		rT_bScavValve : REAL; (*air temperature before exhaust gas scavening valve*)
		rT_EGbCat : REAL; (*OXIcat Inlet temperature*) (*OldName: ANA.VKAT; Cycle: 5*)
		rT_EGaCat : REAL; (*OXIcat Outlet temperature*) (*OldName: ANA.NKAT; Cycle: 5*)
		rPr_OXIcat_In : REAL; (*OXIcat Inlet pressure*) (*OldName: newPV; Cycle: 5*)
		rPr_OXIcat_Diff : REAL; (*OXIcat Differential pressure*) (*OldName: newPV; Cycle: 5*)
		rPr_OXIcat_In_Fast : REAL; (*OXIcat Exhaust gas inlet pressure fast*) (*OldName: newPV; Cycle: 1*)
		rPr_OXIcat_In_Fast_Peak : REAL; (*OXIcat Exhaust gas inlet peak pressure fast*) (*OldName: newPV; Cycle: 5*)
		rPr_OXIcat_In_Fast_Minimum : REAL; (*OXIcat Exhaust gas inlet minimum pressure fast*)
		rT_EGaHE : REAL; (*exhaust gas temperature after heat exchanger*) (*OldName:ANA.NABK;Cycle:5*)
		rT_EGaHE1 : REAL; (*exhaust gas temperature after heat exchanger 1*) (*OldName:NWTT1_WE;Cycle:5*)
		rT_EGaHE2 : REAL; (*exhaust gas temperature after heat exchanger 2*) (*OldName:NWTT2_WE;Cycle:5*)
		rT_EGaHPTC_A : REAL; (*exhaust gas temperatur after high-pressure turbocharger A (M.02-TI-167)*) (*OldName:new pv;Cycle:5*)
		rT_EGaHPTC_B : REAL; (*exhaust gas temperatur after high-pressure turbocharger B (M.02-TI-267)*) (*OldName:new pv;Cycle:5*)
		rT_EGaLPTC_A : REAL; (*exhaust gas temperature after low pressure turbo charger A*) (*OldName:t_EGaLPTC_A;Cycle:5*)
		rT_EGaLPTC_B : REAL; (*exhaust gas temperature after low pressure turbo charger B*) (*OldName:t_EGaLPTC_B;Cycle:5*)
		rT_EGaTC : REAL; (*exhaust gas temperature after turbo charger*) (*OldName:ANA.VABK;Cycle:5*)
		rT_EGbHPTC_A : REAL; (*exhaust gas temperature before high-pressure turbocharger A (M.02-TI-166)*) (*OldName:new pv;Cycle:5*)
		rT_EGbHPTC_B : REAL; (*exhaust gas temperature before high-pressure turbocharger B (M.02-TI-266)*) (*OldName:new pv;Cycle:5*)
		rT_EGbTC : REAL; (*exhaust gas temperature before turbo charger*) (*OldName:ANA.T3;Cycle:5*)
		rT_PlateHE : REAL; (*plate temperature heat exchanger*) (*OldName:ANA.ROHR;Cycle:5*)
		rT_EGaLPTC_Avg : REAL; (*exhaust gas temperature after low pressure turbo charger - average*) (*OldName:NewPv;Cycle:5*)
		rT_EGbHPTC_Avg : REAL; (*exhaust gas temperature before high pressure turbo charger - average*) (*OldName:NewPv;Cycle:5*)
		rT_EGaHPTC_Avg : REAL; (*exhaust gas temperature after high pressure turbo charger - average*) (*OldName:NewPv;Cycle:5*)
		rT_EG_PrReliefVa1 : REAL; (*temperature exhaust gas pressure relief valve 1 (P.02-TI-039)*)
		rT_EG_PrReliefVa2 : REAL; (*temperature exhaust gas pressure relief valve 2 (P.02-TI-040)*)
		bScavRun : BOOL; (*scavening running*)
		tiScavRestTime : TIME; (*scavening rest time*)
	END_STRUCT; (*END_MM2VIS*)
	Perm_EX_Struct : 	STRUCT 
		iCnt_OpHours_Oxi : DINT; (*synchronization operating mode selection*)
		rPermValue02 : REAL; (*spare permanent value - replace with new vars of same lenght, when needed*) (*OldName:new PV;Cycle:2;*)
		rPermValue03 : REAL; (*spare permanent value - replace with new vars of same lenght, when needed*) (*OldName:new PV;Cycle:2;*)
		rPermValue04 : REAL; (*spare permanent value - replace with new vars of same lenght, when needed*) (*OldName:new PV;Cycle:2;*)
		rPermValue05 : REAL; (*spare permanent value - replace with new vars of same lenght, when needed*) (*OldName:new PV;Cycle:2;*)
		rPermValue06 : REAL; (*spare permanent value - replace with new vars of same lenght, when needed*) (*OldName:new PV;Cycle:2;*)
		rPermValue07 : REAL; (*spare permanent value - replace with new vars of same lenght, when needed*) (*OldName:new PV;Cycle:2;*)
		rPermValue08 : REAL; (*spare permanent value - replace with new vars of same lenght, when needed*) (*OldName:new PV;Cycle:2;*)
		rPermValue09 : REAL; (*spare permanent value - replace with new vars of same lenght, when needed*) (*OldName:new PV;Cycle:2;*)
		rPermValue10 : REAL; (*spare permanent value - replace with new vars of same lenght, when needed*) (*OldName:new PV;Cycle:2;*)
	END_STRUCT;
	tManAuxCtr_typ : 	STRUCT 
		bGnl_Rel : BOOL; (*General release. Safety conditions (gas alarm, fire alarm, safety loop, ..) are OK.*) (*OldName: new PV; Cycle: 5;*)
		bECWP_PreH_COf_Man : BOOL; (*engine cooling water pump preheating demand off*) (*OldName: new PV; Cycle: 5;*)
		bECW_PreH_COf_Man : BOOL; (*engine cooling water preheating demand off*) (*OldName: new PV; Cycle: 5;*)
		bInAirER_Lou2DemOpen_Man : BOOL; (*demand open air inlet louver 2*) (*OldName: new PV; Cycle:5;*)
		bInAirER_Lou1DemOpen_Man : BOOL; (*demand open air inlet louver 1*) (*OldName: new PV; Cycle:5;*)
		bOutAirER_LouDemOpen_Man : BOOL; (*open air outlet louver *) (*OldName: new PV; Cycle:5;*)
		bInAirER_Fan1DemOn_Man : BOOL; (*demand air inlet ventilator 1*) (*OldName: new PV; Cycle:5;*)
		bInAirER_Fan2DemOn_Man : BOOL; (*demand air inlet ventilator 2*) (*OldName: new PV; Cycle:5;*)
		bER_FC_Set_Man : BOOL; (*demand engine room frequency converter setpoint*) (*OldName: new PV; Cycle:5;*)
		rER_FC_Set_Man : REAL; (*engine room frequency converter setpoint [%]*) (*OldName: new PV; Cycle:5;*)
		bER_OutlV_FC_Set_Man : BOOL; (*demand engine room air outlet ventilation frequency converter setpoint*) (*OldName: new PV; Cycle:5;*)
		rER_OutlV_FC_Set_Man : REAL; (*engine room air outlet ventilation frequency converter setpoint [%]*) (*OldName: new PV; Cycle:5;*)
		bEC_DemPump_Man : BOOL; (*emergency cooler demand pump*) (*OldName: new PV; Cycle:5;*)
		bEC_DemFan_Man : BOOL; (*emergency cooler demand fan 1 - 16*) (*OldName: new PV; Cycle:5;*)
		bChC_DemPump_Man : BOOL; (*charge cooler demand pump*) (*OldName: new PV; Cycle:5;*)
		bChC_DemFan_Man : BOOL; (*charge cooler demand fan 1 - 16*) (*OldName: new PV; Cycle:5;*)
		bEG_BoVaCoOpen_Man : BOOL; (*exhaust gas boiler valve command open*) (*OldName: new PV; Cycle:5;*)
		bEG_BoVaCoClose_Man : BOOL; (*exhaust gas boiler valve command close*) (*OldName: new PV; Cycle:5;*)
		bEG_ByVaCoOpen_Man : BOOL; (*exhaust gas bypass valve command open*) (*OldName: new PV; Cycle:5;*)
		bEG_ByVaCoClose_Man : BOOL; (*exhaust gas bypass valve command close*) (*OldName: new PV; Cycle:5;*)
		bAuxCust_Man : ARRAY[0..40]OF BOOL; (*reserve customer auxiliaries*) (*OldName: new PV; Cycle:5;*)
		bCDP_Dem_Man : BOOL; (*demand condensor pump*) (*OldName: new PV; Cycle:5;*)
		bBHV_Dem_Man : BOOL; (*demand boiler house ventilation*) (*OldName: newPv; Cycle:5;*)
		bHWF_Dem_Man : BOOL; (*demand heating circuit flap*) (*OldName:newPv; Cycle:5;*)
		bChC_Heating_Man : BOOL; (*charge cooler pre heating*) (*OldName:newPv; Cycle:5;*)
		bCO2_DemCodinox_Man : BOOL; (*CO2 demand CODINOX*) (*OldName:newPv; Cycle:5;*)
		bECWP_PreH_COf : BOOL; (*engine cooling water pump preheating demand off*) (*OldName: new PV; Cycle: 5;*)
		bECW_PreH_COf : BOOL; (*engine cooling water preheating demand off*) (*OldName: new PV; Cycle: 5;*)
		bInAirER_Lou2DemOpen : BOOL; (*demand open air inlet louver 2*) (*OldName: new PV; Cycle:5;*)
		bInAirER_Lou1DemOpen : BOOL; (*demand open air inlet louver 1*) (*OldName: new PV; Cycle:5;*)
		bOutAirER_LouDemOpen : BOOL; (*open air outlet louver *) (*OldName: new PV; Cycle:5;*)
		bInAirER_Fan1DemOn : BOOL; (*demand air inlet ventilator 1*) (*OldName: new PV; Cycle:5;*)
		bInAirER_Fan2DemOn : BOOL; (*demand air inlet ventilator 2*) (*OldName: new PV; Cycle:5;*)
		bER_OutlV_FC_Set : BOOL; (*demand engine room air outlet ventilation frequency converter setpoint*) (*OldName: new PV; Cycle:5;*)
		rER_OutlV_FC_Set : REAL; (*engine room air outlet ventilation frequency converter setpoint [%]*) (*OldName: new PV; Cycle:5;*)
		bER_FC_Set : BOOL; (*demand engine room frequency converter setpoint*) (*OldName: new PV; Cycle:5;*)
		rER_FC_Set : REAL; (*engine room frequency converter setpoint [%]*) (*OldName: new PV; Cycle:5;*)
		bEC_DemPump : BOOL; (*emergency cooler demand pump*) (*OldName: new PV; Cycle:5;*)
		bEC_DemFan : BOOL; (*emergency cooler demand fan 1 - 16*) (*OldName: new PV; Cycle:5;*)
		bChC_DemPump : BOOL; (*charge cooler demand pump*) (*OldName: new PV; Cycle:5;*)
		bChC_DemFan : BOOL; (*charge cooler demand fan 1 - 16*) (*OldName: new PV; Cycle:5;*)
		bEG_BoVaCoOpen : BOOL; (*exhaust gas boiler valve command open*) (*OldName: new PV; Cycle:5;*)
		bEG_BoVaCoClose : BOOL; (*exhaust gas boiler valve command close*) (*OldName: new PV; Cycle:5;*)
		bEG_ByVaCoOpen : BOOL; (*exhaust gas bypass valve command open*) (*OldName: new PV; Cycle:5;*)
		bEG_ByVaCoClose : BOOL; (*exhaust gas bypass valve command close*) (*OldName: new PV; Cycle:5;*)
		bAuxCust : ARRAY[0..70]OF BOOL; (*reserve customer auxiliaries*) (*OldName: new PV; Cycle:5;*)
		bCDP_Dem : BOOL; (*demand condensor pump*) (*OldName: new PV; Cycle:5;*)
		bBHV_Dem : BOOL; (*demand boiler house ventilation*) (*OldName: newPv; Cycle:5;*)
		bHWF_Dem : BOOL; (*demand heating circuit flap*) (*OldName:newPv; Cycle:5;*)
		bChC_Heating : BOOL; (*charge cooler pre heating*) (*OldName:newPv; Cycle:5;*)
		bCO2_DemCodinox : BOOL; (*CO2 demand CODINOX*) (*OldName:newPv; Cycle:5;*)
		bChC2_DemPump : BOOL; (*charge cooler 2 demand pump*) (*OldName: new PV; Cycle:5;*)
		bChC2_DemPump_Man : BOOL; (*charge cooler 2 demand pump*) (*OldName: new PV; Cycle:5;*)
		bChC2_DemFan : BOOL; (*charge cooler 2 demand fan 1 - 16*) (*OldName: new PV; Cycle:5;*)
		bChC2_DemFan_Man : BOOL; (*charge cooler 2 demand fan 1 - 16*) (*OldName: new PV; Cycle:5;*)
		bChC2_Heating : BOOL; (*charge cooler 2 pre heating*) (*OldName:newPv; Cycle:5;*)
		bChC2_Heating_Man : BOOL; (*charge cooler 2 pre heating*) (*OldName:newPv; Cycle:5;*)
		bECW_HydrPreH_COf : BOOL; (*engine cooling water hydraulic preheating demand off*) (*OldName: new PV; Cycle: 5;*)
		bECW_HydrPreH_COf_Man : BOOL; (*engine cooling water hydraulic preheating demand off*) (*OldName: new PV; Cycle: 5;*)
		bEOP_DemPump : BOOL; (*engine prelubrication pump manual demand*) (*OldName: new PV; Cycle: 5;*)
		bEOP_DemPump_Man : BOOL; (*engine prelubrication pump manual demand*) (*OldName: new PV; Cycle: 5;*)
	END_STRUCT;
END_TYPE
