(*******************************************************************************
DefaultCH		value set

This code is confidential and proprietary to the INNIO Company.
It may not be used in any form, or reproduced in any manner,
without the express written permission of the INNIO Company.
Copyright, INNIO Company, 2019
 
Customized modifications: -
------------------------
 
History:
-------
V03.99.00.00	11.09.2012	Tinello		new

Instructions for use:
--------------------
- Default TRUE setting for not existing Di's

Outstandings:
------------

*******************************************************************************)
PROGRAM _CYCLIC

END_PROGRAM
