
TYPE
	PROGRAMMER_INFO : 	STRUCT 
		DO_NOT_SORT_PARA : STRING[40] := 'DO NOT CHANGE PARAMETER SORTING!'; (*DO NOT CHANGE PARAMETER SORTING!*) (*ADD NEW PARAMETER ONLY AT THE END OF THE Para STRUCTURE. DO NOT DELETE existing Para items.*)
	END_STRUCT;
	Para_GC_Struct : 	STRUCT 
		rP_Act_LimLo : REAL; (*PARA [11509]: actual power low limit *) (*Oldname: GW_MS_PIST;Cycle:5*)
		bCtrGenPF_Active : BOOL; (*PARA [11485]: visibility generator controller*) (*Oldname:new pv;Cycle:5*)
		bGlowIgnPrevActive : BOOL; (*PARA [12089]: glow ignition prevention active*) (*Oldname:sel_GlowIgnPrevent;Cycle:5*)
		bPF_CosPCtr_Diff_Ena : BOOL; (*PARA [11486]: enable differential protection monitoring*) (*Oldname:DEAKT_DIFF;Cycle:5*)
		bPF_CosPCtr_Ena : BOOL; (*PARA [11487]: enable power factor controller on visualization*) (*Oldname:bQPF_XT;Cycle:5*)
		bPF_CosPCtr_F_Ena : BOOL; (*PARA [11488]: enable power reduction by generator frequency*) (*Oldname:bPowRed_GenFrq;Cycle:5*)
		bPF_CosPCtr_U_Ena : BOOL; (*PARA [11489]: enable power reduction by generator voltage*) (*Oldname:bPowRed_GenSpg;Cycle:5*)
		bT_Gen_Bear_A_Ena : BOOL; (*PARA [11490]: bearing A temperature monitoring enabled*) (*Oldname:lag1_a;Cycle:5*)
		bT_Gen_Bear_B_Ena : BOOL; (*PARA [11491]: bearing B temperature monitoring enabled*) (*Oldname:lag2_a;Cycle:5*)
		bT_Gen_Wind_Ena : BOOL; (*PARA [11492]: winding temperature monitoring enabled*) (*Oldname:wick_a;Cycle:5*)
		bU_Gen_Contr_Sel : BOOL; (*From settings task -> select fail safe DI_GENREG_F *) (*Oldname:sel_fs_DI_GENREG_F;Cycle:5*)
		bU_Gen_Exc_Ena : BOOL; (*PARA [11494]: excitation voltage monitoring enabled*) (*Oldname:u_erreg_a;Cycle:5*)
		bU_Gen_Mns_Match : BOOL; (*PARA [11495]: voltage matching active*) (*Oldname:vmatch_a;Cycle:5*)
		bU_Gen_P_Ena : BOOL; (*PARA [11496]: power related voltage adjustment active*) (*Oldname:u_adj_power_a;Cycle:5*)
		bU_Gen_spd_match : BOOL; (*PARA [11497]: speed related voltage adjustment active*) (*Oldname:u_adj_speed_a;Cycle:5*)
		iEng_Motortype : INT; (*Para: Motor type*) (*Oldname:iMotortyp;Cycle:5;*)
		rAng_CosPCtr_Lim : REAL; (*PARA [11501]: limit polar wheel angle for power factor controller*) (*Oldname:rDeltaPara;Cycle:5*)
		rAng_CosPCtr_Min : REAL; (*PARA [11502]: Minimum polar wheel angle for trip (LOSS OF EXCITATION)*) (*Oldname:rDelta_TripPara;Cycle:5*)
		rF_Gen_Match_Max : REAL; (*PARA [11503]: Generator frequency match maximum %Fnom*) (*Oldname:newPV;Cycle:5*)
		rF_Gen_Match_Min : REAL; (*PARA [11504]: Generator frequency match minmum %Fnom*) (*Oldname:newPV;Cycle:5*)
		rF_Nom : ARRAY[0..2]OF REAL; (*PARA [11736], [11737]: nominal generator frequency*) (*Oldname:usFreqNenn;Cycle:5*)
		rGen_CosPhi_Ena : REAL; (*PARA [11505]: Limit cos phi switching*) (*Oldname:GW_COS - calculated;Cycle:5*)
		rGen_CosPhi_Ena_Hy : REAL; (*PARA [11506]: Hysteresis cos phi switching*) (*Oldname:HY_COS;Cycle:5*)
		rN_EngNom : REAL; (*PARA [12128]: nominal speed*) (*Oldname:n_nenn;Cycle:5*)
		rN_EngStart_HyHi : REAL; (*PARA [11295]: speed engine start limit high hysteresis*) (*Oldname:HY_DREHZ;Cycle:5;*)
		rN_EngStart_HyHiHi : REAL; (*PARA [11507]: speed engine start limit high high hysteresis*) (*Oldname:HY_HDREHZ;Cycle:5*)
		rN_EngStart_LimHi : REAL; (*PARA [11296]: speed engine start limit high*) (*Oldname:GW_DREHZ;Cycle:5*)
		rN_EngStart_LimHiHi : REAL; (*PARA [11508]: speed engine start limit high high*) (*Oldname:GW_HDREHZ;Cycle:5*)
		rP_CosPCtr_F_Hi : REAL; (*PARA [11510]: minimum power at generator frequency high*) (*Oldname:ssPowRed_GenFrqHigh;Cycle:5*)
		rP_CosPCtr_F_Lo : REAL; (*PARA [11511]: minimum power at generator frequency low*) (*Oldname:ssPowRed_GenFrqLow;Cycle:5*)
		rP_CosPCtr_T_Hi : REAL; (*PARA [11512]: start power reduction winding temperature high*) (*Oldname:ssPowRed_GenWickHi;Cycle:5*)
		rP_CosPCtr_U_Hi : REAL; (*PARA [11513]: minimum power at generator voltage high*) (*Oldname:ssPowRed_GenVoltHigh;Cycle:5*)
		rP_CosPCtr_U_Lo : REAL; (*PARA [11514]: minimum power at generator voltage low*) (*Oldname:ssPowRed_GenVoltLow;Cycle:5*)
		rP_Reverse : REAL; (*PARA [11515]: reverse power limit*) (*Oldname:GW_RLSG;Cycle:5*)
		rP_Reverse_Hy : REAL; (*PARA [11516]: reverse power limit hysteresis*) (*Oldname:HY_RLSG;Cycle:5*)
		tiPF_CosPCtr_del : TIME; (*PARA [11620]: delay of reactive power monitoring*) (*Oldname:usReactDel[1] * 10;Cycle:5*)
		rPF_CosPCtr_F_Hi_End : REAL; (*PARA [11521]: power reduction ends at this generator (high) frequency value*) (*Oldname:ssGenFrqHighStop;Cycle:5*)
		rPF_CosPCtr_F_Hi_Start : REAL; (*PARA [11522]: power reduction starts at this generator (high) frequency value*) (*Oldname:ssGenFrqHighStart;Cycle:5*)
		rPF_CosPCtr_F_Lo_End : REAL; (*PARA [11523]: power reduction ends at this generator (low) frequency value*) (*Oldname:ssGenFrqLowStop;Cycle:5*)
		rPF_CosPCtr_F_Lo_Start : REAL; (*PARA [11524]: power reduction starts at this generator (low) frequency value*) (*Oldname:ssGenFrqLowStart;Cycle:5*)
		rPF_CosPCtr_F_ret : REAL; (*PARA [11525]: frequency value for retourning to normal power*) (*Oldname:ssFrqReturn;Cycle:5*)
		rPF_CosPCtr_h : ARRAY[0..5]OF REAL; (*PARA [11527], [11528], [11529], [11530], [11531]: map for time dependent power factor control*) (*Oldname:usPF_time_h;Cycle:5*)
		rPF_CosPCtr_m : ARRAY[0..5]OF REAL; (*PARA [11533], [11534], [11535], [11536], [11537]: map for time dependent power factor control*) (*Oldname:usPF_time_m;Cycle:5*)
		rPF_CosPCtr_T_max : REAL; (*PARA [11546]: maximum temp. For activation power factor reductions*) (*Oldname:twred_max;Cycle:5*)
		rPF_CosPCtr_T_red : REAL; (*PARA [11547]: gradient for power factor reduction by winding temperature high*) (*Oldname:twgradient;Cycle:5*)
		rPF_CosPCtr_T_wind : REAL; (*PARA [11548]: power reduction factor by generator winding temperature*) (*Oldname:wick_dp;Cycle:5*)
		rPF_CosPCtr_Tme_Set : ARRAY[0..5]OF REAL; (*PARA [11550], [11551], [11552], [11553], [11554]: power factor table for parameter entry time*) (*Oldname:rPF_Zeit;Cycle:5*)
		rPF_CosPCtr_U_Hi_End : REAL; (*PARA [11555]: power reduction ends at this generator (high) voltage value*) (*Oldname:ssGenVoltHighStop;Cycle:5*)
		rPF_CosPCtr_U_Hi_Start : REAL; (*PARA [11556]: power reduction starts at this generator (high) voltage value*) (*Oldname:ssGenVoltHighStart;Cycle:5*)
		rPF_CosPCtr_U_Lo_End : REAL; (*PARA [11557]: power reduction ends at this generator (low) voltage value*) (*Oldname:ssGenVoltLowStop;Cycle:5*)
		rPF_CosPCtr_U_Lo_Start : REAL; (*PARA [11558]: power reduction starts at this generator (low) voltage value*) (*Oldname:ssGenVoltLowStart;Cycle:5*)
		rS_Nom : REAL; (*PARA [11571]: Generator apparent nominal power*) (*Oldname:rS_CosP Ctr_act ;Cycle:5*)
		rT_Gen_Bear_Lim_A : REAL; (*PARA [11572]: generator bearing A temperature maximum, Warning*) (*Oldname:GW_LAGW1;Cycle:5*)
		rT_Gen_Bear_Lim_B : REAL; (*PARA [11573]: generator bearing B temperature maximum, Warning*) (*Oldname:GW_LAGW2;Cycle:5*)
		rT_Gen_Bear_Max_A : REAL; (*PARA [11574]: generator bearing A temperature maximum, Trip*) (*Oldname:GW_LAGA1;Cycle:5*)
		rT_Gen_Bear_Max_B : REAL; (*PARA [11575]: generator bearing B temperature maximum, Trip*) (*Oldname:GW_LAGA2;Cycle:5*)
		rT_Gen_Bear_Max_Hy_A : REAL; (*PARA [11576]: hysteresis generator bearing A temperature maximum*) (*Oldname:HY_LAG1;Cycle:5*)
		rT_Gen_Bear_Max_Hy_B : REAL; (*PARA [11577]: hysteresis generator bearing B temperature maximum*) (*Oldname:HY_LAG2;Cycle:5*)
		rT_Gen_Wind_Lim : REAL; (*PARA [11578]: Winding temperature maximum, Warning*) (*Oldname:GW_GWTW;Cycle:5*)
		rT_Gen_Wind_Lim_Hy : REAL; (*PARA [11579]: hysteresis generator winding temperature maximum*) (*Oldname:HY_GWTW;Cycle:5*)
		rT_Gen_Wind_Lim_Hy2 : REAL; (*PARA [11580]: hysteresis generator winding temperature maximum*) (*Oldname:HY_GWW;Cycle:5*)
		rT_Gen_Wind_Lim_L1 : REAL; (*PARA [11581]: generator winding temperature maximum phase 1, Warning*) (*Oldname:GW_GWW1;Cycle:5*)
		rT_Gen_Wind_Lim_L2 : REAL; (*PARA [11582]: generator winding temperature maximum phase 2, Warning*) (*Oldname:GW_GWW2;Cycle:5*)
		rT_Gen_Wind_Lim_L3 : REAL; (*PARA [11583]: generator winding temperature maximum phase 3, Warning*) (*Oldname:GW_GWW3;Cycle:5*)
		rT_Gen_Wind_Max : REAL; (*PARA [11584]: Winding temperature maximum, Trip*) (*Oldname:GW_GWTA;Cycle:5*)
		rT_Gen_Wind_Max_Hy : REAL; (*PARA [11585]: hysteresis generator winding temperature maximum*) (*Oldname:HY_GWA;Cycle:5*)
		rT_Gen_Wind_Max_Hy2 : REAL; (*PARA [11586]: hysteresis generator winding temperature maximum*) (*Oldname:HY_GWTA;Cycle:5*)
		rT_Gen_Wind_Max_L1 : REAL; (*PARA [11587]: generator winding temperature maximum phase 1, Trip*) (*Oldname:GW_GWA1;Cycle:5*)
		rT_Gen_Wind_Max_L2 : REAL; (*PARA [11588]: generator winding temperature maximum phase 2, Trip*) (*Oldname:GW_GWA2;Cycle:5*)
		rT_Gen_Wind_Max_L3 : REAL; (*PARA [11589]: generator winding temperature maximum phase 3, Trip*) (*Oldname:GW_GWA3;Cycle:5*)
		rU_Gen_Diff_Idle : REAL; (*PARA [11590]: voltage offset at idle operation %Un*) (*Oldname:U_offset_0PN;Cycle:5*)
		rU_Gen_Diff_Pn : REAL; (*PARA [11591]: voltage offset at full load %Un*) (*Oldname:U_offset_100PN;Cycle:5*)
		rU_Gen_ExcHi : REAL; (*PARA [11592]: excitation voltage high*) (*Oldname:GW_ERGW2;Cycle:5*)
		rU_Gen_ExcHyHi : REAL; (*PARA [11593]: excitation voltage high hysteresis*) (*Oldname:HY_ERGW2;Cycle:5*)
		rU_Gen_ExcHyLo : REAL; (*PARA [11594]: excitation voltage low hysteresis*) (*Oldname:HY_ERGW1;Cycle:5*)
		rU_Gen_ExcLo : REAL; (*PARA [11595]: excitation voltage low*) (*Oldname:GW_ERGW1;Cycle:5*)
		rU_Gen_match_delta : REAL; (*PARA [11596]: voltage matching per pulse %Unom/s*) (*Oldname:delta_u;Cycle:5*)
		rU_Gen_Nom : ARRAY[0..2]OF REAL; (*PARA [11597], [11598]: nominal voltage generator [70V..65kV]*) (*Oldname:usUNennGen;Cycle:5*)
		rU_Gen_Rmp_Dec : REAL; (*PARA [11600]: Maximum negative voltage adjustment ramp in %Unom/s*) (*Oldname:U_adj_ramp;Cycle:5*)
		rU_Gen_Rmp_Inc : REAL; (*PARA [11601]: Maximum positive voltage adjustment ramp in %Unom/s*) (*Oldname:U_adj_ramp;Cycle:5*)
		rU_adj_max_up : REAL; (*PARA [12438]: Maximum positive voltage adjustment in %Unom*) (*Oldname: U_adj_max_up; Cycle: 5*)
		rU_adj_max_down : REAL; (*PARA [12439]: Maximum negative voltage adjustment in %Unom*) (*Oldname: U_adj_max_down; Cycle: 5*)
		rU_SyncNom : ARRAY[0..2]OF REAL; (*PARA [11859], [11860]: nominal voltage sync1 & sync2 [70V..65kV]*) (*Oldname:usUNennSync;Cycle:5*)
		rxd_CosPCtr : REAL; (*PARA [11602]: Synchronous reactance xd*) (*Oldname:r_xd;Cycle:5*)
		tCtrGenPF : _tGeACtrPara; (*Para controller Generator*) (*Oldname:new pv;Cycle:5*)
		ti_Gen_VoltReg_Fail : TIME; (*PARA [11616]: timer generator voltage regulator failure (Standard =T#0s ; Basler = T#60s)*) (*Oldname:new pv; Cycle:5*)
		tiP_Gen_Reverse : TIME; (*PARA [11617]: timer (10 sec) for delay after gen. Circuit breaker closed*) (*Oldname:TW_AT24;Cycle:5*)
		tiP_Gen_Reverse2 : TIME; (*PARA [11618]: timer (10 sec) for delay of generator reverse power*) (*Oldname:TW_T28;Cycle:5*)
		tiP_Reverse_Mon_Ena : TIME; (*PARA [11619]: timer (10 sec) for activation monitoring reverse power *) (*Oldname:TW_RLSG_W;Cycle:5*)
		bU_adj_gcb_ext_hilo_a : BOOL; (*PARA [12442]: voltage adjust for GCB sync. external Hi/Low enable*) (*Oldname:u_adj_gcb_ext_hilo_a;Cycle:5;*)
		bU_adj_gcb_mmd_calc_a : BOOL; (*PARA [12440]: voltage adjust for GCB sync. MMD calc enable*) (*Oldname:u_adj_gcb_mmd_calc_a;Cycle:5;*)
		bU_adj_mcb_ext_hilo_a : BOOL; (*PARA [12443]: voltage adjust for MCB sync. external Hi/Low enable*) (*Oldname:u_adj_mcb_ext_hilo_a;Cycle:5;*)
		bU_adj_mcb_mmd_calc_a : BOOL; (*PARA [12441]: voltage adjust for MCB sync. MMD calc enable*) (*Oldname:u_adj_mcb_mmd_calc_a;Cycle:5;*)
		rTi_Q_MinDel : ARRAY[0..2]OF REAL; (*PARA [11835], [11836]: delay reactive power monitoring *) (*OldName:usReactDel; Cycle: *)
		bSyActive : BOOL; (*PARA [12195]: synchronization functions active *) (*OldName:bSynch; Cycle:5;*)
		bOilSkid_Exist : BOOL; (*PARA [12528]: OilSkid active	*) (*Oldname:new pv; Cycle:5*)
		bFlow_OilSkid_DE_Exist : BOOL; (*PARA [12543]: Oil flow to DE storage active	*) (*Oldname:new pv; Cycle:5*)
		bFlow_OilSkid_NDE_Exist : BOOL; (*PARA [12548]: Oil flow to NDE storage activ	*) (*Oldname:new pv; Cycle:5*)
		bLev_OilSkid_Tank_Exist : BOOL; (*PARA [12529]: Oil tank level active	*) (*Oldname:new pv; Cycle:5*)
		bPr_OilSkid_HP_DE_Exist : BOOL; (*PARA [12557]: Oil pressure in high pressure circle to DE Storage active	*) (*Oldname:new pv; Cycle:5*)
		bPr_OilSkid_HP_NDE_Exist : BOOL; (*PARA [12558]: Oil pressure in high pressure circle to NDE Storage active	*) (*Oldname:new pv; Cycle:5*)
		bT_OilSkid_Supply_Exist : BOOL; (*PARA [12538]: Oil pre-temperaure active (�lvorlauftemperatur) 	*) (*Oldname:new pv; Cycle:5*)
		bT_OilSkid_Tank_Exist : BOOL; (*PARA [12534]: Oil tank temperature activ	*) (*Oldname:new pv; Cycle:5*)
		rFlow_OilSkid_DE_Hi : REAL; (*PARA [12547]: Oil flow to DE storage Maximum - Warning [l/min]*) (*Oldname:new pv; Cycle:5*)
		rFlow_OilSkid_DE_Lo : REAL; (*PARA [12546]: Oil flow to DE storage Minimum - Warning [l/min]*) (*Oldname:new pv; Cycle:5*)
		rFlow_OilSkid_NDE_Hi : REAL; (*PARA [12552]: Oil flow to NDE storage Maximum- Warning [l/min]*) (*Oldname:new pv; Cycle:5*)
		rFlow_OilSkid_NDE_Lo : REAL; (*PARA [12551]: Oil flow to NDE storage Minimum - Warning [l/min]*) (*Oldname:new pv; Cycle:5*)
		rLev_OilSkid_Tank_Lo : REAL; (*PARA [12532]: Oil tank level  Minimum - Warning [%]*) (*Oldname:new pv; Cycle:5*)
		rLev_OilSkid_Tank_LoLo : REAL; (*PARA [12533]: Oil tank level Minimum - Error [%]*) (*Oldname:new pv; Cycle:5*)
		rPr_OilSkid_HP_Lo : REAL; (*PARA [12556]: Oil pressure in high pressure circle Minimum � Warning [bar]*) (*Oldname:new pv; Cycle:5*)
		rT_OilSkid_Supply_Hi : REAL; (*PARA [12542]: Oil pre-temperaure active Maximum - Warning [°C]*) (*Oldname:new pv; Cycle:5*)
		rT_OilSkid_Supply_Lo : REAL; (*PARA [12541]: Oil pre-temperaure active Minimum - Warning [°C]*) (*Oldname:new pv; Cycle:5*)
		rT_OilSkid_Tank_Set : REAL; (*PARA [12537]: Oil tank set temperature [°C]*) (*Oldname:new pv; Cycle:5*)
		tiOilSkid_PumpHP_Run : TIME; (*PARA [12553]: Time untill the high pressure pump switched off [s]*) (*Oldname:new pv; Cycle:5*)
		bF_GenBear_DE1_Active : BOOL; (*PARA [12706]: vibration generator bearing drive end 1 measuring signal activ*) (*Oldname:v_GenBear_a;Cycle:5;*)
		bF_GenBear_DE2_Active : BOOL; (*PARA [12707]: vibration generator bearing drive end 2 measuring signal activ*) (*Oldname:v_GenBear_a;Cycle:5;*)
		bF_GenBear_NDE1_Active : BOOL; (*PARA [12708]: vibration generator bearing non drive end 1 measuring signal activ*) (*Oldname:v_GenBear_a;Cycle:5;*)
		bF_GenBear_NDE2_Active : BOOL; (*PARA [12709]: vibration generator bearing non drive end 2 measuring signal activ*) (*Oldname:v_GenBear_a;Cycle:5;*)
		rF_GenBear_Hi : REAL; (*PARA [12712]: vibration generator bearing limit high*) (*Oldname:GW_v_GenBear_hi2;Cycle:5;*)
		tiF_GenBear_Hi : TIME; (*PARA [12713]: delay bearing displacement high*) (*Oldname:TW_v_GenBear_hi2;Cycle:5*)
		rF_GenBear_HiHi : REAL; (*PARA [12714]: vibration generator bearing limit high high*) (*Oldname:GW_v_GenBear_hi2;Cycle:5;*)
		tiF_GenBear_HiHi : TIME; (*PARA [12717]: delay bearing displacement high high*) (*Oldname:TW_v_GenBear_hi2;Cycle:5*)
		bT_GenAirIn_Active : BOOL; (*PARA [12715]: generator air inlet temperature measuring signal activ*) (*Oldname:t_GenAirIn_a;Cycle:5;*)
		bT_GenAirOut_Active : BOOL; (*PARA [12716]: generator air outlet temperature measuring signal activ*) (*Oldname:t_GenAirOut_a;Cycle:5;*)
		bT_GenAirIn2_Active : BOOL; (*PARA [13695]: generator air inlet temperature 2 measuring signal activ*) (*Oldname:newPv;Cycle:5;*)
		rT_Pred_GenAirIn_Start : REAL; (*PARA [13696]: generator air inlet temperature start power reduction*) (*Oldname:newPv;Cycle:5;*)
		rT_Pred_GenAirIn_Rate : REAL; (*PARA [13697]: generator air inlet temperature rate power reduction*) (*Oldname:newPv;Cycle:5;*)
		rQ_UnderExc_Lim : REAL; (*PARA [13693]: reactive power limit underexcitated [%]*) (*Oldname:newPv;Cycle:5;*)
		rQ_OverExc_Lim : REAL; (*PARA [13694]: reactive power limit overexcitated [%]*) (*Oldname:newPv;Cycle:5;*)
		bCtr_Q : BOOL; (*PARA [14107]: visibility generator Q controller*) (*Oldname:newPv;Cycle:5*)
		tCtr_Q : _tGeACtrPara; (*Para generator Q controller*) (*Oldname:newPv;Cycle:5*)
		iQ_GrC_PointCtrl : INT; (*PARA [13992]: Q controller - selection point of control*) (*Oldname:newPv;Cycle:5;*)
		rU_GrC_SetEU_Nom : REAL; (*PARA [11696]: [V] Nominal voltage for voltage setpoint *) (* OldName: ulUnom_evu; Cycle: 5 *)
		iQ_GrC_CtrlFun : USINT; (*PARA [13991]: select Q/PF control function: 0:custom 1:PFset 2:PF(P) 3:PF(U) 4:Q(U) 5:Q(P) 6:Qset 7:Uset 8:time table*)
		rV_Over2 : ARRAY[0..2]OF REAL; (*Para: over voltage 2[V]*) (*Oldname:newPv;Cycle:5;*)
		rTi_V_Over2 : ARRAY[0..2]OF REAL; (*Para: over voltage 2 delay*) (*Oldname:newPv;Cycle:5;*)
		bQ_UnderExc_Ena : BOOL; (*PARA [14284]: Reactive power reduction by voltage enabled*)
		rQ_UnderExc_Start : REAL; (*PARA [14285]: Start value low voltage (Umin1)*)
		rQ_UnderExc_Stop : REAL; (*PARA [14286]: Stop value low voltage (Umin2)*)
		rQ_UnderExc_Lim2 : REAL; (*PARA [14287]: Reduced reactive power low voltage(Qlim2)*)
		iSource_U_OffsSet : INT; (*PARA [14298]: Voltage offset set point in island mode: 0= no setpoint, 1= Droop, 2= External *)
		rU_StCtr_Grad : REAL; (*PARA [14299]: Gradient for the voltage droop curve in island mode [%Unom]*)
		rEta_Gen_PF1 : REAL; (*PARA [14343]: Generator Efficiency at power factor 1.0*)
		rEta_Gen_PF08 : REAL; (*PARA [14344]: Generator Efficiency at power factor 0.8 overexcited*)
		iU_Isl_SetX : INT; (*PARA [14705]: choice of voltage setpoint: 0=not used, 1=Internal Setpoint, 2=Voltage backup set point; 3=External Bus, 4=Customized, 5=External AI*)
		rU_Isl_SetInt : REAL; (*PARA [14706]: voltage internal setpoint*)
		rU_SetExtAI_SetI1 : REAL; (*PARA [14707]: voltage external setpoint AI, current point 1*)
		rU_SetExtAI_SetI2 : REAL; (*PARA [14708]: voltage external setpoint AI, current point 2*)
		rU_SetExtAI_SetP1 : REAL; (*PARA [14709]: voltage external setpoint AI, voltage point 1*)
		rU_SetExtAI_SetP2 : REAL; (*PARA [14710]: voltage external setpoint AI, voltage point 2*)
		rU_Isl_SetAct_BU : REAL; (*PARA [14711]: voltage external setpoint, backup value*)
		bRelFreeze_Uset_Isl : BOOL; (*PARA [14712]: voltage external setpoint, interruption characteristic: 0=backup value, 1=last valid value*)
		iQ_Droop_SetX : INT; (*PARA [14713]: choice of reactive power setpoint: 0=not used, 1=Internal Setpoint, 2=Voltage backup set point; 3=External Bus, 4=Customized, 5=External AI*)
		rQ_Droop_SetInt : REAL; (*PARA [14714]: reactive power internal setpoint, -x[underexcited]/+x[overexcited]*)
		rQ_Droop_Set_SetI1 : REAL; (*PARA [14715]: reactive power external setpoint AI, current point 1*)
		rQ_Droop_Set_SetI2 : REAL; (*PARA [14716]: reactive power external setpoint AI, current point 2*)
		rQ_Droop_Set_SetP1 : REAL; (*PARA [14717]: reactive power external setpoint AI, reactive power point 1, -x[underexcited]/+x[overexcited]*)
		rQ_Droop_Set_SetP2 : REAL; (*PARA [14718]: reactive power external setpoint AI, reactive power point 2, -x[underexcited]/+x[overexcited]*)
		rQ_Droop_SetAct_BU : REAL; (*PARA [14719]: reactive power external setpoint, backup value, -x[underexcited]/+x[overexcited]*)
		bRelFreeze_Qset_Droop : BOOL; (*PARA [14720]: reactive power external setpoint, interruption characteristic: 0=backup value, 1=last valid value*)
		bComm1_Ena : BOOL; (*PARA [10165]: link 1 release data receive enabled*) (*OldName:Kopl1Empf; Cycle: 5;*)
		bComm2_Ena : BOOL; (*PARA [10166]: link 2 release data receive enabled*) (*OldName:Kopl2Empf; Cycle: 5;*)
		bMMDGroundFaultMonAct : BOOL;(*PARA [14943]: Earth fault monitoring via MMU signals activated*)
		tTi_MMDGroundFaultWarning : TIME; (*PARA [14944]: delay MMD earth fault warning*)
		tTi_MMDGroundFaultTrip : TIME; (*PARA [14945]: delay MMD earth fault trip*)
		bCAsym_Ena : BOOL; (*PARA [15070]: Enable unbalance current monitoring*)
	END_STRUCT;
END_TYPE
