
TYPE
	MM2VIS_Struct : 	STRUCT 
		tCtrGenPF_Out : _tGeACtrOut; (* Controller to visulization out structure *) (*OldName:new pv;Cycle:5*)
		tCtr_Q_Out : _tGeACtrOut; (* Controller to visulization out structure *) (*OldName:new pv;Cycle:5*)
		bP_CosPCtr_Red_F_Hi : BOOL; (* power reduction by generator frequency high active *) (*OldName:bPowRedGenFrqH;Cycle:5*)
		bP_CosPCtr_Red_F_Lo : BOOL; (* power reduction by generator frequency low active *) (*OldName:bPowRedGenFrqL;Cycle:5*)
		bP_CosPCtr_Red_U_Hi : BOOL; (* power reduction by generator voltage high active *) (*OldName:bPowRedGenSpgH;Cycle:5*)
		bP_CosPCtr_Red_U_Lo : BOOL; (* power reduction by generator voltage low active *) (*OldName:bPowRedGenSpgL;Cycle:5*)
		bPF_Ctrl_Ena : BOOL; (* plant controller No. 13 enabled *) (*OldName:bPlantCtr13;Cycle:5*)
		rAng_CosPCtr_LimCalc : REAL; (* calculated limit polar wheel angle for power factor controller *) (*OldName:rQgLimit;Cycle:5*)
		rAng_CosPCtr_LimCalcVis : REAL; (*  Q- limit for visualization  *) (*OldName:ssQLimVis;Cycle:5*)
		rAng_CosPCtr_MinCalc : REAL; (* calculated minimum polar wheel angle for trip (LOSS OF EXCITATION) *) (*OldName:rQgErregerausfall;Cycle:5*)
		rAng_CosPCtr_MinCalcVis : REAL; (*  Q- trip limit for visualization  *) (*OldName:ssQTripVis;Cycle:5*)
		rP_Red_CosPCtr_F : REAL; (* power reduction by generator frequency *) (*OldName:ssPowerRedGenFrq;Cycle:5*)
		rP_Red_CosPCtr_T : REAL; (* power reduction by generator winding temperature *) (*OldName:ssPowerRedGenTemp;Cycle:5*)
		rP_Red_CosPCtr_U : REAL; (* power reduction by generator voltage *) (*OldName:ssPowerRedGenSpg;Cycle:5*)
		rP_Gen_ppt : REAL; (* nominal power in parts per thousand *) (*OldName:PN_PROM;Cycle:5*)
		rPF_CosPCtr_LimCalc1 : REAL; (* calculated reactive power trip limit of power 0 (zero) *) (*OldName:rQgTrip0;Cycle:5*)
		rPF_CosPCtr_LimCalc2 : REAL; (* calculated reactive power trip limit of nominal power 0 (PN_GASART) *) (*OldName:rQgTripN;Cycle:5*)
		rPF_CosPCtr_MinCalc1 : REAL; (* calculated reactive power limit of power 0 (zero) *) (*OldName:rQgLimit0;Cycle:5*)
		rPF_CosPCtr_MinCalc2 : REAL; (* calculated reactive power limit of nominal power 0 (PN_GASART) *) (*OldName:rQgLimitN;Cycle:5*)
		rPF_CosPCtr_Set_Ctr13 : REAL; (* set point value for plant controller *) (*OldName:ssContr_PF_SOLL;Cycle:5*)
		rPF_CosPCtr_Set_Vis : REAL; (* enable power factor input in visualization (picture 88) *) (*OldName:usPF_input_vis;Cycle:5*)
		rPF_CosPCtr_VisLine1 : REAL; (* value for visualization *) (*OldName:ucVisLine1_P14;Cycle:5*)
		rPF_GenCtr_Act : REAL; (* power factor generator controller actual value  *) (*OldName:ssContr_IST;Cycle:5*)
		rPF_GenCtr_Set : REAL; (* power factor generator controller set point  *) (*OldName:ssContr_SOLL;Cycle:5*)
		rQ_CosPCtr_Set : REAL; (* set point of reactive power for PF- controller on XT *) (*OldName:ssQSoll;Cycle:5*)
		rT_Gen_Bear_A_Act : REAL; (*Temperature generator bearing A*) (*OldName:ANA.LAG1;Cycle:5*)
		rT_Gen_Bear_B_Act : REAL; (*Temperature generator bearing B*) (*OldName:ANA.LAG2;Cycle:5*)
		rT_Gen_Wind_Act_L1 : REAL; (* generator winding temperature signal, winding phase 1 *) (*OldName:ANA.WICK1;Cycle:5*)
		rT_Gen_Wind_Act_L2 : REAL; (* generator winding temperature signal, winding phase 2 *) (*OldName:ANA.WICK2;Cycle:5*)
		rT_Gen_Wind_Act : REAL; (*generator winding temperature signal*) (*OldName:ANA.WICK;Cycle:;*)
		rU_Gen_Exc : REAL; (*Generator excitation voltage*) (*OldName:ANA.ERREG;Cycle:5;*)
		rT_Gen_Wind_Act_L3 : REAL; (* generator winding temperature signal, winding phase 3 *) (*OldName:ANA.WICK3;Cycle:5*)
		bOilSkid_Fan_Dem : BOOL; (*OilSkid - demand of fan (TRUE = on)*) (*OldName:newPv; Cycle:5;*)
		bOilSkid_Heater_Dem : BOOL; (*OilSkid - demand of heater (TRUE = on)*) (*OldName:newPv; Cycle:5;*)
		bOilSkid_PumpC_Dem : BOOL; (*OilSkid - demand of circulation pump (TRUE = on)*) (*OldName:newPv; Cycle:5;*)
		bOilSkid_PumpLP_Dem : BOOL; (*OilSkid - demand of low pressure pump (TRUE = on)*) (*OldName:newPv; Cycle:5;*)
		bOilSkid_PumpHP_Dem : BOOL; (*OilSkid - demand of high pressure pump (TRUE = on)*) (*OldName:newPv; Cycle:5;*)
		rPr_OilSkid_HP_DE : REAL; (*OilSkid - oil pressure in high pressure circuit to DE bearing [bar]*) (*OldName:newPv; Cycle:5;*)
		rPr_OilSkid_HP_NDE : REAL; (*OilSkid - oil pressure in high pressure circuit to NDE bearing [bar]*) (*OldName:newPv; Cycle:5;*)
		rT_OilSkid_Tank : REAL; (*OilSkid - tank temperature [°C]*) (*OldName:newPv; Cycle:5;*)
		rT_OilSkid_Supply : REAL; (*OilSkid - supply temperature [°C]*) (*OldName:newPv; Cycle:5;*)
		rLev_OilSkid_Tank : REAL; (*OilSkid - tank level [%]*) (*OldName:newPv; Cycle:5;*)
		rFlow_OilSkid_DE : REAL; (*OilSkid - oil flow to DE bearing [l/min]*) (*OldName:newPv; Cycle:5;*)
		rFlow_OilSkid_NDE : REAL; (*OilSkid - oil flow to NDE bearing [l/min]*) (*OldName:newPv; Cycle:5;*)
		rF_GenBear_DE1 : REAL; (*AI vibration generator bearing drive end 1*) (*Oldname:newPv;Cycle:5;*)
		rF_GenBear_DE2 : REAL; (*AI vibration generator bearing drive end 2*) (*Oldname:newPv;Cycle:5;*)
		rF_GenBear_NDE1 : REAL; (*AI vibration generator bearing non drive end 1*) (*Oldname:newPv;Cycle:5;*)
		rF_GenBear_NDE2 : REAL; (*AI vibration generator bearing non drive end 2*) (*Oldname:newPv;Cycle:5;*)
		rGen_T_In : REAL; (*AI generator air inlet temperature*) (*Oldname:t_GenAirIn;Cycle:5;*)
		rGen_T_In2 : REAL; (*AI generator air inlet temperature 2*) (*Oldname:newPv;Cycle:5;*)
		rT_GenAirOut : REAL; (*AI generator air outlet temperature*) (*Oldname:t_GenAirOut;Cycle:5;*)
		rQ_AVR_Set_Norm : REAL; (*reactive power setpoint [%]*) (*Oldname:newPv;Cycle:5;*)
		bSel_AVR_Set : BOOL; (*Q controller enabled*) (*Oldname:newPv;Cycle:5;*)
		bQ_Lim_On : BOOL; (*Q_Set is limited, Q_Limiter is working*) (*Oldname:newPv;Cycle:5;*)
		rQS_POC : REAL; (*Q/Sn diagram Y(graph)-value for point of control(POC)*) (*Oldname:newPv;Cycle:5;*)
		rPF_POC_Act_lin : REAL; (*PF diagram Y(graph)-value for point of control(POC)*) (*Oldname:newPv;Cycle:5;*)
		bU_Gen_Inc : BOOL; (* DI voltage adjustment external (increasing)*)
		bU_Gen_Dec : BOOL; (* DI voltage adjustment external (decreasing)*)
		bMsg1036 : BOOL; (*Generator over load/short circuit, Trip *) (*OldName:M_ULKS;Cycle:5*)
		bMsg1037 : BOOL; (*Generator winding temperature maximum, Trip *) (*OldName:AN_GWTA;Cycle:5*)
		bMsg1038 : BOOL; (*Generator reverse power, Trip *) (*OldName:M_RLSG;Cycle:5*)
		bMsg1062 : BOOL; (*measuring signal failure excitation voltage *) (*OldName:MS_EREG;Cycle:5*)
		bMsg1073 : BOOL; (*MMD: overload/short circuit *) (*OldName:ALM[1073];Cycle:5*)
		bMsg1109 : BOOL; (*loss of excitation (trip) *) (*OldName:bErregerAusfall;Cycle:5*)
		bMsg1110 : BOOL; (*Generator frequency low, Trip *) (*OldName:M_GFZN;Cycle:5*)
		bMsg1111 : BOOL; (*Generator frequency high, Trip *) (*OldName:M_GFZH;Cycle:5*)
		bMsg1112 : BOOL; (*Neutral current high, Trip *) (*OldName:M_INULL;Cycle:5*)
		bMsg1113 : BOOL; (*Generator power measuring signal failure*) (*OldName:M_PIST;Cycle:5*)
		bMsg1121 : BOOL; (* generator winding temperature maximum phase 1, Trip *) (*OldName:AN_GWA1;Cycle:5*)
		bMsg1122 : BOOL; (* generator winding temperature maximum phase 2, Trip *) (*OldName:AN_GWA2;Cycle:5*)
		bMsg1123 : BOOL; (* generator winding temperature maximum phase 3, Trip *) (*OldName:AN_GWA3;Cycle:5*)
		bMsg1124 : BOOL; (* generator bearing temperature maximum bearing A, Trip *) (*OldName:AN_LAGA1;Cycle:5*)
		bMsg1125 : BOOL; (* generator bearing temperature maximum bearing B, Trip *) (*OldName:AN_LAGA2;Cycle:5*)
		bMsg1126 : BOOL; (* generator voltage low, Trip *) (*OldName:M_GUZN;Cycle:5*)
		bMsg1127 : BOOL; (* generator voltage high, Trip *) (*OldName:M_GUZH;Cycle:5*)
		bMsg1132 : BOOL; (*Differential protection, Trip*) (*OldName:M_Diff;Cycle:5*)
		bMsg1134 : BOOL; (* Earth failure, Trip *) (*OldName:M_ERDS;Cycle:5*)
		bMsg1143 : BOOL; (* Voltage negative sequence (Voltage asymmetry), Trip *) (*OldName:M_UASY;Cycle:5*)
		bMsg1144 : BOOL; (* Current negative sequnece (Current asymmetrt), Trip *) (*OldName:M_IASY;Cycle:5*)
		bMsg1154 : BOOL; (* generator winding temperature maximum phase 1, Warning *) (*OldName:AN_GWW1;Cycle:5*)
		bMsg1155 : BOOL; (* generator winding temperature maximum phase 2, Warning *) (*OldName:AN_GWW2;Cycle:5*)
		bMsg1156 : BOOL; (* generator winding temperature maximum phase 3, Warning *) (*OldName:AN_GWW3;Cycle:5*)
		bMsg1157 : BOOL; (* generator bearing temperature maximum bearing A, Warning *) (*OldName:AN_LAGW1;Cycle:5*)
		bMsg1158 : BOOL; (* generator bearing temperature maximum bearing B, Warning *) (*OldName:AN_LAGW2;Cycle:5*)
		bMsg1185 : BOOL; (* generator winding temperature maximum, Warning *) (*OldName:AN_GWTW;Cycle:5*)
		bMsg2100 : BOOL; (* Differential protection, Warning *) (*OldName:M_STDIFF;Cycle:5*)
		bMsg2105 : BOOL; (* measuring signal failure winding temperature *) (*OldName:MS_GWT;Cycle:5*)
		bMsg2106 : BOOL; (* measuring signal failure winding temperature phase 1 *) (*OldName:MS_GWT1;Cycle:5*)
		bMsg2107 : BOOL; (* measuring signal failure winding temperature phase 2 *) (*OldName:MS_GWT2;Cycle:5*)
		bMsg2108 : BOOL; (* measuring signal failure winding temperature phase 3 *) (*OldName:MS_GWT3;Cycle:5*)
		bMsg2109 : BOOL; (* measuring signal failure bearing temperature bearing A *) (*OldName:MS_LAG1;Cycle:5*)
		bMsg2110 : BOOL; (* measuring signal failure bearing temperature bearing B *) (*OldName:MS_LAG2;Cycle:5*)
		bMsg2115 : BOOL; (* Generator voltage regulator failure *) (*OldName:Not-found;Cycle:5*)
		bMsg2156 : BOOL; (* B2156 Q-RED by winding temperature limit *) (*OldName:RPSDIA[35];Cycle:5*)
		bMsg2157 : BOOL; (* B2157 Q-limit by polar wheel angle *) (*OldName:RPSDIA[36];Cycle:5*)
		bMsg2202 : BOOL; (*generator DE bearing displacement*) (*OldName:newPv;Cycle:5*)
		bMsg2203 : BOOL; (*generator NDE bearing displacement*) (*OldName:newPv;Cycle:5*)
		bMsg2204 : BOOL; (*measuring signal failure displacement sensor 1 generator DE bearing*) (*OldName:newPv;Cycle:5*)
		bMsg2205 : BOOL; (*measuring signal failure displacement sensor 2 generator DE bearing*) (*OldName:newPv;Cycle:5*)
		bMsg2206 : BOOL; (*measuring signal failure displacement sensor 1 generator NDE bearing*) (*OldName:newPv;Cycle:5*)
		bMsg2207 : BOOL; (*measuring signal failure displacement sensor 2 generator NDE bearing*) (*OldName:newPv;Cycle:5*)
		bMsg2208 : BOOL; (*A2208 Oilskid tank oil level low *) (*OldName:newPv; Cycle:5;*)
		bMsg2209 : BOOL; (*not used - Generator Lube Oil System oil outlet pressure low*) (*OldName:newPv; Cycle:5;*)
		bMsg2210 : BOOL; (*not used - Generator both Lube Oil System AC oil pumps failed*) (*OldName:newPv; Cycle:5;*)
		bMsg2211 : BOOL; (*not used - Generator Lube Oil System oil supply temperature high*) (*OldName:newPv; Cycle:5;*)
		bMsg2212 : BOOL; (*not used - Generator both Jack Oil System AC oil pumps failed*) (*OldName:newPv; Cycle:5;*)
		bMsg2213 : BOOL; (*not used - Turbo charger oil filter differential pressure high*) (*OldName:newPv; Cycle:5;*)
		bMsg2235 : BOOL; (*not used - Generator Lube Oil System/Jack Oil System not ready*) (*OldName:newPv; Cycle:5;*)
		bMsg2277 : BOOL; (*Generator voltage too low 2*) (*OldName:newpv;Cycle:5*)
		bMsg2316 : BOOL; (*generator voltage high 2 (one phase)*) (*OldName:newPv;Cycle:5*)
		bMsg2336 : BOOL; (*Generator lube oil cooling system failure*) (*OldName:newpv;Cycle:5*)
		bMsg2371 : BOOL; (*A2371 Oil skid Oil flow to DE bearing Low*)
		bMsg2372 : BOOL; (*A2372 Oil skid Oil flow to NDE bearing Low*)
		bMsg2501 : BOOL; (*Generator rotating diode failure, Warning*) (*OldName:Not-found;Cycle:5*)
		bMsg2502 : BOOL; (*generator DE bearing displacement*) (*OldName:newPv;Cycle:5*)
		bMsg2503 : BOOL; (*generator NDE bearing displacement*) (*OldName:newPv;Cycle:5*)
		bMsg2504 : BOOL; (*Generator AVR panel MCB trip*) (*OldName:ALM[2504];Cycle:5*)
		bMsg2505 : BOOL; (*W2505 Oilskid low pressure oil filter clogged*) (*OldName:newPv; Cycle:5;*)
		bMsg2506 : BOOL; (*not used - Generator Lube Oil System pump A to B*) (*OldName:newPv; Cycle:5;*)
		bMsg2507 : BOOL; (*not used - Generator Lube Oil System pump B to A*) (*OldName:newPv; Cycle:5;*)
		bMsg2508 : BOOL; (*W2508 Oilskid high pressure oil filter DE clogged*) (*OldName:newPv; Cycle:5;*)
		bMsg2555 : BOOL; (*generator air inlet temperature*) (*OldName:newPv;Cycle:5*)
		bMsg2556 : BOOL; (*generator air outlet temperature*) (*OldName:newPv;Cycle:5*)
		bMsg2573 : BOOL; (* Overvoltage protection generator failure *) (*OldName:Not-found;Cycle:5*)
		bMsg2631 : BOOL; (*measuring signal failure displacement sensor 1 generator DE bearing*) (*OldName:newPv;Cycle:5*)
		bMsg2632 : BOOL; (*measuring signal failure displacement sensor 2 generator DE bearing*) (*OldName:newPv;Cycle:5*)
		bMsg2633 : BOOL; (*measuring signal failure displacement sensor 1 generator NDE bearing*) (*OldName:newPv;Cycle:5*)
		bMsg2634 : BOOL; (*measuring signal failure displacement sensor 2 generator NDE bearing*) (*OldName:newPv;Cycle:5*)
		bMsg2637 : BOOL; (*Generator interface panel circuit breaker tripped*) (*OldName:newPv;Cycle:5*)
		bMsg2665 : BOOL; (*Generator heater circuit breaker tripped*) (*OldName:newPv;Cycle:5*)
		bMsg2690 : BOOL; (*rotor earth fault*) (*OldName:newPV; Cycle:5;*)
		bMsg2691 : BOOL; (*reactive power/undervoltage protection (Q-U-protection)*) (*OldName:newPV; Cycle:5;*)
		bMsg2827 : BOOL; (*Generator Lube Oil System/Jacket Oil System read for start and operation*) (*OldName:bAMM[2827];Cycle:5;*)
		bMsg2828 : BOOL; (*Generator Lube Oil System oil outlet pressure ok*) (*OldName:bAMM[2828];Cycle:5;*)
		bMsg2829 : BOOL; (*Generator Lube Oil System drive end bearing oil flow ok*) (*OldName:bAMM[2829];Cycle:5;*)
		bMsg2830 : BOOL; (*Generator Lube Oil System non drive end bearing oil flow ok*) (*OldName:bAMM[2830];Cycle:5;*)
		bMsg2998 : BOOL; (*Q-limit by under voltage*)
		bMsg3219 : BOOL; (* excitation voltage low *) (*OldName:AN_ERGW1;Cycle:5*)
		bMsg3298 : BOOL; (* gcb opened by generator reverse power  *) (*OldName:ALM[3298];Cycle:5*)
		bMsg3299 : BOOL; (* gcb opened by current negative sequence *) (*OldName:ALM[3299];Cycle:5*)
		bMsg3319 : BOOL; (* generator protection trip *) (*OldName:ALM[3319];Cycle:5*)
		bMsg3393 : BOOL; (*generator overexcitation*) (*OldName:newPV; Cycle:5;*)
		bMsg3418 : BOOL; (*W3418 Oilskid oil in oil sump *) (*OldName:newPv; Cycle:5;*)
		bMsg3419 : BOOL; (*W3419 Oilskid tank oil level measuring signal failure *) (*OldName:newPv; Cycle:5;*)
		bMsg3420 : BOOL; (*W3420 Oilskid tank oil level low*) (*OldName:newPv; Cycle:5;*)
		bMsg3421 : BOOL; (*W3421 Oilskid tank oil temperature measuring signal failure*) (*OldName:newPv; Cycle:5;*)
		bMsg3422 : BOOL; (*W3422 Oilskid tank oil temperature low*) (*OldName:newPv; Cycle:5;*)
		bMsg3423 : BOOL; (*W3423 Oilskid oil supply temperature measuring signal failure*) (*OldName:newPv; Cycle:5;*)
		bMsg3424 : BOOL; (*W3424 Oilskid oil supply temperature low*) (*OldName:newPv; Cycle:5;*)
		bMsg3425 : BOOL; (*W3425 Oilskid oil supply temperature high*) (*OldName:newPv; Cycle:5;*)
		bMsg3426 : BOOL; (*W3426 Oilskid low pressure oil pump circuit breaker tripped*) (*OldName:newPv; Cycle:5;*)
		bMsg3427 : BOOL; (*W3427 Oilskid oil flow TO DE bearing measuring signal failure*) (*OldName:newPv; Cycle:5;*)
		bMsg3428 : BOOL; (*W3428 Oilskid oil flow TO DE bearing low*) (*OldName:newPv; Cycle:5;*)
		bMsg3429 : BOOL; (*W3429 Oilskid oil flow TO DE bearing high*) (*OldName:newPv; Cycle:5;*)
		bMsg3430 : BOOL; (*W3430 Oilskid oil flow TO NDE bearing measuring signal failure*) (*OldName:newPv; Cycle:5;*)
		bMsg3431 : BOOL; (*W3431 Oilskid oil flow TO NDE bearing low*) (*OldName:newPv; Cycle:5;*)
		bMsg3432 : BOOL; (*W3432 Oilskid oil flow TO NDE bearing high*) (*OldName:newPv; Cycle:5;*)
		bMsg3433 : BOOL; (*W3433 Oilskid high pressure oil pump circuit breaker tripped*) (*OldName:newPv; Cycle:5;*)
		bMsg3434 : BOOL; (*W3434 Oilskid high pressure oil pump circuit breaker tripped - UPS*) (*OldName:newPv; Cycle:5;*)
		bMsg3435 : BOOL; (*W3435 Oilskid oil pressure TO DE bearing measuring signal failure*) (*OldName:newPv; Cycle:5;*)
		bMsg3436 : BOOL; (*W3436 Oilskid oil pressure TO DE bearing low*) (*OldName:newPv; Cycle:5;*)
		bMsg3442 : BOOL; (*W3442 Oilskid oil pressure TO NDE bearing measuring signal failure*) (*OldName:newPv; Cycle:5;*)
		bMsg3443 : BOOL; (*W3443 Oilskid oil pressure TO NDE bearing low*) (*OldName:newPv; Cycle:5;*)
		bMsg3446 : BOOL; (*W3446 Oilskid high pressure oil filter NDE clogged*) (*OldName:newPv; Cycle:5;*)
		bMsg3437 : BOOL; (*W3437 Oilskid fan circuit breaker tripped*) (*OldName:newPv; Cycle:5;*)
		bMsg3438 : BOOL; (*W3438 Oilskid heater circuit breaker tripped*) (*OldName:newPv; Cycle:5;*)
		bMsg3439 : BOOL; (*W3439 Oilskid main switch auxiliaries opened*) (*OldName:newPv; Cycle:5;*)
		bMsg3440 : BOOL; (*W3440 Oilskid auxiliaries voltage NOT available*) (*OldName:newPv; Cycle:5;*)
		bMsg3441 : BOOL; (*W3441 Oilskid auxiliaries voltage NOT available - UPS*) (*OldName:newPv; Cycle:5;*)
		bMsg3447 : BOOL; (*W3447 Oilskid circulation pump circuit breaker tripped*) (*OldName:newPv; Cycle:5;*)
		bMsg3468 : BOOL; (*generator air inlet temperature 2 signal failure*) (*OldName:newPv;Cycle:5*)
		bMsg3516 : BOOL; (*excitation voltage high*) (*OldName:AN_ERGW2;Cycle:5*)
		bMsg3563 : BOOL; (*Generator lubrication failure, Warning*) (*OldName:Not-found;Cycle:5*)
		bMsg3566 : BOOL; (*Generator power factor setpoint measuring signal failur*) (*Oldname: ALM[3566];Cycle:5*)
		bMsg3573 : BOOL; (*Generatow lube oil cooling system failure*) (*OldName:newpv;Cycle:5*)
		bMsg9311 : BOOL; (*Earth failure, warning*)
		tU_Stat : _tXY_Stat; (* Voltage static XY Diagram *)
		bCntGndFail_Visible : BOOL; (*counter earth failure visibility*)
		bMsg1038Set : BOOL; (*Generator reverse power, Trip*)
		bMsg1109Set : BOOL; (*loss of excitation (trip)*)
		bMsg1110Set : BOOL; (*Generator frequency low, Trip*)
		bMsg1111Set : BOOL; (*Generator frequency high, Trip*)
		bMsg1112Set : BOOL; (*Neutral current high, Trip*)
		bMsg1126Set : BOOL; (*generator voltage low, Trip*)
		bMsg1127Set : BOOL; (*generator voltage high, Trip*)
		bMsg1143Set : BOOL; (*Voltage negative sequence (Voltage asymmetry), Trip*)
		bMsg1144Set : BOOL; (*Current negative sequnece (Current asymmetrt), Trip*)
		bMsg2277Set : BOOL; (*Generator voltage too low 2*)
		bMsg2316Set : BOOL; (*generator voltage high 2 (one phase)*)
		bMsg9351 : BOOL; (*Measuring signal failure external reactive power set point for voltage droop mode*)
		bMsg9365 : BOOL; (*Automatic generator greasing system error (drive end DE bearing) *)
		bMsg9366 : BOOL; (*Automatic generator greasing system error (non-drive end NDE bearing) *)
		bMsg9367 : BOOL; (*Automatic generator greasing system - lubrication cartridge empty (drive end DE bearing) *)
		bMsg9368 : BOOL; (*Automatic generator greasing system - lubrication cartridge empty (non-drive end NDE bearing) *)
		rQ_Droop_Offs : REAL; (*Actual reactive power set point for voltage droop mode*)
		iIdx_Q_Droop_Offs : INT; (*Source of reactive power set point for voltage droop mode 0=none/1=analog/2=bus/3=HMI)*)
		iSource_U_OffsSet : INT; (* Voltage setpoint in island mode: 0= no setpoint, 1= Droop, 2= External *)
		bMsg9372 : BOOL; (*W9372 Multi measurement device: Earth failure generator*)
		bMsg2373 : BOOL; (*A2373 Multi measurement device: Earth failure generator*)
	END_STRUCT;
END_TYPE

(*END_MM2VIS*)

TYPE
	VIS2MM_Struct : 	STRUCT 
		tCtrGenPF_In : _tGeACtrIn; (*Visulization to Controller in structure*) (*OldName:new pv;Cycle:5*)
		tCtr_Q_In : _tGeACtrIn; (*Visulization to Controller in structure*) (*OldName:new pv;Cycle:5*)
		iCnt_OilSkid_HP_PrErr : INT; (*Para-Visu synchronization operating mode selection*) (*OldName:newPv; Cycle:5;*)
		iOpH_GndFailure : DINT; (* earth failure h *)
		bQ_Droop_Set_Man : BOOL; (*Manual reactive power set point for voltage droop mode active*)
		rQ_Droop_Set_Man : REAL; (*Manual reactive power set point for voltage droop mode active*)
	END_STRUCT;
	IN_GC_Struct : 	STRUCT 
		tAB2GC : AmmBase2MM; (*Structure Alarm base to Generator control module*) (*OldName:new pv;Cycle:5;*)
		tPB2MM : ParaBase2MM_type; (*Data exchange structure to ParaBase*) (*OldName:new PV;Cycle:5*)
		tCustAnaIn : ARRAY[0..120]OF HALioAi_Type; (*Replacement for RAN_KANAL...*) (*OldName: ANA_RAN; Cycle:5;*)
		tCustDigIn : ARRAY[0..200]OF HALioDi_Type; (*new, reserved for Project specific use*) (*OldName: newPV; Cycle:5;*)
		tExtCtrOk : HALioDi_Type; (* DI: External speed / voltage controller okay *) (*OldName: newPV; Cycle:5;*)
		tECWP_PreH_Dem : HALioDo_Type; (*engine cooling water preheating pump demand*) (*OldName:A_VORW;Cycle:5*)
		tEleStarter_Dem : HALioDo_Type; (*electric starter demand*) (*OldName:A_STRT;Cycle:5;*)
		tU_Gen_Dec : HALioDi_Type; (*digital input for voltage adjustment external (decreasing)*) (*OldName:DI_u_minus; Cycle: 5;*)
		tU_Gen_Inc : HALioDi_Type; (*digital input for voltage adjustment external (increasing)*) (*OldName:DI_u_plus; Cycle: 5;*)
		tDiffPrct : HALioDi_Type; (*DI: Differential protection *) (*OldName:DIFF;Cycle:5*)
		tEng_Run : HALioDo_Type; (*Engine in operation*) (*OldName:M_BTRB;Cycle:5*)
		tEng_SUExc_Rel : HALioDi_Type; (*start-up excitation release*) (*OldName:U_SY_LFG;Cycle:5*)
		tF_MMD : ARRAY[0..2]OF HALioAi_Type; (*actual generator frequency*) (*OldName:usFreq,ssFreq;Cycle:5*)
		tF_MMD_LimHi : ARRAY[0..2]OF HALioDi_Type; (*generator frequency too high*) (*OldName:GFZH;Cycle:5*)
		tF_MMD_LimLo : ARRAY[0..2]OF HALioDi_Type; (*generator frequency too low*) (*OldName:GFZN;Cycle:5*)
		tFlow_Gen_Lube : HALioDi_Type; (*generator lubrication failure*) (*OldName:DI_GENS_F ;Cycle:5*)
		tGCB_DVM : HALioDi_Type; (*voltage matching for synchronization*) (*OldName:MSY_DVM;Cycle:5*)
		tGCB_On : HALioDi_Type; (*Generator circuit breaker*) (*OldName:GCB_ON;Cycle:5*)
		tGen_Exc_Off : HALioDi_Type; (*de- excitation*) (*OldName:T_ENTR;Cycle:5*)
		tGen_T_In : HALioAi_Type; (*generator air inlet temperature*) (*OldName:t_GenAirIn;Cycle:5*)
		tGen_T_In2 : HALioAi_Type; (*generator air inlet temperature*) (*OldName:new_pv;Cycle:5*)
		tT_GenAirOut : HALioAi_Type; (*generator air outlet temperature*) (*OldName:t_GenAirOut;Cycle:5*)
		tGenDeexitDem : HALioDo_Type; (*generator deexitation demand*) (*OldName:A_ENTR;Cycle:5*)
		tGenPrctTrip : HALioDi_Type; (*Generator protection trip*) (*OldName:DI_GEN_PT_TC1;Cycle:5*)
		tGndFailure : HALioDi_Type; (*earth failure generator*) (*OldName:ERDS;Cycle:5*)
		tI_Diff : HALioDi_Type; (*generator differential protection trip*) (*OldName:ST_DIFF;Cycle:5*)
		tI_MMD_Asy : ARRAY[0..2]OF HALioDi_Type; (*generator current negative sequence too high*) (*OldName:IASY;Cycle:5*)
		tI_MMD_LimHi : HALioDi_Type; (*MMD: overload short circuit*) (*OldName:DI_MMD_OL_TC1;Cycle:5*)
		tI_MMD_Neutr_LimHi : ARRAY[0..2]OF HALioDi_Type; (*generator neutral current too high*) (*OldName:INULL;Cycle:5*)
		tMCB_On : HALioDi_Type; (*mains circuit breaker closed*) (*OldName:MCB_ON;Cycle:5*)
		tOlShortCirc : HALioDi_Type; (*Overload/short circuit*) (*OldName:ULKS, DI_GCB_OL_TC1;Cycle:5*)
		tP_Act : ARRAY[0..2]OF HALioAi_Type; (*actual electric power [kW] *) (*OldName:ssPAct;Cycle:5*)
		tPF_Act : ARRAY[0..2]OF HALioAi_Type; (*actual cos phi value *) (*OldName:ssCosPhi, ANA.COSPHI;Cycle:5*)
		tQ_Act : ARRAY[0..2]OF HALioAi_Type; (*actual reactive power [kVar] *) (*OldName:ssPReac;Cycle:5*)
		tRel_U_Sel_LS_Gen : HALioDi_Type; (*Release voltage selection LS-Generator *) (*OldName:E_LSHK;Cycle:5*)
		tReq_PowMod : HALioDi_Type; (*request power operation mode *) (*OldName:DI_DMND_PM;Cycle:5*)
		tT_Gen_Bear_A_Act : HALioAi_Type; (*generator bearing A temperature signal*) (*OldName:ANA.LAG1;Cycle:5*)
		tT_Gen_Bear_B_Act : HALioAi_Type; (*generator bearing B temperature signal*) (*OldName:ANA.LAG2;Cycle:5*)
		tT_Gen_Wind : HALioAi_Type; (*actual generator winding temperature signal*) (*OldName:ANA.WICK;Cycle:5*)
		tT_Gen_Wind_Act_L1 : HALioAi_Type; (*generator winding temperature signal, winding phase 1*) (*OldName:ANA.WICK1;Cycle:5*)
		tT_Gen_Wind_Act_L2 : HALioAi_Type; (*generator winding temperature signal, winding phase 2*) (*OldName:ANA.WICK2;Cycle:5*)
		tT_Gen_Wind_Act_L3 : HALioAi_Type; (*generator winding temperature signal, winding phase 3*) (*OldName:ANA.WICK3;Cycle:5*)
		tU_Adj_Minus : HALioDi_Type; (*Voltage adjustment Minus *) (*OldName:A_UMIN;Cycle:5*)
		tU_Adj_Plus : HALioDi_Type; (*Voltage adjustment Plus *) (*OldName:A_UPLU;Cycle:5*)
		tU_Avg : ARRAY[0..2]OF HALioAi_Type; (*actual generator average voltage*) (*OldName:ssUAvg;Cycle:5*)
		tU_Gen_Contr_Fail : HALioDi_Type; (*generator voltage regulator failure *) (*OldName:DI_GENREG_F;Cycle:5*)
		tU_Gen_Exc : HALioAi_Type; (*actual excitation voltage signal, filtered and scaled*) (*OldName:ANA.ERREG;Cycle:5*)
		tU_Gen_LimHi : ARRAY[0..2]OF HALioDi_Type; (*generator voltage too high*) (*OldName:GUZH ;Cycle:5*)
		tU_Gen_LimLo2 : ARRAY[0..2]OF HALioDi_Type; (*generator voltage too low 2*) (*OldName:GUZN_2;Cycle:5*)
		tU_Gen_LimLo : ARRAY[0..2]OF HALioDi_Type; (*generator voltage too low*) (*OldName:GUZN;Cycle:5*)
		tU_GenDiode_Fail : HALioDi_Type; (*generator diode alarm*) (*OldName:DI_GEN_D_F ;Cycle:5*)
		tU_GenDiode_Trip : HALioDi_Type; (*generator diode trip*) (*OldName:DI_GEN_D_Tr ;Cycle:5*)
		tU_GenOverVolt : HALioDi_Type; (*failure generator overvoltage protection*) (*OldName:DI_GOVP ;Cycle:5*)
		tGen_LO_CoolingSys_Fail : HALioDi_Type; (*generator lube oil cooling system failure*) (*OldName: DI_GEN_BERC; Cycle: 5;*)
		tGenCtr_CktBkr_Trip : HALioDi_Type; (*generator cicuit breaker off*) (*OldName: GEN_AVR_CB; Cycle: 5;*)
		tU_MMD_Asy : ARRAY[0..2]OF HALioDi_Type; (*generator voltage negative sequence too high*) (*OldName:UASY;Cycle:5*)
		tU_MMD_Synch1 : ARRAY[0..2]OF HALioAi_Type; (*phase voltage system 1*) (*OldName:ssSynch1Volt;Cycle:5*)
		tU_MMD_Synch2 : ARRAY[0..2]OF HALioAi_Type; (*phase voltage system 2*) (*OldName:ssSynch2Volt;Cycle:5*)
		rT_Ch_T1LP_Avg : REAL; (*average charge temperature before low-pressure turbocharger (= engine intake air) [°C]*) (*OldName:ssIATemp,ANA_ZLTP,tT_InAirER; Cycle:5;*) (* V04.04.00.00 *)
		bAMM_T_Ch_T1LP_Avg : BOOL; (*collective warning - average charge temp. before low-pressure TC (= engine intake air)*) (* V04.04.00.00 *)
		bECW_Gnl_PreH_Dem : BOOL; (*engine cooling water preheating demand *)
		tLev_OilSkid_Sump_Hi : HALioDi_Type; (*OilSkid oil in safety sump *) (*Oldname:new pv;Cycle:5;*)
		tOilSkid_PumpLP_CBOk : HALioDi_Type; (*OilSkid low pressure pump - circuit breaker*) (*Oldname:new pv;Cycle:5;*)
		tDPr_OilSkid_FiltLP_Hi : HALioDi_Type; (*OilSkid difference pressure - oil low pressure filter*) (*Oldname:new pv;Cycle:5;*)
		tOilSkid_PumpHP_DemOn : HALioDi_Type; (*OilSkid high pressure pump - demand ON*) (*Oldname:new pv;Cycle:5;*)
		tOilSkid_PumpHP_DemOff : HALioDi_Type; (*OilSkid high pressure pump - demand OFF*) (*Oldname:new pv;Cycle:5;*)
		tOilSkid_PumpHP_CBOk : HALioDi_Type; (*OilSkid high pressure pump - circuit breaker*) (*Oldname:new pv;Cycle:5;*)
		tOilSkid_PumpHP_CBOk_UPS : HALioDi_Type; (*OilSkid high pressure pump - circuit breaker UPS*) (*Oldname:new pv;Cycle:5;*)
		tT_OilSkid_Supply : HALioAi_Type; (*OilSkid supply temperature*) (*Oldname:new pv;Cycle:5;*)
		tT_OilSkid_Tank : HALioAi_Type; (*OilSkid tank temperature*) (*Oldname:new pv;Cycle:5;*)
		tLev_OilSkid_Tank : HALioAi_Type; (*OilSkid tank level*) (*Oldname:new pv;Cycle:5;*)
		tFlow_OilSkid_DE : HALioAi_Type; (*OilSkid oil flow to DE bearing *) (*Oldname:new pv;Cycle:5;*)
		tFlow_OilSkid_NDE : HALioAi_Type; (*OilSkid oil flow to NDE bearing (G.03-FI-003)*) (*Oldname:new pv;Cycle:5;*)
		tOilSkid_Heater_CBOk : HALioDi_Type; (*OilSkid heater - circuit breaker*) (*Oldname:new pv;Cycle:5;*)
		tDPr_OilSkid_FiltHP_DE_Hi : HALioDi_Type; (*OilSkid difference pressure - oil high pressure filter to DE bearing*) (*Oldname:new pv;Cycle:5;*)
		tDPr_OilSkid_FiltHP_NDE_Hi : HALioDi_Type; (*OilSkid difference pressure - oil high pressure filter to NDE bearing*) (*Oldname:new pv;Cycle:5;*)
		tOilSkid_Fan_CBOk : HALioDi_Type; (*OilSkid fan - circuit breaker*) (*Oldname:new pv;Cycle:5;*)
		tOilSkid_MCB : HALioDi_Type; (*OilSkid main switch auxiliaries opened*) (*Oldname:new pv;Cycle:5;*)
		tOilSkid_AuxV_Ok : HALioDi_Type; (*OilSkid auxiliaries voltage not available*) (*Oldname:new pv;Cycle:5;*)
		tOilSkid_AuxV_Ok_UPS : HALioDi_Type; (*OilSkid auxiliaries voltage not available - UPS*) (*Oldname:new pv;Cycle:5;*)
		tOilSkid_PumpC_CBOk : HALioDi_Type; (*OilSkid circulation pump - circuit breaker*) (*Oldname:new pv;Cycle:5;*)
		tPr_OilSkid_HP_DE : HALioAi_Type; (*OilSkid oil pressure in high pressure circuit to DE bearing*) (*Oldname:new pv;Cycle:5;*)
		tPr_OilSkid_HP_NDE : HALioAi_Type; (*OilSkid oil pressure in high pressure circuit to NDE bearing *) (*Oldname:new pv;Cycle:5;*)
		tF_GenBear_DE1 : HALioAi_Type; (*vibration generator bearing drive end 1*) (*Oldname:AI_v_GenBearDE1;Cycle:5;*)
		tF_GenBear_DE2 : HALioAi_Type; (*vibration generator bearing drive end 2*) (*Oldname:AI_v_GenBearDE2;Cycle:5;*)
		tF_GenBear_NDE1 : HALioAi_Type; (*vibration generator bearing non drive end 1*) (*Oldname:AI_v_GenBearNDE1;Cycle:5;*)
		tF_GenBear_NDE2 : HALioAi_Type; (*vibration generator bearing non drive end 2*) (*Oldname:AI_v_GenBearNDE2;Cycle:5;*)
		tGenIF_CB_On : HALioDi_Type; (*Generator interface panel circuit breaker tripped*) (*Oldname:DI_GENI_CB_trip;Cycle:5;*)
		tGenHeat_CB_On : HALioDi_Type; (*Generator heater circuit breaker tripped*) (*Oldname:newPv;Cycle:5;*)
		bEng_RPSDem : BOOL; (*engine demanded  *) (*OldName:A_AGFD; Cycle:5*)
		rCust_SparePara : ARRAY[0..200]OF REAL; (*SPS_REZP1 to SPS_REZP200	*) (* OldName: SPS_REZP1, SPS_REZP2, SPS_REZP70; Cycle: 5; *)
		iGCQ_Fun_Act : USINT; (*Number of the active Voltage control function from static GridCode*) (*OldName:usGCQ_Fun_act;Cycle:5*)
		bGCQ_Fun_Act : BOOL; (* falls eigenes Modul Schnittstelle zu reg_in(_9) - stat. GC Funktion aktiv *) (* OldName: bGCQ_Fun_act; Cycle: 0 *)
		rPFSoll_lin_GR2GC : REAL; (*power factor setpoint GR->GC incl.QLim + GR/EVU_funct.1-5*) (*OldName:newPV;Cycle:5*)
		bScavFinished : BOOL; (*scavenging cycle finished *) (*OldName:SPUEL_AB; Cycle:5;*)
		bEO_PrelubeDemIgn : BOOL; (*Demand Prelubricating from ignition*) (*OldName:PRELUBE_IgnST; Cycle:5;*)
		bEng_Aux_Dem : BOOL; (*engine auxiliaries demand *) (*OldName:M_ANFHBT;Cycle:5;*)
		bEng_Dem : BOOL; (*Module demanded*) (*OldName:M_AGFD;Cycle:5;*)
		bEng_Dem_EPS : BOOL; (*engine demand for emergency operation*) (*OldName:M_NANF;Cycle:5;*)
		bEng_Start : BOOL; (*Engine start command*) (*OldName:M_STRT;Cycle:5;*)
		bGCB_DemSy : BOOL; (*generator circuit breaker demand synchronization*) (*OldName:ASYANW;Cycle:5;*)
		bGen_SyD_Dem : BOOL; (* demand synch.device *) (*OldName:dmnd_sy_device;Cycle:5;*)
		bGV_On : BOOL; (*command open gas valves*) (*OldName:M_GASV;Cycle:5;*)
		bIgn_Dem : BOOL; (*Demand ignition*) (*OldName:ZUEND;Cycle:5;*)
		bMCB_DemSy : BOOL; (*mains circuit breaker demand synchronization*) (*OldName:ARSYANW;Cycle:5;*)
		bOtherGenParallel : BOOL; (*1 Genset still in operation and demanded *) (*OldName:PARALLEL;Cycle:5;*)
		bSCO_Active : BOOL; (*safety cut out gas valves glow ignition prevention*) (*OldName:SICH_SCHL;Cycle:5;*)
		bSynchDem : BOOL; (*synchronization demanded*) (*OldName:bSynch;Cycle:5;*)
		bSyncSlipMode : ARRAY[0..2]OF BOOL; (* MMD synchronization with slip mode *) (*OldName:bSyncSlipMode;Cycle:5;*)
		iIdx_Gtyp_Dem : INT; (* actual gassort 0 to 4 *) (*OldName:gasart;Cycle:5;*)
		iSt_OpMode : UDINT; (*Operating mode*) (*OldName:InselM;Cycle:5;*)
		iIdx_OMSS : INT; (*Index of operation mode selector switch*) (*OldName:BWS_HA ;Cycle:5;*)
		rN_EngAct : REAL; (* Engine Speed (1/min) *) (*OldName:ANA.DREHZ;Cycle:5;*)
		rP_Act_Norm_Filt : REAL; (*Actual normalized power*) (*OldName:P_IST_PROM;Cycle:5;*)
		rP_Act_Norm : REAL; (*actual power related to rP_Nom without filter *) (* OldName: P_IST_OF; Cyclic:5; *)
		rP_Nom : REAL; (*Nominal power*) (*OldName:PN_GASART;Cycle:5;*)
		rPF_CosPCtr_Bus : REAL; (*Power factor setpoint via bus*) (*Oldname:new pv;Cycle:5;*)
		bEng_Aux_Dem_CDR : BOOL; (*engine auxiliaries demand with cool down run*) (*OldName:ANFHBT; Cycle:5*)
		bMsg1031 : BOOL; (*Emergency stop*) (*OldName: M_SIS; Cycle: 5;*)
		bMsg1054 : BOOL; (*Fire alarm*) (*OldName:M_BAL; Cycle: 5;*)
		tP_GenRev_Ext : HALioDi_Type; (*generator reverse power*) (*OldName:newPV; Cycle:5*)
		tGenLossExc_Ext : HALioDi_Type; (*generator loss of excitation*) (*OldName:newPV; Cycle:5*)
		tU_GenAsy_Ext : HALioDi_Type; (*voltage negative sequence*) (*OldName:newPV; Cycle:5*)
		tI_GenAsy_Ext : HALioDi_Type; (*current negative sequence*) (*OldName:newPV; Cycle:5*)
		tGenOverExc : HALioDi_Type; (*generator overexcitation*) (*OldName:newPV; Cycle:5*)
		tGenRotorEarthFault : HALioDi_Type; (*rotor earth fault*) (*OldName:newPV; Cycle:5*)
		tQ_GenUnderVoltProt : HALioDi_Type; (*reactive power/undervoltage protection (Q-U-protection)*) (*OldName:newPV; Cycle:5*)
		bMMD_GenAlarmTestOn : BOOL; (*MMD_Gen alarm test On*) (*OldName:newPv; Cycle:5;*)
		bN2_ScavCoPrelubeOn : BOOL; (*N2 scavenging command prelubrication ON*) (*OldName:PRELUBE_SC;Cycle:5*)
		bTP_GrC_Event : BOOL;
		bOilskidDemSTFS : BOOL; (*oilskid demand for slowturn faststart*) (* Oldname: new PV, Cycle:5 *)
		tS_Act : ARRAY[0..2]OF HALioAi_Type; (*actual aparent power [kVar] *) (*OldName:newPV;Cycle:5*)
		rQSoll_filt_GR2GC : REAL; (*Q setpoint after ramp before limiter from GR*) (*OldName:newPV;Cycle:5*)
		rQSoll_Lim_GR2GC : REAL; (*Q setpoint limited from GR*) (*OldName:newPV;Cycle:5*)
		rP_POC_Act_Cust : REAL; (*active power actual  from customer(point of connection)[kW]*) (*OldName:newPV;Cycle:5*)
		rS_POC_Act_Cust : REAL; (*apparent power actual from customer(point of connection)[kVA]*) (*OldName:newPV;Cycle:5*)
		rQ_POC_Act_Cust : REAL; (*reactive power actual from customer(point of connection)[kVAr]*) (*OldName:newPV;Cycle:5*)
		rPF_POC_Act_Cust : REAL; (*power factor actual from customer(point of connection)*) (*OldName:newPV;Cycle:5*)
		bQSetLim : BOOL; (*GR: Q limitation custom OR Q(U) ON*) (*OldName:newPV;Cycle:5*)
		tU_L1L2 : ARRAY[0..2]OF HALioAi_Type; (* generator voltage phase 1_2 [V] *) (*OldName:ssUL1L2[1];Cycle:5;*)
		tU_L2L3 : ARRAY[0..2]OF HALioAi_Type; (* generator voltage phase 2_3 [V] *) (*OldName:ssUL2L3[1];Cycle:5;*)
		tU_L3L1 : ARRAY[0..2]OF HALioAi_Type; (* generator voltage phase 3_1 [V] *) (*OldName:ssUL3L1[1];Cycle:5;*)
		tU_L1N : ARRAY[0..2]OF HALioAi_Type; (* generator voltage phase 1_N [V] *) (*OldName:ssUL1N[1];Cycle:5;*)
		tU_L2N : ARRAY[0..2]OF HALioAi_Type; (* generator voltage phase 2_N [V] *) (*OldName:ssUL2N[1];Cycle:5;*)
		tU_L3N : ARRAY[0..2]OF HALioAi_Type; (* generator voltage phase 3_N [V] *) (*OldName:ssUL3N[1];Cycle:5;*)
		rU_Set_Norm_Cust : REAL; (* External voltage set point from CU module [%Unom] *) (*OldName:new PV V4.07;Cycle:5*)
		bMsg2831 : BOOL; (* B2831 Low Voltage Ride Through Event *)
		tGndFaultW : HALioDi_Type; (*Earth failure generator warning*)
		bN_U_Set_Ext_On : BOOL; (*External speed and voltage control ON*)
		tQ_Droop_Set : HALioAi_Type; (*reactive power setpoint in voltage droop*)
		tU_SetExtAI_Norm : HALioAi_Type; (*setpoint voltage [%Unom]*)
		rQset_Droop_Bus : REAL; (*Reactive power setpoint for droop mode via Bus*)
		rUset_Isl_Bus : REAL; (*Generator voltage setpoint via Bus*)
		bMsg1147 : BOOL; (*W1147 Outage coupling with central control system*)
		bExtCtrOk : BOOL; (*External voltage/speed control released*)
		rU_Set_NP : REAL; (*voltage setpoint-net parallel mode*)
		bU_Set_NP_Rel : BOOL; (*voltage setpoint-net parallel mode/release*)
		tGenBearGreasSys2DE : HALioDi_Type; (*INNIO STAR CONTROL SYSTEM Pin2 drive end DE bearing*)
		tGenBearGreasSys4DE : HALioDi_Type; (*INNIO STAR CONTROL SYSTEM Pin4 drive end DE bearing*)
		tGenBearGreasSys2NDE : HALioDi_Type; (*INNIO STAR CONTROL SYSTEM Pin2 non-drive end NDE bearing*)
		tGenBearGreasSys4NDE : HALioDi_Type; (*INNIO STAR CONTROL SYSTEM Pin4 non-drive end NDE bearing*)
		bGCB_aut_on2dead_bb : BOOL; (*generator circuit breaker automatic on to dead bus bar*)
		iTimeStamp_PosZeroCrossing_UGen1 : DINT; (*TimeStamp of last positive zero crossing UGen1 [ 1 / 4096microseconds]*)
		iTimeStamp_PosZeroCrossing_UGen2 : DINT; (*TimeStamp of last positive zero crossing UGen2 [ 1 / 4096microseconds]*)
		iTimeStamp_PosZeroCrossing_UGen3 : DINT; (*TimeStamp of last positive zero crossing UGen3 [ 1 / 4096microseconds]*)
		bReq_PowMod : BOOL; (*request power mode - over-written in customization*)
		bBypassMCB_CosPhi : BOOL; (*bypass MCB status information from the standard CosPhi Ctrl check*)
		bSimWinMOD_Active : BOOL; (*WinMode simulation active *) (*OldName:new PV; Cycle:5*)
	END_STRUCT;
END_TYPE

(*END_IN*)

TYPE
	OUT_GC_Struct : 	STRUCT 
		tGC2AB : MM2AmmBase; (*AMM structure *) (*OldName:new pv;Cycle:5*)
		tGC2PB : MM2ParaBase_type; (*Data exchange structure to ParaBase*) (*OldName:new pv;Cycle:5*)
		tPF_AO_PF_U : HALioAo_Type; (*power factor generator *) (* OldName:AO_PF_gen_V;Cycle:5*)
		tPF_AO_PF_I : HALioAo_Type; (*power factor generator *) (* OldName:AO_PF_gen_mA;Cycle:5*)
		tGen_PreHDem : HALioDo_Type; (*Generator preheat demand*) (*OldName: DO_GenPreH; Cycle:5;*)
		tCtr_Gen_Set : HALioAo_Type; (*Generator ???*) (*OldName:new pv;Cycle:5*)
		tGCB_On_ReturnSign : HALioDo_Type; (*Release for Unitrol AVR*) (*Oldname:DO_GCB_ON;Cycle:5*)
		tLOS_Dem : HALioDo_Type; (*Generator demand lube oil system*) (*OldName:DO_GEN_BERC;Cycle:5*)
		tLeroySomer_AuxContactor : HALioDo_Type; (*LEROY-SOMER Auxiliary Contactor *) (*OldName:LSHK;Cycle:5*)
		tPF_CosPCtr_Ena : HALioDo_Type; (*power factor controller enabled*) (*OldName:A_COSPHI;Cycle:5*)
		tT_AO_Gen_T_In : HALioAo_Type; (*Generator air inlet temperature for gen.controler*) (*OldName:AO_t_GenAirIn_V;Cycle:5*)
		tGenCtrResetSp : HALioDo_Type; (*Generator controller reset setpoint*) (*OldName:DO_GenCtrResetSp;Cycle:5*)
		tU_MidPos : HALioDo_Type; (*Voltage middle position *) (*OldName:U_MIT;Cycle:5*)
		tU_Minus : HALioDo_Type; (*Voltage minus *) (*OldName:UMIN;Cycle:5*)
		tU_Plus : HALioDo_Type; (*Voltage plus *) (*OldName:UPLU;Cycle:5*)
		tOilSkid_PumpLP : HALioDo_Type; (*OilSkid low pressure pump (G.03-M-001)*) (*OldName:new pv;Cycle:5*)
		tOilSkid_PumpHP : HALioDo_Type; (*OilSkid high pressure pump (G.03-M-002)*) (*OldName:new pv;Cycle:5*)
		tOilSkid_PumpHP_UPS : HALioDo_Type; (*OilSkid high pressure pump - UPS (G.03-M-002)*) (*OldName:new pv;Cycle:5*)
		tOilSkid_PumpHP_Soft : HALioDo_Type; (*OilSkid high pressure pump - Soft (G.03-M-002)*) (*OldName:new pv;Cycle:5*)
		tOilSkid_PumpC : HALioDo_Type; (*OilSkid circulation pump (G.03-M-004)*) (*OldName:new pv;Cycle:5*)
		tOilSkid_Fan : HALioDo_Type; (*OilSkid fan*) (*OldName:new pv;Cycle:5*)
		tOilSkid_Heater : HALioDo_Type; (*OilSkid heater*) (*OldName:new pv;Cycle:5*)
		rPFSoll_lin_GC2GR : REAL; (*power factor setpoint GC->GR incl.GenReg.funct.1-7*) (*OldName:newPV;Cycle:5*)
		bP_Red_CosPCtr_U_Lo : BOOL; (*Power reduction by voltage low*) (*OldName:bPowRedGenSpgL;Cycle:5;*)
		bP_Red_CosPCtr_U_Hi : BOOL; (*Power reduction by voltage high*) (*OldName:bPowRedGenSpgH;Cycle:5;*)
		bP_Red_CosPCtr_F_Hi : BOOL; (*Power reduction by frequency high*) (*OldName:bPowRedGenFrqH;Cycle:5;*)
		bP_Red_CosPCtr_F_Lo : BOOL; (*Power reduction by frequnecy low*) (*OldName:bPowRedGenFrqL;Cycle:5;*)
		rPF_Lim_Norm : REAL; (*Generator power reduction due to Polar angle*) (*OldName:newpv;Cycle:5;*)
		rP_Red_CosPCtr_F_Norm : REAL; (*Generator power reduction due to Frequency*) (*OldName:ssPowerRedGenFrq;Cycle:5;*)
		rP_Red_CosPCtr_T_Norm : REAL; (*Generator power reduction due to Temperature*) (*OldName:ssPowerRedGenTemp;Cycle:5;*)
		rP_Red_CosPCtr_U_Norm : REAL; (*Generator power reduction due to Voltage*) (*OldName:ssPowerRedGenSpg;Cycle:5;*)
		rU_Gen_Exc : REAL; (*IF605 gen.excitation voltage*) (*OldName: ANA.ERREG; Cycle:5;*)
		bGCB_Off_CNS : BOOL; (*Generator circuit breaker opened by curent negative sequence*) (*OldName:gcb_off_iasy;Cycle:5*)
		bGCB_Off_RP : BOOL; (*Generator circuit breaker opened by reverse power*) (*OldName:gcb_off_rlsg;Cycle:5*)
		bPF_CosPCtr_block : BOOL; (*Block bit for generator controller*) (*OldName:Reg13_bBlock2;Cycle:5*)
		bU_Gen_match_isolated : BOOL; (*Speed related voltage adjustment active (local variable)*) (*OldName:u_adj_f_a;Cycle:5*)
		bU_SyD_match : BOOL; (*Voltage matching enabled*) (*OldName:dmnd_vmatch_synch;Cycle:5*)
		rPF_CosPCtr_block : REAL; (*Block value for generator controller*) (*OldName:Reg13_Block2;Cycle:5*)
		rPF_CosPCtr_Set_2 : REAL; (*NOT USED! power factor set point*) (*OldName:ssPF_STELL;Cycle:5*)
		rU_Gen_Mns_Set : REAL; (*Set mains voltage for PF- controller*) (*OldName:ssUnetzSoll;Cycle:5*)
		rCtrGenPF_Set : REAL; (*Generator ???*) (*OldName:new pv;Cycle:5*)
		rCtr_Q_Set : REAL; (*Generator Q controller*) (*OldName:new pv;Cycle:5*)
		rPF_AO_PF_I : REAL; (*power factor generator, mA signal*) (*OldName:AO_PF_gen_mA;Cycle:5*)
		rPF_AO_PF_U : REAL; (*power factor generator, V signal*) (*OldName:AO_PF_gen_V;Cycle:5*)
		bRelEngTurn_OilSkid : BOOL; (*release engine turn gear (Durchdrehvorrichtung) from Oil Skid*) (*OldName:new pv;Cycle:5*)
		bRelEngOp_OilSkid : BOOL; (*release engine operation from Oil Skid*) (*OldName:bRelEngOpGenLOS, rel_EngOp_LOS;Cycle:5*)
		rP_Red_T_GenAirIn_Norm : REAL; (*generator air inlet temperature power reduction*)
		tQ_AVR_Set_U : HALioAo_Type; (*reactive power setpoint for AlterantorVoltageRegulator V-Signal*) (*OldName:new pv;Cycle:5*)
		bMsg1036 : BOOL; (*overload short circuit*) (*OldName:new pv;Cycle:5*)
		bMsg1038 : BOOL; (*generator reverse power*) (*OldName:new pv;Cycle:5*)
		bMsg1073 : BOOL; (*generator over load from multi measuring device*) (*OldName:new pv;Cycle:5*)
		bMsg1132 : BOOL; (*generator differential protection*) (*OldName:new pv;Cycle:5*)
		bMsg1134 : BOOL; (*Earth failure*) (*OldName:new pv;Cycle:5*)
		bMsg3319 : BOOL; (*generator protection trip*) (*OldName:new pv;Cycle:5*)
		bRelEngStart_OilSkid : BOOL; (*release engine start from Oil Skid*) (*OldName:NewPv;Cycle:5*)
		rPF_Set_TimeTable : REAL; (*power factor setpoint from time table*) (*Oldname:newPv;Cycle:5;*)
		tU_Set_Norm : HALioAo_Type; (* voltage output for island mode [%Unom] *) (*OldName:new pv V4.07 ;Cycle:5*)
		bMsg1038Set : BOOL; (*Generator reverse power, Trip*)
		bMsg1109Set : BOOL; (*loss of excitation (trip)*)
		bMsg1110Set : BOOL; (*Generator frequency low, Trip*)
		bMsg1111Set : BOOL; (*Generator frequency high, Trip*)
		bMsg1112Set : BOOL; (*Neutral current high, Trip*)
		bMsg1126Set : BOOL; (*generator voltage low, Trip*)
		bMsg1127Set : BOOL; (*generator voltage high, Trip*)
		bMsg1143Set : BOOL; (*Voltage negative sequence (Voltage asymmetry), Trip*)
		bMsg1144Set : BOOL; (*Current negative sequnece (Current asymmetrt), Trip*)
		bMsg2277Set : BOOL; (*Generator voltage too low 2*)
		bMsg2316Set : BOOL; (*generator voltage high 2 (one phase)*)
		bAMM_OilSkid_PumpLP_CB : BOOL; (*Oilskid low pressure oil pump circuit breaker tripped*)
		bAMM_OilSkid_PumpHP_CB : BOOL; (*Oilskid high pressure oil pump circuit breaker tripped*)
		bAMM_OilSkid_MCB : BOOL; (*Oilskid main switch auxiliaries opened*)
		tCtr_Q_Out : _tGeACtrOut; (* Controller to visulization out structure *)
		bMsg9285 : BOOL; (*Measuring signal failure external voltage setpoint*)
		bPact_Rev : BOOL; (*Reverse power*)
		rP_Red_Eta_Gen_Norm : REAL; (*power reduction due to Cosphi<1 sent to OP [p.u.]*)
	END_STRUCT;
END_TYPE

(*END_OUT*)

TYPE
	Perm_GC_Struct : 	STRUCT 
		iCnt_OilSkid_HP_PrErr : INT; (*synchronization operating mode selection*)
		iOpS_GndFailure : DINT; (*earth failure s*)
		iOpM_GndFailure : DINT; (*earth failure m*)
		iOpH_GndFailure : DINT; (*earth failure h*)
		rTB_PermValue04 : REAL; (*spare permanent value for testbench- replace with new vars of same lenght, when needed*) (*OldName:new PV;Cycle:2;*)
		rTB_PermValue05 : REAL; (*spare permanent value for testbench- replace with new vars of same lenght, when needed*) (*OldName:new PV;Cycle:2;*)
		rTB_PermValue06 : REAL; (*spare permanent value for testbench- replace with new vars of same lenght, when needed*) (*OldName:new PV;Cycle:2;*)
		rTB_PermValue07 : REAL; (*spare permanent value for testbench- replace with new vars of same lenght, when needed*) (*OldName:new PV;Cycle:2;*)
		rTB_PermValue08 : REAL; (*spare permanent value for testbench- replace with new vars of same lenght, when needed*) (*OldName:new PV;Cycle:2;*)
		rTB_PermValue09 : REAL; (*spare permanent value for testbench- replace with new vars of same lenght, when needed*) (*OldName:new PV;Cycle:2;*)
		rTB_PermValue10 : REAL; (*spare permanent value for testbench- replace with new vars of same lenght, when needed*) (*OldName:new PV;Cycle:2;*)
	END_STRUCT;
END_TYPE
