FUNCTION_BLOCK DigFil
	VAR_INPUT
		Input	:REAL;
		Ordnung	:UINT;
		an	:ARRAY[0..3] OF REAL;
		bn	:ARRAY[0..3] OF REAL;
	END_VAR
	VAR_OUTPUT
		Output	:REAL;
	END_VAR
	VAR
		Y	:ARRAY[0..3] OF REAL;
		X	:ARRAY[0..3] OF REAL;
	END_VAR
END_FUNCTION_BLOCK
