
TYPE
	IN_AB_Struct : 	STRUCT 
		tPB2MM : ParaBase2MM_type;
		tVE2AB : MM2AmmBase; (*VE Ventilation*) (*OldName:newPv; Cycle:2;*)
		tHC2AB : MM2AmmBase; (*HC Heating Cooling*) (*OldName:newPv; Cycle:2;*)
		tEX2AB : MM2AmmBase; (*EX Exhaust*) (*OldName:newPv; Cycle:2;*)
		tTR2AB : MM2AmmBase; (*TR ThermalReactor*) (*OldName:newPv; Cycle:2;*)
		tGC2AB : MM2AmmBase; (*GC Generator Control*) (*OldName:newPv; Cycle:2;*)
		tCU2AB : MM2AmmBase; (*CU Customized*) (*OldName:newPv; Cycle:2;*)
		tMO2AB : MM2AmmBase; (*MO Monic*) (*OldName:newPv; Cycle:2;*)
		tIC2AB : MM2AmmBase; (*IC ICxxx*) (*OldName:newPv; Cycle:2;*)
		tIG2AB : MM2AmmBase; (*IG Ignition*) (*OldName:newPv; Cycle:2;*)
		tSY2AB : MM2AmmBase; (*SY Synchronization*) (*OldName:newPv; Cycle:2;*)
		tCP2AB : MM2AmmBase; (*CP Coupling*) (*OldName:newPv; Cycle:2;*)
		tEC2AB : MM2AmmBase; (*EC EngineController*) (*OldName:newPv; Cycle:2;*)
		tEG2AB : MM2AmmBase; (*EG EngineGeneral*) (*OldName:newPv; Cycle:2;*)
		tKN2AB : MM2AmmBase; (*KN Knocking*) (*OldName:newPv; Cycle:2;*)
		tGM2AB : MM2AmmBase; (*GM GasMixer*) (*OldName:newPv; Cycle:2;*)
		tGT2AB : MM2AmmBase; (*GT GasTrain*) (*OldName:newPv; Cycle:2;*)
		tAG2AB : MM2AmmBase; (*AG AuxiliariesGeneral*) (*OldName:newPv; Cycle:2;*)
		tOP2AB : MM2AmmBase; (*OP Opstate*) (*OldName:newPv; Cycle:2;*)
		tSA2AB : MM2AmmBase; (*SA SAFI*) (*OldName:newPv; Cycle:2;*)
		tKL2AB : MM2AmmBase; (*KL KLS98*) (*OldName:newPv; Cycle:2;*)
		tGD2AB : MM2AmmBase; (*GD GasMeteringUnit*) (*OldName:newPv; Cycle:2;*)
		tCH2AB : MM2AmmBase; (*CH ChargingUnit*) (*OldName:newPv; Cycle:2;*)
		tHA2AB : MM2AmmBase; (*HA HalIO*) (*OldName:newPv; Cycle:2;*)
		tPB2AB : MM2AmmBase; (*PB ParaBase*) (*OldName:newPv; Cycle:2;*)
		tTB2AB : MM2AmmBase; (*TB Test Bench*) (*OldName:newPv; Cycle:2;*)
		tVI2AB : MM2AmmBase; (*VI Visualization*) (*OldName:newPv; Cycle:2;*)
		tGR2AB : MM2AmmBase; (*GR GRidcode*) (*OldName:newPv; Cycle:2;*)
		tEM2AB : MM2AmmBase; (*EM emission*) (*OldName:newPv; Cycle:2;*)
		tCB2AB : MM2AmmBase; (*CB condition based management*) (*OldName:newPv; Cycle:2;*)
		tResetRemoteExt : HALioDi_Type; (*reset remote external*) (*OldName:E_FQUITT; Cycle:2;*)
		tGCB_On : HALioDi_Type; (*generator circuit breaker closed*) (*OldName:DI_GCB_ON; Cycle:2;*)
		tGCB_RUC : HALioDo_Type; (*generator circuit breaker release undervoltage coil*) (*OldName:DI_GCB_RUC; Cycle:2;*)
		tSafetyLoop_Eng : HALioDi_Type; (*safety loop engine*) (*OldName:SIS; Cycle:2;*)
		tEng_Run : HALioDo_Type; (*engine in operation*) (*OldName:BTRB; Cycle:2;*)
		iPassLevel : INT; (*pass level actual*) (*OldName:ucPassLevel; Cycle:2;*)
		iIdx_OMSS : INT; (*operation selection*) (*OldName:newPv; Cycle:2;*)
		iSt_OpMode : UDINT; (*engine operation status*) (*OldName:newPv; Cycle:2;*)
		rN_EngAct : REAL; (*engine speed actual [1/min]*) (*OldName:n_ist; Cycle:2;*)
		bEng_Start : BOOL; (*engine start*) (*OldName:M_STRT; Cycle:2*)
		bResetRemBus : BOOL; (* remote reset from fieldbus *) (*OldName:M_STRT; Cycle:5*)
		bMsg2101 : BOOL; (*signal failure engine cooling water temperature*) (*OldName:M_MSKWT; Cycle:2;*)
		bMsg2102 : BOOL; (*signal failure engine engine oil temperature*) (*OldName:M_MSOTP; Cycle:2;*)
		bMsg2103 : BOOL; (*signal failure engine engine oil pressure*) (*OldName:M_MSODR; Cycle:2;*)
		bMsg2104 : BOOL; (*signal failure engine engine cooling water pressure*) (*OldName:M_MSKWD; Cycle:2;*)
		bMsg3152 : BOOL; (*signal failure engine room air temperature*) (*OldName:M_MSRTM_W; Cycle:2;*)
		bGnlWarningHMI : BOOL; (*Internal HMI messsages for building group alarm*)
	END_STRUCT;
	OUT_AB_Struct : 	STRUCT 
		tAB2PB : MM2ParaBase_type; (*AB Structure for this modules Para Services ( this is NOT tAB2PB! )*)
		tAB2VE : AmmBase2MM; (*VE Ventilation*) (*OldName:newPv; Cycle:2;*)
		tAB2HC : AmmBase2MM; (*HC Heating Cooling*) (*OldName:newPv; Cycle:2;*)
		tAB2EX : AmmBase2MM; (*EX Exhaust*) (*OldName:newPv; Cycle:2;*)
		tAB2TR : AmmBase2MM; (*TR ThermalReactor*) (*OldName:newPv; Cycle:2;*)
		tAB2GC : AmmBase2MM; (*GC Generator Control*) (*OldName:newPv; Cycle:2;*)
		tAB2CU : AmmBase2MM; (*CU Customized*) (*OldName:newPv; Cycle:2;*)
		tAB2MO : AmmBase2MM; (*MO Monic*) (*OldName:newPv; Cycle:2;*)
		tAB2IC : AmmBase2MM; (*IC ICxxx*) (*OldName:newPv; Cycle:2;*)
		tAB2IG : AmmBase2MM; (*IG Ignition*) (*OldName:newPv; Cycle:2;*)
		tAB2SY : AmmBase2MM; (*SY Synchronization*) (*OldName:newPv; Cycle:2;*)
		tAB2CP : AmmBase2MM; (*CP Coupling*) (*OldName:newPv; Cycle:2;*)
		tAB2EC : AmmBase2MM; (*EC EngineController*) (*OldName:newPv; Cycle:2;*)
		tAB2EG : AmmBase2MM; (*EG EngineGeneral*) (*OldName:newPv; Cycle:2;*)
		tAB2KN : AmmBase2MM; (*KN Knocking*) (*OldName:newPv; Cycle:2;*)
		tAB2GM : AmmBase2MM; (*GM GasMixer*) (*OldName:newPv; Cycle:2;*)
		tAB2GT : AmmBase2MM; (*GT GasTrain*) (*OldName:newPv; Cycle:2;*)
		tAB2AG : AmmBase2MM; (*AG AuxiliariesGeneral*) (*OldName:newPv; Cycle:2;*)
		tAB2OP : AmmBase2MM; (*OP Opstate*) (*OldName:newPv; Cycle:2;*)
		tAB2SA : AmmBase2MM; (*SA SAFI*) (*OldName:newPv; Cycle:2;*)
		tAB2KL : AmmBase2MM; (*KL KLS98*) (*OldName:newPv; Cycle:2;*)
		tAB2GD : AmmBase2MM; (*GD GasMeteringUnit*) (*OldName:newPv; Cycle:2;*)
		tAB2CH : AmmBase2MM; (*CH ChargingUnit*) (*OldName:newPv; Cycle:2;*)
		tAB2HA : AmmBase2MM; (*HA HalIO*) (*OldName:newPv; Cycle:2;*)
		tAB2GR : AmmBase2MM; (*GR GRidcode*) (*OldName:newPv; Cycle:2;*)
		tAB2EM : AmmBase2MM; (*EM emission*) (*OldName:newPv; Cycle:2;*)
		tAB2CB : AmmBase2MM; (*CB condition based management*) (*OldName:newPv; Cycle:2;*)
		tAlarmB2PB : AmmBase2MM; (*PB ParaBase( for AB data)*) (*OldName:newPv; Cycle:2;*)
		tAB2TB : AmmBase2MM; (*TB TestBench*) (*OldName:newPv; Cycle:2;*)
		tAB2VI : AmmBase2MM; (*VI Visualization*) (*OldName:newPv; Cycle:2;*)
		tResetWarning : HALioDo_Type; (*DO reset warning pulse*) (*OldName:DO_W_QUITT; Cycle:2;*)
		tResetTrip : HALioDo_Type; (*DO reset trip pulse*) (*OldName:DO_A_QUITT Cycle:2;*)
		tMonitoringOn : HALioDo_Type; (*DO monitoring on pulse(safety loop)*) (*OldName:UW_EIN; Cycle:2;*)
		tGnlTrip : HALioDo_Type; (*DO engine general trip*) (*OldName:A_SSTA; Cycle:2;*)
		tGnlWarning : HALioDo_Type; (*DO engine general warning*) (*OldName:A_SSTW; Cycle:2;*)
		bMsg3003 : BOOL; (*signal failure( 2101 or 2102 or 2103 or 2104 or 3152 > 24h)*) (*OldName:M_MS; Cycle:2;*)
		bServiceMode : BOOL; (*service mode*) (*OldName:bServiceBegin; Cycle:2;*)
		iMsg : ARRAY[0..9999]OF USINT; (*provides data from all alarms*) (*OldName:newPv; Cycle:2;*)
		bMMD_GenAlarmTestOn : BOOL; (*MMD_Gen alarm test On*) (*OldName:newPv; Cycle:2;*)
		bMMD_BB_AlarmTestOn : BOOL; (*MMD_BB  alarm test On*) (*OldName:newPv; Cycle:2;*)
	END_STRUCT;
	VIS2MM_Struct : 	STRUCT 
		bResetLocVis : BOOL; (*reset local from vis*) (*OldName:E_QUITT; Cycle:5;*)
		bResetRemVis : BOOL; (*reset remote from vis*) (*OldName:VIS_FQUITT; Cycle:5;*)
		iNumAlarmTest : DINT; (*number alarm test from vis*) (*OldName:NumAmmTest; Cycle:5;*)
		bAlarmTestStart : BOOL; (*alarm test start from vis*) (*OldName:SetAmmTestStart; Cycle:5;*)
		bAlarmTestStop : BOOL; (*alarm test stop from vis*) (*OldName:SetAmmTestStop; Cycle:5;*)
		bServiceBegin : BOOL; (*service mode*) (*OldName:bServiceBegin; Cycle:5;*)
		bMMD_GenAlarmTestStart : BOOL; (*MMD_Gen alarm test start from vis*) (*OldName:newPv; Cycle:5;*)
		bMMD_GenAlarmTestStop : BOOL; (*MMD_Gen alarm test stop from vis*) (*OldName:newPv; Cycle:5;*)
		bMMD_BB_AlarmTestStart : BOOL; (*MMD_BB alarm test start from vis*) (*OldName:newPv; Cycle:5;*)
		bMMD_BB_AlarmTestStop : BOOL; (*MMD_BB alarm test stop from vis*) (*OldName:newPv; Cycle:5;*)
	END_STRUCT;
	MM2VIS_Struct : 	STRUCT 
		bGnlTrip : BOOL; (*engine general trip*) (*OldName:M_SSTA; Cycle:5;*)
		bGnlTrip1 : BOOL; (*engine general trip 1*) (*OldName:M_SSTA1; Cycle:5;*)
		bGnlTrip2 : BOOL; (*engine general trip 2*) (*OldName:M_SSTA2; Cycle:5;*)
		bGnlTrip3 : BOOL; (*engine general trip 3*) (*OldName:M_SSTA3; Cycle:5;*)
		bGnlWarning : BOOL; (*engine general warning*) (*OldName:M_SSTW; Cycle:5;*)
		bTriptype1 : BOOL; (*triptype*) (*OldName:triptype_1; Cycle:5;*)
		bTriptype2 : BOOL; (*triptype*) (*OldName:triptype_2; Cycle:5;*)
		bTriptype3 : BOOL; (*triptype*) (*OldName:triptype_3; Cycle:5;*)
		bTriptypeS : BOOL; (*triptype*) (*OldName:RUHE; Cycle:5;*)
		bGnlTripDurEngOp : BOOL; (*engine general trip during engine operation*) (*OldName:newPv; Cycle:5;*)
		bAlarmTestEnable : BOOL; (*alarm test enable*) (*OldName:AmmTestEnable; Cycle:5;*)
		bNumAmmTestValid : BOOL; (*number alarm test valid*) (*OldName:NumAmmTestValid; Cycle:5;*)
		bAlarmTestOn : BOOL; (*alarm test On*) (*OldName:AmmTestOn; Cycle:5;*)
		iAlarmTestRestTime : INT; (*alarm test rest time [s]*) (*OldName:AmmTestRestTime; Cycle:5;*)
		bMMD_GenAlarmTestEnable : BOOL; (*MMD_Gen alarm test enable*) (*OldName:newPv; Cycle:5;*)
		bMMD_GenAlarmTestOn : BOOL; (*MMD_Gen alarm test On*) (*OldName:newPv; Cycle:5;*)
		iMMD_GenAlarmTestRestTime : INT; (*MMD_Gen alarm test rest time [s]*) (*OldName:newPv; Cycle:5;*)
		bMMD_BB_AlarmTestEnable : BOOL; (*MMD_BB alarm test enable*) (*OldName:newPv; Cycle:5;*)
		bMMD_BB_AlarmTestOn : BOOL; (*MMD_BB alarm test On*) (*OldName:newPv; Cycle:5;*)
		iMMD_BB_AlarmTestRestTime : INT; (*MMD_BB alarm test rest time [s]*) (*OldName:newPv; Cycle:5;*)
		bMsg1239 : BOOL; (*engine general trip*) (*OldName:M_SSTA; Cycle:5;*)
		bMsg1240 : BOOL; (*engine general warning*) (*OldName:M_SSTW; Cycle:5;*)
		bMsg1253 : BOOL; (*warm restart*) (*OldName:WARMSTART; Cycle:5;*)
		bMsg1254 : BOOL; (*cold restart*) (*OldName:KALTSTART; Cycle:5;*)
		bMsg1256 : BOOL; (*reset*) (*OldName:RM_QUITT; Cycle:5;*)
		bMsg3003 : BOOL; (*signal failure( 2101 or 2102 or 2103 or 2104 or 3152 > 24h)*) (*OldName:M_MS; Cycle:5;*)
		bMsg3252 : BOOL; (*remote reset*) (*OldName:T_FQUITT; Cycle:5;*)
		bMsg9389 : BOOL; (* W9389 Remote acknowledgement not possible, too many or safety trip *)
	END_STRUCT;
END_TYPE
