
TYPE
	IN_EM_Struct : 	STRUCT 
		bAMM_T_Ch_T1LP_Avg : BOOL; (*collective warning - average charge temp. before low-pressure TC (= engine intake air)*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		bAMM_T_EGaHPTC_Avg : BOOL; (*exhaust gas temperature after high pressure turbo charger - average not valid*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		bAMM_T_EGaLPTC_Avg : BOOL; (*exhaust gas temperature after low pressure turbo charger - average not valid*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		bAMM_T_EGaTC : BOOL; (*exhaust gas temperature after turbo charger - signal not valid*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		bAMM_T_EGbHPTC_Avg : BOOL; (*exhaust gas temperature before high pressure turbo charger - average not valid*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		bAMM_T_EGbTC : BOOL; (*exhaust gas temperature before turbo charger - signal not valid*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		bESC_enable : BOOL; (*emissions supervisory controller enabled *) (*OldName: new PV; Cycle:5*) (*V04.05.06.00*)
		bLeanOut_H2 : BOOL; (*Active lean out of engine via H2 content *) (*OldName: new PV; Cycle:5*) (*V04.12.00.00*)
		bLp_c_Enable : BOOL; (*LEANOX point at low load enabled*) (*OldName: new PV; Cycle:5*) (*V04.11.00.00*)
		bMsg1031 : BOOL; (*Safety loop - ermergency stop*) (*OldName: M_SIS; Cycle:5*) (*V04.05.00.00*)
		bMsg1054 : BOOL; (*fire alarm*) (*OldName: M_BAL; Cycle:5*) (*V04.07.00.00*)
		bPBC_Event_Misf : BOOL; (*PBCMem trigger for Misfire event *) (* OldName: new PV; Cycle:5; *) (*V04.07.01.00*)
		bScavFinished : BOOL; (*scavenging cycle finished  *) (*OldName: SPUEL_AB; Cycle:5*) (*V04.07.00.00*)
		bSCR_CemsExtCatOut_Rdy : BOOL; (*Validity of external customer CEMS signal at catalyst output*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		bServiceMode : BOOL; (*service mode*) (*OldName: bServiceBegin; Cycle: 5;*) (*V04.07.00.00*)
		bSimWinMOD_Active : BOOL; (*WinMOD simulation active *) (*OldName:new PV; Cycle:5*) (*V04.07.00.00*)
		bSkip_active : BOOL; (*Static skipfire from Gen2 is active *) (*OldName: new PV; Cycle:2*) (*V04.11.00.00*)
		iCAN_NOxS_IF1_us_ident : UDINT; (*User ident for NOx sensor CAN interface 1*) (*OldName: new PV; Cycle:2*) (*V04.05.00.00*)
		iCAN_NOxS_IF2_us_ident : UDINT; (*User ident for NOx sensor CAN interface 2*) (*OldName: new PV; Cycle:2*) (*V04.05.00.00*)
		iCAN_NOxS_IF3_us_ident : UDINT; (*User ident for NOx sensor CAN interface 3*) (*OldName: new PV; Cycle:2*) (*V04.14.00.00*)
		iCnt_OpHours : DINT; (*operating hours counter*) (*OldName: betrieb_h; Cycle: 5;*) (*V04.07.00.00*)
		iIdx_OMSS : INT; (*Operationg mode selection switch (0= OFF / 1=Hand / 2=Auto / 3=Test / 4=Spülen)*) (*OldName: BWS_HA; Cycle:5*) (*V04.05.00.00*)
		iModbus_SCR_INT : ARRAY[0..MODBUS_RTU_MASTER_MAX_ARRAY]OF INT; (*SCR Receive data via MODBUS - INTEGER (register 73,74,75)*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		iModbus_SCR_UINT : ARRAY[0..MODBUS_RTU_MASTER_MAX_ARRAY]OF UINT; (*SCR Receive data via MODBUS*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		iSt_OpMode : UDINT; (*Engine operation mode*) (*OldName: StopM; Cycle:5*) (*V04.05.00.00*)
		rCF_ESC_UreaNFlow : REAL; (*Urea controller gain correction factor send from ESC (-)*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		rCO_SCR_CemsExtCatOut : REAL; (*CO measured by external customer CEMS at catalyst output (ppm dry)*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		rH2_Mix : REAL; (*Hydrogen concentration volumetric for H2 compensation function after gas mixing [%]*) (*OldName: new PV; Cycle:5*) (*V04.12.00.00*)
		rHum_SCR_CemsExtCatOut : REAL; (*Exhaust water content measured by external customer CEMS at catalyst output [%]*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		rLam_Eng_LL_Set : REAL; (*Leanox Lambda set point*) (*OldName: ssPosGasmixerNominal / bp_y; Cycle:2*) (*V04.05.00.00*)
		rNFlow_ESC_UreaOffs : REAL; (*Urea controller offset from ESC (l/h)*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		rNH3_SCR_CemsExtCatOut : REAL; (*NH3 measured by external customer CEMS at catalyst output (ppm dry)*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		rNO2_SCR_CemsExtCatOut : REAL; (*NO2 measured by external customer CEMS at catalyst output (ppm dry)*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		rNOx_ESC_CatOut_Set : REAL; (*Reference NOx at SCR output from  ESC (ppm)*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		rNO_SCR_CemsExtCatOut : REAL; (*NO measured by external customer CEMS at catalyst output (ppm dry)*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		rN_EngAct : REAL; (*Engine speed actual (1/min)*) (*OldName: n_ist; Cycle:5*) (*V04.05.00.00*)
		rO2_SCR_CemsExtCatOut : REAL; (*O2 measured by external customer CEMS at catalyst output [Vol-%]*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		rP_Act_Norm_Filt : REAL; (*Actual power related to rP_Nom [%Pnom] filtered T=1s*) (*OldName: P_IST_PROM; Cycle:5*) (*V04.05.00.00*)
		rP_Set_Min_Norm : REAL; (*Minimal power setpoint related to rP_nom p.u.*) (*OldName: p_min; Cycle:2*) (*V04.13.00.00*)
		rP_Nom : REAL; (*nominal electric power [KW], depends on gastype *) (*OldName:PN_GASART;Cycle:2;*) (*V04.11.00.00*)
		rP_Set_Norm : REAL; (*power setpoint related to rP_Nom *) (*OldName:p_soll;Cycle:2;*) (*V04.11.00.00*)
		rT_Ch_T1LP_Avg : REAL; (*Average charge temperature before low-pressure turbocharger (= engine intake air) [°C]*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		rT_EGaHPTC_Avg : REAL; (*exhaust gas temperature after high pressure turbo charger - average*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		rT_EGaLPTC_Avg : REAL; (*exhaust gas temperature after low pressure turbo charger - average*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		rT_EGaTC : REAL; (*exhaust gas temperature after turbo charger*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		rT_EGbHPTC_Avg : REAL; (*exhaust gas temperature before high pressure turbo charger - average*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		rT_EGbTC : REAL; (*exhaust gas temperature after turbo charger*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		rT_EG_Avg : REAL; (*Cylinder temperature average [°C] *) (*OldName: ZYL_AV; Cycle:2*) (*V04.05.00.00*)
		rVol_Ch_Engine_Norm : REAL; (*Normalized engine mixture volume flow [Nm3/h]*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		tAB2EM : AmmBase2MM; (*AMM structure*) (*OldName: new PV; Cycle:5*)
		tCO_SCR_EMLine1 : HALioAi_Type; (*SCR Emission measurement line 1 - CO sensor [ppm] (P.02-JI-105)*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		tEmStop_SCR : HALioDi_Type; (*DI emergency stop push button - exhaust gas after treatment control panel (+SCR)*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		tEng_Run : HALioDo_Type; (*Engine in operation*) (*OldName: M_BTRB; Cycle:5*) (*V04.05.00.00*)
		tFlow_SCR_UreaDosingOut : HALioAi_Type; (*SCR Urea flow rate after dosing unit [l/h] (P.29-FI-001)*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		tFS_SCR_EMLine1_Lo : HALioDi_Type; (*SCR Emission measurement line 1 - flow rate minimum (FALSE = Error)(P.02-FS-101)*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		tFS_SCR_EMLine2_Lo : HALioDi_Type; (*SCR Emission measurement line 2 - flow rate minimum (FALSE = Error)(P.02-FS-102)*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		tGCB_On : HALioDi_Type; (*generator circuit breaker CLOSED*) (*OldName: GCB_ON; Cycle: 5;*) (*V04.07.01.00*)
		tLev_SCR_EMAir_Hi : HALioDi_Type; (*SCR Emission measurement air line - moisture maximum (TRUE = Error)(P.02-LS-103)*) (*OldName: new PV; Cycle:5*) (*V04.14.00.00*)
		tLev_SCR_EMLine1_Hi : HALioDi_Type; (*SCR Emission measurement line 1 - moisture maximum (TRUE = Error)(P.02-LS-101)*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		tLev_SCR_EMLine2_Hi : HALioDi_Type; (*SCR Emission measurement line 2 - moisture maximum (TRUE = Error)(P.02-LS-102)*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		tLev_SCR_UreaDosingCabinet_Hi : HALioDi_Type; (*SCR Leakage in urea dosing cabinet (FALSE = Error)(P.29-LS-002)*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		tLev_SCR_UreaTank : HALioAi_Type; (*SCR Urea tank level [%] (P.29-LI-001)*) (*OldName: new PV; Cycle:5*) (*V04.13.00.00*)
		tLev_SCR_UreaTank_Lo : HALioDi_Type; (*SCR Urea tank level minimum (FALSE = Error)(P.29-LS-001)*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		tLL : _tLL_Struct; (*Leanox line for all gas types, including interpolation *) (*OldName: new PV; Cycle:5*) (*V04.11.00.00*)
		tNO2_SCR_EMLine1 : HALioAi_Type; (*SCR Emission measurement line 1 - NO2 sensor [ppm] (P.02-JI-103)*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		tNO2_SCR_EMLine2 : HALioAi_Type; (*SCR Emission measurement line 2 - NO2 sensor [ppm] (P.02-JI-104)*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		tNO_SCR_EMLine1 : HALioAi_Type; (*SCR Emission measurement line 1 - NO sensor [ppm] (P.02-JI-101)*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		tNO_SCR_EMLine2 : HALioAi_Type; (*SCR Emission measurement line 2 - NO sensor [ppm] (P.02-JI-102)*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		tO2_SCR_EMLine1 : HALioAi_Type; (*SCR Emission measurement line 1 - O2 sensor [Vol-%] (P.02-JI-107)*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		tPB2MM : ParaBase2MM_type; (*Para structure*) (*OldName: new PV; Cycle:5*)
		tPr_SCR_CatIn : HALioAi_Type; (*SCR Exhaust pressure CAT inlet [bar] (P.02-PI-101)*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		tPr_SCR_CatOut : HALioAi_Type; (*SCR Exhaust pressure CAT outlet [bar] (P.02-PI-102)*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		tPr_SCR_ComprAirSupply : HALioAi_Type; (*SCR Compressed air supply pressure urea injection [bar] (P.32-PI-010)*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		tPr_SCR_UreaDosingIn : HALioAi_Type; (*SCR Urea pressure before dosing unit [bar] (P.29-PI-002)*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		tPr_SCR_UreaDosingOut : HALioAi_Type; (*SCR Urea pressure after dosing unit [bar] (P.29-PI-001)*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		tSCR_AirCompressor_Rdy : HALioDi_Type; (*SCR Air compressor urea injection - power supply ready(= TRUE) (P.32-VT-010)*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		tSCR_Catalyst_Rdy : HALioDi_Type; (*SCR Catalyst ready - from customer (Ready = TRUE)*) (*OldName: new PV; Cycle: 5;*) (*V04.07.00.00*)
		tSCR_ComprAirValve_Rdy : HALioDi_Type; (*SCR Compressed air valve urea injection - power supply ready(= TRUE) (P.32-YCS-010)*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		tSCR_DosingExt_On : HALioDi_Type; (*SCR External dosing on - from customer (TRUE = On)*) (*OldName: new PV; Cycle: 5;*) (*V04.09.00.00*)
		tSCR_EMCooler_Rdy : HALioDi_Type; (*SCR Emission measurement sample gas cooler - ready(= TRUE) (P.02-TS-101)*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		tSCR_EMPump1_Rdy : HALioDi_Type; (*SCR Emission measurement line 1 - sample gas pump ready(= TRUE) (P.02-P-101)*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		tSCR_EMPump2_Rdy : HALioDi_Type; (*SCR Emission measurement line 2 - sample gas pump ready(= TRUE) (P.02-P-102)*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		tSCR_InjectValve_Air : HALioDi_Type; (*SCR Urea/Air injection valve - air opened (P.29-YCS-001)*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		tSCR_InjectValve_Opened : HALioDi_Type; (*SCR Urea/Air injection valve - opened (P.29-YCS-001)*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		tSCR_InjectValve_Urea : HALioDi_Type; (*SCR Urea/Air injection valve - urea opened (P.29-YCS-001)*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		tSCR_UreaDosingPump2_Rdy : HALioDi_Type; (*SCR Urea dosing pump redundant - ready(= TRUE) (P.29-P-003)*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		tSCR_UreaDosingPump_Rdy : HALioDi_Type; (*SCR Urea dosing pump - ready(= TRUE) (P.29-P-001)*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		tSCR_UreaSupplyPump_Op : HALioDi_Type; (*SCR Urea supply pump operating(= TRUE) (P.29-P-002)*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		tSCR_ValvePowerSupply_Ok : HALioDi_Type; (*SCR Power supply to the valves on(= TRUE)*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		tT_AirIn : HALioAi_Type; (* AI: intake air temperature of humidity sensor [°C]*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		tT_EGaCat : HALioAi_Type; (*OXIcat Outlet temperature (P.02-TI-047)*) (*OldName: NKAT_WE; Cycle: 5*) (*V04.11.00.00*)
		tT_EGbCat : HALioAi_Type; (*OXIcat Inlet temperature (P.02-TI-046)*) (*OldName: VKAT_WE; Cycle: 5*) (*V04.11.00.00*)
		tT_SCR_CatIn : HALioAi_Type; (*SCR Exhaust temperature CAT inlet [°C] (P.02-TI-101)*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		tT_SCR_CatOut : HALioAi_Type; (*SCR Exhaust temperature CAT outlet [°C] (P.02-TI-102)*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		tT_SCR_Cat_HiHi : HALioDi_Type; (*SCR Exhaust temperatures CAT maximum - from customer (OK = TRUE)*) (*OldName: new PV; Cycle: 5;*) (*V04.07.00.00*)
	END_STRUCT;
	OUT_EM_Struct : 	STRUCT 
		bAMM_NOx_NOxS_EngOut_Avg : BOOL; (*collective warning for NOx average value from NOx sensor at engine outlet position*) (*OldName: new PV; Cycle:5*) (*V04.07.00.00*)
		bAMM_O2_NOxS_EngOut_Avg : BOOL; (*collective warning for O2 average value from NOx sensor at engine outlet position*) (*OldName: new PV; Cycle:5*) (*V04.07.00.00*)
		bRel_SCR_UDC : BOOL; (*SCR Release urea dosing controller (UDC)*) (*OldName: new PV; Cycle:5*) (*V04.05.06.00*)
		bSCR_NH3SlipDetected : BOOL; (*NH3 slip out of SCR catalyst detected*) (*OldName: new PV; Cycle:5*) (*V04.05.05.00*)
		bSCR_SDB_EmStop : BOOL; (*INPUT from smart dosing box (SDB): Emergency stop push button - exhaust gas after treatment control panel (+SCR)*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		iModbus_SCR : ARRAY[0..MODBUS_RTU_MASTER_MAX_ARRAY]OF UINT; (*SCR Send data via MODBUS*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		rNOx_Em_CatOut_Set : REAL; (*NOx emissions at CAT outlet - setpoint [ppm]*) (*OldName: new PV; Cycle:5*) (*V04.07.00.00*)
		rNOx_Em_EngOut_Set : REAL; (*NOx emissions at engine outlet - setpoint [ppm]*) (*OldName: new PV; Cycle:5*) (*V04.07.00.00*)
		rNOx_NOxS_CatOut_cor : REAL; (*NOx sensor at catalyst outlet - actual NOx value with offset and CEMS correction [ppm]*) (*OldName: new PV; Cycle:5*) (*V04.05.01.00*)
		rNOx_NOxS_EngOut_Avg : REAL; (*NOx average value from NOx sensor at engine outlet position [ppm]*) (*OldName: new PV; Cycle:5*) (*V04.05.01.00*)
		rNOx_NOxS_EngOut_mg_Avg : REAL; (*NOx average value from NOx sensor at engine outlet position [mg/Nm3]*) (*OldName: new PV; Cycle:5*) (*V04.07.00.00*)
		rO2_NOxS_EngOut_Avg : REAL; (*O2 average value from NOx sensor at engine outlet position [Vol%]*) (*OldName: new PV; Cycle:5*) (*V04.07.00.00*)
		tEM2AB : MM2AmmBase; (*AMM structure*) (*OldName: new PV; Cycle:5*)
		tEM2PB : MM2ParaBase_type; (*Para structure*) (*OldName: new PV; Cycle:5*)
		tPc_SCR_UreaDosingPump_Set : HALioAo_Type; (*SCR Urea dosing pump - set point [%] (P.29-P-001 / P.29-P-003)*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		tPos_SCR_UreaDosingValve2_Set : HALioAo_Type; (*SCR Urea dosing valve redundant - set position [%] (P.29-YCI-002)*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		tPos_SCR_UreaDosingValve_Set : HALioAo_Type; (*SCR Urea dosing valve - set position [%] (P.29-YCI-001)*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		tSCR_AirCompressor_Dem : HALioDo_Type; (*SCR Air compressor demand (P.32-VT-010)*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		tSCR_Aux_Dem : HALioDo_Type; (*SCR Auxiliaries demand*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		tSCR_ComprAirValve_Dem : HALioDo_Type; (*SCR Compressed air valve urea injection - demand (P.32-YCS-010)*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		tSCR_EMPump1_Dem : HALioDo_Type; (*SCR Emission measurement line 1 - sample gas pump demand (P.02-P-101)*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		tSCR_EMPump2_Dem : HALioDo_Type; (*SCR Emission measurement line 2 - sample gas pump demand (P.02-P-102)*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		tSCR_EMValve1_CG_Dem : HALioDo_Type; (*SCR Emission measurement line 1 - calibration/sample gas switch valve (FALSE = sample gas) (P.02-YCS-105)*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		tSCR_EMValve1_SGbCat_Dem : HALioDo_Type; (*SCR Emission measurement line 1 - bevor/after CAT sample gas switch valve (FALSE = after CAT) (P.02-YCS-101)*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		tSCR_EMValve1_SGbOxi_Dem : HALioDo_Type; (*SCR Emission measurement line 1 - before/after OXI sample gas switch valve (FALSE = after OXI = after CAT) (P.02-YCS-102)*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		tSCR_EMValve1_SG_Dem : HALioDo_Type; (*SCR Emission measurement line 1 - air/sample gas switch valve (FALSE = air) (P.02-YCS-103)*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		tSCR_EMValve2_CG_Dem : HALioDo_Type; (*SCR Emission measurement line 2 - calibration/sample gas switch valve (FALSE = sample gas) (P.02-YCS-106)*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		tSCR_EMValve2_SG_Dem : HALioDo_Type; (*SCR Emission measurement line 2 - air/sample gas switch valve (FALSE = air) (P.02-YCS-104)*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		tSCR_IndicatorLight : HALioDo_Type; (*SCR Indicator light demand*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		tSCR_InjectValve_Open_Dem : HALioDo_Type; (*SCR Urea/Air injection valve - open demand (P.29-YCS-001)*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		tSCR_InjectValve_Urea_Dem : HALioDo_Type; (*SCR Urea/Air injection valve - urea demand (P.29-YCS-001)*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		tSCR_UreaDosingPump2_Dem : HALioDo_Type; (*SCR Urea dosing pump redundant - demand (P.29-P-003)*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		tSCR_UreaDosingPump_Dem : HALioDo_Type; (*SCR Urea dosing pump - demand (P.29-P-001)*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		tSCR_UreaDosingPump_Reset : HALioDo_Type; (*SCR Urea dosing pump - FC reset demand (P.29-P-001)*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		tSCR_UreaDosingValve2_Dem : HALioDo_Type; (*SCR Urea dosing valve redundant - demand (P.29-YCI-002)*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		tSCR_UreaDosingValve_Dem : HALioDo_Type; (*SCR Urea dosing valve - demand (P.29-YCI-001)*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		tSCR_UreaSupplyPump_Dem : HALioDo_Type; (*SCR Urea supply pump demand (P.29-P-002)*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		bAMM_Lev_EMAir : BOOL; (*Warning - SCR Emission measurement air line - moisture maximum [W]*)
	END_STRUCT;
	VIS2MM_Struct : 	STRUCT 
		bNOxS_CatOut_DiagActive : BOOL; (*NOx sensor at catalyst outlet - Activation self-diagnosis*) (*OldName: new PV; Cycle:5*) (*V04.07.00.00*)
		bNOxS_CatOut_DiagStart : BOOL; (*NOx sensor at catalyst outlet - Start self-diagnosis*) (*OldName: new PV; Cycle:5*) (*V04.07.00.00*)
		bNOxS_EngOut_A_DiagActive : BOOL; (*NOx sensor at engine outlet bank A - Activation self-diagnosis*) (*OldName: new PV; Cycle:5*) (*V04.07.00.00*)
		bNOxS_EngOut_A_DiagStart : BOOL; (*NOx sensor at engine outlet bank A - Start self-diagnosis*) (*OldName: new PV; Cycle:5*) (*V04.07.00.00*)
		bNOxS_EngOut_B_DiagActive : BOOL; (*NOx sensor at engine outlet bank B - Activation self-diagnosis*) (*OldName: new PV; Cycle:5*) (*V04.07.00.00*)
		bNOxS_EngOut_B_DiagStart : BOOL; (*NOx sensor at engine outlet bank B - Start self-diagnosis*) (*OldName: new PV; Cycle:5*) (*V04.07.00.00*)
		bNOxS_EngOut_DiagActive : BOOL; (*NOx sensor at engine outlet - Activation self-diagnosis*) (*OldName: new PV; Cycle:5*) (*V04.07.00.00*)
		bNOxS_EngOut_DiagStart : BOOL; (*NOx sensor at engine outlet - Start self-diagnosis*) (*OldName: new PV; Cycle:5*) (*V04.07.00.00*)
		bSCR_ComprAirSupply_DemMan : BOOL; (*SCR Compressed air valve urea injection - manual demand*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		bSCR_EMPump1_DemMan : BOOL; (*SCR Emission measurement line 1 - sample gas pump - manual demand*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		bSCR_EMPump2_DemMan : BOOL; (*SCR Emission measurement line 2 - sample gas pump - manual demand*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		bSCR_EMValve1_CG_DemMan : BOOL; (*SCR Emission measurement line 1 - calibration/sample gas switch valve (FALSE = sample gas) - manual demand*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		bSCR_EMValve1_SGbCat_DemMan : BOOL; (*SCR Emission measurement line 1 - bevor/after CAT sample gas switch valve (FALSE = after CAT) - manual demand*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		bSCR_EMValve1_SGbOxi_DemMan : BOOL; (*SCR Emission measurement line 1 - before/after OXI sample gas switch valve (FALSE = after OXI = after CAT) - manual demand*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		bSCR_EMValve1_SG_DemMan : BOOL; (*SCR Emission measurement line 1 - air/sample gas switch valve (FALSE = air) - manual demand*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		bSCR_EMValve2_CG_DemMan : BOOL; (*SCR Emission measurement line 2 - calibration/sample gas switch valve (FALSE = sample gas) - manual demand*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		bSCR_EMValve2_SG_DemMan : BOOL; (*SCR Emission measurement line 2 - air/sample gas switch valve (FALSE = air) - manual demand*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		bSCR_InjectValve_Open_DemMan : BOOL; (*SCR Urea/Air injection valve - open - manual demand*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		bSCR_InjectValve_Urea_DemMan : BOOL; (*SCR Urea/Air injection valve - urea - manual demand*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		bSCR_Man : BOOL; (*SCR Button: SCR - man/auto*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		bSCR_NOxControl_Man : BOOL; (*SCR Button: NOx controller - man/auto*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		bSCR_UreaDosingPump2_DemMan : BOOL; (*SCR Urea dosing pump redundant - manual demand*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		bSCR_UreaDosingPump_DemMan : BOOL; (*SCR Urea dosing pump - manual demand*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		bSCR_UreaDosingUnit2_Active : BOOL; (*SCR Button: Switch between dosing unit and redundant dosing unit*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		bSCR_UreaDosingUnit2_Blocked : BOOL; (*SCR Urea dosing unit redundant - Blocked*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		bSCR_UreaDosingUnit_Blocked : BOOL; (*SCR Urea dosing unit - Blocked*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		bSCR_UreaDosingUnit_Man : BOOL; (*SCR Button: Urea dosing unit - man/auto*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		bSCR_UreaSupplyPump_DemMan : BOOL; (*SCR Urea supply pump - manual demand*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		iCnt_NOx_Em_MonLim_Exc : DINT; (*Duration of NOx emission tolerance exceedance (Dauer der Emissionstoleranzüberschreitung) [h]*) (*OldName: new PV; Cycle:5*) (*V04.07.00.00*)
		iCnt_SCR_AirCompressorMaint : DINT; (*SCR Air compressor - maintenance counter [h]*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		iCnt_SCR_UreaDosingUnitMaint : DINT; (*SCR Urea dosing unit - maintenance counter [h]*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		iCnt_SCR_UreaDosingUnitMaint2 : DINT; (*SCR Urea dosing unit redundant - maintenance counter [h]*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		iOpH_SCR_AirCompressor : UDINT; (*SCR Air compressor - total operation hours [h]*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		iOpH_SCR_UreaDosingUnit : UDINT; (*SCR Urea dosing unit - total operation hours [h]*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		iOpH_SCR_UreaDosingUnit2 : UDINT; (*SCR Urea dosing unit redundant - total operation hours [h]*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		rFlow_SCR_UreaDosingUnit_spMan : REAL; (*SCR NOx controller - y-Total & manual setpoint (= setpoint for flow controller) [l/h]*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		rPc_SCR_UreaDosingUnit_spMan : REAL; (*SCR Urea dosing unit - y-Total & manual setpoint [%]*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		rVol_SCR_UreaConsumption : LREAL; (*SCR Urea consumption over lifetime [l]*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
	END_STRUCT;
	MM2VIS_Struct : 	STRUCT 
		bAMM_NOx_NOxS_EngOut_Avg : BOOL; (*collective warning for NOx average value from NOx sensor at engine outlet position*) (*OldName: new PV; Cycle:5*) (*V04.07.00.00*)
		bAMM_O2_NOxS_EngOut_Avg : BOOL; (*collective warning for O2 average value from NOx sensor at engine outlet position*) (*OldName: new PV; Cycle:5*) (*V04.07.00.00*)
		bEngineSteadyState : BOOL; (*SCR Engine in steady state mode*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		bLev_SCR_UreaDosingCabinet_Hi : BOOL; (*SCR Leakage in urea dosing cabinet (FALSE = Error)*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		bLev_SCR_UreaTank_Lo : BOOL; (*SCR Urea tank level minimum (FALSE = Error)*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		bMsg2276 : BOOL; (*NOx Deviation --> canceled with V04.05.00.00*) (*OldName: new PV; Cycle:5*)
		bMsg2446 : BOOL; (*SCR BUS communication interrupted*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		bMsg2447 : BOOL; (*SCR Measuring signal failure urea pressure before dosing*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		bMsg2448 : BOOL; (*SCR Urea pressure before dosing minimum*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		bMsg2449 : BOOL; (*SCR Urea pressure before dosing maximum*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		bMsg2450 : BOOL; (*SCR Leakage in urea dosing cabinet*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		bMsg2451 : BOOL; (*SCR Urea dosing valve - error*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		bMsg2452 : BOOL; (*SCR Measuring signal failure urea flow rate after dosing*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		bMsg2453 : BOOL; (*SCR Urea flow rate - valve characteristic deviating maximum*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		bMsg2454 : BOOL; (*SCR Compressed air supply pressure urea injection maximum*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		bMsg2455 : BOOL; (*SCR Deviation to continous emission monitoring system maximum*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		bMsg2456 : BOOL; (*SCR Emission measurement line 1 - O2 maximum*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		bMsg2457 : BOOL; (*SCR Measuring signal failure emission measurement line 1 - O2 sensor*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		bMsg2458 : BOOL; (*SCR Measuring signal failure emission measurement line 2 - NO2 sensor*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		bMsg2464 : BOOL; (*SCR Urea dosing unit (external) - error*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		bMsg2607 : BOOL; (*CAN failure - NOx sensor CAN interface 1*) (*OldName: new PV; Cycle:5*)
		bMsg2609 : BOOL; (*CAN failure - NOx sensor CAN interface 2*) (*OldName: new PV; Cycle:5*)
		bMsg2610 : BOOL; (*No connection to the sensor - NOx sensor engine out*) (*OldName: new PV; Cycle:5*)
		bMsg2697 : BOOL; (*SCR Urea dosing unit - maintenance needed*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		bMsg2766 : BOOL; (*Catalyst temperature minimum*) (*OldName: new PV; Cycle:5*) (*V04.11.00.00*)
		bMsg2769 : BOOL; (*SCR Emission measurement air line - moisture maximum*) (*OldName: new PV; Cycle:5*) (*V04.14.00.00*)
		bMsg2877 : BOOL; (*SCR Exhaust after treatment (SCR) deactivated --> canceled with V04.05.00.00*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		bMsg2878 : BOOL; (*SCR Urea dosing activated*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		bMsg2879 : BOOL; (*SCR Urea dosing deactivated*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		bMsg2884 : BOOL; (*SCR Manual mode on*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		bMsg2885 : BOOL; (*SCR Manual mode off*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		bMsg2923 : BOOL; (*SCR NH3 slip detection started*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		bMsg2924 : BOOL; (*SCR NH3 slip detection completed*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		bMsg2971 : BOOL; (*Error during self-diagnosis - NOx sensor engine out*) (*OldName: new PV; Cycle:5*) (*V04.07.00.00*)
		bMsg2974 : BOOL; (*Error during self-diagnosis - NOx sensor engine out A*) (*OldName: new PV; Cycle:5*) (*V04.07.00.00*)
		bMsg2977 : BOOL; (*Error during self-diagnosis - NOx sensor engine out B*) (*OldName: new PV; Cycle:5*) (*V04.07.00.00*)
		bMsg2980 : BOOL; (*Error during self-diagnosis - NOx sensor CAT out*) (*OldName: new PV; Cycle:5*) (*V04.07.00.00*)
		bMsg3379 : BOOL; (*SCR Exhaust temperatures CAT maximum*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		bMsg3380 : BOOL; (*SCR CO emission average maximum --> canceled with V04.07*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		bMsg3381 : BOOL; (*NOx emissions - short-term average high*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		bMsg3383 : BOOL; (*SCR Measuring signal failure exhaust temperatures CAT*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		bMsg3450 : BOOL; (*SCR Group alarm - exhaust after treatment system --> canceled with V04.05.00.00*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		bMsg3451 : BOOL; (*SCR Power supply to the valves interrupted*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		bMsg3452 : BOOL; (*SCR Measuring signal failure urea pressure after dosing*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		bMsg3453 : BOOL; (*SCR Urea pressure after dosing maximum*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		bMsg3454 : BOOL; (*SCR Urea pressure after dosing minimum*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		bMsg3455 : BOOL; (*SCR Urea flow rate after dosing maximum*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		bMsg3456 : BOOL; (*SCR Urea dosing pump - error*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		bMsg3457 : BOOL; (*SCR Urea-air valve blocked*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		bMsg3458 : BOOL; (*SCR Urea tank level minimum*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		bMsg3459 : BOOL; (*SCR Urea tank level minimum - dosing deactivated*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		bMsg3460 : BOOL; (*SCR Urea supply pump not operating*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		bMsg3461 : BOOL; (*SCR Measuring signal failure compressed air supply pressure urea injection*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		bMsg3462 : BOOL; (*SCR Compressed air supply pressure urea injection minimum*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		bMsg3463 : BOOL; (*SCR Compressed air valve urea injection power supply interrupted*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		bMsg3464 : BOOL; (*SCR Measuring signal failure exhaust pressure CAT inlet*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		bMsg3465 : BOOL; (*SCR Measuring signal failure exhaust pressure CAT outlet*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		bMsg3466 : BOOL; (*SCR Measuring signal failure exhaust temperature CAT inlet*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		bMsg3467 : BOOL; (*SCR Measuring signal failure exhaust temperature CAT outlet*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		bMsg3469 : BOOL; (*SCR Exhaust differential pressure CAT maximum*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		bMsg3470 : BOOL; (*SCR Emission measurement sample gas cooler - error*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		bMsg3471 : BOOL; (*SCR Emission measurement line 1 - sample gas pump not ready*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		bMsg3472 : BOOL; (*SCR Emission measurement line 2 - sample gas pump not ready*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		bMsg3473 : BOOL; (*SCR Emission measurement line 1 - moisture maximum*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		bMsg3474 : BOOL; (*SCR Emission measurement line 2 - moisture maximum*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		bMsg3475 : BOOL; (*SCR Emission measurement line 1 - flow rate minimum*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		bMsg3476 : BOOL; (*SCR Emission measurement line 2 - flow rate minimum*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		bMsg3477 : BOOL; (*SCR Measuring signal failure emission measurement line 2 - NO sensor*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		bMsg3478 : BOOL; (*SCR Measuring signal failure emission measurement line 1 - NO sensor*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		bMsg3479 : BOOL; (*SCR Measuring signal failure emission measurement line 1 - NO2 sensor*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		bMsg3480 : BOOL; (*SCR NH3 slip detection deactivated*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		bMsg3481 : BOOL; (*SCR Measuring signal failure emission measurement line 1 - CO sensor*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		bMsg3482 : BOOL; (*SCR NOx emission to check --> canceled with V04.07*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		bMsg3483 : BOOL; (*SCR CO emission to check --> canceled with V04.07*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		bMsg3484 : BOOL; (*CO emissions - short-term average high*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		bMsg3485 : BOOL; (*NOx emissions - short-term average high*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		bMsg3486 : BOOL; (*SCR Urea flow rate after dosing minimum*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		bMsg3487 : BOOL; (*SCR Exhaust temperature CAT inlet maximum*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		bMsg3488 : BOOL; (*SCR Exhaust temperature CAT outlet maximum*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		bMsg3489 : BOOL; (*SCR Emergency Stop SCR control cabinet --> canceled with V04.05.00.00*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		bMsg9077 : BOOL; (*SCR NH3 slip detection interrupted*) (*OldName: new PV; Cycle:5*) (*V04.13.00.00*)
		bMsg9079 : BOOL; (*SCR Urea dosing - dosing conditions reached*) (*OldName: new PV; Cycle:5*) (*V04.13.00.00*)
		bMsg9080 : BOOL; (*SCR Urea dosing - dosing conditions ended*) (*OldName: new PV; Cycle:5*) (*V04.13.00.00*)
		bMsg9081 : BOOL; (*SCR Urea dosing - requested*) (*OldName: new PV; Cycle:5*) (*V04.13.00.00*)
		bMsg9082 : BOOL; (*SCR Urea dosing - unrequested*) (*OldName: new PV; Cycle:5*) (*V04.13.00.00*)
		bMsg9201 : BOOL; (*Measuring signal failure O2, NOx sensor engine out*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		bMsg9202 : BOOL; (*Measuring signal failure NOx, NOx sensor engine out*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		bMsg9203 : BOOL; (*No connection to the sensor - NOx sensor engine out A*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		bMsg9204 : BOOL; (*Measuring signal failure O2, NOx sensor engine out – bank A*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		bMsg9205 : BOOL; (*Measuring signal failure NOx, NOx sensor engine out – bank A*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		bMsg9206 : BOOL; (*No connection to the sensor - NOx sensor engine out B*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		bMsg9207 : BOOL; (*Measuring signal failure O2, NOx sensor engine out – bank B*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		bMsg9208 : BOOL; (*Measuring signal failure NOx, NOx sensor engine out – bank B*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		bMsg9209 : BOOL; (*No connection to the sensor - NOx sensor CAT out*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		bMsg9210 : BOOL; (*Measuring signal failure O2, NOx sensor CAT out*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		bMsg9211 : BOOL; (*Measuring signal failure NOx, NOx sensor CAT out*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		bMsg9212 : BOOL; (*SCR Air compressor - maintenance needed *) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		bMsg9233 : BOOL; (*Lifetime reached - NOx sensor engine out*) (*OldName: new PV; Cycle:5*) (*V04.07.00.00*)
		bMsg9234 : BOOL; (*Lifetime reached - NOx sensor engine out A*) (*OldName: new PV; Cycle:5*) (*V04.07.00.00*)
		bMsg9235 : BOOL; (*Lifetime reached - NOx sensor engine out B*) (*OldName: new PV; Cycle:5*) (*V04.07.00.00*)
		bMsg9236 : BOOL; (*Lifetime reached - NOx sensor CAT out*) (*OldName: new PV; Cycle:5*) (*V04.07.00.00*)
		bMsg9250 : BOOL; (*O2 deviation bank A/B maximum - NOx sensor engine out*) (*OldName: new PV; Cycle:5*) (*V04.07.00.00*)
		bMsg9251 : BOOL; (*NOx deviation bank A/B maximum - NOx sensor engine out*) (*OldName: new PV; Cycle:5*) (*V04.07.00.00*)
		bMsg9252 : BOOL; (*NOx emissions - daily average high*) (*OldName: new PV; Cycle:5*) (*V04.07.00.00*)
		bMsg9277 : BOOL; (*SCR Urea dosing stopped - error*) (*OldName: new PV; Cycle:5*) (*V04.07.00.00*)
		bMsg9278 : BOOL; (*SCR Catalyst - failure*) (*OldName: new PV; Cycle:5*) (*V04.07.00.00*)
		bMsg9379 : BOOL; (*SCR Measuring signal failure urea tank level*) (*OldName: new PV; Cycle:5*) (*V04.13.00.00*)
		bMsg9380 : BOOL; (*SCR Urea flow dosing error*) (*OldName: new PV; Cycle:5*) (*V04.13.00.00*)
		bNOxS_CatOut_Active : BOOL; (*NOx sensor at catalyst outlet - Activation status *) (*OldName: new PV; Cycle:5*) (*V04.07.00.00*)
		bNOxS_CatOut_CAN_Ok : BOOL; (*NOx sensor at catalyst outlet - CAN connectivity status*) (*OldName: new PV; Cycle:5*) (*V04.07.00.00*)
		bNOxS_CatOut_Heater_Ok : BOOL; (*NOx sensor at catalyst outlet - Heater status*) (*OldName: new PV; Cycle:5*) (*V04.07.00.00*)
		bNOxS_CatOut_NOx_Ok : BOOL; (*NOx sensor at catalyst outlet - NOx status*) (*OldName: new PV; Cycle:5*) (*V04.07.00.00*)
		bNOxS_CatOut_NOx_Validity_Ok : BOOL; (*NOx sensor at catalyst outlet - NOx plausibility status*) (*OldName: new PV; Cycle:5*) (*V04.07.01.00*)
		bNOxS_CatOut_O2_Ok : BOOL; (*NOx sensor at catalyst outlet - O2 status*) (*OldName: new PV; Cycle:5*) (*V04.07.00.00*)
		bNOxS_CatOut_O2_Validity_Ok : BOOL; (*NOx sensor at catalyst outlet - O2 plausibility status*) (*OldName: new PV; Cycle:5*) (*V04.07.01.00*)
		bNOxS_CatOut_Power_Ok : BOOL; (*NOx sensor at catalyst outlet - Power status*) (*OldName: new PV; Cycle:5*) (*V04.07.00.00*)
		bNOxS_EngOut_Active : BOOL; (*NOx sensor at engine outlet - Activation status *) (*OldName: new PV; Cycle:5*) (*V04.07.00.00*)
		bNOxS_EngOut_A_Active : BOOL; (*NOx sensor at engine outlet bank A - Activation status *) (*OldName: new PV; Cycle:5*) (*V04.07.00.00*)
		bNOxS_EngOut_A_CAN_Ok : BOOL; (*NOx sensor at engine outlet bank A - CAN connectivity status*) (*OldName: new PV; Cycle:5*) (*V04.07.00.00*)
		bNOxS_EngOut_A_Heater_Ok : BOOL; (*NOx sensor at engine outlet bank A - Heater status*) (*OldName: new PV; Cycle:5*) (*V04.07.00.00*)
		bNOxS_EngOut_A_NOx_Ok : BOOL; (*NOx sensor at engine outlet bank A - NOx status*) (*OldName: new PV; Cycle:5*) (*V04.07.00.00*)
		bNOxS_EngOut_A_NOx_Validity_Ok : BOOL; (*NOx sensor at engine outlet bank A - NOx plausibility status*) (*OldName: new PV; Cycle:5*) (*V04.07.01.00*)
		bNOxS_EngOut_A_O2_Ok : BOOL; (*NOx sensor at engine outlet bank A - O2 status*) (*OldName: new PV; Cycle:5*) (*V04.07.00.00*)
		bNOxS_EngOut_A_O2_Validity_Ok : BOOL; (*NOx sensor at engine outlet bank A - O2 plausibility status*) (*OldName: new PV; Cycle:5*) (*V04.07.01.00*)
		bNOxS_EngOut_A_Power_Ok : BOOL; (*NOx sensor at engine outlet bank A - Power status*) (*OldName: new PV; Cycle:5*) (*V04.07.00.00*)
		bNOxS_EngOut_B_Active : BOOL; (*NOx sensor at engine outlet bank B - Activation status *) (*OldName: new PV; Cycle:5*) (*V04.07.00.00*)
		bNOxS_EngOut_B_CAN_Ok : BOOL; (*NOx sensor at engine outlet bank B - CAN connectivity status*) (*OldName: new PV; Cycle:5*) (*V04.07.00.00*)
		bNOxS_EngOut_B_Heater_Ok : BOOL; (*NOx sensor at engine outlet bank B - Heater status*) (*OldName: new PV; Cycle:5*) (*V04.07.00.00*)
		bNOxS_EngOut_B_NOx_Ok : BOOL; (*NOx sensor at engine outlet bank B - NOx status*) (*OldName: new PV; Cycle:5*) (*V04.07.00.00*)
		bNOxS_EngOut_B_NOx_Validity_Ok : BOOL; (*NOx sensor at engine outlet bank B - NOx plausibility status*) (*OldName: new PV; Cycle:5*) (*V04.07.01.00*)
		bNOxS_EngOut_B_O2_Ok : BOOL; (*NOx sensor at engine outlet bank B - O2 status*) (*OldName: new PV; Cycle:5*) (*V04.07.00.00*)
		bNOxS_EngOut_B_O2_Validity_Ok : BOOL; (*NOx sensor at engine outlet bank B - O2 plausibility status*) (*OldName: new PV; Cycle:5*) (*V04.07.01.00*)
		bNOxS_EngOut_B_Power_Ok : BOOL; (*NOx sensor at engine outlet bank B - Power status*) (*OldName: new PV; Cycle:5*) (*V04.07.00.00*)
		bNOxS_EngOut_CAN_Ok : BOOL; (*NOx sensor at engine outlet - CAN connectivity status*) (*OldName: new PV; Cycle:5*) (*V04.07.00.00*)
		bNOxS_EngOut_Heater_Ok : BOOL; (*NOx sensor at engine outlet - Heater status*) (*OldName: new PV; Cycle:5*) (*V04.07.00.00*)
		bNOxS_EngOut_NOx_Ok : BOOL; (*NOx sensor at engine outlet - NOx status*) (*OldName: new PV; Cycle:5*) (*V04.07.00.00*)
		bNOxS_EngOut_NOx_Validity_Ok : BOOL; (*NOx sensor at engine outlet - NOx plausibility status*) (*OldName: new PV; Cycle:5*) (*V04.07.01.00*)
		bNOxS_EngOut_O2_Ok : BOOL; (*NOx sensor at engine outlet - O2 status*) (*OldName: new PV; Cycle:5*) (*V04.07.00.00*)
		bNOxS_EngOut_O2_Validity_Ok : BOOL; (*NOx sensor at engine outlet - O2 plausibility status*) (*OldName: new PV; Cycle:5*) (*V04.07.01.00*)
		bNOxS_EngOut_Power_Ok : BOOL; (*NOx sensor at engine outlet - Power status*) (*OldName: new PV; Cycle:5*) (*V04.07.00.00*)
		bSCR_CemsExtCatOut_Rdy : BOOL; (*SCR Validity of external customer CEMS signal at catalyst output READY*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		bSCR_ComprAirSupply_Dem : BOOL; (*SCR Compressed air valve urea injection - demanded*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		bSCR_ComprAirValve_Exist : BOOL; (*SCR Compressed air valve exist*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		bSCR_EMCooler_Op : BOOL; (*SCR Emission measurement sample gas cooler - operating*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		bSCR_EMLine1_MsRdy : BOOL; (*SCR Emission measurement line 1 - ready for measuring*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		bSCR_EMLine2_MsRdy : BOOL; (*SCR Emission measurement line 2 - ready for measuring*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		bSCR_EMPump1_Op : BOOL; (*SCR Emission measurement line 1 - sample gas pump operating*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		bSCR_EMPump2_Op : BOOL; (*SCR Emission measurement line 2 - sample gas pump operating*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		bSCR_EMValve1_CG_Dem : BOOL; (*SCR Emission measurement line 1 - calibration/sample gas switch valve (FALSE = sample gas)*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		bSCR_EMValve1_SGbCat_Dem : BOOL; (*SCR Emission measurement line 1 - bevor/after CAT sample gas switch valve (FALSE = after CAT)*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		bSCR_EMValve1_SGbOxi_Dem : BOOL; (*SCR Emission measurement line 1 - before/after OXI sample gas switch valve (FALSE = after OXI = after CAT)*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		bSCR_EMValve1_SG_Dem : BOOL; (*SCR Emission measurement line 1 - air/sample gas switch valve (FALSE = air)*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		bSCR_EMValve2_CG_Dem : BOOL; (*SCR Emission measurement line 2 - calibration/sample gas switch valve (FALSE = sample gas)*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		bSCR_EMValve2_SG_Dem : BOOL; (*SCR Emission measurement line 2 - air/sample gas switch valve (FALSE = air)*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		bSCR_ExtEMAdjust_Run : BOOL; (*SCR External emission measurement fine adjustment active*) (*OldName: new PV; Cycle:5*) (*V04.05.01.00*)
		bSCR_InjectValve_3rdPos : BOOL; (*SCR Urea/Air injection valve - third position exist*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		bSCR_InjectValve_Air : BOOL; (*SCR Urea/Air injection valve - air opened*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		bSCR_InjectValve_Opened : BOOL; (*SCR Urea/Air injection valve - air or urea opened*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		bSCR_InjectValve_Open_Dem : BOOL; (*SCR Air/urea injection valve - open demand*) (*OldName: new PV; Cycle:5*) (*V04.13.00.00*)
		bSCR_InjectValve_Urea : BOOL; (*SCR Urea/Air injection valve - urea opened*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		bSCR_InjectValve_Urea_Dem : BOOL; (*SCR Air/urea injection valve - open urea demand*) (*OldName: new PV; Cycle:5*) (*V04.13.00.00*)
		bSCR_NH3SlipDetected : BOOL; (*SCR NH3 slip detected*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		bSCR_NOxCtrl_Active : BOOL; (*SCR NOx controller is active*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		bSCR_SDB_Err : ARRAY[0..48]OF BOOL; (*SCR Urea dosing unit (external smart dosing unit) - Error details linked to [W2464]*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		bSCR_UreaDosingPump2_Op : BOOL; (*SCR Urea dosing pump redundant - operating*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		bSCR_UreaDosingPump2_Rdy : BOOL; (*SCR Urea dosing pump redundant - ready (= TRUE)*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		bSCR_UreaDosingPump_Op : BOOL; (*SCR Urea dosing pump - operating*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		bSCR_UreaDosingPump_Rdy : BOOL; (*SCR Urea dosing pump - ready (= TRUE)*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		bSCR_UreaDosingValve2_Open : BOOL; (*SCR Urea dosing valve redundant - opened*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		bSCR_UreaDosingValve_Open : BOOL; (*SCR Urea dosing valve - opened*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		bSCR_UreaFlowCtrl_Active : BOOL; (*SCR Urea flow controller is active*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		bSCR_UreaSupplyPump_Op : BOOL; (*SCR Urea supply pump - operating*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		iCnt_NOxS_CatOut_LastDiag : DINT; (*NOx sensor at catalyst outlet - Last self-diagnosis [h]*) (*OldName: new PV; Cycle:5*) (*V04.07.00.00*)
		iCnt_NOxS_EngOut_A_LastDiag : DINT; (*NOx sensor at engine outlet bank A - Last self-diagnosis [h]*) (*OldName: new PV; Cycle:5*) (*V04.07.00.00*)
		iCnt_NOxS_EngOut_B_LastDiag : DINT; (*NOx sensor at engine outlet bank B - Last self-diagnosis [h]*) (*OldName: new PV; Cycle:5*) (*V04.07.00.00*)
		iCnt_NOxS_EngOut_LastDiag : DINT; (*NOx sensor at engine outlet - Last self-diagnosis [h]*) (*OldName: new PV; Cycle:5*) (*V04.07.00.00*)
		iIdx_NOxS_CatOut_DiagState : INT; (*NOx sensor at catalyst outlet - Status self-diagnosis (0= OK, 1= error, 2= waiting, 3= active)*) (*OldName: new PV; Cycle:5*) (*V04.07.00.00*)
		iIdx_NOxS_EngOut_A_DiagState : INT; (*NOx sensor at engine outlet bank A - Status self-diagnosis (0= OK, 1= error, 2= waiting, 3= active)*) (*OldName: new PV; Cycle:5*) (*V04.07.00.00*)
		iIdx_NOxS_EngOut_B_DiagState : INT; (*NOx sensor at engine outlet bank B - Status self-diagnosis (0= OK, 1= error, 2= waiting, 3= active)*) (*OldName: new PV; Cycle:5*) (*V04.07.00.00*)
		iIdx_NOxS_EngOut_DiagState : INT; (*NOx sensor at engine outlet - Status self-diagnosis (0= OK, 1= error, 2= waiting, 3= active)*) (*OldName: new PV; Cycle:5*) (*V04.07.00.00*)
		iNOxS_CatOut_OpHours : INT; (*NOx sensor at catalyst outlet - Operating hours [h]*) (*OldName: new PV; Cycle:5*) (*V04.07.00.00*)
		iNOxS_EngOut_A_OpHours : INT; (*NOx sensor at engine outlet bank A - Operating hours [h]*) (*OldName: new PV; Cycle:5*) (*V04.07.00.00*)
		iNOxS_EngOut_B_OpHours : INT; (*NOx sensor at engine outlet bank B - Operating hours [h]*) (*OldName: new PV; Cycle:5*) (*V04.07.00.00*)
		iNOxS_EngOut_OpHours : INT; (*NOx sensor at engine outlet - Operating hours [h]*) (*OldName: new PV; Cycle:5*) (*V04.07.00.00*)
		iNum_2451 : INT; (*SCR Urea dosing valve - number of valve with error*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		iNum_2453 : INT; (*SCR Urea dosing valve - number of valve with error*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		iNum_3456 : INT; (*SCR Urea dosing pump - number of pump with error*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		iNum_9380 : INT; (*SCR Urea dosing pump/valve - number of pump/valve with error*) (*OldName: new PV; Cycle:5*) (*V04.13.00.00*)
		rCF_SCR_UreaNFlowGain_Auto : REAL; (*SCR Urea nominal flow rate - Auto adjusted gain for feedforward [-]*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		rCO_Em_AvgShortTerm : REAL; (*CO emissions - short-term average - based on parametrized time base  [mg/Nm3]*) (*OldName: new PV; Cycle:5*) (*V04.07.00.00*)
		rCO_Em_CatOut_Hi : REAL; (*CO emissions at CAT outlet - maximum [ppm]*) (*OldName: new PV; Cycle:5*) (*V04.07.00.00*)
		rCO_Em_MonLim_Hi : REAL; (*CO emissions monitoring limit [mg/Nm3]*) (*OldName: new PV; Cycle:5*) (*V04.07.00.00*)
		rCO_SCR_CemsExtCatOut : REAL; (*CO measured by external customer CEMS at catalyst output [ppm]*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		rCO_SCR_EMLine1 : REAL; (*SCR Emission measurement line 1 - CO offset-corrected actual value [ppm]*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		rCO_SCR_EMLine1_Offset : REAL; (*SCR Emission measurement line 1 - CO offset [ppm]*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		rDPr_SCR_Cat : REAL; (*SCR CAT differential pressure [bar]*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		rFlow_SCR_UreaDosingOut : REAL; (*SCR Urea flow rate after dosing unit [l/h]*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		rFlow_SCR_UreaDosingUnit_ff : REAL; (*SCR NOx Controller - FF (feed forward) [l/h]*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		rFlow_SCR_UreaDosingUnit_Y : REAL; (*SCR NOx Controller - Y (output) [l/h]*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		rFlow_SCR_UreaDosingValve_Calc : REAL; (*SCR Urea flow rate after dosing unit - calculated via urea valve [l/h]*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		rFlow_SCR_UreaDosing_ffNH3Cor : REAL; (*SCR NOx Controller - FF (feed forward) with NH3 slip correction [l/h]*) (*OldName: new PV; Cycle:5*) (*V04.13.00.00*)
		rHum_CatOut : REAL; (*Exhaust water content at catalyst output [%]*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		rHum_SCR_CemsExtCatOut : REAL; (*Exhaust water content measured by external customer CEMS at catalyst output [%]*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		rLev_SCR_UreaTank : REAL; (*SCR Urea tank level [%]*) (*OldName: new PV; Cycle:5*) (*V04.13.00.00*)
		rNH3_SCR_CemsExtCatOut : REAL; (*NH3 measured by external customer CEMS at catalyst output [ppm]*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		rNO2_SCR_CemsExtCatOut : REAL; (*NO2 measured by external customer CEMS at catalyst output [ppm]*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		rNO2_SCR_EMLine1 : REAL; (*SCR Emission measurement line 1 - NO2 offset-corrected actual value [ppm]*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		rNO2_SCR_EMLine1_Offset : REAL; (*SCR Emission measurement line 1 - NO2 offset [ppm]*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		rNO2_SCR_EMLine2 : REAL; (*SCR Emission measurement line 2 - NO2 offset-corrected actual value [ppm]*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		rNO2_SCR_EMLine2_Offset : REAL; (*SCR Emission measurement line 2 - NO2 offset [ppm]*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		rNOx_Em_AvgDaily : REAL; (*NOx emissions - daily average normal operation [mg/Nm3]*) (*OldName: new PV; Cycle:5*) (*V04.07.00.00*)
		rNOx_Em_AvgDaily_All : REAL; (*NOx emissions - daily average total [mg/Nm3]*) (*OldName: new PV; Cycle:5*) (*V04.07.00.00*)
		rNOx_Em_AvgShortTerm : REAL; (*NOx emissions - short-term average - based on parametrized time base [mg/Nm3]*) (*OldName: new PV; Cycle:5*) (*V04.07.00.00*)
		rNOx_Em_CatOut_Hi : REAL; (*NOx emissions at CAT outlet - maximum [ppm]*) (*OldName: new PV; Cycle:5*) (*V04.07.00.00*)
		rNOx_Em_CatOut_Set : REAL; (*NOx emissions at CAT outlet - setpoint [ppm]*) (*OldName: new PV; Cycle:5*) (*V04.07.00.00*)
		rNOx_Em_EngOut_Set : REAL; (*NOx emissions at engine outlet - setpoint [ppm]*) (*OldName: new PV; Cycle:5*) (*V04.07.00.00*)
		rNOx_Em_EngOut_Set_H2_act : REAL; (*NOx emissions at engine outlet H2 based [ppm]*) (*OldName: new PV; Cycle:5*) (*V04.12.00.00*)
		rNOx_Em_MonLim_Hi : REAL; (*NOx emissions monitoring limit [mg/Nm3]*) (*OldName: new PV; Cycle:5*) (*V04.07.00.00*)
		rNOx_Em_MonLim_HiTol : REAL; (*NOx emissions monitoring limit + tolerance [mg/Nm3]*) (*OldName: new PV; Cycle:5*) (*V04.07.00.00*)
		rNOx_NOxS_CatOut : REAL; (*NOx sensor at catalyst outlet - actual NOx value with offset [ppm]*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		rNOx_NOxS_CatOut_cor : REAL; (*NOx sensor at catalyst outlet - actual NOx value with offset and CEMS correction [ppm]*) (*OldName: new PV; Cycle:5*) (*V04.05.01.00*)
		rNOx_NOxS_CatOut_DurDiag : REAL; (*NOx sensor at catalyst outlet - NOx during self-diagnosis [ppm]*) (*OldName: new PV; Cycle:5*) (*V04.07.00.00*)
		rNOx_NOxS_CatOut_Filt : REAL; (*NOx sensor at catalyst outlet - filtered NOx value [ppm]*) (*OldName: new PV; Cycle:5*) (*V04.07.00.00*)
		rNOx_NOxS_CatOut_mg : REAL; (*NOx sensor at catalyst outlet - actual NOx value with offset [mg/Nm3]*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		rNOx_NOxS_CatOut_mg_Filt : REAL; (*NOx sensor at catalyst outlet - filtered NOx value [mg/Nm3]*) (*OldName: new PV; Cycle:5*) (*V04.07.00.00*)
		rNOx_NOxS_EngOut : REAL; (*NOx sensor at engine outlet - actual NOx value with offset [ppm]*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		rNOx_NOxS_EngOut_A : REAL; (*NOx sensor at engine outlet bank A - actual NOx value with offset [ppm]*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		rNOx_NOxS_EngOut_Avg : REAL; (*NOx average value from NOx sensor at engine outlet position [ppm]*) (*OldName: new PV; Cycle:5*) (*V04.05.01.00*)
		rNOx_NOxS_EngOut_Avg_Filt : REAL; (*Filtered NOx average value from NOx sensor at engine outlet position [ppm]*) (*OldName: new PV; Cycle:5*) (*V04.07.00.00*)
		rNOx_NOxS_EngOut_A_DurDiag : REAL; (*NOx sensor at engine outlet bank A - NOx during self-diagnosis [ppm]*) (*OldName: new PV; Cycle:5*) (*V04.07.00.00*)
		rNOx_NOxS_EngOut_A_Filt : REAL; (*NOx sensor at engine outlet bank A - filtered NOx value [ppm]*) (*OldName: new PV; Cycle:5*) (*V04.07.00.00*)
		rNOx_NOxS_EngOut_A_mg : REAL; (*NOx sensor at engine outlet bank A - actual NOx value with offset [mg/Nm3]*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		rNOx_NOxS_EngOut_A_mg_Filt : REAL; (*NOx sensor at engine outlet bank A - filtered NOx value [mg/Nm3]*) (*OldName: new PV; Cycle:5*) (*V04.07.00.00*)
		rNOx_NOxS_EngOut_B : REAL; (*NOx sensor at engine outlet bank B - actual NOx value with offset [ppm]*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		rNOx_NOxS_EngOut_B_DurDiag : REAL; (*NOx sensor at engine outlet bank B - NOx during self-diagnosis [ppm]*) (*OldName: new PV; Cycle:5*) (*V04.07.00.00*)
		rNOx_NOxS_EngOut_B_Filt : REAL; (*NOx sensor at engine outlet bank B - filtered NOx value [ppm]*) (*OldName: new PV; Cycle:5*) (*V04.07.00.00*)
		rNOx_NOxS_EngOut_B_mg : REAL; (*NOx sensor at engine outlet bank B - actual NOx value with offset [mg/Nm3]*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		rNOx_NOxS_EngOut_B_mg_Filt : REAL; (*NOx sensor at engine outlet bank B - filtered NOx value [mg/Nm3]*) (*OldName: new PV; Cycle:5*) (*V04.07.00.00*)
		rNOx_NOxS_EngOut_DurDiag : REAL; (*NOx sensor at engine outlet - NOx during self-diagnosis [ppm]*) (*OldName: new PV; Cycle:5*) (*V04.07.00.00*)
		rNOx_NOxS_EngOut_Filt : REAL; (*NOx sensor at engine outlet - filtered NOx value [ppm]*) (*OldName: new PV; Cycle:5*) (*V04.07.00.00*)
		rNOx_NOxS_EngOut_mg : REAL; (*NOx sensor at engine outlet - actual NOx value with offset [mg/Nm3]*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		rNOx_NOxS_EngOut_mg_Avg : REAL; (*NOx average value from NOx sensor at engine outlet position [mg/Nm3]*) (*OldName: new PV; Cycle:5*) (*V04.07.00.00*)
		rNOx_NOxS_EngOut_mg_Avg_Filt : REAL; (*Filtered NOx average value from NOx sensor at engine outlet position [mg/Nm3]*) (*OldName: new PV; Cycle:5*) (*V04.07.00.00*)
		rNOx_NOxS_EngOut_mg_Filt : REAL; (*NOx sensor at engine outlet - filtered NOx value [mg/Nm3]*) (*OldName: new PV; Cycle:5*) (*V04.07.00.00*)
		rNOx_SCR_NOxCtrl_act : REAL; (*SCR NOx controller - X (actual NOx value) [ppm]*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		rNOx_SCR_NOxCtrl_sp : REAL; (*SCR NOx controller - W (setpoint) [ppm]*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		rNO_SCR_CemsExtCatOut : REAL; (*NO measured by external customer CEMS at catalyst output [ppm]*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		rNO_SCR_EMLine1 : REAL; (*SCR Emission measurement line 1 - NO offset-corrected actual value [ppm]*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		rNO_SCR_EMLine1_Offset : REAL; (*SCR Emission measurement line 1 - NO offset [ppm]*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		rNO_SCR_EMLine2 : REAL; (*SCR Emission measurement line 2 - NO offset-corrected actual value [ppm]*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		rNO_SCR_EMLine2_Offset : REAL; (*SCR Emission measurement line 2 - NO offset [ppm]*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		rO2_NOxS_CatOut : REAL; (*NOx sensor at catalyst outlet - actual O2 value with offset [Vol%]*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		rO2_NOxS_CatOut_DurDiag : REAL; (*NOx sensor at catalyst outlet - O2 during self-diagnosis [Vol%]*) (*OldName: new PV; Cycle:5*) (*V04.07.00.00*)
		rO2_NOxS_CatOut_Filt : REAL; (*NOx sensor at catalyst outlet - filtered O2 value [Vol%]*) (*OldName: new PV; Cycle:5*) (*V04.07.00.00*)
		rO2_NOxS_EngOut : REAL; (*NOx sensor at engine outlet - actual O2 value with offset [Vol%]*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		rO2_NOxS_EngOut_A : REAL; (*NOx sensor at engine outlet bank A - actual O2 value with offset [Vol%]*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		rO2_NOxS_EngOut_Avg : REAL; (*O2 average value from NOx sensor at engine outlet position [Vol%]*) (*OldName: new PV; Cycle:5*) (*V04.07.00.00*)
		rO2_NOxS_EngOut_Avg_Filt : REAL; (*Filtered O2 average value from NOx sensor at engine outlet position [Vol%]*) (*OldName: new PV; Cycle:5*) (*V04.07.00.00*)
		rO2_NOxS_EngOut_A_DurDiag : REAL; (*NOx sensor at engine outlet bank A - O2 during self-diagnosis [Vol%]*) (*OldName: new PV; Cycle:5*) (*V04.07.00.00*)
		rO2_NOxS_EngOut_A_Filt : REAL; (*NOx sensor at engine outlet bank A - filtered O2 value [Vol%]*) (*OldName: new PV; Cycle:5*) (*V04.07.00.00*)
		rO2_NOxS_EngOut_B : REAL; (*NOx sensor at engine outlet bank B - actual O2 value with offset [Vol%]*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		rO2_NOxS_EngOut_B_DurDiag : REAL; (*NOx sensor at engine outlet bank B - O2 during self-diagnosis [Vol%]*) (*OldName: new PV; Cycle:5*) (*V04.07.00.00*)
		rO2_NOxS_EngOut_B_Filt : REAL; (*NOx sensor at engine outlet bank B - filtered O2 value [Vol%]*) (*OldName: new PV; Cycle:5*) (*V04.07.00.00*)
		rO2_NOxS_EngOut_DurDiag : REAL; (*NOx sensor at engine outlet - O2 during self-diagnosis [Vol%]*) (*OldName: new PV; Cycle:5*) (*V04.07.00.00*)
		rO2_NOxS_EngOut_Filt : REAL; (*NOx sensor at engine outlet - filtered O2 value [Vol%]*) (*OldName: new PV; Cycle:5*) (*V04.07.00.00*)
		rO2_SCR_CemsExtCatOut : REAL; (*O2 measured by external customer CEMS at catalyst output [Vol-%]*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		rO2_SCR_EMLine1 : REAL; (*SCR Emission measurement line 1 - O2 actual value [Vol-%]*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		rPc_NOxS_CatOut_DiagResult : REAL; (*NOx sensor at catalyst outlet - Self-diagnosis result [%]*) (*OldName: new PV; Cycle:5*) (*V04.07.00.00*)
		rPc_NOxS_EngOut_A_DiagResult : REAL; (*NOx sensor at engine outlet bank A - Self-diagnosis result [%]*) (*OldName: new PV; Cycle:5*) (*V04.07.00.00*)
		rPc_NOxS_EngOut_B_DiagResult : REAL; (*NOx sensor at engine outlet bank B - Self-diagnosis result [%]*) (*OldName: new PV; Cycle:5*) (*V04.07.00.00*)
		rPc_NOxS_EngOut_DiagResult : REAL; (*NOx sensor at engine outlet - Self-diagnosis result [%]*) (*OldName: new PV; Cycle:5*) (*V04.07.00.00*)
		rPc_SCR_UreaDosingUnit_ff : REAL; (*SCR Urea flow controller - FF (feed forward) [%]*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		rPc_SCR_UreaDosingUnit_Y : REAL; (*SCR Urea flow controller - Y (output) [%]*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		rPr_SCR_CatIn : REAL; (*SCR Exhaust pressure CAT inlet [bar]*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		rPr_SCR_CatOut : REAL; (*SCR Exhaust pressure CAT outlet [bar]*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		rPr_SCR_ComprAirSupply : REAL; (*SCR Compressed air supply pressure urea injection [bar]*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		rPr_SCR_UreaDosingIn : REAL; (*SCR Urea pressure before dosing unit [bar]*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		rPr_SCR_UreaDosingOut : REAL; (*SCR Urea pressure after dosing unit [bar]*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		rT_Cat_Msg2766 : REAL; (*Catalyst temperature at the time of the warning 2766 [°C]*) (*OldName: new PV; Cycle: 5;*) (*V04.11.00.00*)
		rT_SCR_CatAvg : REAL; (*SCR Exhaust temperature CAT average [°C]*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		rT_SCR_CatIn : REAL; (*SCR Exhaust temperature CAT inlet [°C]*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		rT_SCR_CatOut : REAL; (*SCR Exhaust temperature CAT outlet [°C]*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		tiNOxS_CatOut_ActiveCountdown : TIME; (*NOx sensor at catalyst outlet - Activation countdown [sec]*) (*OldName: new PV; Cycle:5*) (*V04.07.00.00*)
		tiNOxS_EngOut_ActiveCountdown : TIME; (*NOx sensor at engine outlet - Activation countdown [sec]*) (*OldName: new PV; Cycle:5*) (*V04.07.00.00*)
		tiNOxS_EngOut_A_ActiveCountdown : TIME; (*NOx sensor at engine outlet bank A - Activation countdown [sec]*) (*OldName: new PV; Cycle:5*) (*V04.07.00.00*)
		tiNOxS_EngOut_B_ActiveCountdown : TIME; (*NOx sensor at engine outlet bank B - Activation countdown [sec]*) (*OldName: new PV; Cycle:5*) (*V04.07.00.00*)
		tiSCR_UreaDosingUnit_Remain : TIME; (*SCR Remaining time until urea dosing unit stops - tank level min [s]*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		rO2_LowNOxS_CatOut : REAL; (*NOx sensor at CatOut low - O2 dry value [%]*) (*OldName: new PV; Cycle:5*) (*V04.14.00.00*)
		rNOx_LowNOxS_CatOut : REAL; (*NOx sensor at CatOut low - NOx dry value [ppm]*) (*OldName: new PV; Cycle:5*) (*V04.14.00.00*)
		rNOx_LowNOxS_CatOut_mg : REAL; (*NOx sensor at CatOut low - O2 dry value [mg/Nm3]*) (*OldName: new PV; Cycle:5*) (*V04.14.00.00*)
		rO2_StdNOxS_CatOut : REAL; (*NOx sensor at CatOut standard - O2 dry value [%]*) (*OldName: new PV; Cycle:5*) (*V04.14.00.00*)
		rNOx_StdNOxS_CatOut : REAL; (*NOx sensor at CatOut standard - NOx dry value [ppm]*) (*OldName: new PV; Cycle:5*) (*V04.14.00.00*)
		rNOx_StdNOxS_CatOut_mg : REAL; (*NOx sensor at CatOut standard - NOx dry value [mg/Nm3]*) (*OldName: new PV; Cycle:5*) (*V04.14.00.00*)
		iID_LowNOxS_CatOut_SN : UDINT; (*NOx sensor at CatOut low - Serial number*) (*OldName: new PV; Cycle:5*) (*V04.14.00.00*)
		iID_LowNOxS_CatOut_RVN : UDINT; (*NOx sensor at CatOut low - Revision number*) (*OldName: new PV; Cycle:5*) (*V04.14.00.00*)
		iID_LowNOxS_CatOut_PCD : UDINT; (*NOx sensor at CatOut low - Product code*) (*OldName: new PV; Cycle:5*) (*V04.14.00.00*)
		iID_LowNOxS_CatOut_VID : UDINT; (*NOx sensor at CatOut low - Vendor ID*) (*OldName: new PV; Cycle:5*) (*V04.14.00.00*)
	END_STRUCT;
	Perm_EM_Struct : 	STRUCT 
		iCnt_SCR_UreaDosingUnitMaint : DINT; (*SCR Urea dosing unit - maintenance counter [h]*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		iCnt_SCR_UreaDosingUnitMaint2 : DINT; (*SCR Urea dosing unit redundant - maintenance counter [h]*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		iOpH_SCR_UreaDosingUnit : UDINT; (*SCR Urea dosing unit - total operation hours [h]*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		iOpH_SCR_UreaDosingUnit2 : UDINT; (*SCR Urea dosing unit - total operation hours [h]*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		rVol_SCR_UreaConsumption : LREAL; (*SCR Urea consumption over lifetime [l]*) (*OldName: new PV; Cycle:5*) (*V04.05.00.00*)
		iOpH_SCR_AirCompressor : UDINT; (*SCR Air compressor - total operation hours [h]*) (*OldName: new PV; Cycle:5*) (*V04.05.01.00*)
		iCnt_SCR_AirCompressorMaint : DINT; (*SCR Air compressor - maintenance counter [h]*) (*OldName: new PV; Cycle:5*) (*V04.05.01.00*)
		iCnt_NOx_Em_MonLim_Exc : DINT; (*Duration of emission tolerance exceedance (Dauer der Emissionstoleranzüberschreitung) [h]*) (*OldName: new PV; Cycle:5*) (*V04.07.00.00*)
		iDay_Em_AvgDaily : USINT; (*Save last day to trigger change of day*) (*OldName: new PV; Cycle:5*) (*V04.10.00.00*)
		rNOx_Em_AvgDailyT_Sum_mg : REAL; (*Sum for average calculation - NOx daily total [mg/Nm3]*) (*OldName: new PV; Cycle:5*) (*V04.10.00.00*)
		rNOx_Em_AvgDaily_Sum_mg : REAL; (*Sum for average calculation - NOx daily [mg/Nm3]*) (*OldName: new PV; Cycle:5*) (*V04.10.00.00*)
		iCnt_Em_AvgDaily : UINT; (*counter - for average calculation - NOx daily*) (*OldName: new PV; Cycle:5*) (*V04.10.00.00*)
		rPermValue01 : REAL; (*spare permanent value - replace with new vars of same lenght, when needed*) (*OldName: new PV; Cycle:5*)
		rPermValue02 : REAL; (*spare permanent value - replace with new vars of same lenght, when needed*) (*OldName: new PV; Cycle:5*)
		rPermValue03 : REAL; (*spare permanent value - replace with new vars of same lenght, when needed*) (*OldName: new PV; Cycle:5*)
		rPermValue04 : REAL; (*spare permanent value - replace with new vars of same lenght, when needed*) (*OldName: new PV; Cycle:5*)
		rPermValue05 : REAL; (*spare permanent value - replace with new vars of same lenght, when needed*) (*OldName: new PV; Cycle:5*)
		rPermValue06 : REAL; (*spare permanent value - replace with new vars of same lenght, when needed*) (*OldName: new PV; Cycle:5*)
		rPermValue07 : REAL; (*spare permanent value - replace with new vars of same lenght, when needed*) (*OldName: new PV; Cycle:5*)
		rPermValue08 : REAL; (*spare permanent value - replace with new vars of same lenght, when needed*) (*OldName: new PV; Cycle:5*)
		rPermValue09 : REAL; (*spare permanent value - replace with new vars of same lenght, when needed*) (*OldName: new PV; Cycle:5*)
		rPermValue10 : REAL; (*spare permanent value - replace with new vars of same lenght, when needed*) (*OldName: new PV; Cycle:5*)
	END_STRUCT;
	rtctime_typ : 	STRUCT  (*structure for actual time of controller*) (*OldName: new PV; Cycle: 5;*) (*V04.07.00.00*)
		year : UINT;
		month : USINT;
		day : USINT;
		reserve : USINT;
		hour : USINT;
		minute : USINT;
		second : USINT;
		millisec : UINT;
		microsec : UINT;
	END_STRUCT;
END_TYPE
