
TYPE
	PROGRAMMER_INFO_Perm : 	STRUCT 
		DO_NOT_CHANGE_PERM : STRING[40] := 'DO NOT CHANGE PERM  LENGT OR SORTING! '; (*DO NOT CHANGE PERM LENGT OR SORTING! Every change demands an update of main revision numbering.*) (*ADD NEW PERM DATAPOINT ONLY BY REPLACING SPARE ENTRIES OF SAME LENGHT!. DO NOT DELETE existing Perm items. Add new file for mayor releases, don't  change existing!*)
	END_STRUCT;
	PERM_CU_Struct : 	STRUCT 
		iCount1 : DINT; (* Customized Counter*)
		iCount2 : DINT; (* Customized Counter*)
		iCount3 : DINT; (* Customized Counter*)
		iCount4 : DINT; (* Customized Counter*)
		iMaintenanceCount1 : DINT; (*Maintenance Counter*)
		iMaintenanceCount2 : DINT; (*Maintenance Counter*)
		iMaintenanceCount3 : DINT; (*Maintenance Counter*)
		iMaintenanceCount4 : DINT; (*Maintenance Counter*)
		iMaintenanceCount5 : DINT; (*Maintenance Counter - spare permanent value*)
		iMaintenanceCount6 : DINT; (*Maintenance Counter - spare permanent value*)
		iMaintenanceCount7 : DINT; (*Maintenance Counter - spare permanent value*)
		iMaintenanceCount8 : DINT; (*Maintenance Counter - spare permanent value*)
		iCount5 : DINT; (*Customized Counter - spare permanent value*)
		iCount6 : DINT; (*Customized Counter - spare permanent value*)
		iCount7 : DINT; (*Customized Counter - spare permanent value*)
		iCount8 : DINT; (*Customized Counter - spare permanent value*)
		iCount9 : DINT; (*Customized Counter - spare permanent value*)
		iCount10 : DINT; (*Customized Counter - spare permanent value*)
		iCount11 : DINT; (*Customized Counter - spare permanent value V4.4*)
		iCount12 : DINT; (*Customized Counter - spare permanent value V4.4*)
		iCount13 : DINT; (*Customized Counter - spare permanent value V4.4*)
		iCount14 : DINT; (*Customized Counter - spare permanent value V4.4*)
		iCount15 : DINT; (*Customized Counter - spare permanent value V4.4*)
		iCount16 : DINT; (*Customized Counter - spare permanent value V4.4*)
		iCount17 : DINT; (*Customized Counter - spare permanent value V4.4*)
		iCount18 : DINT; (*Customized Counter - spare permanent value V4.4*)
		iCount19 : DINT; (*Customized Counter - spare permanent value V4.4*)
		iCount20 : DINT; (*Customized Counter - spare permanent value V4.4*)
		rTB_PermValue21 : REAL; (*spare permanent value - replace with new vars of same lenght, when needed*)
		rTB_PermValue22 : REAL; (*spare permanent value - replace with new vars of same lenght, when needed*)
		rTB_PermValue23 : REAL; (*spare permanent value - replace with new vars of same lenght, when needed*)
		rTB_PermValue24 : REAL; (*spare permanent value - replace with new vars of same lenght, when needed*)
		rTB_PermValue25 : REAL; (*spare permanent value - replace with new vars of same lenght, when needed*)
		rTB_PermValue26 : REAL; (*spare permanent value - replace with new vars of same lenght, when needed*)
		rTB_PermValue27 : REAL; (*spare permanent value - replace with new vars of same lenght, when needed*)
		rTB_PermValue28 : REAL; (*spare permanent value - replace with new vars of same lenght, when needed*)
		rTB_PermValue29 : REAL; (*spare permanent value - replace with new vars of same lenght, when needed*)
		rTB_PermValue30 : REAL; (*spare permanent value - replace with new vars of same lenght, when needed*)
	END_STRUCT;
END_TYPE
