
TYPE
	PARA_Cust_Struct : 	STRUCT 
		bActUniIO : BOOL; (*CustomerIO - UniversalIO enable general*) (* OldName: bActUniIO; Cycle: 5; *)
		bAuxEC_Visible : BOOL; (*PARA [11870]: visibility parameters of emergency cooler control*)
		bCalc_PRamp_FC_active : BOOL; (*PARA [13499]: calculation of power ramp exists*)
		bCA_IgnP_CylOffset_Active : BOOL; (*cylinder timing para prepared for special purpose (0 without customized code)*)
		bCtr_Cust1 : BOOL; (* visibility bit for new customizable controllers without predefined purpose	*) (* OldName: bREG1; Cycle: 5; *)
		bCtr_Cust2 : BOOL; (* visibility bit for new customizable controllers without predefined purpose	*) (* OldName: bREG2; Cycle: 5; *)
		bCtr_Cust3 : BOOL; (* visibility bit for new customizable controllers without predefined purpose	*) (* OldName: bREG3; Cycle: 5; *)
		bCtr_Cust4 : BOOL; (* visibility bit for new customizable controllers without predefined purpose	*) (* OldName: bREG4; Cycle: 5; *)
		bCtr_Cust5 : BOOL; (* visibility bit for new customizable controllers without predefined purpose	*) (* OldName: bREG5; Cycle: 5; *)
		bCtr_Cust6 : BOOL; (* visibility bit for new customizable controllers without predefined purpose	*) (* OldName: bREG6; Cycle: 5; *)
		bCtr_Cust7 : BOOL; (* visibility bit for new customizable controllers without predefined purpose	*) (* OldName: bREG7; Cycle: 5; *)
		bCtr_Cust8 : BOOL; (* visibility bit for new customizable controllers without predefined purpose	*) (* OldName: bREG8; Cycle: 5; *)
		bCtr_Cust41 : BOOL; (* visibility bit for new customizable controllers without predefined purpose	*) (* OldName: bREG8; Cycle: 5; *)
		bCtr_Cust42 : BOOL; (* visibility bit for new customizable controllers without predefined purpose	*) (* OldName: bREG8; Cycle: 5; *)
		bCtr_Cust43 : BOOL; (* visibility bit for new customizable controllers without predefined purpose	*) (* OldName: bREG8; Cycle: 5; *)
		bCtr_Cust44 : BOOL; (* visibility bit for new customizable controllers without predefined purpose	*) (* OldName: bREG8; Cycle: 5; *)
		bCtr_Cust45 : BOOL; (* visibility bit for new customizable controllers without predefined purpose	*) (* OldName: bREG8; Cycle: 5; *)
		bCtr_Mns_AnaIn_Setp_Enable : BOOL; (*	setpoint over mA aktiv Var.2 via parameter*)
		bCtr_Mns_Enable : BOOL; (*PARA [13587]: meter Netzbezugsregler Aktivierung *)
		bCtr_Mns_Setp_Set4mA : BOOL; (*	scaling 4-20 mA aktiv *)
		bCustAnaIn_Active : ARRAY[0..120]OF BOOL; (* = RAN1_a to RAN16_a	-	reserve channel activation bit	*) (*OldName: RAN1_a, RAN2_a, RAN16_a; Cycle: 5;*)
		bCustAnaOut_Active : ARRAY[0..iNoOf_AnaOut]OF BOOL; (* UNUSED LEGACY DATA POINT (V4.02), scheduled for removal. BOOL[0..60]  DO NOT USE ANY MORE!*) (*OldName: RAN1_a, RAN2_a, RAN16_a; Cycle: 5;*)
		bCustDigIn_Active : ARRAY[0..200]OF BOOL; (* NEW with V4.02: reserve input channel VISIBILITY RELEASE ONLY	*) (*OldName: RAN1_a, RAN2_a, RAN16_a; Cycle: 5;*)
		bCustDigOut_Active : ARRAY[0..150]OF BOOL; (* NEW with V4.02: reserve output channel release bit	*) (*OldName: RAN1_a, RAN2_a, RAN16_a; Cycle: 5;*)
		bDEIE_Active : BOOL; (*PARA [13691]: ERDF task active *)
		bLimOnOff_aktiv : BOOL; (*	*)
		bOPC_Rcv_Ena : BOOL; (*PARA [12872]: OPC receive enabled*) (*OldName:opc_rcv; Cycle: 5;*)
		bPRamp_FC_ExtInp : BOOL; (*PARA [13458]: external input for power ramp with Frequency Control*)
		bPRamp_FC_SetCOn : BOOL; (*PARA [13455]: activation of power ramp for Frequency Control*)
		bP_Mns_AnaIn_Enable : BOOL; (*	True for AnaIn Var.1 - actual value has to be connected to a Customer Analog Input *)
		bP_Mns_AnaIn_Set4mA : BOOL; (*   *)
		bP_Mns_MMU_Enable : BOOL; (*	True for MMU Var.2 - actual value is determined by an additional MMU *)
		bSet_FC_COn : BOOL; (*PARA [13429]: acitvation frequency control*)
		bSet_FC_HFRCOn : BOOL; (*PARA [13442]: HFR (High Frequency Response) activation*)
		bSet_FC_Input : BOOL; (*PARA [13430]: selection of input [0 = Standard Input, 1 = external Input]*)
		bSet_FC_PORCOn : BOOL; (*PARA [13443]: POR (Primary Operational Reserve) activation*)
		bSet_FC_RRCOn : BOOL; (*PARA [13451]: RR (Replacement Reserve) activation*)
		bSet_FC_SORCOn : BOOL; (*PARA [13445]: SOR (Secondary Operational Reserve) activation*)
		bSet_FC_SRCOn : BOOL; (*PARA [13453]: SR (Substitute Reserve) activation*)
		bSet_FC_TimeActFunctCOn : BOOL; (*PARA [13441]: activation of Time Activated Functions [Hz]*)
		bSet_FC_TOR2COn : BOOL; (*PARA [13449]: TOR 2 (Tertiary 2 Operational Reserve) activation*)
		bSet_FC_TORCOn : BOOL; (*PARA [13447]: TOR (Tertiary Operational Reserve) activation*)
		bT_Gen_Wind_Ena : BOOL; (*PARA [11492]: winding temperature monitoring enabled*) (*Oldname:wick_a; Cycle:;*)
		iAuxCust_Active : ARRAY[0..70]OF INT; (* = 	HBM30_TYP...	-	type of reserve auxiliary #30...	* watch for HMI Extension*) (*OldName: HBM30_TYP; Cycle: 5; *)
		iCtr_Mns_Options : INT; (*INTERNAL parameter to set developer options for mains controller operation PREPARED *)
		iCustAnaIn_MinMaxActive : ARRAY[0..120]OF INT; (* = activation for new limit values min, max for reserve analog input*) (*OldName: new PV; Cycle: 5;*)
		iCustAnaIn_Typ : ARRAY[0..120]OF INT; (*= code to define the type  to reserve channel: 1 ... 0-20mA, 2 ... 4-20mA, 3 ... 0-10V, 4 ... 2-10V, 5 ... Pt100, 6 ... NiCr-Ni, 7 ... 0-5V, 8 ... -10/10V*) (*OldName: RAN1_TYP, RAN2_TYP, RAN16_TYP; Cycle: 5;*)
		iCustAnaIn_Unit : ARRAY[0..120]OF INT; (* = 	RAN1_UNIT to RAN16_UNIT	-	code to define unit to reserve channel*) (*OldName: RAN1_UNIT, RAN2_UNIT, RAN16_UNIT; Cycle: 5;*)
		iCust_ScalingBlock_Typ : ARRAY[0..30]OF INT; (*PARA [14655], [14660], [14665],...ff: Scaling Block Type*) (*OldName: new PV; Cycle: 5;*)
		iCust_SparePara_OLD : ARRAY[0..70]OF INT; (* = 	SPS_REZP1 to SPS_REZP70	-	DO NOT USE FOR NEW INSTALLATIONS! Spare, for compatibility only,	*) (* OldName: obsolete; Cycle: 5; *)
		iEng_Motortype : INT; (*Index of Engine Type*) (*OldName: new PV; Cycle: 5;*)
		iIdx_Droop_SetDefaultCase : USINT; (*Droop fallback mode,  0: default Para, 1: freeze last value*)
		iKlS_KnckValue_Limit : UINT; (*  limit for knocking detection [mV]  *) (* OldName: Fenst2LiMx ; Cycle:   *)
		iNoOfUniAna : USINT; (* CustomerIO system configuration	*) (* OldName: ucNoOfUniAna; Cycle: 5; *)
		iNoOfUniDig : USINT; (* CustomerIO system configuration	*) (* OldName: ucNoOfUniDig; Cycle: 5; *)
		iSet_FC_ExtInp : INT; (*PARA [13434]: selection of external Input [1 = e2M Bus, 2 = e2m HW, 3 = next-Box Bus, 4 = next-Box HW, ]*)
		iSet_FC_Testmode : INT; (*PARA [13496]: Frequency Control test mode [1= AUTO via frequency setpoint, 2 = MAN via frequency setpoint, 3 = AUTO via frequency actual, 4 = MAN via frequency actual]*)
		iSet_GrC_FSM : INT;
		iSource_F_N_OffsSet : INT; (*V4.10.1; Para: F/N Setpoint: 0= no setpoint, 1= Droop, 2= External, 3= LSL * ToDo:  correct VIS Additional PLC Tag is to be established*)
		iT_FreqFilt_TB : INT; (* Lowpass filter time constant TF *)
		rCA_IgnP_CylOffset : ARRAY[0..24]OF REAL; (*cylinder timing para prepared for special purpose (0 without customized code)*)
		rCtr_CustOut_ScalMax : ARRAY[0..45]OF REAL; (*= outdated parameter, scaling in HAL is per default allways 0.0 - 1-0*) (*OldName: new PV; Cycle: 5;*)
		rCtr_CustOut_ScalMin : ARRAY[0..45]OF REAL; (*= outdated parameter, scaling in HAL is per default allways 0.0 - 1-0*) (*OldName: new PV; Cycle: 5;*)
		rCtr_Mns_Setp_ScalMax : REAL; (*	scale maximum *)
		rCtr_Mns_Setp_ScalMin : REAL; (*	scale minimum *)
		rCustAnaIn_Hy : ARRAY[0..120]OF REAL; (* = new hysteresis to limit values (+min, -max) for reserve analog input*) (*OldName: new PV; Cycle: 5;*)
		rCustAnaIn_LimHi : ARRAY[0..120]OF REAL; (* = new prepared limit value for reserve analog input (->watch also rCustAnaIn_LimHiHi below)*) (*OldName: new PV; Cycle: 5;*)
		rCustAnaIn_LimHiHi : ARRAY[0..120]OF REAL; (* = new SHUTDOWN limit value for reserve analog input*) (*OldName: new PV; Cycle: 5;*)
		rCustAnaIn_LimLo : ARRAY[0..120]OF REAL; (* = new prepared limit value for reserve analog input (->watch also rCustAnaIn_LimLoLo below)*) (*OldName: new PV; Cycle: 5;*)
		rCustAnaIn_LimLoLo : ARRAY[0..120]OF REAL; (* = new SHUTDOWN limit value for reserve analog input*) (*OldName: new PV; Cycle: 5;*)
		rCustAnaIn_Offset : ARRAY[0..120]OF REAL; (*watch for HMI Extension*)
		rCustAnaIn_ScalMax : ARRAY[0..120]OF REAL; (* = OBGR_RAN1 to OBERGR_RAN16	-	reserve channel raw signal scaling	*) (*OldName: OBGR_RAN1, OBGR_RAN2, OBGR_RAN16; Cycle: 5;*)
		rCustAnaIn_ScalMin : ARRAY[0..120]OF REAL; (* = 	UNGR_RAN1 to UNERGR_RAN16	-	reserve channel raw signal scaling	*) (*OldName: UNGR_RAN1, UNGR_RAN2, UNGR_RAN16; Cycle: 5;*)
		rCustAnaOut_ScalMax : ARRAY[0..iNoOf_AnaOut]OF REAL; (* = new AnalogOUT reserve channel 0-20mA raw signal scaling	REAL[0..60]*) (*HMI Extension*)
		rCustAnaOut_ScalMin : ARRAY[0..iNoOf_AnaOut]OF REAL; (* = new AnalogOUT reserve channel 0-20mA raw signal scaling REAL[0..60]*) (*HMI Extension*)
		rCustFactor_IF : ARRAY[660..757]OF REAL; (*Scaling factor for Customer Bus connection values*)
		rCust_SparePara : ARRAY[0..500]OF REAL; (*[1..200] ELEMENTS PREPARED IN DEFAULT CONFIGURATION - possible HMI Extension [201..500] IS NOT FORWARDED TO OTHER MODULES!*) (* OldName: SPS_REZP1, SPS_REZP2, SPS_REZP70; Cycle: 5; *)
		rCust_ScalingBlock_X1 : ARRAY[0..30]OF REAL; (*PARA [14656], [14661], [14666],...ff: Scaling Block X1 *) (*OldName: new PV; Cycle: 5;*)
		rCust_ScalingBlock_X2 : ARRAY[0..30]OF REAL; (*PARA [14657], [14662], [14667],...ff: Scaling Block X2 *) (*OldName: new PV; Cycle: 5;*)
		rCust_ScalingBlock_Y1 : ARRAY[0..30]OF REAL; (*PARA [14658], [14663], [14668],...ff: Scaling Block Y1 *) (*OldName: new PV; Cycle: 5;*)
		rCust_ScalingBlock_Y2 : ARRAY[0..30]OF REAL; (*PARA [14659], [14664], [14669],...ff: Scaling Block Y2 *) (*OldName: new PV; Cycle: 5;*)
		rDemGenerate_Lim_Off : REAL; (*PARA [13628]: meter	Shutdown Limit (% of PN Generator) *)
		rDemGenerate_Lim_On : REAL; (*PARA [13627]: meter	Start Up Limit (% of PN Generator) *)
		rDroop_FC_neg : REAL; (*PARA [13432]: negative Droop [%]*)
		rDroop_FC_pos : REAL; (*PARA [13431]: postive Droop [%]*)
		ReplaceMeWithYourParameter : REAL := 1000.0; (*spacer*) (* OldName: new PV; Cycle: 5; *)
		rFAct_FC_ManualTest : REAL; (*PARA [13498]: actual Frequency for manual Test *)
		rFNom_FC_ManualTest : REAL; (*PARA [13497]: nominal Frequency for manual Test *)
		rFNom_LFSM_Ref : REAL; (*Frequency reference for FSM/LFSM [Hz]*)
		rF_Deadband_TB : REAL; (* Deadband width CF *)
		rF_FC_Deadband_neg : REAL; (*PARA [13440]: Frequency Deadband negative [Hz]*)
		rF_FC_Deadband_pos : REAL; (*PARA [13439]: Frequency Deadband positive [Hz]*)
		rF_FC_Dlt_neg : REAL; (*PARA [13438]: Delta Frequency negative [Hz]*)
		rF_FC_Dlt_pos : REAL; (*PARA [13437]: Delta Frequency positive [Hz]*)
		rF_MMD_FSM_PT1_OUT : REAL;
		rF_Nom : ARRAY[0..2]OF REAL; (*PARA: nominal frequency [Hz]*)
		rI_Ctr_CustOut_ScalMax : ARRAY[0..45]OF REAL; (*= Hardware Side scaling 0-20mA in [mA]*)
		rI_Ctr_CustOut_ScalMin : ARRAY[0..45]OF REAL; (*= Hardware Side scaling 0-20mA in [mA]*)
		rI_CustAnaOut_ScalMax : ARRAY[0..iNoOf_AnaOut]OF REAL; (*= Hardware Side scaling 0-20mA in [mA]*) (*HMI Extension [0..60]*)
		rI_CustAnaOut_ScalMin : ARRAY[0..iNoOf_AnaOut]OF REAL; (*= Hardware Side scaling 0-20mA in [mA]*) (*HMI Extension [0..60]*)
		rI_NomMax : ARRAY[0..2]OF REAL; (* Para: monitoring limit neutral current *) (* OldName:usCNMax; Cycle: *)
		rI_N_Set_ExtAI_NormScalMax : REAL; (*PARA [11754]: external speed setpoint via analog input related to rN_EngNom mA at point 2 *) (* OldName:n_i2; Cycle: *)
		rI_N_Set_ExtAI_NormScalMin : REAL; (*PARA [11755]: external speed setpoint via analog input related to rN_EngNom mA at point 1 *) (* OldName:n_i1; Cycle: *)
		rI_P_Red_AI_NormScalMax : REAL; (*PARA [11758]: power reduction by analog input mA at point 2 *) (* OldName:p_red_i2; Cycle: *)
		rI_P_Red_AI_NormScalMin : REAL; (*PARA [11759]: power reduction by analog input mA at point 1 *) (* OldName: p_red_i1; Cycle: *)
		rI_P_Set_ExtAI_NormScalMax : REAL; (*PARA [11760]: external power setpoint via analog input related to rP_Nom mA at point 2 *) (* OldName:p_soll_i2; Cycle: *)
		rI_P_Set_ExtAI_NormScalMin : REAL; (*PARA [11761]: external power setpoint via analog input related to rP_Nom mA at point 1 *) (* OldName:p_soll_i1; Cycle: *)
		rMainsExport_max : REAL; (*PARA [13625]: meter	Mains Export maximum	*)
		rMainsExport_max_trip : REAL; (*PARA [13626]: meter	Mains Export maximum trip True/False *)
		rMainsImport_max : REAL; (*PARA [13623]: meter	Mains Import maximum	*)
		rMainsImport_max_trip : REAL; (*PARA [13624]: meter	Mains Import maximum trip True/False *)
		rN_EngNom : REAL; (*= nominal speed (for conversion of rN_Eng_Norm*)
		rN_EngStart_HyHi : REAL; (*	*) (* OldName: new PV; Cycle: 5; *)
		rN_EngStart_LimHi : REAL; (* *) (* OldName: new PV; Cycle: 5; *)
		rN_Set_ExtAI_NormScalMax : REAL; (*PARA [11780]: external speed setpoint via analog input related to rN_EngNom N at point 2 *) (* OldName:n_p2; Cycle: *)
		rN_Set_ExtAI_NormScalMin : REAL; (*PARA [11781]: external speed setpoint via analog input related to rN_EngNom N at point 1 *) (* OldName:n_p1; Cycle: *)
		rPRamp_FC_DecGrad_Norm : REAL; (*PARA [13457]: power ramp decrease with Frequency control *)
		rPRamp_FC_IncGrad_Norm : REAL; (*PARA [13456]: power ramp increase with Frequency control *)
		rPr_ECWScalMax : REAL; (*PARA [11806]: Pressure engine cooling water scale maximum*) (*OldName: MBE_KWD; Cycle: 5;*)
		rPr_EngLubOilScalMax : REAL; (*PARA [11807]: Oil pressure scale maximum*) (*OldName: MBE_ODR; Cycle: 5;*)
		rP_Custom1_Norm_HyHi : REAL; (* *) (*OldName: HY_PGW1; Cycle: 5;*)
		rP_Custom1_Norm_LimHi : REAL; (* *) (*OldName: Z_GW_PGW1; Cycle: 5;*)
		rP_Mns_AnaIn_ScalMax : REAL; (*	scale maximum *)
		rP_Mns_AnaIn_ScalMin : REAL; (*	scale minimum *)
		rP_Red_AI_NormScalMax : REAL; (*PARA [11788]: power reduction by analog input P at point 2 *) (* OldName:p_red_p2; Cycle: *)
		rP_Red_AI_NormScalMin : REAL; (*PARA [11789]: power reduction by analog input P at point 1 *) (* OldName:p_red_p1; Cycle: *)
		rP_Red_Ch_T2s : ARRAY[0..4]OF REAL; (*PARA [10149]: value for power reduction by charge temperature t2' [%Pnom/degC]*) (*OldName: dp_gr; Cycle: 2;*) (*V04.00.00.00*)
		rP_Red_EVU_Stage1 : REAL; (*value of power reduction when input tDI_Dem_P_Red_EVU_Stage1 is aktive*) (*OldName: ssPowRed_Utility_1; Cycle: 5;*)
		rP_Red_EVU_Stage2 : REAL; (*value of power reduction when input tDI_Dem_P_Red_EVU_Stage2 is aktive*) (*OldName: ssPowRed_Utility_2; Cycle: 5;*)
		rP_Red_EVU_Stage3 : REAL; (*value of power reduction when input tDI_Dem_P_Red_EVU_Stage3 is aktive*) (*OldName: ssPowRed_Utility_3; Cycle: 5;*)
		rP_Red_EVU_Stage4 : REAL; (*value of power reduction when input tDI_Dem_P_Red_EVU_Stage4 is aktive*) (*OldName: ssPowRed_Utility_4; Cycle: 5;*)
		rP_Red_EVU_Stage5 : REAL; (*value of power reduction when input tDI_Dem_P_Red_EVU_Stage5 is aktive*) (*OldName: ssPowRed_Utility_5; Cycle: 5;*)
		rP_Set1_ExtDI_Norm : REAL; (*reactivated with V4.03*) (*OldName: ssExtPwrSetP1; Cycle 5;*)
		rP_Set2_ExtDI_Norm : REAL; (*reactivated with V4.03*) (*OldName: ssExtPwrSetP2; Cycle 5;*)
		rP_Set3_ExtDI_Norm : REAL; (*reactivated with V4.03*) (*OldName: ssExtPwrSetP3; Cycle 5;*)
		rP_Set4_ExtDI_Norm : REAL; (*reactivated with V4.03*) (*OldName: ssExtPwrSetP4; Cycle 5;*)
		rP_Set5_ExtDI_Norm : REAL; (*again included in V4.03*) (*OldName: ssExtPwrSetP4; Cycle 5;*)
		rP_Set_Default_Norm : REAL; (* Droop default Para value normalized*)
		rP_Set_ExtAI_NormScalMax : REAL; (*PARA [11794]: external power setpoint via analog input related to rP_Nom P at point 2 *) (* OldName:p_soll_p2; Cycle: *)
		rP_Set_ExtAI_NormScalMin : REAL; (*PARA [11795]: external power setpoint via analog input related to rP_Nom P at point 1 *) (* OldName:p_soll_p1; Cycle: *)
		rSetMarg_FC_neg : REAL; (*PARA [13436]: PRL default activation power negative [% P_nom]*)
		rSetMarg_FC_pos : REAL; (*PARA [13435]: PRL default activation power positve [% P_nom]*)
		rSetMarg_FC_StaInp : REAL; (*PARA [13433]: Margin [%] for Standard Input*)
		rSetMarg_FC_StaInp_Neg : REAL; (*PARA [13968]: Margin [%] for Standard Input Negative*)
		rTime_Dem_Off_delay : REAL; (*PARA [13845]: Shut down delay [sec]*)
		rTime_Dem_On_delay : REAL; (*PARA [13844]: Demand delay [sec]*)
		rTime_Trip_MainsExport : REAL; (*Parameter	Shut down delay at limit exceeded *)
		rTime_Trip_MainsImort : REAL; (*Parameter	Shut down delay at limit exceeded *)
		rT_AirOutdoor_LimHi3 : REAL; (*spare, prepared, read- only*)
		rT_AirOutdoor_LimHi4 : REAL; (*spare, prepared, read- only*)
		rT_Ch_LimHi1 : REAL; (*PARA [11932]: charge temperature high limit 1 [degC]*) (*OldName:GW_LLGW1; Cycle:5;*)
		rT_Ch_LimHi2 : REAL; (*PARA [11933]: charge temperature high limit 2 [degC]*) (*OldName:GW_LLGW2; Cycle:5;*)
		rT_Ch_T2s_Hi : ARRAY[0..4]OF REAL; (*PARA [10158]: charge temperature t2' maximum [degC]*) (*OldName: gem_red; Cycle: 2;*) (*V04.00.00.00*)
		rU_Knck_Lim : REAL; (*  limit value for knock detection  *) (* OldName: KlopfLimit ; Cycle:   *)
		tCtr_Cust1 : _tGeACtrPara; (*  customizable controllers without predefined purpose	*) (* OldName: REG1; Cycle: 5; *)
		tCtr_Cust2 : _tGeACtrPara; (*  customizable controllers without predefined purpose	*) (* OldName: REG2; Cycle: 5; *)
		tCtr_Cust3 : _tGeACtrPara; (*  customizable controllers without predefined purpose	*) (* OldName: REG3; Cycle: 5; *)
		tCtr_Cust4 : _tGeACtrPara; (*  customizable controllers without predefined purpose	*) (* OldName: REG4; Cycle: 5; *)
		tCtr_Cust5 : _tGeACtrPara; (*  customizable controllers without predefined purpose	*) (* OldName: REG5; Cycle: 5; *)
		tCtr_Cust6 : _tGeACtrPara; (*  customizable controllers without predefined purpose	*) (* OldName: REG6; Cycle: 5; *)
		tCtr_Cust7 : _tGeACtrPara; (*  customizable controllers without predefined purpose	*) (* OldName: REG7; Cycle: 5; *)
		tCtr_Cust8 : _tGeACtrPara; (*  customizable controllers without predefined purpose	*) (* OldName: REG8; Cycle: 5; *)
		tCtr_Cust21 : _tGeACtrPara; (*  customizable controllers without predefined purpose	*) (* OldName: new PV; Cycle: 5; *)
		tCtr_Cust22 : _tGeACtrPara; (*  customizable controllers without predefined purpose	*) (* OldName: new PV; Cycle: 5; *)
		tCtr_Cust23 : _tGeACtrPara; (*  customizable controllers without predefined purpose	*) (* OldName: new PV; Cycle: 5; *)
		tCtr_Cust24 : _tGeACtrPara; (*  customizable controllers without predefined purpose	*) (* OldName: new PV; Cycle: 5; *)
		tCtr_Cust25 : _tGeACtrPara; (*  customizable controllers without predefined purpose	*) (* OldName: new PV; Cycle: 5; *)
		tCtr_Cust26 : _tGeACtrPara; (*  customizable controllers without predefined purpose	*) (* OldName: new PV; Cycle: 5; *)
		tCtr_Cust27 : _tGeACtrPara; (*  customizable controllers without predefined purpose	*) (* OldName: new PV; Cycle: 5; *)
		tCtr_Cust28 : _tGeACtrPara; (*  customizable controllers without predefined purpose	*) (* OldName: new PV; Cycle: 5; *)
		tCtr_Cust41 : _tGeACtrPara; (*  customizable controllers without predefined purpose	*) (* OldName: new PV; Cycle: 5; *)
		tCtr_Cust42 : _tGeACtrPara; (*  customizable controllers without predefined purpose	*) (* OldName: new PV; Cycle: 5; *)
		tCtr_Cust43 : _tGeACtrPara; (*  customizable controllers without predefined purpose	*) (* OldName: new PV; Cycle: 5; *)
		tCtr_Cust44 : _tGeACtrPara; (*  customizable controllers without predefined purpose	*) (* OldName: new PV; Cycle: 5; *)
		tCtr_Cust45 : _tGeACtrPara; (*  customizable controllers without predefined purpose	*) (* OldName: new PV; Cycle: 5; *)
		tCtr_Mns : _tGeACtrPara; (*  mains power controller	*) (* OldName: REGx; Cycle: 5; *)
		tiDelay_MsgAutoReset : TIME; (*Prototype Parameter*)
		tiSetTime_FC_POR : TIME; (*PARA [13444]: POR (Primary Operational Reserve) time*)
		tiSetTime_FC_PRamp : TIME; (*PARA [13500]: power ramp time for Frequency control [s]*)
		tiSetTime_FC_RR : TIME; (*PARA [13452]: RR (Replacement Reserve) time*)
		tiSetTime_FC_SOR : TIME; (*PARA [13446]: SOR (Secondary Operational Reserve) time*)
		tiSetTime_FC_SR : TIME; (*PARA [13454]: SR (Substitute Reserve) time*)
		tiSetTime_FC_TOR : TIME; (*PARA [13448]: TOR (Tertiary Operational Reserve) time*)
		tiSetTime_FC_TOR2 : TIME; (*PARA [13450]: TOR 2 (Tertiary 2 Operational Reserve) time*)
		zz_V4_0_ParaVersionEnd : REAL := 4.14; (*! ADD NEW PARAMETER preferably below this line, for easier visibility of new stuff. But since Para positioning in this list  is not sensitive anymore, declaration file is free to be sortet alphabetical as needed*) (* OldName: new PV; Cycle: 5; *)
		tiFreshOilPump_Delay : TIME; (*AG V4.14 new- check AdditionalPLCTag before use*)
		tiFreshOilPump_RTC_Time : TIME; (*AG V4.14 new- check AdditionalPLCTag before use*)
		iSource_U_OffsSet : INT; (*PARA [14298]: Voltage offset set point in island mode: 0= no setpoint, 1= Droop, 2= External *)
		bBS_Enable : BOOL; (*PARA [12179]: black start enable *)
		iSel_Customer : DINT; (*PARA [14950]: 0 = no special, 1 = AB Energy, 2 = Aggreko, 3 = 2G, etc.... *)
		bComm_OpcUa_Active : BOOL; (*PARA [15018]: OPC UA customer communication active*)
		tPlantComm : tPlantComm_Para; (*Parameters for the Plant Communication*)
		iOpt_Compatible_OpHoursFormat : USINT := 0; (*PARA[15081]  0=default option for plants with signed int customer logic (HW*32767+LW),  2= 32bit counter=HighWord & LowWord unsigned, 1= compaible V4.7 Mode for Plants with <V4.07 engines and previous adopted customer logic*)
	END_STRUCT;
END_TYPE
