
TYPE
	IN_GR_struct : 	STRUCT 
		tAB2GR : AmmBase2MM; (*AMM structure*) (*OldName: new PV; Cycle: 5;*)
		tPB2MM : ParaBase2MM_type; (* Data exchange structure TO ParaBase*) (*OldName:new PV;Cycle:5	*)
		iSt_OpMode : UDINT; (* engine operation mode *) (*OldName: new PV; Cycle:2; *)
		bGenC_PFBC_SetCOn : BOOL; (* bus: setpoint  genetaror power factor (COS PHI) from EU - on (activate) *) (* OldName: BUS_GCQ_PF_S; Cycle:5; *)
		bGenC_PFBC_SetCOf : BOOL; (* bus: setpoint  genetaror power factor (COS PHI) from EU - off (deactivate) *) (* OldName: BUS_GCQ_PF_R; Cycle:5; *)
		bGenC_QBC_SetCOn : BOOL; (* bus: setpoint reactive power (Q) from EU - on (activate) *) (* OldName: BUS_GCQ_Q_S; Cycle:5; *)
		bGenC_QBC_SetCOf : BOOL; (* bus: setpoint reactive power (Q) from EU - off (deactivate) *) (* OldName: BUS_GCQ_Q_R; Cycle:5; *)
		bGenC_QLimBC_SetCOn : BOOL; (* bus: setpoint reactive power limitation (Qlim) from EU - on (activate) *) (* OldName: BUS_GCQ_Qlim_S; Cycle:5; *)
		bGenC_QLimBC_SetCOf : BOOL; (* bus: setpoint reactive power limitation (Qlim) from EU - off (deactivate) *) (* OldName: BUS_GCQ_Qlim_R; Cycle:5; *)
		bGenC_QPCBC_SetCOn : BOOL; (* bus: setpoint reactive power characteristics COS(phi)=f(P) from EU - on (activate) *) (* OldName: BUS_GCQ_PFP_S; Cycle:5; *)
		bGenC_QPCBC_SetCOf : BOOL; (* bus: setpoint reactive power characteristics COS(phi)=f(P) from - off (deactivate) *) (* OldName: BUS_GCQ_PFP_R; Cycle:5; *)
		bGenC_UQBC_SetCOn : BOOL; (* bus: setpoint generator voltage for rective power - on (activate) *) (* OldName: BUS_GCQ_Uset_S; Cycle:5; *)
		bGenC_UQBC_SetCOf : BOOL; (* bus: setpoint generator voltage for rective power - off (deactivate) *) (* OldName: BUS_GCQ_Uset_R; Cycle:5; *)
		bGenC_QUCBC_SetCOn : BOOL; (* bus: setpoint reactive power characteristics Q=f(U) from EU -on (activate) *) (* OldName: BUS_GCQ_QU_S; Cycle:5; *)
		bGenC_QUCBC_SetCOf : BOOL; (* bus: setpoint reactive power characteristics Q=f(U) from EU -off (deactivate) *) (* OldName: BUS_GCQ_QU_R; Cycle:5; *)
		bGenC_PFUCBC_SetCOn : BOOL; (* bus: setpoint reactive power characteristics COS(phi)=f(U) from EU -on (active) *) (* OldName: BUS_GCQ_PFU_S; Cycle:5; *)
		bGenC_PFUCBC_SetCOf : BOOL; (* bus: setpoint reactive power characteristics COS(phi)=f(U) from EU -off (deactive) *) (* OldName: BUS_GCQ_PFU_R; Cycle:5; *)
		bGenC_PBC_SetCOn : BOOL; (* bus: setpoint power P from EU -on (activate) *) (* OldName: BUS_GCP_P_S; Cycle:5; *)
		bGenC_PBC_SetCOf : BOOL; (* bus: setpoint power P from EU -off (deactivate) *) (* OldName: BUS_GCP_P_R; Cycle:5; *)
		bGenC_PLimBC_SetCOn : BOOL; (* bus: power limition from  EU - on (activate) *) (* OldName: BUS_GCP_Plim_S; Cycle:5; *)
		bGenC_PLimBC_SetCOf : BOOL; (* bus: power limition from  EU - off (deactivate) *) (* OldName: BUS_GCP_Plim_R; Cycle:5; *)
		bGenC_PFCBC_SetCOn : BOOL; (* bus: primary frequency control - on (activate) *) (* OldName: BUS_GCP_PFC_S; Cycle:5; *)
		bGenC_PFCBC_SetCOf : BOOL; (* bus: primary frequency control - off (deactivate) *) (* OldName: BUS_GCP_PFC_R; Cycle:5; *)
		bGenC_RMCBC_SetCOn : BOOL; (* bus: regulation margin control -on (activate) *) (* OldName: BUS_GCP_RMC_S; Cycle:5; *)
		bGenC_RMCBC_SetCOf : BOOL; (* bus: regulation margin control -off (deactivate) *) (* OldName: BUS_GCP_RMC_R; Cycle:5; *)
		rGenC_PFBC : REAL; (* bus: scaling value genetaror power factor (COS PHI) from EU *) (* OldName: rBUS_GCQ_PF; Cycle:5; *)
		rGenC_QBC : REAL; (* bus: scaling value reactive power (Q) from EU *) (* OldName: rBUS_GCQ_Q; Cycle:5; *)
		rGenC_QLimBC : REAL; (* bus: scaling value for reactive power limitation for EVA BUS[kVAr] *) (* OldName: rBUS_GCQ_Qlim; Cycle:5; *)
		rGenC_UQBC : REAL; (* bus: scaling value generator voltage for reactive power (Q) *) (* OldName: rBUS_GCQ_Uset; Cycle:5; *)
		rGenC_PBC : REAL; (* bus: scaling value for power P from EU *) (* OldName: rBUS_GCP_P; Cycle:5; *)
		iGenC_PLimBC : INT; (* bus: setpoint power limitation (Plim) from EU - on (activate) *) (* OldName: BUS_GCP_Plim; Cycle:5; *)
		rGenC_PLimBC : REAL; (* bus: scaling value power limitation from EU *) (* OldName: rBUS_GCP_Plim; Cycle:5; *)
		tPF_CUSTGenC : HALioAi_Type; (* customiz: scaling value genetaror power factor (COS PHI) from EU *) (* OldName: rCUST_GCQ_PF; Cycle:5; *)
		tQ_GenC_CUST : HALioAi_Type; (* costumiz: scaling value for reactive power (Q) from EU *) (* OldName: rCUST_GCQ_Q; Cycle:5; *)
		tU_GenC_SetCUST : HALioAi_Type; (* costumiz: scaling value for generator voltage for reactive power from EU *) (* OldName: rCUST_GCQ_Uset; Cycle:5; *)
		bQ_GenC_SetErrBC : BOOL; (* W3594 - Q setpoint BUS EU error - use Backupvalue *) (* OldName: bMSST_BUS_GCQ_Q; Cycle:5; *)
		bP_GenC_SetErr : BOOL; (* Generator power setpoint measuring signal failure *) (* OldName: bMSST_BUS_GCP_P; Cycle:5; *)
		bP_GenC_SetErrPlim : BOOL; (* Leistungslimitierung BUS EU gestört - Backupwert verwenden *) (* OldName: bMSST_BUS_GCP_Plim; Cycle:5; *)
		bQ_GenC_SetErrQlim : BOOL; (* W3595 - reactive power limitation meassur signal error *) (* OldName: bMSST_BUS_GCQ_Qlim; Cycle:5; *)
		bPFBC_GenC_SetErrBC : BOOL; (* bus: setpoint generator power factor (COS PHI) from EU error - use backupvalue *) (* OldName: bMSST_BUS_GCQ_PF; Cycle:5; *)
		bU_GenC_SetErrBC : BOOL; (* bus: setpoint voltage from EU error - use backupvalue *)
		PF_GenC_SetFix1 : BOOL; (* setpoint  genetaror power factor (COS PHI) - Fixvalue 1 from EU *)
		PF_GenC_SetFix2 : BOOL; (* setpoint  genetaror power factor (COS PHI) - Fixvalue 2 from EU *)
		PF_GenC_SetFix3 : BOOL; (* setpoint  genetaror power factor (COS PHI) - Fixvalue 3 from EU *)
		PF_GenC_SetFix4 : BOOL; (* setpoint  genetaror power factor (COS PHI) - Fixvalue 4 from EU *)
		PF_GenC_SetFix5 : BOOL; (* setpoint  genetaror power factor (COS PHI) - Fixvalue 5 from EU *)
		Q_GenC_SetFix1 : BOOL; (* reactive power (Q) - Q-fixvalue 1 from EU *)
		Q_GenC_SetFix2 : BOOL; (* reactive power (Q) - Q-fixvalue 2 from EU *)
		Q_GenC_SetFix3 : BOOL; (* reactive power (Q) - Q-fixvalue 3 from EU *)
		Q_GenC_SetFix4 : BOOL; (* reactive power (Q) - Q-fixvalue 4 from EU *)
		Q_GenC_SetFix5 : BOOL; (* reactive power (Q) - Q-fixvalue 5 from EU *)
		P_GenC_SetFix1 : BOOL; (*power value - P- fixvalue 1 from EU *) (* OldName: DI_GCP_P_FIX1; Cycle:HALioDi_Type; *)
		P_GenC_SetFix2 : BOOL; (*power value - P- fixvalue 2 from EU *) (* OldName: DI_GCP_P_FIX2; Cycle:HALioDi_Type; *)
		P_GenC_SetFix3 : BOOL; (*power value - P- fixvalue 3 from EU *) (* OldName: DI_GCP_P_FIX3; Cycle:HALioDi_Type; *)
		P_GenC_SetFix4 : BOOL; (*power value - P- fixvalue 4 from EU *) (* OldName: DI_GCP_P_FIX4; Cycle:HALioDi_Type; *)
		P_GenC_SetFix5 : BOOL; (*power value - P- fixvalue 5 from EU *) (* OldName: DI_GCP_P_FIX5; Cycle:HALioDi_Type; *)
		PLim_GenC_SetEUPFix1 : BOOL; (* power limitation fixvalue 1 *) (* OldName: DI_EVU_1; Cycle:HALioDi_Type; *)
		PLim_GenC_SetEUPFix2 : BOOL; (* power limitation fixvalue 2 *) (* OldName: DI_EVU_2; Cycle:HALioDi_Type; *)
		PLim_GenC_SetEUPFix3 : BOOL; (* power limitation fixvalue 3 *) (* OldName: DI_EVU_3; Cycle:HALioDi_Type; *)
		PLim_GenC_SetEUPFix4 : BOOL; (* power limitation fixvalue 4 *) (* OldName: DI_EVU_4; Cycle:HALioDi_Type; *)
		PLim_GenC_SetEUPFix5 : BOOL; (* power limitation fixvalue 5 *) (* OldName: DI_EVU_5; Cycle:HALioDi_Type; *)
		tPF_GenC_SetEU : HALioAi_Type; (* AI: setpoint  genetaror power factor (COS PHI) from EU *) (* OldName: AI_GCQ_PF; Cycle:HALioAi_Type; *)
		tQ_GenC_SetEU : HALioAi_Type; (* AI: setpoint reactive power characteristic (Q) from EU *) (* OldName: AI_GCQ_Q; Cycle:HALioAi_Type; *)
		tQLim_GenC_SetEU : HALioAi_Type; (* AI: setpoint reactive power limitation (Qlim) from EU *) (* OldName: AI_GCQ_Qlim; Cycle:HALioAi_Type; *)
		tQU_GenC_Set : HALioAi_Type; (* AI: setpoint generator voltage for rective power control[%] vor EU *) (* OldName: AI_GCQ_Uset; Cycle:HALioAi_Type; *)
		tP_GenC_SetEU : HALioAi_Type; (* AI: request power value from EU *) (* OldName: AI_GCP_P; Cycle:HALioAi_Type; *)
		tPLim_GenC_SetEU : HALioAi_Type; (* AI: setpoint power limitation (Plim) from EU *) (* OldName: AI_GCP_Plim; Cycle:HALioAi_Type; *)
		rP_Act_Norm_Filt : REAL; (* actual power related to rP_nom filtered T=1s *) (*OldName:P_IST_PROM;Cycle:2;*)
		tU_MMD_Synch1 : ARRAY[0..2]OF HALioAi_Type; (* synchronization voltage 1*)
		tU_MMD_Synch2 : ARRAY[0..2]OF HALioAi_Type; (* synchronization voltage 2*)
		tU_L1L2 : ARRAY[0..2]OF HALioAi_Type; (* generator voltage phase 1_2 [V] *) (*OldName:ssUL1L2[1];Cycle:2;*)
		tU_L1N : ARRAY[0..2]OF HALioAi_Type; (* generator voltage phase 1_N [V] *) (*OldName:ssUL1N[1];Cycle:2;*)
		tU_L2L3 : ARRAY[0..2]OF HALioAi_Type; (* generator voltage phase 2_3 [V] *) (*OldName:ssUL2L3[1];Cycle:2;*)
		tU_L2N : ARRAY[0..2]OF HALioAi_Type; (* generator voltage phase 2_N [V] *) (*OldName:ssUL2N[1];Cycle:2;*)
		tU_L3L1 : ARRAY[0..2]OF HALioAi_Type; (* generator voltage phase 3_1 [V] *) (*OldName:ssUL3L1[1];Cycle:2;*)
		tU_L3N : ARRAY[0..2]OF HALioAi_Type; (* generator voltage phase 3_N [V] *) (*OldName:ssUL3N[1];Cycle:2;*)
		tU_Avg : ARRAY[0..2]OF HALioAi_Type; (* actual generator average voltage*) (*OldName:ssUAvg[1];Cycle:2;*)
		tP_Act : ARRAY[0..2]OF HALioAi_Type; (* actual electric power [kW]*) (*OldName:ssPAct[1];Cycle:2;*)
		tQ_Act : ARRAY[0..2]OF HALioAi_Type; (* actual reactive power [kVar]*) (*OldName:ssQAct[1];Cycle:2;*)
		tS_Act : ARRAY[0..2]OF HALioAi_Type; (*appearent power [kV] *) (*OldName:ssSAct[1];Cycle:2;*)
		tF_MMD : ARRAY[0..2]OF HALioAi_Type; (*actuel generator frequence*)
		iIdx_RSS : INT; (*inex of request selector switch - 0..OFF, 1..ON, 2..REMOTE *) (*OldName:new PV;Cycle:2;*)
		iIdx_OMSS : INT; (*Index of operation mode selector switch 0  OFF, 1  MANUAL, 2  AUTOMATIC, 3 Test (Optional)*) (*OldName:BWS_HA,PROBE; Cycle:5;*)
		tPF_Act : ARRAY[0..2]OF HALioAi_Type; (* power factor, actual cos phi value *)
		rP_Set_Min_Norm : REAL; (*Minimal power setpoint related to rP_nom p.u.*) (*OldName:PN_GASART;Cycle:2;*)
		rP_Nom : REAL; (* nominal electric power [KW], depends on gastype *) (*OldName:PN_GASART;Cycle:2;*)
		tDI_Dem_EU_Block : HALioDi_Type; (*external request from utility (evu). power reduction *) (*OldName: DI_EVU; Cycle: 5;*)
		tMCB_On : HALioDi_Type; (* SS447 Netzschalter EIN  *) (*OldName: MCB_ON	; Cycle: 5;*)
		iIdx_Pset_Type : INT; (* power setpoint type *) (*OldName:usPowerSetpTyp;Cycle:5;*)
		iIdx_Pred_Type : INT; (* Index for type of power reduction *) (*OldName:usPowerRedTyp;Cycle:5;*)
		tMnsOk : HALioDi_Type; (*DI mains ok	*) (*OldName:DI_MNS_OK;Cycle:2*)
		bP_Ramp_Target_Reached : BOOL; (* ramp of power set value has reached the target value *) (*OldName:new PV;Cycle:2;*)
		rPF_AO_PF_U : REAL; (* power factor generator controller *) (* OldName:AO_PF_gen_V;Cycle:5*) (*E *****  ERDF *)
		tMCB_Dcp_SetEUCOn : HALioDi_Type; (* DI: set requirement  decoupling from EU(ERDF),DIs *) (*OldName:DI_SDemandMCBoff PV;Cycle:2;*)
		tMCB_Dcp_SetEUCOf : HALioDi_Type; (* DI: rest requirement decoupling from EU(ERDF),DIs *) (*OldName:DI_RDemandMCBoff PV;Cycle:2;*)
		tMCB_Rel_Sync : HALioDi_Type; (* DI: release synchronization from EU(ERDF) *) (*OldName:DI_ReleaseMCBon PV;Cycle:2;*)
		tMCB_DcpQu_SetEUCOn : HALioDi_Type; (* DI: set decoupling quickly from EU (ERDF) *) (*OldName:DI_SFDemMCBoff PV;Cycle:2;*)
		tMCB_DcpQu_SetEUCOf : HALioDi_Type; (* DI: reset decoupling quickly from EU (ERDF) *) (*OldName:DI_RFDemMCBoff PV;Cycle:2;*)
		tRSE_SetEUCOn : HALioDi_Type; (* DI: set decoupling RSE from EU (ERDF) *) (*OldName:DI_SDEmRSE PV;Cycle:2;*)
		tRSE_SetEUCOf : HALioDi_Type; (* DI: reset decoupling RSE from EU (ERDF) *) (*OldName:DI_RDEmRSE PV;Cycle:2;*)
		tP0_BLOCK_DEIE : HALioDi_Type; (* DI : Installed 1/0 switch *) (*OldName:Cust_switch_erdf PV;Cycle:2;*)
		tGCB_On : HALioDi_Type; (* DI: generator circuit breaker closed *) (*OldName:DI_GCB_ON; Cycle:5;*) (*OldName: GCB_ON ; Cycle:2; *)
		tMnsOk_GTE : HALioDi_Type; (*DI mains ok GTE monitoring device, france country specific*) (*OldName:DI_GTE; Cycle:5;*) (* ERDF A*)
		tCustAnaIn : ARRAY[0..120]OF HALioAi_Type; (*Replacement for RAN_KANAL...*) (*OldName: ANA_RAN	; Cycle: 5;*)
		rCust_SparePara : ARRAY[0..200]OF REAL; (*SPS_REZP1 to SPS_REZP200*) (*OldName: SPS_REZP1, SPS_REZP2, SPS_REZP3, SPS_REZP16 ; Cycle: 5;*)
		tCustDigIn : ARRAY[0..200]OF HALioDi_Type; (*new, reserved for Project specific use*) (*OldName: new PV	; Cycle: 5;*)
		rPFSoll_lin_GC2GR : REAL; (* PFSoll_lin von GenRegFunct. 1-7 *) (* OldName: PFSoll_lin;Cycle:2;*) (* Gridcode interface added *)
		rP_Set_Unred_Norm : REAL; (* normed power set value without reductions *) (*OldName:P_UNRED;Cycle:5;*)
		tF_MMD_Synch2 : ARRAY[0..2]OF HALioAi_Type; (* *) (*OldName:usSynch2Frequency;Cycle:2;*)
		bPF_GenC_SetEUCOn : BOOL; (* setpoint  genetaror power factor (COS PHI) from EU - on (activate)  *) (* OldName: DI_GCQ_PF_S; Cycle:HALioDi_Type; *)
		bPF_GenC_SetEUCOf : BOOL; (* setpoint  genetaror power factor (COS PHI) from EVA - off (deactivate)  *) (* OldName: DI_GCQ_PF_R; Cycle:HALioDi_Type; *)
		bQ_GenC_SetEUCOn : BOOL; (* setpoint reactive power characteristic (Q) from EU - on (activate) *) (* OldName: DI_GCQ_Q_S; Cycle:HALioDi_Type; *)
		bQ_GenC_SetEUCOf : BOOL; (* setpoint reactive power characteristic (Q) from EU - off (deactivate) *) (* OldName: DI_GCQ_Q_R; Cycle:HALioDi_Type; *)
		bQLim_GenC_SetEUCOn : BOOL; (* setpoint reactive power limitation (Qlim) from EU - on (activate) *) (* OldName: DI_GCQ_Qlim_S; Cycle:HALioDi_Type; *)
		bQLim_GenC_SetEUCOf : BOOL; (* setpoint reactive power limitation (Qlim) from EU - off (deactivate) *) (* OldName: DI_GCQ_Qlim_R; Cycle:HALioDi_Type; *)
		bUist_max : BOOL; (*TRUE = Uist für Q(U) & cosphi(U) ist max. Generatorspannung Ph-Ph, FALSE = durchschnittliche Generatorspannung Ph-Ph*)
		bQUC_GenC_SetEUCOn : BOOL; (* setpoint reactive power characteristics Q=f(U) from EU -on (activate) *) (* OldName: DI_GCQ_QU_S; Cycle:HALioDi_Type; *)
		bQUC_GenC_SetEUCOf : BOOL; (* setpoint reactive power characteristics Q=f(U) from EU -off (deactivate) *) (* OldName: DI_GCQ_QU_R; Cycle:HALioDi_Type; *)
		bPFUC_GenC_SetEUCOn : BOOL; (* setpoint reactive power characteristics COS(phi)=f(U) von EU -on (active) *) (* OldName: DI_GCQ_PFU_S; Cycle:HALioDi_Type; *)
		bPFUC_GenC_SetEUCOf : BOOL; (* setpoint reactive power characteristics COS(phi)=f(U) von EU -off (deactive) *) (* OldName: DI_GCQ_PFU_R; Cycle:HALioDi_Type; *)
		bP_GenC_SetEUCOn : BOOL; (* request power value from EU - on (activate) *) (* OldName: DI_GCP_P_S; Cycle:HALioDi_Type; *)
		bP_GenC_SetEUCOf : BOOL; (* request power value from EU - off (deactivate) *) (* OldName: DI_GCP_P_R; Cycle:HALioDi_Type; *)
		bPFC_SetCOn : BOOL; (* primary frequency control - on (activate) *) (* OldName: DI_GCP_PFC_S; Cycle:HALioDi_Type; *)
		bPFC_SetCOf : BOOL; (* primary frequency control - off (deactivate) *) (* OldName: DI_GCP_PFC_R; Cycle:HALioDi_Type; *)
		bQPC_GenC_SetEUCOn : BOOL; (* setpoint reactive power characteristics cosphi=f(P) from EU - on (activate) *)
		bQPC_GenC_SetEUCOf : BOOL; (* setpoint reactive power characteristics cosphi=f(P) from EU - off (deactivate) *)
		bPLim_GenC_SetEUCOn : BOOL; (* setpoint power limitation (Plim) from EU - on (activate) *) (* OldName: DI_GCP_Plim_S; Cycle:HALioDi_Type; *)
		bPLim_GenC_SetEUCOf : BOOL; (* setpoint power limitation (Plim) from EU - off (deactivate) *) (* OldName: DI_GCP_Plim_R; Cycle:HALioDi_Type; *)
		bRMC_SetCOn : BOOL; (* regulation margin control -on (activate) *) (* OldName: DI_GCP_RMC_S; Cycle:HALioDi_Type; *)
		bRMC_SetCOf : BOOL; (* regulation margin control -off (deactivate) *) (* OldName: DI_GCP_RMC_R; Cycle:HALioDi_Type; *)
		tF_MMD_BusBar : ARRAY[0..2]OF HALioAi_Type; (*actuel busbar frequence [10mHz]*)
		bGenC_QLimSetErrBC : BOOL; (* bus: setpoint reactive power limitation from EU error - use backupvalue *)
		iGenC_PrioQ : USINT; (* Prioritet  reactive power (Q) - fixvalue *) (* OldName: usPrio_Qset; Cycle:5; *)
		iGenC_PrioQUC : USINT; (* Prioritet  reactive power characteristic Q=f(U) *) (* OldName: usPrio_Q_U; Cycle:5; *)
		iGenC_PrioPFUC : USINT; (* Prioritet  reactive power characteristic COS(phi)=f(U) *) (* OldName: usPrio_PF_U; Cycle:5; *)
		iGenC_PrioPFPC : USINT; (* Prioritet  reactive power characteristic COS(phi)=f(P) *) (* OldName: usPrio_PF_P; Cycle:5; *)
		iGenC_PrioPF : USINT; (* Prioritet  genetaror power factor (COS(phi)) - fixvalue *) (* OldName: usPrio_PFset; Cycle:5; *)
		iGenC_PrioQP : USINT; (* Prioritet  reactive power characteristic Q=f(P)  *)
		iGenC_PrioQCustSet : USINT; (* Prioritet  reactive power Q customized 	*)
		iGenC_PrioQUset : USINT; (* Prioritet  reactive power U control(Q) -    *)
		iPassLevel : INT; (*pass level actual*) (*OldName:ucPassLevel; Cycle:2;*)
		rP_RMC_FC_pos : REAL; (*positive reserve power for frequency control*)
		rP_RMC_FC_neg : REAL; (*negative reserve power for frequency control*)
		rDroop_FC_pos : REAL; (*positive droop for frequency control*)
		rDroop_FC_neg : REAL; (*negative droop for frequency control*)
		bBus_Dem : BOOL; (*demand over bus and no bus failure*)
		bSet_ILF_COn_Bus : BOOL; (*demand on local frequency integrator over bus*)
		bSet_ILF_COf_Bus : BOOL; (*demand off local frequency integrator over bus*)
		bILF_SetCOn : BOOL; (*demand local frequency integrator on over hardwire*)
		bILF_SetCOf : BOOL; (*demand local frequency integrator off over hardwire*)
		bSet_FC_COn_Bus : BOOL; (*demand on frequency control over bus*)
		bSet_FC_COf_Bus : BOOL; (*demand off  frequency control over bus*)
		bFC_SetCOn : BOOL; (*demand frequency control on over hardwire*)
		bFC_SetCOf : BOOL; (*demand frequency control off over hardwire*)
		rF_Nom : REAL; (*nominal frequency [Hz]*)
		rF_MMD_FC : REAL; (*actual frequency for frequency control [Hz]*)
		rP_Set_FC : REAL; (*generator power setpoint by frequency control [kW]*)
		rF_Act : REAL; (* actual frequency [Hz] *)
		rF_Ref : REAL; (* frequency setpoint [Hz]*)
		iIdx_Gtyp_Dem : INT; (*actual gassort 1..4*) (*OldName: gasart; Cycle: 5;*)
		rP_Red_Norm : REAL; (*power reduction related to rP_Nom*) (*OldName: RedPowerProm	; Cycle: 5;*)
		bP_Red_Active : BOOL; (*power reduction active - any kind *) (*OldName:PredAkt; Cycle:5;*)
		rP_Set_Unred_Norm_ohne_FC : REAL; (* normed power set value without reductions AND without (P)FC *)
		bEng_Dem : BOOL; (*module demanded*) (*OldName:M_AGFD; Cycle:5;*)
		tP_DEIE : HALioAi_Type;
		rP_Ramp_max_BR6_FC : REAL; (* maximum loadramp allowed for type 6 in FC mode *)
		bPU_SetCOn : BOOL; (*demand on P(U) over DIs*)
		bPU_SetCOf : BOOL; (*demand off  P(U) over DIs*)
		bGenC_PUBC_SetCOn : BOOL; (*demand on P(U) over Bus*)
		bGenC_PUBC_SetCOf : BOOL; (*demand off P(U) over Bus*)
		rU_Act_PointCtrl : REAL; (*actual voltage from point of control*)
		rPF_Set_TimeTable : REAL; (*power factor Time Table*)
		rQ_SetCust : REAL; (*Customer Reactive Power*)
		bU_GenC_SetEUCOn : BOOL; (*DI: Voltage control for reactive power - on (activated)*)
		bGenC_UBC_SetCOn : BOOL; (*Bus: Voltage control for reactive power - on (activated)*)
		bU_GenC_SetEUCOf : BOOL; (*DI: Voltage control for reactive power - off (deactivated)*)
		bGenC_UBC_SetCOf : BOOL; (*Bus: Voltage control for reactive power - off (deactivated)*)
		rP_POR_Act_Cust : REAL; (*actual active power used as point of reference [kW]*)
		rU_POR_Act_Cust : REAL; (*actual voltage used as point of reference [V]*)
		rQ_Cust : REAL; (*Customized Q setpoint [kVAr]*)
		bGenC_QCustBC_SetCOn : BOOL; (*bus: Customized Q setpoint - on (activate)*)
		bGenC_QCustBC_SetCOf : BOOL; (*bus: Customized Q setpoint - off (deactivate)*)
		bQP_GenC_SetEUCOn : BOOL; (* DI setpoint reactive power characteristics Q=f(P) from EU - on (activate) *)
		bQP_GenC_SetEUCOf : BOOL; (* DI setpoint reactive power characteristics Q=f(P) from EU - off (deactivate) *)
		bGenC_QPBC_SetCOn : BOOL; (* Bus setpoint reactive power characteristics Q=f(P) from EU - on (activate) *)
		bGenC_QPBC_SetCOf : BOOL; (* Bus setpoint reactive power characteristics Q=f(P) from EU - off (deactivate) *)
		rP_POC_Act_Cust : REAL; (*actual active power used as point of control [kW]*)
		rP_Set_Norm : REAL; (* power setpoint related to rP_Nom	*)
		bLockPlantBC_SetEUCOn : BOOL; (* lock plant(all modules) 1=locked *)
		tCU2GR : CUSTOM2GRID_Struct; (* Data exchange structure to Custom *)
		tHA2GR : HALIO2GRID_Struct; (* Data exchange structure to HALIO *)
		bEng_Block_EVU : BOOL; (* = 	BLOCK_EVU Engine shutdown by external utility(evu)demand *)
		bPowerRampEU_Ena : BOOL; (* Ramp from EU aktiv *)
		rF_Deadband_TB : REAL; (* Deadband for frequency filter *)
		ti_FreqFilt_TB : TIME; (* Time for frequency filter *)
		rFNom_LFSM_Ref : REAL; (*Frequency reference for FSM/LFSM [Hz]*)
		iSet_GrC_FSM : INT; (*Choice for FSM activation 0=not used, 1=Internal Setpoint, 2=External AI, 3=External Bus *)
		rP_Ramp_IncGrad_Norm : REAL; (*gradient for increase of power ramp in grid mode denpending on gastype [1/s]*)
		rP_Ramp_DecGrad_Norm : REAL; (*gradient for decrease of power ramp in grid mode denpending on gastype [1/s]*)
		tDem_EU_Block2 : HALioDi_Type; (*module blocked from grid operator - shutdown*)
		tDem_EU_Block3 : HALioDi_Type; (*module blocked from grid operator - demand off*)
		bBypassMCB_FSM : BOOL; (*TRUE if FSM should be available in island operation*)
		bDroopDB_Active : BOOL; (*The droop deadband remote and local/HMI setpoint data*)
		rDB_FSM_LFSM : REAL; (*Dead band setpoint to be used from custom*)
		bSet_LFSM_Test_COn : BOOL; (*LFSM Test command on external (DI or Bus)*)
		bLFSM_Test_Enabled : BOOL; (*FSM/LFSM  test enabled external*)
		rF_Act_FSM_Test_Ext : REAL; (*Actual frequency for FSM test via external signal*)
		bDem_EU_Block2_Bus : BOOL; (*module blocked from grid operator - shutdown via BUS*)
		bDem_EU_Block3_Bus : BOOL; (*module blocked from grid operator - demand off via BUS*)
	END_STRUCT;
	MM2VIS_GR_struct : 	STRUCT 
		bMsg2171 : BOOL; (* B2171 - FC response enabled *) (* OldName: new; Cyclic:5;  AFC/RMC response enabled *)
		bMsg2172 : BOOL; (* B2172 - FC response disabled *) (* OldName: new; Cyclic:5;  AFC/RMC response disabled *)
		bMsg2173 : BOOL; (* B2173 - HFR enabled *) (* OldName: new; Cyclic:5;  *)
		bMsg2174 : BOOL; (* B2174 - HFR disabled *) (* OldName: new; Cyclic:5;  *)
		bMsg2175 : BOOL; (* B2175 - POR enabled *) (* OldName: new; Cyclic:5;  *)
		bMsg2176 : BOOL; (* B2176 - POR disabled *) (* OldName: new; Cyclic:5;  *)
		bMsg2177 : BOOL; (* B2177 - SOR enabled *) (* OldName: new; Cyclic:5;  *)
		bMsg2178 : BOOL; (* B2178 - SOR disabled *) (* OldName: new; Cyclic:5;  *)
		bMsg2179 : BOOL; (* B2179 - TOR1 enabled *) (* OldName: new; Cyclic:5;  *)
		bMsg2180 : BOOL; (* B2180 - TOR1 disabled *) (* OldName: new; Cyclic:5;  *)
		bMsg2181 : BOOL; (* B2181 - TOR2 enabled *) (* OldName: new; Cyclic:5;  *)
		bMsg2182 : BOOL; (* B2182 - TOR2 disabled *) (* OldName: new; Cyclic:5;  *)
		bMsg2183 : BOOL; (* B2183 - RR enabled *) (* OldName: new; Cyclic:5;  *)
		bMsg2184 : BOOL; (* B2184 - RR disabled *) (* OldName: new; Cyclic:5;  *)
		bMsg2185 : BOOL; (* B2185 - SR enabled *) (* OldName: new; Cyclic:5;  *)
		bMsg2186 : BOOL; (* B2186 - SR disabled *) (* OldName: new; Cyclic:5;  *)
		bMsg2811 : BOOL; (* B2811 power limitation by utility *) (* OldName: B2811; Cyclic:5;  *)
		bMsg2812 : BOOL; (* B2812 module blocked by utility *) (* OldName: B2812; Cyclic:5;    *)
		bMsg2853 : BOOL; (* B2853 - RMC enabled *) (* OldName: bBM2853_RMC_ON; Cycle: 5 *)
		bMsg2854 : BOOL; (* B2854 - RMC disabled *) (* OldName: bBM2854_RMC_OFF; Cycle: 5 *)
		bMsg2855 : BOOL; (* B2855 - PFC enabled *) (* OldName: bBM2855_PFC_ON; Cycle: 5 *)
		bMsg2856 : BOOL; (* B2856 - PFC disabled *) (* OldName: bBM2856_PFC_OFF; Cycle: 5 *)
		bMsg2857 : BOOL; (* B2857 - Power setpoint by utility operator *) (* OldName: AW_EXPS_EVU; Cycle: 5 *)
		bMsg2858 : BOOL; (* B2858 - Power factor setpoint by utility operator enabled *) (* OldName: bBM2858_PFset_ON; Cycle: 5 *)
		bMsg2859 : BOOL; (* B2859 - Power factor setpoint by utility operator disabled *) (* OldName: bBM2859_PFset_OFF; Cycle: 5 *)
		bMsg2860 : BOOL; (* B2860 - Reactive power setpoint by utility operator enabled *) (* OldName: bBM2860_Qset_ON; Cycle: 5 *)
		bMsg2861 : BOOL; (* B2861 - Reactive power setpoint by utility operator disabled *) (* OldName: bBM2861_Qset_OFF; Cycle: 5 *)
		bMsg2862 : BOOL; (* B2862 - Reactive power limitation by utility operator *) (* OldName: bBM2862_Qlim; Cycle: 5 *)
		bMsg2863 : BOOL; (* B2863 - Reactive power limitation by utility operator enabled *) (* OldName: bBM2863_Qlim_ON; Cycle: 5 *)
		bMsg2864 : BOOL; (* B2864 - Reactive power limitation by utility operator disabled *) (* OldName: bBM2864_Qlim_OFF; Cycle: 5 *)
		bMsg2865 : BOOL; (* B2865 - cos phi (P) enabled *) (* OldName: bBM2865_PFP_ON; Cycle: 5 *)
		bMsg2866 : BOOL; (* B2866 - cos phi (P) disabled *) (* OldName: bBM2866_PFP_OFF; Cycle: 5 *)
		bMsg2867 : BOOL; (* B2867 - cos phi (U) enabled *) (* OldName: bBM2867_PFU_ON; Cycle: 5 *)
		bMsg2868 : BOOL; (* B2868 - cos phi (U) disabled *) (* OldName: bBM2868_PFU_OFF; Cycle: 5 *)
		bMsg2869 : BOOL; (* B2869 - Q(U) enabled *) (* OldName: bBM2869_QU_ON; Cycle: 5 *)
		bMsg2870 : BOOL; (* B2870 - Q(U) disabled *) (* OldName: bBM2870_QU_OFF; Cycle: 5 *)
		bMsg2940 : BOOL; (*B2940 - Q customized enabled*)
		bMsg2941 : BOOL; (*B2941 - Q customized disabled*)
		bMsg2942 : BOOL; (*B2942 - U control enabled*)
		bMsg2943 : BOOL; (*B2943 - U control disabled*)
		bMsg2944 : BOOL; (*B2944 - Q(P) enabled*)
		bMsg2945 : BOOL; (*B2945 - Q(P) disabled*)
		bMsg2946 : BOOL; (*B2946 - PF Time Table enabled*)
		bMsg2947 : BOOL; (*B2947 - PF Time Table disabled*)
		bMsg2948 : BOOL; (*B2948 - Test function Q(U) PF(U) active*)
		bMsg2949 : BOOL; (*B2949 - Q reduction based Q(U) limitation*)
		bMsg2950 : BOOL; (*B2950 - LFSM-O activated*)
		bMsg2951 : BOOL; (*B2951 - LFSM-O deactivated*)
		bMsg2952 : BOOL; (*B2952 - LFSM-U activated*)
		bMsg2953 : BOOL; (*B2953 - LFSM-U deactivated*)
		bMsg2954 : BOOL; (*B2954 - P(U) activated*)
		bMsg2955 : BOOL; (*B2955 - P(U) deactivated*)
		bMsg3384 : BOOL; (* A3384 DEIE fast decoupling *)
		bMsg3385 : BOOL; (* A3385 measuring signal failure P0 *)
		bMsg3386 : BOOL; (* A3386 Waiting release for SY DEIE *)
		bMsg3591 : BOOL; (* W3591 - Power limitation by utility operator measuring signal failure *) (* OldName: bMSST_GCP_Plim; Cycle: 5 *)
		bMsg3592 : BOOL; (* W3592 - Power setpoint by utility operator measuring signal failure *) (* OldName: bMSST_GCP_P; Cycle: 5 *)
		bMsg3593 : BOOL; (* W3593 - Power factor setpoint by utility operator measuring signal failure *) (* OldName: bMSST_GCQ_PF; Cycle: 5 *)
		bMsg3594 : BOOL; (* W3594 - Reactive power setpoint by utility operator measuring signal failure *) (* OldName: bMSST_GCQ_Q; Cycle: 5 *)
		bMsg3595 : BOOL; (* W3595 - Reactive power limitation by utility operator measuring signal failure *) (* OldName: bMSST_GCQ_Qlim; Cycle: 5 *)
		bMsg3596 : BOOL; (* W3596 - Voltage setpoint by utility operator measuring signal failure *) (* OldName: bMSST_GCQ_Uset; Cycle: 5 *)
		bMsg2331 : BOOL; (* A2331 - Unit shutdown due to explosion risk in the Junction Box - surge suppressor has reached critical pressure *)
		bMsg3000 : BOOL; (* B3000 - Module blocked by Grid module, data structure failure *)
		bMsg9008 : BOOL; (* B9008 - Positive droop LFSM-O setpoint by utility operator enabled *)
		bMsg9009 : BOOL; (* B9009 - Positive droop LFSM-O setpoint by utility operator disabled *)
		bMsg9010 : BOOL; (* B9010 - Negative droop LFSM-U setpoint by utility operator enabled *)
		bMsg9011 : BOOL; (* B9011 - Negative droop LFSM-U setpoint by utility operator disabled *)
		bMsg9012 : BOOL; (* B9012 - Positive droop FSM setpoint  by utility operator enabled *)
		bMsg9013 : BOOL; (* B9013 - Positive droop FSM setpoint by utility operator disabled *)
		bMsg9014 : BOOL; (* B9014 - Negative droop FSM setpoint by utility operator enabled *)
		bMsg9015 : BOOL; (* B9015 - Negative droop FSM setpoint by utility operator disabled *)
		bMsg9016 : BOOL; (* B9016 - Dead band positive FSM setpoint by utility operator enabled *)
		bMsg9017 : BOOL; (* B9017 - Dead band positive FSM setpoint by utility operator disabled *)
		bMsg9018 : BOOL; (* B9018 - Dead band negative FSM setpoint by utility operator enabled *)
		bMsg9019 : BOOL; (* B9019 - Dead band negative FSM setpoint by utility operator disabled *)
		bMsg9020 : BOOL; (* B9020 - Frequency threshold LFSM-O setpoint by utility operator enabled *)
		bMsg9021 : BOOL; (* B9021 - Frequency threshold LFSM-O setpoint by utility operator disabled *)
		bMsg9022 : BOOL; (* B9022 - Frequency threshold LFSM-U setpoint by utility operator enabled *)
		bMsg9023 : BOOL; (* B9023 - Frequency threshold LFSM-U setpoint by utility operator disabled *)
		bMsg9093 : BOOL; (* B9093 - Enable ILF*)
		bMsg9094 : BOOL; (* B9094 - Disable ILF*)
		bMsg9261 : BOOL; (* W9261 - Frequency limit LFSM-O by utility operator measuring signal failure *)
		bMsg9262 : BOOL; (* W9262 - Frequency limit LFSM-U by utility operator measuring signal failure *)
		bMsg9263 : BOOL; (* W9263 - Positive droop LFSM-O by utility operator measuring signal failure *)
		bMsg9264 : BOOL; (* W9264 - Negative droop LFSM-U by utility operator measuring signal failure *)
		bMsg9265 : BOOL; (* W9265 - Droop FSM-U by utility operator measuring signal failure *)
		bMsg9266 : BOOL; (* W9266 - Droop FSM-O by utility operator measuring signal failure *)
		bMsg9267 : BOOL; (* W9267 - Dead band FSM-U by utility operator measuring signal failure *)
		bMsg9268 : BOOL; (* W9268 - Dead band FSM-O by utility operator measuring signal failure *)
		bMsg9269 : BOOL; (* W9269 - Positive Margin FSM by utility operator measuring signal failure *)
		bMsg9270 : BOOL; (* W9270 - Negative Margin FSM by utility operator measuring signal failure *)
		bMsg9271 : BOOL; (* W9271 - U droop by utility operator measuring signal failure *)
		bMsg9272 : BOOL; (* W9272 - Ramp rate up by utility operator measuring signal failure *)
		bMsg9273 : BOOL; (* W9273 - Ramp rate down by utility operator measuring signal failure *)
		bMsg9274 : BOOL; (* W9274 - Reference Frequency FSM/LFSM by utility operator measuring signal failure *)
		rPF_AO_PF_I : REAL; (* power factor generator, mA signal*) (*OldName:AO_PF_gen_mA;Cycle:5*)
		rPF_AO_PF_U : REAL; (* power factor generator, V signal*) (*OldName:AO_PF_gen_V;Cycle:5*)
		rCtrGenPF_Set : REAL; (* Generator ???*) (*OldName:new pv;Cycle:5*)
		bMsg2886 : BOOL; (* B2886 P0 DEIE activ *)
		bMsg2887 : BOOL; (* B2887 Q0 DEIE activ *)
		bMsg2888 : BOOL; (* B2888 DEIE Release to synchronise *)
		bMsg2889 : BOOL; (* B2889 Q0 not activ *)
		bMsg2890 : BOOL; (* B2890 RSE activ *)
		bMsg2891 : BOOL; (* B2891 P0 DEIE inactive *)
		bMsg2892 : BOOL; (* B2892 customer switch on *)
		bMsg2893 : BOOL; (* B2893 customer switch on *)
		iQU_PFU_TestRestTime : INT; (*PFU QU Test - Restzeit*)
		iPFC_TestRestTime : INT; (*PFC Test - Restzeit*)
		bMsg2799 : BOOL; (*W2799 - P0 DEIE measuring signal failure*)
		rU_QU_PFU_NomSim : REAL; (*Simulierte Actual Voltage für QU PFU Test [%Un]*)
		rF_PFC_NomSim : REAL; (*Simulierte Netzfrequenz für PFC Test [Hz]*)
		bstatGC_rel : BOOL; (* general enabling conditions for stat. GR performs functions*)
		rCosPhi_P_Set : REAL; (*cos(phi) setpoint from PF = f(P)*)
		rPF_Q_U_Set : REAL; (*cos(phi) setpoint from Q = f(U)*)
		rPFC_Set : REAL; (* set value for PFC *) (* OldName: PFC_set; Cycle:5; *)
		rP_Red_PFC_Norm : REAL; (*PFC Absolute Power Limitation*) (* OldName: ssLimitPowerPFC_PROM; Cycle: 5 *)
		rP_Set_PFC_Norm : REAL; (* Power Setpoint PFC*) (* OldName: ssOffsetPowerkW_PFC; Cycle: 5 *)
		bP_Set_PFC_Enable : BOOL; (* Power setpoint PFC aktiv *) (*OldName:new PV;Cycle:5;*)
		rP_Set_Unred_Freeze : REAL; (*last unreduzed power setpoint*)
		rGCQ_PFSetExt : REAL; (* setpoint cos(phi) extern *) (* OldName: rGCQ_PFset_ext; Cycle:5; *)
		rGCQ_PF : REAL; (* Skalierter Wert AI:COS PHI Sollwert von EU *) (* OldName: rGCQ_PF; Cycle:5; *)
		rGenC_PFBC : REAL; (* bus: scaling value genetaror power factor (COS PHI) from EU *) (* OldName: rBUS_GCQ_PF; Cycle:5; *)
		rGCQ_QSetExt : REAL; (*   *) (* OldName: rGCQ_Qset_ext; Cycle:5; *)
		rGCQ_Q : REAL; (* Skalierter Wert AI:Q Sollwert von EU [kVAr] *) (* OldName: rGCQ_Q; Cycle:5; *)
		rGenC_QBC : REAL; (* bus: scaling value reactive power (Q) from EU *) (* OldName: rBUS_GCQ_Q; Cycle:5; *)
		rPF_QSet : REAL; (* 0 *) (* OldName: rPF_Qset; Cycle:5; *)
		rGCQ_QLim : REAL; (* Skalierter Wert AI:QLim Sollwert von EU [kVAr] *) (* OldName: rGCQ_Qlim; Cycle:5; *)
		rGenC_QLimBC : REAL; (* bus: scaling value for reactive power limitation for EVA BUS[kVAr] *) (* OldName: rBUS_GCQ_Qlim; Cycle:5; *)
		rGCQ_QLimExt : REAL; (*  *) (* OldName: ; Cycle:; *)
		rGCQ_USet : REAL; (* [-] *) (* OldName: rGCQ_Uset; Cycle:5; *)
		rPF_QLim : REAL := 0.0;
		rGCQ_USetExt : REAL; (* [V] *) (* OldName: rGCQ_Uset_ext; Cycle:5; *)
		rGenC_UQBC : REAL; (* bus: scaling value generator voltage for reactive power (Q) *) (* OldName: rBUS_GCQ_Uset; Cycle:5; *)
		bPF_GenC_ExtRel : BOOL; (* extern release  cos phi EU - Hardware  *) (* OldName: bGCQ_PF; Cycle:5; *)
		bGenC_PFBC_ExtRel : BOOL; (* extern release  cos phi EU - Bus *) (* OldName: bBUS_GCQ_PF; Cycle:5; *)
		bQ_GenC_ExtRel : BOOL; (* extern release  Q EU - Hardware  *) (* OldName: bGCQ_Q; Cycle:5; *)
		bGenC_QBC_ExtRel : BOOL; (* extern release  Q EU - Bus *) (* OldName: bBUS_GCQ_Q; Cycle:5; *)
		bGenC_QLim_ExtRel : BOOL; (* externe release Q limit EU - Hardware *) (* OldName: bGCQ_Qlim; Cycle:5; *)
		bGenC_QLimBC_ExtRel : BOOL; (* externe release Q limit EU - Bus *) (* OldName: bBUS_GCQ_Qlim; Cycle:5; *)
		bGenC_UQBC_ExtRel : BOOL; (* externe release Q = f(U) EU - Bus *) (* OldName: bBUS_GCQ_Uset; Cycle:5; *)
		bGCQ_PFP : BOOL; (* Enable external power factor *) (* OldName: bGCQ_PFP; Cycle:5; *)
		bBC_GCQ_PFP : BOOL; (* Enable external power factor bus *) (* OldName: bBUS_GCQ_PFP; Cycle:5; *)
		bGCQ_PFU : BOOL; (* 0 *) (* OldName: bGCQ_PFU; Cycle:5; *)
		bBC_GCQ_PFU : BOOL; (* 0 *) (* OldName: bBUS_GCQ_PFU; Cycle:5; *)
		bGCQ_QU : BOOL; (* 0 *) (* OldName: bGCQ_QU; Cycle:5; *)
		bBC_GCQ_QU : BOOL; (* 0 *) (* OldName: bBUS_GCQ_QU; Cycle:5; *)
		iGCQ_Fun_Act : USINT; (* falls eigenes Modul Schnittstelle zu pf_ctr/gen_ctr - Nr. der aktiven VoltageControlFunction aus stat. GridCode *) (* OldName: usGCQ_Fun_act; Cycle: 0 *)
		tPF_GenC_Fix1SOn : BOOL;
		tPF_GenC_Fix2SOn : BOOL;
		tPF_GenC_Fix3SOn : BOOL;
		tPF_GenC_Fix4SOn : BOOL;
		tPF_GenC_Fix5SOn : BOOL;
		bQ_GenC_Fix1SOn : BOOL;
		bQ_GenC_Fix2SOn : BOOL;
		bQ_GenC_Fix3SOn : BOOL;
		bQ_GenC_Fix4SOn : BOOL;
		bQ_GenC_Fix5SOn : BOOL;
		bP0_BLOCK_DEIE : BOOL;
		bGCP_PLim : BOOL;
		bBC_GCP_PLim : BOOL;
		bGCP_PFC : BOOL;
		bBC_GCP_PFC : BOOL;
		rPFP_Set : REAL;
		tPFP_Points : ARRAY[0..7]OF lcrCurveByPoints_TabEntry_type;
		rPFP_x : REAL;
		iPFP_NoOfPoints : INT;
		tPFC_Points : ARRAY[0..7]OF lcrCurveByPoints_TabEntry_type;
		tPFC_Points2 : ARRAY[0..7]OF lcrCurveByPoints_TabEntry_type;
		rPFC_x : REAL;
		iPFC_NoOfPoints : INT;
		rQU_Set : REAL;
		tQU_Points : ARRAY[0..7]OF lcrCurveByPoints_TabEntry_type;
		tQU_Points2 : ARRAY[0..7]OF lcrCurveByPoints_TabEntry_type;
		rQU_x : REAL;
		iQU_NoOfPoints : INT;
		rU_ActV : REAL;
		iPFU_NoOfPoints : INT;
		tPFU_Points : ARRAY[0..7]OF lcrCurveByPoints_TabEntry_type;
		tPFU_Points2 : ARRAY[0..7]OF lcrCurveByPoints_TabEntry_type;
		rPFU_x : REAL;
		bGCP_P : BOOL;
		bBC_GCP_P : BOOL;
		rGCP_P_AI : REAL;
		rGCP_P_BUS : REAL;
		rGCP_P : REAL;
		rP_Set_EU_kW : REAL;
		rP_Set_EU_Norm : REAL;
		bGCP_RMC : BOOL;
		bBC_GCP_RMC : BOOL;
		rP_Red_RMC_Norm : REAL;
		bP_GenC_Lim1SOn : BOOL;
		bP_GenC_Lim2SOn : BOOL;
		bP_GenC_Lim3SOn : BOOL;
		bP_GenC_Lim4SOn : BOOL;
		bP_GenC_Lim5SOn : BOOL;
		rGCP_Plim_BUS : REAL;
		rGCP_Plim_Norm : REAL;
		rPlim_EU_kW : REAL;
		rPlim_EU_Norm : REAL;
		bEU_RM_BLOCK_INT : BOOL;
		iQPointRef : INT;
		rP_act : REAL;
		rU_act : REAL;
		rPF_P_set : REAL;
		rPF_set : REAL;
		bGCQ_QP : BOOL;
		bBC_GCQ_QP : BOOL;
		rQ_set_KVAr : REAL;
		rU_set : REAL;
		rQ_Uset : REAL;
		rPF_set_tab : REAL;
		rQ_PFset_tab : REAL;
		rQ_P_set : REAL;
		rQ_U_set : REAL;
		rPF_U_set : REAL;
		rPF_Px : ARRAY[0..7]OF REAL; (*Cosphi(P) Curve 1 X-Values*)
		rPF_Py : ARRAY[0..7]OF REAL; (*Cosphi(P) Curve 1 Y-Values*)
		rPF2_Px : ARRAY[0..7]OF REAL; (*Cosphi(P) Curve 2 X-Values*)
		rPF2_Py : ARRAY[0..7]OF REAL; (*Cosphi(P) Curve 2 Y-Values*)
		rQ_Px : ARRAY[0..7]OF REAL; (*Q(P) Curve 1 X-Values*)
		rQ_Py : ARRAY[0..7]OF REAL; (*Q(P) Curve 1 Y-Values*)
		rQ2_Px : ARRAY[0..7]OF REAL; (*Q(P) Curve 2 X-Values*)
		rQ2_Py : ARRAY[0..7]OF REAL; (*Q(P) Curve 2 Y-Values*)
		rQ_Ux : ARRAY[0..7]OF REAL; (*Q(U) Curve 1 X-Values*)
		rQ_Uy : ARRAY[0..7]OF REAL; (*Q(U) Curve 1 Y-Values*)
		rQ2_Ux : ARRAY[0..7]OF REAL; (*Q(U) Curve 2 X-Values*)
		rQ2_Uy : ARRAY[0..7]OF REAL; (*Q(U) Curve 2 Y-Values*)
		rPF_Ux : ARRAY[0..7]OF REAL; (*Cosphi(U) Curve 1 X-Values*)
		rPF_Uy : ARRAY[0..7]OF REAL; (*Cosphi(U) Curve 1 Y-Values*)
		rPF2_Ux : ARRAY[0..7]OF REAL; (*Cosphi(U) Curve 2 X-Values*)
		rPF2_Uy : ARRAY[0..7]OF REAL; (*Cosphi(U) Curve 2 Y-Values*)
		iPFP_Points : INT; (*PF(P) Number of points used*)
		iQP_Points : INT; (*Q(P) Number of points used*)
		iQU_Points : INT; (*Q(U) Number of points used*)
		iPFU_Points : INT; (*PF(U) Number of points used*)
		rQ_CUST_set : REAL; (*Q Customer Setpoint*)
		rQ_Uctrl : REAL; (*Q from U control*)
		rQ_set : REAL; (*Final Q setpoint*)
		tiQ_RampFilt : TIME; (*Time Constant PT1 filter*)
		rQ_set_filt : REAL; (*Q after PT1 filter*)
		rF_FSMPoints_x : ARRAY[0..8]OF REAL; (*FSM Curve X-Values*)
		rP_FSMPoints_y : ARRAY[0..8]OF REAL; (*FSM Curve Y-Values*)
		rF_LFSMOPoints_x : ARRAY[0..2]OF REAL; (*FSMO Curve X-Values*)
		rP_LFSMOPoints_y : ARRAY[0..2]OF REAL; (*FSMO Curve Y-Values*)
		rF_LFSMUPoints_x : ARRAY[0..2]OF REAL; (*FSMU Curve X-Values*)
		rP_LFSMUPoints_y : ARRAY[0..2]OF REAL; (*FSMU Curve Y-Values*)
		rF_FSM_Range_Delta_x : ARRAY[0..1]OF REAL; (*FSM/LFM Range*)
		rP_FSM_Range_Delta_y : ARRAY[0..1]OF REAL; (*FSM/LFM Range*)
		rF_Point_Act_x : REAL; (*FSM Curve Point Act*)
		rF_Point_Act_y : REAL; (*FSM Curve Point Act*)
		rF_FSMLFSM_Act_x : REAL; (*FSM Curve Point Act*)
		rP_FSMLFSM_Act_y : REAL; (*FSM Curve Point Act*)
		bLFSMO_active : BOOL; (* FSMO active *)
		rDroop_LFSMO : REAL; (* Droop LFSMO *)
		bLFSMU_active : BOOL; (* FSMU active *)
		rDroop_LFSMU : REAL; (* Droop FSMU *)
		bILF_Active : BOOL; (*ILF active *)
		bFSM_active : BOOL; (* FSM active *)
		rDroop_FSMO : REAL; (* Droop FSMO *)
		rDroop_FSMU : REAL; (* Droop FSMU *)
		rF_FSM_Deadband_pos : REAL; (* Deadband FSM positive *)
		rF_FSM_Deadband_neg : REAL; (* Deadband FSM negative *)
		rF_LFSMO_Deadband_pos : REAL; (* Deadband LFSMO positive *)
		rF_LFSMO_Deadband_neg : REAL; (* Deadband LFSMU negative *)
		bMsg2344 : BOOL; (*module blocked from grid operator - shutdown*)
		bMsg2345 : BOOL; (*module blocked from grid operator - demand off*)
		bDI_Dem_EU_Block : BOOL; (*di: request lock plant(all modules) 1=locked*)
		bDI_Dem_EU_MnsConBlock : BOOL; (*di: request lock mains connection   1=locked*)
		bLockPlantBC_SetEUCOn : BOOL; (*bus: request lock plant(all modules) 1=locked*)
		bLockMnsConBC_SetEUCOn : BOOL; (*bus: request lock mains connection   1=locked*)
		bP_GenC_SetEUCOn : BOOL; (*di: request power value from EU - on (activate)*)
		bP_GenC_SetEUCOf : BOOL; (*di: request power value from EU - off (deactivate)*)
		bGenC_PBC_SetCOn : BOOL; (*bus: setpoint power P from EU - on (activate)*)
		bGenC_PBC_SetCOf : BOOL; (*bus: setpoint power P from EU - off (deactivate)*)
		rGenC_PBC : REAL; (*bus: scaling value power limitation from EU*)
		bPF_GenC_SetEUCOn : BOOL; (*di: setpoint power factor (COS PHI) from EU - on (activate)*)
		bPF_GenC_SetEUCOf : BOOL; (*di: setpoint power factor (COS PHI) from EU - off (deactivate)*)
		rGCQ_PF_AI : REAL; (*ai: setpoint power factor (PF) from EU[linearized]*)
		bGenC_PFBC_SetCOn : BOOL; (*bus: setpoint power factor (COS PHI) from EU - on (activate)*)
		bGenC_PFBC_SetCOf : BOOL; (*bus: setpoint power factor (COS PHI) from EU - off (deactivate)*)
		bQ_GenC_SetEUCOn : BOOL; (*di: setpoint reactive power characteristic (Q) from EU - on (activate)*)
		bQ_GenC_SetEUCOf : BOOL; (*di: setpoint reactive power characteristic (Q) from EU - on (activate)*)
		rGCQ_Q_AI : REAL; (*ai: setpoint reactive power (Q) from EU[kVAr]*)
		bGenC_QBC_SetCOn : BOOL; (*bus: setpoint reactive power (Q) from EU - on (activate)*)
		bGenC_QBC_SetCOf : BOOL; (*bus: setpoint reactive power (Q) from EU - off (deactivate)*)
		bU_GenC_SetEUCOn : BOOL; (*DI: Voltage control for reactive power - on (activated)*)
		bU_GenC_SetEUCOf : BOOL; (*DI: Voltage control for reactive power - off (deactivated)*)
		rGCQ_USet_AI : REAL; (*ai: Voltage setpoint[%]*)
		bGenC_UBC_SetCOn : BOOL; (*bus: Voltage control for reactive power - on (activate)*)
		bGenC_UBC_SetCOf : BOOL; (*bus: Voltage control for reactive power - off (deactivate)*)
		bPLim_GenC_SetEUCOn : BOOL; (*di: setpoint power limitation (Plim) from EU - on (activate)*)
		bPLim_GenC_SetEUCOf : BOOL; (*di: setpoint power limitation (Plim) from EU - off (deactivate)*)
		rGCP_PLim_AI : REAL; (*di: scaling value power limitation from EU*)
		bGenC_PLimBC_SetCOn : BOOL; (*bus: power limition from  EU - on (activate)*)
		bGenC_PLimBC_SetCOf : BOOL; (*bus: power limition from  EU - off (deactivate)*)
		rGenC_PLimBC : REAL; (*bus: scaling value power limitation from EU*)
		bPRampExt_SetEUCOn : BOOL; (*power ramp rate extern active*) (*TF 3.2.3*)
		bPRampExtBC_SetEUCOn : BOOL; (*power ramp rate extern active*) (*TF 3.2.3*)
		rPRampExtBC_SetEU_Up : REAL; (*power ramp rate extern gradient UP*) (* %Pnom/s *)
		rPRampExtBC_SetEU_Down : REAL; (*power ramp rate extern gradient DOWN*) (* %Pnom/s *)
		rU_droopBC : REAL; (*voltage control droop*)
		rF_FC_Deadband_posBC : REAL; (*FSM-O frequency deadband positive [Hz]*)
		rDroop_FC_posBC : REAL; (*FSM-U droop [%]*)
		rF_FC_Deadband_negBC : REAL; (*FSM-O frequency deadband negative [Hz]*)
		rDroop_FC_negBC : REAL; (*FSM-O droop [%]*)
		rF_LFSMU_GrC_DeadBand_negBC : REAL; (*LFSM-U frequency threshold [Hz]*)
		rF_LFSMO_GrC_DeadBand_posBC : REAL; (*LFSM-O frequency threshold [Hz]*)
		rDroop_GrC_LFSMU_negBC : REAL; (*LFSM-U droop [%]*)
		rDroop_GrC_LFSMO_posBC : REAL; (*LFSM-O droop [%]*)
		bLFSMO_SetEUCOn : BOOL; (*di: LFSMO - on  (activate)*)
		bLFSMO_SetEUCOf : BOOL; (*di: LFSMO - off (deactivate)*)
		bLFSMU_SetEUCOn : BOOL; (*di: LFSMU - on  (activate)*)
		bLFSMU_SetEUCOf : BOOL; (*di: LFSMU - off (deactivate)*)
		bLFSMO_SetEUCOn_BC : BOOL; (*bus: LFSMO - on  (activate)*)
		bLFSMO_SetEUCOf_BC : BOOL; (*bus: LFSMO - off (deactivate)*)
		bLFSMU_SetEUCOn_BC : BOOL; (*bus: LFSMU - on  (activate)*)
		bLFSMU_SetEUCOf_BC : BOOL; (*bus: LFSMU - off (deactivate)*)
		bSet_ILF_COn_Bus : BOOL; (*demand on ILF over bus*)
		bSet_ILF_COf_Bus : BOOL; (*demand off ILF over bus*)
		bILF_SetCOn : BOOL; (*demand ILF on over hardwire*)
		bILF_SetCOf : BOOL; (*demand ILF off over hardwire*)
		bSet_FC_COn_Bus : BOOL; (*demand on frequency control over bus*)
		bSet_FC_COf_Bus : BOOL; (*demand off  frequency control over bus*)
		bFC_SetCOn : BOOL; (*demand frequency control on over hardwire*)
		bFC_SetCOf : BOOL; (*demand frequency control off over hardwire*)
		rGCQ_QLim_AI : REAL; (*setpoint reactive power limitation (Qlim) from Ai, for diagnosis*)
		bQLim_GenC_SetEUCOn : BOOL; (*setpoint reactive power limitation (Qlim) from EU - on (activate)*)
		bQLim_GenC_SetEUCOf : BOOL; (*setpoint reactive power limitation (Qlim) from EU - off (deactivate)*)
		bGenC_QLimBC_SetCOn : BOOL; (*bus: setpoint reactive power limitation (Qlim) from EU - on (activate)*)
		bGenC_QLimBC_SetCOf : BOOL; (*bus: setpoint reactive power limitation (Qlim) from EU - off (deactivate)*)
		rPRampExtAi_SetEU_Up : REAL; (*power ramp rate extern gradient UP*) (* %Pnom/s *)
		rPRampExtAi_SetEU_Down : REAL; (*power ramp rate extern gradient DOWN*) (* %Pnom/s *)
		rF_FC_Deadband_posAi : REAL; (*FSM-O frequency deadband positive [Hz]*)
		rDroop_FC_posAi : REAL; (*FSM-U droop [%]*)
		rF_FC_Deadband_negAi : REAL; (*FSM-U frequency deadband negative [Hz]*)
		rDroop_FC_negAi : REAL; (*FSM-O droop [%]*)
		rF_LFSMU_GrC_DeadBand_negAi : REAL; (*LFSM-U frequency threshold [Hz]*)
		rF_LFSMO_GrC_DeadBand_posAi : REAL; (*LFSM-O frequency threshold [Hz]*)
		rDroop_GrC_LFSMU_negAi : REAL; (*LFSM-U droop [%]*)
		rDroop_GrC_LFSMO_posAi : REAL; (*LFSM-O droop [%]*)
		rU_droopAI : REAL; (*Ai: voltage droop at PoC from EU [%U_Nom]*)
	END_STRUCT;
	OUT_GR_struct : 	STRUCT 
		tGR2AB : MM2AmmBase; (* AMM structure*) (* OldName: new PV; Cycle: 5  *)
		tGR2PB : MM2ParaBase_type; (* Data exchange structure to ParaBase*) (* OldName: new PV; Cycle: 5  *)
		tPF_GenC_SOn : HALioDo_Type; (* DO: generator power factor (COS PHI) from EU is on *) (* OldName: DO_GCQ_PF_ON; Cycle: 5 *)
		tPF_GenC_SOf : HALioDo_Type; (* DO: generator power factor (COS PHI) from EU is off *) (* OldName: DO_GCQ_PF_OFF; Cycle: 5 *)
		tPF_GenC_Fix1SOn : HALioDo_Type; (* DO: genetaror power factor (COS PHI) - fixvalue 1 from EU is on *) (* OldName: DO_GCQ_PF_FIX1; Cycle: 5 *)
		tPF_GenC_Fix2SOn : HALioDo_Type; (* DO: genetaror power factor (COS PHI) - fixvalue 2 from EU is on *) (* OldName: DO_GCQ_PF_FIX2; Cycle: 5 *)
		tPF_GenC_Fix3SOn : HALioDo_Type; (* DO: genetaror power factor (COS PHI) - fixvalue 3 from EU is on *) (* OldName: DO_GCQ_PF_FIX3; Cycle: 5 *)
		tPF_GenC_Fix4SOn : HALioDo_Type; (* DO: genetaror power factor (COS PHI) - fixvalue 4 from EU is on *) (* OldName: DO_GCQ_PF_FIX4; Cycle: 5 *)
		tPF_GenC_Fix5SOn : HALioDo_Type; (* DO: genetaror power factor (COS PHI) - fixvalue 5 from EU is on *) (* OldName: DO_GCQ_PF_FIX5; Cycle: 5 *)
		tQ_GenC_SOn : HALioDo_Type; (* DO: reactive power characteristic (Q) from EU is on *) (* OldName: DO_GCQ_Qset_ON; Cycle: 5 *)
		tQ_GenC_SOf : HALioDo_Type; (* DO: reactive power characteristic (Q) from EU is off *) (* OldName: DO_GCQ_Qset_OFF; Cycle: 5 *)
		tQ_GenC_Fix1SOn : HALioDo_Type; (* DO: reactive power (Q) - Q-fixvalue 1 from EU on *) (* OldName: DO_GCQ_Q_FIX1; Cycle: 5 *)
		tQ_GenC_Fix2SOn : HALioDo_Type; (* DO: reactive power (Q) - Q-fixvalue 2 from EU on *) (* OldName: DO_GCQ_Q_FIX2; Cycle: 5 *)
		tQ_GenC_Fix3SOn : HALioDo_Type; (* DO: reactive power (Q) - Q-fixvalue 3 from EU on *) (* OldName: DO_GCQ_Q_FIX3; Cycle: 5 *)
		tQ_GenC_Fix4SOn : HALioDo_Type; (* DO: reactive power (Q) - Q-fixvalue 4 from EU on *) (* OldName: DO_GCQ_Q_FIX4; Cycle: 5 *)
		tQ_GenC_Fix5SOn : HALioDo_Type; (* DO: reactive power (Q) - Q-fixvalue 5 from EU on *) (* OldName: DO_GCQ_Q_FIX5; Cycle: 5 *)
		tQLim_GenC_SOn : HALioDo_Type; (* DO: reactive power limiting (QLim)  is on *) (* OldName: DO_GCQ_Qlim_ON; Cycle: 5 *)
		tQLim_GenC_SOf : HALioDo_Type; (* DO: reactive power limiting (QLim)  is off *) (* OldName: DO_GCQ_Qlim_OFF; Cycle: 5 *)
		tQLim_GenC_Act : HALioDo_Type; (* DO: reactive power limitation (Plim) from EU is aktiv *) (* OldName: DO_GCQ_Qlim_ACT; Cycle: 5 *)
		tQPC_GenC_SOn : HALioDo_Type; (* DO: reactive power characteristics COS(phi)=f(P) from EU is on *) (* OldName: DO_GCQ_PFP_ON; Cycle: 5 *)
		tQPC_GenC_SOf : HALioDo_Type; (* DO: reactive power characteristics COS(phi)=f(P) from EU is off *) (* OldName: DO_GCQ_PFP_OFF; Cycle: 5 *)
		tQUC_GenC_SOn : HALioDo_Type; (* DO: reactive power characteristics Q=f(U) from EU is on *) (* OldName: DO_GCQ_QU_ON; Cycle: 5 *)
		tQUC_GenC_SOf : HALioDo_Type; (* DO: reactive power characteristics Q=f(U) from EU is off *) (* OldName: DO_GCQ_QU_OFF; Cycle: 5 *)
		tQP_GenC_SOn : HALioDo_Type; (* DO: reactive power characteristics Q=f(P) from EU is on *)
		tQP_GenC_SOf : HALioDo_Type; (* DO: reactive power characteristics Q=f(P) from EU is on *)
		tPFUC_GenC_SOn : HALioDo_Type; (* DO: reactive power characteristics COS(phi)=f(U) von EU is on *) (* OldName: DO_GCQ_PFU_ON; Cycle: 5 *)
		tPFUC_GenC_SOf : HALioDo_Type; (* DO: reactive power characteristics COS(phi)=f(U) von EU is on *) (* OldName: DO_GCQ_PFU_OFF; Cycle: 5 *)
		tP_GenC_SOn : HALioDo_Type; (* DO: power value fon EU is on *) (* OldName: DO_GCP_P_ON; Cycle: 5 *)
		tP_GenC_SOf : HALioDo_Type; (* DO: power value fon EU is off *) (* OldName: DO_GCP_P_OFF; Cycle: 5 *)
		tP_GenC_Fix0SOn : HALioDo_Type; (* DO: no limiting power value - P- fixvalue 0 from EU is on *) (* OldName: DO_RM_EVU_0; Cycle: 5 *)
		tP_GenC_Fix1SOn : HALioDo_Type; (* DO: power value - P- fixvalue 1 from EU is on *) (* OldName: DO_RM_EVU_1; Cycle: 5 *)
		tP_GenC_Fix2SOn : HALioDo_Type; (* DO: power value - P- fixvalue 2 from EU is on *) (* OldName: DO_RM_EVU_2; Cycle: 5 *)
		tP_GenC_Fix3SOn : HALioDo_Type; (* DO: power value - P- fixvalue 3 from EU is on *) (* OldName: DO_RM_EVU_3; Cycle: 5 *)
		tP_GenC_Fix4SOn : HALioDo_Type; (* DO: power value - P- fixvalue 4 from EU is on *) (* OldName: DO_RM_EVU_4; Cycle: 5 *)
		tP_GenC_Fix5SOn : HALioDo_Type; (* DO: power value - P- fixvalue 5 from EU is on *) (* OldName: DO_RM_EVU_5; Cycle: 5 *)
		tPLim_GenC_SOn : HALioDo_Type; (* DO: power limitation (Plim) from EU is on *) (* OldName: DO_GCP_Plim_ON; Cycle: 5 *)
		tPLim_GenC_SOf : HALioDo_Type; (* DO: power limitation (Plim) from EU is off *) (* OldName: DO_GCP_Plim_OFF; Cycle: 5 *)
		tPLim_GenC_Act : HALioDo_Type; (* DO: power limitation (Plim) from EU is aktiv *) (* OldName: DO_GCP_Plim_ACT; Cycle: 5 *)
		tPFC_SOn : HALioDo_Type; (* DO: primary frequency control is on *) (* OldName: DO_GCP_PFC_ON; Cycle: 5 *)
		tPFC_SOf : HALioDo_Type; (* DO: primary frequency control is off *) (* OldName: DO_GCP_PFC_OFF; Cycle: 5 *)
		tRMC_SOn : HALioDo_Type; (* DO: regulation margin control is on *) (* OldName: DO_GCP_RMC_ON; Cycle: 5 *)
		tRMC_SOf : HALioDo_Type; (* DO: regulation margin control is off *) (* OldName: DO_GCP_RMC_OFF; Cycle: 5 *)
		tEU_RM_BLOCK : HALioDo_Type; (* DO: 	Separate unit of utility and of active network*) (* OldName: DO_RM_EVU_BLOCK ; Cycle: 5 *)
		tQ_GenC_Act : HALioAo_Type; (* AO: reactive power actuele value *) (* OldName: AO_GCQ_Q ; Cycle: 5 *)
		tPF_GenC_Act : HALioAo_Type; (* AO: generator power factor (COS PHI) actuele value *) (* OldName: AO_GCQ_PF; Cycle: 5 *)
		iGCQ_Fun_Act : USINT; (* falls eigenes Modul Schnittstelle zu pf_ctr/gen_ctr - Nr. der aktiven VoltageControlFunction aus stat. GridCode - 0: customized
1: cosphi set
2: cosphi(P) 
3: cosphi(U)
4: Q(U)
5: Q(P)
6: Q set
7: U set
8: time table 
*) (* OldName: usGCQ_Fun_act; Cycle: 0 *)
		bGCQ_Fun_Act : BOOL; (* falls eigenes Modul Schnittstelle zu reg_in(_9) - stat. GC Funktion aktiv *) (* OldName: bGCQ_Fun_act; Cycle: 0 *) (*============*)
		bP_Set_EU_Enable : BOOL; (*power setpoint of EU active*) (* OldName: bPset_EVU_aktiv; Cycle: 5 *)
		rP_Red_EU_Norm : REAL; (*Power reduction EU (AI or BUS)*) (* OldName: ssPowRed_EVU_HWBUS; Cycle: 5 *)
		bPFP_Aktiv : BOOL; (*TRUE = cosphi(P) aktiv*)
		bP_Red_PFC_Enable : BOOL; (* PFC aktiv *) (* OldName: bPFC_aktiv; Cycle: 5 *)
		bPFU_Aktiv : BOOL; (*PFU is active*)
		bQLim_Aktiv : BOOL; (* Q Limiti is active*) (* OldName: bQlim_aktiv; Cycle: 5 *)
		bQU_Aktiv : BOOL; (*Q(U) is active*)
		rP_Red_PFC_Norm : REAL; (*PFC Absolute Power Limitation*) (* OldName: ssLimitPowerPFC_PROM; Cycle: 5 *)
		rP_Set_EU_Norm : REAL; (*setpoint power EU*) (* OldName: ssSetpointPowerkW_EVU; Cycle: 5 *)
		bP_Red_RMC_Enable : BOOL; (*TRUE = RMC is active*) (* OldName: bRMC_aktiv; Cycle: 5 *)
		rP_Red_RMC_Norm : REAL; (* power limitation RMC*) (* OldName: ssSetpointPowerkW_RMC; Cycle: 5 *)
		rP_Set_PFC_Norm : REAL; (* Power Setpoint PFC*) (* OldName: ssOffsetPowerkW_PFC; Cycle: 5 *)
		rPF_QLim_Lin : REAL; (*from the Q limit value determined COS PHI limit value*) (* OldName: ssPF_Qlim_lin; Cycle: 5 *)
		bEU_BLOCK_INT : BOOL; (* falls eigenes Modul Schnittstelle zu op_msg/pb7_(x) - interne Blockierung Aggregat *) (* OldName: EVU_BLOCK_INT; Cycle: 5 *)
		iPF_EU : INT; (* falls eigenes Modul Schnittstelle zu pf_ctr - cosphi Sollwert aus allen stat. GC Funktionen LINEARISIERT + RAMPE *) (* OldName: ssPF_EVU; Cycle: 5 *)
		rP_Ramp_IncGrad_GR_Norm : REAL; (*gradient for increase of power ramp from grid modul *) (* OldName: newPV; Cycle: 5 *)
		rP_Ramp_DecGrad_GR_Norm : REAL; (*gradient for decrease of power ramp from grid modul *) (* OldName: newPV; Cycle: 5 *)
		bP_Ramp_IncGrad_GR_Enable : BOOL; (*enable gradient for increase of power ramp from grid modul  *) (* OldName: newPV; Cycle: 5 *)
		bP_Ramp_DecGrad_GR_Enable : BOOL; (*enable gradient for decrease of power ramp from grid modul *) (* OldName: newPV; Cycle: 5 *)
		bP_Red_EU_Enable : BOOL; (* Power reduction EU (AI or BUS) aktiv *) (*OldName:new PV;Cycle:5;*)
		bP_Set_PFC_Enable : BOOL; (* Power setpoint PFC aktiv *) (*OldName:new PV;Cycle:5;*)
		rP_RedDI_EU_Norm : REAL; (*Power reduction EU from DIs*) (* OldName: RED_EVU; Cycle: 5 *)
		tP_GenC_Bloc : HALioDo_Type; (* DO: internal blocking signal*) (* OldName: DO_RM_EVU_0; Cycle: 5 *)
		rP_Set_ExtDI_Norm : REAL; (* external power setpoint via digital input related to rP_Nom *) (*OldName:Dig_P_SOLL;Cycle:5;*)
		tCtrGenPF_Set : HALioAo_Type; (*AO Generator ???*) (*OldName:new pv;Cycle:5*) (*E  ERDF *)
		tERDF_BLOCK : HALioDo_Type; (* DO: Block von ERDF *) (* OldName: DI_EVU_BLOCK ; Cycle: 5 *)
		tMCB_SOn : HALioDo_Type; (*DO: receive requested Command form machine*) (*OldName:DO_RMAnfEntk ;Cycle:5;*)
		tMCB_Rel_Sync_SOn : HALioDo_Type; (* DO: releas decoupling quickly from EU (ERDF) *) (*OldName:DO_RMFrgKop ;Cycle:5;*)
		tRSE_SOn : HALioDo_Type; (* DO: decoupling RSE from EU (ERDF)*) (*OldName: DO_RMRSE;Cycle:5;*)
		tMCB_EDF_SOn : HALioDo_Type; (* DO: feedback Engine off get  *) (*OldName: DO_RMFAnfEntk;Cycle:5;*)
		tGCB_SOn : HALioDo_Type; (* DO: Generator switch is on *) (*OldName:DO_GCB_ON ;Cycle:5;*)
		tEng_Ready : HALioDo_Type; (* DO: aggregate available (PLC run) *) (*OldName:DO_NotReady ;Cycle:5;*)
		bOpAlm_Res01 : BOOL; (* Alarm Reserve failure 1 trip *) (*OldName: ;Cycle:5;*)
		bOpAlm_DecQu : BOOL; (* Alarm  DEIE fast decoupling *) (*OldName:F_ENTK ;Cycle:5;*)
		bOpAlm_Res03 : BOOL; (* Alarm  Reserve failure 3 trip *) (*OldName: ;Cycle:5;*)
		bOpAlm_MSF_P0 : BOOL; (* Alarm  measuring signal failure P0 *) (*OldName: ;Cycle:5;*)
		bOpAlm_ERDF_SY : BOOL; (*Alarm  release for SY ERDF *) (*OldName:REL_SY_EDF ;Cycle:5;*)
		bOpMsg_Plim_ERDF_SOnOf : BOOL; (* P0 DEIE activ / not active *) (*OldName: ;Cycle:5;*)
		bOpMsg_Qlim_ERDF_SOnOf : BOOL; (* Q0 DEIE activ / not active *) (*OldName: ;Cycle:5;*)
		bOpMsg_RSE_SOnOf : BOOL; (* RSE activ / not active*) (*OldName: ;Cycle:5;*)
		bOpMsg_P0_BLOCK_DEIE_SOnOf : BOOL; (* customer switch on / off *) (*OldName: ;Cycle:5;*)
		bOpMsg_Plim_ERDF_ABF_SOnOf : BOOL; (* P0 DEIE too low->shut down  *) (*OldName: ;Cycle:5;*)
		rPFSoll_lin_GR2GC : REAL; (* PFSoll_lin incl. QLim + EVU funct. 1-5 *) (* OldName: PFSoll_lin;Cycle:2;*)
		bP_Red_POR_Enable : BOOL; (* POR aktiv *) (* OldName: ; Cycle: 5 *)
		bP_Red_SOR_Enable : BOOL; (* SOR aktiv *) (* OldName: ; Cycle: 5 *)
		bP_Red_TOR1_Enable : BOOL; (* TOR1 aktiv *) (* OldName: ; Cycle: 5 *)
		bP_Red_TOR2_Enable : BOOL; (* TOR2 aktiv *) (* OldName: ; Cycle: 5 *)
		bP_Red_RR_Enable : BOOL; (* RR aktiv *) (* OldName: ; Cycle: 5 *)
		bP_Red_SR_Enable : BOOL; (* SR aktiv *) (* OldName: ; Cycle: 5 *)
		bP_Red_HFC_Enable : BOOL; (* HFC aktiv *) (* OldName: ; Cycle: 5 *)
		bP_Act_ILF_Enable : BOOL; (* activation of integrator power for ILF*)
		bP_Set_FC_Enable : BOOL; (* activatoin of power Setpoint for FC *)
		rP_Set_FC_Norm : REAL; (* generator power setpoint by frequency control*)
		rP_FC_ContOutput : REAL; (* PRL controller output [e2m]*)
		tILF_SOn : HALioDo_Type; (* DO: ILF switched on*)
		tILF_SOf : HALioDo_Type; (* DO: ILF switched off*)
		tFC_SOn : HALioDo_Type; (* DO: frequency control switched on*)
		tFC_SOf : HALioDo_Type; (* DO: frequency control switched off*)
		tPU_SOn : HALioDo_Type; (* DO: PU switched on*)
		tPU_SOf : HALioDo_Type; (* DO: PU switched off*)
		rP_FC_Delta : REAL; (*power output of frequency control [kW]*)
		rP_Set_Min : REAL; (* minimal power setpoint related to rP_nom*)
		bILF_SOn_Bus : BOOL; (* Bus: ILF switched on*)
		bILF_SOf_Bus : BOOL; (* Bus: ILF switched off*)
		bFC_SOn_Bus : BOOL; (* Bus: frequency control switched on*)
		bFC_SOf_Bus : BOOL; (* Bus: frequency control switched off*)
		bP_Set_PU_Enable : BOOL; (*P(U) - power set activated and ready to use by powersel*)
		bP_Red_PU_Enable : BOOL; (*P(U) activated*)
		rP_Set_PU_Norm : REAL; (*P(U) - power set reduced when U > Ugrenz and not PFC working*)
		bQP_Aktiv : BOOL; (*Q(P) function activated*)
		rQSoll_filt_GR2GC : REAL; (*Q set after filter*)
		rQSoll_Lim_GR2GC : REAL; (*Q set after limitations*)
		bQSetLim : BOOL; (*Qset is limited*)
		bPRamp_GrC_SetErr : BOOL; (* Slow increase power ramp after mains failure active *)
		tGR2CU : GRID2CUSTOM_Struct; (* Data exchange structure to Custom *)
		bEng_Bloc_GR : BOOL; (* Module blocked by Grid module, data structure failure *)
		bGEN2_UsePowtraj_LFSM : BOOL; (*Force GEN2 to faster reaction time in case of FSM/LFSM*)
		tEU_RM_BLOCK2 : HALioDo_Type; (*module blocked from grid operator - shutdown*)
		tEU_RM_BLOCK3 : HALioDo_Type; (*module blocked from grid operator - demand off*)
		rU_Set_NP : REAL; (*voltage setpoint-net parallel mode*)
		bU_Set_NP_Rel : BOOL; (*voltage setpoint-net parallel mode/release*)
		bPFC_SOn_Bus : BOOL; (*Bus feedback signal: LFSM switched on*)
		bPFC_SOf_Bus : BOOL; (*Bus feedback signal: LFSM switched off*)
	END_STRUCT;
	Para_Struct : 	STRUCT 
		rU_Act_sim_HMI : REAL; (*PARA: Simulated Voltage*)
		rP_GrC_SetPar_Lim : REAL; (*PARA [11660]: Gridcode power limit from network operator *) (* OldName: ssPLimit_Abf; Cycle: 5 *)
		rP_GrC_SetPar_Hy : REAL; (*PARA [11659]: Gridcode power hysteresis from network operator *) (* OldName: ssHy_Plimit_Abf; Cycle: 5 *)
		tiP_GrC_SetPar : TIME; (*PARA [11703]: [%Pnom]  Gridcode power time delay from network operator *) (* OldName: ssT_Plimit_Abf; Cycle: 5 *)
		bPRamp_GrC_SetLFSMCOn : BOOL; (*PARA [14173]: Power ramp LFSM active*)
		rPRampUp_LFSMO : REAL; (*PARA [14486]: [%Pnom/sec] Power ramp up LFSMO*) (* OldName: rPRamp_GrC_SetLFSMPar[14174], ssRampe_evu *)
		rPRampDown_LFSMO : REAL; (*PARA [14487]: [%Pnom/sec] Power ramp down LFSMO*) (* OldName: rPRamp_GrC_SetLFSMPar[14174], ssRampe_evu *)
		rPRampUp_LFSMU : REAL; (*PARA [14488]: [%Pnom/sec] Power ramp up LFSMU*) (* OldName: rPRamp_GrC_SetLFSMPar[14174], ssRampe_evu *)
		rPRampDown_LFSMU : REAL; (*PARA [14489]: [%Pnom/sec] Power ramp down LFSMU*) (* OldName: rPRamp_GrC_SetLFSMPar[14174], ssRampe_evu *)
		bPRamp_GrC_SetEUCOn : BOOL; (*PARA [11627]: Power ramp utility active *) (* OldName: bPRampe_evu; Cycle: 5 *)
		rPRamp_GrC_SetEUPar : REAL; (*PARA [11675]: [%Pnom/sec] Power ramp utility *) (* OldName: ssRampe_evu; Cycle: 5 *)
		bPRamp_GrC_SetErrCOn : BOOL; (*PARA [11626]: Power ramp after mains failure active *) (* OldName: bPRampe_Netzfehler; Cycle: 5 *)
		rPRamp_GrC_SetErr : REAL; (*PARA [11674]: [%Pnom/sec] Power ramp after mains failure *) (* OldName: ssPRampe_Netzfehler; Cycle: 5 *)
		rPRamp_GrC_SetNachLFSM : REAL; (*PARA [14175]: [%Pnom/sec] Power ramp after LFSM event*) (* OldName: ssPRampe_Netzfehler; Cycle: 5 *)
		tiP_GrC_SetNOK : TIME; (*PARA [11702]: [min] Time delay after mains ok *) (* OldName: ssT_NOK; Cycle: 5 *)
		rP_GrC_EUAct_Lim_BU : REAL; (*PARA [11645]: [kW]  setpoint Gridecode power limitation internal setpoint *) (* OldName: p_red_evu_backup; Cycle: 5 *)
		bP_GrC_SetEUCOn_Lim : BOOL; (*PARA [11622]: External analogue power limitation from utility active *) (* OldName: b_p_red_evu_act; Cycle: 5 *)
		rP_GrC_SetEUI1_Lim : REAL; (*PARA [11647]: [mA] Current point 1 *) (* OldName: p_red_evu_i1; Cycle: 5 *)
		rP_GrC_SetEUI2_Lim : REAL; (*PARA [11649]: [mA] Current point 2 *) (* OldName: p_red_evu_i2; Cycle: 5 *)
		rP_GrC_SetEUP1_Lim : REAL; (*PARA [11651]: [kW] Power point 1 *) (* OldName: p_red_evu_p1; Cycle: 5 *)
		rP_GrC_SetEUP2_Lim : REAL; (*PARA [11653]: [kW] Power point 2 *) (* OldName: p_red_evu_p2; Cycle: 5 *)
		rP_GrC_SetExtUt1_Lim : REAL; (*PARA [11654]: Power point limit  step 1 *) (* OldName: ssPowRed_Utility_1; Cycle: 5 *)
		rP_GrC_SetExtUt2_Lim : REAL; (*PARA [11655]: Power point limit  step 2 *) (* OldName: ssPowRed_Utility_2; Cycle: 5 *)
		rP_GrC_SetExtUt3_Lim : REAL; (*PARA [11656]: Power point limit  step 3 *) (* OldName: ssPowRed_Utility_3; Cycle: 5 *)
		rP_GrC_SetExtUt4_Lim : REAL; (*PARA [11657]: Power point limit  step 4 *) (* OldName: ssPowRed_Utility_4; Cycle: 5 *)
		rP_GrC_SetExtUt5_Lim : REAL; (*PARA [11658]: Power point limit  step 5 *) (* OldName: ssPowRed_Utility_5; Cycle: 5 *)
		bP_GrC_SetEUCOn : BOOL; (*PARA [11621]: External analogue power setpoint from utility active *) (* OldName: b_p_soll_evu_act; Cycle: 5 *)
		rP_GrC_SetEUI1 : REAL; (*PARA [11646]: [mA] Current point 1 *) (* OldName: p_soll_evu_i1; Cycle: 5 *)
		rP_GrC_SetEUI2 : REAL; (*PARA [11648]: [mA] Current point 2 *) (* OldName: p_soll_evu_i2; Cycle: 5 *)
		rP_GrC_SetEUP1 : REAL; (*PARA [11650]: [kW] Power point 1 *) (* OldName: p_soll_evu_p1; Cycle: 5 *)
		rP_GrC_SetEUP2 : REAL; (*PARA [11652]: [kW] Power point 2 *) (* OldName: p_soll_evu_p2; Cycle: 5 *)
		rP_GrC_SetExtP1 : REAL; (* Para: External selected constant power set point 1 *) (* OldName: ssExtPwrSetP1; Cycle: 5 *)
		rP_GrC_SetExtP2 : REAL; (* Para: External selected constant power set point 2 *) (* OldName: ssExtPwrSetP2; Cycle: 5 *)
		rP_GrC_SetExtP3 : REAL; (* Para: External selected constant power set point 3 *) (* OldName: ssExtPwrSetP3; Cycle: 5 *)
		rP_GrC_SetExtP4 : REAL; (* Para: External selected constant power set point 4 *) (* OldName: ssExtPwrSetP4; Cycle: 5 *)
		rP_GrC_SetExtP5 : REAL; (* Para: External selected constant power set point 5 *) (* OldName: ssExtPwrSetP5; Cycle: 5 *)
		rExtPwrSetEUP1 : REAL; (*PARA [11640]: Netz/stat. Grid Code/power setpoint *) (* OldName: ssExtPwrSetEVUP1; Cycle: 5 *)
		rExtPwrSetEUP2 : REAL; (*PARA [11641]: Netz/stat. Grid Code/power setpoint *) (* OldName: ssExtPwrSetEVUP2; Cycle: 5 *)
		rExtPwrSetEUP3 : REAL; (*PARA [11642]: Netz/stat. Grid Code/power setpoint *) (* OldName: ssExtPwrSetEVUP3; Cycle: 5 *)
		rExtPwrSetEUP4 : REAL; (*PARA [11643]: Netz/stat. Grid Code/power setpoint *) (* OldName: ssExtPwrSetEVUP4; Cycle: 5 *)
		rExtPwrSetEUP5 : REAL; (*PARA [11644]: Netz/stat. Grid Code/power setpoint *) (* OldName: ssExtPwrSetEVUP5; Cycle: 5 *)
		iQPF_GrC_SetEUCOn : USINT; (*PARA [11637]: Choice for power factor functions *) (* OldName: ucQPF_evu_XT; Cycle: 5 *)
		rPF_GrC_SetEU : REAL; (*PARA [11666]: Power factor internal set point *) (* OldName: rPF_Soll_evu; Cycle: 5 *)
		rPF_GrC_SetEUAct_BU : REAL; (*PARA [11667]: Power factor backup set point *) (* OldName: rPF_Soll_evu_backup; Cycle: 5 *)
		rPF_GrC_SetEUI1 : REAL; (*PARA [11668]: [mA] Current point 1 *) (* OldName: ssPF_evu_i1; Cycle: 5 *)
		rPF_GrC_SetEUI2 : REAL; (*PARA [11669]: [mA] Current point 2 *) (* OldName: ssPF_evu_i2; Cycle: 5 *)
		rPF_GrC_SetEUP1 : REAL; (*PARA [11670]: Power factor point 1 *) (* OldName: ssPF_evu_P1; Cycle: 5 *)
		rPF_GrC_SetEUP2 : REAL; (*PARA [11671]: Power factor point 2 *) (* OldName: ssPF_evu_P2; Cycle: 5 *)
		rPF_GrC_Ext1FixEU : REAL; (*PARA [11661]: Netz/stat. Grid Code/cos phi Sollwert intern/extern *) (* OldName: ssPFext1fixEVU; Cycle: 5 *)
		rPF_GrC_Ext2FixEU : REAL; (*PARA [11662]: Netz/stat. Grid Code/cos phi Sollwert intern/extern *) (* OldName: ssPFext2fixEVU; Cycle: 5 *)
		rPF_GrC_Ext3FixEU : REAL; (*PARA [11663]: Netz/stat. Grid Code/cos phi Sollwert intern/extern *) (* OldName: ssPFext3fixEVU; Cycle: 5 *)
		rPF_GrC_Ext4FixEU : REAL; (*PARA [11664]: Netz/stat. Grid Code/cos phi Sollwert intern/extern *) (* OldName: ssPFext4fixEVU; Cycle: 5 *)
		rPF_GrC_Ext5FixEU : REAL; (*PARA [11665]: Netz/stat. Grid Code/cos phi Sollwert intern/extern *) (* OldName: ssPFext5fixEVU; Cycle: 5 *)
		iQ_GrC_SetX : USINT; (*PARA [11636]: Choice for reactive power functions *) (* OldName: ucQset_XT; Cycle: 5 *)
		rQ_GrC_SetInt : REAL; (*PARA [11691]: [kVAr] Reactive power internal set point *) (* OldName: ssQset_intern; Cycle: 5 *)
		rQ_GrC_SetAct_BU : REAL; (*PARA [11676]: [kVAr] Reactive power backup set point *) (* OldName: ssQset_backup; Cycle: 5 *)
		rQ_GrC_SetEUI1 : REAL; (*PARA [11683]: [mA] Current for reactive power point 1 *) (* OldName: ssQset_evu_i1; Cycle: 5 *)
		rQ_GrC_SetEUI2 : REAL; (*PARA [11685]: [mA] Current for reactive power point 2 *) (* OldName: ssQset_evu_i2; Cycle: 5 *)
		rQ_GrC_SetEUP1 : REAL; (*PARA [11687]: [kVAr] Reactive power point 1 *) (* OldName: ssQset_evu_P1; Cycle: 5 *)
		rQ_GrC_SetEUP2 : REAL; (*PARA [11689]: [kVAr] Reactive power point 2 *) (* OldName: ssQset_evu_P2; Cycle: 5 *)
		rQ_GrC_SetEUFix1 : REAL; (*PARA [11678]: [kVAr] External constant reactive power set point 1 *) (* OldName: ssQext1fix; Cycle: 5 *)
		rQ_GrC_SetEUFix2 : REAL; (*PARA [11679]: [kVAr] External constant reactive power set point 2 *) (* OldName: ssQext2fix; Cycle: 5 *)
		rQ_GrC_SetEUFix3 : REAL; (*PARA [11680]: [kVAr] External constant reactive power set point 3 *) (* OldName: ssQext3fix; Cycle: 5 *)
		rQ_GrC_SetEUFix4 : REAL; (*PARA [11681]: [kVAr] External constant reactive power set point 4 *) (* OldName: ssQext4fix; Cycle: 5 *)
		rQ_GrC_SetEUFix5 : REAL; (*PARA [11682]: [kVAr] External constant reactive power set point 5 *) (* OldName: ssQext5fix; Cycle: 5 *)
		iU_GrC_SetX : USINT; (*PARA [11639]: Choice for voltage functions *) (* OldName: ucUset_XT; Cycle: 5 *)
		rU_GrC_SetEU_Nom : REAL; (*PARA [11696]: [V] Nominal voltage for voltage setpoint *) (* OldName: ulUnom_evu; Cycle: 5 *)
		rU_GrC_SetInt : REAL; (*PARA [11701]: Voltage internal set point *) (* OldName: ssUset_intern; Cycle: 5 *)
		rU_GrC_Set_Act_BU : REAL; (*PARA [11695]: Voltage backup set point *) (* OldName: ssUset_backup; Cycle: 5 *)
		rU_GrC_SetEUI1 : REAL; (*PARA [11697]: [mA] Current point 1 *) (* OldName: ssUset_evu_i1; Cycle: 5 *)
		rU_GrC_SetEUI2 : REAL; (*PARA [11698]: [mA] Current point 2 *) (* OldName: ssUset_evu_i2; Cycle: 5 *)
		rU_GrC_SetEUP1 : REAL; (*PARA [11699]: Voltage point 1 *) (* OldName: ssUset_evu_P1; Cycle: 5 *)
		rU_GrC_SetEUP2 : REAL; (*PARA [11700]: Voltage point 2 *) (* OldName: ssUset_evu_P2; Cycle: 5 *)
		bQ_GrC_SetEUCOn_Lim : BOOL; (*PARA [11630]: Reactive power limitation set point from utility active *) (* OldName: b_Qlim_evu_act; Cycle: 5 *)
		rQ_GrC_SetEUI1_Lim : REAL; (*PARA [11684]: [mA] Current point 1 *) (* OldName: ssQlim_evu_i1; Cycle: 5 *)
		rQ_GrC_SetEUI2_Lim : REAL; (*PARA [11686]: [mA] Current point 2 *) (* OldName: ssQlim_evu_i2; Cycle: 5 *)
		rQ_GrC_SetEUP1_Lim : REAL; (*PARA [11688]: [kVAr] Reactive power point 1 *) (* OldName: ssQlim_evu_P1; Cycle: 5 *)
		rQ_GrC_SetEUP2_Lim : REAL; (*PARA [11690]: [kVAr] Reactive power point 2 *) (* OldName: ssQlim_evu_P2; Cycle: 5 *)
		rQ_GrC_SetAct_Lim_BU : REAL; (*PARA [11677]: [kVAr] Reactive power limitation backup set point *) (* OldName: ssQlim_backup; Cycle: 5 *)
		bQAO_GrC_SetCOn : BOOL; (*PARA [11631]: Measuring range Reactive power output signal Off = 0-20 mA, On = 4-20 mA *) (* OldName: bQact_AO_4ma; Cycle: 5 *)
		rQAO_GrC_SetP1 : REAL; (*PARA [11692]: [kVAr] Reactive power output signal at 0/4 mA *) (* OldName: ssQact_AO_P1; Cycle: 5 *)
		rQAO_GrC_SetP2 : REAL; (*PARA [11693]: [kVAr] Reactive power output signal at 0/4 mA *) (* OldName: ssQact_AO_P2; Cycle: 5 *)
		bPFAO_GrC_Set4mA : BOOL; (*PARA [11624]: Measuring range cos phi output signalOff = 0-20 mA, On = 4-20 mA *) (* OldName: bPFact_AO_4ma; Cycle: 5 *)
		rPFAO_GrC_SetP1 : REAL; (*PARA [11672]: Cos phi output signal at 0/4 mA *) (* OldName: ssPFact_AO_P1; Cycle: 5 *)
		rPFAO_GrC_SetP2 : REAL; (*PARA [11673]: Cos phi output signal at 0/4 mA *) (* OldName: ssPFact_AO_P2; Cycle: 5 *)
		rF_Nom : ARRAY[0..2]OF REAL; (*PARA [11736], [11737]: nominal frequency [48..62Hz] *) (* OldName: usFreqNenn[1]; Cycle: 5 *)
		bGridCode_Active : BOOL; (*PARA [11055]: Gride Code active *) (* OldName:bGridCode; Cycle: *)
		bPF_CosPCtr_Ena : BOOL; (*PARA [11487]: enable power factor controller on visualization*) (*Oldname:bQPF_XT;Cycle:5*)
		rU_Gen_Nom : ARRAY[0..2]OF REAL; (*PARA [11597], [11598]: nominal voltage generator [70V..65kV] *) (* OldName:usUNennGen; Cycle: *)
		bPRamp_GrC_SetPFCCOn : BOOL; (*PARA [11628]: Power ramp after PFC active *) (* OldName: bSlowRampPFC; Cycle: 5 *)
		rP_Set_ExtAI_NormScalMin : REAL; (*PARA [11795]: external power setpoint via analog input related to rP_Nom P at point 1 *) (* OldName:p_soll_p1; Cycle: *)
		rP_Set_ExtAI_NormScalMax : REAL; (*PARA [11794]: external power setpoint via analog input related to rP_Nom P at point 2 *) (* OldName:p_soll_p2; Cycle: *)
		bAFC_manual : BOOL; (* Para: TRUE = droop values can be changed manual *)
		rAFC_Droop_Down : REAL; (* Para: droop for positive frequency deviation *)
		rAFC_Droop_Up : REAL; (* Para: droop for negative frequency deviation *)
		rAFC_Deadband : REAL; (* Para: indicates within which frequency band the AFC function should not be activated *)
		bAFC_HFC : BOOL; (* Para: TRUE = infinity frequency response *)
		tiPOR_Active : TIME; (* Para: activation time for primary operation reserve *)
		tiSOR_Active : TIME; (* Para: activation time for secondary operation reserve *)
		tiTOR1_Active : TIME; (* Para: activation time for tertiary 1 operation reserve *)
		tiTOR2_Active : TIME; (* Para: activation time for tertiary 2 operation reserve *)
		tiRR_Active : TIME; (* Para: activation time for replacement reserve *)
		tiSR_Active : TIME; (* Para: activation time for substitute reserve *)
		iAFC_CalcMethode : USINT; (* Para: defines the calculation methode *)
		bDEIE_Active : BOOL; (*PARA [13691]: ERDF task active *)
		tiDelayDEIE : TIME; (*PARA [13692]: Time for mains failure DEIE [ms]*)
		bILF_ena : BOOL; (*PARA [15007]: acitvation ILF Local Frequency Integrator*)
		bSet_FC_COn : BOOL; (*PARA [13429]: acitvation FC Frequency Control*)
		bSet_FC_Input : BOOL; (*PARA [13430]: choose if Input [0 ... Standard Input; 1 ... External Input]*)
		rDroop_FC_pos : REAL; (*PARA [13431]: positive Droop [%]*)
		rDroop_FC_neg : REAL; (*PARA [13432]: negative Droop [%]*)
		rSetMarg_FC_StaInp_Neg : REAL; (*PARA [13968]: Margin for Standard Input Neg [%]*)
		rSetMarg_FC_StaInp : REAL; (*PARA [13433]: Margin for Standard Input [%]*)
		iSet_FC_ExtInp : INT; (*PARA [13434]: selection of external Input [1 = e2M Bus, 2 = e2m HW, 3 = next-Box Bus, 4 = next-Box HW, ]*)
		rSetMarg_FC_pos : REAL; (*PARA [13435]: Default power activation for PRL positive [% Pnenn]*)
		rSetMarg_FC_neg : REAL; (*PARA [13436]: Default power activation for PRL negative [% Pnenn]*)
		rF_FC_Dlt_pos : REAL; (*PARA [13437]: delta frequency positive [Hz]*)
		rF_FC_Dlt_neg : REAL; (*PARA [13438]: delta frequency negative [Hz]*)
		rF_FC_Deadband_pos : REAL; (*PARA [13439]: Deadband positive [Hz]*)
		rF_FC_Deadband_neg : REAL; (*PARA [13440]: Deadband negative [Hz]*)
		bPRamp_FC_SetCOn : BOOL; (*PARA [13455]: activation of power ramp for frequency control*)
		bPRamp_FC_ExtInp : BOOL; (*PARA [13458]: external input for power ramp*)
		rPRamp_FC_IncGrad_Norm : REAL; (*PARA [13456]: positive gradient load ramp*)
		rPRamp_FC_DecGrad_Norm : REAL; (*PARA [13457]: negative gradient load ramp*)
		bCalc_PRamp_FC_active : BOOL; (*PARA [13499]: calculation of load ramp active*)
		tiSetTime_FC_PRamp : TIME; (*PARA [13500]: load ramp time [s]*)
		bSet_FC_TimeActFunctCOn : BOOL; (*PARA [13441]: activation of Time Activated Functions [Hz]*)
		bSet_FC_HFRCOn : BOOL; (*PARA [13442]: HFR (High Frequency Response) activation*)
		bSet_FC_PORCOn : BOOL; (*PARA [13443]: POR (Primary Operational Reserve) activation*)
		tiSetTime_FC_POR : TIME; (*PARA [13444]: POR (Primary Operational Reserve) time*)
		bSet_FC_SORCOn : BOOL; (*PARA [13445]: SOR (Secondary Operational Reserve) activation*)
		tiSetTime_FC_SOR : TIME; (*PARA [13446]: SOR (Secondary Operational Reserve) time*)
		bSet_FC_TORCOn : BOOL; (*PARA [13447]: TOR (Tertiary Operational Reserve) activation*)
		tiSetTime_FC_TOR : TIME; (*PARA [13448]: TOR (Tertiary Operational Reserve) time*)
		bSet_FC_TOR2COn : BOOL; (*PARA [13449]: TOR 2 (Tertiary 2 Operational Reserve) activation*)
		tiSetTime_FC_TOR2 : TIME; (*PARA [13450]: TOR 2 (Tertiary 2 Operational Reserve) time*)
		bSet_FC_RRCOn : BOOL; (*PARA [13451]: RR (Replacement Reserve) activation*)
		tiSetTime_FC_RR : TIME; (*PARA [13452]: RR (Replacement Reserve) time*)
		bSet_FC_SRCOn : BOOL; (*PARA [13453]: SR (Substitute Reserve) activation*)
		tiSetTime_FC_SR : TIME; (*PARA [13454]: SR (Substitute Reserve) time*)
		iSet_FC_Testmode : INT; (*PARA [13496]: selection of testmode*)
		rFNom_FC_ManualTest : REAL; (*PARA [13497]: frequency setpoint for testmode 2*)
		rFAct_FC_ManualTest : REAL; (*PARA [13498]: actual frequency for testmode 4*)
		iEng_Motortype : INT;
		rP_Ramp_IncGrad_Norm : ARRAY[1..4]OF REAL;
		rP_Ramp_DecGrad_Norm : ARRAY[1..4]OF REAL;
		rF_FC_Deadband_TAF_pos : REAL; (*PARA [13678]: positive deathband for time activated functions*)
		rF_FC_Deadband_TAF_neg : REAL; (*PARA [13679]: negative deathband for time activated functions*)
		rP_SetMarg_FC_TAF : REAL; (*PARA [13680]: PRL margin for time activated functions*)
		iQ_GrC_PointRef : INT; (*PARA [13993]: Point of reference of reactive power function*)
		iQ_GrC_PointCtrl : INT; (*PARA [13992]: Point of control of reactive power function*)
		iQ_GrC_CtrlFun : USINT; (*PARA [13991]: select Q/PF control function: 0:custom 1:PFset 2:PF(P) 3:PF(U) 4:Q(U) 5:Q(P) 6:Qset 7:Uset 8:time table*)
		rQU_GrC_UpointX : ARRAY[0..7]OF REAL; (*PARA [13996], [13997], [13998], [13999], [14000], [14001], [14002]: Defines the U data point of function Q(U)*)
		rQU_GrC_QpointY : ARRAY[0..7]OF REAL; (*PARA [14004], [14005], [14006], [14007], [14008], [14009], [14010]: Defines the Q data point of function Q(U)*)
		iQU_GrC_DataPoints : INT; (*PARA [13994]: Defines the number of data points. Any data point beyond will not be included.*)
		rQP_GrC_PpointX : ARRAY[0..7]OF REAL; (*PARA [14047], [14048], [14049], [14050], [14051], [14052], [14053]: Defines the P data point of function Q(P)*)
		rQP_GrC_QpointY : ARRAY[0..7]OF REAL; (*PARA [14055], [14056], [14057], [14058], [14059], [14060], [14061]: Defines the Q data point of function Q(P)*)
		iQP_GrC_DataPoints : INT; (*PARA [14045]: Defines the number of data points. Any data point beyond will not be included.*)
		rPFP_GrC_PpointX : ARRAY[0..7]OF REAL; (*PARA [14030], [14031], [14032], [14033], [14034], [14035], [14036]: Defines the P data point of function PF(P)*)
		rPFP_GrC_PFpointY : ARRAY[0..7]OF REAL; (*PARA [14038], [14039], [14040], [14041], [14042], [14043], [14044]: Defines the PF data point of function PF(P)*)
		iPFP_GrC_DataPoints : INT; (*PARA [14028]: Defines the number of data points. Any data point beyond will not be included.*)
		rQU_PFU_GrC_Hyst : REAL; (*PARA [14062]: The hysteresis refers to the active function Q(U) or cosphi(U) and shifts the curve with the given value. *)
		rU_GrC_DeadBand : REAL; (*PARA [14063]: Defines the dead band applied on the voltage signal of function Q(U), cosphi(U)*)
		rS_Nom : REAL; (*PARA [11571]: Nominal Aparent Power (kVA)*)
		rPFU_GrC_UpointX : ARRAY[0..7]OF REAL; (*PARA [14013], [14014], [14015], [14016], [14017], [14018], [14019]: Defines the U data point of function PF(U)*)
		rPFU_GrC_PFpointY : ARRAY[0..7]OF REAL; (*PARA [14021], [14022], [14023], [14024], [14025], [14026], [14027]: Defines the PF data point of function PF(U)*)
		iPFU_GrC_DataPoints : INT; (*PARA [14011]: Defines the number of data points. Any data point beyond will not be included.*)
		rQP_PFP_GrC_Hyst : REAL; (*PARA [14075]: The hysteresis refers to the active function Q(P) or cosphi(P) and shifts the curve with the given value. *)
		bMMD2_Act : BOOL; (*PARA [11713]: Activation of the 2nd multi measurement device.*)
		bSet_GrC_LFSMO_COn : BOOL; (*PARA [14070]: Activates the LFSM-O function and allows the input of all other parameters*)
		bSet_GrC_LFSMU_COn : BOOL; (*PARA [14069]: Activates the LFSM-U function and allows the input of all other parameters*)
		rDroop_GrC_LFSMO_pos : REAL; (*PARA [14073]: Defines the rate of power reduction based on the overfrequency level. *)
		rDroop_GrC_LFSMU_neg : REAL; (*PARA [14074]: Defines the rate of powerchange based on the underfrequency level.*)
		rF_LFSMO_GrC_DeadBand_pos : REAL; (*PARA [14071]: Defines the frequency limit (in the over-frequency range) where the power reduction is released. *)
		rF_LFSMU_GrC_DeadBand_neg : REAL; (*PARA [14072]: Defines the frequency limit (in the under-frequency range) where the power increase is released. *)
		bLFSM_GrC_Pref : BOOL; (*PARA [14076]: Defines the reference power Pref to calculate the power reduction based on the droop setting (0: Pmom is the power when the frequency exceeds the frequency threshold/ 1: nominal power of the engine)*)
		bHyst_GrC_COn : BOOL; (*PARA [14077]: The adjusted power (at max. measured frequency) is kept until the frequency drops below the hysteresis threshold limit*)
		rHyst_GrC_DeadBand : REAL; (*PARA [14078]: Defines the threshold value of the hysteresis. *)
		rPU_GrC_Uknick : REAL; (*PARA [14084]: voltage point at which the function will start to operate*)
		rPU_GrC_Ugrenz : REAL; (*PARA [14085]: voltage point at which the function will stop to operate*)
		bPU_GrC_SetCOn : BOOL; (*PARA [14083]: Activate/deactivate the P(U) function*)
		rU_droop : REAL; (*PARA [14081]: Droop for voltage control calculation*)
		tiQ_Ramp : TIME; (*PARA [14080]: Time constant for Q filter*)
		bSet_FC_StepOn : BOOL; (*PARA [13967]: Activation FC step functionality*)
		bQLim_QU_active : BOOL; (*PARA [14082]: Q Limitation based on QU curve activated*)
		bRelFreeze_Uset_EU : BOOL; (*PARA [14292]: Freeze Uset from EU if AI signal lost*)
		bRelFreeze_PF_EU : BOOL; (*PARA [14293]: Freeze PFset from EU if AI signal lost*)
		bRelFreeze_Qset_EU : BOOL; (*PARA [14294]: Freeze Qset from EU if AI signal lost*)
		bRelFreeze_PLim_EU : BOOL; (*PARA [14295]: Freeze Plim from EU if AI signal lost*)
		bRelFreeze_QLim_EU : BOOL; (*PARA [14296]: Freeze Qlim from EU if AI signal lost*)
		bRelFreeze_Pset_EU : BOOL; (*PARA [14297]: Freeze Pset from EU if AI signal lost*)
		rQLimU_GrC_UpointX : ARRAY[0..3]OF REAL; (*PARA [14451], [14452], [14453], [14454]: Defines the U data point of function Q limit(U)*)
		rQLimU_GrC_QpointY : ARRAY[0..3]OF REAL; (*PARA [14447], [14448], [14449], [14450]: Defines the Q data point of function Q limit(U)*)
		bPowerRampEU_Ena : BOOL; (*PARA [14291]: Ramp from EU aktiv *)
		rF_Deadband_TB : REAL; (*PARA [14290]: Deadband for frequency filter *)
		ti_FreqFilt_TB : TIME; (* Para: Time for frequency filter *)
		rFNom_LFSM_Ref : REAL; (*PARA [14288]: Frequency reference for FSM/LFSM [Hz]*)
		iSet_GrC_FSM : INT; (*PARA [14351]: Choice for FSM activation 0=not used, 1=Internal Setpoint, 2=External AI, 3=External Bus *)
		tiLFSM_GrC_Entry : TIME; (*PARA [14413]: LFSM delay time - entry*)
		tiLFSM_GrC_Exit : TIME; (*PARA [14414]: LFSM delay time - exit*)
		bPRamp_GrC_AftPLim_Active : BOOL; (*PARA [14412]: Slow power ramp after power setpoint from utility active*)
		rPRamp_GrC_AftPLim : REAL; (*PARA [14411]: Slow power ramp after power setpoint from utility*)
		bPRamp_GrC_AftGridConn_Active : BOOL; (*PARA [14479]: power ramp after mains connection active*)
		rPRamp_GrC_AftGridConn : REAL; (*PARA [14480]: power ramp after mains connection*)
		bQ_SetFilt_PT2 : BOOL; (*PARA [14482]: reactive power filter: 0=PT1, 1=PT2 behavior*)
		bEU_BlockResetMan : BOOL; (*PARA [14481]: module blocked from grid operator - manual reset active*)
		bLFSM_StaticFSMDeadband : BOOL; (*PARA [14721]: LFSM power setpoint with static FSM deadband*)
		rP_FSM_DeltaLimPos : REAL; (*PARA [14946]: FSM Maximum positive power change*)
		rP_FSM_DeltaLimNeg : REAL; (*PARA [14947]: FSM Maximum negative power change*)
		rF_errDeActive : REAL; (*PARA [15009]: ILF deltaF error deactivation*)
		rF_errActive : REAL; (*PARA [15008]: ILF deltaF error activation*)
	END_STRUCT;
	VIS2MM_Struct : 	STRUCT  (*OPC variables from VIS to module*)
		bPFC_TestStart : BOOL; (*Start PFC Test*)
		bQU_PFU_TestStart : BOOL; (*Start QU PFU Test*)
		bQU_PFU_TestStop : BOOL; (*Stop QU PFU Test*)
		bPFC_TestStop : BOOL; (*Stop PFC Test*)
		rU_Act_sim_HMI : REAL; (*Simulated Actual Voltage*)
		bFSM_Zoom : BOOL; (*Zoom function for FSM/LFSM visualization*)
		iSet_FSM_Testmode : INT; (* Frequency Control Testmode [1= AUTO Höcker über Frequenzsollwert, 2 = MAN über FrequenzSollwert, 3 = AUTO Höcker über FrequenzIstwert, 4 = MAN über FreuqenzIstwert]*)
		rFNom_FSM_ManualTest : REAL; (* Frequency setpoint for testmode 2*)
		rFAct_FSM_ManualTest : REAL; (* Actual frequency for testmode 4*)
		bLFSM_TestStart : BOOL; (* Start of testmode*)
		bLFSM_TestStop : BOOL; (* Stop of testmode*)
		iSet_FC_Testmode : INT; (* Frequency Control Testmode [1= AUTO Höcker über Frequenzsollwert, 2 = MAN über FrequenzSollwert, 3 = AUTO Höcker über FrequenzIstwert, 4 = MAN über FreuqenzIstwert]*)
	END_STRUCT;
	GRID2CUSTOM_Struct : 	STRUCT 
		rDroop_GrC_FSMU : REAL; (*FSMU Droop reference [Hz]*)
		rDroop_GrC_FSMO : REAL; (*FSMO Droop reference [Hz]*)
		rFSMU_GRC_DB : REAL; (*FSMU Deadband reference [Hz]*)
		rFSMO_GRC_DB : REAL; (*FSMO Deadband reference [Hz]*)
		bSet_GrC_ILF : BOOL; (*ILF function active*)
		bSet_GrC_FSM : BOOL; (*FSM function active*)
		rFNom_LFSM_Ref : REAL; (*Frequency reference for FSM/LFSM [Hz]*)
		bLFSM_Test_On : BOOL; (* Test FC active *)
		iSet_FC_Testmode : INT; (* Testmode [0 = testmode off / 1 = AUTO square wave nominal frequency / 2 = MAN nominal frequency  / 3 = AUTO square wave current frequency / 4 = MAN current frequency] *)
		rFNom_FSM_ManualTest : REAL; (* MAN test - Adjustable nominal frequency [Hz] *)
		rFAct_FSM_ManualTest : REAL; (* MAN test - Adjustable current frequency [Hz] *)
		rMarg_GrC_FSM_Pos : REAL; (* Power margin FSM positiv [%] *)
		rMarg_GrC_FSM_Neg : REAL; (* Power margin FSM negativ [%] *)
		bCheck_GR2CU : BOOL; (* Controlbit for Grid to Custom structure *)
	END_STRUCT;
	CUSTOM2GRID_Struct : 	STRUCT 
		bLFSMO_DB_AI_COn : BOOL; (* AI:LFSMO Deadband set command on *)
		bLFSMO_DB_AI_COf : BOOL; (* AI:LFSMO Deadband set command off *)
		bLFSMO_DB_BC_COn : BOOL; (* Bus:LFSMO Deadband set command on *)
		bLFSMO_DB_BC_COf : BOOL; (* Bus:LFSMO Deadband set command off *)
		rF_LFSMO_DB_BC : REAL; (* Bus: Scaling value LFSMO Deadband from EU [Hz] *)
		bLFSMO_DB_BC_SetErr : BOOL; (* Bus: LFSMO Deadband measuring signal failure *)
		bLFSMU_DB_AI_COn : BOOL; (* AI:LFSMU Deadband set command on *)
		bLFSMU_DB_AI_COf : BOOL; (* AI:LFSMU Deadband set command off *)
		bLFSMU_DB_BC_COn : BOOL; (* Bus:LFSMU Deadband set command on *)
		bLFSMU_DB_BC_COf : BOOL; (* Bus:LFSMU Deadband set command off *)
		rF_LFSMU_DB_BC : REAL; (* Bus: Scaling value LFSMU Deadband from EU [Hz] *)
		bLFSMU_DB_BC_SetErr : BOOL; (* Bus: LFSMU Deadband measuring signal failure *)
		bLFSMO_Droop_AI_COn : BOOL; (* AI:LFSMO Droop set command on *)
		bLFSMO_Droop_AI_COf : BOOL; (* AI:LFSMO Droop set command off *)
		bLFSMO_Droop_BC_COn : BOOL; (* Bus:LFSMO Droop set command on *)
		bLFSMO_Droop_BC_COf : BOOL; (* Bus:LFSMO Droop set command off *)
		rP_LFSMO_Droop_BC : REAL; (* Bus: Scaling value LFSMO Droop from EU [Hz] *)
		bLFSMO_Droop_BC_SetErr : BOOL; (* Bus: LFSMO Droop measuring signal failure *)
		bLFSMU_Droop_AI_COn : BOOL; (* AI:LFSMU Droop set command on *)
		bLFSMU_Droop_AI_COf : BOOL; (* AI:LFSMU Droop set command off *)
		bLFSMU_Droop_BC_COn : BOOL; (* Bus:LFSMU Droop set command on *)
		bLFSMU_Droop_BC_COf : BOOL; (* Bus:LFSMU Droop set command off *)
		rP_LFSMU_Droop_BC : REAL; (* Bus: Scaling value LFSMU Droop from EU [Hz] *)
		bLFSMU_Droop_BC_SetErr : BOOL; (* Bus: LFSMU Droop measuring signal failure *)
		bFSMU_Droop_AI_COn : BOOL; (* AI:FSMU Droop set command on *)
		bFSMU_Droop_AI_COf : BOOL; (* AI:FSMU Droop set command off *)
		bFSMU_Droop_BC_COn : BOOL; (* Bus:FSMU Droop set command on *)
		bFSMU_Droop_BC_COf : BOOL; (* Bus:FSMU Droop set command off *)
		rP_FSMU_Droop_BC : REAL; (* Bus: Scaling value FSMU Droop from EU [Hz] *)
		bFSMU_Droop_BC_SetErr : BOOL; (* Bus: FSMU Droop measuring signal failure *)
		bFSMO_Droop_AI_COn : BOOL; (* AI:FSMO Droop set command on *)
		bFSMO_Droop_AI_COf : BOOL; (* AI:FSMO Droop set command off *)
		bFSMO_Droop_BC_COn : BOOL; (* Bus:FSMO Droop set command on *)
		bFSMO_Droop_BC_COf : BOOL; (* Bus:FSMO Droop set command off *)
		rP_FSMO_Droop_BC : REAL; (* Bus: Scaling value FSMO Droop from EU [Hz] *)
		bFSMO_Droop_BC_SetErr : BOOL; (* Bus: FSMO Droop measuring signal failure *)
		bFSMU_DB_AI_COn : BOOL; (* AI:FSMU Deadband set command on *)
		bFSMU_DB_AI_COf : BOOL; (* AI:FSMU Deadband set command off *)
		bFSMU_DB_BC_COn : BOOL; (* Bus:FSMU Deadband set command on *)
		bFSMU_DB_BC_COf : BOOL; (* Bus:FSMU Deadband set command off *)
		rF_FSMU_DB_BC : REAL; (* Bus: Scaling value FSMU Deadband from EU [Hz] *)
		bFSMU_DB_BC_SetErr : BOOL; (* Bus: FSMU Deadband measuring signal failure *)
		bFSMO_DB_AI_COn : BOOL; (* AI:FSMO Deadband set command on *)
		bFSMO_DB_AI_COf : BOOL; (* AI:FSMO Deadband set command off *)
		bFSMO_DB_BC_COn : BOOL; (* Bus:FSMO Deadband set command on *)
		bFSMO_DB_BC_COf : BOOL; (* Bus:FSMO Deadband set command off *)
		rF_FSMO_DB_BC : REAL; (* Bus: Scaling value FSMO Deadband from EU [Hz] *)
		bFSMO_DB_BC_SetErr : BOOL; (* Bus: FSMO Deadband measuring signal failure *)
		bFSM_RMC_Up_AI_COn : BOOL; (* AI: Positive Margin FSM set command on *)
		bFSM_RMC_Up_AI_COf : BOOL; (* AI: Positive Margin FSM set command off *)
		bFSM_RMC_Up_BC_COn : BOOL; (* Bus: Positive Margin FSM set command on*)
		bFSM_RMC_Up_BC_COf : BOOL; (* Bus: Positive Margin FSM set command off *)
		rP_FSM_RMC_Up_BC : REAL; (* Bus: Scaling value for positive Margin FSM from EU [%Pn]*)
		bFSM_RMC_Up_BC_SetErr : BOOL; (* Bus: Positive Margin FSM setpoint measuring signal failure *)
		bFSM_RMC_Down_AI_COn : BOOL; (* AI: Negative Margin FSM set command on *)
		bFSM_RMC_Down_AI_COf : BOOL; (* AI: Negative Margin FSM set command off *)
		bFSM_RMC_Down_BC_COn : BOOL; (* Bus: Negative Margin FSM set command on*)
		bFSM_RMC_Down_BC_COf : BOOL; (* Bus: Negative Margin FSM set command off *)
		rP_FSM_RMC_Down_BC : REAL; (* Bus: Scaling value for negative Margin FSM from EU [%Pn]*)
		bFSM_RMC_Down_BC_SetErr : BOOL; (* Bus: Negative Margin FSM setpoint measuring signal failure *)
		bU_Droop_AI_COn : BOOL; (* AI: Droop U set command on *)
		bU_Droop_AI_COf : BOOL; (* AI: Droop U set command off *)
		bU_Droop_BC_COn : BOOL; (* Bus: Droop U set command on*)
		bU_Droop_BC_COf : BOOL; (* Bus: Droop U set command off *)
		rU_Droop_BC : REAL; (* Bus: Scaling value for droop U from EU [%]*)
		bU_Droop_BC_SetErr : BOOL; (* Bus: Droop U setpoint measuring signal failure *)
		bFSM_Rmp_AI_COn : BOOL; (* AI: Ramp rate set command on *)
		bFSM_Rmp_AI_COf : BOOL; (* AI: Ramp rate set command off *)
		bFSM_Rmp_BC_COn : BOOL; (* Bus: Ramp rate set command on*)
		bFSM_Rmp_BC_COf : BOOL; (* Bus: Ramp rate set command off *)
		rP_FSM_Rmp_Up_BC : REAL; (* Bus: Scaling value for ramp rate from EU [%Pnom/s]*)
		bFSM_Rmp_BC_SetErr : BOOL; (* Bus: Ramp rate setpoint measuring signal failure *)
		rP_FSM_Rmp_Down_BC : REAL; (* Bus: Scaling value for ramp rate DOWN from EU [%Pnom/s]*)
		bF_Ref_FSM_AI_COn : BOOL; (* AI: Frequency reference for FSM/LFSM set command on *)
		bF_Ref_FSM_AI_COf : BOOL; (* AI: Frequency reference for FSM/LFSM set command off *)
		bF_Ref_FSM_BC_COn : BOOL; (* Bus: Frequency reference for FSM/LFSM set command on*)
		bF_Ref_FSM_BC_COf : BOOL; (* Bus: Frequency reference for FSM/LFSM set command off *)
		rF_Ref_FSM_BC : REAL; (* Bus: Scaling value for Frequency reference for FSM/LFSM from EU [%Pnom/s]*)
		bF_Ref_FSM_BC_SetErr : BOOL; (* Bus: Frequency reference for FSM/LFSM setpoint measuring signal failure *)
		bLFSM_TestStop : BOOL; (* Stop of FC testmode *)
		bCheck_CU2GR : BOOL; (* Controlbit for Custom to Grid structure *)
	END_STRUCT;
	HALIO2GRID_Struct : 	STRUCT 
		tF_LFSMO_DB : HALioAi_Type; (* LFSMO Deadband from EU [Hz] *)
		tF_LFSMU_DB : HALioAi_Type; (* LFSMU Deadband from EU [Hz] *)
		tF_LFSMO_Droop : HALioAi_Type; (* LFSMO Droop from EU [Hz] *)
		tF_LFSMU_Droop : HALioAi_Type; (* LFSMU Droop from EU [Hz] *)
		tF_FSMU_Droop : HALioAi_Type; (* FSMU Droop from EU [Hz] *)
		tF_FSMO_Droop : HALioAi_Type; (* FSMO Droop from EU [Hz] *)
		tF_FSMU_DB : HALioAi_Type; (* FSMU Deadband from EU [Hz] *)
		tF_FSMO_DB : HALioAi_Type; (* FSMO Deadband from EU [Hz] *)
		tP_FSM_RMC_Up : HALioAi_Type; (* Positive Margin FSM from EU [%Pnom] *)
		tP_FSM_RMC_Down : HALioAi_Type; (* Negative Margin FSM from EU [%Pnom] *)
		tU_Droop : HALioAi_Type; (* U droop from EU [%] *)
		tFSM_Rmp_Up : HALioAi_Type; (* Ramp rate UP from EU [%Pnom/s] *)
		tFSM_Rmp_Down : HALioAi_Type; (* Ramp rate DOWN from EU [%Pnom/s] *)
		tF_Ref_FSM : HALioAi_Type; (* Reference frequency for FSM/LFSM from EU [Hz] *)
		tJunctionBox_GnlAlm : HALioDi_Type; (* DI:General Alarm from junction box *)
		bCheck_HA2GR : BOOL; (* Controlbit for HALio to Grid structure *)
	END_STRUCT;
END_TYPE
