(*******************************************************************************
GasMixer: control up to 2 gasmixer positions  (init)

This code is confidential and proprietary to the INNIO Company.
It may not be used in any form, or reproduced in any manner,
without the express written permission of the INNIO Company.
Copyright, INNIO Company, 2019
 
Customized modifications: -
------------------------
 
History:
-------
V03.99.00.00	10.01.2013 	Tinello 	restructured

Instructions for use: -
--------------------

Outstandings: -
------------

(*******************************************************************************)
PROGRAM _INIT

	(* carry out a reference set *)	
	bGM1_SetRef	:= TRUE;	
	bGM2_SetRef	:= TRUE;
		
END_PROGRAM


