(********************************************************************
 * COPYRIGHT -- INNIO Company
 ********************************************************************
 * Programm: empfang
 * Datei: empfangInit.st
 * Autor: 105046866
 * Erstellt: 4. Juni 2013
 ********************************************************************
 * Implementierung des Programms empfang
 ********************************************************************)

PROGRAM _INIT


(* TODO : Code hier einfügen *)


END_PROGRAM

