
TYPE
	PROGRAMMER_INFO : 	STRUCT 
		DO_NOT_SORT_PARA : STRING[40] := 'DO NOT CHANGE PARAMETER SORTING!'; (*DO NOT CHANGE PARAMETER SORTING!*) (*ADD NEW PARAMETER ONLY AT THE END OF THE Para STRUCTURE. DO NOT DELETE existing Para items.*)
	END_STRUCT;
	PARA_HC_Struct : 	STRUCT  (*! Add new tags only at the end OF the pm structure!*)
		tCtr_Cust1 : _tGeACtrPara; (*Para controller customized*) (*OldName:bTuneREG1_Invert; Cycle:5;*)
		tCtr_Cust2 : _tGeACtrPara; (*Para controller customized*) (*OldName:bTuneREG2_Invert; Cycle:5;*)
		tCtr_Cust3 : _tGeACtrPara; (*Para controller customized*) (*OldName:bTuneREG3_Invert; Cycle:5;*)
		tCtr_Cust4 : _tGeACtrPara; (*Para controller customized*) (*OldName:bTuneREG4_Invert; Cycle:5;*)
		tCtr_Cust5 : _tGeACtrPara; (*Para controller customized*) (*OldName:bTuneREG5_Invert; Cycle:5;*)
		tCtr_Cust6 : _tGeACtrPara; (*Para controller customized*) (*OldName:bTuneREG6_Invert; Cycle:5;*)
		tCtr_Cust7 : _tGeACtrPara; (*Para controller customized*) (*OldName:bTuneREG7_Invert; Cycle:5;*)
		tCtr_Cust8 : _tGeACtrPara; (*Para controller customized*) (*OldName:bTuneREG8_Invert; Cycle:5;*)
		tCtr_EC : _tGeACtrPara; (*Para controller emergency cooler*) (*OldName:REG11; Cycle:5;*)
		tCtr_HWRe : _tGeACtrPara; (*Para controller heat water return temperature*) (*OldName:REG10; Cycle:5;*)
		tCtr_HWSu : _tGeACtrPara; (*Para controller heat water supply temperature*) (*OldName:REG14; Cycle:5;*)
		tCtr_ChCHP : _tGeACtrPara; (*Para controller charge temperature cooler high pressure*) (*OldName:REG18; Cycle:5;*)
		tCtr_ChCV : _tGeACtrPara; (*Para controller charge temperature  cooler ventilation*) (*OldName:REG15; Cycle:5;*)
		tCtr_ChC : _tGeACtrPara; (*Para controller charge temperature cooler*) (*OldName:REG9; Cycle:5;*)
		rN_EngStart_LimHi : REAL; (*PARA [11296]: engine start speed limit high [1/min]*) (*OldName:GW_DREHZ; Cycle:5;*)
		rN_EngStart_HyHi : REAL; (*PARA [11295]: engine start speed limit high hysteresis [1/min]*) (*OldName:HY_DREHZ; Cycle:5;*)
		bCtr_ChC : BOOL; (*PARA [11872]: visibility charge temperature controller*) (*OldName:bPlantCtr9,reg0_visible; Cycle:5;*)
		bCtr_ChCV : BOOL; (*PARA [11874]: visibility charge cooler ventilation controller*) (*OldName:bPlantCtr15; Cycle:5;*)
		bCtr_ChCHP : BOOL; (*PARA [11873]: visibility charge temperature controller, high pressure*) (*OldName:bPlantCtr18; Cycle:5;*)
		bCtr_EC : BOOL; (*PARA [11875]: visibility emergency controller(dump radiator)*) (*OldName:bPlantCtr11; Cycle:5;*)
		bCtr_HWRe : BOOL; (*PARA [11876]: visibility heat water return temperature controller*) (*OldName:bPlantCtr10; Cycle:5;*)
		bCtr_HWSu : BOOL; (*PARA [11877]: visibility heat water supply temperature controller*) (*OldName:bPlantCtr14; Cycle:5;*)
		iEng_Motortype : INT; (*Para engine type*) (*OldName:motortyp; Cycle:5;*)
		bT_HW_Su_SF_Trip : BOOL; (*PARA [11893]: temperature heat water supply signal failure trip*) (*OldName:vorl_msa; Cycle:5;*)
		bT_HW_Re_SF_Trip : BOOL; (*PARA [11887]: temperature heat water  return signal failure trip*) (*OldName:rueckl_msa; Cycle:5;*)
		bT_HW_ReAfEC_SF_Trip : BOOL; (*PARA [11889]: temperature heat water  return after EC signal failure trip*) (*OldName:rlt_nk_msa; Cycle:5;*)
		bVISA : BOOL; (*PARA [12259]: monitoring acc. VISA*) (*OldName:VISA; Cycle:5;*)
		rT_AirOutdoor_LimHi2 : REAL; (*PARA [11927]: temperature air outdoor limit high [°C]*) (*OldName:GW_ULT_2; Cycle:5;*)
		rT_AirOutdoor_LimHi3 : REAL; (*PARA [11928]: temperature air outdoor limit high [°C]*) (*OldName:GW_ULT_3; Cycle:5;*)
		rT_AirOutdoor_LimHi4 : REAL; (*PARA [11929]: temperature air outdoor limit high [°C]*) (*OldName:GW_ULT_4; Cycle:5;*)
		rT_AirOutdoor_LimHi1 : REAL; (*PARA [11926]: temperature air outdoor limit high [°C]*) (*OldName:GW_ULT_1; Cycle:5;*)
		rT_AirOutdoor_HyHi2 : REAL; (*PARA [11923]: temperature air outdoor hysteres limit high [°C]*) (*OldName:HY_ULT_2; Cycle:5;*)
		rT_AirOutdoor_HyHi3 : REAL; (*PARA [11924]: temperature air outdoor hysteres limit high [°C]*) (*OldName:HY_ULT_3; Cycle:5;*)
		rT_AirOutdoor_HyHi4 : REAL; (*PARA [11925]: temperature air outdoor hysteres limit high [°C]*) (*OldName:HY_ULT_4; Cycle:5;*)
		rT_AirOutdoor_HyHi1 : REAL; (*PARA [11922]: temperature air outdoor hysteres limit high [°C]*) (*OldName:HY_ULT_1; Cycle:5;*)
		iEC_NumDemAux : INT; (*PARA [11899]: number emergency cooler stages with demand auxiliaries*) (*OldName:Anz_hbt; Cycle:5;*)
		iEC_NumStages : INT; (*PARA [11900]: emergency cooler number of cooling steps total*) (*OldName:K_anz; Cycle:5;*)
		iChC_NumDemAux : INT; (*PARA [11895]: number charge cooler stages with demand auxiliaries*) (*OldName:Anz_GK_hbt; Cycle:5;*)
		iChC_NumStages : INT; (*PARA [11896]: charge cooler number stages*) (*OldName:GK_anz; Cycle:5;*)
		iChC_OpMode : INT; (*PARA [11897]: charge cooler operating mode*) (*OldName:GK_var; Cycle:5;*)
		iChC_CtrNum : INT; (*PARA [11894]: charge cooler controller number*) (*OldName:GK_reg; Cycle:5;*)
		bEC_St1onlyP : BOOL; (*PARA [11879]: emergency cooler first stage only with pump*) (*OldName:K_nmp; Cycle:5;*)
		rEC_ValPosLimHi_On : REAL; (*PARA [11909]: emergency cooler activation from  valve position limit high [%]*) (*OldName:GW_K_EIN; Cycle:5;*)
		rPr_ECW_LimLo1 : REAL; (*PARA [11918]: pressure engine cooling water limit low 1 [bar]*) (*OldName:GW_KDGW1; Cycle:5;*)
		rPr_ECW_LimHiHi : REAL; (*PARA [11916]: pressure engine cooling water limit high high [bar]*) (*OldName:GW_KDMA; Cycle:5;*)
		rPr_ECW_LimLoLo : REAL; (*PARA [11919]: pressure engine cooling water limit low low [bar]*) (*OldName:GW_KDMI; Cycle:5;*)
		rPr_ECW_LimLo : REAL; (*PARA [11917]: pressure engine cooling water limit low [bar]*) (*OldName:GW_KDMI_W; Cycle:5;*)
		rT_ECW_LimHi1 : REAL; (*PARA [11942]: temperature engine cooling water limit high 1 [°C]*) (*OldName:GW_KTGW1; Cycle:5;*)
		rT_ECW_LimHi2 : REAL; (*PARA [11943]: temperature engine cooling water limit high 2 [°C]*) (*OldName:GW_KTGW2; Cycle:5;*)
		rT_ECW_LimHi : REAL; (*PARA [11941]: temperature engine cooling water limit high [°C]*) (*OldName:GW_KTMA; Cycle:5;*)
		rT_ECW_LimLo : REAL; (*PARA [11944]: temperature engine cooling water limit low [°C]*) (*OldName:GW_KTMI; Cycle:5;*)
		rT_ECW_LimRelLoad : REAL; (*PARA [11945]: temperature engine cooling water limit release load [°C]*) (*OldName:GW_LFG; Cycle:5;*)
		rEC_ValPosLimStageDown : REAL; (*PARA [11910]: position emergency cooler valve limit stage down [%]*) (*OldName:GW_MINUS; Cycle:5;*)
		rEC_ValPosLimStageUp : REAL; (*PARA [11911]: position emergency cooler valve limit stage up [%]*) (*OldName:GW_PLUS; Cycle:5;*)
		rT_HW_ReBeEng_LimHi : REAL; (*PARA [11960]: temperature heat water return before engine limit high [°C]*) (*OldName:GW_RLT_M; Cycle:5;*)
		rT_HW_ReBeEng_LimHiHi : REAL; (*PARA [11961]: temperature heat water return before engine limit high high [°C]*) (*OldName:GW_RLT_MA; Cycle:5;*)
		rT_HW_ReAfEC_LimHi : REAL; (*PARA [11956]: temperature heat water return after emergency cooler limit high [°C]*) (*OldName:GW_RLT_NK; Cycle:5;*)
		rT_HW_ReAfEC_LimHiHi : REAL; (*PARA [11957]: temperature heat water return after emergency cooler limit high high [°C]*) (*OldName:GW_RLT_NKA; Cycle:5;*)
		rT_HW_Re_LimHi : REAL; (*PARA [11952]: temperature heat water return limit high [°C]*) (*OldName:GW_RLTP; Cycle:5;*)
		rT_HW_Re_LimHiHi : REAL; (*PARA [11953]: temperature heat water return limit high high [°C]*) (*OldName:GW_RLTPA; Cycle:5;*)
		rT_HW_Su_LimHi : REAL; (*PARA [11964]: temperature heat water supply limit high [°C]*) (*OldName:GW_VLTP; Cycle:5;*)
		rT_HW_Su_LimHiHi : REAL; (*PARA [11965]: temperature heat water supply limit high high [°C]*) (*OldName:GW_VLTPA; Cycle:5;*)
		rT_ECW_PreH_LimOFF : REAL; (*PARA [10089]: temperature engine cooling water preheating limit off [°C]*) (*OldName:GW_VORW; Cycle:5;*)
		rEC_ValPosHyHi_On : REAL; (*PARA [11908]: position valve emergency cooler ON limit high hysteresis [%]*) (*OldName:HY_K_EIN; Cycle:5;*)
		rPr_ECW_HyLo1 : REAL; (*PARA [11914]: pressure engine cooling water limit low 1 hysteresis [bar]*) (*OldName:HY_KDGW1; Cycle:5;*)
		rPr_ECW_HyHiHi : REAL; (*PARA [11912]: pressure engine cooling water limit high high hysteresis [bar]*) (*OldName:HY_KDMA; Cycle:5;*)
		rPr_ECW_HyLoLo : REAL; (*PARA [11915]: pressure engine cooling water limit low low hysteresis [bar]*) (*OldName:HY_KDMI; Cycle:5;*)
		rPr_ECW_HyLo : REAL; (*PARA [11913]: pressure engine cooling water limit low hysteresis [bar]*) (*OldName:HY_KDMI_W; Cycle:5;*)
		rT_ECW_HyHi1 : REAL; (*PARA [11936]: temperature engine cooling water limit high 1 hysteresis [°C]*) (*OldName:HY_KTGW1; Cycle:5;*)
		rT_ECW_HyHi2 : REAL; (*PARA [11937]: temperature engine cooling water limit high 2 hysteresis [°C]*) (*OldName:HY_KTGW2; Cycle:5;*)
		rT_ECW_HyHi : REAL; (*PARA [11935]: temperature engine cooling water limit high hysteresis [°C]*) (*OldName:HY_KTMA; Cycle:5;*)
		rT_ECW_HyLo : REAL; (*PARA [11938]: temperature engine cooling water limit low hysteresis [°C]*) (*OldName:HY_KTMI; Cycle:5;*)
		rT_ECW_HyRelLoad : REAL; (*PARA [11939]: temperature engine cooling water limit release load hysteresis [°C]*) (*OldName:HY_LFG; Cycle:5;*)
		rT_HW_ReBeEng_HyHi : REAL; (*PARA [11958]: temperature heat water return before engine limit high hysteresis [°C]*) (*OldName:HY_RLT_M; Cycle:5;*)
		rT_HW_ReBeEng_HyHiHi : REAL; (*PARA [11959]: temperature heat water return before engine limit high high hysteresis [°C]*) (*OldName:HY_RLT_MA; Cycle:5;*)
		rT_HW_ReAfEC_HyHi : REAL; (*PARA [11954]: temperature heat water return after emergency cooler limit high hysteresis [°C]*) (*OldName:HY_RLT_NK; Cycle:5;*)
		rT_HW_ReAfEC_HyHiHi : REAL; (*PARA [11955]: temperature heat water return after emergency cooler limit high high hysteresis [°C]*) (*OldName:HY_RLT_NKA; Cycle:5;*)
		rT_HW_Re_HyHi : REAL; (*PARA [11950]: temperature heat water return limit high hysteresis [°C]*) (*OldName:HY_RLTP; Cycle:5;*)
		rT_HW_Re_HyHiHi : REAL; (*PARA [11951]: temperature heat water return limit high high hysteresis [°C]*) (*OldName:HY_RLTPA; Cycle:5;*)
		rT_HW_Su_HyHi : REAL; (*PARA [11962]: temperature heat water supply limit high hysteresis [°C]*) (*OldName:HY_VLTP; Cycle:5;*)
		rT_HW_Su_HyHiHi : REAL; (*PARA [11963]: temperature heat water supply limit high high hysteresis [°C]*) (*OldName:HY_VLTPA; Cycle:5;*)
		rT_ECW_PreH_HyOFF : REAL; (*PARA [10088]: temperature engine cooling water preheating limit off hysteresis [°C]*) (*OldName:HY_VORW; Cycle:5;*)
		iEC_NumCtr : INT; (*PARA [11898]: emergency cooler number of PLC controller for valve control*) (*OldName:K_reg; Cycle:5;*)
		iEC_OpMode : INT; (*PARA [11901]: emergency cooler operating mode selection*) (*OldName:K_var; Cycle:5;*)
		bT_HW_ReBeEng_Active : BOOL; (*PARA [11890]: temperature heat water return before engine measurement active*) (*OldName:rlt_m_a; Cycle:5;*)
		bT_HW_ReBeEng_SF_Trip : BOOL; (*PARA [11891]: temperature heat water return before engine signal failure trip*) (*OldName:rlt_msa_a; Cycle:5;*)
		bT_HW_ReAfEC_Active : BOOL; (*PARA [11888]: temperature heat water return after emergency cooler measurement active*) (*OldName:rlt_nk_a; Cycle:5;*)
		bT_HW_Re_Active : BOOL; (*PARA [11886]: temperature heat water return measurement active*) (*OldName:rueckl_a; Cycle:5;*)
		tiEC_DelayOff : TIME; (*PARA [12050]: emergency cooler delay OFF*) (*OldName:TW_K_AUS; Cycle:5;*)
		tiEC_DelayStageDown : TIME; (*PARA [12051]: emergency cooler delay switch stage down*) (*OldName:TW_MINUS; Cycle:5;*)
		tiEC_DelayStageUp : TIME; (*PARA [12052]: emergency cooler delay switch stage up*) (*OldName:TW_PLUS; Cycle:5;*)
		bT_AirOutdoor_Active : BOOL; (*PARA [11885]: air outdoor temperature measurement enable *) (*OldName:ULT_a; Cycle:5;*)
		bT_HW_Su_Active : BOOL; (*PARA [11892]: temperature heat water supply measurement active*) (*OldName:vorl_a; Cycle:5;*)
		rT_Ch_LimHi1 : REAL; (*PARA [11932]: charge temperature high limit 1 [°C]*) (*OldName:GW_LLGW1; Cycle:5;*)
		rT_Ch_LimHi2 : REAL; (*PARA [11933]: charge temperature high limit 2 [°C]*) (*OldName:GW_LLGW2; Cycle:5;*)
		rT_Ch_HyHi1 : REAL; (*PARA [11930]: charge temperature high hysteresis limit 1 [°C]*) (*OldName:HY_LLGW1; Cycle:5;*)
		rT_Ch_HyHi2 : REAL; (*PARA [11931]: charge temperature high hysteresis limit 2 [°C]*) (*OldName:HY_LLGW2; Cycle:5;*)
		rT_EO_LimHi2 : REAL; (*PARA [11949]: engine oil temperature high limit 2 [°C]*) (*OldName:GW_OTGW2; Cycle:5;*)
		rT_EO_LimHi1 : REAL; (*PARA [11948]: engine oil temperature high limit 1 [°C]*) (*OldName:GW_OTGW1; Cycle:5;*)
		rT_EO_HyHi2 : REAL; (*PARA [11947]: engine oil temperature high hysteresis limit 2 [°C]*) (*OldName:HY_OTGW2; Cycle:5;*)
		rT_EO_HyHi1 : REAL; (*PARA [11946]: engine oil temperature high hysteresis limit 1 [°C]*) (*OldName:HY_OTGW1; Cycle:5;*)
		rChC_ValPosLimHi_On : REAL; (*PARA [11905]: position valve charge cooler ON limit high [%]*) (*OldName:GW_GK_EIN; Cycle:5;*)
		rChC_ValPosHyHi_On : REAL; (*PARA [11904]: position valve charge cooler ON limit high hysteresis [%]*) (*OldName:HY_GK_EIN; Cycle:5;*)
		rChC_ValPosLimStageUp : REAL; (*PARA [11907]: position charge cooler valve limit stage up [%]*) (*OldName:GW_GK_PLUS; Cycle:5;*)
		rChC_ValPosLimStageDown : REAL; (*PARA [11906]: position charge cooler valve limit stage down [%]*) (*OldName:GW_GK_MINUS; Cycle:5;*)
		tiChC_DelayOff : TIME; (*PARA [12047]: charge cooler delay OFF*) (*OldName:TW_GK_AUS; Cycle:5;*)
		tiChC_DelayStageUp : TIME; (*PARA [12049]: charge cooler delay switch stage up *) (*OldName:TW_GK_PLUS; Cycle:5;*)
		tiChC_DelayStageDown : TIME; (*PARA [12048]: charge cooler delay switch stage down*) (*OldName:TW_GK_MINUS; Cycle:5;*)
		iPred_T_HW_Re_Sel : INT; (*PARA [11903]: power reduction heat water return temperature high active*) (*OldName:Pred_RLT_act; Cycle:5;*)
		rT_Pred_HW_Re_Start : REAL; (*PARA [11967]: power reduction heat water return temperature high start [°C]*) (*OldName:Pred_RLT_start; Cycle:5;*)
		rPred_T_HW_Re_Rate : REAL; (*PARA [11921]: power reduction heat water return temperature high rate [%/°C]*) (*OldName:Pred_RLT_rate; Cycle:5;*)
		rT_Pred_ECW_Start : REAL; (*PARA [11966]: power reduction engine cooling water temperature high start [°C]*) (*OldName:Pred_KWT_start; Cycle:5;*)
		rPred_ECW_Rate : REAL; (*PARA [11920]: power reduction engine cooling water temperature high rate [%/°C]*) (*OldName:Pred_KWT_rate; Cycle:5;*)
		bAuxEC_Visible : BOOL; (*PARA [11870]: visibility parameters of emergency cooler control*) (*OldName:bAuxilAirCool; Cycle:5;*)
		bEC_St1_Visible : BOOL; (*PARA [11878]: emergency cooler stage 1 visible*) (*OldName:bCoolRadStage1; Cycle:5;*)
		bEC_St2_Visible : BOOL; (*PARA [11880]: emergency cooler stage 2 visible*) (*OldName:bCoolRadStage2; Cycle:5;*)
		bEC_StX_Visible : BOOL; (*PARA [11881]: emergency cooler stage 0-x visible*) (*OldName:bCoolRadStageX; Cycle:5;*)
		bChC_StX_Visible : BOOL; (*PARA [11871]: charge cooler stage0-x visible*) (*OldName:bMixCoolRadStageX; Cycle:5;*)
		bECW_Circuit_Visible : BOOL; (*PARA [11883]: engine cooling water circuit visible*) (*OldName:bVisuCoolCircuit; Cycle:5;*)
		bEC_Visible : BOOL; (*PARA [11882]: graphic for emergency cooler in HYD diagram visible*) (*OldName:bVisuDeskCooler; Cycle:5;*)
		bECW_PreH_Ext_Visible : BOOL; (*PARA [11884]: bypass to 3-way-thermostatic valve visible*) (*OldName:bVisuExtHeating; Cycle:5;*)
		iECW_PreH_Int_Visible : INT; (*PARA [11902]: engine cooling water preheating device visible*) (*OldName:usVisuIntHeating; Cycle:5;*)
		bT_HW_Re_LT_Active : BOOL; (*PARA [12451]: temperature heat water return low temp.circuit measurement active*) (*OldName:bT_HWR_LT_Active; Cycle:5;*)
		rT_HW_Re_LT_LimHi : REAL; (*PARA [12452]: temperature heat water return low temp.circuit limit high [°C]*) (*OldName:newPv; Cycle:5;*)
		rT_HW_Re_LT_HyHi : REAL; (*PARA [12453]: temperature heat water return low temp.circuit limit high hysteresis [°C]*) (*OldName:newPv; Cycle:5;*)
		rT_ECW_LimBpV : REAL; (*PARA [11940]: temperature engine cooling water bypass valve [°C]*) (*OldName:newPv; Cycle:5;*)
		rT_ECW_HyBpV : REAL; (*PARA [11934]: temperature engine cooling water bypass valve hysteresis [°C]*) (*OldName:newPv; Cycle:5;*)
		rT_T2_Set : ARRAY[0..4]OF REAL; (*PARA [11195], [11196], [11197], [11198]: setpoint charge temperature [°C]*) (*OldName:tg_soll[0..4]; Cycle:5;*)
		bAuxChC_Visible : BOOL; (*PARA [11869]: visibility parameters of charge cooler control*) (*OldName:newPv; Cycle:5;*)
		bT_ECWbEng_Active : BOOL; (*PARA [12741]: engine cooling water temperature before engine measurement active M.04-TI-002*) (*OldName:newPv; Cycle:5;*)
		bPr_ECWaEng_Active : BOOL; (*PARA [12739]: engine cooling water pressure after engine measurement active*) (*OldName:newPv; Cycle:5;*)
		bPr_HW_Su_LT_Active : BOOL; (*PARA [12616]: pressure heat water supply low temp.circuit measurement active*) (*OldName:newPv; Cycle:5;*)
		bPr_HW_Su_HT_Active : BOOL; (*PARA [12645]: pressure heat water supply high temp.circuit measurement active*) (*OldName:newPv; Cycle:5;*)
		bT_HW_Su_LT_Active : BOOL; (*PARA [12647]: temperature heat water supply low temp.circuit measurement active*) (*OldName:newPv; Cycle:5;*)
		bPr_HW_Re_LT_Active : BOOL; (*PARA [12892]: pressure heat water return low temp.circuit measurement active M.07-PI-002*) (*OldName:newPv; Cycle:5;*)
		bPr_HW_Re_HT_Active : BOOL; (*PARA [12895]: pressure heat water return high temp.circuit measurement active M.06-PI-002*) (*OldName:newPv; Cycle:5;*)
		bPr_HW_Re_PreH_ECW_Active : BOOL; (*PARA [12898]: pressure heat water return preheating engine cooling water measurement activ M.04-PI-005 *) (*OldName:newPv; Cycle:5;*)
		bPr_HW_Re_PreH_EO_Active : BOOL; (*PARA [12901]: pressure heat water return preheating engine oil measurement active M.03-PI-005*) (*OldName:newPv; Cycle:5;*)
		bPr_EO_Mod_Out_Active : BOOL; (*PARA [12904]: pressure engine oil module outlet measurement active M.03-PI-006*) (*OldName:newPv; Cycle:5;*)
		bT_ECW_Mod_In_Active : BOOL; (*PARA [12908]: temperature engine cooling water, engine cooling water module inlet measurement active M.04-TI-003*) (*OldName:newPv; Cycle:5;*)
		bT_ECW_Mod_Out_Active : BOOL; (*PARA [12909]: temperature engine cooling water, engine cooling water module outlet measurement active M.04-TI-004*) (*OldName:newPv; Cycle:5;*)
		bT_EO_Mod_In_Active : BOOL; (*PARA [12910]: temperature engine oil, oil module inlet measurement active M.03-TI-004*) (*OldName:newPv; Cycle:5;*)
		bT_EO_Mod_Out_Active : BOOL; (*PARA [12911]: temperature engine oil, oil module outlet measurement active M.03-TI-003*) (*OldName:newPv; Cycle:5;*)
		bT_HW_Su_PreH_ECW_Active : BOOL; (*PARA [12912]: temperature heat water supply preheating engine cooling water measurement activ M.04-TI-005 *) (*OldName:newPv; Cycle:5;*)
		bT_HW_Re_PreH_ECW_Active : BOOL; (*PARA [12913]: temperature heat water return preheating engine cooling water measurement activ M.04-TI-006 *) (*OldName:newPv; Cycle:5;*)
		bT_HW_Su_PreH_EO_Active : BOOL; (*PARA [12914]: temperature heat water supply preheating engine oil measurement activ M.03-TI-005 *) (*OldName:newPv; Cycle:5;*)
		bT_HW_Re_PreH_EO_Active : BOOL; (*PARA [12915]: temperature heat water return preheating engine oil measurement activ M.03-TI-006 *) (*OldName:newPv; Cycle:5;*)
		bT_HW_HC_Re_Active : BOOL; (*PARA [13319]: measuring active heat circuit return temperature*) (*OldName:newPv; Cycle:5;*)
		rT_HW_HC_Re_HyHi : REAL; (*PARA [13321]: maximum hysterese heat circuit temperature maximum*) (*OldName:newPv; Cycle:5;*)
		rT_HW_HC_Re_LimHi : REAL; (*PARA [13320]: maximum heat circuit temperature maximum*) (*OldName:newPv; Cycle:5;*)
		bCtr_CDSu : BOOL; (*PARA [13306]: Condensor circuit supply temperature controller*) (*OldName:newPv; Cycle:5;*)
		tCtr_CDSu : _tGeACtrPara; (*Para controller condensor circuit supply temperature*) (*OldName:newPv; Cycle:5;*)
		bT_CD_Re_Active : BOOL; (*PARA [13284]: measuring active return temperature condensor circuit*) (*OldName:newPv; Cycle:5;*)
		rT_CD_Re_HyHi : REAL; (*PARA [13283]: maximum hysterese return temperature condensor circuit*) (*OldName:newPv; Cycle:5;*)
		rT_CD_Re_LimHi : REAL; (*PARA [13282]: maximum return temperature condensor circuit*) (*OldName:newPv; Cycle:5;*)
		bT_CD_Su_Active : BOOL; (*PARA [13281]: measuring active supply temperature condensor circuit*) (*OldName:newPv; Cycle:5;*)
		rT_CD_Su_HyHi : REAL; (*PARA [13280]: maximum hysterese supply temperatur condensor circuit*) (*OldName:newPv; Cycle:5;*)
		rT_CD_Su_LimHi : REAL; (*PARA [13279]: maximum supply temperatur condensor circuit*) (*OldName:newPv; Cycle:5;*)
		bBHV_Active : BOOL; (*PARA [13307]: boiler house flap active*) (*OldName:newPv; Cycle:5;*)
		rT_Su_PriCirc_LimHi : REAL; (*PARA [13156]: supply water temperature high primary circuit [°C]*) (*OldName: new PV   ; Cycle: 5;*)
		rT_Su_PriCirc_HyLimHi : REAL; (*PARA [13157]: supply water temperature high primary circuit hysteresis [°C]*) (*OldName: new PV   ; Cycle: 5;*)
		rT_Re_PriCirc_LimHi : REAL; (*PARA [13159]: return water temperature high primary circuit [°C]*) (*OldName: new PV   ; Cycle: 5;*)
		rT_Re_PriCirc_HyLimHi : REAL; (*PARA [13160]: return water temperature high primary circuit hysteresis [°C]*) (*OldName: new PV   ; Cycle: 5;*)
		rT_Su_SecCirc_LimHi : REAL; (*PARA [13162]: supply water temperature high secondary circuit [°C]*) (*OldName: new PV   ; Cycle: 5;*)
		rT_Su_SecCirc_HyLimHi : REAL; (*PARA [13163]: supply water temperature high secondary circuit hysteresis [°C]*) (*OldName: new PV   ; Cycle: 5;*)
		rT_Re_SecCirc_LimHi : REAL; (*PARA [13165]: return water temperature high secondary circuit [°C]*) (*OldName: new PV   ; Cycle: 5;*)
		rT_Re_SecCirc_HyLimHi : REAL; (*PARA [13166]: return water temperature high secondary circuit hysteresis [°C]*) (*OldName: new PV   ; Cycle: 5;*)
		bT_Su_PriCirc_Active : BOOL; (*PARA [13155]: supply water temperature primary circuit measurement active*) (*OldName: new PV   ; Cycle: 5;*)
		bT_Re_PriCirc_Active : BOOL; (*PARA [13158]: return water temperature primary circuit measurement active*) (*OldName: new PV	; Cycle: 5;*)
		bT_Su_SecCirc_Active : BOOL; (*PARA [13161]: supply water temperature secondary circuit measurement active*) (*OldName: new PV	; Cycle: 5;*)
		bT_Re_SecCirc_Active : BOOL; (*PARA [13164]: return water temperature secondary circuit measurement active*) (*OldName: new PV	; Cycle: 5;*)
		bPos_HW_ReValve : BOOL; (*PARA [13146]: measuring active position control valve heat water return temperature*) (*OldName:newPv; Cycle:5;*)
		bPos_HW_EC_ReValve : BOOL; (*PARA [13147]: measuring active position control valve heat water return temperature after cooler*) (*OldName:newPv; Cycle:5;*)
		bPos_ChCValve : BOOL; (*PARA [13148]: measuring active position control valve charge cooler circuit temperature*) (*OldName:newPv; Cycle:5;*)
		bP_Heat_Active : BOOL; (*PARA [13167]: measuring active heating power engine heat water circuit*) (*OldName:newPv; Cycle:5;*)
		bCnt_P_Heat : BOOL; (*PARA [13170]: counter active heating power engine heat water circuit*) (*OldName:newPv; Cycle:5;*)
		rImpVal_Cnt_P_Heat : REAL; (*PARA [13171]: impulse value counter heating power engine heat water circuit*) (*OldName:newPv; Cycle:5;*)
		bHWF_Active : BOOL; (*PARA [13183]: Kesselhausventilator active*) (*OldName:newPv; Cycle:5;*)
		bCHC_Heating_active : BOOL; (*PARA [13184]: Ladek�hler Vorw�rmung active*) (*OldName:newPv; Cycle:5;*)
		bT_ECW_bChC_HT_Active : BOOL; (*PARA [13395]: temperature engine cooling water before charge cooler high temp.circuit active M.06-TI-014*) (*OldName:newPv; Cycle:5;*)
		bT_ECW_bOilC_Active : BOOL; (*PARA [13396]: temperature engine cooling water before oil cooler active M.06-TI-020*) (*OldName:newPv; Cycle:5;*)
		bT_ECW_bECWC_Active : BOOL; (*PARA [13397]: temperature engine cooling water before engine cooling water cooler active M.06-TI-030*) (*OldName:newPv; Cycle:5;*)
		bBOP_HeatCirc_Act : BOOL; (*PARA [13832]: -Visu: Plant display heat circuit active*) (*OldName:newPv; Cycle:5;*)
		bBOP_EmCoolCirc_Act : BOOL; (*PARA [13833]: -Visu: Plant display emergency cooler circuit active*) (*OldName:newPv; Cycle:5;*)
		bBOP_ChCoolCirc_Act : BOOL; (*PARA [13834]: -Visu: Plant display charge cooling circuit active*) (*OldName:newPv; Cycle:5;*)
		rT_ECW_PwrRamp_LimLo : REAL; (*Para engine cooling water temperature limit low - power limitation for warm up operation [°C]*) (*OldName:newPV; Cycle:5;*)
		iChC2_NumDemAux : INT; (*PARA [14255]: number charge cooler 2 stages with demand auxiliaries*) (*OldName:newPV; Cycle:5;*)
		iChC2_NumStages : INT; (*PARA [14254]: charge cooler 2 number stages*) (*OldName:newPV; Cycle:5;*)
		iChC2_OpMode : INT; (*PARA [14253]: charge cooler 2 operating mode*) (*OldName:newPV; Cycle:5;*)
		iChC2_CtrNum : INT; (*PARA [14256]: charge cooler 2 controller number*) (*OldName:newPV; Cycle:5;*)
		rChC2_ValPosLimHi_On : REAL; (*PARA [14257]: position valve charge cooler 2 ON limit high [%]*) (*OldName:newPV; Cycle:5;*)
		rChC2_ValPosHyHi_On : REAL; (*PARA [14258]: position valve charge cooler 2 ON limit high hysteresis [%]*) (*OldName:newPV; Cycle:5;*)
		rChC2_ValPosLimStageUp : REAL; (*PARA [14259]: position charge cooler 2 valve limit stage up [%]*) (*OldName:newPV; Cycle:5;*)
		rChC2_ValPosLimStageDown : REAL; (*PARA [14260]: position charge cooler 2 valve limit stage down [%]*) (*OldName:newPV; Cycle:5;*)
		tiChC2_DelayOff : TIME; (*PARA [14261]: charge cooler 2 delay OFF*) (*OldName:newPV; Cycle:5;*)
		tiChC2_DelayStageUp : TIME; (*PARA [14262]: charge cooler 2 delay switch stage up *) (*OldName:newPV; Cycle:5;*)
		tiChC2_DelayStageDown : TIME; (*PARA [14263]: charge cooler 2 delay switch stage down*) (*OldName:newPV; Cycle:5;*)
		rT_Ch_T1HP_LimHi1 : REAL; (*PARA [14264]: charge temperature before high-pressure turbocharger high limit 1 [°C]*) (*OldName:newPV; Cycle:5;*)
		rT_Ch_T1HP_LimHi2 : REAL; (*PARA [14267]: charge temperature before high-pressure turbocharger high limit 2 [°C]*) (*OldName:newPV; Cycle:5;*)
		rT_Ch_T1HP_HyHi1 : REAL; (*PARA [14265]: charge temperature before high-pressure turbocharger high hysteresis limit 1 [°C]*) (*OldName:newPV; Cycle:5;*)
		rT_Ch_T1HP_HyHi2 : REAL; (*PARA [14266]: charge temperature before high-pressure turbocharger high hysteresis limit 2 [°C]*) (*OldName:newPV; Cycle:5;*)
		tCtr_ChC_T1HP : _tGeACtrPara; (*Para controller charge temperature before high-pressure turbo charger cooler*) (*OldName:newPV; Cycle:5;*)
		bCtr_ChC_T1HP : BOOL; (*PARA [14244]: visibility charge temperature before high-pressure turbo charger controller*) (*OldName:newPV; Cycle:5;*)
		bAuxChC2_Visible : BOOL; (*PARA [14251]: visibility parameters of charge cooler control*) (*OldName:newPv; Cycle:5;*)
		bChC2_StX_Visible : BOOL; (*PARA [14252]: charge cooler stage0-x visible*) (*OldName:bMixCoolRadStageX; Cycle:5;*)
		bPos_ChC2_Valve : BOOL; (*PARA [14268]: measuring active position control valve 2nd LT charge cooler circuit (T1-HP)*) (*OldName:newPv; Cycle:5;*)
		bT_ChC2_Su_LT_Active : BOOL; (*PARA [14271]: measuring supply water temperature 2nd LT charge cooler circuit (T1-HP) active (P.07-TI-004)*) (*OldName:newPv; Cycle:5;*)
		bT_ChC2_Re_LT_Active : BOOL; (*PARA [14272]: measuring return water temperature 2nd LT charge cooler circuit (T1-HP) active (P.07-TI-006)*) (*OldName:newPv; Cycle:5;*)
		rT_ChC2_Re_LT_LimHi : REAL; (*PARA [14273]: return water temperature 2nd LT charge cooler circuit (T1-HP) maximum*) (*OldName:newPv; Cycle:5;*)
		rT_ChC2_Re_LT_HyHi : REAL; (*PARA [14274]: return water temperature 2nd LT charge cooler circuit (T1-HP) hysteresis*) (*OldName:newPv; Cycle:5;*)
		bChC2_Heating_Active : BOOL; (*PARA [14276]: Ladek�hler 2 Vorw�rmung active*) (*OldName:newPv; Cycle:5;*)
		bEC_Pump_Visible : BOOL; (*PARA [14275]: emergency cooler pump visible*)
		bRedCCWP_Active : BOOL; (*PARA [14347]: Activate redundant pump control for charge cooler water pump *)
		bRedCC2WP_Active : BOOL; (*PARA [14346]: Activate redundant pump control for charge cooler 2 water pump *)
		bRedEmCWP_Active : BOOL; (*PARA [14348]: Activate redundant pump control for emergency cooler water pump *)
		rPr_ECW_LimLo_EngOp : REAL; (*PARA [15066]:Engine cooling water pressure minimum at engine operation*)
		bT_HW_Su_Unit_Active : BOOL; (*PARA [15126]: Heating water supply temperature unit measuring active*) (*SAFETY PLC: newPv; Cycle:5;*) (*V04.25.00.00*)
		rT_HW_Su_Unit_LimHi : REAL; (*PARA [15127]: Heating water supply temperature unit maximum*) (*SAFETY PLC: newPv; Cycle:5;*) (*V04.25.00.00*)
	END_STRUCT;
END_TYPE
