
TYPE
	IN_HC_Struct : 	STRUCT 
		tAB2HC : AmmBase2MM;
		tPB2MM : ParaBase2MM_type;
		tCtr_Cust1_Out : _tGeACtrOut; (*controller customized*) (*OldName:REG1; Cycle:5;*)
		tCtr_Cust2_Out : _tGeACtrOut; (*controller customized*) (*OldName:REG2; Cycle:5;*)
		tCtr_Cust3_Out : _tGeACtrOut; (*controller customized*) (*OldName:REG3; Cycle:5;*)
		tCtr_Cust4_Out : _tGeACtrOut; (*controller customized*) (*OldName:REG4; Cycle:5;*)
		tCtr_Cust5_Out : _tGeACtrOut; (*controller customized*) (*OldName:REG5; Cycle:5;*)
		tCtr_Cust6_Out : _tGeACtrOut; (*controller customized*) (*OldName:REG6; Cycle:5;*)
		tCtr_Cust7_Out : _tGeACtrOut; (*controller customized*) (*OldName:REG7; Cycle:5;*)
		tCtr_Cust8_Out : _tGeACtrOut; (*controller customized*) (*OldName:REG8; Cycle:5;*)
		tCtr_Cust1_In : _tGeACtrIn; (*controller customized*) (*OldName:F_SPSR1; Cycle:5;*)
		tCtr_Cust2_In : _tGeACtrIn; (*controller customized*) (*OldName:F_SPSR2; Cycle:5;*)
		tCtr_Cust3_In : _tGeACtrIn; (*controller customized*) (*OldName:F_SPSR3; Cycle:5;*)
		tCtr_Cust4_In : _tGeACtrIn; (*controller customized*) (*OldName:F_SPSR4; Cycle:5;*)
		tCtr_Cust5_In : _tGeACtrIn; (*controller customized*) (*OldName:F_SPSR5; Cycle:5;*)
		tCtr_Cust6_In : _tGeACtrIn; (*controller customized*) (*OldName:F_SPSR6; Cycle:5;*)
		tCtr_Cust7_In : _tGeACtrIn; (*controller customized*) (*OldName:F_SPSR7; Cycle:5;*)
		tCtr_Cust8_In : _tGeACtrIn; (*controller customized*) (*OldName:F_SPSR8; Cycle:5;*)
		rCust_SparePara : ARRAY[0..200]OF REAL; (*SPS_REZP1 to SPS_REZP200	*) (* OldName: SPS_REZP1, SPS_REZP2, SPS_REZP70; Cycle: 5; *)
		tCustAnaIn : ARRAY[0..120]OF HALioAi_Type; (*Replacement for RAN_KANAL...*) (*OldName: ANA_RAN	; Cycle: 5;*)
		tCustDigIn : ARRAY[0..200]OF HALioDi_Type; (*new, reserved for Project specific use*) (*OldName: new PV	; Cycle: 5;*)
		tT_ECW_Ext_Hi : HALioDi_Type; (*DI temperature engine cooling water high external*) (*OldName:KTMA; Cycle:5;*)
		tEC_Failure : HALioDi_Type; (*DI emergency cooler failure*) (*OldName:ST_K; Cycle:5;*)
		tChC_Failure : HALioDi_Type; (*DI charge cooler failure*) (*OldName:ST_GKV; Cycle:5;*)
		tPr_CCircuit_Lo : HALioDi_Type; (*DI water pressure cooler circuit low*) (*OldName:WDK; Cycle:5;*)
		tPr_HW_Lo : HALioDi_Type; (*DI heat water pressure low*) (*OldName:HWD; Cycle:5;*)
		tPr_ChC_Lo : HALioDi_Type; (*DI charge cooler water pressure low*) (*OldName:GKWD; Cycle:5;*)
		tGCB_On : HALioDi_Type; (*DI generator circuit breaker closed*) (*OldName:GCB_ON; Cycle:5;*)
		tT_AirOutdoor : HALioAi_Type; (*AI temperature air outdoor*) (*OldName:ANA_ULT; Cycle:5;*)
		tPr_ECW : HALioAi_Type; (*pressure engine cooling water M.04-PI-001*) (*OldName:ANA.KWD; Cycle:5;*)
		tPr_ECWaEng : HALioAi_Type; (*pressure engine cooling water after engine M.04-PI-058*) (*OldName:AI_p_ECWaEng; Cycle:5;*)
		tT_ECW : HALioAi_Type; (*temperature engine cooling water M.04-TI-001*) (*OldName:ANA.KWT; Cycle:5;*)
		tT_HW_ReBeEng : HALioAi_Type; (*temperature heat water return before engine M.06-TI-001*) (*OldName:ANA.RLT_M; Cycle:5;*)
		tT_HW_ReAfEC : HALioAi_Type; (*temperature heat water return after emergency cooler P.06-TI-015, M.04-TI-015*) (*OldName:ANA.RLT_NK; Cycle:5;*)
		tT_HW_Re : HALioAi_Type; (*temperature heat water return P.06-TI-012, M.04-TI-012*) (*OldName:ANA.RLTP; Cycle:5;*)
		tT_HW_Su : HALioAi_Type; (*temperature heat water supply P.06-TI-014, M.04-TI-014*) (*OldName:ANA.VLTP; Cycle:5;*)
		tT_Su_PriCirc : HALioAi_Type; (*AI supply water temperature primary circuit [°C]*) (*OldName: new PV	; Cycle: 5;*)
		tT_Re_PriCirc : HALioAi_Type; (*AI return water temperature primary circuit [°C]*) (*OldName: new PV	; Cycle: 5;*)
		tT_Su_SecCirc : HALioAi_Type; (*AI supply water temperature secondary circuit [°C]*) (*OldName: new PV	; Cycle: 5;*)
		tT_Re_SecCirc : HALioAi_Type; (*AI return water temperature secondary circuit [°C]*) (*OldName: new PV	; Cycle: 5;*)
		tP_Heat : HALioAi_Type; (*AI heating power engine heat water circuit [kW]*) (*OldName: new PV	; Cycle: 5;*)
		tP_Heat_Imp : HALioDi_Type; (*DI heating power engine heat water circuit pulse*) (*OldName: new PV	; Cycle: 5;*)
		rT_Ch_T2s_Avg : REAL; (*average charge temperature t2' [°C]*) (*OldName: newPV; Cycle: 5;*)
		tT_EO : HALioAi_Type; (*temperature engine oil M.03-TI-001*) (*OldName:ANA.OTP; Cycle:5;*)
		tECWP1Dem : HALioDo_Type; (*DO engine cooling water pump 1 demand*) (*OldName:A_MKWP1; Cycle:5;*)
		tPr_HW_Hi1 : HALioDi_Type; (*DI heat water pressure high*) (*OldName:HWDX1; Cycle:5;*)
		tPr_HW_Hi : HALioDi_Type; (*DI heat water pressure high*) (*OldName:HWDX; Cycle:5;*)
		tT_HW_Hi1 : HALioDi_Type; (*DI heat water temperature high P.06-TS-023*) (*OldName:HWTP1; Cycle:5;*)
		tT_HW_Hi : HALioDi_Type; (*DI heat water temperature high P.06-TS-001*) (*OldName:HWTP; Cycle:5;*)
		tFlow_HW_Lo : HALioDi_Type; (*DI heat water flow low*) (*OldName:HWDF; Cycle:5;*)
		tT_ChCW_Hi : HALioDi_Type; (*DI charge cooling water temperature high*) (*OldName:GKWT_2; Cycle:5;*)
		tT_HW_Su_LT : HALioAi_Type; (*temperature heat water supply low temp.circuit [°C] M.07-TI-048*) (*OldName:NT_supply_water_temp; Cycle:5;*)
		tT_ECW_AfEng : HALioAi_Type; (*temperature engine cooling water after engine [°C]*) (*OldName:MKW_press_after_engine; Cycle:5;*)
		tEng_Run : HALioDo_Type; (*engine is running*) (*OldName:M_BTRB; Cycle:5;*)
		tT_HW_Re_LT : HALioAi_Type; (*temperature heat water return low temp.circuit [°C] M.07-TI-001*) (*OldName:iT_HWR_LT; Cycle:5;*)
		tAuxV_ModIf_ok : HALioDi_Type; (*DI auxiliary voltage supply ok Module interface*) (*OldName:SPG_HBT; Cycle:5;*)
		tAuxV_Aux_ok : HALioDi_Type; (*DI auxiliary voltage supply ok Auxiliaries panel*) (*OldName:SPG_HBT; Cycle:5;*)
		tAuxV_Supply_Ok : HALioDi_Type; (*DI auxiliary voltage supply ok*) (*OldName:SPG_HBT; Cycle:5;*)
		tChC_FanRdy : HALioDi_Type; (*DI charge cooler fan ready*) (*OldName:RDY_ICF; Cycle:5;*)
		tPr_HW_Su_LT : HALioAi_Type; (*supply water pressure LT circuit M.07-PI-001*) (*OldName:AI_p_VL_NT; Cycle:5;*)
		tPr_HW_Su_HT : HALioAi_Type; (*supply water pressure HT circuit M.06-PI-001*) (*OldName:AI_p_VL_HT; Cycle:5;*)
		tT_ECWbEng : HALioAi_Type; (*engine cooling water temperature before engine measurement active M.04-TI-002*) (*OldName:newPv; Cycle:5;*)
		tPr_HW_Re_LT : HALioAi_Type; (*pressure heat water return low temp.circuit M.07-PI-002*) (*OldName:newPv; Cycle:5;*)
		tPr_HW_Re_HT : HALioAi_Type; (*pressure heat water return high temp.circuit M.06-PI-002*) (*OldName:newPv; Cycle:5;*)
		tPr_HW_Re_PreH_ECW : HALioAi_Type; (*pressure heat water return preheating engine cooling water M.04-PI-005*) (*OldName:newPv; Cycle:5;*)
		tPr_HW_Re_PreH_EO : HALioAi_Type; (*pressure heat water return preheating engine oil M.03-PI-005*) (*OldName:newPv; Cycle:5;*)
		tPr_EO_Mod_Out : HALioAi_Type; (*pressure engine oil module outlet M.03-PI-006*) (*OldName:newPv; Cycle:5;*)
		tT_ECW_Mod_In : HALioAi_Type; (*temperature engine cooling water, engine cooling water module inlet M.04-TI-003*) (*OldName:newPv; Cycle:5;*)
		tT_ECW_Mod_Out : HALioAi_Type; (*temperature engine cooling water, engine cooling water module outlet M.04-TI-004*) (*OldName:newPv; Cycle:5;*)
		tT_EO_Mod_In : HALioAi_Type; (*temperature engine oil, oil module inlet M.03-TI-004*) (*OldName:newPv; Cycle:5;*)
		tT_EO_Mod_Out : HALioAi_Type; (*temperature engine oil, oil module outlet M.03-TI-003*) (*OldName:newPv; Cycle:5;*)
		tT_HW_Su_PreH_ECW : HALioAi_Type; (*temperature heat water supply preheating engine cooling water M.04-TI-005*) (*OldName:newPv; Cycle:5;*)
		tT_HW_Re_PreH_ECW : HALioAi_Type; (*temperature heat water return preheating engine cooling water M.04-TI-006*) (*OldName:newPv; Cycle:5;*)
		tT_HW_Su_PreH_EO : HALioAi_Type; (*temperature heat water supply preheating engine oil M.03-TI-005*) (*OldName:newPv; Cycle:5;*)
		tT_HW_Re_PreH_EO : HALioAi_Type; (*temperature heat water return preheating engine oil M.03-TI-006*) (*OldName:newPv; Cycle:5;*)
		iSt_OpMode : UDINT; (*engine operating mode*) (*OldName:newPv; Cycle:5;*)
		rN_EngAct : REAL; (*engine speed actual [1/min]*) (*OldName:n_ist; Cycle:5;*)
		rT_ChC_Ctr_Wex : REAL; (*charge temperature controller external setpoint(knocking)*) (*OldName:Wex_GEMREG; Cycle:5;*)
		bEng_Dem_EPS : BOOL; (*engine demand for emergency power supply*) (*OldName:M_NANF; Cycle:5;*)
		bEng_Aux_Dem_CDR : BOOL; (*engine auxiliaries demand with cool down run*) (*OldName:ANFHBT; Cycle:5;*)
		bEng_Aux_Dem : BOOL; (*engine auxiliaries demand*) (*OldName:M_ANFHBT; Cycle:5;*)
		iIdx_OMSS : INT; (*engine operation mode selection*) (*OldName:newPv; Cycle:5;*)
		rP_Act_Norm_Filt : REAL; (*actual power related to rP_Nom filtered(1s) [%] *) (*OldName:P_IST; Cycle:5;*)
		bEC_Rel : BOOL; (*release emergency cooler from monitoring*) (*OldName:K_frg; Cycle:5;*)
		bChC_Rel : BOOL; (*release charge cooler from monitoring*) (*OldName:GK_frg; Cycle:5;*)
		tCDP_Dem : HALioDo_Type; (*demand condensor pump*) (*OldName:newPv; Cycle:5;*)
		tHWF_Fail : HALioDi_Type; (*failure heating circuit flap*) (*OldName:newPv; Cycle:5;*)
		tCDP_Op : HALioDi_Type; (*failure condensor pump*) (*OldName:newPv; Cycle:5;*)
		tT_HW_HC_Re : HALioAi_Type; (*heating circuit return temperature*) (*OldName:newPv; Cycle:5;*)
		tT_CD_Su : HALioAi_Type; (*supply temperature condensor circuit*) (*OldName:newPv; Cycle:5;*)
		tT_CD_Re : HALioAi_Type; (*return temperature condensor circuit*) (*OldName:newPv; Cycle:5;*)
		tPos_HW_ReValve : HALioAi_Type; (*position heating water return temperature regulation valve*) (*OldName:newPv; Cycle:5;*)
		tPos_HW_EC_ReValve : HALioAi_Type; (*position heating water return temperature after cooler regulation valve*) (*OldName:newPv; Cycle:5;*)
		tPos_ChC_Valve : HALioAi_Type; (*position charge temperature regulation valve*) (*OldName:newPv; Cycle:5;*)
		tBHV_Op : HALioDi_Type; (*failure boiler house ventilation*) (*OldName:newPv; Cycle:5;*)
		tDemnd_BHV : HALioDi_Type; (*demand boiler house ventilation*) (*OldName:newPv; Cycle:5;*)
		bMsg1031 : BOOL; (*emergency stop / safety loop*) (*OldName:M_SIS; Cycle:5;*)
		bMsg1053 : BOOL; (*gas alarm*) (*OldName:M_GAL; Cycle:5;*)
		bMsg1054 : BOOL; (*fire alarm*) (*OldName:M_BAL; Cycle:5;*)
		bMsg3003 : BOOL; (*signal failure( 2101 or 2102 or 2103 or 2104 or 3152 > 24h)*) (*OldName:M_MS; Cycle:5;*)
		tManAuxCtr : tManAuxCtr_typ; (*Manual operating auxiliaries control - Handbedienebene*) (*OldName: new PV; Cycle: 5;*)
		tT_ECW_bChC_HT : HALioAi_Type; (*temperature engine cooling water before charge cooler high temp.circ. M.06-TI-014*) (*OldName:newPv; Cycle:5;*)
		tT_ECW_bOilC : HALioAi_Type; (*temperature engine cooling water before oil cooler M.06-TI-020*) (*OldName:newPv; Cycle:5;*)
		tT_ECW_bECWC : HALioAi_Type; (*temperature engine cooling water before engine cooling water cooler M.06-TI-030*) (*OldName:newPv; Cycle:5;*)
		bAMM_T_Ch_T2s_Avg : BOOL; (*collective warning - average charge temp. t2'  *) (*OldName: new PV; Cycle:5;*) (*SWAT920/2*)
		bT_ChC_Ctr_Wex_Enable_Cust : BOOL; (*new V4.5*)
		rT_ChC_Ctr_Wex_Cust : REAL; (*new V4..5*)
		rCustomizedHC : ARRAY[0..99]OF REAL; (*New customizable interface 2017  - BETA PHASE, use only in coordination with TPSS*)
		bChC2_Rel : BOOL; (*release charge cooler 2 from monitoring*) (*OldName:newPV; Cycle:5;*)
		bAMM_T_Ch_T1HP_Avg : BOOL; (*collective warning - average charge temp. before high-pressure TC*) (*OldName: new PV; Cycle:5;*)
		rT_Ch_T1HP_Avg : REAL; (*average charge temperature before high-pressure turbo charger T1-HP [°C]*) (*OldName: newPV; Cycle: 5;*)
		tPos_ChC2_Valve : HALioAi_Type; (*AI Position temperature-regulation-valve 2nd LT charge cooler circuit (T1-HP)*) (*OldName:newPv; Cycle:5;*)
		tPr_ChC2_Lo : HALioDi_Type; (*DI charge cooler 2 water pressure low - DI = FALSE if pressure is low*) (*OldName:newPV; Cycle:5;*)
		tChC2_FanRdy : HALioDi_Type; (*DI charge cooler 2 fan ready*) (*OldName:newPV; Cycle:5;*)
		tChC2_Failure : HALioDi_Type; (*DI charge cooler 2 failure - DI = FALSE if failure active*) (*OldName:newPV; Cycle:5;*)
		tT_ChC2_Su_LT : HALioAi_Type; (*AI supply water temperature 2nd LT charge cooler circuit (T1-HP) [°C] (P.07-TI-004)*) (*OldName:newPV; Cycle:5;*)
		tT_ChC2_Re_LT : HALioAi_Type; (*AI return water temperature 2nd LT charge cooler circuit (T1-HP) [°C] (P.07-TI-006)*) (*OldName:newPV; Cycle:5;*)
		tT_ChC2W_Hi : HALioDi_Type; (*DI charge cooler 2 water temperature high - DI = FALSE if water temp. too high*) (*OldName:newPV; Cycle:5;*)
		tT_HW_EGHE_Hi : HALioDi_Type; (*DI Heating water temperature max. exhaust gas cooler*)
		tT_HW_EGCD_Hi : HALioDi_Type; (*DI Heating water temperature max. exhaust gas condenser*)
		tCust_HW_Ext_Trip : HALioDi_Type; (*DI External heating water circuit monitoring*)
		bECWP_MechDriven : BOOL;  (* CUSTOM for new Pr_ECW plausibility check: Mechanically driven ECWP on type3 or type2 *)
		tECWP_Op : HALioDi_Type; (* DI engine cooling water pump operating *)
		tT_HW_Su_Unit : HALioAi_Type; (*SAFETY PLC: Heating water supply temperature - Unit (M.06-TI-003)*) (*OldName: new PV; Cycle: 5;*) (*V04.25.00.00*)
	END_STRUCT; (*END_IN*)
	OUT_HC_Struct : 	STRUCT 
		tChC_Heating : HALioDo_Type; (*DO charge cooler pre heating*) (*OldName:FG_KT; Cycle:5;*)
		tHC2AB : MM2AmmBase;
		tHC2PB : MM2ParaBase_type;
		tExCo_Rel : HALioDo_Type; (*DO external cooler release*) (*OldName:FG_KT; Cycle:5;*)
		tChC_DemPump : HALioDo_Type; (*DO charge cooler demand pump*) (*OldName:GKP_EIN; Cycle:5;*)
		tChC_DemFan1 : HALioDo_Type; (*DO charge cooler demand fan 1*) (*OldName:GKV_1; Cycle:5;*)
		tChC_DemFan2 : HALioDo_Type; (*DO charge cooler demand fan 2*) (*OldName:GKV_2; Cycle:5;*)
		tChC_DemFan3 : HALioDo_Type; (*DO charge cooler demand fan 3*) (*OldName:GKV_3; Cycle:5;*)
		tChC_DemFan4 : HALioDo_Type; (*DO charge cooler demand fan 4*) (*OldName:GKV_4; Cycle:5;*)
		tChC_DemFan5 : HALioDo_Type; (*DO charge cooler demand fan 5*) (*OldName:GKV_5; Cycle:5;*)
		tChC_DemFan6 : HALioDo_Type; (*DO charge cooler demand fan 6*) (*OldName:GKV_6; Cycle:5;*)
		tChC_DemFan7 : HALioDo_Type; (*DO charge cooler demand fan 7*) (*OldName:GKV_7; Cycle:5;*)
		tChC_DemFan8 : HALioDo_Type; (*DO charge cooler demand fan 8*) (*OldName:GKV_8; Cycle:5;*)
		tChC_DemFan9 : HALioDo_Type; (*DO charge cooler demand fan 9*) (*OldName:GKV_9; Cycle:5;*)
		tChC_DemFan10 : HALioDo_Type; (*DO charge cooler demand fan 10*) (*OldName:GKV_10; Cycle:5;*)
		tChC_DemFan11 : HALioDo_Type; (*DO charge cooler demand fan 11*) (*OldName:GKV_11; Cycle:5;*)
		tChC_DemFan12 : HALioDo_Type; (*DO charge cooler demand fan 12*) (*OldName:GKV_12; Cycle:5;*)
		tChC_DemFan13 : HALioDo_Type; (*DO charge cooler demand fan 13*) (*OldName:GKV_13; Cycle:5;*)
		tChC_DemFan14 : HALioDo_Type; (*DO charge cooler demand fan 14*) (*OldName:GKV_14; Cycle:5;*)
		tChC_DemFan15 : HALioDo_Type; (*DO charge cooler demand fan 15*) (*OldName:GKV_15; Cycle:5;*)
		tChC_DemFan16 : HALioDo_Type; (*DO charge cooler demand fan 16*) (*OldName:GKV_16; Cycle:5;*)
		tEC_DemPump : HALioDo_Type; (*DO emergency cooler demand pump*) (*OldName:KP_EIN; Cycle:5;*)
		tEC_DemFan1 : HALioDo_Type; (*DO emergency cooler demand fan 1*) (*OldName:KV_1; Cycle:5;*)
		tEC_DemFan2 : HALioDo_Type; (*DO emergency cooler demand fan 2*) (*OldName:KV_2; Cycle:5;*)
		tEC_DemFan3 : HALioDo_Type; (*DO emergency cooler demand fan 3*) (*OldName:KV_3; Cycle:5;*)
		tEC_DemFan4 : HALioDo_Type; (*DO emergency cooler demand fan 4*) (*OldName:KV_4; Cycle:5;*)
		tEC_DemFan5 : HALioDo_Type; (*DO emergency cooler demand fan 5*) (*OldName:KV_5; Cycle:5;*)
		tEC_DemFan6 : HALioDo_Type; (*DO emergency cooler demand fan 6*) (*OldName:KV_6; Cycle:5;*)
		tEC_DemFan7 : HALioDo_Type; (*DO emergency cooler demand fan 7*) (*OldName:KV_7; Cycle:5;*)
		tEC_DemFan8 : HALioDo_Type; (*DO emergency cooler demand fan 8*) (*OldName:KV_8; Cycle:5;*)
		tEC_DemFan9 : HALioDo_Type; (*DO emergency cooler demand fan 9*) (*OldName:KV_9; Cycle:5;*)
		tEC_DemFan10 : HALioDo_Type; (*DO emergency cooler demand fan 10*) (*OldName:KV_10; Cycle:5;*)
		tEC_DemFan11 : HALioDo_Type; (*DO emergency cooler demand fan 11*) (*OldName:KV_11; Cycle:5;*)
		tEC_DemFan12 : HALioDo_Type; (*DO emergency cooler demand fan 12*) (*OldName:KV_12; Cycle:5;*)
		tEC_DemFan13 : HALioDo_Type; (*DO emergency cooler demand fan 13*) (*OldName:KV_13; Cycle:5;*)
		tEC_DemFan14 : HALioDo_Type; (*DO emergency cooler demand fan 14*) (*OldName:KV_14; Cycle:5;*)
		tEC_DemFan15 : HALioDo_Type; (*DO emergency cooler demand fan 15*) (*OldName:KV_15; Cycle:5;*)
		tEC_DemFan16 : HALioDo_Type; (*DO emergency cooler demand fan 16*) (*OldName:KV_16; Cycle:5;*)
		tECW_DemBpP : HALioDo_Type; (*DO demand engine cooling water bypass pump (AMOT)*) (*OldName:BP_P; Cycle:5;*)
		tECW_DemBpV : HALioDo_Type; (*DO demand engine cooling water bypass valve (AMOT)*) (*OldName:BP_V; Cycle:5;*)
		tCtr_ChC_Set : HALioAo_Type; (*AO charge temperature cooler control valve*) (*OldName:Reg9_y; Cycle:5;*)
		tCtr_HWRe_Set : HALioAo_Type; (*AO heat water return temperature control valve*) (*OldName:Reg10_y; Cycle:5;*)
		tCtr_EC_Set : HALioAo_Type; (*AO heat water return temperature control valve emergency cooler*) (*OldName:Reg11_y; Cycle:5;*)
		tCtr_HWSu_Set : HALioAo_Type; (*AO heat water supply temperature control valve*) (*OldName:Reg14_y; Cycle:5;*)
		tCtr_ChCV_Set : HALioAo_Type; (*AO charge temperature cooler ventilation*) (*OldName:Reg15_y, GKV_y; Cycle:5;*)
		tCtr_ChCHP_Set : HALioAo_Type; (*AO charge temperature cooler high pressure control valve*) (*OldName:Reg18_y; Cycle:5;*)
		bT_ECW_Hi : BOOL; (*temperature engine cooling water limit high*) (*OldName:AN_KTMA; Cycle:5;*)
		bT_ECW_Lo : BOOL; (*temperature engine cooling water limit low*) (*OldName:AN_KTMI; Cycle:5;*)
		bT_ECW_RelLoad : BOOL; (*temperature engine cooling water release load*) (*OldName:AN_LFG; Cycle:5;*)
		bT_ECW_PreH_OFF : BOOL; (*temperature engine cooling water preheating off*) (*OldName:AN_VORW; Cycle:5;*)
		rP_Red_T_HWR_Norm : REAL; (*power reduction heat water return temperature high [% Pnom]*) (*OldName:RED_RLT; Cycle:5;*)
		rP_Red_T_ECW_Norm : REAL; (*power reduction engine cooling water temperature high [% Pnom]*) (*OldName:RED_KWT; Cycle:5;*)
		bPr_ECW_Lo1 : BOOL; (*pressure engine cooling water limit low 1*) (*OldName:AN_KDGW1; Cycle:5;*)
		tHWF_Dem : HALioDo_Type; (*demand heating circuit flap*) (*OldName:newPv; Cycle:5;*)
		tCtr_CDSu_Set : HALioAo_Type; (*setpoint frequency conferter condensor pump*) (*OldName:newPv; Cycle:5;*)
		tBHV_Dem : HALioDo_Type; (*demand boiler house ventilation*) (*OldName:newPv; Cycle:5;*)
		iCnt_P_Heat : DINT; (*counter heating power engine heat water circuit*) (*OldName:newPv; Cycle:5;*)
		bMsg1019 : BOOL; (*engine cooling water pressure low*) (*OldName:M_KDMI; Cycle:5;*)
		bMsg2104 : BOOL; (*signal failure engine cooling water pressure *) (*OldName:M_MSKWD; Cycle:5;*)
		bMsg2101 : BOOL; (*signal failure engine cooling water temperature*) (*OldName:M_MSKWT; Cycle:5;*)
		bMsg3404 : BOOL; (*water pressure cooler circuit low*) (*OldName:M_NKWD_W; Cycle:5;*)
		bMsg1130 : BOOL; (*charge cooler water pressure low*) (*OldName:AMM_A11xx[]; Cycle:5;*)
		bMsg2117 : BOOL; (*charge cooler water pressure low*) (*OldName:M_GKWD; Cycle:5;*)
		rP_Red_T_ECW_Low_Norm : REAL; (*power reduction engine cooling water temperature low [% Pnom]*) (*OldName:newPv; Cycle:5;*)
		rCustomizedHC : ARRAY[0..99]OF REAL; (*New customizable interface 2017  - BETA PHASE, use only in coordination with TPSS*)
		tChC2_DemPump : HALioDo_Type; (*DO charge cooler 2 demand pump*) (*OldName:newPV; Cycle:5;*)
		tCtr_ChC2_Valve_Set : HALioAo_Type; (*AO Control temperature-regulation-valve 2nd LT charge cooler circuit (T1-HP)*) (*OldName:newPV; Cycle:5;*)
		tChC2_DemFan1 : HALioDo_Type; (*DO charge cooler 2 demand fan 1*) (*OldName:newPV; Cycle:5;*)
		tChC2_DemFan2 : HALioDo_Type; (*DO charge cooler 2 demand fan 2*) (*OldName:newPV; Cycle:5;*)
		tChC2_DemFan3 : HALioDo_Type; (*DO charge cooler 2 demand fan 3*) (*OldName:newPV; Cycle:5;*)
		tChC2_DemFan4 : HALioDo_Type; (*DO charge cooler 2 demand fan 4*) (*OldName:newPV; Cycle:5;*)
		tChC2_DemFan5 : HALioDo_Type; (*DO charge cooler 2 demand fan 5*) (*OldName:newPV; Cycle:5;*)
		tChC2_DemFan6 : HALioDo_Type; (*DO charge cooler 2 demand fan 6*) (*OldName:newPV; Cycle:5;*)
		tChC2_DemFan7 : HALioDo_Type; (*DO charge cooler 2 demand fan 7*) (*OldName:newPV; Cycle:5;*)
		tChC2_DemFan8 : HALioDo_Type; (*DO charge cooler 2 demand fan 8*) (*OldName:newPV; Cycle:5;*)
		tChC2_DemFan9 : HALioDo_Type; (*DO charge cooler 2 demand fan 9*) (*OldName:newPV; Cycle:5;*)
		tChC2_DemFan10 : HALioDo_Type; (*DO charge cooler 2 demand fan 10*) (*OldName:newPV; Cycle:5;*)
		tChC2_DemFan11 : HALioDo_Type; (*DO charge cooler 2 demand fan 11*) (*OldName:newPV; Cycle:5;*)
		tChC2_DemFan12 : HALioDo_Type; (*DO charge cooler 2 demand fan 12*) (*OldName:newPV; Cycle:5;*)
		tChC2_DemFan13 : HALioDo_Type; (*DO charge cooler 2 demand fan 13*) (*OldName:newPV; Cycle:5;*)
		tChC2_DemFan14 : HALioDo_Type; (*DO charge cooler 2 demand fan 14*) (*OldName:newPV; Cycle:5;*)
		tChC2_DemFan15 : HALioDo_Type; (*DO charge cooler 2 demand fan 15*) (*OldName:newPV; Cycle:5;*)
		tChC2_DemFan16 : HALioDo_Type; (*DO charge cooler 2 demand fan 16*) (*OldName:newPV; Cycle:5;*)
		bMsg9226 : BOOL; (*charge cooler 2 water pressure low*) (*OldName:newPV; Cycle:5;*)
		tChC2_Heating : HALioDo_Type; (*DO Demand charge cooler 2 pre heating*) (*OldName:newPV; Cycle:5;*)
		bMsg2684 : BOOL; (*Temperature heat water supply hydraulic engine cooling water preheating signal failure*) (*OldName:newPV; Cycle:5;*)
		bCCWP_Dem : BOOL; (*Charge cooler water pump demand*) (*OldName:newPV; Cycle:5;*)
		bCC2WP_Dem : BOOL; (*Charge cooler 2 water pump demand*) (*OldName:newPV; Cycle:5;*)
		bEmCWP_Dem : BOOL; (*Emergency cooler water pump demand*) (*OldName:newPV; Cycle:5;*)
		bMsg1050 : BOOL; (*engine cooling water pressure high*) (*OldName:newPV; Cycle:5;*)
		tECW_ShutOffVal_Dem : HALioDo_Type; (*demand 2-way shut off valve engine jacket water circuit*)
		tValHeater_Dem : HALioDo_Type; (*demand 3-way valve heater*)
		tFanRingHeater_Dem : HALioDo_Type; (*demand fan ring heater*)
	END_STRUCT; (*END_OUT*)
	VIS2MM_Struct : 	STRUCT 
		tCtr_CDSu_In : _tGeACtrIn; (*condensor circuit supply temperature controller*) (*OldName:newPv; Cycle:5;*)
		tCtr_ChC_In : _tGeACtrIn; (*charge temperature controller*) (*OldName:REG9; Cycle:5;*)
		tCtr_HWRe_In : _tGeACtrIn; (*heat water return temperature controller*) (*OldName:REG10; Cycle:5;*)
		tCtr_EC_In : _tGeACtrIn; (*emergency cooler controller*) (*OldName:REG11; Cycle:5;*)
		tCtr_HWSu_In : _tGeACtrIn; (*heat water supply temperature controller*) (*OldName:REG14; Cycle:5;*)
		tCtr_ChCV_In : _tGeACtrIn; (*charge cooler ventilation controller*) (*OldName:REG15; Cycle:5;*)
		tCtr_ChCHP_In : _tGeACtrIn; (*charge temperature high pressure controller*) (*OldName:REG18; Cycle:5;*)
		tCtr_ChC_T1HP_In : _tGeACtrIn; (*charge temperature before high-pressure turbo charger controller*) (*OldName:newPV; Cycle:5;*)
	END_STRUCT; (*END_VIS2MM*)
	MM2VIS_Struct : 	STRUCT 
		tCtr_CDSu_Out : _tGeACtrOut; (*condensor circuit supply temperature controller*) (*OldName:newPv; Cycle:5;*)
		tCtr_ChC_Out : _tGeACtrOut; (*charge temperature controller*) (*OldName:REG9; Cycle:5;*)
		tCtr_HWRe_Out : _tGeACtrOut; (*heat water return temperature controller*) (*OldName:REG10; Cycle:5;*)
		tCtr_EC_Out : _tGeACtrOut; (*emergency cooler controller*) (*OldName:REG11; Cycle:5;*)
		tCtr_HWSu_Out : _tGeACtrOut; (*heat water supply temperature controller*) (*OldName:REG14; Cycle:5;*)
		tCtr_ChCV_Out : _tGeACtrOut; (*charge cooler ventilation controller*) (*OldName:REG15; Cycle:5;*)
		tCtr_ChCHP_Out : _tGeACtrOut; (*charge temperature high pressure controller*) (*OldName:REG18; Cycle:5;*)
		rT_AirOutdoor : REAL; (*temperature air outdoor *) (*OldName:ANA_ULT; Cycle:5;*)
		bECW_DemBpP : BOOL; (*demand engine cooling water bypass pump*) (*OldName:BP_P; Cycle:5;*)
		bEC_Stage1 : BOOL; (*emergency cooler stage 1*) (*OldName:B_SV[38]; Cycle:5;*)
		bEC_Stage2 : BOOL; (*emergency cooler stage 2*) (*OldName:B_SV[39]; Cycle:5;*)
		bEC_Dem : BOOL; (*emergency cooler demanded*) (*OldName:newPv; Cycle:5;*)
		iSumChC_Stages : INT; (*summary charge cooler stages*) (*OldName:AnzGkuehlSt; Cycle:5;*)
		iSumEC_Stages : INT; (*summary emergency cooler stages*) (*OldName:AnzKuehlSt; Cycle:5;*)
		iCnt_P_Heat : DINT; (*counter heating power engine heat water circuit*) (*OldName:newPv; Cycle:5;*)
		rT_HW_ReBeEng : REAL; (*temperature heat water return before engine [°C]*) (*OldName:ANA.RLT_M; Cycle:5;*)
		rT_HW_ReAfEC : REAL; (*temperature heat water return after emergency cooler [°C]*) (*OldName:ANA.RLT_NK; Cycle:5;*)
		rT_HW_Re : REAL; (*temperature heat water return [°C]*) (*OldName:ANA.RLTP; Cycle:5;*)
		rT_HW_Su : REAL; (*temperature heat water supply [°C]*) (*OldName:ANA.VLTP; Cycle:5;*)
		rPr_HW_Su_HT : REAL; (*pressure heat water supply high temp.circuit [bar]*) (*OldName:AI_p_VL_HT; Cycle:5;*)
		rPr_ECW : REAL; (*pressure engine cooling water [°C]*) (*OldName:ANA.KWD; Cycle:5;*)
		rPr_ECWaEng : REAL; (*pressure engine cooling water after engine [°C]*) (*OldName:MKWPress_a_e; Cycle:5;*)
		rT_ECW : REAL; (*temperature engine cooling water [°C]*) (*OldName:ANA.KWT; Cycle:5;*)
		rP_Red_T_HWR_Norm : REAL; (*power reduction heat water return temperature high [% Pnom]*) (*OldName:ssPowerRedRLT; Cycle:5;*)
		rP_Red_T_ECW_Norm : REAL; (*power reduction engine cooling water temperature high [% Pnom]*) (*OldName:ssPowerRedKWT; Cycle:5;*)
		rT_HW_Su_LT : REAL; (*temperature heat water supply low temp.circuit [°C]*) (*OldName:NTemp_supply; Cycle:5;*)
		rPr_HW_Su_LT : REAL; (*pressure heat water supply low temp.circuit [bar]*) (*OldName:AI_p_VL_NT; Cycle:5;*)
		rT_ECW_AfEng : REAL; (*temperature engine cooling water after engine [°C]*) (*OldName:MKW_press_after_engine; Cycle:5;*)
		rT_HW_Re_LT : REAL; (*temperature heat water return low temp.circuit [°C]*) (*OldName:iT_HWR_LT; Cycle:5;*)
		rT_ECWbEng : REAL; (*engine cooling water temperature before engine M.04-TI-002*) (*OldName:newPv; Cycle:5;*)
		rPr_HW_Re_LT : REAL; (*pressure heat water return low temp.circuit M.07-PI-002*) (*OldName:newPv; Cycle:5;*)
		rPr_HW_Re_HT : REAL; (*pressure heat water return high temp.circuit M.06-PI-002*) (*OldName:newPv; Cycle:5;*)
		rPr_HW_Re_PreH_ECW : REAL; (*pressure heat water return preheating engine cooling water M.04-PI-005*) (*OldName:newPv; Cycle:5;*)
		rPr_HW_Re_PreH_EO : REAL; (*pressure heat water return preheating engine oil M.03-PI-005*) (*OldName:newPv; Cycle:5;*)
		rPr_EO_Mod_Out : REAL; (*pressure engine oil module outlet M.03-PI-006*) (*OldName:newPv; Cycle:5;*)
		rT_ECW_Mod_In : REAL; (*temperature  engine cooling water, engine cooling water module inlet M.04-TI-003*) (*OldName:newPv; Cycle:5;*)
		rT_ECW_Mod_Out : REAL; (*temperature  engine cooling water, engine cooling water module outlet M.04-TI-004*) (*OldName:newPv; Cycle:5;*)
		rT_EO_Mod_In : REAL; (*temperature engine oil, oil module inlet M.03-TI-004*) (*OldName:newPv; Cycle:5;*)
		rT_EO_Mod_Out : REAL; (*temperature engine oil, oil module outlet M.03-TI-003*) (*OldName:newPv; Cycle:5;*)
		rT_HW_Su_PreH_ECW : REAL; (*temperature heat water supply preheating engine cooling water M.04-TI-005*) (*OldName:newPv; Cycle:5;*)
		rT_HW_Re_PreH_ECW : REAL; (*temperature heat water return preheating engine cooling water M.04-TI-006*) (*OldName:newPv; Cycle:5;*)
		rT_HW_Su_PreH_EO : REAL; (*temperature heat water supply preheating engine oil M.03-TI-005*) (*OldName:newPv; Cycle:5;*)
		rT_HW_Re_PreH_EO : REAL; (*temperature heat water return preheating engine oil M.03-TI-006*) (*OldName:newPv; Cycle:5;*)
		rPos_HW_ReValve : REAL; (*position heating water return temperature regulation valve*) (*OldName:newPv; Cycle:5;*)
		rPos_HW_EC_ReValve : REAL; (*position heating water return temperature after cooler regulation valve*) (*OldName:newPv; Cycle:5;*)
		rPos_ChC_Valve : REAL; (*position charge temperature regulation valve*) (*OldName:newPv; Cycle:5;*)
		rT_Su_PriCirc : REAL; (*supply water temperature high primary circuit*) (*OldName:newPv; Cycle:5;*)
		rT_Re_PriCirc : REAL; (*return water temperature high primary circuit*) (*OldName:newPv; Cycle:5;*)
		rT_Su_SecCirc : REAL; (*supply water temperature high secondary circuit*) (*OldName:newPv; Cycle:5;*)
		rT_Re_SecCirc : REAL; (*return water temperature high secondary circuit*) (*OldName:newPv; Cycle:5;*)
		rP_Heat : REAL; (*heating power engine heat water circuit*) (*OldName:newPv; Cycle:5;*)
		bHWF_Dem : BOOL; (*demand heat circuit flap*) (*OldName:newPv; Cycle:5;*)
		rT_HW_HC_Re : REAL; (*heating circuit return temperature*) (*OldName:newPv; Cycle:5;*)
		bCDP_Dem : BOOL; (*demand condensor pump*) (*OldName:newPv; Cycle:5;*)
		bBHV_Dem : BOOL; (*demand boiler house ventilator*) (*OldName:newPv; Cycle:5;*)
		rT_CD_Re : REAL; (*return temperature condensor circuit [°C]*) (*OldName:newPv; Cycle:5;*)
		rT_CD_Su : REAL; (*supply temperature condensor circuit [°C]*) (*OldName:newPv; Cycle:5;*)
		bMsg1019 : BOOL; (*engine cooling water pressure low*) (*OldName:M_KDMI; Cycle:5;*)
		bMsg1021 : BOOL; (*engine cooling water temperature high*) (*OldName:M_KTMA; Cycle:5;*)
		bMsg1032 : BOOL; (*heat water  flow low*) (*OldName:M_HWDF; Cycle:5;*)
		bMsg1033 : BOOL; (*heat water  temperature high*) (*OldName:M_HWTP; Cycle:5;*)
		bMsg1034 : BOOL; (*heat water  pressure low*) (*OldName:M_HWD; Cycle:5;*)
		bMsg1035 : BOOL; (*heat water  pressure high*) (*OldName:M_HWDX; Cycle:5;*)
		bMsg1050 : BOOL; (*engine cooling water pressure high*) (*OldName:M_KDMA; Cycle:5;*)
		bMsg1063 : BOOL; (*heat water supply temperature high*) (*OldName:AMM_A10xx[]; Cycle:5;*)
		bMsg1070 : BOOL; (*signal failure heat water return temperature*) (*OldName:AMM_A10xx[]; Cycle:5;*)
		bMsg1071 : BOOL; (*signal failure heat water supply temperature*) (*OldName:AMM_A10xx[]; Cycle:5;*)
		bMsg1130 : BOOL; (*charge cooler water pressure low*) (*OldName:AMM_A11xx[]; Cycle:5;*)
		bMsg1145 : BOOL; (*engine cooling water temperature low*) (*OldName:AMM_W11xx[]; Cycle:5;*)
		bMsg1167 : BOOL; (*heat water return temperature high*) (*OldName:AMM_W11xx[]; Cycle:5;*)
		bMsg1186 : BOOL; (*signal failure heat water return temperature*) (*OldName:AMM_W11xx[]; Cycle:5;*)
		bMsg1187 : BOOL; (*signal failure heat water supply temperature*) (*OldName:AMM_W11xx[]; Cycle:5;*)
		bMsg2101 : BOOL; (*signal failure engine cooling water temperature*) (*OldName:AMM_W21xx[]; Cycle:5;*)
		bMsg2104 : BOOL; (*signal failure engine cooling water pressure*) (*OldName:AMM_W21xx[]; Cycle:5;*)
		bMsg2116 : BOOL; (*emergency cooler failure*) (*OldName:AMM_W21xx[]; Cycle:5;*)
		bMsg2117 : BOOL; (*charge cooler water pressure low*) (*OldName:M_GKWD; Cycle:5;*)
		bMsg2119 : BOOL; (*charge cooler failure*) (*OldName:AMM_W21xx[]; Cycle:5;*)
		bMsg2341 : BOOL; (*Heating water temperature maximum - exhaust gas cooler*) (*OldName:newPv; Cycle:5;*)
		bMsg2342 : BOOL; (*Heating water temperature maximum - exhaust gas condenser*) (*OldName:newPv; Cycle:5;*)
		bMsg2343 : BOOL; (*External heating water circuit monitoring tripped*) (*OldName:newPv; Cycle:5;*)
		bMsg2428 : BOOL; (*heat water  flow low*) (*SWAT920/1*)
		bMsg2429 : BOOL; (*heat water  temperature high*) (*SWAT920/1*)
		bMsg2430 : BOOL; (*heat water supply temperature high*) (*SWAT920/1*)
		bMsg2638 : BOOL; (*supply water pressure LT circuit signal failure*) (*OldName:AMM_W26xx[]; Cycle:5;*)
		bMsg2639 : BOOL; (*supply water pressure HT circuit signal failure*) (*OldName:AMM_W26xx[]; Cycle:5;*)
		bMsg2640 : BOOL; (*return water temperature LT circuit signal failure*) (*OldName:AMM_W26xx[]; Cycle:5;*)
		bMsg2641 : BOOL; (*supply water temperature LT circuit signal failure*) (*OldName:AMM_W26xx[]; Cycle:5;*)
		bMsg2647 : BOOL; (*engine  cooling water pressure after engine signal failure*) (*OldName:AMM_W26xx; Cycle:5*)
		bMsg2667 : BOOL; (*engine cooling water temperature before engine signal failure*) (*OldName:AMM_W26xx; Cycle:5*)
		bMsg2675 : BOOL; (*pressure heat water return low temperature circuit signal failure*)
		bMsg2676 : BOOL; (*pressure heat water return high temperature circuit signal failure*)
		bMsg2677 : BOOL; (*pressure heat water return hydraulic engine cooling water preheating signal failure*)
		bMsg2678 : BOOL; (*pressure heat water return hydraulic oil preheating signal failure*)
		bMsg2679 : BOOL; (*pressure oil module oil outlet signal failure*)
		bMsg2680 : BOOL; (*temperature engine cooling water module inlet  signal failure*)
		bMsg2681 : BOOL; (*temperature engine cooling water module outlet  signal failure*)
		bMsg2682 : BOOL; (*temperature oil module oil inlet signal failure*)
		bMsg2683 : BOOL; (*temperature oil module oil outlet  signal failure*)
		bMsg2684 : BOOL; (*temperature heat water supply hydraulic engine cooling water preheating signal failure*)
		bMsg2685 : BOOL; (*temperature heat water return hydraulic engine cooling water preheating signal failure*)
		bMsg2686 : BOOL; (*temperature heat water supply hydraulic oil preheating signal failure*)
		bMsg2687 : BOOL; (*temperature heat water return hydraulic oil preheating signal failure*)
		bMsg2710 : BOOL; (*measuring signal failure position control valve heat water return temperature*) (*OldName:newPv; Cycle:5;*)
		bMsg2711 : BOOL; (*measuring signal failure position control valve heat water return temperature after cooler*) (*OldName:newPv; Cycle:5;*)
		bMsg2712 : BOOL; (*measuring signal failure position control valve charge cooler circuit temperature*) (*OldName:newPv; Cycle:5;*)
		bMsg2713 : BOOL; (*measuring signal failure supply water temperature primary circuit*) (*OldName:newPv; Cycle:5;*)
		bMsg2714 : BOOL; (*measuring signal failure return water temperature primary circuit*) (*OldName:newPv; Cycle:5;*)
		bMsg2715 : BOOL; (*measuring signal failure supply water temperature secondary circuit*) (*OldName:newPv; Cycle:5;*)
		bMsg2716 : BOOL; (*measuring signal failure return water temperature secondary circuit*) (*OldName:newPv; Cycle:5;*)
		bMsg2717 : BOOL; (*supply water temperature high primary circuit*) (*OldName:newPv; Cycle:5;*)
		bMsg2718 : BOOL; (*return water temperature high primary circuit*) (*OldName:newPv; Cycle:5;*)
		bMsg2719 : BOOL; (*supply water temperature high secondary circuit*) (*OldName:newPv; Cycle:5;*)
		bMsg2720 : BOOL; (*return water temperature high secondary circuit*) (*OldName:newPv; Cycle:5;*)
		bMsg2721 : BOOL; (*measuring signal failure heating power engine heat water circuit*) (*OldName:newPv; Cycle:5;*)
		bMsg2731 : BOOL; (*measuring signal failure supply temperature condensor circuit*) (*OldName:newPv; Cycle:5;*)
		bMsg2732 : BOOL; (*supply temperature condensor circuit maximum*) (*OldName:newPv; Cycle:5;*)
		bMsg2733 : BOOL; (*measuring signal failure return temperature condensor circuit*) (*OldName:newPv; Cycle:5;*)
		bMsg2734 : BOOL; (*return temperature condensor circuit maximum*) (*OldName:newPv; Cycle:5;*)
		bMsg2735 : BOOL; (*failure condensor pump*) (*OldName:newPv; Cycle:5;*)
		bMsg2736 : BOOL; (*Failure boiler house ventilation*) (*OldName:newPv; Cycle:5;*)
		bMsg2750 : BOOL; (*failure heat circuit flap*) (*OldName:newPv; Cycle:5;*)
		bMsg2751 : BOOL; (*heat circuit return temperature high*) (*OldName:newPv; Cycle:5;*)
		bMsg2752 : BOOL; (*signal failure heat circuit return temperature high*) (*OldName:newPv; Cycle:5;*)
		bMsg2763 : BOOL; (*plausibility check measuring signal engine cooling water pressure*)
		bMsg3220 : BOOL; (*engine cooling water temperature high*) (*OldName:AMM_W32xx[]; Cycle:5;*)
		bMsg3303 : BOOL; (*signal failure heat water return temp. after EC trip*) (*OldName:AMM_A33xx[]; Cycle:5;*)
		bMsg3312 : BOOL; (*signal failure heat water return temp. after EC trip*) (*OldName:AMM_A33xx[]; Cycle:5;*)
		bMsg3321 : BOOL; (*signal failure heat  water return temperature trip*) (*OldName:AMM_A33xx[]; Cycle:5;*)
		bMsg3402 : BOOL; (*engine cooling water pressure low*) (*OldName:AMM_W34xx[]; Cycle:5;*)
		bMsg3404 : BOOL; (*water pressure cooler circuit low*)
		bMsg3406 : BOOL; (*engine cooling water pressure high*)
		bMsg3407 : BOOL; (*signal failure outdoor temperature*)
		bMsg3492 : BOOL; (*temperature engine cooling water before charge cooler high temp.circuit active M.06-TI-014*)
		bMsg3493 : BOOL; (*temperature engine cooling water before oil cooler active M.06-TI-020*)
		bMsg3494 : BOOL; (*temperature engine cooling water before engine cooling water cooler active M.06-TI-030*)
		bMsg3508 : BOOL; (*signal failure heat water return temp. after EC*)
		bMsg3509 : BOOL; (*heat water return temperature after EC high*)
		bMsg3521 : BOOL; (*charge cooling water temperature high*)
		bMsg3526 : BOOL; (*signal failure heat  water return temperature before engine*)
		bMsg3527 : BOOL; (*heat water return temperature before engine high*)
		bMsg3590 : BOOL; (*signal failure temp. heat water return low temperatur*)
		bMsg9098 : BOOL; (*Valve heating in operation*)
		bMsg9099 : BOOL; (*Ring heater for cooling fan in operation*)
		bMsg9226 : BOOL; (*charge cooler 2 water pressure low*) (*OldName:newPV; Cycle:5;*)
		bMsg9228 : BOOL; (*charge cooler 2 failure*) (*OldName:newPV; Cycle:5;*)
		bMsg9229 : BOOL; (*Charge cooler 2 water temperature high*) (*OldName:newPV; Cycle:5;*)
		bMsg9230 : BOOL; (*Measuring signal failure position temperature-control-valve charge cooler 2 circuit*) (*OldName:newPV; Cycle:5;*)
		bMsg9231 : BOOL; (*Measuring signal failure supply water temperature charge cooler 2 circuit*) (*OldName:newPV; Cycle:5;*)
		bMsg9232 : BOOL; (*Measuring signal failure return water temperature charge cooler 2 circuit*) (*OldName:newPV; Cycle:5;*)
		bChC_DemPump : BOOL; (*charge cooler demand pump*) (*OldName:GKP_EIN; Cycle:5;*)
		bEC_DemPump : BOOL; (*emergency cooler demand pump*) (*OldName:KP_EIN; Cycle:5;*)
		bChC_Heating_Dem : BOOL; (*Charge cooler pre heating*) (*OldName:FG_KT; Cycle:5;*)
		rT_ECW_bChC_HT : REAL; (*temperature engine cooling water before charge cooler high temp.circ. M.06-TI-014*) (*OldName:newPv; Cycle:5;*)
		rT_ECW_bOilC : REAL; (*temperature engine cooling water before oil cooler M.06-TI-020*) (*OldName:newPv; Cycle:5;*)
		rT_ECW_bECWC : REAL; (*temperature engine cooling water before engine cooling water cooler M.06-TI-030*) (*OldName:newPv; Cycle:5;*)
		bEC_On : BOOL; (*emergency cooler on*) (*OldName:newPv; Cycle:5;*)
		bChC_On : BOOL; (*charge cooler on*) (*OldName:newPv; Cycle:5;*)
		bChC2_DemPump : BOOL; (*charge cooler 2 demand pump*) (*OldName:newPV; Cycle:5;*)
		tCtr_ChC_T1HP_Out : _tGeACtrOut; (*charge temperature before high-pressure turbo charger controller*) (*OldName:newPV; Cycle:5;*)
		rPos_ChC2_Valve : REAL; (*Position temperature-regulation-valve 2nd LT charge cooler circuit (T1-HP)*) (*OldName:newPv; Cycle:5;*)
		iSumChC2_Stages : INT; (*summary charge cooler 2 stages*) (*OldName:newPV; Cycle:5;*)
		bChC2_On : BOOL; (*charge cooler 2 on*) (*OldName:newPv; Cycle:5;*)
		bChC2_Heating_Dem : BOOL; (*Charge cooler 2 pre heating*) (*OldName:newPV; Cycle:5;*)
		rT_ChC2_Su_LT : REAL; (*supply water temperature charge cooler 2 [°C]*) (*OldName:newPV; Cycle:5;*)
		rT_ChC2_Re_LT : REAL; (*return water temperature charge cooler 2 [°C]*) (*OldName:newPV; Cycle:5;*)
		bECW_ShutOffVal_Dem : BOOL; (*demand 2-way shut off valve engine jacket water circuit*)
		bECW_ShutOffVal_Dem_Exist : BOOL; (*demand 2-way shut off valve engine jacket water circuit exist*)
		bValHeater_Dem : BOOL; (*demand 3-way valve heater*)
		bValHeater_Dem_Exist : BOOL; (*demand 3-way valve heater exist*)
		bFanRingHeater_Dem : BOOL; (*demand fan ring heater*)
		bFanRingHeater_Dem_Exist : BOOL; (*demand fan ring heater exist*)
		rT_HW_Su_Unit : REAL; (*SAFETY PLC: Heating water supply temperature - Unit (M.06-TI-003)*) (*OldName: new PV; Cycle: 5;*) (*V04.25.00.00*)
		bMsg9588 : BOOL; (*SAFETY PLC: Heating water supply temperature unit maximum*) (*OldName: new PV; Cycle: 5;*) (*V04.25.00.00*)
		bMsg9589 : BOOL; (*SAFETY PLC: Heating water supply temperature unit measuring signal failure*) (*OldName: new PV; Cycle: 5;*) (*V04.25.00.00*)
	END_STRUCT; (*END_MM2VIS*)
	tManAuxCtr_typ : 	STRUCT 
		bGnl_Rel : BOOL; (*General release. Safety conditions (gas alarm, fire alarm, safety loop, ..) are OK.*) (*OldName: new PV; Cycle: 5;*)
		bECWP_PreH_COf_Man : BOOL; (*engine cooling water pump preheating demand off*) (*OldName: new PV; Cycle: 5;*)
		bECW_PreH_COf_Man : BOOL; (*engine cooling water preheating demand off*) (*OldName: new PV; Cycle: 5;*)
		bInAirER_Lou2DemOpen_Man : BOOL; (*demand open air inlet louver 2*) (*OldName: new PV; Cycle:5;*)
		bInAirER_Lou1DemOpen_Man : BOOL; (*demand open air inlet louver 1*) (*OldName: new PV; Cycle:5;*)
		bOutAirER_LouDemOpen_Man : BOOL; (*open air outlet louver *) (*OldName: new PV; Cycle:5;*)
		bInAirER_Fan1DemOn_Man : BOOL; (*demand air inlet ventilator 1*) (*OldName: new PV; Cycle:5;*)
		bInAirER_Fan2DemOn_Man : BOOL; (*demand air inlet ventilator 2*) (*OldName: new PV; Cycle:5;*)
		bER_FC_Set_Man : BOOL; (*demand engine room frequency converter setpoint*) (*OldName: new PV; Cycle:5;*)
		rER_FC_Set_Man : REAL; (*engine room frequency converter setpoint [%]*) (*OldName: new PV; Cycle:5;*)
		bER_OutlV_FC_Set_Man : BOOL; (*demand engine room air outlet ventilation frequency converter setpoint*) (*OldName: new PV; Cycle:5;*)
		rER_OutlV_FC_Set_Man : REAL; (*engine room air outlet ventilation frequency converter setpoint [%]*) (*OldName: new PV; Cycle:5;*)
		bEC_DemPump_Man : BOOL; (*emergency cooler demand pump*) (*OldName: new PV; Cycle:5;*)
		bEC_DemFan_Man : BOOL; (*emergency cooler demand fan 1 - 16*) (*OldName: new PV; Cycle:5;*)
		bChC_DemPump_Man : BOOL; (*charge cooler demand pump*) (*OldName: new PV; Cycle:5;*)
		bChC_DemFan_Man : BOOL; (*charge cooler demand fan 1 - 16*) (*OldName: new PV; Cycle:5;*)
		bEG_BoVaCoOpen_Man : BOOL; (*exhaust gas boiler valve command open*) (*OldName: new PV; Cycle:5;*)
		bEG_BoVaCoClose_Man : BOOL; (*exhaust gas boiler valve command close*) (*OldName: new PV; Cycle:5;*)
		bEG_ByVaCoOpen_Man : BOOL; (*exhaust gas bypass valve command open*) (*OldName: new PV; Cycle:5;*)
		bEG_ByVaCoClose_Man : BOOL; (*exhaust gas bypass valve command close*) (*OldName: new PV; Cycle:5;*)
		bAuxCust_Man : ARRAY[0..40]OF BOOL; (*reserve customer auxiliaries*) (*OldName: new PV; Cycle:5;*)
		bCDP_Dem_Man : BOOL; (*demand condensor pump*) (*OldName: new PV; Cycle:5;*)
		bBHV_Dem_Man : BOOL; (*demand boiler house ventilation*) (*OldName: newPv; Cycle:5;*)
		bHWF_Dem_Man : BOOL; (*demand heating circuit flap*) (*OldName:newPv; Cycle:5;*)
		bChC_Heating_Man : BOOL; (*charge cooler pre heating*) (*OldName:newPv; Cycle:5;*)
		bCO2_DemCodinox_Man : BOOL; (*CO2 demand CODINOX*) (*OldName:newPv; Cycle:5;*)
		bECWP_PreH_COf : BOOL; (*engine cooling water pump preheating demand off*) (*OldName: new PV; Cycle: 5;*)
		bECW_PreH_COf : BOOL; (*engine cooling water preheating demand off*) (*OldName: new PV; Cycle: 5;*)
		bInAirER_Lou2DemOpen : BOOL; (*demand open air inlet louver 2*) (*OldName: new PV; Cycle:5;*)
		bInAirER_Lou1DemOpen : BOOL; (*demand open air inlet louver 1*) (*OldName: new PV; Cycle:5;*)
		bOutAirER_LouDemOpen : BOOL; (*open air outlet louver *) (*OldName: new PV; Cycle:5;*)
		bInAirER_Fan1DemOn : BOOL; (*demand air inlet ventilator 1*) (*OldName: new PV; Cycle:5;*)
		bInAirER_Fan2DemOn : BOOL; (*demand air inlet ventilator 2*) (*OldName: new PV; Cycle:5;*)
		bER_OutlV_FC_Set : BOOL; (*demand engine room air outlet ventilation frequency converter setpoint*) (*OldName: new PV; Cycle:5;*)
		rER_OutlV_FC_Set : REAL; (*engine room air outlet ventilation frequency converter setpoint [%]*) (*OldName: new PV; Cycle:5;*)
		bER_FC_Set : BOOL; (*demand engine room frequency converter setpoint*) (*OldName: new PV; Cycle:5;*)
		rER_FC_Set : REAL; (*engine room frequency converter setpoint [%]*) (*OldName: new PV; Cycle:5;*)
		bEC_DemPump : BOOL; (*emergency cooler demand pump*) (*OldName: new PV; Cycle:5;*)
		bEC_DemFan : BOOL; (*emergency cooler demand fan 1 - 16*) (*OldName: new PV; Cycle:5;*)
		bChC_DemPump : BOOL; (*charge cooler demand pump*) (*OldName: new PV; Cycle:5;*)
		bChC_DemFan : BOOL; (*charge cooler demand fan 1 - 16*) (*OldName: new PV; Cycle:5;*)
		bEG_BoVaCoOpen : BOOL; (*exhaust gas boiler valve command open*) (*OldName: new PV; Cycle:5;*)
		bEG_BoVaCoClose : BOOL; (*exhaust gas boiler valve command close*) (*OldName: new PV; Cycle:5;*)
		bEG_ByVaCoOpen : BOOL; (*exhaust gas bypass valve command open*) (*OldName: new PV; Cycle:5;*)
		bEG_ByVaCoClose : BOOL; (*exhaust gas bypass valve command close*) (*OldName: new PV; Cycle:5;*)
		bAuxCust : ARRAY[0..70]OF BOOL; (*reserve customer auxiliaries*) (*OldName: new PV; Cycle:5;*)
		bCDP_Dem : BOOL; (*demand condensor pump*) (*OldName: new PV; Cycle:5;*)
		bBHV_Dem : BOOL; (*demand boiler house ventilation*) (*OldName: newPv; Cycle:5;*)
		bHWF_Dem : BOOL; (*demand heating circuit flap*) (*OldName:newPv; Cycle:5;*)
		bChC_Heating : BOOL; (*charge cooler pre heating*) (*OldName:newPv; Cycle:5;*)
		bCO2_DemCodinox : BOOL; (*CO2 demand CODINOX*) (*OldName:newPv; Cycle:5;*)
		bChC2_DemPump : BOOL; (*charge cooler 2 demand pump*) (*OldName: new PV; Cycle:5;*)
		bChC2_DemPump_Man : BOOL; (*charge cooler 2 demand pump*) (*OldName: new PV; Cycle:5;*)
		bChC2_DemFan : BOOL; (*charge cooler 2 demand fan 1 - 16*) (*OldName: new PV; Cycle:5;*)
		bChC2_DemFan_Man : BOOL; (*charge cooler 2 demand fan 1 - 16*) (*OldName: new PV; Cycle:5;*)
		bChC2_Heating : BOOL; (*charge cooler 2 pre heating*) (*OldName:newPv; Cycle:5;*)
		bChC2_Heating_Man : BOOL; (*charge cooler 2 pre heating*) (*OldName:newPv; Cycle:5;*)
		bECW_HydrPreH_COf : BOOL; (*engine cooling water hydraulic preheating demand off*) (*OldName: new PV; Cycle: 5;*)
		bECW_HydrPreH_COf_Man : BOOL; (*engine cooling water hydraulic preheating demand off*) (*OldName: new PV; Cycle: 5;*)
		bEOP_DemPump : BOOL; (*engine prelubrication pump manual demand*) (*OldName: new PV; Cycle: 5;*)
		bEOP_DemPump_Man : BOOL; (*engine prelubrication pump manual demand*) (*OldName: new PV; Cycle: 5;*)
	END_STRUCT;
	Perm_HC_Struct : 	STRUCT 
		iCnt_P_Heat : DINT; (*heat counter*)
		rPermValue01 : REAL; (*spare permanent value - replace with new vars of same lenght, when needed*)
		rPermValue02 : REAL; (*spare permanent value - replace with new vars of same lenght, when needed*)
		rPermValue03 : REAL; (*spare permanent value - replace with new vars of same lenght, when needed*)
		rPermValue04 : REAL; (*spare permanent value - replace with new vars of same lenght, when needed*)
		rPermValue05 : REAL; (*spare permanent value - replace with new vars of same lenght, when needed*)
		rPermValue06 : REAL; (*spare permanent value - replace with new vars of same lenght, when needed*)
		rPermValue07 : REAL; (*spare permanent value - replace with new vars of same lenght, when needed*)
		rPermValue08 : REAL; (*spare permanent value - replace with new vars of same lenght, when needed*)
		rPermValue09 : REAL; (*spare permanent value - replace with new vars of same lenght, when needed*)
		rPermValue10 : REAL; (*spare permanent value - replace with new vars of same lenght, when needed*)
	END_STRUCT;
END_TYPE
