
TYPE
	PROGRAMMER_INFO : 	STRUCT 
		DO_NOT_SORT_PARA : STRING[40] := 'DO NOT CHANGE PARAMETER SORTING!'; (*DO NOT CHANGE PARAMETER SORTING!*) (*ADD NEW PARAMETER ONLY AT THE END OF THE Para STRUCTURE. DO NOT DELETE existing Para items.*)
	END_STRUCT;
	Para_SA_struct : 	STRUCT 
		rCA_AdvTimeLim : REAL; (*PARA [12065]: advanced ingnition timing 1/10 deg *) (* OldName:AdvTimLi; Cycle: *)
		bSA_PI_CloDetActive : BOOL; (*PARA [12121]: TRUE = SAFI PI close detection is enabled/active *) (* OldName:bCloDet_Act; Cycle: *)
		bSA_Active : BOOL; (*PARA [12114]: TRUE = SAFI is enabled/active *) (* OldName:bSAFI_Act; Cycle: *)
		bSA_PBC_Active : BOOL; (*PARA [12119]: TRUE = SAFI PBC function is enabled/active *) (* OldName:bSAFIDMR_Act; Cycle: *)
		bSA_EG_Active : BOOL; (*PARA [12115]: TRUE = SAFI exh. temp. measur. is enabled/active *) (* OldName:bSAFIExhT_Act; Cycle: *)
		bSA_HV_Active : BOOL; (*PARA [12116]: TRUE = SAFI high volt. measur. is enabled/active *) (* OldName:bSAFIHS_Act; Cycle: *)
		bSA_Ign_Active : BOOL; (*PARA [12117]: TRUE = SAFI ignition function is enabled/active *) (* OldName:bSAFIIgn_Act; Cycle: *)
		bSA_KLS_Active : BOOL; (*PARA [12118]: TRUE = SAFI KLS function is enabled/active *) (* OldName:bSAFIKLS_Act; Cycle: *)
		bSA_PI_Active : BOOL; (*PARA [12120]: TRUE = SAFI port injection is enabled/active *) (* OldName:bSAFIPI_Act; Cycle: *)
		rN_EngNom : REAL; (*PARA [12128]: engine nominal speed *) (* OldName:n_nenn; Cycle: *)
		rN_OvrSpeed : REAL; (*PARA [12129]: Ignition overspeed limit *) (* OldName:OvrSpeed; Cycle: *)
		rCA_RetTimeLim : REAL; (*PARA [12066]: Retard ignition timing limit 1/10 deg  *) (* OldName:RetTimLi; Cycle: *)
		rSA_PI_opdet2_rate : REAL; (*PARA [12145]: SAFI PI opdet2_rate *) (* OldName:SAFI_tPI_tPIopdet2_ratePMM; Cycle: *)
		rSA_PI_pudet2_rate : REAL; (*PARA [12146]: SAFI PI pudet2_rate *) (* OldName:SAFI_tPI_tPIpudet2_ratePMM; Cycle: *)
		tSA_Ign_0 : _tSAFICurrPmmREAL; (* Para: SAFI ignition current / duration setting 0 *) (* OldName:SAFICurr0PMM; Cycle: *)
		tSA_Ign_1 : _tSAFICurrPmmREAL; (* Para: SAFI ignition current / duration setting 1 *) (* OldName:SAFICurr1PMM; Cycle: *)
		tSA_Ign_2 : _tSAFICurrPmmREAL; (* Para: SAFI ignition current / duration setting 2 *) (* OldName:SAFICurr2PMM; Cycle: *)
		tSA_Ign_3 : _tSAFICurrPmmREAL; (* Para: SAFI ignition current / duration setting 3 *) (* OldName:SAFICurr3PMM; Cycle: *)
		tSA_Ign_4 : _tSAFICurrPmmREAL; (* Para: SAFI ignition current / duration setting 4 *) (* OldName:SAFICurr4PMM; Cycle: *)
		tSA_Ign_5 : _tSAFICurrPmmREAL; (* Para: SAFI ignition current / duration setting 5 *) (* OldName:SAFICurr5PMM; Cycle: *)
		tSA_Ign_6 : _tSAFICurrPmmREAL; (* Para: SAFI ignition current / duration setting 6 *) (* OldName:SAFICurr6PMM; Cycle: *)
		rSA_PBC_Sensitivity : REAL; (*PARA [12144]: PBC sensor sensitivity [mV/bar] *) (* OldName:ssDMR_empf; Cycle: *)
		rSA_ResetPos : REAL; (*PARA [12148]: SAFI reset position *) (* OldName:ssPosResSA; Cycle: *)
		rSA_EarlTiIonization : REAL; (*PARA [12135]: earliest timing for ionization *) (* OldName:ucAdvTiIonPMM; Cycle: *)
		rSA_CoilType : REAL; (*PARA [12130]: coil type *) (* OldName:ucCoilType; Cycle: *)
		rSA_DelFailR : REAL; (*PARA [12131]: trip limit spark delay failure rate *) (* OldName:ucDelFailRPMM; Cycle: *)
		rSA_DeMagLvl : REAL; (*PARA [12132]: magnatism level decrease *) (* OldName:ucDeMagLvlPMM; Cycle: *)
		rSA_DurFailR : REAL; (*PARA [12133]: spark duration deviation failure rate *) (* OldName:ucDurFailR; Cycle: *)
		rSA_DurTol : REAL; (*PARA [12134]: spark duration deviation limit *) (* OldName:ucDurTol; Cycle: *)
		rSA_InMagLvl : REAL; (*PARA [12140]: magnatism level increase *) (* OldName:ucInMagLvlPmm; Cycle: *)
		rSA_MxSpPow : REAL; (*PARA [12143]: limit for spark power *) (* OldName:ucMxSpPowPMM; Cycle: *)
		iSA_PIValveType : INT; (*PARA [12147]: valve type (1=Woodward, 2= Hoerbiger)*) (* OldName:ucPIValveType; Cycle: *)
		rSA_RetTiIon : REAL; (*PARA [12149]: latest timing for ionization *) (* OldName:ucRetTiIonPMM; Cycle: *)
		rSA_SparkCurChar : REAL; (*PARA [12150]: spark current characteristic *) (* OldName:ucSparkCurChar; Cycle: *)
		rSA_SparkCurLev : REAL; (*PARA [12151]: spark current level *) (* OldName:ucSparkCurLev; Cycle: *)
		rSA_SpPOffTi : REAL; (*PARA [12153]: turn on/off ration for spark power *) (* OldName:ucSpPOffTiPMM; Cycle: *)
		rSA_SparkDuration : REAL; (*PARA [12152]: SAFI spark duration  *) (* OldName:usDurationPMM; Cycle: *)
		rSA_Eps : REAL; (*PARA [12136]: eps *) (* OldName:usEps; Cycle: *)
		rSA_IgnPwrLi : REAL; (*PARA [12138]: SAFI ignition  power limitation  *) (* OldName:usIgnPwrLi; Cycle: *)
		rSA_IgnPwrOut : REAL; (*PARA [12139]: power supply output *) (* OldName:usIgnPwrOut; Cycle: *)
		rSA_MxIonMag : REAL; (*PARA [12141]: magnatism ionisation level *) (* OldName:usMxIonMagPMM; Cycle: *)
		rSA_MxMagLvl : REAL; (*PARA [12142]: magnatism level limit *) (* OldName:usMxMagLvlPMM; Cycle: *)
		rSA_IgnFeedbackLim : REAL; (*PARA [12137]: Time for ignition feedback *) (* OldName:usZuVLimPMM; Cycle: *)
		rCA_Win1_B : REAL; (*PARA [12122]: beginn of window 1 in 1/10 deg.  *) (* OldName:WMF1_B; Cycle: *)
		rCA_Win1_D : REAL; (*PARA [12123]: duration of window 1 in 1/10 deg.  *) (* OldName:WMF1_D; Cycle: *)
		rCA_Win2_B : REAL; (*PARA [12124]: beginn of window 2 in 1/10 deg.  *) (* OldName:WMF2_B; Cycle: *)
		rCA_Win2_D : REAL; (*PARA [12125]: duration of window 2 in 1/10 deg.  *) (* OldName:WMF2_D; Cycle: *)
		rCA_Win3_B : REAL; (*PARA [12126]: beginn of window 3 in 1/10 deg.  *) (* OldName:WMF3_B; Cycle: *)
		rCA_Win3_D : REAL; (*PARA [12127]: duration of window 3 in 1/10 deg.  *) (* OldName:WMF3_D; Cycle: *)
		rCA_Win4_B : REAL; (*PARA [14310]: beginn of window 4 in 1/10 deg.  *) (* OldName:WMF4_B; Cycle: *)
		rCA_Win4_D : REAL; (*PARA [14311]: duration of window 4 in 1/10 deg.  *) (* OldName:WMF4_D; Cycle: *)
		rSA_Win1_F : REAL; (*PARA [12154]: window 1 function *) (* OldName:FenstF1; Cycle: *)
		rSA_Win2_F : REAL; (*PARA [14312]: window 2 function *) (* OldName:FenstF2; Cycle: *)
		rSA_Win3_F : REAL; (*PARA [14313]: window 3 function *) (* OldName:FenstF3; Cycle: *)
		rSA_Win4_F : REAL; (*PARA [14314]: window 4 function *) (* OldName:FenstF4; Cycle: *)
		rU_IgnMon_LimActive : REAL; (*PARA [12155]: ignition voltage start monitoring  *) (* OldName:LimitActiv; Cycle: *)
		tIgn_LimitMonitor : ARRAY[0..4]OF _tMonicLimitREAL; (* Para: parameter voltage limit monitoring  *) (* OldName:LimitMon; Cycle: *)
		bIgn_LimitMonitorActive : ARRAY[0..4]OF BOOL; (* Para: type of voltage limit monitoring *) (* OldName:MonLimitOn; Cycle: *)
		bGridCode_Active : BOOL; (*PARA [11055]: Gride Code active *) (* OldName:bGridCode; Cycle: *)
		iEng_Motortype : INT; (* Para: Engine type *) (* OldName:motortyp; Cycle: *)
		bGridCodeMonitoringOnly : BOOL; (*PARA [11056]: Grid Code monitoring only active *) (* OldName:bGridCodeMonitoringOnly; Cycle: *)
		zz_V4_0_ParaVersionEnd : REAL := 4.0; (*! ADD NEW PARAMETER ONLY BELOW THIS LINE ! This is the end of base version parameter and has to stay unchanged. DO NOT CHANGE SORT ORDER of Para!*) (* OldName: new PV; Cycle: 5; *)
		rHCR : ARRAY[0..4]OF REAL; (* Para: Heat Capacity Ratio *) (* OldName: rKappa; Cycle: 2 *)
		bGT_SpecGasActive : BOOL; (*PARA [11374]: Sondergas *)
		bDynSparkDuration : BOOL; (*PARA [13646]: Variable spark duration active *) (* OldName:newPV; Cycle: *)
		usDurationIdle : UINT; (*PARA [13647]: Spark duration below power threshold *) (* OldName:newPV; Cycle: *)
		rP_Act_DynSpark_Limit_Nom : REAL; (*PARA [13648]: Spark duration below power threshold *) (* OldName:newPV; Cycle: *)
		iSA_CyclPIOnDuringMisf : USINT; (*PARA [13698]: Allowed Nr of cycles of ign off with PI on during misfire*) (* OldName:newPV; Cycle: *)
		rSA_PI_pudet_level : REAL; (*PARA [13699]: PI pull in current level *) (* OldName:newPV; Cycle: *)
		rSA_PI_pudet_st_time : REAL; (*PARA [13700]: PI pull in current start time *) (* OldName:newPV; Cycle: *)
		rSA_PI_pudet_duration : REAL; (*PARA [13701]: PI pull in current duration *) (* OldName:newPV; Cycle: *)
		rSA_PI_demag_delay : REAL; (*PARA [13707]: PI demagnetisation delay *) (* OldName:newPV; Cycle: *)
		rSA_PI_demag_duration : REAL; (*PARA [13708]: PI demagnetisation duration  *) (* OldName:newPV; Cycle: *)
		rSA_PI_demag_up_limit : REAL; (*PARA [13709]: PI demagnetisation upper limit *) (* OldName:newPV; Cycle: *)
		rSA_PI_currCtr_delay : REAL; (*PARA [13702]: PI correct current control delay *) (* OldName:newPV; Cycle: *)
		rSA_PI_currCtr_duration : REAL; (*PARA [13703]: PI correct current control duration *) (* OldName:newPV; Cycle: *)
		rSA_PI_currCtr_level : REAL; (*PARA [13704]: PI correct current control level *) (* OldName:newPV; Cycle: *)
		rSA_PI_currCtr_rate : REAL; (*PARA [13705]: PI correct current control failure rate *) (* OldName:newPV; Cycle: *)
		bPIDemagActive : BOOL; (*PARA [13706]: demagnetisation active *) (* OldName:newPV; Cycle: *)
		rSA_PI_clodet_st_time : ARRAY[0..24]OF REAL; (* PI close detection timing point *) (* OldName:newPV; Cycle: *)
		rSA_PI_clodet_set_current : REAL; (* PI close detection set point current *) (* OldName:newPV; Cycle: *)
		rSA_PI_clodet_set_duration : REAL; (* PI close detection set point duration *) (* OldName:newPV; Cycle: *)
		rSA_PI_clodet_duration : REAL; (* PI close detection duration *) (* OldName:newPV; Cycle: *)
		rSA_PI_clodet_cur_gradient : REAL; (* PI close detection current gradient *) (* OldName:newPV; Cycle: *)
		rSA_PI_clodet_var_limit_Start : REAL; (* PI close detection current gradient variation limit *) (* OldName:newPV; Cycle: *)
		rSA_PI_clodet_var_limit_Idle : REAL; (* PI close detection current gradient variation limit *) (* OldName:newPV; Cycle: *)
		rSA_PI_clodet_var_limit_Load : REAL; (* PI close detection current gradient variation limit *) (* OldName:newPV; Cycle: *)
		rSA_PI_curr1_current : REAL; (* PI set point 1 current *) (* OldName:newPV; Cycle: *)
		rSA_PI_curr1_duration : REAL; (* PI set point 1 duration *) (* OldName:newPV; Cycle: *)
		rSA_PI_curr2_current : REAL; (* PI set point 2 current *) (* OldName:newPV; Cycle: *)
		rSA_PI_curr2_duration : REAL; (* PI set point 2 duration *) (* OldName:newPV; Cycle: *)
		rSA_PI_curr3_current : REAL; (* PI set point 3 current *) (* OldName:newPV; Cycle: *)
		rSA_PI_curr3_duration : REAL; (* PI set point 3 duration *) (* OldName:newPV; Cycle: *)
		rSA_PI_curr4_current : REAL; (* PI set point 4 current *) (* OldName:newPV; Cycle: *)
		rSA_PI_recov_delay : REAL; (* PI energy recovery delay *) (* OldName:newPV; Cycle: *)
		rSA_PI_recov_current : REAL; (* PI energy recovery current *) (* OldName:newPV; Cycle: *)
		rSA_PI_recov_duration : REAL; (* PI energy recovery duration *) (* OldName:newPV; Cycle: *)
		iSA_NrOfMPM : USINT; (*PARA [14108]: SAFI number of  *) (* OldName:newPV; Cycle: *)
		bMORISonExh : BOOL; (*PARA [14352]: TRUE = MORIS rails are onto the exhaus pipes*)
		iU_EVCNoiseLim : UINT; (*PARA [14316]: Outlet valve closure noise limit*)
		iU_IVCNoiseLim : UINT; (*PARA [14317]: Inlet valve closure noise limit*)
		rNum_EVCThreshPer : REAL; (*PARA [14306]: Parameter for outlet valve closure detection*)
		rNum_IVCThreshPer : REAL; (*PARA [14307]: Parameter for inlet valve closure detection*)
		iU_EVCThreshMin : UINT; (*PARA [14308]: Minimum level for outlet valve closure detection*)
		iU_IVCThreshMin : UINT; (*PARA [14309]: Minimum level for inlet valve closure detection*)
		iKlS_MSFailure_Limit : UINT; (*PARA [12074]: limit for measuring signal failue [mV]*)
		bSA_Unb_Active : BOOL; (*PARA [14457]: Valve unbalance detection*)
		iCA_EVCDistLim : UINT; (*PARA [14458]: Maximum distance between the exhaust valve closure events*)
		iCA_IVCDistLim : UINT; (*PARA [14459]: Maximum distance between the intake valve closure events*)
		iCA_EarlyEVCLim : UINT; (*PARA [14460]: Valve unbalance detection exhaust valve closure timing minimum*)
		iCA_EarlyIVCLim : UINT; (*PARA [14461]: Valve unbalance detection intake valve closure timing minimum*)
		bKLS21_IgnMon : BOOL; (*PARA [14622]: KLS21 ignition monitoring*)
		iSA_PI_clodet_FailRLim : USINT; (*PARA [14623]: PI close detection failure rate limit [1/10 cycles]*)
		rNum_SAFI1_RelFwVer : REAL; (*PARA [14624]: Released SAFI1 firmware version*)
		rNum_SAFI2KLS_RelFwVer : REAL; (*PARA [14625]: Released SAFI2 KLS firmware version*)
		rNum_SAFI2DMR_RelFwVer : REAL; (*PARA [14626]: Released SAFI2 DMR firmware version*)
		rNum_SAFI3_RelFwVer : REAL; (*PARA [14627]: Released SAFI3 firmware version*)
		rNum_KLS21_RelFwVer : REAL; (*PARA [14628]: Released KLS21 firmware version*)
		rCA_KLS21_ITPDevLim : REAL; (*PARA [14629]: IP deviation limit [degCA]*)
		iNum_KLS21_ITPDevHist : USINT; (*PARA [14630]: Length of ignition events history [1/10 cycles]*)
		iNum_KLS21_ITPDevMax : USINT; (*PARA [14631]: Maximum missing ignition events [cycles]*)
		iNum_KLS21_ITPDevFailRLim : USINT; (*PARA [14632]: Failure rate limit for IP deviation [cycles]*)
		b_IgnIC_900Active : BOOL; (*PARA [12062]: TRUE=CAN ignition system is used *) (*OldName:ic900_vis; Cycle:;*)
		bSEMIC_Active : BOOL; (*PARA [14519]: Ignition controller SEMIC*)
		r_IgnIC_ResPosIC : REAL; (*PARA [12055]: Ignition reset pickup position *)
		rNum_PolEx : REAL; (*PARA [14900]: Polytropic exponent*)
		bFastStart_Act : BOOL; (* PARA [14184]: Fast Start package activated *)
	END_STRUCT;
END_TYPE
