
TYPE
	PROGRAMMER_INFO : 	STRUCT 
		DO_NOT_SORT_PARA : STRING[40] := 'DO NOT CHANGE PARAMETER SORTING!'; (*DO NOT CHANGE PARAMETER SORTING!*) (*ADD NEW PARAMETER ONLY AT THE END OF THE Para STRUCTURE. DO NOT DELETE existing Para items.*)
	END_STRUCT;
	Para_SY_struct : 	STRUCT 
		rN_EngNom : REAL; (*PARA [12128]: engine nominal speed [1/min]*) (*OldName:n_nenn; Cycle:5;*)
		rU_Gen_Nom : ARRAY[0..2]OF REAL; (*PARA [11597], [11598]: generator nominal voltage [V]*) (*OldName:usUNennGen[1]; Cycle:5;*)
		bGlowIgnPrevActive : BOOL; (*PARA [12089]: glow ignition prevention active *) (*OldName:sel_GlowIgnPrevent; Cycle:5;*)
		bRemoteReqActive : BOOL; (*PARA [12091]: remote request active *) (*OldName:bRemoteReqAct; Cycle:5;*)
		rP_LimLo : REAL; (*PARA [12208]: power signal missing limit low  *) (*OldName:Z_GW_LSA; Cycle:5;*)
		rP_HyLo : REAL; (*PARA [12206]: power signal missing limit hysteresis low  *) (*OldName:HY_LSA; Cycle:5;*)
		rP_LimHi : REAL; (*PARA [12207]: power signal overload limit high  *) (*OldName:GW_LSU; Cycle:5;*)
		rP_HyHi : REAL; (*PARA [12205]: power signal overload limit hysteresis high  *) (*OldName:HY_LSU; Cycle:5;*)
		tiMainsOkDelay : TIME; (*PARA [12216]: mains return delay *) (*OldName:PT_MNS_OK; Cycle:5;*)
		rP_LS_LimHi : REAL; (*PARA [12212]: generator power limit high (load shedding)(% Pnom) *) (*OldName:GW_P_MAX; Cycle:5;*)
		rP_LS_HyHi : REAL; (*PARA [12209]: generator power hysteresis limit high (load shedding)(% Pnom) *) (*OldName:HY_P_MAX; Cycle:5;*)
		tiP_LS_LimHi : TIME; (*PARA [12219]: generator power limit high delay (load shedding)(% Pnom) *) (*OldName:TW_P_MAX; Cycle:5;*)
		rP_LS_LimLo : REAL; (*PARA [12213]: generator power limit low warning (load shedding)(% Pnom) *) (*OldName:GW_P_MIN_W; Cycle:5;*)
		rP_LS_HyLo : REAL; (*PARA [12210]: generator power hysteresis limit low warning (load shedding)(% Pnom) *) (*OldName:newPv; Cycle:5;*)
		tiP_LS_LimLo : TIME; (*PARA [12220]: generator power limit low warning delay (load shedding)(% Pnom) *) (*OldName:TW_P_MIN_W; Cycle:5;*)
		rP_LS_LimLoLo : REAL; (*PARA [12214]: generator power limit low shutdown (load shedding)(% Pnom) *) (*OldName:GW_P_MIN_A; Cycle:5;*)
		rP_LS_HyLoLo : REAL; (*PARA [12211]: generator power hysteresis limit low shutdown (load shedding)(% Pnom) *) (*OldName:HY_P_MIN; Cycle:5;*)
		tiP_LS_LimLoLo : TIME; (*PARA [12221]: generator power limit low shutdown delay (load shedding) *) (*OldName:TW_P_MIN_A; Cycle:5;*)
		rN_LS_LimLo : REAL; (*PARA [12204]: engine speed limit low (load shedding) [1/min]*) (*OldName:GW_DR_MIN; Cycle:5;*)
		rN_LS_HyLo : REAL; (*PARA [12203]: engine speed hysteresis limit low (load shedding) [1/min]*) (*OldName:HY_DR_MIN; Cycle:5;*)
		tiN_LS_LimLo : TIME; (*PARA [12218]: engine speed limit low delay (load shedding) [1/min]*) (*OldName:TW_DR_MIN; Cycle:5;*)
		iEng_Motortype : INT; (* Para engine motortype *) (*OldName:motortyp; Cycle:5;*)
		iCountry : INT; (*PARA [12196]: code for country specific functions *) (*OldName:newPv; Cycle:5;*)
		bMCB_SyMMD2 : BOOL; (*PARA [12189]: synchronization mcb with MMUsynch 2 *) (*OldName:bMMU2syMCB; Cycle:5;*)
		bSyActive : BOOL; (*PARA [12195]: synchronization functions active *) (*OldName:bSynch; Cycle:5;*)
		bMSy : BOOL; (*PARA [12193]: connected to master sy/interlock panel *) (*OldName:msy; Cycle:5;*)
		bMCB_Enable : BOOL; (*PARA [12187]: mains circuit breaker enable (mcb controlled by esy) *) (*OldName:mcb[1].enable; Cycle:5;*)
		bC_CB_Enable : BOOL; (*PARA [12181]: customer circuit breaker (gcb0 = custom generator/engine) enable *) (*OldName:gcb[0].enable; Cycle:5;*)
		bMns_Enable : BOOL; (*PARA [12191]: mains monitoring enable *) (*OldName:mains[1].enable; Cycle:5;*)
		bOnlyIsland_Enable : BOOL; (*PARA [12194]: only island operation (without MSY) enable *) (*OldName:sel_only_island; Cycle:5;*)
		bIslandOp_Enable : BOOL; (*PARA [12184]: island operation (without MSY) enable *) (*OldName:sel_island; Cycle:5;*)
		bBS_Enable : BOOL; (*PARA [12179]: black start enable *) (*OldName:sel_black_start; Cycle:5;*)
		bBS_Acc_Active : BOOL; (*PARA [12178]: black start accelerated active *) (*OldName:sel_black_start_15s; Cycle:5;*)
		rN_BS_Acc_LimHi : REAL; (*PARA [12202]: black start accelerated speed limit high (for engine operation)[rpm] *) (*OldName:bs_15s_rpm_lim_hi; Cycle:5;*)
		bBS_OnlyMan : BOOL; (*PARA [12180]: black start only manual enable *) (*OldName:sel_only_man_black; Cycle:5;*)
		bADL_Enable : BOOL; (*PARA [12177]: anti detonation logic enable *) (*OldName:sel_anti_detonat_logic; Cycle:5;*)
		bMIF_Enable : BOOL; (*PARA [12190]: micro interruption filter enable *) (*OldName:sel_mi_filter_activ; Cycle:5;*)
		bEngOpAfterMIF_Enable : BOOL; (*PARA [12182]: engine operation after micro interruption filter enable *) (*OldName:sel_op_after_MIF; Cycle:5;*)
		bMCB_ReSw2Mns_Enable : BOOL; (*PARA [12188]: mains circuit breaker reswitch to mains enable *) (*OldName:sel_reswitch_to_mains; Cycle:5;*)
		bGenDeexit_Enable : BOOL; (*PARA [12183]: generator deexitation enable *) (*OldName:sel_de_excit; Cycle:5;*)
		bMCB_Ctr_Cust : BOOL; (*PARA [12186]: mains circuit breaker controlled by customer *) (*OldName:sel_mcb_ctrl_c; Cycle:5;*)
		tiMIF : TIME; (*PARA [12217]: micro interruption filter delay time *) (*OldName:PT_MIF; Cycle:5;*)
		rN_EngStart_LimHi : REAL; (*PARA [11296]: speed engine start limit high [1/min]*) (*OldName:GW_DREHZ; Cycle:5;*)
		rN_EngStart_HyHi : REAL; (*PARA [11295]: speed engine start limit high hysteresis [1/min]*) (*OldName:HY_DREHZ; Cycle:5;*)
		rU_Gen_DeEx_LimLo : REAL; (*PARA [12215]: generator voltage deexcitation limit low*) (*OldName:GW_GEN_OSP; Cycle:5;*)
		bGridCode_Active : BOOL; (*PARA [11055]: Gride Code active*) (*OldName:bGridCode; Cycle:5;*)
		bLoadShedPara_Visible : BOOL; (*PARA [12185]: isolated operation/limits load shedding visible*) (*OldName:bIsolOperation; Cycle:5;*)
		iMnsPath_Visible : INT; (*PARA [12199]: connection mains circuit breaker visible*) (*OldName:usVisuNetPath; Cycle:5;*)
		bMnsOk_Visible : BOOL; (*PARA [12192]: symbol mains ok status without mains path visible*) (*OldName:bVisuNetOK; Cycle:5;*)
		iGenPathDown_Visible : INT; (*PARA [12197]: symbol down generator cb - path visible(0=no symbol, 1=transformer, 2=circuit breaker)*) (*OldName:usVisuGenPathDown; Cycle:5;*)
		iGenPathUp_Visible : INT; (*PARA [12198]: symbol up generator cb - path visible(0=no symbol, 1=transformer, 2=circuit breaker)*) (*OldName:usVisuGenPathUp; Cycle:5;*)
		iMnsPathDown_Visible : INT; (*PARA [12200]: symbol down mains cb - path visible(0=no symbol, 1=transformer, 2=circuit breaker)*) (*OldName:usVisuNetPathDown; Cycle:5;*)
		iMnsPathUp_Visible : INT; (*PARA [12201]: symbol up mains cb - path visible(0=no symbol, 1=transformer, 2=circuit breaker)*) (*OldName:usVisuNetPathUp; Cycle:5;*)
		bP_LoadReject_Active : BOOL; (*PARA [12890]: Load rejection funcitons active *) (*OldName:newPv; Cycle:5;*)
		bBB_ClosCondLimits_Active : BOOL; (*PARA [13172]: Busbar closing condition limit active *) (*OldName:newPv; Cycle:5;*)
		rU_BB_ClosCond_LimLo_Norm : REAL; (*PARA [13173]: Busbar closing condition norm voltage lower limit *) (*OldName:newPv; Cycle:5;*)
		rU_BB_ClosCond_LimHi_Norm : REAL; (*PARA [13174]: Busbar closing condition norm voltage higher limit *) (*OldName:newPv; Cycle:5;*)
		rU_BB_ClosCond_Hy_Norm : REAL; (*PARA [13175]: Busbar closing condition norm voltage hysteresis *) (*OldName:newPv; Cycle:5;*)
		rF_BB_ClosCond_LimLo : REAL; (*PARA [13176]: Busbar closing condition frequency lower limit *) (*OldName:newPv; Cycle:5;*)
		rF_BB_ClosCond_LimHi : REAL; (*PARA [13177]: Busbar closing condition frequency higher limit *) (*OldName:newPv; Cycle:5;*)
		rF_BB_ClosCond_Hy : REAL; (*PARA [13178]: Busbar closing condition frequency hysteresis *) (*OldName:newPv; Cycle:5;*)
		tiBB_ClosCond_Delay : TIME; (*PARA [13179]: Busbar closing condition delay time *) (*OldName:newPv; Cycle:5;*)
		tiBB_ClosCondAftMnsFail_Delay : TIME; (*PARA [13180]: Busbar closing condition delay time after mains failure *) (*OldName:newPv; Cycle:5;*)
		tiMCB_COf_GCB_OpF : TIME; (*PARA [13309]: delay time opening MCB in case of GCB opening failure*) (*OldName:newPv; Cycle:5;*)
		rP_Red_TempMax_GenCB_Rate : REAL; (*PARA [13272]: Setpoint power reduction temp. max generator switch gear*) (*OldName:newPv; Cycle:5;*)
		bP_Red_TempMax_GenCB_Active : BOOL; (*PARA [13271]: activation power reduction temp. max generator switch gear*) (*OldName:newPv; Cycle:5;*)
		rI_GenNom : ARRAY[0..2]OF REAL; (*PARA [11750], [11751]: nominal current generator [0..65kA] *) (* OldName:usINennGen; Cycle: 5*)
		bGCB_MainsCutOff_Active : BOOL; (*PARA [13263]: mains cut off with generator circuit breaker active*) (*OldName:sel_gcb_mains_cut_off_Enable; Cycle:5;*)
		rU_BusNom : ARRAY[0..2]OF REAL; (*PARA [11851], [11852]: nominal voltage bus [70V..65kV] *) (* OldName:usUNennBus; Cycle: 5*)
		bRej2houseload : BOOL; (*PARA [14079]: Fangen im Eigenbedarf aktiv?*)
		bBB_AfMnsF_ClosCondLimits_Active : BOOL; (*PARA [14136]: Busbar closing condition limit after mains failure active *) (*OldName:newPv; Cycle:5;*)
		rU_BB_AfMnsF_ClosCond_LimLo_Norm : REAL; (*PARA [14137]: Busbar closing condition norm voltage lower limit after mains failure*) (*OldName:newPv; Cycle:5;*)
		rU_BB_AfMnsF_ClosCond_LimHi_Norm : REAL; (*PARA [14138]: Busbar closing condition norm voltage higher limit after mains failure*) (*OldName:newPv; Cycle:5;*)
		rU_BB_AfMnsF_ClosCond_Hy_Norm : REAL; (*PARA [14139]: Busbar closing condition norm voltage hysteresis after mains failure*) (*OldName:newPv; Cycle:5;*)
		rF_BB_AfMnsF_ClosCond_LimLo : REAL; (*PARA [14140]: Busbar closing condition frequency lower limit after mains failure*) (*OldName:newPv; Cycle:5;*)
		rF_BB_AfMnsF_ClosCond_LimHi : REAL; (*PARA [14141]: Busbar closing condition frequency higher limit after mains failure*) (*OldName:newPv; Cycle:5;*)
		rF_BB_AfMnsF_ClosCond_Hy : REAL; (*PARA [14142]: Busbar closing condition frequency hysteresis after mains failure*) (*OldName:newPv; Cycle:5;*)
  		bMMDSynch_Act : ARRAY[0..2]OF BOOL; (*PARA [11714], [11715]: synchronization of MMDsynch active *) (* OldName:bMMUSynchAct; Cycle: *)
  		rTi_SynchImpMin : ARRAY[0..2]OF REAL; (*PARA [11837], [11838]: minimum impulse width of DO4 [0,04..0,5s] *) (* OldName:usImpDO4Min; Cycle: *)
  		rTi_SynchSwitchDel : ARRAY[0..2]OF REAL; (*PARA [11839], [11840]: witching delay of the relay switched with DO4 [40..300ms] *) (* OldName:usSwitchDelDO4; Cycle: *)
		iGCB_OnCnt_LimHi : DINT; (*PARA [14495]: generator circuit breaker switching cycles maintenance request*)
		rP_LimHiHi : REAL; (*PARA [12559]: power signal overload  isolated mode *) (*OldName; Cycle:5;*)
		ti_P_LimHiHi : TIME; (* PARA [14510]: power signal overload  isolated mode delay *) (*OldName; Cycle:5;*)
		iSel_Customer : DINT; (*PARA [14950]: 0 = no special, 1 = AB Energy, 2 = Aggreko, 3 = 2G, etc.... *)
	END_STRUCT;
END_TYPE
