
TYPE
	IN_SY_struct : 	STRUCT 
		tAB2SY : AmmBase2MM;
		tPB2MM : ParaBase2MM_type;
		iSt_OpMode : UDINT; (*status operation mode*) (*OldName:newPv; Cycle:5;*)
		iIdx_OMSS : INT; (*engine operation mode selection*) (*OldName:newPv; Cycle:5;*)
		rN_EngAct : REAL; (*engine speed actual [1/min]*) (*OldName:ANA.DREHZ; Cycle:5;*)
		bEng_RPSDem : BOOL; (*engine demanded *) (*OldName:A_AGFD; Cycle:5;*)
		bEng_Rdy_Aut_Exc : BOOL; (* engine ready for automatic operation *) (*OldName:BERAUT; Cycle:5;*)
		bGCB_Off_CNS : BOOL; (* generator circuit breaker opened by curent negative sequence *) (*OldName:gcb_off_iasy; Cycle:5;*)
		bGCB_Off_RP : BOOL; (* generator circuit breaker opened by reverse power *) (*OldName:gcb_off_rlsg; Cycle:5;*)
		bEng_Dem : BOOL; (* demand engine *) (*OldName:M_AGFD; Cycle:5;*)
		bEng_Dem_EPS : BOOL; (* engine demand for emergency operation *) (*OldName:M_NANF; Cycle:5;*)
		bGV_On : BOOL; (*Gas valves On *) (* OldName:M_GASV; Cyclic:5;*)
		rP_Nom : REAL; (* nominal power related to selected gas type [kW]*) (*OldName:PN_GASART[]; Cycle:5;*)
		bSCO_Active : BOOL; (* safety cut out gas valves glow ignition prevention *) (*OldName:SICH_SCHL; Cycle:5;*)
		rP_Act_Norm : REAL; (* actual power related to rP_Nom [%] *) (*OldName:P_IST_OF; Cycle:5;*)
		rP_Act_Norm_Filt : REAL; (* actual power related to rP_Nom filtered(1s) [%] *) (*OldName:P_IST; Cycle:5;*)
		bP_Red_Active : BOOL; (* power reduction active - any kind *) (*OldName:PredAkt; Cycle:5;*)
		bRelSy_Customized : BOOL; (*release synchronization from custom)*) (*OldName:newPv; Cycle:5;*)
		rP_MainsImport : REAL; (* mains import power [kW]*) (*OldName:Pmns_pv_1; Cycle:5;*)
		tEng_Run : HALioDo_Type; (* engine in operation *) (*OldName:BTRB; Cycle:5;*)
		tRel_Sync_Load : HALioDo_Type; (*DO release of sychronization and load*) (*OldName:SY_LFG; Cycle:5;*)
		tGrC_DCon : HALioDo_Type; (*DO: FALSE = Disconnect from Grid due to GridCode Event*) (* OldName: DO_GRIDCODE_DCON_TC1; Cycle:5; *)
		tTBMode : HALioDi_Type; (* DI test bench mode *) (*OldName:CIRCUITUS; Cycle:5;*)
		tBB_Alive : HALioDi_Type; (* DI bus bar alive *) (*OldName:DI_BB_ALIVE; Cycle:5;*)
		tBB_Dead_MMD : ARRAY[0..2]OF HALioDi_Type; (* DI bus bar dead from MMD *) (*OldName:DI_MMUSynchStatDO03; Cycle:5;*)
		tC_CB_EDC : HALioDi_Type; (* DI customer circuit breaker (engine) demand close *) (*OldName:DI_C_CB_EDC; Cycle:5;*)
		tC_CB_ESL : HALioDi_Type; (* DI customer circuit breaker (engine) status locked *) (*OldName:DI_C_CB_ESL; Cycle:5;*)
		tC_CB_Off : HALioDi_Type; (* DI customer circuit breaker opened *) (*OldName:DI_C_CB_OFF; Cycle:5;*)
		tC_CB_On : HALioDi_Type; (* DI customer circuit breaker closed *) (*OldName:DI_C_CB_ON; Cycle:5;*)
		tReq_PowMod : HALioDi_Type; (* DI request power operation mode *) (*OldName:DI_DMND_PM; Cycle:5;*)
		tEngDemIsland : HALioDi_Type; (* DI engine demand for island operation *) (*OldName:DI_ENG_DI; Cycle:5;*)
		tGCB_AGO : HALioDi_Type; (* DI all other generator circuit breaker off *) (*OldName:DI_GCB_AGO; Cycle:5;*)
		tGCB_DSY : HALioDi_Type; (* DI  generator circuit breaker demand synchronization (synchline) *) (*OldName:DI_GCB_DSY; Cycle:5;*)
		tGCB_DVM : HALioDi_Type; (* DI  generator circuit breaker demand voltage matching *) (*OldName:DI_GCB_DVM; Cycle:5;*)
		tGCB_MDL : HALioDi_Type; (* DI generator circuit breaker master demand lock (for closing other GCB to dead BB) *) (*OldName:DI_GCB_MDL; Cycle:5;*)
		tGCB_MRC : HALioDi_Type; (* DI generator circuit breaker master release close (to dead busbar) *) (*OldName:DI_GCB_MRC; Cycle:5;*)
		tGCB_OGP : HALioDi_Type; (* DI generator circuit breaker other generator parallel *) (*OldName:DI_GCB_OGP; Cycle:5;*)
		tGCB_On : HALioDi_Type; (* DI generator circuit breaker closed *) (*OldName:DI_GCB_ON; Cycle:5;*)
		tGCB_Rac : HALioDi_Type; (* DI generator circuit breaker racked in *) (*OldName:DI_GCB_RAC; Cycle:5;*)
		tGCB_Rdy : HALioDi_Type; (* DI generator circuit breaker ready (for close) *) (*OldName:DI_GCB_RDY; Cycle:5;*)
		tGCB_RI : HALioDi_Type; (* DI generator circuit breaker reelase island *) (*OldName:DI_GCB_RI; Cycle:5;*)
		tGCB_SM1 : HALioDi_Type; (* DI generator circuit breaker output signal monitoring 1 *) (*OldName:DI_GCB_SM1; Cycle:5;*)
		tGCB_SM2 : HALioDi_Type; (* DI generator circuit breaker contact signal monitoring 2 *) (*OldName:DI_GCB_SM2; Cycle:5;*)
		tGCB_Off : HALioDi_Type; (* DI generator circuit breaker opened *) (*OldName:DI_GCB_OFF; Cycle:5;*)
		tGCB_Earth : HALioDi_Type; (* DI generator circuit breaker position earth *) (*OldName:newPv; Cycle:5;*)
		tMCB_OL : HALioDi_Type; (* DI mains circuit breaker overload *) (*OldName:DI_MCB_OL; Cycle:5;*)
		tMCB_On : HALioDi_Type; (* DI mains circuit breaker closed *) (*OldName:DI_MCB_ON; Cycle:5;*)
		tMCB_Off : HALioDi_Type; (* DI mains circuit breaker opened *) (*OldName:DI_MCB_OFF; Cycle:5;*)
		tMCB_Rac : HALioDi_Type; (* DI mains circuit breaker racked in *) (*OldName:DI_MCB_RAC; Cycle:5;*)
		tMCB_Rdy : HALioDi_Type; (* DI mains circuit breaker ready (for close) *) (*OldName:DI_MCB_RDY; Cycle:5;*)
		tMCB_Rem : HALioDi_Type; (* DI mains circuit breaker remote (operating mode) *) (*OldName:DI_MCB_REM; Cycle:5;*)
		tMCB_SM : HALioDi_Type; (* DI mains circuit breaker signal monitoring *) (*OldName:DI_MCB_SM; Cycle:5;*)
		tMns_MDF : HALioDi_Type; (* DI mains monitoring device failure *) (*OldName:DI_MCB_MDF; Cycle:5;*)
		tMnsOk : HALioDi_Type; (* DI mains ok *) (*OldName:DI_MNS_OK; Cycle:5;*)
		tOnly_Island : HALioDi_Type; (* DI only island operation *) (*OldName:DI_ONLY_I; Cycle:5;*)
		tRel_BS : HALioDi_Type; (* DI release black start *) (*OldName:DI_REL_BS; Cycle:5;*)
		tRel_I : HALioDi_Type; (* DI release island operation *) (*OldName:DI_REL_I; Cycle:5;*)
		tRel_LS : HALioDi_Type; (* DI release load shedding *) (*OldName:DI_REL_LS; Cycle:5;*)
		tGCB_DRM : HALioDi_Type; (* DI generator circuit breaker demand MCB closing return to mains *) (*OldName:newPv; Cycle:5;*)
		tGen_RVM : HALioDi_Type; (* DI generator release voltage matching (leroy somer) *) (*OldName:newPv; Cycle:5;*)
		tSy_N_Up : HALioDi_Type; (* DI external speed matching UP *) (*OldName:newPv; Cycle:5;*)
		tSy_N_Down : HALioDi_Type; (* DI external speed matching DOWN *) (*OldName:newPv; Cycle:5;*)
		tLineCB_On : HALioDi_Type; (* DI line circuit breaker closed *) (*OldName:LIN_EIN; Cycle:5;*)
		tU_Avg : ARRAY[0..2]OF HALioAi_Type; (*AI generator voltage average value MMD [V]*) (*OldName:ANA.UDURCH; Cycle:5;*)
		tRelEngOpFromGSy : HALioDi_Type; (*DI release engine operation from 'gemeinsame'synchronization*) (*OldName:F_BLO; Cycle:5;*)
		tEarthCB_Off : HALioDi_Type; (*DI earth circuit breaker opened, france country specific*) (*OldName:DI_ECB_OFF; Cycle:5;*)
		tIsoCB_Off : HALioDi_Type; (*DI disconnecting circuit breaker opened, france country specific*) (*OldName:DI_ISOL; Cycle:5;*)
		tMnsOk_GTE : HALioDi_Type; (*DI mains ok GTE monitoring device, france country specific*) (*OldName:DI_GTE; Cycle:5;*)
		tMnsOk_TGS : HALioDi_Type; (*DI mains ok TGS monitoring device, france country specific*) (*OldName:DI_TGS; Cycle:5;*)
		tMnsOk_C13100 : HALioDi_Type; (*DI mains ok C13.100 monitoring device, france country specific*) (*OldName:DI_C13_100; Cycle:5;*)
		bMsg1026 : BOOL; (*engine shutdown failure *) (*OldName:M_ANSTAB; Cycle:5;*)
		bMsg1026_Test : BOOL; (*engine shutdown failure test*) (*OldName:newPv; Cycle:5;*)
		bMsg1134 : BOOL; (*Earth failure*) (*OldName:M_ERDS; Cycle:5;*)
		bMsg1036 : BOOL; (*overload short circuit*) (*OldName:M_ULKS; Cycle:5;*)
		bMsg1038 : BOOL; (*generator reverse power*) (*OldName:M_RLSG; Cycle:5;*)
		bMsg1073 : BOOL; (*generator over load from multi measuring device*) (*OldName:M_MMD_OL; Cycle:5;*)
		bMsg1132 : BOOL; (*generator differencial protection*) (*OldName:M_DIFF; Cycle:5;*)
		bMsg3319 : BOOL; (*generator protection trip*) (*OldName:M_GEN_PT; Cycle:5;*)
		rCust_SparePara : ARRAY[0..200]OF REAL; (*SPS_REZP1 to SPS_REZP200	*) (* OldName: SPS_REZP1, SPS_REZP2, SPS_REZP70; Cycle: 5; *)
		tCustAnaIn : ARRAY[0..120]OF HALioAi_Type; (*Replacement for RAN_KANAL...*) (*OldName: ANA_RAN	; Cycle: 5;*)
		tCustDigIn : ARRAY[0..200]OF HALioDi_Type; (*new, reserved for Project specific use*) (*OldName: new PV	; Cycle: 5;*)
		tMCB_Rel_Sync_SOn : HALioDo_Type; (* DO: releas decoupling quickly from EU (ERDF) *) (*OldName:DO_RMFrgKop ;Cycle:5;*)
		bServiceMode : BOOL; (*service mode*) (*OldName:bServiceBegin; Cycle:5;*)
		bBDC_Emergency_OFF : BOOL; (*over load - emergency off*) (*OldName:new PV; Cycle:5;*)
		tPr_Ch_P2s : HALioAi_Type; (*actual charge pressure before throttle valve(P2s)[bar]*) (*OldName:pl_ist; Cycle:5;*)
		tPr_Ch_P2s_A : HALioAi_Type; (*actual charge pressure before throttle valve(P2s)bank A[bar]*) (*OldName:pl_ist; Cycle:5;*)
		tPr_Ch_P2s_B : HALioAi_Type; (*actual charge pressure before throttle valve(P2s)bank B[bar]*) (*OldName:pl_ist; Cycle:5;*)
		tMnsOk_ClosCond_Ok : HALioDi_Type; (*closing condition from external facility*) (*OldName:newPV; Cycle:5*)
		tU_MMD_Synch2 : ARRAY[0..2]OF HALioAi_Type; (*phase voltage system 2*) (*OldName:ssSynch2Volt; Cycle:5*)
		tF_MMD_Synch2 : ARRAY[0..2]OF HALioAi_Type; (*frequency sync-system 2*) (*OldName:usSynch2Frequency; Cycle:2*)
		iIdx_Eng_State : INT; (* state of engine *) (*OldName:HPTSCHL; Cycle:5;*)
		tMCB_OpF_Ext : HALioDi_Type; (*generator circuit breaker opening failure*) (*OldName:newPV; Cycle:5*)
		tGCB_OpF_Ext : HALioDi_Type; (*generator circuit breaker opening failure*) (*OldName:newPV; Cycle:5*)
		tTempMax_GenCB : HALioDi_Type; (*Temperature max generator switch gear*)
		bEng_Bloc : BOOL; (* blocking engine *) (*OldName:M_BLOCK;Cycle:5;*)
		bMMD_GenAlarmTestOn : BOOL; (*MMD_Gen alarm test On*) (*OldName:newPv; Cycle:5;*)
		bMMD_BB_AlarmTestOn : BOOL; (*MMD_BB  alarm test On*) (*OldName:newPv; Cycle:5;*)
		rI_MaxL1 : ARRAY[0..2]OF REAL; (* max. generator current phase 1 [A]  *) (* OldName:ssIMaxL1; Cycle: *)
		rI_MaxL2 : ARRAY[0..2]OF REAL; (* max. generator current phase 2 [A]  *) (* OldName:ssIMaxL2; Cycle: *)
		rI_MaxL3 : ARRAY[0..2]OF REAL; (* max. generator current phase 3 [A]  *) (* OldName:ssIMaxL3; Cycle: *)
		bType6_Update_Rel : BOOL; (* Enables Type6 Engine controls Update (100% Loadrejection, Island mode etc..) *) (*OldName:newPv; Cycle:5;*)
		bT_ECW_Lo : BOOL; (*temperature engine cooling water limit low*) (*OldName:AN_KTMI; Cycle:5;*)
		tU_Bus_L3_1 : ARRAY[0..2]OF HALioAi_Type; (* Line voltage bus bar 3 1 *) (*OldName:ssBusVoltPh3_1; Cycle:5*)
		tU_Bus_L2_3 : ARRAY[0..2]OF HALioAi_Type; (* Line voltage bus bar 2 3 *) (*OldName:ssBusVoltPh2_3; Cycle:5*)
		tU_Bus_L1_2 : ARRAY[0..2]OF HALioAi_Type; (* Line voltage bus bar 1 2 *) (*OldName:ssBusVoltPh1_2; Cycle:5*)
		bGridCode_ON : BOOL; (*any dyn. GridCode function activated*)
		bGen2_Act : BOOL; (* TRUE = Gen2 Controller active*) (* Oldname: BDC_ON; Cycle: 2 *)
		tMnsOk_ClosCond_Skip : HALioDi_Type; (*skip closing condition from external facility*) (* OldName: newPV; Cycle:5; *)
		tAfMnsF_ClosCond_Ok : HALioDi_Type; (*closing condition from external facility after mains failure*) (* OldName: newPV; Cycle:5; *)
		tAfMnsF_ClosCond_Skip : HALioDi_Type; (*skip closing condition from external facility after mains failure*) (* OldName: newPV; Cycle:5; *)
		tHW_Switches : OpMode_Switches; (*Hardware operation mode switches*)
		tF_MMD_BusBar : ARRAY[0..2]OF HALioAi_Type; (*frequency busbar*) (*OldName:usSynch2Frequency; Cycle:2*)
		bTP_GrC_Event : BOOL; (* Grid Code Event*) (*OldName: bGridCodeEvent;*)
		tMidVoltCB_Failure : HALioDi_Type; (*mid voltage CB failure*)
		tAuxV_Supply_Ok : HALioDi_Type; (*DI auxiliary voltage supply ok*) (*OldName:SPG_HBT; Cycle:5;*)
		bDem_I_Bus : BOOL; (* Demand Island Operation by Bus *)
		bRel_I_Bus : BOOL; (* Release Island Operation by Bus *)
		bDem_Sy_Bus : BOOL; (* Demand synchronization by Bus *)
		bDem_RSy_Bus : BOOL; (* Demand re-synchronization by Bus *)
		bDem_BS_GCBOn_Bus : BOOL; (* Demand blouck-out start with GCB closed by Bus *)
		bDem_BS_DeExc_Bus : BOOL; (* Demand blouck-out start with deexcitation by Bus *)
		bGCB_by_Customer : BOOL; (* GCB controled by Customer *)
		bMMD_SynchDO : ARRAY[0..2]OF BOOL; (* feedback synch DO *) (* OldName:new PV;*)
		bMMD_SynchDO_TC1 : ARRAY[0..2]OF BOOL; (* feedback synch DO *) (* OldName:new PV;*)
		tI_L1_TC1 : ARRAY[0..2]OF HALioAi_Type; (*Phase current generator I1 *) (*OldName:ssIL1_fast;*)
		tI_L2_TC1 : ARRAY[0..2]OF HALioAi_Type; (*Phase current generator I2 *) (*OldName:ssIL2_fast;*)
		tI_L3_TC1 : ARRAY[0..2]OF HALioAi_Type; (*Phase current generator I3 *) (*OldName:ssIL3_fast;*)
		bCust_Dem_Sy : BOOL; (* Demand synchronization from CU module *) (*OldName:ssBusVoltPh1_2; Cycle:5*)
		bCust_Dem_RSy : BOOL; (* Demand re-synchronization from CU module *) (*OldName:ssBusVoltPh1_2; Cycle:5*)
		tGndFault_BB : HALioDi_Type; (*earth fault bus bar*)
		bGCB_DCon_EC : BOOL; (*GCB open command from EngineController *)
		tDemGenExcOff : HALioDi_Type; (*demand generator excitation off*)
		bBypassMCB_deadBB : BOOL; (*bypass MCB status information from the standard dead_bb check*)
		bBypassMCB_SoftStart : BOOL; (*bypass MCB status information from the standard soft energisation logic*)
		bBypassMCB_LoadShed : BOOL; (*bypass MCB status information from the standard load shedding logic*)
		bSoftEnergDem : BOOL; (*demand transformer soft energisation*)
		bReq_PowMod : BOOL; (*request power mode - over-written in customization*)
		bCust_Rel_I : BOOL; (*release island from CU module*)
		bCust_RelI_BB : BOOL; (*release VKE10 from CU module (Aggreko)*)
		bCust_Dem_EPS_Sy : BOOL; (*demand EPS from CU module*)
		bSmoothDischarge_CU : BOOL; (*Smooth engine discharge in Island mode set in CU*)
		bSetGCB2Close : BOOL; (*External GCB close command*)
		bSetGCB2Open : BOOL; (*External GCB open command*)
		bSetFixedPwrMode : BOOL; (*Set power mode event based*)
		bOM_Bus : BOOL; (*Operation mode via BUS*) (*OldName:OperationModeModbus; Cycle:5;*)
		bSetIslandMode : BOOL; (*Set island mode event based*)
		bSetAutControlMode : BOOL; (*Set manual conrol mode event based *)
		bSetManControlMode : BOOL; (*Set auto conrol mode event based*)
		bBus_Active : BOOL; (*Bus communication active*) (*OldName:Modbus_activ; Cycle:5;*)
		bGCB_OGP_Bus : BOOL; (* other generator parallel over Modbus*)
		bPact_Rev : BOOL; (*reverse power*)
	END_STRUCT;
END_TYPE

(*END_IN*)

TYPE
	OUT_SY_struct : 	STRUCT 
		tIsland_Op : HALioDo_Type; (*Island operation*) (*OldName:A_USP; Cycle:5;*)
		tParallel_Op : HALioDo_Type; (*mains parallel operation*) (*OldName:A_USP; Cycle:5;*)
		tSY2AB : MM2AmmBase;
		tSY2PB : MM2ParaBase_type;
		bSyncSlipMode : ARRAY[0..2]OF BOOL; (*MMD synchronization with slip mode*) (*OldName:bSyncSlipMode; Cycle:5;*)
		bEng_Dem_EPS_Sy : BOOL; (*engine demand emergency power supply from synch.*) (*OldName:ANF_NSB; Cycle:5;*)
		bMCB_DemSy : BOOL; (* demand synchronization mains circuit breaker *) (*OldName:ARSYANW,mcb[1].dmnd_sy; Cycle:5;*)
		bGCB_DemSy : BOOL; (* demand synchronization generator circuit breaker *) (*OldName:ASYANW,gcb[1].dmnd_sy; Cycle:5;*)
		bGen_SyD_Dem : BOOL; (* demand synch.device *) (*OldName:dmnd_sy_device; Cycle:5;*)
		bRelEngOpFromSy : BOOL; (* release engine operation from synchronization *) (*OldName:M_FBLO; Cycle:5;*)
		bRel_Island : BOOL; (* release island operation *) (*OldName:FG_INSEL; Cycle:5;*)
		bDSyLine : BOOL; (* demand synchline *) (*OldName:M_SYL; Cycle:5;*)
		bMCB_On : BOOL; (* mains circuit breaker closed *) (*OldName:MCB_ON; Cycle:5;*)
		bMnsOk : BOOL; (* mains ok *) (*OldName:NE_OK; Cycle:5;*)
		bMainsReturn : BOOL; (* mains return *) (*OldName:NWK; Cycle:5;*)
		bOtherGenParallel : BOOL; (* other generator parallel *) (*OldName:PARALLEL; Cycle:5;*)
		bOnly_Island : BOOL; (* only island operation *) (*OldName:REIN_INSEL; Cycle:5;*)
		bMsg1218 : BOOL; (* generator circuit breaker opening failure *) (*OldName:S_AUS_GS; Cycle:5;*)
		bMsg1219 : BOOL; (* generator circuit breaker closing failure *) (*OldName:S_EIN_GS; Cycle:5;*)
		bMsg1217 : BOOL; (* generator circuit breaker position signal failure *) (*OldName:S_STL_GS; Cycle:5;*)
		bMsg1209 : BOOL; (* mains circuit breaker position signal failure *) (*OldName:S_STL_NS; Cycle:5;*)
		bSmoothDischarge : BOOL; (* smooth engine discharge *) (*OldName:SANFT; Cycle:5;*)
		bBB_dead : BOOL; (* bus bar dead *) (*OldName:SS_OSP; Cycle:5;*)
		bSynchDem : BOOL; (* synchronization demanded *) (*OldName:SynchAnf; Cycle:5;*)
		bGen_Exc_Off : BOOL; (* de- excitation *) (*OldName:T_ENTR; Cycle:5;*)
		bRel_IslandAfMITime : BOOL; (* jump release island op.after mi-filter time *) (*OldName:T79; Cycle:5;*)
		bTestBenchModeIsland : BOOL; (* test bench mode - island mode *) (*OldName:PRF_I; Cycle:5;*)
		bTestBenchModeParallel : BOOL; (* test bench mode - parallel mode *) (*OldName:PRF_NP; Cycle:5;*)
		tGCB_RUC : HALioDo_Type; (* generator circuit breaker release undervoltage coil *) (*OldName:A_USP; Cycle:5;*)
		tGCB_COf : HALioDo_Type; (* command gcb off *) (*OldName:DO_GCB_COF; Cycle:5;*)
		tMCB_COf : HALioDo_Type; (* command mcb off *) (*OldName:DO_MCB_COF; Cycle:5;*)
		tDemandBB : HALioDo_Type; (* demand busbar *) (*OldName:DO_DMND_BB; Cycle:5;*)
		tEng_Dem : HALioDo_Type; (* engine demanded for MSY *) (*OldName:DO_ENG_D; Cycle:5;*)
		tEng_Run_Sy : HALioDo_Type; (* engine runing - synchronization*) (*OldName:DO_ENG_RUN; Cycle:5;*)
		tGCB_COn : HALioDo_Type; (* command gcb on *) (*OldName:DO_GCB_CON; Cycle:5;*)
		tGCB_DVS : HALioDo_Type; (* generator circuit breaker demand voltage selection *) (*OldName:DO_GCB_DVS; Cycle:5;*)
		tGCB_EDC : HALioDo_Type; (* generator circuit breaker engine demand close  *) (*OldName:DO_GCB_EDC; Cycle:5;*)
		tGCB_ESL : HALioDo_Type; (* generator circuit breaker status locked  *) (*OldName:DO_GCB_ESL; Cycle:5;*)
		tGCB_OpF : HALioDo_Type; (* generator circuit breaker opening failure  *) (*OldName:DO_GCB_OPF; Cycle:5;*)
		tGCB_Rel : HALioDo_Type; (* generator circuit breaker release closing  *) (*OldName:DO_GCB_REL; Cycle:5;*)
		tGCB_RSP : HALioDo_Type; (* generator circuit breaker release synch pulse  *) (*OldName:DO_GCB_RSP; Cycle:5;*)
		tGCB_RT : HALioDo_Type; (* generator circuit breaker release trip  *) (*OldName:DO_GCB_RT; Cycle:5;*)
		tLock_C_MCB : HALioDo_Type; (* lock customer mains circuit breaker *) (*OldName:DO_LOCK_C_MCB; Cycle:5;*)
		tMCB_COn : HALioDo_Type; (* mains circuit breaker comand on *) (*OldName:DO_MCB_CON; Cycle:5;*)
		tMCB_DVS : HALioDo_Type; (* mains circuit breaker demand voltage selection *) (*OldName:DO_MCB_DVS; Cycle:5;*)
		tMCB_RSP : HALioDo_Type; (* mains circuit breaker release synch pulse  *) (*OldName:DO_MCB_RSP; Cycle:5;*)
		tMCB_RT : HALioDo_Type; (* mains circuit breaker release trip  *) (*OldName:DO_MCB_RT; Cycle:5;*)
		tPulseMainsOk : HALioDo_Type; (* pulse mains ok *) (*OldName:DO_PUL_MNS_OK; Cycle:5;*)
		tRdy_MSy : HALioDo_Type; (* engine ready for MSY *) (*OldName:DO_RDY_MSY; Cycle:5;*)
		tGenDeexitDem : HALioDo_Type; (* DO generator deexitation demand *) (*OldName:A_ENTR; Cycle:5;*)
		tP_Lo : HALioDo_Type; (* DO power low (for opening GCB) *) (*OldName:P_MIN; Cycle:5;*)
		tN_EngStart : HALioDo_Type; (* DO engine startup speed exceeded*) (*OldName:A_DREHZ; Cycle:5;*)
		tLS_Dem : HALioDo_Type; (*DO load shedding demand*) (*OldName:DO_DMND_LS; Cycle:5;*)
		iIdx_SyOMSS : INT; (*synchronization operating mode selection*) (*OldName:newPv; Cycle:5;*)
		bRelMainsConnect : BOOL; (*Blocking module*) (*OldName:newPv; Cycle:5;*)
		tMCB_COf_GCB_OpF : HALioDo_Type; (*DO opening MCB in case of GCB opening failure*) (*OldName:newPv; Cycle:5;*)
		rP_Red_TempMax_GenCB_Norm : REAL; (*Setpoint power reduction temperature max generator switch gear*) (*OldName:newPv; Cycle:5;*)
		bP_Red_TempMax_GenCB_Sel : BOOL; (*Set power reduction temperature max generator switch gear*) (*OldName:newPv; Cycle:5;*)
		tLockEng_ClosCond : HALioDo_Type; (*lock engine due to closing conditions*) (*OldName:newPv; Cycle:5;*)
		tOMSS_Man : HALioDo_Type; (*operating mode selection man*) (*OldName:BWS_H; Cycle:5;*)
		tOMSS_Aut : HALioDo_Type; (*operating mode selection aut*) (*OldName:BWS_A; Cycle:5;*)
		tClosCond : HALioDo_Type; (*closing conditions ok*) (*OldName:newPv; Cycle:5;*)
		tAfMnsF_ClosCond : HALioDo_Type; (*closing conditions ok after mains failure*) (*OldName:newPv; Cycle:5;*)
		tAfMnsF_LockEng_ClosCond : HALioDo_Type; (*lockout engine due to closing conditions after mains failure*) (*OldName:newPV; Cycle:5;*)
		bSel_DeExc : BOOL; (* Deexcitation selected *)
		bGen_DeExc_Rdy : BOOL; (* Generator Deexitation ready *)
		bMsg1041Set : BOOL; (*power signal missing*)
		bMsg1042Set : BOOL; (*power signal overload*)
		bMsg2801Set : BOOL; (*module blocked by grid connection conditions*)
		bMsg2934Set : BOOL; (*module blocked by grid connection conditions after mains failure*)
		tGenExcOff : HALioDo_Type; (*generator de-energized(excitation off)*)
		tSyOMSS_Man : HALioDo_Type; (*synchronization operating mode selection MANUAL*)
		tSyOMSS_Aut : HALioDo_Type; (*synchronization operating mode selection AUTO*)
		bGCB_aut_on2dead_bb : BOOL; (*generator circuit breaker automatic on to dead bus bar*)
		iModule : USINT; (*Engine Module Number*)
		bGCB_psf_EngStop : BOOL; (*gcb position failure when engine stopped*)
	END_STRUCT;
END_TYPE

(*END_OUT*)

TYPE
	MM2VIS_Struct : 	STRUCT 
		bMnsOk : BOOL; (*mains ok*) (*OldName:B_SV[7]; Cycle:5;*)
		bNotMainsReturn : BOOL; (*not mains return*) (*OldName:RPMZ1; Cycle:5;*)
		bGCB_On : BOOL; (*gcb closed for report time measuring*) (*OldName:B_SV[11]; Cycle:5;*)
		bGCB_GnlWarning : BOOL; (* gcb general failure *) (*OldName:B_SV[8]; Cycle:5;*)
		bDSyGCB : BOOL; (*demand synchronization gcb*) (*OldName:B_SV[10]; Cycle:5;*)
		bMCB_On : BOOL; (*mcb closed for report time measuring*) (*OldName:B_SV[19]; Cycle:5;*)
		bMCB_GnlWarning : BOOL; (*mcb general failure*) (*OldName:B_SV[16]; Cycle:5;*)
		bDSyMCB : BOOL; (*demand synchronization gcb*) (*OldName:B_SV[18]; Cycle:5;*)
		bEngDemIsland : BOOL; (* DI engine demand for island operation *)
		bOnly_Island : BOOL; (* DI only island operation *)
		bGCB_MDL : BOOL; (* DI generator circuit breaker master demand lock (for closing other GCB to dead BB) *)
		bGCB_MRC : BOOL; (* DI generator circuit breaker master release close (to dead busbar) *)
		bGCB_AGO : BOOL; (* DI all other generator circuit breaker off *)
		bGCB_RI : BOOL; (* DI generator circuit breaker reelase island *)
		bGCB_OGP : BOOL; (* DI generator circuit breaker other generator parallel *)
		bGCB_DVM : BOOL; (* DI all other generator circuit breaker off *)
		bGCB_DSY : BOOL; (* DI generator circuit breaker demand synchronization (synchline) *)
		bRdy_MSy : BOOL; (* DO engine ready    for MSY/GSY *)
		bEng_Run_Sy : BOOL; (* DO engine rotating for MSY/GSY *)
		bEng_Dem : BOOL; (* DO engine demanded for MSY/GSY *)
		bGCB_OpF : BOOL; (* DO alarm gcb opening failure *)
		bGCB_EDC : BOOL; (* DO ESY demand lock all other cb's connected to dead busbar *)
		bGCB_ESL : BOOL; (* DO ESY status gcb locked *)
		bMsg1038 : BOOL; (*Generator reserve power*) (*OldName:newPV; Cycle:5;*)
		bMsg1039 : BOOL; (*synchronizing failure (time out)*) (*OldName:AMM_A10xx[]; Cycle:5;*)
		bMsg1041 : BOOL; (*power signal missing*) (*OldName:AMM_A10xx[]; Cycle:5;*)
		bMsg1042 : BOOL; (*power signal overload*) (*OldName:AMM_A10xx[]; Cycle:5;*)
		bMsg1109 : BOOL; (*Generator loss of excitation*) (*OldName:newPV; Cycle:5;*)
		bMsg1143 : BOOL; (*Voltage negative sequence*) (*OldName:newPV; Cycle:5;*)
		bMsg1144 : BOOL; (*Current negative sequence*) (*OldName:newPV; Cycle:5;*)
		bMsg1175 : BOOL; (*mains failure*) (*OldName:AMM_W11xx[]; Cycle:5;*)
		bMsg1189 : BOOL; (*release from synchronization missing*) (*OldName:AMM_W11xx[]; Cycle:5;*)
		bMsg1209 : BOOL; (*mains circuit breaker position signal failure*) (*OldName:AMM_W12xx[]; Cycle:5;*)
		bMsg1210 : BOOL; (*mains circuit breaker opening failure*) (*OldName:AMM_W12xx[]; Cycle:5;*)
		bMsg1211 : BOOL; (*mains circuit breaker closing failure*) (*OldName:AMM_W12xx[]; Cycle:5;*)
		bMsg1212 : BOOL; (*mains circuit breaker o-signal failure*) (*OldName:AMM_W12xx[]; Cycle:5;*)
		bMsg1213 : BOOL; (*mains circuit breaker 1-signal failure*) (*OldName:AMM_W12xx[]; Cycle:5;*)
		bMsg1214 : BOOL; (*mains circuit breaker overload/short circuit*) (*OldName:AMM_W12xx[]; Cycle:5;*)
		bMsg1216 : BOOL; (*bus bar voltage sensor failure*) (*OldName:AMM_W12xx[]; Cycle:5;*)
		bMsg1217 : BOOL; (*generator circuit breaker position signal failure*) (*OldName:AMM_W12xx[]; Cycle:5;*)
		bMsg1218 : BOOL; (*generator circuit breaker opening failure*) (*OldName:AMM_W12xx[]; Cycle:5;*)
		bMsg1219 : BOOL; (*generator circuit breaker closing failure*) (*OldName:AMM_W12xx[]; Cycle:5;*)
		bMsg1220 : BOOL; (*generator circuit breaker o-signal failure*) (*OldName:AMM_W12xx[]; Cycle:5;*)
		bMsg1221 : BOOL; (*generator circuit breaker 1-signal failure*) (*OldName:AMM_W12xx[]; Cycle:5;*)
		bMsg1222 : BOOL; (*generator manual circuit breaker open*) (*OldName:AMM_W12xx[]; Cycle:5;*)
		bMsg1235 : BOOL; (*generator circuit breaker closed*) (*OldName:AMM_B12xx[]; Cycle:5;*)
		bMsg1236 : BOOL; (*generator circuit breaker opened*) (*OldName:AMM_B12xx[]; Cycle:5;*)
		bMsg2139 : BOOL; (*synchronizing running*) (*OldName:AMM_B21xx[]; Cycle:5;*)
		bMsg2330 : BOOL; (*mid voltage CB failure*)
		bMsg2354 : BOOL; (*earth fault bus bar*)
		bMsg2366 : BOOL; (*generator circuit breaker closing failure*)
		bMsg2688 : BOOL; (*Generator current at synchronization too high*) (*OldName:newPv;Cycle:5*)
		bMsg2692 : BOOL; (*generator circuit breaker opening failure*) (*OldName:newPV; Cycle:5;*)
		bMsg2693 : BOOL; (*generator circuit breaker opening failure*) (*OldName:newPV; Cycle:5;*)
		bMsg2730 : BOOL; (*low voltage CB failure*) (*OldName:AMM_W33xx[]; Cycle:5;*)
		bMsg2801 : BOOL; (*module blocked by grid connection conditions*) (*OldName:NewbMsg; Cycle:5;*)
		bMsg2901 : BOOL; (*synchronization selection OFF*) (*OldName:NewPv; Cycle:5;*)
		bMsg2902 : BOOL; (*synchronization selection MAN*) (*OldName:NewPv; Cycle:5;*)
		bMsg2903 : BOOL; (*synchronization selection AUT*) (*OldName:NewPv; Cycle:5;*)
		bMsg2934 : BOOL; (*module blocked by grid connection conditions after mains failure*) (*OldName:NewPv; Cycle:5;*)
		bMsg3253 : BOOL; (*begin maintenance/testbench mode*) (*OldName:AMM_B32xx[]; Cycle:5;*)
		bMsg3254 : BOOL; (*end   maintenance/testbench mode*) (*OldName:AMM_B32xx[]; Cycle:5;*)
		bMsg3263 : BOOL; (*mains circuit breaker closed*) (*OldName:AMM_B32xx[]; Cycle:5;*)
		bMsg3264 : BOOL; (*mains circuit breaker opened*) (*OldName:AMM_B32xx[]; Cycle:5;*)
		bMsg3265 : BOOL; (*demand close GCB*) (*OldName:AMM_B32xx[]; Cycle:5;*)
		bMsg3266 : BOOL; (*mains failure on*) (*OldName:AMM_B32xx[]; Cycle:5;*)
		bMsg3267 : BOOL; (*mains failure off*) (*OldName:AMM_B32xx[]; Cycle:5;*)
		bMsg3269 : BOOL; (*generator de-energized*)
		bMsg3296 : BOOL; (*demand generator excitation off*)
		bMsg3297 : BOOL; (*demand generator excitation on*)
		bMsg3329 : BOOL; (*earth circuit breaker closed, france country specific*) (*OldName:AMM_W33xx[]; Cycle:5;*)
		bMsg3352 : BOOL; (*disconnecting circuit breaker opened, france country specific*) (*OldName:AMM_W33xx[]; Cycle:5;*)
		bMsg3400 : BOOL; (*module blocked by no operating release from sy or cooling water temp.low*) (*OldName:NewPv; Cycle:5;*)
		bMsg3412 : BOOL; (*mains monitoring device failure*) (*OldName:AMM_W34xx[]; Cycle:5;*)
		bMsg3575 : BOOL; (*mains failure GTE2666, france country specific*) (*OldName:AMM_W35xx[]; Cycle:5;*)
		bMsg3576 : BOOL; (*mains failure TGS, france country specific*) (*OldName:AMM_W35xx[]; Cycle:5;*)
		bMsg3577 : BOOL; (*mains failure C13.100, france country specific*) (*OldName:AMM_W35xx[]; Cycle:5;*)
		bMsg9244 : BOOL; (*generator circuit breaker not ready*)
		bMsg9245 : BOOL; (*generator circuit breaker not racked-in*)
		bMsg9304 : BOOL; (*generator circuit breaker closing time deviation high*)
		bMsg9331 : BOOL; (*maintenance request generator circuit breaker*)
		tiGCB_ClosTime : TIME; (*generator circuit breaker closing time*)
		tiGCB_ClosTimeOld : TIME; (*generator circuit breaker closing time old*)
		bMsg1041Set : BOOL; (*power signal missing*)
		bMsg1042Set : BOOL; (*power signal overload*)
		bMsg2801Set : BOOL; (*module blocked by grid connection conditions*)
		bMsg2934Set : BOOL; (*module blocked by grid connection conditions after mains failure*)
		bDemGenExcOff : BOOL; (*demand generator excitation off*)
		bGenExcOff : BOOL; (*generator excitation off*)
		bMsg9083 : BOOL; (*LCB open*)
		bMsg9084 : BOOL; (*LCB closed*)
		tGCB : ARRAY[0..2]OF GCB2VIS_Struct; (* LV GCB *)
		bMsg9085 : BOOL; (*Parameters saved to the GCB*)
		bMsg9382 : BOOL; (*GCB contact wear over 80%*)
		bMsg9383 : BOOL; (*GCB contact wear over 95%*)
	END_STRUCT;
END_TYPE

(*END_MM2VIS*)

TYPE
	VIS2MM_Struct : 	STRUCT 
		bGCB_MOf : BOOL; (*gcb manual off command button*) (*OldName:DI_GCB_MOF; Cycle:5;*)
		bGCB_MOn : BOOL; (*gcb manual on  command button*) (*OldName:DI_GCB_MON; Cycle:5;*)
		bMCB_MOf : BOOL; (*mcb manual off command button*) (*OldName:DI_MCB_MOF; Cycle:5;*)
		bMCB_MOn : BOOL; (*mcb manual on  command button*) (*OldName:DI_MCB_MON; Cycle:5;*)
		iIdx_SyOMSS : DINT; (*synchronization operating mode selection*) (*OldName:newPv; Cycle:5;*)
		bServiceBegin : BOOL; (*service begin (VIS button)*) (*OldName:bServiceBegin; Cycle:5;*)
		iGCB_OnCnt : DINT; (*generator circuit breaker cycle counter*)
		iModule : INT; (*HMI/SYS/Module/Module number setted*)
		tGCB : ARRAY[0..2]OF VIS2GCB_Struct; (* LV GCB *)
	END_STRUCT;
	cb_Struct : 	STRUCT 
		enable : BOOL;
		rdy : BOOL;
		racked_in : BOOL;
		opf : BOOL;
		on : BOOL;
		off : BOOL;
		dmnd_sy : BOOL;
		remote : BOOL;
		man_off : BOOL;
		man_on : BOOL;
		release : BOOL;
		aut_on2dead_bb : BOOL;
		man_on2dead_bb : BOOL;
		eng_demanded : BOOL;
		eng_run : BOOL;
		eng_oper : BOOL;
		esl : BOOL;
		edc_in : BOOL;
		edc : BOOL;
		all_other_gcb_off : BOOL;
		other_gcb_on : BOOL;
		other_gen_parallel : BOOL;
		rel_sy_puls : BOOL;
		rel_island : BOOL;
		dmnd_on : BOOL;
		dmnd_off : BOOL;
		command_on : BOOL;
		command_off : BOOL;
		rel_trip : BOOL;
		mon_release : BOOL;
		mdl : BOOL;
		mrc : BOOL;
		alarm : BOOL;
		alm_psf : BOOL;
		alm_opf : BOOL;
		alm_cf : BOOL;
		alm_0sf : BOOL;
		alm_1sf : BOOL;
		alm_ol : BOOL;
	END_STRUCT;
	mns_Struct : 	STRUCT 
		enable : BOOL;
		ok : BOOL;
		return_rest_time : DINT;
	END_STRUCT;
	Perm_SY_Struct : 	STRUCT 
		iIdx_SyOMSS : DINT; (*synchronization operating mode selection*)
		iGCB_OnCnt : DINT; (*generator circuit breaker cycle counter*)
		rTB_PermValue02 : REAL; (*spare permanent value for testbench- replace with new vars of same lenght, when needed*) (*OldName:new PV;Cycle:2;*)
		rTB_PermValue03 : REAL; (*spare permanent value for testbench- replace with new vars of same lenght, when needed*) (*OldName:new PV;Cycle:2;*)
		rTB_PermValue04 : REAL; (*spare permanent value for testbench- replace with new vars of same lenght, when needed*) (*OldName:new PV;Cycle:2;*)
		rTB_PermValue05 : REAL; (*spare permanent value for testbench- replace with new vars of same lenght, when needed*) (*OldName:new PV;Cycle:2;*)
		rTB_PermValue06 : REAL; (*spare permanent value for testbench- replace with new vars of same lenght, when needed*) (*OldName:new PV;Cycle:2;*)
		rTB_PermValue07 : REAL; (*spare permanent value for testbench- replace with new vars of same lenght, when needed*) (*OldName:new PV;Cycle:2;*)
		rTB_PermValue08 : REAL; (*spare permanent value for testbench- replace with new vars of same lenght, when needed*) (*OldName:new PV;Cycle:2;*)
		rTB_PermValue09 : REAL; (*spare permanent value for testbench- replace with new vars of same lenght, when needed*) (*OldName:new PV;Cycle:2;*)
		rTB_PermValue10 : REAL; (*spare permanent value for testbench- replace with new vars of same lenght, when needed*) (*OldName:new PV;Cycle:2;*)
	END_STRUCT;
	OpMode_Switches : 	STRUCT 
		iIdx_OMS_Hw : INT; (* index of hardware operation mode selector switch *)
		iIdx_RMS_Hw : INT; (* index of hardware request mode selector switch *)
		iIdx_SyOMS_Hw : INT; (* index of hardware synchronisation operation mode selector switch *)
		bGoodQual : BOOL; (* Global GoodQual Bit for all 3 hw-switches *)
	END_STRUCT;
	GCB2VIS_Struct : 	STRUCT 
		bEna : BOOL; (* X20CS1030_xxx_xx_GCB was found*)
		rSave : REAL; (* Save process*)
		rLoad : REAL; (* Load process*)
		iState : UINT; (* Current State of Statemachine*)
		iError : UINT; (* Error numbers from Modbus*)
		iType : INT; (* Types: 1 = ABB EMax, 2 = Schneider MTZ *)
		iNumOp : DINT; (* Number of GCB operations *)
		iNumPT : DINT; (* Number of GCB protection trips *)
		bClosed : BOOL; (* TRUE = GCB is closed *)
		bFail : BOOL; (* TRUE = GCB failure *)
		bRacked : BOOL; (* TRUE = GCB is racked in *)
		rU_Nom : REAL; (* [V] Nominal Voltage *)
		rI_Nom : REAL; (* [A] Nominal Current *)
		rU_Act : REAL; (* [V] Actual Voltage *)
		rI_Act_L1 : REAL; (* [A] Actual Current L1 *)
		rI_Act_L2 : REAL; (* [A] Actual Current L2 *)
		rI_Act_L3 : REAL; (* [A] Actual Current L3 *)
		rWear : REAL; (* [0-1] contact wear of GCB *)
	END_STRUCT;
	VIS2GCB_Struct : 	STRUCT 
		bLoad : BOOL; (* TRUE = Load parameters from GCB *)
		bSave : BOOL; (* TRUE = Save parameters to GCB *)
		bCalc : BOOL; (* TRUE = Calc parameters from I_Nom *)
		rI_GenNom : REAL; (* [A] Nominal Generator Current *)
		rt1 : REAL; (* [s] Short circuit protection delay t1 / tr *)
		rt2 : REAL; (* [s] Overload protection delay t2 / tsd *)
		rI1 : REAL; (* [A] Overload protection current I1 / Ir *)
		rI2 : REAL; (* [A] Short circuit protection delayed current I2 / Isd *)
		rI3 : REAL; (* [A] short circuit protection instantaneous I3 / Ii *)
	END_STRUCT;
END_TYPE
