(*******************************************************************************
CUSTOMIZED: c_spare 			customized task placeholder

This code is confidential and proprietary to the INNIO Company.
It may not be used in any form, or reproduced in any manner,
without written permission of the INNIO Company.
Copyright, INNIO Company, 2019

Customized modifications: -
------------------------
 
History:
-------
V3.90.0	17-10-2012 Zengerer   new	
V4.02.0 24.06.2015 Zengerer   cleanup, init

Instructions for use:
--------------------
USE THIS TASK TO ADD CODE SNIPPETS AFTER ENGINE DELIVERY

Outstandings:
------------

*******************************************************************************)
PROGRAM _CYCLIC	
	
	(*insert your code here*)

	(*-----------------------------------------------------------------------------*)
	bDoNothing; 
	(*-----------------------------------------------------------------------------*)	
END_PROGRAM