(********************************************************************
 * COPYRIGHT -- INNIO Company
 ********************************************************************
 * Program: mainsf
 * File: mainsfInit.st
 * Author: 105035758
 * Created: August 24, 2016
 ********************************************************************
 * Implementation of program mainsf
 ********************************************************************)

PROGRAM _INIT


(* TODO : Add your code here *)


END_PROGRAM

