
TYPE
	PROGRAMMER_INFO : 	STRUCT 
		DO_NOT_SORT_PARA : STRING[40] := 'DO NOT CHANGE PARAMETER SORTING!'; (*DO NOT CHANGE PARAMETER SORTING!*) (*ADD NEW PARAMETER ONLY AT THE END OF THE Para STRUCTURE. DO NOT DELETE existing Para items.*)
	END_STRUCT;
	Para_Vent : 	STRUCT 
		tCtr_ER : _tGeACtrPara; (*Para controller engine room temperature*) (*OldName:REG12; Cycle:5;*)
		bCtr_ER : BOOL; (*PARA [12245]: engine room ventilation controller enable*) (*OldName:bPlantCtr12; Cycle:5;*)
		bAuxER_Vent_Visible : BOOL; (*PARA [12244]: auxiliaries engine room ventilation visible*) (*OldName:bAuxilAirVent; Cycle:5;*)
		iEng_Motortype : INT; (*Para motortype*) (*OldName:motortyp; Cycle:5;*)
		bVISA : BOOL; (*PARA [12259]: monitoring according VISA*) (*OldName:newPv; Cycle:5;*)
		bLouvers : BOOL; (*PARA [12253]: engine room ventilation with louvers*) (*OldName:newPv; Cycle:5;*)
		bER_VentColdCountryMode : BOOL; (*PARA [12246]: engine room VE cold country mode*) (*OldName:newPv; Cycle:5;*)
		rT_CtrER_WexStop : REAL; (*PARA [12272]: engine room temperature controller external setpoint stop*) (*OldName:W2_RTMREG; Cycle:5;*)
		rT_CtrER_WexRun : REAL; (*PARA [12271]: engine room temperature controller external setpoint run*) (*OldName:Wex_RTMREG; Cycle:5;*)
		tiPurgeTimeMax : TIME; (*PARA [12296]: purge time maximum (room vent. before start without feedback)*) (*OldName:PurgeTimeMax; Cycle:5;*)
		bPurgecycle_Active : BOOL; (*PARA [12256]: purge cycle enable *) (*OldName:bPurgecycle; Cycle:5;*)
		bOutAirER_Lou1_visible : BOOL; (*PARA [12254]: outlet air engine room louver 1 visible*) (*OldName:bAirOutLou; Cycle:5;*)
		bInAirER_Lou2_visible : BOOL; (*PARA [12252]: intake air engine room louver 2 visible*) (*OldName:bAirInLou2; Cycle:5;*)
		bInAirER_Lou1_visible : BOOL; (*PARA [12251]: intake air engine room louver 1 visible*) (*OldName:bAirInLou1; Cycle:5;*)
		bInAirER_Fan2_visible : BOOL; (*PARA [12250]: intake air engine room fan 2 visible*) (*OldName:bAirInVent2; Cycle:5;*)
		bInAirER_Fan1_visible : BOOL; (*PARA [12249]: intake air engine room fan 1 visible*) (*OldName:bAirInVent1; Cycle:5;*)
		bInAirER_Fan_FU : BOOL; (*PARA [12248]: intake air engine room fan with frequency controller*) (*OldName:bAirInVentF; Cycle:5;*)
		rT_InAirER_LimHi : REAL; (*PARA [12274]: intake air engine room temperature limit high*) (*OldName:ssIATempMax; Cycle:5;*)
		rT_AirER_HyHi4 : REAL; (*PARA [12265]: air engine room temperature limit high 4 hysteresis*) (*OldName:HY_RTM_4; Cycle:5;*)
		rT_AirER_HyHi3 : REAL; (*PARA [12264]: air engine room temperature limit high 3 hysteresis*) (*OldName:HY_RTM_3; Cycle:5;*)
		rT_AirER_HyHi2 : REAL; (*PARA [12263]: air engine room temperature limit high 2 hysteresis*) (*OldName:HY_RTM_2; Cycle:5;*)
		rT_AirER_HyHi1 : REAL; (*PARA [12262]: air engine room temperature limit high 1 hysteresis*) (*OldName:HY_RTM_1; Cycle:5;*)
		rT_AirER_HyHi : REAL; (*PARA [12261]: air engine room temperature limit high hysteresis*) (*OldName:HY_RTM; Cycle:5;*)
		rT_Fan_InAirER_HyHi : REAL; (*PARA [12273]: intake air engine room temperature limit demand fan hysteresis*) (*OldName:HY_ASLT_V; Cycle:5;*)
		rT_Lou_InAirER_HyHi : REAL; (*PARA [12277]: intake air engine room temperature limit demand open louvers hysteresis*) (*OldName:HY_ASLT_J; Cycle:5;*)
		rT_AirER_LimHi4 : REAL; (*PARA [12270]: air engine room temperature limit high 4*) (*OldName:GW_RTM_4; Cycle:5;*)
		rT_AirER_LimHi3 : REAL; (*PARA [12269]: air engine room temperature limit high 3*) (*OldName:GW_RTM_3; Cycle:5;*)
		rT_AirER_LimHi2 : REAL; (*PARA [12268]: air engine room temperature limit high 2*) (*OldName:GW_RTM_2; Cycle:5;*)
		rT_AirER_LimHi1 : REAL; (*PARA [12267]: air engine room temperature limit high 1*) (*OldName:GW_RTM_1; Cycle:5;*)
		rT_AirER_LimHi : REAL; (*PARA [12266]: air engine room temperature limit high *) (*OldName:GW_RTM; Cycle:5;*)
		rT_InAirER_LimHi_Fan : REAL; (*PARA [12275]: intake air engine room temperature limit demand fan *) (*OldName:GW_ASLT_V; Cycle:5;*)
		rT_InAirER_LimHi_Lou : REAL; (*PARA [12276]: intake air engine room temperature limit demand open louvers *) (*OldName:GW_ASLT_J; Cycle:5;*)
		bPred_T_InAirER_Active : BOOL; (*PARA [12255]: intake air engine room temperature power reduction active*) (*OldName:bIATempRed; Cycle:5;*)
		rT_Pred_InAirER_Start : REAL; (*PARA [12280]: intake air engine room temperature power reduction start [°C]*) (*OldName:ssIATempRedStart; Cycle:5;*)
		rT_Pred_InAirER_Rate : REAL; (*PARA [12278]: intake air engine room temperature power reduction rate [%Pnom/°C]*) (*OldName:ssIATempRedRate; Cycle:5;*)
		rT_Pred_InAirER_Start2 : REAL; (*PARA [12281]: intake air engine room temperature power reduction start 2 [°C]*) (*OldName:ssIATempRedStart2; Cycle:5;*)
		rT_Pred_InAirER_Rate2 : REAL; (*PARA [12279]: intake air engine room temperature power reduction rate 2 [%Pnom/°C]*) (*OldName:ssIATempRedRate2; Cycle:5;*)
		bT_AirER_Active : BOOL; (*PARA [12257]: intake air engine room temperature measuremnet enable *) (*OldName:bRoomTemp; Cycle:5;*)
		bT_InAirER_Active : BOOL; (*PARA [12258]: intake air engine room temperature measurement enable *) (*OldName:bIATempAct; Cycle:5;*)
		rP_Dev_LimHi : REAL; (*PARA [12260]: power deviation (actual value/reduced set value) limit high [%/P_nom]*) (*OldName:Z_GW_PDIFF; Cycle:5;*)
		tiP_Dev_LimHi_Delay : TIME; (*PARA [12295]: power deviation (actual value/reduced set value) high, delay time*) (*OldName:T99; Cycle:5;*)
		bERV_AirFlowMon_Active : BOOL; (*PARA [12247]: eng.room vent.air flow monitoring active*) (*OldName:bERV_AirFlowMon_Active; Cycle:5;*)
		rN_EngStart_HyHi : REAL; (*PARA [11295]: speed engine start limit high hysteresis *) (*OldName:HY_DREHZ; Cycle:5*)
		rN_EngStart_LimHi : REAL; (*PARA [11296]: speed engine start limit high *) (*OldName:GW_DREHZ; Cycle:5*)
		bCtr_InlLou : BOOL; (*PARA [13068]: air inlet louver controller enable*) (*OldName:newPv; Cycle:5;*) (*STM*)
		bCtr_OutlLou_RT : BOOL; (*PARA [13078]: air outlet louver controller for room temperature enable*) (*OldName:newPv; Cycle:5;*) (*STM 2*)
		bCtr_OutlLou_RDP : BOOL; (*PARA [13262]: air outlet louver controller for room differential pressure enable*) (*OldName:newPv; Cycle:5;*) (*STM 2*)
		bCtr_CircLou : BOOL; (*PARA [13116]: air circulation louver controller enable*) (*OldName:newPv; Cycle:5;*) (*STM*)
		bPos_InlLou1_Active : BOOL; (*PARA [13069]: air inlet louver 1 position measuring enable*) (*OldName:newPv; Cycle:5;*) (*STM*)
		bPos_InlLou2_Active : BOOL; (*PARA [13072]: air inlet louver 2 position measuring enable*) (*OldName:newPv; Cycle:5;*) (*STM*)
		bPos_OutlLou1_Active : BOOL; (*PARA [13079]: air outlet louver 1 position measuring enable*) (*OldName:newPv; Cycle:5;*) (*STM*)
		bPos_OutlLou2_Active : BOOL; (*PARA [13084]: air outlet louver 2 position measuring enable*) (*OldName:newPv; Cycle:5;*) (*STM*)
		bPos_CircLou1_Active : BOOL; (*PARA [13138]: air circulation louver 1 position measuring enable*) (*OldName:newPv; Cycle:5;*) (*STM*)
		bPos_CircLou2_Active : BOOL; (*PARA [13143]: air circulation louver 2 position measuring enable*) (*OldName:newPv; Cycle:5;*) (*STM*)
		bInlVent_Ctr_InlLou_Active : BOOL; (*PARA [13075]: room ventilation with controllable inlet louver active*) (*OldName:newPv; Cycle:5;*) (*STM*)
		bOutlVent_Ctr_OutlLou_Active : BOOL; (*PARA [13088]: room ventilation with controllable out louver active*) (*OldName:newPv; Cycle:5;*) (*STM*)
		rPosLim_InlLou_Rel_FC_ER : REAL; (*PARA [13076]: minimal air inlet louver(s) position for release frequency converter room ventilation (FG_FU)*) (*OldName:newPv; Cycle:5;*) (*STM*)
		rPosLim_InlLou_Rel_FC_ER_Hy : REAL; (*PARA [13077]: minimal air inlet louver(s) position for release frequency converter room ventilation (FG_FU) hysteresis*) (*OldName:newPv; Cycle:5;*) (*STM*)
		tCtr_InlLou : _tGeACtrPara; (*Para controller air inlet louvers (for engine room temperature)*) (*OldName:newPv; Cycle:5;*) (*STM*)
		tCtr_OutlLou_RT : _tGeACtrPara; (*Para controller air outlet louvers (for engine room temperature)*) (*OldName:newPv; Cycle:5;*) (*STM 2*)
		tCtr_OutlLou_RDP : _tGeACtrPara; (*Para controller air outlet louvers (for engine room diffential pressure)*) (*OldName:newPv; Cycle:5;*) (*STM 2*)
		tCtr_CircLou : _tGeACtrPara; (*Para controller air circulation louvers (for engine intake air temperature)*) (*OldName:newPv; Cycle:5;*) (*STM*)
		bPrDiff_ER_Active : BOOL; (*PARA [13085]: engine room difference pressure enable*) (*OldName:newPv; Cycle:5;*) (*STM 2*)
		rPosLim_OutlLou_Rel_FC_ER : REAL; (*PARA [13089]: minimal air outlet louver(s) position for release frequency converter room ventilation (FG_FU)*) (*OldName:newPv; Cycle:5;*) (*STM*)
		rPosLim_OutlLou_Rel_FC_ER_Hy : REAL; (*PARA [13090]: minimal air outlet louver(s) position for release frequency converter room ventilation (FG_FU) hysteresis*) (*OldName:newPv; Cycle:5;*) (*STM*)
		rPrDiff_ER_Lim_High : REAL; (*PARA [13091]: limit high engine room differece pressure*) (*OldName:newPv; Cycle:5;*) (*STM 2*)
		rPrDiff_ER_Lim_High_Hy : REAL; (*PARA [13092]: limit high engine room difference pressure hysteresis*) (*OldName:newPv; Cycle:5;*) (*STM 2*)
		rPrDiff_ER_Lim_Low : REAL; (*PARA [13093]: limit low engine room differece pressure*) (*OldName:newPv; Cycle:5;*) (*STM 2*)
		rPrDiff_ER_Lim_Low_Hy : REAL; (*PARA [13094]: limit low engine room difference pressure hysteresis*) (*OldName:newPv; Cycle:5;*) (*STM 2*)
		rT_InAirER_Rel_CircOp : REAL; (*PARA [13144]: limit low engine intake air temperature for circulating operation release*) (*OldName:newPv; Cycle:5;*) (*STM*)
		rT_InAirER_Rel_CircOp_Hy : REAL; (*PARA [13145]: limit low engine intake air temperature for circulating operation release hysteresis*) (*OldName:newPv; Cycle:5;*) (*STM*)
		iTypeCtr_InlLou_ERV : INT; (*PARA [13817]: type control inlet louver(s)*) (*OldName:newPv; Cycle:5;*)
		iTypeCtr_OutlLou_ERV : INT; (*PARA [13818]: type control outlet louver(s)*) (*OldName:newPv; Cycle:5;*)
		iTypeFeedback_InlLou_ERV : INT; (*PARA [13819]: type feedback inlet louver(s)*) (*OldName:newPv; Cycle:5;*)
		iTypeFeedback_OutlLou_ERV : INT; (*PARA [13820]: type feedback outlet louver(s)*) (*OldName:newPv; Cycle:5;*)
		rPosLim_InlLou_Rel_ERV : REAL; (*PARA [13821]: minimal air inlet louver(s) position for release frequency converter room ventilation (FG_FU)*) (*OldName:newPv; Cycle:5;*)
		rPosLim_InlLou_Rel_ERV_Hy : REAL; (*PARA [13822]: minimal air inlet louver(s) position for release frequency converter room ventilation (FG_FU) hysteresis*) (*OldName:newPv; Cycle:5;*)
		rPosLim_OutlLou_Rel_ERV : REAL; (*PARA [13823]: minimal air outlet louver(s) position for release frequency converter room ventilation (FG_FU)*) (*OldName:newPv; Cycle:5;*)
		rPosLim_OutlLou_Rel_ERV_Hy : REAL; (*PARA [13824]: minimal air outlet louver(s) position for release frequency converter room ventilation (FG_FU) hysteresis*) (*OldName:newPv; Cycle:5;*)
		tCtr_OutlVE_RT : _tGeACtrPara; (*Para controller air outlet ventilation (for engine room temperature)*) (*OldName:newPv; Cycle:5;*) (*STM 2*)
		bCtr_OutlVE_RT : BOOL; (*PARA [13540]: air outlet ventilation controller for room temperature enable*)
		tCtr_OutlVE_RDP : _tGeACtrPara; (*Para controller air outlet ventilation (for engine room differential pressure)*) (*OldName:newPv; Cycle:5;*) (*STM 2*)
		bCtr_OutlVE_RDP : BOOL; (*PARA [13563]: air outlet ventilation controller for room differential pressure enable*)
		rVent_SpeedDif : REAL; (*PARA [13586]: speed difference [%] air inlet ventilation to air outlet ventilation in case of MSF engine room differential pressure*)
		bOutAirER_Fan_FU : BOOL; (*PARA [13541]: outlet air engine room fan with frequency controller*) (*OldName:newPv; Cycle:5;*)
		bCtr_RDP_OutlVE_Dep_InlVent : BOOL; (*PARA [13846]: activation ctr room differential pressure with outlet ventilation depending on ctr-signal inlet ventilation*)
		rScal_CtrInlVentER_Set_Min : REAL; (*PARA [13848]: minimal ctr-signal (speed-setpoint %) for room temperature-ctr inlet ventilation*)
		rScal_CtrInlVentER_Set_Max : REAL; (*PARA [13849]: maximal ctr-signal (speed-setpoint %) for room temperature-ctr inlet ventilation*)
		rScal_OffSetMin_CtrOutlVent : REAL; (*PARA [13850]: minimal offset (speed-setpoint %) for ctr outlet ventilation depending on ctr-signal inlet ventilation*)
		rScal_OffSetMax_CtrOutlVent : REAL; (*PARA [13851]: maximal offset (speed-setpoint %) for ctr outlet ventilation depending on ctr-signal inlet ventilation*)
		bCtr_RDP_OutlVE_Dep_EngP : BOOL; (*PARA [13847]: activation ctr room differential pressure with outlet ventilation depending on actual engine power*)
		rScal_PminEl : REAL; (*PARA [13852]: minimal engine power (%)  for load-related outlet ventilation control*)
		rScal_PmaxEl : REAL; (*PARA [13853]: maximal engine power (%)  for load-related outlet ventilation control*)
		rScal_OffSetMin_Pel : REAL; (*PARA [13854]: minimal offset (speed-setpoint %) for ctr outlet ventilation depending on acutal engine power*)
		rScal_OffSetMax_Pel : REAL; (*PARA [13855]: maximal offset (speed-setpoint %) for ctr outlet ventilation depending on ctr-signal inlet ventilation*)
		bFireProtFlap1_InlAir_visible : BOOL; (*PARA [13610]: fire protection flap 1 inlet air visible *) (*OldName:newPv; Cycle:5;*)
		bFireProtFlap2_InlAir_visible : BOOL; (*PARA [13611]: fire protection flap 2 inlet air visible *) (*OldName:newPv; Cycle:5;*)
		bFireProtFlap1_OutlAir_visible : BOOL; (*PARA [13612]: fire protection flap 1 outlet air visible *) (*OldName:newPv; Cycle:5;*)
		bFireProtFlap2_OutlAir_visible : BOOL; (*PARA [13613]: fire protection flap 2 outlet air visible *) (*OldName:newPv; Cycle:5;*)
		bBOP_ERVent_Act : BOOL; (*PARA [13836]: -Visu: Plant display room ventilation active*) (*OldName:newPv; Cycle:5;*)
		rT_ACP_AirER_sp : REAL; (*PARA [13987]: Active cooling program setpoint temperature engine room ventilation *)
		rT_AirER_LimWr : REAL; (*PARA [15064]: Room Temperature Warning*)
		bSafe_ERV_Cust_Active : BOOL; (*PARA [15188]: Customer room ventilation - Monitoring active*) (*SAFETY PLC; Cycle: 5;*) (*V04.25.00.00*)
	END_STRUCT;
END_TYPE
