
TYPE
	IN_Vent : 	STRUCT 
		tAB2VE : AmmBase2MM;
		tPB2MM : ParaBase2MM_type;
		tERV_Op : HALioDi_Type; (*DI engine room ventilation operating/air flow ok*) (*OldName:DI_ERV_Op; Cycle:5;*)
		tERV_InlAir_Op : HALioDi_Type; (*DI engine room ventilation inlet-air operating/air flow ok*) (*OldName:newPv; Cycle:5;*)
		tERV_OutlAir_Op : HALioDi_Type; (*DI engine room ventilation outlet-air operating/air flow ok*) (*OldName:newPv; Cycle:5;*)
		tT_AirER_Ext_Hi1 : HALioDi_Type; (*DI room temperature limit *) (*OldName:RTM_25; Cycle:5;*)
		tT_AirER_Ext_Hi : HALioDi_Type; (*DI air engine room temperature external high*) (*OldName:RTM; Cycle:5;*)
		tT_AirER_Ext_Hi3 : HALioDi_Type; (*DI room temperature limit*) (*OldName:RTM_35; Cycle:5;*)
		tT_AirER_Ext_Hi2 : HALioDi_Type; (*DI room temperature limit*) (*OldName:RTM_30; Cycle:5;*)
		tER_Ext_Err : HALioDi_Type; (*DI engine room VE failure *) (*OldName:ST_RLV; Cycle:5;*)
		tER_InlAir_Ext_Err : HALioDi_Type; (*DI engine room inlet air VE failure *) (*OldName:ST_RLV; Cycle:5;*)
		tER_OutlAir_Ext_Err : HALioDi_Type; (*DI engine room outlet air VE failure *) (*OldName:ST_RLV; Cycle:5;*)
		tAirER_FS : HALioDi_Type; (*DI engine room VE flow switch*) (*OldName:DI_ERVent_FS; Cycle:5;*)
		tRel_ER_PurgeCycle : HALioDi_Type; (*DI release purge cycle*) (*OldName:DI_Rel_PurgeC; Cycle:5;*)
		tInAirER_Lou1Opened : HALioDi_Type; (*DI intake air engine room louver 1 open*) (*OldName:ZJAL1_O; Cycle:5;*)
		tInAirER_Lou2Opened : HALioDi_Type; (*DI intake air engine room louver 2 open*) (*OldName:ZJAL2_O; Cycle:5;*)
		tOutAirER_LouOpened : HALioDi_Type; (*DI outlet air engine room louver open*) (*OldName:AJAL_O; Cycle:5;*)
		tAuxV_Aux_ok : HALioDi_Type; (*DI auxiliary voltage supply ok Auxiliaries panel*) (*OldName:SPG_HBT; Cycle:5;*)
		tAuxV_ModIf_ok : HALioDi_Type; (*DI auxiliary voltage supply ok Module interface*) (*OldName:SPG_HBT; Cycle:5;*)
		tAuxV_Supply_Ok : HALioDi_Type; (*DI auxiliary voltage supply ok*) (*OldName:SPG_HBT; Cycle:5;*)
		tGCB_On : HALioDi_Type; (*DI generator circuit breaker closed*) (*OldName:GCB_ON; Cycle:5;*)
		rT_Ch_T1LP_Avg : REAL; (*average charge temperature before low-pressure turbocharger (= engine intake air) [°C]*) (*OldName:ssIATemp,ANA_ZLTP,tT_InAirER; Cycle:5;*) (* V04.04.00.00 *)
		bAMM_T_Ch_T1LP_Avg : BOOL; (*collective warning - average charge temp. before low-pressure TC (= engine intake air)*) (* V04.04.00.00 *)
		tT_AirER : HALioAi_Type; (*AI air engine room temperature [C]*) (*OldName:ANA_RTM; Cycle:5;*)
		rT_AirER_Customized : REAL; (*air engine room temperature customized [C]*) (*OldName:newPv; Cycle:5;*)
		tEng_Run : HALioDo_Type; (*Engine in operation*) (*OldName:M_BTRB; Cycle:5;*)
		tPos_InlLou1 : HALioAi_Type; (*AI position air inlet louver 1 [%]*) (*OldName:newPv; Cycle:5;*) (*STM*)
		tPos_InlLou2 : HALioAi_Type; (*AI position air inlet louver 2 [%]*) (*OldName:newPv; Cycle:5;*) (*STM*)
		rPos_InlLou1 : REAL; (*position air inlet louver 1 [%]*) (*OldName:newPv; Cycle:5;*) (*STM*)
		rPos_InlLou2 : REAL; (*position air inlet louver 2 [%]*) (*OldName:newPv; Cycle:5;*) (*STM*)
		tPos_OutlLou1 : HALioAi_Type; (*AI position air outlet louver 1 [%]*) (*OldName:newPv; Cycle:5;*) (*STM*)
		tPos_OutlLou2 : HALioAi_Type; (*AI position air outlet louver 2 [%]*) (*OldName:newPv; Cycle:5;*) (*STM*)
		rPos_OutlLou1 : REAL; (*position air outlet louver 1 [%]*) (*OldName:newPv; Cycle:5;*) (*STM*)
		rPos_OutlLou2 : REAL; (*position air outlet louver 2 [%]*) (*OldName:newPv; Cycle:5;*) (*STM*)
		tPos_CircLou1 : HALioAi_Type; (*AI position air circulation louver 1 [%]*) (*OldName:newPv; Cycle:5;*) (*STM*)
		tPos_CircLou2 : HALioAi_Type; (*AI position air circulation louver 2 [%]*) (*OldName:newPv; Cycle:5;*) (*STM*)
		rPos_CircLou1 : REAL; (*position air circulation louver 1 [%]*) (*OldName:newPv; Cycle:5;*) (*STM*)
		rPos_CircLou2 : REAL; (*position air circulation louver 2 [%]*) (*OldName:newPv; Cycle:5;*) (*STM*)
		tPrDiff_ER : HALioAi_Type; (*AI engine room difference pressure [mbar]*) (*OldName:newPv; Cycle:5;*) (*STM 2*)
		rPrDiff_ER : REAL; (*engine room difference pressure [mbar]*) (*OldName:newPv; Cycle:5;*) (*STM 2*)
		bMsg1031 : BOOL; (*Alarm 1031 Emergency stop*) (*OldName:M_SIS; Cycle:5;*)
		bMsg1052 : BOOL; (*Alarm 1052 gas prealarm*) (*OldName:M_GALV; Cycle:5;*)
		bMsg1053 : BOOL; (*Alarm 1053 Gas Alarm*) (*OldName:M_GAL; Cycle:5;*)
		bMsg1054 : BOOL; (*Alarm 1054 Fire alarm*) (*OldName:M_BAL; Cycle:5;*)
		bMsg3003 : BOOL; (*3003 Measurement signal disturbance*) (*OldName:M_MS; Cycle:5;*)
		bEng_Aux_Dem_CDR : BOOL; (*engine auxiliaries demand with cool down run*) (*OldName:ANFHBT; Cycle:5;*)
		bEng_Dem_EPS : BOOL; (*Engine demand for emergency operation*) (*OldName:M_NANF; Cycle:5;*)
		bOnly_Island : BOOL; (*only island operation*) (*OldName:REIN_INSEL; Cycle:5;*)
		bRel_ScavN2 : BOOL; (*conditions for scavenge with N2*) (*OldName:FG_N2; Cycle:5;*)
		iSt_OpMode : UDINT; (*engine operating mode*) (*OldName:newPv; Cycle:5;*)
		bEng_Dem : BOOL; (*module demanded*) (*OldName:M_AGFD; Cycle:5;*)
		bGV_On : BOOL; (*command open gas valves*) (*OldName:M_GASV; Cycle:5;*)
		bEng_Aux_Dem : BOOL; (*engine auxiliaries demand*) (*OldName:M_ANFHBT; Cycle:5;*)
		iIdx_OMSS : INT; (*engine operating mode selection*) (*OldName:newPv; Cycle:5;*)
		bInAirER_FanSet100 : BOOL; (*demand engine room fan 100% speed*) (*OldName:LUE100; Cycle:5;*)
		rP_Act_Norm_Filt : REAL; (*Actual power related to rP_Nom filtered T=1s [%/P_Nom]*) (*OldName:P_IST; Cycle:5;*)
		rN_EngAct : REAL; (* engine speed actual [1/min] *) (*OldName:n_ist; Cycle:5*)
		tER_DoorClosed : HALioDi_Type; (*DI engine room doors closed*) (*OldName:DI_ER_DoorClosed; Cycle:5;*)
		rCust_SparePara : ARRAY[0..200]OF REAL; (*SPS_REZP1 to SPS_REZP200	*) (* OldName: SPS_REZP1, SPS_REZP2, SPS_REZP70; Cycle: 5; *)
		tCustAnaIn : ARRAY[0..120]OF HALioAi_Type; (*Replacement for RAN_KANAL...*) (*OldName: ANA_RAN	; Cycle: 5;*)
		tCustDigIn : ARRAY[0..200]OF HALioDi_Type; (*new, reserved for Project specific use*) (*OldName: new PV	; Cycle: 5;*)
		tManAuxCtr : tManAuxCtr_typ; (*Manual operating auxiliaries control - Handbedienebene*) (*OldName: new PV; Cycle: 5;*)
		tDPr_InAirFiltERV_Hi : HALioDi_Type; (*air inlet filter difference pressure high - engine room ventilation*) (*OldName: E_FILTER; Cycle: 5;*)
		tFireProtFlap1_InlAir_Closed : HALioDi_Type; (*fireprotectionflap 1 inlet-air closed*) (*OldName:newPv; Cycle:5;*)
		tFireProtFlap2_InlAir_Closed : HALioDi_Type; (*fireprotectionflap 2 inlet-air closed*) (*OldName:newPv; Cycle:5;*)
		tFireProtFlap1_InlAir_Opened : HALioDi_Type; (*fireprotectionflap 1 inlet-air opened*) (*OldName:newPv; Cycle:5;*)
		tFireProtFlap2_InlAir_Opened : HALioDi_Type; (*fireprotectionflap 2 inlet-air opened*) (*OldName:newPv; Cycle:5;*)
		tFireProtFlap1_OutlAir_Closed : HALioDi_Type; (*fireprotectionflap 1 outlet-air closed*) (*OldName:newPv; Cycle:5;*)
		tFireProtFlap2_OutlAir_Closed : HALioDi_Type; (*fireprotectionflap 2 outlet-air closed*) (*OldName:newPv; Cycle:5;*)
		tFireProtFlap1_OutlAir_Opened : HALioDi_Type; (*fireprotectionflap 1 outlet-air opened*) (*OldName:newPv; Cycle:5;*)
		tFireProtFlap2_OutlAir_Opened : HALioDi_Type; (*fireprotectionflap 2 outlet-air opened*) (*OldName:newPv; Cycle:5;*)
		bFS_Act : BOOL; (*FastStart activated (enabled and required from customer)*) (*Oldname:new PV, Cycle:5*)
		bACP_AirER_Dem : BOOL; (* Active Cooling Program Room Air Ventilation demanded *) (*OldName:newPv; Cycle:5;*)
		tInAirER_Lou1Closed : HALioDi_Type; (*DI intake air engine room louver 1 Closed*)
		tInAirER_Lou2Closed : HALioDi_Type; (*DI intake air engine room louver 2 Closed*)
		tOutAirER_LouClosed : HALioDi_Type; (*DI outlet air engine room louver Closed*)
		bInLouDemIgn : BOOL; (*Inlet louver demand for ignition selftest*)
		bInLouDemEX : BOOL; (*Inlet louver demand for scavenging*)
		bInLouDemAG : BOOL; (*Inlet louver demand for purge cranking cycle for fast start*)
		bERV_PC_Forced : BOOL; (*SAFETY PLC: Force ERV safety plausibility checks*)
		bSafetyPLC_Active : BOOL; (*SAFETY PLC: SafetyPLC is active*) (*OldName: new PV; Cycle: 5;*)
	END_STRUCT;
	OUT_Vent : 	STRUCT 
		tVE2AB : MM2AmmBase;
		tVE2PB : MM2ParaBase_type;
		tRel_ER_Fan : HALioDo_Type; (*DO demand VE > min. speed*) (*OldName:FG_LUE; Cycle:5;*)
		tSet_ER_Fan_Min : HALioDo_Type; (*DO demand VE min. speed*) (*OldName:LUE_MIN; Cycle:5;*)
		tDemPurgeER : HALioDo_Type; (*DO demand room VE for purge cycle*) (*OldName:DO_DmndPurge; Cycle:5;*)
		tRel_ER_FC : HALioDo_Type; (*DO release frequency converter for room VE*) (*OldName:FG_FU; Cycle:5;*)
		tInAirER_Fan1DemOn : HALioDo_Type; (*DO demand air inlet ventilator 1*) (*OldName:ZLVST_1; Cycle:5;*)
		tInAirER_Fan2DemOn : HALioDo_Type; (*DO demand air inlet ventilator 2*) (*OldName:ZLVST_2; Cycle:5;*)
		tOutAirER_LouDemOpen : HALioDo_Type; (*DO demand open air outlet louver *) (*OldName:A_AJAL; Cycle:5;*)
		tInAirER_Lou2DemOpen : HALioDo_Type; (*DO demand open air inlet louver 2*) (*OldName:A_ZJAL2; Cycle:5;*)
		tInAirER_Lou1DemOpen : HALioDo_Type; (*DO demand open air inlet louver 1*) (*OldName:A_ZJAL1; Cycle:5;*)
		tCtr_InlLou_Set : HALioAo_Type; (*AO inlet-air louver setpoint*) (*OldName:newPv; Cycle:5;*) (*STM*)
		tCtr_OutlLou_RT_Set : HALioAo_Type; (*AO outlet-air louver setpoint regarding engine room temperature*) (*OldName:newPv; Cycle:5;*) (*STM 2*)
		tCtr_OutlLou_RDP_Set : HALioAo_Type; (*AO outlet-air louver setpoint regarding engine room differential pressure*) (*OldName:newPv; Cycle:5;*) (*STM 2*)
		tCtr_CircLou_Set : HALioAo_Type; (*AO circulation-air louver setpoint*) (*OldName:newPv; Cycle:5;*) (*STM*)
		tER_FC_Set : HALioAo_Type; (*AO engine room frequency converter setpoint [%]*) (*OldName:REG12_y; Cycle:5;*)
		bMsg2295 : BOOL; (*engine room ventilation failure inlet air*) (*OldName:newPv; Cycle:5;*)
		bMsg2296 : BOOL; (*engine room ventilation failure outlet air*) (*OldName:newPv; Cycle:5;*)
		bMsg2701 : BOOL; (*position air inlet louver 1 signal failure*) (*OldName:newPv; Cycle:5;*) (*STM*)
		bMsg2702 : BOOL; (*position air inlet louver 2 signal failure*) (*OldName:newPv; Cycle:5;*) (*STM*)
		bMsg2703 : BOOL; (*position air outlet louver 1 signal failure*) (*OldName:newPv; Cycle:5;*) (*STM*)
		bMsg2704 : BOOL; (*position air outlet louver 2 signal failure*) (*OldName:newPv; Cycle:5;*) (*STM*)
		bMsg2705 : BOOL; (*engine room difference pressure signal failure*) (*OldName:newPv; Cycle:5;*) (*STM*)
		bMsg2706 : BOOL; (*engine room difference pressure low*) (*OldName:newPv; Cycle:5;*) (*STM*)
		bMsg2707 : BOOL; (*engine room difference pressure high*) (*OldName:newPv; Cycle:5;*) (*STM*)
		bMsg2708 : BOOL; (*position air circulation louver 1 signal failure*) (*OldName:newPv; Cycle:5;*) (*STM*)
		bMsg2709 : BOOL; (*position air circulation louver 2 signal failure*) (*OldName:newPv; Cycle:5;*) (*STM*)
		bMsg2795 : BOOL; (*engine room ventilation failure inlet air*) (*OldName:newPv; Cycle:5;*)
		bMsg2796 : BOOL; (*engine room ventilation failure outlet air*) (*OldName:newPv; Cycle:5;*)
		bMsg2797 : BOOL; (*parameterization error air inlet louvers*) (*OldName:newPv; Cycle:5;*)
		bMsg2798 : BOOL; (*parameterization error air outlet louvers*) (*OldName:newPv; Cycle:5;*)
		bMsg3152 : BOOL; (*engine room temperature signal failure*) (*OldName:M_MSRTM_W; Cycle:5;*)
		bPurgeER_Rdy : BOOL; (*purge cycle ready*) (*OldName:purge_rdy; Cycle:5;*)
		rP_Red_T_InAirER_Norm : REAL; (*power reduction by engine room air inlet temperature [%]*) (*OldName:newPv; Cycle:5;*)
		tCtr_OutlVE_RT_Set : HALioAo_Type; (*AO outlet-air ventilation setpoint regarding engine room temperature*) (*OldName:newPv; Cycle:5;*)
		tCtr_OutlVE_RDP_Set : HALioAo_Type; (*AO outlet-air ventilation setpoint regarding engine room differential pressure*) (*OldName:newPv; Cycle:5;*)
		Pos_OutlLou2_OK : BOOL; (*position feedback air outlet louver 2 OK depending on parameter*)
		Pos_OutlLou1_OK : BOOL; (*position feedback air outlet louver 1 OK depending on parameter*)
		Pos_InlLou2_OK : BOOL; (*position feedback air inlet louver 2 OK depending on parameter*)
		Pos_InlLou1_OK : BOOL; (*position feedback air inlet louver 1 OK depending on parameter*)
		bERV_NotRdy : BOOL; (*engine room ventilation not ready - block engine start*)
		tInAirER_Lou1Opened : HALioDi_Type; (*DI intake air engine room louver 1 open*)
		tInAirER_Lou2Opened : HALioDi_Type; (*DI intake air engine room louver 2 open*)
		tOutAirER_LouOpened : HALioDi_Type; (*DI outlet air engine room louver open*)
		tDemERVentInLou_Cust : HALioDo_Type; (*DO inlet louvers demand for customer*)
		bInLouRelVE : BOOL; (*inlet louvers open or not closed*)
		bERV_ColdCountry : BOOL; (*SAFETY PLC: Cold country mode active for safety PLC*)
		bERV_Lou_PC_OP : BOOL; (*SAFETY PLC: Plausibility check for opening the louvres*)
		bERV_Lou_PC_CL : BOOL; (*SAFETY PLC: Plausibility check for closing the louvres*)
	END_STRUCT;
	VIS2MM_Struct : 	STRUCT 
		tCtr_InlLou_In : _tGeACtrIn; (*inlet-air louver controller (for engine room temperature)*) (*OldName:newPv; Cycle:5;*) (*STM*)
		tCtr_OutlLou_RT_In : _tGeACtrIn; (*outlet-air louver controller (for engine room temperature)*) (*OldName:newPv; Cycle:5;*) (*STM 2*)
		tCtr_OutlVE_RT_In : _tGeACtrIn; (*outlet-air ventilation controller (for engine room temperature)*) (*OldName:newPv; Cycle:5;*)
		tCtr_OutlLou_RDP_In : _tGeACtrIn; (*outlet-air louver controller (for engine room differential pressure)*) (*OldName:newPv; Cycle:5;*) (*STM 2*)
		tCtr_OutlVE_RDP_In : _tGeACtrIn; (*outlet-air ventilation controller (for engine room differential pressure)*) (*OldName:newPv; Cycle:5;*)
		tCtr_CircLou_In : _tGeACtrIn; (*circulation-air louver controller (for intake air temperature)*) (*OldName:newPv; Cycle:5;*) (*STM*)
		tCtr_ER_In : _tGeACtrIn; (*engine room temperature controller*) (*OldName:REG12; Cycle:5;*)
	END_STRUCT;
	MM2VIS_Struct : 	STRUCT 
		tCtr_InlLou_Out : _tGeACtrOut; (*inlet-air louver controller (for engine room temperature)*) (*OldName:newPv; Cycle:5;*) (*STM*)
		tCtr_OutlLou_RT_Out : _tGeACtrOut; (*outlet-air louver controller (for engine room temperature)*) (*OldName:newPv; Cycle:5;*) (*STM 2*)
		tCtr_OutlVE_RT_Out : _tGeACtrOut; (*outlet-air ventilation controller (for engine room temperature)*) (*OldName:newPv; Cycle:5;*)
		tCtr_OutlLou_RDP_Out : _tGeACtrOut; (*outlet-air louver controller (for engine room differential pressure)*) (*OldName:newPv; Cycle:5;*) (*STM 2*)
		tCtr_OutlVE_RDP_Out : _tGeACtrOut; (*outlet-air ventilation controller (for engine room differential pressure)*) (*OldName:newPv; Cycle:5;*)
		tCtr_CircLou_Out : _tGeACtrOut; (*circulation-air louver controller (for intake air temperature)*) (*OldName:newPv; Cycle:5;*) (*STM*)
		tCtr_ER_Out : _tGeACtrOut; (*engine room temperature controller*) (*OldName:REG12; Cycle:5;*)
		rCtr_OutlVE_RDP_Set : REAL; (*vis speed setpoint outlet ventilation [%]*)
		rT_AirER : REAL; (*vis air engine room temperature [°C]*) (*OldName:ANA_RTM; Cycle:5;*)
		rPrDiff_ER : REAL; (*vis engine room difference pressure [mbar]*) (*OldName:newPv; Cycle:5;*) (*STM 2*)
		rP_Red_T_InAirER_Norm : REAL; (*power reduction by engine room inlet air temperature [%]*) (*OldName:newPv; Cycle:5;*)
		rPos_InlLou1 : REAL; (*position air inlet louver 1 [%]*) (*OldName:newPv; Cycle:5;*) (*STM*)
		rPos_InlLou2 : REAL; (*position air inlet louver 2 [%]*) (*OldName:newPv; Cycle:5;*) (*STM*)
		rPos_OutlLou1 : REAL; (*position air outlet louver 1 [%]*) (*OldName:newPv; Cycle:5;*) (*STM*)
		rPos_OutlLou2 : REAL; (*position air outlet louver 2 [%]*) (*OldName:newPv; Cycle:5;*) (*STM*)
		rPos_CircLou1 : REAL; (*position air circulation louver 1 [%]*) (*OldName:newPv; Cycle:5;*) (*STM*)
		rPos_CircLou2 : REAL; (*position air circulation louver 2 [%]*) (*OldName:newPv; Cycle:5;*) (*STM*)
		bInAirER_Lou1Opened : BOOL; (*vis inlet air engine room louver 1 opened*) (*OldName:B_SV[33]; Cycle:5;*)
		bInAirER_Lou2Opened : BOOL; (*vis inlet air engine room louver 2 opened*) (*OldName:B_SV[34]; Cycle:5;*)
		bOutAirER_LouOpened : BOOL; (*vis outlet air engine room louver opened*) (*OldName:B_SV[35]; Cycle:5;*)
		bInAirER_Fan1DemOn : BOOL; (*vis demand air inlet ventilator 1*) (*OldName:B_SV[36]; Cycle:5;*)
		bInAirER_Fan2DemOn : BOOL; (*vis demand air inlet ventilator 2*) (*OldName:B_SV[37]; Cycle:5;*)
		bInAirER_FanSet100 : BOOL; (*vis demand engine room fan 100% speed*) (*OldName:LUE100; Cycle:5;*)
		bRel_ER_Fan : BOOL; (*engine room fan release*) (*OldName:FG_FU; Cycle:5;*)
		bFireProtFlap1_InlAir_Opened : BOOL; (*vis status fire protection flap 1 inlet air *) (*OldName:newPv; Cycle:5;*)
		bFireProtFlap2_InlAir_Opened : BOOL; (*vis status fire protection flap 2 inlet air *) (*OldName:newPv; Cycle:5;*)
		bFireProtFlap1_OutlAir_Opened : BOOL; (*vis status fire protection flap 1 outlet air *) (*OldName:newPv; Cycle:5;*)
		bFireProtFlap2_OutlAir_Opened : BOOL; (*vis status fire protection flap 2 outlet air *) (*OldName:newPv; Cycle:5;*)
		bCtrER_YFix : BOOL; (*demand engine room controller activation with fixed y*)
		bMsg1135 : BOOL; (*air engine room temperature high*) (*OldName:AMM_Axxxx[]; Cycle:5;*)
		bMsg1138 : BOOL; (*engine room fan failure trip*) (*OldName:AMM_Axxxx[]; Cycle:5;*)
		bMsg2120 : BOOL; (*engine room fan failure*) (*OldName:AMM_Wxxxx[]; Cycle:5;*)
		bMsg2295 : BOOL; (*engine room ventilation failure inlet air*) (*OldName:newPv; Cycle:5;*)
		bMsg2296 : BOOL; (*engine room ventilation failure outlet air*) (*OldName:newPv; Cycle:5;*)
		bMsg2630 : BOOL; (*difference pressure filter high - engine room ventilation*) (*OldName:newPv; Cycle:5;*)
		bMsg2701 : BOOL; (*position air inlet louver 1 signal failure*) (*OldName:newPv; Cycle:5;*) (*STM*)
		bMsg2702 : BOOL; (*position air inlet louver 2 signal failure*) (*OldName:newPv; Cycle:5;*) (*STM*)
		bMsg2703 : BOOL; (*position air outlet louver 1 signal failure*) (*OldName:newPv; Cycle:5;*) (*STM*)
		bMsg2704 : BOOL; (*position air outlet louver 2 signal failure*) (*OldName:newPv; Cycle:5;*) (*STM*)
		bMsg2705 : BOOL; (*engine room difference pressure signal failure*) (*OldName:newPv; Cycle:5;*) (*STM*)
		bMsg2706 : BOOL; (*engine room difference pressure low*) (*OldName:newPv; Cycle:5;*) (*STM*)
		bMsg2707 : BOOL; (*engine room difference pressure high*) (*OldName:newPv; Cycle:5;*) (*STM*)
		bMsg2708 : BOOL; (*position air circulation louver 1 signal failure*) (*OldName:newPv; Cycle:5;*) (*STM*)
		bMsg2709 : BOOL; (*position air circulation louver 2 signal failure*) (*OldName:newPv; Cycle:5;*) (*STM*)
		bMsg2795 : BOOL; (*engine room ventilation failure inlet air*) (*OldName:newPv; Cycle:5;*)
		bMsg2796 : BOOL; (*engine room ventilation failure outlet air*) (*OldName:newPv; Cycle:5;*)
		bMsg2797 : BOOL; (*parameterization error air inlet louvers*) (*OldName:newPv; Cycle:5;*)
		bMsg2798 : BOOL; (*parameterization error air outlet louvers*) (*OldName:newPv; Cycle:5;*)
		bMsg3152 : BOOL; (*engine room air temperature signal failure*) (*OldName:AMM_Wxxxx[]; Cycle:5;*)
		bMsg3223 : BOOL; (*engine room air inlet temperature signal failure*) (*OldName:AMM_Wxxxx[]; Cycle:5;*)
		bMsg3224 : BOOL; (*engine room air inlet temperature high*) (*OldName:AMM_Wxxxx[]; Cycle:5;*)
		bMsg3302 : BOOL; (*purge cycle incomplete*) (*OldName:AMM_Axxxx[]; Cycle:5;*)
		bMsg3367 : BOOL; (*engine room ventilation failure - doors*) (*OldName:AMM_Axxxx[]; Cycle:5;*)
		bMsg3571 : BOOL; (*no release start module from purge cycle*) (*OldName:AMM_Wxxxx[]; Cycle:5;*)
		bMsg2968 : BOOL; (*Air inlet louver status signal failure*)
		bMsg2969 : BOOL; (*Air outlet louver status signal failure*)
		bMsg2472 : BOOL; (*Room temperature high warning*)
		bMsg9401 : BOOL; (*Louvers failure*)
	END_STRUCT;
	tManAuxCtr_typ : 	STRUCT 
		bGnl_Rel : BOOL; (*General release. Safety conditions (gas alarm, fire alarm, safety loop, ..) are OK.*) (*OldName: new PV; Cycle: 5;*)
		bECWP_PreH_COf_Man : BOOL; (*engine cooling water pump preheating demand off*) (*OldName: new PV; Cycle: 5;*)
		bECW_PreH_COf_Man : BOOL; (*engine cooling water preheating demand off*) (*OldName: new PV; Cycle: 5;*)
		bInAirER_Lou2DemOpen_Man : BOOL; (*demand open air inlet louver 2*) (*OldName: new PV; Cycle:5;*)
		bInAirER_Lou1DemOpen_Man : BOOL; (*demand open air inlet louver 1*) (*OldName: new PV; Cycle:5;*)
		bOutAirER_LouDemOpen_Man : BOOL; (*open air outlet louver *) (*OldName: new PV; Cycle:5;*)
		bInAirER_Fan1DemOn_Man : BOOL; (*demand air inlet ventilator 1*) (*OldName: new PV; Cycle:5;*)
		bInAirER_Fan2DemOn_Man : BOOL; (*demand air inlet ventilator 2*) (*OldName: new PV; Cycle:5;*)
		bER_FC_Set_Man : BOOL; (*demand engine room frequency converter setpoint*) (*OldName: new PV; Cycle:5;*)
		rER_FC_Set_Man : REAL; (*engine room frequency converter setpoint [%]*) (*OldName: new PV; Cycle:5;*)
		bER_OutlV_FC_Set_Man : BOOL; (*demand engine room air outlet ventilation frequency converter setpoint*) (*OldName: new PV; Cycle:5;*)
		rER_OutlV_FC_Set_Man : REAL; (*engine room air outlet ventilation frequency converter setpoint [%]*) (*OldName: new PV; Cycle:5;*)
		bEC_DemPump_Man : BOOL; (*emergency cooler demand pump*) (*OldName: new PV; Cycle:5;*)
		bEC_DemFan_Man : BOOL; (*emergency cooler demand fan 1 - 16*) (*OldName: new PV; Cycle:5;*)
		bChC_DemPump_Man : BOOL; (*charge cooler demand pump*) (*OldName: new PV; Cycle:5;*)
		bChC_DemFan_Man : BOOL; (*charge cooler demand fan 1 - 16*) (*OldName: new PV; Cycle:5;*)
		bEG_BoVaCoOpen_Man : BOOL; (*exhaust gas boiler valve command open*) (*OldName: new PV; Cycle:5;*)
		bEG_BoVaCoClose_Man : BOOL; (*exhaust gas boiler valve command close*) (*OldName: new PV; Cycle:5;*)
		bEG_ByVaCoOpen_Man : BOOL; (*exhaust gas bypass valve command open*) (*OldName: new PV; Cycle:5;*)
		bEG_ByVaCoClose_Man : BOOL; (*exhaust gas bypass valve command close*) (*OldName: new PV; Cycle:5;*)
		bAuxCust_Man : ARRAY[0..40]OF BOOL; (*reserve customer auxiliaries*) (*OldName: new PV; Cycle:5;*)
		bCDP_Dem_Man : BOOL; (*demand condensor pump*) (*OldName: new PV; Cycle:5;*)
		bBHV_Dem_Man : BOOL; (*demand boiler house ventilation*) (*OldName: newPv; Cycle:5;*)
		bHWF_Dem_Man : BOOL; (*demand heating circuit flap*) (*OldName:newPv; Cycle:5;*)
		bChC_Heating_Man : BOOL; (*charge cooler pre heating*) (*OldName:newPv; Cycle:5;*)
		bCO2_DemCodinox_Man : BOOL; (*CO2 demand CODINOX*) (*OldName:newPv; Cycle:5;*)
		bECWP_PreH_COf : BOOL; (*engine cooling water pump preheating demand off*) (*OldName: new PV; Cycle: 5;*)
		bECW_PreH_COf : BOOL; (*engine cooling water preheating demand off*) (*OldName: new PV; Cycle: 5;*)
		bInAirER_Lou2DemOpen : BOOL; (*demand open air inlet louver 2*) (*OldName: new PV; Cycle:5;*)
		bInAirER_Lou1DemOpen : BOOL; (*demand open air inlet louver 1*) (*OldName: new PV; Cycle:5;*)
		bOutAirER_LouDemOpen : BOOL; (*open air outlet louver *) (*OldName: new PV; Cycle:5;*)
		bInAirER_Fan1DemOn : BOOL; (*demand air inlet ventilator 1*) (*OldName: new PV; Cycle:5;*)
		bInAirER_Fan2DemOn : BOOL; (*demand air inlet ventilator 2*) (*OldName: new PV; Cycle:5;*)
		bER_OutlV_FC_Set : BOOL; (*demand engine room air outlet ventilation frequency converter setpoint*) (*OldName: new PV; Cycle:5;*)
		rER_OutlV_FC_Set : REAL; (*engine room air outlet ventilation frequency converter setpoint [%]*) (*OldName: new PV; Cycle:5;*)
		bER_FC_Set : BOOL; (*demand engine room frequency converter setpoint*) (*OldName: new PV; Cycle:5;*)
		rER_FC_Set : REAL; (*engine room frequency converter setpoint [%]*) (*OldName: new PV; Cycle:5;*)
		bEC_DemPump : BOOL; (*emergency cooler demand pump*) (*OldName: new PV; Cycle:5;*)
		bEC_DemFan : BOOL; (*emergency cooler demand fan 1 - 16*) (*OldName: new PV; Cycle:5;*)
		bChC_DemPump : BOOL; (*charge cooler demand pump*) (*OldName: new PV; Cycle:5;*)
		bChC_DemFan : BOOL; (*charge cooler demand fan 1 - 16*) (*OldName: new PV; Cycle:5;*)
		bEG_BoVaCoOpen : BOOL; (*exhaust gas boiler valve command open*) (*OldName: new PV; Cycle:5;*)
		bEG_BoVaCoClose : BOOL; (*exhaust gas boiler valve command close*) (*OldName: new PV; Cycle:5;*)
		bEG_ByVaCoOpen : BOOL; (*exhaust gas bypass valve command open*) (*OldName: new PV; Cycle:5;*)
		bEG_ByVaCoClose : BOOL; (*exhaust gas bypass valve command close*) (*OldName: new PV; Cycle:5;*)
		bAuxCust : ARRAY[0..70]OF BOOL; (*reserve customer auxiliaries*) (*OldName: new PV; Cycle:5;*)
		bCDP_Dem : BOOL; (*demand condensor pump*) (*OldName: new PV; Cycle:5;*)
		bBHV_Dem : BOOL; (*demand boiler house ventilation*) (*OldName: newPv; Cycle:5;*)
		bHWF_Dem : BOOL; (*demand heating circuit flap*) (*OldName:newPv; Cycle:5;*)
		bChC_Heating : BOOL; (*charge cooler pre heating*) (*OldName:newPv; Cycle:5;*)
		bCO2_DemCodinox : BOOL; (*CO2 demand CODINOX*) (*OldName:newPv; Cycle:5;*)
		bChC2_DemPump : BOOL; (*charge cooler 2 demand pump*) (*OldName: new PV; Cycle:5;*)
		bChC2_DemPump_Man : BOOL; (*charge cooler 2 demand pump*) (*OldName: new PV; Cycle:5;*)
		bChC2_DemFan : BOOL; (*charge cooler 2 demand fan 1 - 16*) (*OldName: new PV; Cycle:5;*)
		bChC2_DemFan_Man : BOOL; (*charge cooler 2 demand fan 1 - 16*) (*OldName: new PV; Cycle:5;*)
		bChC2_Heating : BOOL; (*charge cooler 2 pre heating*) (*OldName:newPv; Cycle:5;*)
		bChC2_Heating_Man : BOOL; (*charge cooler 2 pre heating*) (*OldName:newPv; Cycle:5;*)
		bECW_HydrPreH_COf : BOOL; (*engine cooling water hydraulic preheating demand off*) (*OldName: new PV; Cycle: 5;*)
		bECW_HydrPreH_COf_Man : BOOL; (*engine cooling water hydraulic preheating demand off*) (*OldName: new PV; Cycle: 5;*)
		bEOP_DemPump : BOOL; (*engine prelubrication pump manual demand*) (*OldName: new PV; Cycle: 5;*)
		bEOP_DemPump_Man : BOOL; (*engine prelubrication pump manual demand*) (*OldName: new PV; Cycle: 5;*)
	END_STRUCT;
END_TYPE
