(********************************************************************
 * COPYRIGHT -- INNIO Company
 ********************************************************************
 * Program: ExtSelect
 * File: ExtSelectInit.st
 * Author: 105046866
 * Created: September 17, 2012
 ********************************************************************
 * Implementation of program ExtSelect
 ********************************************************************)

PROGRAM _INIT


(* TODO : Add your code here *)


END_PROGRAM

