
TYPE
	IN_TR_Struct : 	STRUCT  (* *) (*OldName: new pv; Cycle:5;*)
		tAB2TR : AmmBase2MM; (*Structure Alarm base to Thermal Reactor module*) (*OldName: new pv; Cycle:5;*)
		tPB2MM : ParaBase2MM_type; (*Data exchange structure to ParaBase*) (*OldName:new PV;Cycle:5*)
		tEng_Run : HALioDo_Type; (*Engine in operation*) (*OldName:M_BTRB;Cycle:5*)
		iSt_OpMode : UDINT; (*Operating mode*) (*OldName:new pv; Cycle:5;*)
		tThR_LampTest : HALioDi_Type; (* DI thermal reactor lamp test *) (*OldName:DI_LT; Cycle:5;*)
		tThR_SL : HALioDi_Type; (* DI thermal reactor safety loop *) (*OldName:DI_SIK_TH; Cycle:5;*)
		tThR_Swth_On : HALioDi_Type; (* DI thermal reactor operation switch on *) (*OldName:DI_S_EIN; Cycle:5;*)
		tGCB_On : HALioDi_Type; (* generator circuit breaker closed *) (*OldName:GCB_ON;Cycle:2*)
		tMCB_On : HALioDi_Type; (* mains circuit breaker closed *) (*OldName:MCB_ON;Cycle:5*)
		tPos_ThR_Val_In1 : HALioDi_Type; (* DI1 thermal reactor flap in position moved in *) (*OldName:DI_KL_EIN1; Cycle:5;*)
		tPos_ThR_Val_In2 : HALioDi_Type; (* DI2 thermal reactor flap in position moved in *) (*OldName:DI_KL_EIN2; Cycle:5;*)
		tPos_ThR_Val_Mid : HALioDi_Type; (* DI thermal reactor flap in middle position *) (*OldName:DI_E_MITT; Cycle:5;*)
		tPos_ThR_Val_Out1 : HALioDi_Type; (* DI1 thermal reactor flap in position moved out *) (*OldName:DI_KL_AUS1; Cycle:5;*)
		tPos_ThR_Val_Out2 : HALioDi_Type; (* DI2 thermal reactor flap in position moved out *) (*OldName:DI_KL_AUS2; Cycle:5;*)
		tPr_ThR_AirLo : HALioDi_Type; (* DI thermal reactor compressed air pressure low *) (*OldName:DI_PS_LUFT; Cycle:5;*)
		tT_ThR_ChamberLo : HALioDi_Type; (* DI thermal reactor chamber temperature low *) (*OldName:DI_T_MIN; Cycle:5;*)
		tT_ThR_Swg_Hi : HALioDi_Type; (* DI thermal reactor switchgear temperature high *) (*OldName:DI_SR_TEMP; Cycle:5;*)
		rP_Act_Norm_Filt : REAL; (* actual power related to rP_Nom filtered T=1s *) (*OldName:P_IST_PROM; Cycle:5;*)
		rP_Nom : REAL; (*Nominal power*) (*OldName:PN_GASART;Cycle:5;*)
		tT_ThR_Chamber1_1 : HALioAi_Type; (* thermal reactor chamber temperature 1_1 *) (*OldName:TK1_1; Cycle:5;*)
		tT_ThR_Chamber1_2 : HALioAi_Type; (* thermal reactor chamber temperature 1_2 *) (*OldName:TK1_2; Cycle:5;*)
		tT_ThR_Chamber2_1 : HALioAi_Type; (* thermal reactor chamber temperature 2_1 *) (*OldName:TK2_1; Cycle:5;*)
		tT_ThR_Chamber2_2 : HALioAi_Type; (* thermal reactor chamber temperature 2_2 *) (*OldName:TK2_2; Cycle:5;*)
		tT_ThR_Comp : HALioAi_Type; (* thermal reactor compensation temperature *) (*OldName:AI_Tvgl; Cycle:5;*)
		tT_ThR_In : HALioAi_Type; (* thermal reactor inlet temperature *) (*OldName:AI_TempInTR; Cycle:5;*)
		tT_ThR_Out : HALioAi_Type; (* thermal reactor outlet temperature *) (*OldName:AI_TempOutTR; Cycle:5;*)
		tTR_AuxPS_GndFault : HALioDi_Type; (*earth fault auxiliaries power supply thermal reactor panel*)
		tTR_AuxPS_CB_Trip : HALioDi_Type; (*auxiliaries power supply circuit breaker thermal reactor panel tripped*)
		tTR_AuxPS_CB_On : HALioDi_Type; (*auxiliaries power supply circuit breaker thermal reactor panel opened*)
		tPos_ThR_AuxGasCV_Act : HALioAi_Type; (* Thermal reactor - auxiliary gas injection control valve position [%] (P.16-S-001) *)
		tPr_ThR_AuxGasBeforeCV : HALioAi_Type; (* Thermal reactor - auxiliary gas pressure before control valve [mbar] (P.16-PI-010) *)
		tPr_ThR_AuxGasAfterCV : HALioAi_Type; (* Thermal reactor - auxiliary gas pressure after control valve [mbar] (P.16-PI-020) *)
		tPr_ThR2_Inlet : HALioAi_Type; (* Thermal reactor 2 - inlet pressure [mbar] (P.02-PI-201) *)
		tPr_ThR2_Outlet : HALioAi_Type; (* Thermal reactor 2 - outlet pressure [mbar] (P.02-PI-202) *)
		tT_ThR2_EH_group1 : HALioAi_Type; (* Thermal reactor 2 - electrical heating group 1 - temperature [degC] (P.16-TI-101) *) (*Cycle:5;*)
		tT_ThR2_EH_group2 : HALioAi_Type; (* Thermal reactor 2 - electrical heating group 2 - temperature [degC] (P.16-TI-201) *) (*Cycle:5;*)
		tT_ThR2_EH_group3 : HALioAi_Type; (* Thermal reactor 2 - electrical heating group 3 - temperature [degC] (P.16-TI-301) *) (*Cycle:5;*)
		tT_ThR2_EH_group4 : HALioAi_Type; (* Thermal reactor 2 - electrical heating group 4 - temperature [degC] (P.16-TI-401) *) (*Cycle:5;*)
		tT_ThR2_EH_group5 : HALioAi_Type; (* Thermal reactor 2 - electrical heating group 5 - temperature [degC] (P.16-TI-501) *) (*Cycle:5;*)
		tT_ThR2_LeftChamber : HALioAi_Type; (* Thermal reactor 2 - chamber temperature left side [degC] (P.16-TI-018) *) (*Cycle:5;*)
		tT_ThR2_RightChamber : HALioAi_Type; (* Thermal reactor 2 - chamber temperature right side [degC] (P.16-TI-017) *) (*Cycle:5;*)
		tT_ThR2_Downstream : HALioAi_Type; (* Thermal reactor 2 - downstream temperature [degC] (P.16-TI-021) *) (*Cycle:5;*)
		tThR2_T_UnitOk_LeftCh : HALioDi_Type; (* Thermal reactor 2 - Sensor processing unit ok - chamber temperature left side (P.16-TI-018) *)
		tThR2_T_UnitOk_RightCh : HALioDi_Type; (* Thermal reactor 2 - Sensor processing unit ok - chamber temperature right side (P.16-TI-017) *)
		tThR2_T_UnitOk_Downstream : HALioDi_Type; (* Thermal reactor 2 - Sensor processing unit ok - downstream temperature (P.16-TI-021) *)
		tPr_SCR_CatIn : HALioAi_Type; (*SCR Exhaust pressure CAT inlet [bar] (P.02-PI-101)*)
	END_STRUCT;
	OUT_TR_Struct : 	STRUCT 
		tTR2PB : MM2ParaBase_type; (*Data exchange structure to ParaBase*) (*OldName: new pv; Cycle:5;*)
		tTR2AB : MM2AmmBase; (*AMM Structure*) (*OldName: new pv; Cycle:5;*)
		tThR_Contactor : HALioDo_Type; (* DO thermal reactor contactor *) (*OldName:DO_SCHUETZ; Cycle:5;*)
		tThR_CV_CDec : HALioDo_Type; (* DO thermal reactor gas control valve command decrease *) (*OldName:DO_GAS_MINUS; Cycle:5;*)
		tThR_CV_CInc : HALioDo_Type; (* DO thermal reactor gas control valve command increase *) (*OldName:DO_GAS_PLUS; Cycle:5;*)
		tThR_EH11 : HALioDo_Type; (* DO thermal reactor electrical heating element group 1 output 1 *) (*OldName:b_ThR_EH11; Cycle:5;*)
		tThR_EH12 : HALioDo_Type; (* DO thermal reactor electrical heating element group 1 output 2 *) (*OldName:b_ThR_EH12; Cycle:5;*)
		tThR_EH13 : HALioDo_Type; (* DO thermal reactor electrical heating element group 1 output 3 *) (*OldName:b_ThR_EH13; Cycle:5;*)
		tThR_EH21 : HALioDo_Type; (* DO thermal reactor electrical heating element group 2 output 1 *) (*OldName:b_ThR_EH21; Cycle:5;*)
		tThR_EH22 : HALioDo_Type; (* DO thermal reactor electrical heating element group 2 output 2 *) (*OldName:b_ThR_EH22; Cycle:5;*)
		tThR_EH23 : HALioDo_Type; (* DO thermal reactor electrical heating element group 2 output 3 *) (*OldName:b_ThR_EH23; Cycle:5;*)
		tThR_EH31 : HALioDo_Type; (* DO thermal reactor electrical heating element group 3 output 1 *) (*OldName:b_ThR_EH31; Cycle:5;*)
		tThR_EH32 : HALioDo_Type; (* DO thermal reactor electrical heating element group 3 output 2 *) (*OldName:b_ThR_EH32; Cycle:5;*)
		tThR_EH33 : HALioDo_Type; (* DO thermal reactor electrical heating element group 3 output 3 *) (*OldName:b_ThR_EH33; Cycle:5;*)
		tThR_ErrLamp : HALioDo_Type; (* DO thermal reactor failure lamp *) (*OldName:DO_L_ST; Cycle:5;*)
		tThR_GT_COn1 : HALioDo_Type; (* DO1 thermal reactor gas injection command on *) (*OldName:DO_EIND_EIN1; Cycle:5;*)
		tThR_GT_COn2 : HALioDo_Type; (* DO2 thermal reactor gas injection command on *) (*OldName:DO_EIND_EIN2; Cycle:5;*)
		bThR_RelGas : BOOL; (* thermal reactor gas injection released *) (*OldName:FRG_GASREG; Cycle:5;*)
		bThR_RelGas_Tmin : BOOL; (* thermal reactor minimum temperature for gas injection reached *) (*Cycle:5;*)
		bThR_RelHeat : BOOL; (* thermal reactor heating released *) (*OldName:FG_HEIZG; Cycle:5;*)
		bThR_Run : BOOL; (* thermal reactor operating *) (*OldName:TR_ON; Cycle:5;*)
		tThR_RunLamp : HALioDo_Type; (* DO thermal reactor operating lamp *) (*OldName:DO_L_BETR; Cycle: 5;*)
		bThR_RunReacTemp : BOOL; (* thermal reactor operating on reaction temperature *) (*OldName:TR_OPER; Cycle:5;*)
		tCtrTR_Heater_Set : HALioAo_Type; (*AO -> Controller output*)
		tThR_Val_Air : HALioDo_Type; (* DO thermal reactor purge air valve *) (*OldName:DO_SPLU_STOP; Cycle:5;*)
		tThR_Val_CCylIn : HALioDo_Type; (* DO thermal reactor flap command move in cylinder *) (*OldName:DO_KL_EIN; Cycle:5;*)
		tThR_Val_CCylOut : HALioDo_Type; (* DO thermal reactor flap command move out cylinder *) (*OldName:DO_KL_AUS; Cycle:5;*)
		bThR_Val_SetIn : BOOL; (* thermal reactor flap set direction move in cylinder *) (*OldName:KL_EIN; Cycle:5;*)
		bThR_Val_SetOut : BOOL; (* thermal reactor flap set direction move out cylinder *) (*OldName:KL_AUS; Cycle:5;*)
		bThR_Active : BOOL; (* thermal reactor measuring active *) (*OldName:reactor_a; Cycle:5;*)
		rP_ThR_EH : REAL; (* thermal reactor electrical heating power *) (*OldName:y_HE_Prom; Cycle:5;*)
		rT_ThR_Chamber : REAL; (* thermal reactor chamber temperature *) (*OldName:TK; Cycle:5;*)
		rT_ThR_Chamber1_1 : REAL; (* thermal reactor chamber temperature 1_1 *) (*OldName:TK1_1; Cycle:5;*)
		rT_ThR_Chamber1_2 : REAL; (* thermal reactor chamber temperature 1_2 *) (*OldName:TK1_2; Cycle:5;*)
		rT_ThR_Chamber2_1 : REAL; (* thermal reactor chamber temperature 2_1 *) (*OldName:TK2_1; Cycle:5;*)
		rT_ThR_Chamber2_2 : REAL; (* thermal reactor chamber temperature 2_2 *) (*OldName:TK2_2; Cycle:5;*)
		rT_ThR_Comp : REAL; (* thermal reactor compensation temperature *) (*OldName:Tvgl; Cycle:5;*)
		rT_ThR_In : REAL; (* thermal reactor inlet temperature *) (*OldName:TempInTR; Cycle:5;*)
		rT_ThR_Out : REAL; (* thermal reactor outlet temperature *) (*OldName:TempOutTR; Cycle:5;*)
		tCtrTR_Heater_Out : _tGeACtrOut; (* Heater Controller *) (*OldName: newPV; Cycle:5;*)
		tThR2_EH_group1_Dem : HALioDo_Type; (* Thermal reactor 2 - electrical heating group 1 - command On (P.16-W-101,102,103,104,105) *) (*Cycle:5;*)
		tThR2_EH_group2_Dem : HALioDo_Type; (* Thermal reactor 2 - electrical heating group 2 - command On (P.16-W-201,202,203) *) (*Cycle:5;*)
		tThR2_EH_group3_Dem : HALioDo_Type; (* Thermal reactor 2 - electrical heating group 3 - command On (P.16-W-301,302,303,304,305) *) (*Cycle:5;*)
		tThR2_EH_group4_Dem : HALioDo_Type; (* Thermal reactor 2 - electrical heating group 4 - command On (P.16-W-401,402,403) *) (*Cycle:5;*)
		tThR2_EH_group5_Dem : HALioDo_Type; (* Thermal reactor 2 - electrical heating group 5 - command On (P.16-W-501,502,503,504,505) *) (*Cycle:5;*)
		tThR2_AuxGasShutOffValve_Dem : HALioDo_Type; (* Thermal reactor 2 - solenoid valve gas injection - command Open (P.16-YCS-009) *) (*Cycle:5;*)
	END_STRUCT;
	MM2VIS_Struct : 	STRUCT 
		tCtrTR_Heater_Out : _tGeACtrOut; (*Controller to visualization OUT- structure*) (*OldName: newPV; Cycle:5;*)
		b_ThR_Val_Air : BOOL; (*Thermal reactor purge air valve*) (*OldName:DO_SPLU_STOP; Cycle:5;*)
		rP_ThR_EH : REAL; (*Electrical heating power*) (*OldName:y_HE_Prom1; Cycle:5;*)
		bThR_GT_COn2 : BOOL; (*Thermal reactor gas injection valve 2*) (*OldName:DO_EIND_EIN2; Cycle:5;*)
		bThR_GT_COn1 : BOOL; (*Thermal reactor gas injection valve 1*) (*OldName:DO_EIND_EIN1; Cycle:5;*)
		bPos_ThR_Val_Out2 : BOOL; (*Thermal reactor flap in position moved out 2*) (*OldName: DI_KL_AUS2; Cycle: 5;*)
		bPos_ThR_Val_In2 : BOOL; (*Thermal reactor flap in position moved in 2*) (*OldName: DI_KL_EIN2; Cycle: 5;*)
		bPos_ThR_Val_Mid : BOOL; (*Thermal reactor flap in position middle*) (*OldName: DI_KL_MITT; Cycle:5;*)
		bPos_ThR_Val_Out1 : BOOL; (*Thermal reactor flap in position moved out 1*) (*OldName: DI_KL_AUS1; Cycle: 5;*)
		bPos_ThR_Val_In1 : BOOL; (*Thermal reactor flap in position moved in 1*) (*OldName: DI_KL_EIN1; Cycle: 5;*)
		rT_ThR_Out : REAL; (*Thermal reactor outlet temperature*) (*OldName:AI_TempOut; Cycle: 5;*)
		rT_ThR_In : REAL; (*Thermal reactor inlet temperature*) (*OldName:AI_TempIn; Cycle: 5;*)
		rT_ThR_Comp : REAL; (*Thermal reactor compensation temperature*) (*OldName:Tvgl; Cycle:5;*)
		rT_ThR_Chamber : REAL; (*Thermal reactor average chamber temperature*) (*OldName:TK; Cycle:5;*)
		rT_ThR_Chamber2_2 : REAL; (*Thermal reactor chamber temperature 2_2*) (*OldName:TK2_2; Cycle:5;*)
		rT_ThR_Chamber2_1 : REAL; (*Thermal reactor chamber temperature 2_1*) (*OldName:TK2_1; Cycle:5;*)
		rT_ThR_Chamber1_2 : REAL; (*Thermal reactor chamber temperature 1_2*) (*OldName:TK1_2; Cycle:5;*)
		rT_ThR_Chamber1_1 : REAL; (*Thermal reactor chamber temperature 1_2*) (*OldName:TK1_1; Cycle:5;*)
		bMsg3306 : BOOL; (* Disturbance exhasut valvue middle position *) (*OldName:ALM[3306]; Cycle:5;*)
		bMsg3307 : BOOL; (* Safety loop thermal reactor, active only with RIO *) (*OldName:ALM[3307]; Cycle:5;*)
		bMsg3498 : BOOL; (* Sensor failure  *) (*OldName:ALM[3498]; Cycle:5;*)
		bMsg3499 : BOOL; (* Disturbance in pressurized air supply *) (*OldName:ALM[3499]; Cycle:5;*)
		bMsg3500 : BOOL; (* Disturbance in exhasut valve end position *) (*OldName:ALM[3500]; Cycle:5;*)
		bMsg3501 : BOOL; (* Heating time exceeded *) (*OldName:ALM[3501]; Cycle:5;*)
		bMsg3502 : BOOL; (* Control panel temperature too high *) (*OldName:ALM[3502]; Cycle:5;*)
		bMsg3503 : BOOL; (* Temperature differnce between TK1/TK2  > allowed maximum*) (*OldName:ALM[3503]; Cycle:5;*)
		bMsg3504 : BOOL; (* Reactor temperature TK1/TK2 maximum *) (*OldName:ALM[3504]; Cycle:5;*)
		bMsg3505 : BOOL; (* Reactor temperature minimum *) (*OldName:ALM[3505]; Cycle:5;*)
		bThR_RelHeat : BOOL; (* thermal reactor heating released *) (*OldName:FG_HEIZG; Cycle:5;*)
		bThR_Val_SetIn : BOOL; (* thermal reactor flap set direction move in cylinder *) (*OldName:KL_EIN; Cycle:5;*)
		bThR_Val_SetOut : BOOL; (* thermal reactor flap set direction move out cylinder *) (*OldName:KL_AUS; Cycle:5;*)
		bThR_RelGas : BOOL; (* thermal reactor gas injection released *) (*OldName:FRG_GASREG; Cycle:5;*)
		bMsg9309 : BOOL;
		bMsg9042 : BOOL;
		bMsg9043 : BOOL;
		bMsg2356 : BOOL;
		bMsg2357 : BOOL;
		bMsg2358 : BOOL;
		rPos_ThR_AuxGasCV_Act : REAL; (* Thermal reactor - auxiliary gas injection control valve position [%] (P.16-S-001) *)
		rPr_ThR_AuxGasBeforeCV : REAL; (* Thermal reactor - auxiliary gas pressure before control valve [mbar] (P.16-PI-010) *)
		rPr_ThR_AuxGasAfterCV : REAL; (* Thermal reactor - auxiliary gas pressure after control valve [mbar] (P.16-PI-020) *)
		rPr_Diff_ThR_AuxGasCV : REAL; (* Thermal reactor - auxiliary gas differential pressure across control valve [mbar] *)
		bThr_AuxGasCompressor_Run : BOOL; (* Thermal reactor - auxiliary gas compressor derived running status *)
		rFlow_ThR_AuxGasCV : REAL; (* Thermal reactor - calculated auxiliary gas flow (control valve) [Nm3/h] *)
		bMsg9374 : BOOL; (* Measuring signal failure auxiliary gas control valve position *)
		bMsg9375 : BOOL; (* Measuring signal failure auxiliary gas pressure before control valve *)
		bMsg9376 : BOOL; (* Measuring signal failure auxiliary gas pressure after control valve *)
		bMsg9377 : BOOL; (* Thermal reactor - auxiliary gas compressor fault, low pressure before control valve *)
		bMsg9381 : BOOL; (* Thermal reactor - implausible auxiliary gas pressure before/after control valve *)
		bMsg9396 : BOOL; (* Thermal reactor - differential pressure maximum - ThR2 *)
		bMsg9397 : BOOL; (* Measuring signal failure thermal reactor inlet pressure - ThR2 *)
		bMsg9398 : BOOL; (* Measuring signal failure thermal reactor outlet pressure - ThR2 *)
		bMsg9500 : BOOL; (* Measuring signal failure electrical heating monitoring temperature sensors - ThR2 *)
		bMsg9501 : BOOL; (* Measuring signal failure thermal reactor temperature right side - ThR2 *)
		bMsg9502 : BOOL; (* Measuring signal failure thermal reactor temperature left side - ThR2 *)
		bMsg9503 : BOOL; (* Measuring signal failure thermal reactor downstream temperature - ThR2 *)
		bMsg9504 : BOOL; (* Thermal reactor - auxiliary gas injection solenoid valve fault - ThR2 *)
		bMsg9505 : BOOL; (* Exhaust aftertreatment: Thermal reactor outlet/SCR inlet high differential pressure - ThR2 *)
		rPr_ThR2_Inlet : REAL; (* Thermal reactor 2 - inlet pressure [mbar] (P.02-PI-201) *)
		rPr_ThR2_Outlet : REAL; (* Thermal reactor 2 - outlet pressure [mbar] (P.02-PI-202) *)
		rPr_Diff_ThR2 : REAL; (* Thermal reactor 2 - inlet/outlet differential pressure [mbar] *)
		rT_ThR2_LeftChamber : REAL; (* Thermal reactor 2 - chamber temperature left side [degC] (P.16-TI-018) *)
		rT_ThR2_RightChamber : REAL; (* Thermal reactor 2 - chamber temperature right side [degC] (P.16-TI-017) *)
		rT_ThR2_Downstream : REAL; (* Thermal reactor 2 - downstream temperature [degC] (P.16-TI-021) *)
		bThR2_T_fault_LeftCh : BOOL; (* Thermal reactor 2 - Sensor fault - chamber temperature left side (P.16-TI-018) *)
		bThR2_T_fault_RightCh : BOOL; (* Thermal reactor 2 - Sensor fault - chamber temperature right side (P.16-TI-017) *)
		bThR2_T_fault_Downstream : BOOL; (* Thermal reactor 2 - Sensor fault - downstream temperature (P.16-TI-021) *)
		iThR2_EH_group1_status : UINT; (* Thermal reactor 2 - electrical heating group 1 - status (P.16-W-101,102,103,104,105) *)
		iThR2_EH_group2_status : UINT; (* Thermal reactor 2 - electrical heating group 2 - status (P.16-W-201,202,203) *)
		iThR2_EH_group3_status : UINT; (* Thermal reactor 2 - electrical heating group 3 - status (P.16-W-301,302,303,304,305) *)
		iThR2_EH_group4_status : UINT; (* Thermal reactor 2 - electrical heating group 4 - status (P.16-W-401,402,403) *)
		iThR2_EH_group5_status : UINT; (* Thermal reactor 2 - electrical heating group 5 - status (P.16-W-501,502,503,504,505) *)
		rT_ThR2_EH_group1 : REAL; (* Thermal reactor 2 - electrical heating group 1 - temperature [degC]*)
		rT_ThR2_EH_group2 : REAL; (* Thermal reactor 2 - electrical heating group 1 - temperature [degC]*)
		rT_ThR2_EH_group3 : REAL; (* Thermal reactor 2 - electrical heating group 1 - temperature [degC]*)
		rT_ThR2_EH_group4 : REAL; (* Thermal reactor 2 - electrical heating group 1 - temperature [degC]*)
		rT_ThR2_EH_group5 : REAL; (* Thermal reactor 2 - electrical heating group 1 - temperature [degC]*)
		bThR2_AuxGasShutOffValve_Dem : BOOL; (* Thermal reactor 2 - solenoid valve gas injection - command Open (P.16-YCS-009) *)
		bThR_LeftChamber_inlet : BOOL; (* Thermal reactor 2 - left side inlet status *)
		bThR_RightChamber_inlet : BOOL; (* Thermal reactor 2 - right side inlet status  *)
		rPr_Diff_ThR2out_SCRin : REAL; (* Thermal reactor 2 - Exhaust aftertreatment - Thermal reactor outlet/SCR inlet differential pressure [mbar] *)
	END_STRUCT;
	VIS2MM_Struct : 	STRUCT 
		tCtrTR_Heater_In : _tGeACtrIn; (*Visualization to controller IN - structure*)
		iCnt_OpHours_Reactor : DINT;
		iCnt_OpHours_GasInj : DINT;
		iCnt_OpHours_Heater : DINT;
	END_STRUCT;
	PERM_TR_Struct : 	STRUCT 
		iCnt_OpHours_Reactor : DINT;
		iCnt_OpHours_GasInj : DINT;
		iCnt_OpHours_Heater : DINT;
		rTB_PermValue04 : REAL; (*spare permanent value for testbench- replace with new vars of same lenght, when needed*) (*OldName:new PV;Cycle:2;*)
		rTB_PermValue05 : REAL; (*spare permanent value for testbench- replace with new vars of same lenght, when needed*) (*OldName:new PV;Cycle:2;*)
		rTB_PermValue06 : REAL; (*spare permanent value for testbench- replace with new vars of same lenght, when needed*) (*OldName:new PV;Cycle:2;*)
		rTB_PermValue07 : REAL; (*spare permanent value for testbench- replace with new vars of same lenght, when needed*) (*OldName:new PV;Cycle:2;*)
		rTB_PermValue08 : REAL; (*spare permanent value for testbench- replace with new vars of same lenght, when needed*) (*OldName:new PV;Cycle:2;*)
		rTB_PermValue09 : REAL; (*spare permanent value for testbench- replace with new vars of same lenght, when needed*) (*OldName:new PV;Cycle:2;*)
		rTB_PermValue10 : REAL; (*spare permanent value for testbench- replace with new vars of same lenght, when needed*) (*OldName:new PV;Cycle:2;*)
	END_STRUCT;
	ls : 	STRUCT 
		IN : DINT;
		LSHI : DINT;
		LSLO : DINT;
		QH : BOOL;
		QL : BOOL;
	END_STRUCT;
	ls_t : 	STRUCT 
		IN : DINT;
		LSHI : DINT;
		LSLO : DINT;
		PTHI : TIME;
		PTLO : TIME;
		QH : BOOL;
		QL : BOOL;
	END_STRUCT;
END_TYPE
