(*******************************************************************************
CUSTOMIZED: c_fc 			init to customized frequency control

This code is confidential and proprietary to the INNIO Company.
It may not be used in any form, or reproduced in any manner,
without written permission of the INNIO Company.
Copyright, INNIO Company, 2019

Customized modifications: -
------------------------
 
Instructions for use:
--------------------
USE THIS TASK TO ADD CODE SNIPPETS AFTER ENGINE DELIVERY

Outstandings:
------------

*******************************************************************************)
PROGRAM _INIT	

	bDoNothing := TRUE; 
	
	(*-----------------------------------------------------------------------------*)
	bNoInitDetected := FALSE; 	 (* Insert this into every tasks INIT code to activate download detection *)	
END_PROGRAM

