(********************************************************************
 * COPYRIGHT -- INNIO Company
 ********************************************************************
 * Program: reac_set
 * File: reac_setInit.st
 * Author: thalerjo
 * Created: November 18, 2010
 ********************************************************************
 * Implementation of program reac_set
 ********************************************************************)

PROGRAM _INIT


(* TODO : Add your code here *)


END_PROGRAM

