TYPE

END_TYPE
TYPE
BlockIO_CoV_24Cyl : STRUCT
	Avg : REAL;
	Std : REAL;
	CoV : REAL;
	Avg_g : REAL;
	Std_n : REAL;
	CoV_c : REAL;
	Avg_d : REAL;
	Std_f : REAL;
	CoV_d : REAL;
	Avg_m : REAL;
	Std_i : REAL;
	CoV_m : REAL;
	Avg_dg : REAL;
	Std_g : REAL;
	CoV_k : REAL;
	Avg_h : REAL;
	Std_h : REAL;
	CoV_e : REAL;
	Avg_c : REAL;
	Std_k : REAL;
	CoV_mz : REAL;
	Avg_a : REAL;
	Std_kl : REAL;
	CoV_db : REAL;
	Avg_n : REAL;
	Std_j : REAL;
	CoV_n : REAL;
	Avg_n5 : REAL;
	Std_gz : REAL;
	CoV_l : REAL;
	Avg_m0 : REAL;
	Std_l : REAL;
	CoV_cl : REAL;
	Avg_e : REAL;
	Std_hh : REAL;
	CoV_me : REAL;
	Avg_n4 : REAL;
	Std_hx : REAL;
	CoV_lo : REAL;
	Avg_e5 : REAL;
	Std_e : REAL;
	CoV_f : REAL;
	Avg_eu : REAL;
	Std_m : REAL;
	CoV_i : REAL;
	Avg_ey : REAL;
	Std_b : REAL;
	CoV_lh : REAL;
	Avg_j : REAL;
	Std_ev : REAL;
	CoV_mw : REAL;
	Avg_p : REAL;
	Std_a : REAL;
	CoV_iy : REAL;
	Avg_gz : REAL;
	Std_d : REAL;
	CoV_cc : REAL;
	Avg_pv : REAL;
	Std_ht : REAL;
	CoV_h : REAL;
	Avg_d2 : REAL;
	Std_ji : REAL;
	CoV_hj : REAL;
	Avg_b : REAL;
	Std_ag : REAL;
	CoV_j : REAL;
	Avg_o : REAL;
	Std_gd : REAL;
	CoV_nw : REAL;
	Avg_l : REAL;
	Std_ik : REAL;
	CoV_o : REAL;
	Avg_lu : REAL;
	Std_c : REAL;
	CoV_ja : REAL;
	Input25 : ARRAY[0..24] OF REAL;
	Selector : REAL;
	Selector_l : REAL;
	Selector_a : REAL;
	Selector_n : REAL;
	Selector_c : REAL;
	Selector_c4 : REAL;
	Selector_g : REAL;
	Selector_o : REAL;
	Selector_ct : REAL;
	Selector_h : REAL;
	Selector_lk : REAL;
	Selector_b : REAL;
	Selector_al : REAL;
	Selector_j : REAL;
	Selector_d : REAL;
	Selector_f : REAL;
	Selector_p : REAL;
	Selector_hu : REAL;
	Selector_ob : REAL;
	Selector_ox : REAL;
	Selector_m : REAL;
	Selector_p5 : REAL;
	Selector_k : REAL;
	Selector_og : REAL;
	Selector_fv : REAL;
END_STRUCT;
D_Work_CoV_24Cyl : STRUCT
	TappedDelaysetasN_cyc_X : ARRAY[0..99] OF REAL;
	TappedDelaysetasN_cyc_X_c : ARRAY[0..99] OF REAL;
	TappedDelaysetasN_cyc_X_a : ARRAY[0..99] OF REAL;
	TappedDelaysetasN_cyc_X_ch : ARRAY[0..99] OF REAL;
	TappedDelaysetasN_cyc_X_m : ARRAY[0..99] OF REAL;
	TappedDelaysetasN_cyc_X_b : ARRAY[0..99] OF REAL;
	TappedDelaysetasN_cyc_X_m3 : ARRAY[0..99] OF REAL;
	TappedDelaysetasN_cyc_X_ap : ARRAY[0..99] OF REAL;
	TappedDelaysetasN_cyc_X_d : ARRAY[0..99] OF REAL;
	TappedDelaysetasN_cyc_X_j : ARRAY[0..99] OF REAL;
	TappedDelaysetasN_cyc_X_b0 : ARRAY[0..99] OF REAL;
	TappedDelaysetasN_cyc_X_da : ARRAY[0..99] OF REAL;
	TappedDelaysetasN_cyc_X_di : ARRAY[0..99] OF REAL;
	TappedDelaysetasN_cyc_X_g : ARRAY[0..99] OF REAL;
	TappedDelaysetasN_cyc_X_jg : ARRAY[0..99] OF REAL;
	TappedDelaysetasN_cyc_X_l : ARRAY[0..99] OF REAL;
	TappedDelaysetasN_cyc_X_f : ARRAY[0..99] OF REAL;
	TappedDelaysetasN_cyc_X_n : ARRAY[0..99] OF REAL;
	TappedDelaysetasN_cyc_X_f0 : ARRAY[0..99] OF REAL;
	TappedDelaysetasN_cyc_X_ln : ARRAY[0..99] OF REAL;
	TappedDelaysetasN_cyc_X_jc : ARRAY[0..99] OF REAL;
	TappedDelaysetasN_cyc_X_i : ARRAY[0..99] OF REAL;
	TappedDelaysetasN_cyc_X_mr : ARRAY[0..99] OF REAL;
	TappedDelaysetasN_cyc_X_g1 : ARRAY[0..99] OF REAL;
	TappedDelaysetasN_cyc_X_cc : ARRAY[0..99] OF REAL;
END_STRUCT;
END_TYPE