
TYPE
	IN_IG_Struct : 	STRUCT 
		tPB2MM : ParaBase2MM_type; (*Data exchange structure to ParaBase*) (*OldName:new PV; Cycle:5;*)
		tAB2IG : AmmBase2MM; (*AMM structure*) (*OldName:new PV; Cycle:2;*)
		tIgn_Run_Hal : HALioDi_Type; (*DI: Ignition system running*) (*OldName:ZIB;Cycle:2;*)
		tIgn2_Run_Hal : HALioDi_Type; (*DI: Ignition system double running*) (*OldName:ZIB2; Cycle:2;*)
		tGCB_RUC : HALioDo_Type; (*DO: Generator circuit breaker release under voltage coil*) (*OldName:A_USP; Cycle:2;*)
		tIgn_OverspeedRelay : HALioDi_Type; (*DI: Overspeed relay *) (*OldName:UEDZ; Cycle:5;*)
		tGCB_On : HALioDi_Type; (*DI: generator circuit breaker closed *) (*OldName:GCB_ON; Cycle:5;*)
		bIgnOperating : BOOL; (*SAFI ignition system running*) (*OldName:ZIB; Cycle:2;*)
		bMsg1026 : BOOL; (*shutdown failure*) (*OldName:M_ANSTAB; Cycle:2;*)
		bIgn_Dem : BOOL; (*demand ignition*) (*OldName:ZUEND; Cycle:2;*)
		bIgn_Dem_TC5 : BOOL; (*demand ignition*) (*OldName:ZUEND; Cycle:2;*)
		bGV_On : BOOL; (*Command open gas valves*) (*OldName:M_GASV; Cycle:2;*)
		bGV_On_TC2 : BOOL; (*Command open gas valves*) (*OldName:M_GASV; Cycle:2;*)
		rCA_IgnP_Set : REAL; (*global ignition timing set point*) (*OldName:W_ZZP ; Cycle:2;*)
		rCA_Ign_Act : ARRAY[0..24]OF REAL; (*actual ignition timing *) (*OldName:ActTiming; Cycle:2;*)
		rN_IgnIC_Act : REAL; (*engine speed meassured by ignition *) (*OldName:ZDGSpeed; Cycle:2;*)
		rN_IgnSAFI_Act : REAL; (* engine speed meassured by ignition *) (*OldName:ZDGSpeed; Cycle:2;*)
		bPr_EOP_Prelub1 : BOOL; (* Vorschmierdruck 1 Pumpe *) (*OldName:AN_VSD1; Cycle:5;*)
		b_IgnIC_SelfTestBack : BOOL; (* switch ignition system to selftest *) (*OldName:GoSelftest; Cycle:5;*)
		b_IgnSAFI_SelfTestBack : BOOL; (* switch ignition system to selftest *) (*OldName:GoSelftest; Cycle:5;*)
		rU_IgnSAFI_Cyl : ARRAY[0..24]OF REAL; (*ignition voltage for each cylinder SAFI*) (*OldName:V_Zyl; Cycle:2;*)
		rU_IgnMon_Cyl : ARRAY[0..24]OF REAL; (*ignition voltage for each cylinder Monic*) (*OldName:V_Zyl; Cycle:2;*)
		bEng_Dem : BOOL; (*module demanded*) (*OldName:M_AGFD; Cycle:2;*)
		bDeflagrationPrct : BOOL; (*Deflagration protection*) (*OldName:PUFF; Cycle:2;*)
		bMnsOk : BOOL; (*Mains ok *) (*OldName:NE_OK; Cycle:5;*)
		bPr_EOP_Prelub2 : BOOL; (*Prelubrication pressure 2 pumps*) (*OldName:AN_VSD2; Cycle:5;*)
		bRelEngTurn_OilSkid : BOOL; (*release engine barring gear (Durchdrehvorrichtung) from Oil Skid*) (*OldName:new pv;Cycle:5*)
		bEngOilLevel_Lo : BOOL; (* engine oil level low *) (*OldName:ZM_OMIN; Cycle:5*)
		tSafetyLoop_EmStop : HALioDi_Type; (*safety loop - emergency stop*) (*OldName: DI_SIS; Cycle: 5;*)
		tSafetyLoop_Eng : HALioDi_Type; (*safety loop - engine*) (*OldName: RUHE, DI_RUHE_TC1; Cycle: 5;*)
		bSimWinMOD_Active : BOOL; (*WinMode simulation active *) (* OldName:new PV; Cycle:5*)
		iIdx_OMSS : INT; (* inex of operation mode selector switch - 0..OFF, 1..MAN, 2..AUTO, 3..TEST, 4..SCAVENGING *) (*OldName:new PV;Cycle:5;*)
		bInLouRelVE : BOOL; (*inlet louvers open or not closed*)
		bIC_Ign_Run_CAN : BOOL; (*IC Output ignition active from CAN*)
		bTOF_HwBypassDigitalTwin : BOOL; (*Hardware bypass digital twin - T3 adaptive cranking time*)
		bMsg2295 : BOOL; (*engine room ventilation failure inlet air*)
		bMissfCyl_PurgeCrk : BOOL; (*skip fire all cylinders while purging*)
	END_STRUCT;
	OUT_IG_Struct : 	STRUCT 
		tIG2PB : MM2ParaBase_type; (*Data exchange structure to ParaBase*) (*OldName:new PV; Cycle:5;*)
		tIG2AB : MM2AmmBase; (*AMM structure*) (*OldName:new PV; Cycle:5;*)
		rN_EngAct : REAL; (*Engine Speed (1/min)*) (*OldName:ZDGSpeed; Cycle:2;*)
		bEO_PrelubeDemIgn : BOOL; (*Demand Prelubricating from ignition*) (*OldName:PRELUBE_IgnST; Cycle:2;*)
		bIgn_SelfTest : BOOL; (*Switch ignition system to selftest *) (*OldName:GoSelftest; Cycle:5;*)
		b_ST_DemIgn : BOOL; (*Demand starter from ignition*) (*OldName:STARTER_IgnST; Cycle:5;*)
		rU_Ign_Cyl : ARRAY[0..24]OF REAL; (*Ignition voltage for each cylinder *) (*OldName:V_Zyl; Cycle:;*)
		rU_Ign_Max : REAL; (* Maximum Ignition voltage *) (*OldName:AvgVolt; Cycle:;*)
		bIgn_Run : BOOL; (*Ignition system is running*) (*OldName:ZIB; Cycle:2;*)
		bN_EngStartDrop : BOOL; (*Engine start-up speed drop down*) (*OldName:M_STRDRE; Cycle:2;*)
		bMsg1022 : BOOL; (*Message*) (*OldName:M_UEDZ; Cycle:5;*)
		bIgn2_Sel : BOOL; (*TRUE = Double ignition selected*) (*OldName:IIXZUEND; Cycle:2;*)
		bMsg1064 : BOOL; (*Message *) (*OldName:M_UEDZRP; Cycle:5;*)
		bMsg3561 : BOOL; (*	Message	*) (*OldName:bPv; Cycle:5;*)
		tCA_IgnP_Set : HALioAo_Type; (*AO: timing point*) (*OldName:ssZZPOutWE; Cycle:2;*)
		bSelfTestRunning : BOOL;
		rCA_Ign_Avg : REAL; (*Actual ignition point average*) (*OldName:ZZPAvg; Cycle:;*)
		rU_Ign_Avg : REAL; (* *) (*OldName:AvgVolt; Cycle:;*)
		rU_Ign_Min : REAL; (* *) (*OldName:MinVolt; Cycle:;*)
		rCA_Ign_Min : REAL; (*Actual min. cylinder ignition point*) (*OldName:ZZPMin; Cycle:;*)
		rCA_Ign_Max : REAL; (*Actual max. cylinder ignition point*) (*OldName:ZZPMax; Cycle:;*)
		iIdx_IgnSelfTest : INT; (*Number of shown picture regarding step of execution. 0 - 50 in steps of 10. Detailded description in every step where used.*) (*OldName:usP5xSelftestStep; Cycle:;*)
		bInLouDemIgn : BOOL; (*Inlet louver demand for ignition selftest*)
		bIgn_Run_CAN : BOOL; (*Ignition system is running - feedback from CAN*)
	END_STRUCT;
	Para_IG_Struct : 	STRUCT 
		bIgnMon_Active : BOOL; (*PARA [12064]: TRUE = MONIC is enabled/active*) (*OldName:monic_vis; Cycle:;*)
		bSA_Active : BOOL; (*PARA [12114]: TRUE = SAFI is enabled/active*) (*OldName:bSA_Active; Cycle:;*)
		b_IgnIC_900Active : BOOL; (*PARA [12062]: TRUE = CAN ignition system is used *) (*OldName:ic900_vis; Cycle:;*)
		bSA_Ign_Active : BOOL; (*PARA [12117]: TRUE = SAFI ignition function is enabled/active*) (*OldName:bSAFIIgn_Act; Cycle:;*)
		bIgn2_Sel_Para : BOOL; (*PARA [12063]: Select double ignition*) (*OldName:sel_2ignition; Cycle:;*)
		rN_EngStart_HyHi : REAL; (*PARA [11295]: speed engine start limit high hysteresis*) (*OldName:HY_DREHZ; Cycle:;*)
		rN_EngStart_LimHi : REAL; (*PARA [11296]: speed engine start limit high*) (*OldName:GW_DREHZ; Cycle:;*)
		rN_EngStartMon_HyHi : REAL; (*PARA [12067]: speed engine start monitoring limit high hysteresis*) (*OldName:HY_STRDRE; Cycle:;*)
		rN_EngStartMon_LimHi : REAL; (*PARA [12068]: speed engine start monitoring limit high*) (*OldName:GW_STRDRE; Cycle:;*)
		iEng_Motortype : INT; (*PARA: Motortype of the engine*) (*OldName:motortyp; Cycle:;*)
		rCA_RetTimeLim : REAL; (*PARA [12066]: Retard ignition timing limit*) (*OldName:RetTimLi; Cycle:;*)
		rCA_AdvTimeLim : REAL; (*PARA [12065]: Advanced ignition timing limit*) (*OldName:AdvTimLi; Cycle:;*)
		rN_PLC_LimHi : REAL; (*PARA [12070]: Overspeed PLC limit *) (*OldName:GW_UEDZ; Cycle:;*)
		rN_PLC_HyHi : REAL; (*PARA [12069]: Overspeed PLC hysteresis *) (*OldName:HY_UEDZ; Cycle:;*)
		tiIgn_SelfTest : TIME; (*PARA [14432]: Ignition self test duration*) (*OldName:monic_vis; Cycle:;*)
		bSEMIC_Active : BOOL; (*PARA[14519]: Ignition controller SEMIC*)
	END_STRUCT;
	MM2VIS_Struct : 	STRUCT 
		rCA_Ign_Act : ARRAY[0..24]OF REAL; (*actual cylinder ignition point*) (*OldName:ActTiming; Cycle:;*)
		rCA_Ign_Avg : REAL; (*Actual ignition point average*) (*OldName:ZZPAvg; Cycle:;*)
		rCA_Ign_Min : REAL; (*Actual min. cylinder ignition point*) (*OldName:ZZPMin; Cycle:;*)
		rCA_Ign_Max : REAL; (*Actual max. cylinder ignition point*) (*OldName:ZZPMax; Cycle:;*)
		iIdx_IgnSelfTest : INT; (*Number of shown picture regarding step of execution. 0 - 50 in steps of 10. Detailded description in every step where used.*) (*OldName:usP5xSelftestStep; Cycle:;*)
		rU_Ign_Cyl : ARRAY[0..24]OF REAL; (*ignition voltage for each cylinder *) (*OldName:V_Zyl; Cycle:;*)
		rU_Ign_Avg : REAL; (* *) (*OldName:AvgVolt; Cycle:;*)
		rU_Ign_Max : REAL; (* *) (*OldName:MaxVolt; Cycle:;*)
		rU_Ign_Min : REAL; (* *) (*OldName:MinVolt; Cycle:;*)
		bMsg3346 : BOOL; (* *) (*OldName:; Cycle:;*)
		bMsg3228 : BOOL; (* *) (*OldName:; Cycle:;*)
		bMsg3347 : BOOL; (* *) (*OldName:; Cycle:;*)
		bMsg1061 : BOOL; (* *) (*OldName:; Cycle:;*)
		bMsg3225 : BOOL; (* *) (*OldName:; Cycle:;*)
		bMsg3226 : BOOL; (* *) (*OldName:; Cycle:;*)
		bMsg1022 : BOOL; (* *) (*OldName:; Cycle:;*)
		bMsg1064 : BOOL; (* *) (*OldName:; Cycle:;*)
		bMsg3561 : BOOL; (* *) (*OldName:; Cycle:;*)
		rN_EngAct : REAL; (*Engine Speed (1/min)*) (*OldName:; Cycle:;*)
		bIgn_SelfTest : BOOL; (*Switch ignition system to selftest *) (*OldName:GoSelftest; Cycle:5;*)
		bMsg9044 : BOOL; (* *) (*OldName:; Cycle:;*)
	END_STRUCT;
	VIS2MM_Struct : 	STRUCT 
		bIgn_SelfTestStart : BOOL; (*start self test button*) (*OldName:; Cycle:;*)
		bIgn_SelfTestStop : BOOL; (*stop self test button*) (*OldName:; Cycle:;*)
		bIgn_SelfTestPrep : BOOL; (*start preperation button*) (*OldName:; Cycle:;*)
		bIgn_SelfTestCancel : BOOL; (*cancel preperation button*) (*OldName:; Cycle:;*)
		bHVMaxValueAct : BOOL; (*Spark voltage maximum*) (*OldName:; Cycle:;*)
	END_STRUCT;
END_TYPE
