/*******************************************************************************
JEW_LIB1: time based on/off in dependence of setpoint an actual position
Copyright 1998 - 2003 Jenbacher AG

- calculate actual position and hysteresis for the next step 
- output actual position


Customized modifications: 
------------------------
 
History:
-------
V0.1	02-11-2002	Weitzer,	generated from TimeBaseOn.SRC / V0.1 / 02-11-2002 /Fahringer
V0.2	28-03-2003	Fahringer,	correct casting for calculation of	fd->fUnitTime 

Instructions for use:
--------------------
enable	   	FUB on / off
x			setpoint position
min_value  	min position
max_value  	maximum positon
hysteresis  minimum difference between x and y_act for drive to new position
tchange    	time for drive from min_value to max_value
basetime   	time base for FUB timing  (best generated by LCCounter FUB)
status		FUB status 0 = OK, 1 = no difference between max_value and min_value	
up			open actuator
down		close actuator
y_act		actual actuator position (calcualted FUB internal)
set_pos		position if FUB is disabled (enable OFF)

Outstandings:
------------
*******************************************************************************/

#include <jew_lib1.h>
#include <bur/plctypes.h>

void TimeBasedOnOff_R(TimeBasedOnOff_R_typ *fd)
/* begin FUB */
{

if (fd->enable != 0)
{
	fd->status = 0;		/* reset status */

	/* calculate basetime for 1 step of x */
	if (fd->tchange != 0)
	{
		fd->fUnitTime = (float)(fd->max_value - fd->min_value)/fd->tchange;
	}	
	else
	{
		fd->status = 1;		/* no change time from min_value to max_value */
	}	
	
	/* calcualte time difference since last cycle */
	fd->fDiffTime = fd->basetime - fd->ulLastTime;

	/* calculate minimum hysteresis for the next step */
	fd->fHysteresis = fd->fUnitTime*fd->fDiffTime;

	/* calculate actual position and hysteresis for the next step */
	if (fd->up != 0) 	/* open actuator */
	{
		fd->y_act   = fd->y_act + fd->fHysteresis;		/* calcualte new actual position = y_act + fDiffTime*fUnitTime*/

		fd->fHystUp = fd->fHysteresis;					/* set to minimum up hystersis */

		if (fd->fHysteresis < fd->hysteresis)		/* is mimimum hysteresis < user hysteresis */
		{
			fd->fHystDown = fd->hysteresis;		/* use user down hysteresis */
		}	
		else
		{
			fd->fHystDown = fd->fHysteresis;	/* set to minimum down hysteresis */
		}

	}
	else if (fd->down != 0)		/* close actuator */ 
	{
		fd->y_act     = fd->y_act - fd->fHysteresis;		/* calcualte new actual position close = y_act - fDiffTime*fUnitTime*/

		fd->fHystDown = fd->fHysteresis;					/* set to minimum down hysteresis */

		if (fd->fHysteresis < fd->hysteresis)		/* is mimimum hysteresis < user hysteresis */
		{
			fd->fHystUp = fd->hysteresis;		/* use user up hysteresis */
		}	
		else
		{
			fd->fHystUp = fd->fHysteresis;		/* set to minimum up hysteresis */
		}	
	}
	else		/* actuator stopped */
	{
		if (fd->fHysteresis < fd->hysteresis)		/* is mimimum hysteresis < user hysteresis */
		{
			fd->fHystUp   = fd->hysteresis;		/* use user up hysteresis */
			fd->fHystDown = fd->fHystUp;		/* use user down hysteresis */
		}	
		else
		{
			fd->fHystUp   = fd->fHysteresis;		/* set to minimum up hysteresis */
			fd->fHystDown = fd->fHystUp;			/* set to minimum down hysteresis */
		}
	}
	
	if (fd->x >= fd->y_act + fd->fHystUp)		/* setpoint position >= actual position + hysteresis */
	{
		fd->up   = 1;		/* set bit for open */
		fd->down = 0;		/* reset bit for close */
	}
	else if (fd->x <= fd->y_act - fd->fHystDown)		/* setpoint position <= actual position - hysteresis */
	{
		fd->down = 1;		/* set bit for close */
		fd->up   = 0;		/* reset bit for open */
	}
	else		/* if difference between actual and setpoint positioin within hystetrsis */
	{
		fd->up   = 0;		/* reset bit for open */
		fd->down = 0;		/* reset bit for close */
	}
}
else
{
	fd->y_act = fd->set_pos;
}

if (fd->y_act >= 0)	/* check pos. or neg. output and compensate rounding error */
{
	fd->y          = (short)(fd->y_act+0.5);	/* actual position FUB output */
}
else
{
	fd->y          = (short)(fd->y_act-0.5);	/* actual position FUB output */
}

fd->ulLastTime = fd->basetime;				/* save last cycle time */

/* end FUB */
}
