(*******************************************************************************
vis	INIT		visualization

This code is confidential and proprietary to the INNIO Company.
It may not be used in any form, or reproduced in any manner,
without the express written permission of the INNIO Company.
Copyright, INNIO Company, 2019
*******************************************************************************)

PROGRAM _INIT


	(*-----------------------------------------------------------------------------*)
	bNoInitDetected := FALSE; 	 (* Insert this line into every tasks INIT code to activate download detection *)	
END_PROGRAM



