
TYPE
	PROGRAMMER_INFO_Perm : 	STRUCT 
		DO_NOT_CHANGE_PERM : STRING[40] := 'DO NOT CHANGE PERMLENGT OR ELEMENT ORDER'; (* DO NOT ADD OR DELETE ITEMS HERE! *) (*ADD NEW PERM DATAPOINT ONLY BY REPLACING SPARE ENTRIES OF SAME LENGHT!. DO NOT DELETE existing Perm items. Add new file for mayor changes,but avoid changing existing files as long as possible. Every change demands an update of main revision numbering!*)
	END_STRUCT;
	PERM_PB_Struct : 	STRUCT 
		iCntDiff_OpHours : DINT; (*********** Parabase Items: start counter 	  ...counter difference*)
		iCntDiff_UnitOpHours : DINT; (*Initial detected counter difference*)
		iCntDiff_Starts : DINT; (*Initial detected  counter difference*)
		iCntDiff_FastStarts : DINT; (*Initial detected  counter difference*)
		iCntUnchanged_OpHours : DINT; (* operating hours counter *)
		iCntUnchanged_UnitOpHours : DINT; (* unit operating hours counter *)
		iCntUnchanged_Starts : DINT; (* start counter *)
		iCntUnchanged_FastStarts : DINT; (* fast start counter *)
		iCnt_Offset_OpHours_DataMax : DINT; (*V4.13   holds possible offset to surpress warning*)
		iCnt_Offset_UnitOpHours_DataMax : DINT; (*V4.13   holds possible offset to surpress warning*)
		iCnt_Offset_Starts_DataMax : DINT; (*V4.13   holds possible offset to surpress warning*)
		iCnt_Offset_FastStarts_DataMax : DINT; (*V4.13   holds possible offset to surpress warning ?*)
		iCmd_OpHours_SetCounter : UDINT; (*V4.13   holds commands and execution date to surpress warning ?*)
		iCmd_ReduceStoredOffsets : UDINT; (*V4.13   holds commands and flags to surpress warning ?*)
		tCommand_Execution_Time : RTCtime_typ; (*V4.13   holds execution time to surpress warning ?*)
		tDetectedEvent_Time : RTCtime_typ; (*V4.13   suspected time of counter failure *)
		tSpare_Time : RTCtime_typ; (*V4.13   holds room for future*)
		iCnt_OpHours : DINT; (* operating hours counter *) (*OldName:betrieb_h;Cycle:2;*)
		iCnt_UnitOpHours : DINT; (* unit operating hours counter *)
		iCnt_Starts : DINT; (*********** Backup Opstate: start counter *) (*OldName:start_z;Cycle:2;*)
		iCnt_FastStarts : DINT; (* fast start counter *)
		rPB_PermValue01 : REAL; (********** spare permanent value - replace with new vars of same lenght, when needed*)
		rPB_PermValue02 : REAL; (*spare permanent value - replace with new vars of same lenght, when needed*)
		rPB_PermValue03 : REAL; (*spare permanent value - replace with new vars of same lenght, when needed*)
		rPB_PermValue04 : REAL; (*spare permanent value - replace with new vars of same lenght, when needed*)
		rPB_PermValue05 : REAL; (*spare permanent value - replace with new vars of same lenght, when needed*)
		rPB_PermValue06 : REAL; (*spare permanent value - replace with new vars of same lenght, when needed*)
		rPB_PermValue07 : REAL; (*spare permanent value - replace with new vars of same lenght, when needed*)
		rPB_PermValue08 : REAL; (*spare permanent value - replace with new vars of same lenght, when needed*)
		rPB_PermValue09 : REAL; (*spare permanent value - replace with new vars of same lenght, when needed*)
		rPB_PermValue10 : REAL; (*spare permanent value - replace with new vars of same lenght, when needed*)
		rPB_PermValue11 : REAL; (*spare permanent value - replace with new vars of same lenght, when needed*)
		rPB_PermValue12 : REAL; (*spare permanent value - replace with new vars of same lenght, when needed*)
		rPB_PermValue13 : REAL; (*spare permanent value - replace with new vars of same lenght, when needed*)
		rPB_PermValue14 : REAL; (*spare permanent value - replace with new vars of same lenght, when needed*)
		rPB_PermValue15 : REAL; (*spare permanent value - replace with new vars of same lenght, when needed*)
		rPB_PermValue16 : REAL; (*spare permanent value - replace with new vars of same lenght, when needed*)
		rPB_PermValue17 : REAL; (*spare permanent value - replace with new vars of same lenght, when needed*)
		rPB_PermValue18 : REAL; (*spare permanent value - replace with new vars of same lenght, when needed*)
		rPB_PermValue19 : REAL; (*spare permanent value - replace with new vars of same lenght, when needed*)
		rPB_PermValue20 : REAL; (*spare permanent value - replace with new vars of same lenght, when needed*)
		rPB_PermValue21 : REAL; (*spare permanent value - replace with new vars of same lenght, when needed*)
		rPB_PermValue22 : REAL; (*spare permanent value - replace with new vars of same lenght, when needed*)
		rPB_PermValue23 : REAL; (*spare permanent value - replace with new vars of same lenght, when needed*)
		rPB_PermValue24 : REAL; (*spare permanent value - replace with new vars of same lenght, when needed*)
		rPB_PermValue25 : REAL; (*spare permanent value - replace with new vars of same lenght, when needed*)
		rPB_PermValue26 : REAL; (*spare permanent value - replace with new vars of same lenght, when needed*)
		rPB_PermValue27 : REAL; (*spare permanent value - replace with new vars of same lenght, when needed*)
		rPB_PermValue28 : REAL; (*spare permanent value - replace with new vars of same lenght, when needed*)
		rPB_PermValue29 : REAL; (*spare permanent value - replace with new vars of same lenght, when needed*)
		rPB_PermValue30 : REAL; (*spare permanent value - replace with new vars of same lenght, when needed*)
		rPB_PermValue31 : REAL; (*spare permanent value - replace with new vars of same lenght, when needed*)
		rPB_PermValue32 : REAL; (*spare permanent value - replace with new vars of same lenght, when needed*)
		rPB_PermValue33 : REAL; (*spare permanent value - replace with new vars of same lenght, when needed*)
		rPB_PermValue34 : REAL; (*spare permanent value - replace with new vars of same lenght, when needed*)
		rPB_PermValue35 : REAL; (*spare permanent value - replace with new vars of same lenght, when needed*)
		rPB_PermValue36 : REAL; (*spare permanent value - replace with new vars of same lenght, when needed*)
		rPB_PermValue37 : REAL; (*spare permanent value - replace with new vars of same lenght, when needed*)
		rPB_PermValue38 : REAL; (*spare permanent value - replace with new vars of same lenght, when needed*)
		rPB_PermValue39 : REAL; (*spare permanent value - replace with new vars of same lenght, when needed*)
		rPB_PermValue40 : REAL; (*spare permanent value - replace with new vars of same lenght, when needed*)
		rPB_PermValue41 : REAL; (*spare permanent value - replace with new vars of same lenght, when needed*)
		rPB_PermValue42 : REAL; (*spare permanent value - replace with new vars of same lenght, when needed*)
		rPB_PermValue43 : REAL; (*spare permanent value - replace with new vars of same lenght, when needed*)
		rPB_PermValue44 : REAL; (*spare permanent value - replace with new vars of same lenght, when needed*)
		rPB_PermValue45 : REAL; (*spare permanent value - replace with new vars of same lenght, when needed*)
		rPB_PermValue46 : REAL; (*spare permanent value - replace with new vars of same lenght, when needed*)
		rPB_PermValue47 : REAL; (*spare permanent value - replace with new vars of same lenght, when needed*)
		rPB_PermValue48 : REAL; (*spare permanent value - replace with new vars of same lenght, when needed*)
		rPB_PermValue49 : REAL; (*spare permanent value - replace with new vars of same lenght, when needed*)
		rPB_PermValue50 : REAL; (*spare permanent value - replace with new vars of same lenght, when needed*)
		iCnt_IslandHours : DINT; (* spare preparation only! island operating hours counter*)
		iCnt_NetPHours : DINT; (* spare preparation only! net parallel operating hours counter*)
		iCnt_DemHours : DINT; (* spare preparation only! demanded hours counter*)
		iIdx_OMSS : DINT; (*spare preparation only!  operation mode selector switch *)
		iIdx_RSS : DINT; (*spare preparation only!  remote selector switch *)
	END_STRUCT;
END_TYPE
