(********************************************************************
 * COPYRIGHT -- INNIO Company
 ********************************************************************
 * Program: GeneralVI
 * File: GeneralVIInit.st
 * Author: 105046866
 * Created: August 29, 2012
 ********************************************************************
 * Implementation of program GeneralVI
 ********************************************************************)

PROGRAM _INIT

	(*--------------------------------------------------------------------------------*)
	(*Parameter FACTORY DEFAULT VALUES *)
	(*for missing/new/not visualized parameter*)

END_PROGRAM

