(*******************************************************************************
outData        copy data to OutData

This code is confidential and proprietary to the INNIO Company.
It may not be used in any form, or reproduced in any manner,
without written permission of the INNIO Company.
Copyright, INNIO Company, 2019

Customized modifications: -
------------------------
 
History:
-------
V0.00.0	17.07.2012	froehlichw	new

Instructions for use:
--------------------

Outstandings:
------------

(*******************************************************************************)

PROGRAM _INIT

END_PROGRAM

