(********************************************************************
gwt	 			 Initialization

This code is confidential and proprietary to the INNIO Company.
It may not be used in any form, or reproduced in any manner,
without written permission of the INNIO Company.
Copyright, INNIO Company, 2019


Customized modifications: -
------------------------
 
History:
-------
														
Instructions for use: - 
--------------------
			
Outstandings:
------------

*******************************************************************************)

PROGRAM _INIT


	
END_PROGRAM
