
TYPE
	IN_GT_struct : 	STRUCT 
		bCH4_Bus_Active : BOOL; (* CH4 content measuring via Bus active *)
		bDemScavVa : BOOL; (*demand scavenging valve*) (*OldName: ANF_SPKL;Cycle:5*)
		bEng_Aux_Dem : BOOL; (*demand auxiliaries *) (* OldName: 	M_ANFHBT	; Cyclic: ; *)
		bEng_Aux_Dem_CDR : BOOL; (*demand auxiliaries with cool down run *) (* OldName: 	ANFHBT	; Cyclic: ; *)
		bEng_Bloc : BOOL; (* blocking engine *) (*OldName:M_BLOCK;Cycle:2;*)
		bEng_CDR : BOOL; (*cool down run *) (* OldName: 	T10	; Cyclic: ; *)
		bEng_Dem : BOOL; (*module demanded *) (* OldName: 	M_AGFD	; Cyclic: ; *)
		bEng_Dem_Aut : BOOL; (*demand automatic mode *) (* OldName: 	M_ANF_A	; Cyclic: ; *)
		bEng_Dem_Bloc : BOOL; (*blocking release of engine *) (* OldName: 	ANFBLO	; Cyclic: ; *)
		bEng_Dem_EPS : BOOL; (*engine demand for emergency operation *) (* OldName: 	M_NANF	; Cyclic: ; *)
		bEng_Start : BOOL; (*engine start command *) (* OldName: 	M_STRT	; Cyclic: ; *)
		bEng_Start_TC2 : BOOL; (*engine start command (updated in cyclic#2 10ms)*) (* OldName: 	M_STRT	; Cyclic: ; *)
		bGasTyp1_Act : BOOL; (*gas type 1 active*) (* OldName: 	AN_GAS1	; Cyclic: ; *)
		bGasTyp2_Act : BOOL; (*gas type 2 active*) (* OldName: 	AN_GAS2	; Cyclic: ; *)
		bGasTyp3_Act : BOOL; (*gas type 3 active*) (* OldName: 	AN_GAS3	; Cyclic: ; *)
		bGasTyp4_Act : BOOL; (*gas type 4 active*) (* OldName: 	AN_GAS4	; Cyclic: ; *)
		bGasTypMix1_2_Act : BOOL; (*gas type mix 1-2 active*) (* OldName: 	AN_GAS1_2	; Cyclic: ; *)
		bGen2_Act : BOOL; (* TRUE = Gen2 Controller active*) (* Oldname: BDC_ON; Cycle: 2 *)
		bGT_Check4FastStart : BOOL; (* Start gas train check to prepare for fast start *)
		bGV_Open_Opstate : BOOL; (*Open gas valve from OP-State module*) (* OldName: 	ZM_GASV	; Cyclic: ; *)
		bLeanox_Active : BOOL; (*TRUE = leanox controller is active *) (* OldName: 	bLeanoxActive	; Cyclic: ; *)
		bLeanox_Man : BOOL; (*TRUE = leanox controller in manual *) (* OldName: 	l_einst_a 	; Cyclic:2; *)
		bLR_GasStop : BOOL; (*close gas valve to react on a load rejection by the GCB and force  actuators (open CBP, close TV)*)
		bMnsOk : BOOL; (*Mains OK *) (* OldName: NE_OK; Cyclic: ; *)
		bMsg1031 : BOOL; (*emergency stop *) (* OldName: 	M_SIS	; Cyclic: ; *)
		bMsg1052 : BOOL; (*gas prealarm *) (* OldName: 	M_GALV	; Cyclic: ; *)
		bMsg1053 : BOOL; (*gas alarm *) (* OldName: 	M_GAL	; Cyclic: ; *)
		bMsg1054 : BOOL; (*fire alarm *) (* OldName: 	M_BAL	; Cyclic: ; *)
		bOptGT_RatioMix_Set : BOOL; (*activation bit for custom gasmixing ratio setpoint - new V4.5*)
		bPBC_Active : BOOL; (* PBC is active, since activation power is reached *)
		bRelEngOpFromSy : BOOL; (*gas supply ok*) (* OldName:F_BLO;Cyclic:2; *)
		bRel_Island : BOOL; (*release island operation *) (* OldName: 	FG_INSEL	; Cyclic:2; *)
		bRel_IslandAfMITime : BOOL; (*jump release island op.after mi-filter time *) (* OldName: 	T79	; Cyclic:2; *)
		bRel_ScavN2 : BOOL; (*conditions for scavenge with N2 *) (* OldName: 	FG_N2	; Cyclic: ; *)
		bSCO_Rel_GV1 : BOOL; (*TRUE = Release for gas valve 1 by glow ignition prevention (safety cut out) *) (* OldName: M_GASV1_1; Cyclic:2; *)
		bSCO_Rel_GV2 : BOOL; (*TRUE = Release for gas valve 2 by glow ignition prevention (safety cut out) *) (* OldName: M_GASV1_2; Cyclic:2; *)
		bSimWinMOD_Active : BOOL; (* WinMOD simulation active *) (* OldName:new PV; Cycle:5*)
		bSimWinMOD_FastStart : BOOL; (* WinMOD fast start of engine*) (* OldName:new PV; Cycle:5*)
		bGT_GrC_Bloc : BOOL; (* Block main gastrain in case of grid event *)
		iIdx_OMSS : INT; (*index of operation mode selector switch *) (* OldName: 	AUTO, MAN, …..	; Cyclic: ; *)
		iSt_OpMode : UDINT; (*engine operation mode *) (*OldName:LeerlM,NetpM,InselM,StartM,StopM;Cycle:5;*)
		mp_a : ARRAY[0..4]OF _tMeasurePoint; (* leanox line meassure point 1 *) (* OldName: mp_a; Cycle:2;*)
		rCH4_Bus : REAL; (* CH4 content via Bus, 1.0 = 100% *)
		bH2_Bus_Active : BOOL; (* Bus - H2 content signal via bus *)
		rH2_Bus : REAL; (* Bus - H2 content in percent. 1.0 = 100% *)
		bH2_Bus_MSF : BOOL; (*Bus - Measurement signal failure. FALSE = Failure *)
		rCust_SparePara : ARRAY[0..200]OF REAL; (*SPS_REZP1 to SPS_REZP200 	*) (* OldName: SPS_REZP1, SPS_REZP2, SPS_REZP70; Cycle: 5; *)
		rGT_RatioMix_Set : REAL; (*custom gasmixing ratio setpoint - new V4.5*)
		rN_EngAct : REAL; (*Actual speed [1/min] *) (* OldName: 	n_ist,   ANA.DREHZ	; Cyclic:2; *)
		rPr_Baro_Internal : REAL; (*Internal value for barometric pressure [bar (abs)]*) (*OldName: newPV; Cycle: 2;*)
		rPr_Ch_P2s_A : REAL; (*charge pressure p2' A [bar]*) (*OldName: AI_PressP2s_A_TC1, AIPressP2s_A, ssPressP2s_A, rPressP2s_A; Cycle: 2;*)
		rPr_Ch_P2s_Avg : REAL; (*Average charge pressure p2' after throttle valve [bar]*) (*OldName: newPV; Cycle: 2;*)
		rPr_Ch_P2s_Avg_UF : REAL; (*unfiltered average charge pressure p2' [bar]*) (*OldName: newPV; Cycle: 2;*)
		rPr_Ch_P2s_B : REAL; (*charge pressure p2' B [bar]*) (*OldName: AI_PressP2s_B_TC1, AIPressP2s_B, ssPressP2s_B, rPressP2s_B; Cycle: 2;*)
		rPr_Leanox_Set : REAL; (* Setpoint boost pressure *) (* Oldname: pl_soll; Cycle: 2*)
		rPumpQuotient : REAL; (*Verhältnis kompensierte Gasmenge zu Gesamtgasmenge - für Pumperkennung*)
		rP_Act_Norm_Filt : REAL; (*actual power related to rP_Nom filtered T=1s *) (* OldName: 	P_IST, ANA.P_IST, PN_GASART	; Cyclic: ; *)
		rP_el_max_red : REAL; (* Calculated power for power reduction GR [kW] *) (*OldName: AI_PressP2s_A_TC1, AIPressP2s_A, ssPressP2s_A, rPressP2s_A; Cycle: 2;*)
		rP_Nom : REAL; (*Nominal electrical power depends on gas type [KW]*) (* OldName:p_nenn; Cyclic: ; *)
		tAB2GT : AmmBase2MM; (*AMM structure *) (* OldName: 	QUITT_WA	; Cyclic:2; *)
		tCnt_GasImp : HALioDi_Type; (*DI	 Impulse gas counter  *) (* OldName: 	GAS_IMP	; Cyclic: ; *)
		tCU2GT : CUSTOM2GASTRAIN_Struct; (*V4.07 new*)
		tCustAnaIn : ARRAY[0..120]OF HALioAi_Type; (*Replacement for RAN_KANAL...*) (*OldName: ANA_RAN	; Cycle: 5;*)
		tCustDigIn : ARRAY[0..200]OF HALioDi_Type; (*new, reserved for Project specific use*) (*OldName: new PV	; Cycle: 5;*)
		tDemFlair : HALioDi_Type; (*DI	 Demand gas compressor for flair operation mode *) (* OldName: 	ANF_V_FA	; Cyclic: ; *)
		tDiffPrct_TC2 : HALioDi_Type; (*DI	 Differential protection  *) (* OldName: 	DIFF	; Cyclic:2; *)
		tEng_Run : HALioDo_Type; (*engine operating state *) (* OldName: 	M_BTRB	; Cyclic: ; *)
		tFastStartReq : HALioDi_Type; (*V4.10 new*)
		tFlairRdy : HALioDi_Type; (*DI	 Flair ready *) (* OldName: 	FA_BER	; Cyclic: ; *)
		tGCB_COf : HALioDo_Type; (*DO	 command gcb off  *) (* OldName: 	AB_GS	; Cyclic:2; *)
		tGCB_On : HALioDi_Type; (*DI	 Generator circuit breaker closed *) (* OldName: GCB_ON_TC1; Cyclic: ; *)
		tGCB_On_TC2 : HALioDi_Type; (*DI Generator circuit breaker closed, TC2 synchron *) (* OldName: GCB_ON_TC1; Cyclic:2; *)
		tGenPrctTrip_TC2 : HALioDi_Type; (*DI	 Generator protection trip *) (* OldName: 	DI_GEN_PT_TC1	; Cyclic:2; *)
		tGndFailure_TC2 : HALioDi_Type; (*DI	 earth failure *) (* OldName: 	ERDS	; Cyclic:2; *)
		tGrC_DCon : HALioDo_Type; (*DO: FALSE = Disconnect from Grid due to GridCode Event*) (* OldName: DO_GRIDCODE_DCON_TC1; Cycle:2; *)
		tGT1_1_BackFireDev : HALioDi_Type; (*DI Antibackfire device P.01-YFA-111*) (* OldName: new PV; Cyclic: ; *)
		tGT1_1_SafeDevOK : HALioDi_Type; (*DI Gassafety device 1 line 1*) (* OldName: F_GAS1_1; Cyclic:5 ; *)
		tGT1_2_BackFireDev : HALioDi_Type; (*DI Antibackfire device P.01-YFA-121*) (* OldName: new PV; Cyclic: ; *)
		tGT1_2_SafeDevOK : HALioDi_Type; (*DI	 Gassafety device 2 line 2*) (* OldName: F_GAS1_2; Cyclic:5; *)
		tGT1_3_BackFireDev : HALioDi_Type; (*DI Antibackfire device P.01-YFA-131*) (* OldName: new PV; Cyclic: ; *)
		tGT1_3_SafeDevOK : HALioDi_Type; (*DI Gassafety device 3 line 3*) (* OldName: F_GAS1_3; Cyclic:5; *)
		tGT1_4_BackFireDev : HALioDi_Type; (*DI Antibackfire device P.01-YFA-141*) (* OldName: new PV; Cyclic: ; *)
		tGT1_4_SafeDevOK : HALioDi_Type; (*DI Gassafety device 4 line 4 *) (* OldName: F_GAS1_4; Cyclic:5; *)
		tGT1_SafeDevOK : HALioDi_Type; (*DI	 Gassafety device 1 *) (* OldName: F_GAS1	; Cyclic:5; *)
		tGT2_SafeDevOK : HALioDi_Type; (*DI	 Gassafety device 2 *) (* OldName: F_GAS2	; Cyclic:5; *)
		tGT_AirSupply_LoLo : HALioDi_Type; (*DI FALSE = compressed air supply pressure for gas train too low - error*) (*Oldname : DI_GT_AirSupply_LoLo Cyclic: 2; *)
		tGT_BackFireDev : HALioDi_Type; (*DI Antibackfire device P.01-YFA-101*) (* OldName: 	FLAMM	; Cyclic: ; *)
		tGT_CalibrateActive : HALioDi_Type; (*DI	 Calibration Gas analysis *) (* OldName: 	CAL_GAS	; Cyclic: ; *)
		tGT_CH4 : HALioAi_Type; (*AI	 CH4 content in percent. 1.0 = 100% *) (* OldName: 	ANA_CH4	; Cyclic: ; *)
		tGT_CV : HALioAi_Type; (*AI	 Calorific value *) (* OldName: 	ANA_CV	; Cyclic: ; *)
		tGT_FlairFail : HALioDi_Type; (*DI	 Flare failure *) (* OldName: 	ST_FA	; Cyclic: ; *)
		tGT_Flap1_Closed : HALioDi_Type; (*DI	 Gas flap 1 closed (Feedback)*) (* OldName: 	KL1_ZU	; Cyclic: ; *)
		tGT_Flap1_Opened : HALioDi_Type; (*DI	 Gas flap 1 opened (Feedback)*) (* OldName: 	KL1_AUF	; Cyclic: ; *)
		tGT_Flap2_Closed : HALioDi_Type; (*DI	 Gas flap 2 closed (Feedback)*) (* OldName: 	KL2_ZU	; Cyclic: ; *)
		tGT_Flap2_Opened : HALioDi_Type; (*DI	 Gas flap 2 opened (Feedback)*) (* OldName: 	KL2_AUF	; Cyclic: ; *)
		tGT_FlareOpMod : HALioDi_Type; (*DI	 Flare in operational mode *) (* OldName: 	RM_FA	; Cyclic: ; *)
		tGT_GC_Fail : HALioDi_Type; (*DI	 Gas compressor failure *) (* OldName: 	ST_GVD	; Cyclic: ; *)
		tGT_O2 : HALioAi_Type; (*AI	 O2 content *) (* OldName: 	ANA_O2	; Cyclic: ; *)
		tGT_SelectRatioMix : HALioDi_Type; (*Demand gas mixing bit*) (*OldName: MISCH; Cycle: 5;*)
		tGT_TypSwitch : HALioDi_Type; (*DI	 Gas type switch to second gas *) (* OldName: 	GUMSCH	; Cyclic: ; *)
		tGV1_Closed : HALioDi_Type; (*DI Gasvalve position status*) (* OldName: F_GAS1_1; Cyclic:5 ; *)
		tGV1_Opened : HALioDi_Type; (*DI Gasvalve position status*) (* OldName: F_GAS1_1; Cyclic:5 ; *)
		tGV2_Closed : HALioDi_Type; (*DI Gasvalve position status*) (* OldName: F_GAS1_1; Cyclic:5 ; *)
		tGV2_Opened : HALioDi_Type; (*DI Gasvalve position status*) (* OldName: F_GAS1_1; Cyclic:5 ; *)
		tGV_Upstream_Closed : HALioDi_Type; (*	DI Gasvalve position status	 *) (*OldName: NewPV *)
		tGV_Upstream_Opened : HALioDi_Type; (*	DI Gasvalve position status	 *) (*OldName: NewPV *)
		tMCB_COf : HALioDo_Type; (*DO	 command mcb off       *) (* OldName: 	AB_NS	; Cyclic:2; *)
		tMCB_On : HALioDi_Type; (*DI mains circuit breaker closed*) (* OldName: MCB_ON; Cyclic: ; *)
		tMCB_On_TC2 : HALioDi_Type; (*DI mains circuit breaker closed, TC2 synchron *) (* OldName: MCB_ON_TC1; Cyclic:2; *)
		tMnsOk_TC2 : HALioDi_Type; (*DI	 Mains OK *) (* OldName: DI_MNS_OK; Cyclic:2; *)
		tN2_ScavGV_CoOpen : HALioDo_Type; (*DO	 N2 Gas Valves vommand open*) (* OldName: 	N2_GASV	; Cyclic: ; *)
		tOlShortCirc_TC2 : HALioDi_Type; (*DI	 Overload/short circuit *) (* OldName: 	ULKS, DI_GCB_OL_TC1	; Cyclic:2; *)
		tPB2MM : ParaBase2MM_type; (*Data exchange structure to ParaBase*) (* OldName: 	new structure	; Cyclic: ; *)
		tPCaComp_BackFireDev : HALioDi_Type; (*DI Antibackfire device prechamper after compressor P.14-TI-002*) (* OldName: new PV; Cyclic: ; *)
		tPCbComp_BackFireDev : HALioDi_Type; (*DI Antibackfire device prechamper before compressor P.14-TI-001*) (* OldName: new PV; Cyclic: ; *)
		tPCGT_SafeDevOK : HALioDi_Type; (*DI Gassafety device Prechamber*) (* OldName: newPV; Cyclic:5; *)
		tPCG_GC_Fail : HALioDi_Type; (*DI	 Failure pre chamber gas compressor*) (* OldName: 	ST_VKGV	; Cyclic: ; *)
		tPCG_GC_Oil_Min : HALioDi_Type; (*DI	 pre chamber gas compressor oil level*) (* OldName: 	OMIN_VERD	; Cyclic: ; *)
		tPr_GR_I : HALioAi_Type; (*AI Gas Pressure in Gas Rail number 1 [bar] *) (* OldName: AIPressGasRail	; Cyclic: 2; *)
		tPr_GR_II : HALioAi_Type; (*AI Gas Pressure in Gas Rail number 2 [bar]*) (* OldName: AIPressGasRail2_TC1; Cyclic: 2; *)
		tPr_GT1 : HALioAi_Type; (*AI	 Gas pressure gas train 1 after filter *) (* OldName: 	AI_p_GT1	; Cyclic: ; *)
		tPr_GT1_1_Max : HALioDi_Type; (*DI	 Gas pressure maximum gas train 1 - line 1*) (* OldName: 	GDMA1	; Cyclic: ; *)
		tPr_GT1_1_Min : HALioDi_Type; (*DI	 Gas pressure low gas train 1 - line 1*) (* OldName: 	GDMI1	; Cyclic: ; *)
		tPr_GT1_2_Max : HALioDi_Type; (*DI	 Gas pressure maximum gas train 1 - line 2*) (* OldName: GDMA1_2; Cyclic: ; *)
		tPr_GT1_2_Min : HALioDi_Type; (*DI	 Gas pressure low gas train 1 - line 2*) (* OldName: 	GDMI1_2	; Cyclic: ; *)
		tPr_GT1_3_Max : HALioDi_Type; (*DI	 Gas pressure maximum gas train 1 - line 3*) (* OldName: GDMA1_3; Cyclic: ; *)
		tPr_GT1_3_Min : HALioDi_Type; (*DI	 Gas pressure low gas train 1 - line 3*) (* OldName: 	GDMI1_3	; Cyclic: ; *)
		tPr_GT1_4_Max : HALioDi_Type; (*DI	 Gas pressure maximum gas train 1 - line 4*) (* OldName: GDMA1_4; Cyclic: ; *)
		tPr_GT1_4_Min : HALioDi_Type; (*DI	 Gas pressure low gas train 1 - line 4*) (* OldName: 	GDMI1_4	; Cyclic: ; *)
		tPr_GT1_Max : HALioDi_Type; (*DI	 Gas pressure maximum gas train 1 *) (* OldName: 	GDMA1	; Cyclic: ; *)
		tPr_GT1_Min : HALioDi_Type; (*DI	 Gas pressure low gas train1 *) (* OldName: 	GDMI1	; Cyclic: ; *)
		tPr_GT2_Max : HALioDi_Type; (*DI	 Gas pressure maximum gas train 2 *) (* OldName: 	GDMA2	; Cyclic: ; *)
		tPr_GT2_Min : HALioDi_Type; (*DI	 Gas pressure low gas train2 *) (* OldName: 	GDMI2	; Cyclic: ; *)
		tPr_GT_Gas : HALioAi_Type; (*AI	 Gas pressure *) (* OldName: 	ANA_GD	; Cyclic: ; *)
		tPr_GT_MinBefCompr : HALioDi_Type; (*DI	 Gas pressure low before gas compressor *) (* OldName: 	GDMI11	; Cyclic: ; *)
		tPr_GT_Suct : HALioAi_Type; (*AI	 Gas suction pressure *) (* OldName: 	ANA_SD	; Cyclic: ; *)
		tPr_MGT_a_Filt : HALioAi_Type; (*AI main gas train pressure after filter [bar]*) (* OldName: AI_p_GT1; Cyclic: 2; *)
		tPr_PC : HALioAi_Type; (*AI	 Pressure prechamber*) (* OldName: PDIFF_WE; Cyclic: ; *)
		tPr_PCG : HALioAi_Type; (*AI	 Pressure pre chamber gas compressor  *) (* OldName: 	ANA_VKGD	; Cyclic: ; *)
		tPr_PCGBefComp_Lo : HALioDi_Type; (*DI suction pressure prechamber gas compressor high*) (*OldName:DI_p_PCGBefComp_Lo; Cycle:5;*)
		tPr_PCGT : HALioAi_Type; (*AI	 Gas pressure pre chamber gas train after filter *) (* OldName: 	AI_p_PCGT	; Cyclic: ; *)
		tPr_PCGT_a_Filt : HALioAi_Type; (*AI Gas pressure pre chamber gas train after filter - PLEASE NOTE: module internal variable, because of EPLAN label compability *) (* OldName: 	AI_p_PCGT	; Cyclic: ; *)
		tPr_PCGT_Out : HALioAi_Type; (*AI Warning measuring signal failure - gas pressure after pre chamber gas pressure regulator*) (* OldName: AI_p_PCGT_Out; Cyclic: 2; *)
		tPr_PCG_Min : HALioDi_Type; (*DI	 Pre chamber gas compressor pressure minimum *) (* OldName: 	VKDMI	; Cyclic: ; *)
		tP_GT_Max_Backfire : HALioDi_Type; (*DI	 gas pressure high - backfire*) (* OldName: 	DI_GDMAX_BF	; Cyclic: ; *)
		tP_Red_CH4Active : HALioDi_Type; (*DI Power limitation because of CH4 content active *) (* OldName: CH4RED_0; Cyclic:5; *)
		tP_Red_GasPrActive : HALioDi_Type; (*DI Power limitation because of gas pressure active *) (* OldName: GD_RED_0; Cyclic:5; *)
		tP_Red_SuctPrActive : HALioDi_Type; (*DI Power limitation because of suction pressure active *) (* OldName: SD_RED_0; Cyclic:5; *)
		tRelGasPlant : HALioDi_Type; (*DI	 Release from gas plant missing. FALSE = Missing *) (* OldName: 	FG_GAS	; Cyclic: ; *)
		tRelMainGVext : HALioDi_Type; (*DI release main gas valve from external *) (*OldName:FG_HGV_ext; Cycle:5*)
		tSafetyLoop_Eng : HALioDi_Type; (*DI	 Safety loop engine *) (* OldName: 	RUHE	; Cyclic: ; *)
		tSIFA_BOV : HALioDi_Type; (*Blow-off system supply circuit breaker tripped*)
		tSys_Run : HALioDo_Type; (*RUN DigitaOut bit to HAL*) (* OldName: 	RUN	; Cyclic: ; *)
		tT_GR : HALioAi_Type; (*AI Gas rail temperature*) (*OldName: AI_GRTP; Cyclic: 2; *)
		tT_GT : HALioAi_Type; (*AI	 Gas temperature *) (* OldName: 	ANA_GT	; Cyclic: ; *)
		tT_GT_Ok : HALioDi_Type; (*DI	 Gas temperature OK *) (* OldName: 	GTMA	; Cyclic: ; *)
		tT_PCGAfCo : HALioAi_Type; (*AI temperature prechamber gas after cooler*) (*OldName:PVnew; Cycle:5;*)
		tT_PCGAfComp_Hi : HALioDi_Type; (*DI temperature prechamber gas compressor outlet high*) (*OldName:DI_t_PCGAfComp_Hi; Cycle:5;*)
		tT_PCGT : HALioAi_Type; (*AI	 Pre chamber gas temperature *) (* OldName: 	AI_t_PC	; Cyclic: ; *)
		tVol_GT : HALioAi_Type; (*AI	 Gas volume *) (* OldName: 	ANA_GM	; Cyclic: ; *)
		tT_GT_NG : HALioAi_Type; (*AI Natural gas temperature mA Signal from customer via interface*) (* OldName: ; Cyclic: ; *)
		tPr_GT_NG : HALioAi_Type; (*AI Natural gas pressure mA Signal from customer via interface*) (* OldName: ; Cyclic: ; *)
		tVol_GT_NG : HALioAi_Type; (*AI Natural gas volume mA Signal from customer via interface*) (* OldName: ; Cyclic: ; *)
		iN_GMU_Devices : INT; (*Number of installed gas metering devices*)
		rP_Set_Min_Norm : REAL; (*Minimal power setpoint related to rP_nom p.u.*)
		rGMU_Pr_DiffGas : ARRAY[0..4]OF REAL; (*Differential Pressure over device [bar]*)
		rP_Set_Unred_Norm : REAL; (*normed power set value without reductions*)
		rGMU_Pos_Valve_Prom : ARRAY[0..4]OF REAL; (*Valve Position [%o]*)
		rP_el_max_red_PCGT : REAL; (* Calculated power for power reduction PCGT [kW] *)
		bGT_CalibrateActive_Bus : BOOL; (* Bus - Calibration Gas analysis *)
		bCV_Bus_Active : BOOL; (* Bus - CV content measuring active *)
		rCV_Bus : REAL; (* Bus - CV content [kWh/Nm3] *)
		bRelGasPlant_Bus_Active : BOOL; (* Bus - Release from gas plant missing active *)
		bRelGasPlant_Bus : BOOL; (*Bus - Release from gas plant missing. FALSE = Missing *)
		bPr_GT1_Min_Cust : BOOL; (*Gas pressure minimum from customized module - TRUE = Minimum*)
		bPr_GT1_Max_Cust : BOOL; (*Gas pressure maximum from customized module - TRUE = Maximum*)
		tGT_H2 : HALioAi_Type; (*AI H2 content in percent. 1.0 = 100% *)
		bLR_Act_DBOV : BOOL; (* bypass valve is in saturation due to load rejection event *)
		tGT_RatioMix_Set : HALioAi_Type; (*AI Gas mixing ratio in percent. 1.0 = 100% *)
		bGCB_by_Customer : BOOL; (*Para: GCB controled by Customer*)
		tP_Lo : HALioDo_Type; (* DO power low (for opening GCB) *)
		rP_Act_Norm : REAL; (* Actual unfiltered power related to rP_Nom *)
		bType6L_GEN1_Island : BOOL; (* Activation of T6 GEN1 island controller improvements for L-version SSTC 23bar BMEP *)
		tP_Act : ARRAY[0..2]OF HALioAi_Type; (* actual electric power [kW] *)
		rFlow_VR_TJ : REAL; (* Volume change V-room for pre chamber gas bypass valve [m3/s] *)
		tPr_GT_b_Reg : HALioAi_Type; (* AI Gas pressure before pressure regulator [bar] (P.01-PI-101) *)
		tPr_GT_a_Reg : HALioAi_Type; (* AI Gas pressure after pressure regulator [bar] (P.01-PI-109) *)
		tPr_N2_GT : HALioAi_Type; (* AI Nitrogen pressure sensor inlet gas train [bar] (P.15-PI-002) *)
		bSafetyPLC_Active : BOOL; (*SAFETY PLC: SafetyPLC is active*) (*OldName: new PV; Cycle: 5;*) (*V04.14.00.00*)
		bSafeOUT_GT1_SafeDevOK : BOOL; (*SAFETY PLC: Gas safety device 1 OK*) (*OldName: new PV; Cycle: 5;*) (*V04.25.00.00*)
		bSafeOUT_GT2_SafeDevOK : BOOL; (*SAFETY PLC: Gas safety device 2 OK*) (*OldName: new PV; Cycle: 5;*) (*V04.25.00.00*)
		bSafeOUT_GT3_SafeDevOK : BOOL; (*SAFETY PLC: Gas safety device 3 OK*) (*OldName: new PV; Cycle: 5;*) (*V04.25.00.00*)
		bSafeOUT_GT4_SafeDevOK : BOOL; (*SAFETY PLC: Gas safety device 4 OK*) (*OldName: new PV; Cycle: 5;*) (*V04.25.00.00*)
		bSafeOUT_DCGA_SafeDevOK : BOOL; (*SAFETY PLC: Gas safety device decentral gas addition OK*) (*OldName: new PV; Cycle: 5;*) (*V04.25.00.00*)
		bSafeOUT_GT1_SD_Dem_PS : BOOL; (*SAFETY PLC: Demand for gas safety device 1 - Physical state*) (*OldName: new PV; Cycle: 5;*) (*V04.25.00.00*)
		bSafeOUT_GT2_SD_Dem_PS : BOOL; (*SAFETY PLC: Demand for gas safety device 2 - Physical state*) (*OldName: new PV; Cycle: 5;*) (*V04.25.00.00*)
		bSafeOUT_GT3_SD_Dem_PS : BOOL; (*SAFETY PLC: Demand for gas safety device 3 - Physical state*) (*OldName: new PV; Cycle: 5;*) (*V04.25.00.00*)
		bSafeOUT_GT4_SD_Dem_PS : BOOL; (*SAFETY PLC: Demand for gas safety device 4 - Physical state*) (*OldName: new PV; Cycle: 5;*) (*V04.25.00.00*)
		bSafeOUT_DCGA_SD_Dem_PS : BOOL; (*SAFETY PLC: Demand for gas safety device DCGA - Physical state*) (*OldName: new PV; Cycle: 5;*) (*V04.25.00.00*)
		bSafeOUT_GV_Open : BOOL; (*SAFETY PLC: At least one gas valve opened*) (*OldName: new PV; Cycle: 5;*) (*V04.25.00.00*)
	END_STRUCT;
	MM2VIS_struct : 	STRUCT 
		bGasMixingActive : BOOL; (*Gas mixing active for Tecjets *) (* OldName: 	bCrossOver	; Cyclic: ; *)
		bGT1_CheckOK : BOOL; (*Gas train 1 check OK*) (* OldName: 	M_GAS1OK	; Cyclic: ; *)
		bGT1_FailureTest : BOOL; (*Failure gastrain 1*) (* OldName: 	M_STGAS1	; Cyclic: ; *)
		bGT1_SafeDevice : BOOL; (*DO	 Gas safety device 1 *) (* OldName: A_GAS1; Cyclic:; *)
		bGT2_CheckOK : BOOL; (*Gas train 2 check OK*) (* OldName: 	M_GAS2OK	; Cyclic: ; *)
		bGT2_FailureTest : BOOL; (*Failure gastrain 2*) (* OldName: 	M_STGAS2	; Cyclic: ; *)
		bGT2_SafeDevice : BOOL; (*DO	 Gas safety device 2 *) (* OldName: A_GAS2	; Cyclic:; *)
		bGT_FS_Release : BOOL; (* Release FastStart from Gastrain *)
		bGT_Ipol12Active : BOOL; (*Interpolation Gas1 & 2 active from CH4(or CV)*) (* OldName: 	GAS1_2	; Cyclic: ; *)
		bGV1_Open : BOOL; (*Open gas valve 1*) (* OldName: 	GASV1	; Cyclic: ; *)
		bGV2_Open : BOOL; (*Open gas valve 2*) (* OldName: 	GASV2	; Cyclic: ; *)
		bGV_On : BOOL; (*Gas valves On*) (* OldName: 	M_GASV	; Cyclic: ; *)
		bMGT_BOV : BOOL; (*BlowOff valve*) (*Oldname: DO_BOV_GT1_TC1;*)
		bMsg1027 : BOOL; (*Gas train 1 failure *) (* OldName: 	M_GST1	; Cyclic: ; *)
		bMsg1028 : BOOL; (*Gas train 1 gas pressure low *) (* OldName: 	M_GDMI1	; Cyclic: ; *)
		bMsg1029 : BOOL; (*Gas train 2 failure *) (* OldName: 	M_GST2	; Cyclic: ; *)
		bMsg1030 : BOOL; (*Gas train 2 gas pressure low *) (* OldName: 	M_GDMI2	; Cyclic: ; *)
		bMsg1057 : BOOL; (*Gas train 1 gas pressure high *) (* OldName: 	M_GDMA1	; Cyclic: ; *)
		bMsg1058 : BOOL; (*Gas train 1 gas pressure high *) (* OldName: 	M_GDMA2	; Cyclic: ; *)
		bMsg1084 : BOOL; (*Measuring signal failure prechamber gas pressure*) (* OldName: M_MS_VKDR; Cyclic: ; *)
		bMsg1085 : BOOL; (*Pressure prechamber maximum *) (* OldName: 	M_VKDR_MX	; Cyclic: ; *)
		bMsg1086 : BOOL; (* CH4 content minimum *) (* OldName: 	CH4_MIN_A	; Cyclic: ; *)
		bMsg1087 : BOOL; (*O2 content high  *) (* OldName: 	O2_MAX	; Cyclic: ; *)
		bMsg1088 : BOOL; (*measuring signal failure O2 content *) (* OldName: 	MS_O2_A	; Cyclic: ; *)
		bMsg1094 : BOOL; (*Deflagration protection *) (* OldName: 	M_PUFF	; Cyclic: ; *)
		bMsg1095 : BOOL; (*Pre chamber gas pressure low *) (* OldName: 	ALM[1095].SET	; Cyclic: ; *)
		bMsg1128 : BOOL; (* 1128 Antibackfire device *) (* OldName: 	M_FLAMM	; Cyclic: ; *)
		bMsg1251 : BOOL; (*selection gas type 1_2 *) (* OldName: bAMM[1251]; Cyclic: ; *)
		bMsg1252 : BOOL; (*selection ign. point 1_2 *) (* OldName: bAMM[1252]; Cyclic: ; *)
		bMsg1265 : BOOL; (*	Demand gas leakage check gas train 1 *) (*OldName: *)
		bMsg1266 : BOOL; (*	Release from gas leakage check gas train 1 *) (*OldName: *)
		bMsg1267 : BOOL; (*	Demand gas leakage check gas train 2 *) (*OldName: *)
		bMsg1268 : BOOL; (*	Release from gas leakage check gas train 2 *) (*OldName: *)
		bMsg1269 : BOOL; (* *) (*OldName: *)
		bMsg1270 : BOOL; (* *) (*OldName: *)
		bMsg1271 : BOOL; (* *) (*OldName: *)
		bMsg1272 : BOOL; (* *) (*OldName: *)
		bMsg2231 : BOOL; (*A2231 Measuring signal failure gas rail pressure I *) (* OldName: ALM[2231]; Cyclic: ; *)
		bMsg2240 : BOOL; (*Gas rail temperature high*) (* OldName: bAN_GRTP; Cyclic: ; *)
		bMsg2241 : BOOL; (*Gas rail temperature low*) (* OldName: bAN_GRTP_MIN; Cyclic: ; *)
		bMsg2243 : BOOL; (*gas train 1 gas pressure after filter low *) (* OldName: 	p_GT1_lo1	; Cyclic: ; *)
		bMsg2244 : BOOL; (*Gas rail pressure high*) (* OldName: bAN_GRPRA_MAX; Cyclic: ; *)
		bMsg2245 : BOOL; (*Gas rail pressure low*) (* OldName: bAN_GRPRA_MIN; Cyclic: ; *)
		bMsg2246 : BOOL; (*gas train 1 gas pressure after filter high *) (* OldName: 	p_GT1_hi1	; Cyclic: ; *)
		bMsg2247 : BOOL; (*Measuring signal failure gas pressure after filter gas train *) (* OldName: 	MS_p_GT1	; Cyclic: ; *)
		bMsg2248 : BOOL; (*Gas rail differential pressure high *) (* OldName: bAN_PDGRA_MAX; Cyclic: ; *)
		bMsg2249 : BOOL; (*Gas rail differential pressure low*) (* OldName: bAN_PDGRA_MIN; Cyclic: ; *)
		bMsg2250 : BOOL; (*Trip	 pre chamber gas train gas pressure after filter low *) (* OldName: 	p_PCGT_low	; Cyclic: ; *)
		bMsg2251 : BOOL; (*Trip	 pre chamber gas train gas pressure after filter high *) (* OldName: 	p_PCGT_hi1	; Cyclic: ; *)
		bMsg2257 : BOOL; (*Measuring signal failure gas pressure after filter pre chamber gas train *) (* OldName: 	MS_p_PCGT	; Cyclic: ; *)
		bMsg2261 : BOOL; (*2261 Gas rail pressure higher than barometric pressure*) (* OldName: ALM[ 2261 ] ; Cyclic: ; *)
		bMsg2271 : BOOL; (*2271 Gas rail pressure lower than barometric pressure *) (* OldName: ALM[ 2271 ] ; Cyclic: ; *)
		bMsg2272 : BOOL; (*2272 Measuring signal failure gas rail pressure B*) (* OldName: ALM[2272] ; Cyclic: ; *)
		bMsg2273 : BOOL; (*2273 deviation gas rail pressure*) (* OldName: bDevPGasRailTooHigh ; Cyclic: ; *)
		bMsg2289 : BOOL; (*A2289 Gas train: Compressed air supply failure*) (* OldName: ALM[ 2289 ] ; Cyclic: ;  *)
		bMsg2301 : BOOL; (*Prechamber pressure high at load rejection - blow off valve defect *) (*OldName: AI_GRTP; Cyclic: ;*)
		bMsg2309 : BOOL; (* *) (*OldName: new PV; Cyclic: ; *)
		bMsg2314 : BOOL; (* *) (*OldName: new PV; Cyclic: ; *)
		bMsg2443 : BOOL; (* *) (*OldName: new PV; Cyclic: ; *)
		bMsg2444 : BOOL; (* *) (*OldName: new PV; Cyclic: ; *)
		bMsg2445 : BOOL; (* *) (*OldName: new PV; Cyclic: ; *)
		bMsg2462 : BOOL; (* *) (*OldName: new PV; Cyclic: ; *)
		bMsg2463 : BOOL; (* *) (*OldName: new PV; Cyclic: ; *)
		bMsg2465 : BOOL; (* *) (*OldName: new PV; Cyclic: ; *)
		bMsg2466 : BOOL; (* *) (*OldName: new PV; Cyclic: ; *)
		bMsg2467 : BOOL; (* *) (*OldName: new PV; Cyclic: ; *)
		bMsg2535 : BOOL; (*gas train 1 gas pressure after filter low 2 *) (* OldName: 	p_GT1_lo2	; Cyclic: ; *)
		bMsg2536 : BOOL; (*gas train 1 gas pressure after filter high 2 *) (* OldName: 	p_GT1_hi2	; Cyclic: ; *)
		bMsg2537 : BOOL; (*Warning	 pre chamber gas train gas pressure after filter low *) (* OldName: 	p_PCGT_lo2	; Cyclic: ; *)
		bMsg2538 : BOOL; (*Warning	 pre chamber gas train gas pressure after filter high *) (* OldName: 	p_PCGT_hi2	; Cyclic: ; *)
		bMsg2567 : BOOL; (*Measuring signal failure gas rail temperature*) (*OldName: *)
		bMsg2568 : BOOL; (*Gas rail temperature high*) (*OldName: *)
		bMsg2569 : BOOL; (*Gas rail temperature low*) (*OldName: *)
		bMsg2570 : BOOL; (* *) (*OldName: new PV; Cyclic: ; *)
		bMsg2578 : BOOL; (*Measurement signal failure pre chamber gas temperature *) (* OldName: 	MS_t_PC	; Cyclic: ; *)
		bMsg2580 : BOOL; (*Gas rail differential pressure high*) (*OldName: *)
		bMsg2581 : BOOL; (*Gas rail differential pressure low*) (*OldName: *)
		bMsg2674 : BOOL; (*Prechamber pressure high at load rejection - blow off valve defect *) (*OldName: AI_GRTP; Cyclic: ;*)
		bMsg2694 : BOOL; (*Gas pressure low in gas train 1 line 2*) (* OldName: new PV; Cyclic: ; *)
		bMsg2695 : BOOL; (*Gas pressure low in gas train 1 line 3*) (* OldName: new PV; Cyclic: ; *)
		bMsg2696 : BOOL; (*Gas pressure low in gas train 1 line 4*) (* OldName: new PV; Cyclic: ; *)
		bMsg2753 : BOOL; (*Blow-off system supply circuit breaker tripped *) (* OldName: new PV; Cyclic: ; *)
		bMsg2927 : BOOL; (* *) (*OldName: new PV; Cyclic: ; *)
		bMsg2928 : BOOL; (* *) (*OldName: new PV; Cyclic: ; *)
		bMsg2990 : BOOL; (*BETA V4.07*) (*OldName: new PV; Cyclic: ; *)
		bMsg2991 : BOOL; (*BETA V4.07*) (*OldName: new PV; Cyclic: ; *)
		bMsg2992 : BOOL; (*BETA V4.07*) (*OldName: new PV; Cyclic: ; *)
		bMsg2993 : BOOL; (*BETA V4.07*) (*OldName: new PV; Cyclic: ; *)
		bMsg2994 : BOOL; (*BETA V4.07*) (*OldName: new PV; Cyclic: ; *)
		bMsg2995 : BOOL; (*BETA V4.07*) (*OldName: new PV; Cyclic: ; *)
		bMsg2996 : BOOL; (*BETA V4.07*) (*OldName: new PV; Cyclic: ; *)
		bMsg2997 : BOOL; (*BETA V4.07*) (*OldName: new PV; Cyclic: ; *)
		bMsg3004 : BOOL; (*Difference pressure prechamber minimum *) (* OldName: 	M_PDIFF_MN	; Cyclic: ; *)
		bMsg3153 : BOOL; (*Release from gas plant missing *) (* OldName: 	FGGAS	; Cyclic: ; *)
		bMsg3154 : BOOL; (* CH4-content minimum*) (* OldName: 	CH4_MIN_W	; Cyclic: ; *)
		bMsg3155 : BOOL; (*Measurement signal CH4 *) (* OldName: 	MS_CH4	; Cyclic: ; *)
		bMsg3156 : BOOL; (*Measurement signal Gas pressure *) (* OldName: 	MS_GD	; Cyclic: ; *)
		bMsg3157 : BOOL; (*Measuring signal suction pressure *) (* OldName: 	MS_SD	; Cyclic: ; *)
		bMsg3158 : BOOL; (*Measuring signal failure O2 content *) (* OldName: 	MS_O2_W	; Cyclic: ; *)
		bMsg3159 : BOOL; (*Measurement signal Gas temperature *) (* OldName: 	MS_GT	; Cyclic: ; *)
		bMsg3160 : BOOL; (*Measurement signal Gas quantity *) (* OldName: 	MS_GM	; Cyclic: ; *)
		bMsg3221 : BOOL; (*Gas pressure low in gas train 1 *) (* OldName: 	GD_MIN_W	; Cyclic: ; *)
		bMsg3222 : BOOL; (*Gas pressure low in gas train 2 *) (* OldName: 	M_GDMI2W	; Cyclic: ; *)
		bMsg3227 : BOOL; (*Backfire*) (* OldName: bAMM[3227]; Cyclic: ; *)
		bMsg3257 : BOOL; (*Selection gas type 1/3 *) (* OldName: bAMM[3257]; Cyclic: ; *)
		bMsg3258 : BOOL; (*Selection gas type 1-2/3 *) (* OldName: bAMM[3258]; Cyclic: ; *)
		bMsg3259 : BOOL; (*Selection ignition point 1/3 *) (* OldName: bAMM[3259]; Cyclic: ; *)
		bMsg3260 : BOOL; (*Selection gas type 1-2/3 *) (* OldName: bAMM[3260]; Cyclic: ; *)
		bMsg3261 : BOOL; (*Selection gas quality manual*) (* OldName: bMisch1_2_Man; Cyclic: ; *)
		bMsg3262 : BOOL; (*Selection gas mixture manual *) (* OldName: 	bSetMix_Man	; Cyclic: ; *)
		bMsg3308 : BOOL; (*Pressure pre chamber gas compressor measuring signal failure*) (* OldName: M_MSVKGD; Cyclic: ; *)
		bMsg3309 : BOOL; (*Pressure pre chamber gas compressor high *) (* OldName: 	VKGD_MAX	; Cyclic: ; *)
		bMsg3315 : BOOL; (* A3315 pre chamber gas compressor oil level low *) (* OldName: 	M_OMIN_V	; Cyclic: ; *)
		bMsg3316 : BOOL; (*Trip	 Gas compressor failure *) (* OldName: 	ALM[3316].SET	; Cyclic: ; *)
		bMsg3317 : BOOL; (*Trip	 Gas temperature high *) (* OldName: 	ALM[3317].SET	; Cyclic: ; *)
		bMsg3318 : BOOL; (*Trip	 Gas pressure low before gas compressor *) (* OldName: 	ALM[3318].SET	; Cyclic: ; *)
		bMsg3320 : BOOL; (*pressure pre chamber gas train measuring signal failure*) (*OldName: M_MSpPCGTA;Cyclic:;*)
		bMsg3324 : BOOL; (* 3324 Failure pre chamber gas compressor *) (* OldName: 	bPv	; Cyclic: ; *)
		bMsg3325 : BOOL; (* 3325 Gas pressure high - backfire *) (* OldName: 	bPv	; Cyclic: ; *)
		bMsg3326 : BOOL; (*Idling period gas compressor maximum *) (* OldName: 	ALM[3326].SET	; Cyclic: ; *)
		bMsg3327 : BOOL; (*Trip	 Gas pressure before gas compressor measuring signal failure *) (* OldName: 	ALM[3327].SET	; Cyclic: ; *)
		bMsg3328 : BOOL; (*Trip	 Gas temperature measuring signal failure *) (* OldName: 	ALM[3328].SET	; Cyclic: ; *)
		bMsg3353 : BOOL; (*gas pressure low gas train 1 - line 2*) (*OldName: newPV; Cyclic: ; *)
		bMsg3354 : BOOL; (*gas pressure low gas train 1 - line 3*) (*OldName: newPV; Cyclic: ; *)
		bMsg3355 : BOOL; (*gas pressure low gas train 1 - line 4*) (*OldName: newPV; Cyclic: ; *)
		bMsg3356 : BOOL; (*gas train 1 gas pressure high - line 2*) (*OldName: newPV; Cyclic: ; *)
		bMsg3357 : BOOL; (*gas train 1 gas pressure high - line 3*) (*OldName: newPV; Cyclic: ; *)
		bMsg3358 : BOOL; (*gas train 1 gas pressure high - line 4*) (*OldName: newPV; Cyclic: ; *)
		bMsg3359 : BOOL; (*failure gas train 1 - line 2*) (*OldName: M_GST1_2; Cyclic: ; *)
		bMsg3360 : BOOL; (*failure gas train 1 - line 3*) (*OldName: M_GST1_3; Cyclic: ; *)
		bMsg3361 : BOOL; (*failure gas train 1 - line 4*) (*OldName: M_GST1_4; Cyclic: ; *)
		bMsg3362 : BOOL; (*suction pressure prechamber gas compressor high*) (*OldName: DI_p_PCGBefComp_Lo; Cyclic: 5; *)
		bMsg3363 : BOOL; (*temperature prechamber gas compressor outlet high*) (*OldName: DI_t_PCGAfComp_Hi; Cyclic: 5; *)
		bMsg3364 : BOOL; (*temperature prechamber gas after cooler high*) (*OldName: new; Cyclic: 5; *)
		bMsg3365 : BOOL; (*signal failure temperature prechamber gas after cooler*) (*OldName: new; Cyclic: 5; *)
		bMsg3376 : BOOL; (*A3376 Main gas train set- to actual-gas pressure deviation*) (* OldName: ALM[ 3376 ] ; Cyclic: ; *)
		bMsg3377 : BOOL; (*Calorific value signal failure*) (* OldName: MS_CV; Cyclic: ; *)
		bMsg3387 : BOOL; (*Backfire gas train 1 - line 1*) (* OldName: new PV; Cyclic: ; *)
		bMsg3388 : BOOL; (*Backfire gas train 1 - line 2*) (* OldName: new PV; Cyclic: ; *)
		bMsg3389 : BOOL; (*Backfire gas train 1 - line 3*) (* OldName: new PV; Cyclic: ; *)
		bMsg3390 : BOOL; (*Backfire gas train 1 - line 4*) (* OldName: new PV; Cyclic: ; *)
		bMsg3391 : BOOL; (*Antibackfire device prechamper before compressor*) (* OldName: new PV; Cyclic: ; *)
		bMsg3392 : BOOL; (*Antibackfire device prechamper after compressor*) (* OldName: new PV; Cyclic: ; *)
		bMsg3398 : BOOL; (*Prechamber gas train failure *) (* OldName: newPV; Cyclic: ; *)
		bMsg3444 : BOOL; (*W3444 Main gas train set- to actual-gas pressure deviation*) (* OldName: ALM[3444  ] ; Cyclic: ; *)
		bMsg3445 : BOOL; (*W3445 Pre chamber gas train set- to actual-gas pressure deviation *) (* OldName: ALM[ 3445 ] ; Cyclic: ; *)
		bMsg3448 : BOOL; (*Calorific value signal failure*) (* OldName: *)
		bMsg3520 : BOOL; (*Flare failure *) (* OldName: 	ALM[3520].SET	; Cyclic: ; *)
		bMsg3525 : BOOL; (*Calorific value signal failure*) (* OldName: MS_CV; Cyclic: ; *)
		bMsg3567 : BOOL; (*Warning	 Gas compressor failure *) (* OldName: 	ALM[3567].SET	; Cyclic: ; *)
		bMsg3568 : BOOL; (*Flare failure *) (* OldName: 	ALM[3568].SET	; Cyclic: ; *)
		bMsg3569 : BOOL; (*Warning	 Gas pressure low before gas compressor *) (* OldName: 	ALM[3569].SET	; Cyclic: ; *)
		bMsg3570 : BOOL; (*Warning	 Gas pressure before gas compressor measuring signal failure *) (* OldName: 	ALM[3570].SET	; Cyclic: ; *)
		bMsg9259 : BOOL; (*BETA V4.07*) (*OldName: new PV; Cyclic: ; *)
		bMsg9260 : BOOL; (*BETA V4.07*) (*OldName: new PV; Cyclic: ; *)
		bMsg9275 : BOOL; (*BETA V4.07*) (*OldName: new PV; Cyclic: ; *)
		bMsg9276 : BOOL; (*BETA V4.07*) (*OldName: new PV; Cyclic: ; *)
		bMsg2346 : BOOL;
		bMsg2976 : BOOL;
		bMsg9086 : BOOL; (*Gas valves open*)
		bMsg9087 : BOOL; (*Gas valves closed*)
		bMsg9509 : BOOL; (*W9509 Pre chamber gas bypass valve malfunction *)
		bMsgDummy_Max_SuctPr : BOOL; (*Suction pressure maximum *) (* OldName: 	new PV	; Cyclic: ; *)
		bMsgDummy_Min_SuctPr : BOOL; (*Suction pressure minimum *) (* OldName: 	new PV	; Cyclic: ; *)
		bMsg_Dummy_Trip_CV : BOOL; (*Trip	 calorific value minimum *) (* OldName: 	new PV	; Cyclic: ; *)
		bMsg_Dummy_Warn_CV : BOOL; (*Warning	 calorific value minimum *) (* OldName: 	new PV	; Cyclic: ; *)
		bPCG_GV_Open : BOOL; (*Pre chamber gas valves*) (* OldName: 	VKGV	; Cyclic: ; *)
		bPCG_BPV_Open : BOOL; (*Pre chamber gas bypass valve*)
		bSelGasTyp0 : BOOL; (*Selection of gas type 0*) (* OldName: 	GAS1_2_MAN	; Cyclic: ; *)
		bSelGasTyp1 : BOOL; (*Selection of gas type 1*) (* OldName: 	GAS1	; Cyclic: ; *)
		bSelGasTyp2 : BOOL; (*Selection of gas type 2*) (* OldName: 	GAS2	; Cyclic: ; *)
		bSelGasTyp3 : BOOL; (*Selection of gas type 3*) (* OldName: 	GAS3	; Cyclic: ; *)
		bSelGasTyp4 : BOOL; (*Selection of gas type 4*) (* OldName: 	GAS4	; Cyclic: ; *)
		bSelGasTypAut : BOOL; (*Selection of automatic gas type switching*) (* OldName: 	AUTGAS	; Cyclic: ; *)
		bSelGasTypMix : BOOL; (*Selection of mixed gas *) (* OldName: 	GAS1_3_MAN	; Cyclic: ; *)
		iCnt_Gas_NormM3 : DINT; (*Normal cubic meter*) (* OldName: 	; Cyclic: ; *)
		iCnt_Gas_OpM3 : DINT; (*Operation cubic meter*) (* OldName: 	; Cyclic: ; *)
		iIdx_Gtyp_Act : INT; (*Actual gassort for VISU display*) (* OldName: ucGasType; Cyclic: ; *)
		iIdx_Gtyp_Dem : INT; (*Actual gassort 1..4*) (* OldName: 	gasart	; Cyclic: ; *)
		iMsg2927 : INT; (* *) (*OldName: new PV; Cyclic: ; *)
		iMsg2928 : INT; (* *) (*OldName: new PV; Cyclic: ; *)
		rDPr_MGT_SetAct : REAL; (*main gas train set-/actual-pressure deviation [bar]*) (* OldName: *)
		rDPr_PCGT_SetAct : REAL; (*pre chamber gas train set-/actual-pressure deviation [bar]*) (* OldName: *)
		rGT_CH4 : REAL; (*CH4 content, 1.0 = 100% *) (* OldName: 	ANA_CH4	; Cyclic: ; *)
		rGT_CV : REAL; (*Calorific value *) (* OldName: 	ANA_CV	; Cyclic: ; *)
		rGT_O2 : REAL; (*O2 content *) (* OldName: 	ANA_O2	; Cyclic: ; *)
		rGT_QualMix_1_2 : REAL; (*Mixture ratio bet. gas 1 and 2  *) (* OldName: 	ssMisch1_2	; Cyclic: ; *)
		rGT_RatioMix : REAL; (*Gas mixture rate after ramp fub [%], e.g. 0.5 = 50%*) (* OldName: 	ssRatioMix	; Cyclic: ; *)
		rPr_GR_Avg : REAL; (*Average of 2 Inputs gas rail pressure - average filtered [bar]*) (* OldName: *)
		rPr_GT_Gas : REAL; (*Gas pressure *) (* OldName: 	ANA_GD	; Cyclic: ; *)
		rPr_GT_Suct : REAL; (*Gas suction pressure *) (* OldName: 	ANA_SD	; Cyclic: ; *)
		rPr_MGT_a_Filt : REAL; (*main gas train pressure after filter [bar]*) (* OldName: p_GT1*)
		rPr_MGT_Diff : REAL; (*Difference pressure gas rail to charge pressure*) (*OldName: dp_GR; Cyclic: ; *)
		rPr_MGT_Out_Calc : REAL; (*calculated gas pressure after main gas pressure regulator [bar]*) (* OldName: *)
		rPr_MGT_sp : REAL; (*main gas train pressure - set point [bar]*) (* OldName: p_GR_sp*)
		rPr_PC : REAL; (*Pressure prechamber*) (* OldName: 	ANA_VKDR	; Cyclic: ; *)
		rPr_PCG : REAL; (*Pressure pre chamber gas compressor  *) (* OldName: 	ANA_VKGD	; Cyclic: ; *)
		rPr_PCGT : REAL; (*Gas pressure pre chamber gas train after filter *) (* OldName: p_PCGT1; Cyclic: ; *)
		rPr_PCGT_a_Filt : REAL; (*Gas pressure pre chamber gas train after filter *) (*OldName: p_PCGT1; Cyclic: ; *)
		rPr_PCGT_Out : REAL; (*Warning measuring signal failure - gas pressure after pre chamber gas pressure regulator*) (* OldName: *)
		rPr_PCGT_sp : REAL; (*	pre chamber gas train pressure - set point [bar]*) (* OldName: p_PC_sp*)
		rPr_PC_Diff : REAL; (*Prechamber differential pressure*) (* OldName: 	ANA_PDIFF	; Cyclic: ; *)
		rP_Red_CH4_Norm : REAL; (*power reduction due to CH4 low [%], e.g. 0.75 =75% power of nominal power   *) (* OldName: 	RED_CH4	; Cyclic: ; *)
		rP_Red_CV_Norm : REAL; (*power reduction due to Calorific value low [%], e.g. 0.75 =75% power of nominal power   *) (* OldName: 	RED_CV	; Cyclic: ; *)
		rP_Red_GasPr_Norm : REAL; (*power reduction due to gas pressure low [%], e.g. 0.75 =75% power of nominal power    *) (* OldName: 	RED_GD	; Cyclic: ; *)
		rP_Red_Pr_PCGT_Norm : REAL; (*power reduction by pre chamber gas pressure*) (* OldName: 	ssPowerRedVKG	; Cyclic: ; *)
		rP_Red_SuctPr_Norm : REAL; (*power reduction due to suction pressure high [%], e.g. 0.75 =75% power of nominal power   *) (* OldName: 	RED_SD	; Cyclic: ; *)
		rT_GR : REAL; (*Gas rail temperature*) (*OldName: AI_GRTP; Cyclic: ;*)
		rT_GT : REAL; (*Gas temperature *) (* OldName: 	ANA_GT	; Cyclic: ; *)
		rT_PCGAfCo : REAL; (* temperature prechamber gas after cooler*) (*OldName:PVnew; Cycle:5;*)
		rT_PCGT : REAL; (*Pre chamber gas temperature *) (* OldName: 	AI_t_PC	; Cyclic: ; *)
		rVol_GT : REAL; (*Gas volume *) (* OldName: 	ANA_GM	; Cyclic: ; *)
		tCtr_GC_Out : _tGeACtrOut; (*controller gas compressor*) (*OldName:REG16; Cycle:5;*)
		tGV1_struct : gv_struct; (*BETA V4.07	*) (*OldName: new PV; Cyclic: ; *)
		tGV2_struct : gv_struct; (*BETA V4.07	*) (*OldName: new PV; Cyclic: ; *)
		tGV_Upstream_struct : gv_struct; (*BETA V4.07	*) (*OldName: new PV; Cyclic: ; *)
		rT_GT_NG : REAL; (*Natural gas temperature mA Signal from customer via interface*) (* OldName: ; Cyclic: ; *)
		rPr_GT_NG : REAL; (*Natural gas pressure mA Signal from customer via interface*) (* OldName: ; Cyclic: ; *)
		rVol_GT_NG : REAL; (*Natural gas volume mA Signal from customer via interface*) (* OldName: ; Cyclic: ; *)
		bMsg9300 : BOOL; (*Natural gas temperature measurement signal failure*)
		bMsg9301 : BOOL; (*Natural gas pressure measurement signal failure*)
		bMsg9302 : BOOL; (*Natural gas volume measurement signal failure*)
		rGT_H2 : REAL; (* Filtered H2 content [%] *)
		bMsg9360 : BOOL; (* W9360 - H2 content measuring signal failure *)
		bMsg9361 : BOOL; (* W9361 - H2 content high - warning *)
		bMsg2364 : BOOL; (* A2364 - H2 content high - alarm *)
		bMsg9371 : BOOL; (* W9371 - Measuring signal failure setpoint - Gas mixing *)
		bMsg9387 : BOOL; (* W9387 - Prechamber gas pressure low *)
		bMsg9402 : BOOL; (* A9402 - Gas pressure before regulator in gas train maximum *)
		bMsg9403 : BOOL; (* A9403 - Gas pressure after regulator in gas train maximum *)
		bMsg9404 : BOOL; (* A9404 - Gas pressure N2 maximum *)
		bMsg9405 : BOOL; (* A9405 - Gas pressure N2 minimum *)
		bMsg9406 : BOOL; (* A9406 - Gas differential pressure regulator maximum *)
		bMsg9432 : BOOL; (* A9432 - Measuring signal failure gas pressure before regulator in gas train *)
		bMsg9511 : BOOL; (* W9511 - Measuring signal failure gas pressure after regulator in gas train *)
		bMsg9512 : BOOL; (* W9512 - Measuring signal failure gas pressure N2 *)
		rPr_GT_b_Reg : REAL; (* Gas pressure before pressure regulator [bar] *)
		rPr_GT_a_Reg : REAL; (* Gas pressure after pressure regulator [bar] *)
		rPr_N2_GT : REAL; (* Nitrogen pressure sensor inlet gas train [bar] *)
		bMGT_BOV_Open : BOOL; (* Blow off valve open *)
		bN2_GV_Open : BOOL; (* N2 valve open *)
	END_STRUCT;
	OUT_GT_struct : 	STRUCT 
		bAMM_Pr_MGT_a_Filt_BlockStart : BOOL; (*Block engine start after 5 times W2462 Measuring signal failure gas pressure after filter in main gas train*) (* OldName: new PV ; Cycle: 5;*)
		bAMM_Pr_PCGT_a_Filt_BlockStart : BOOL; (*Block engine start after 5 times W2465 Measuring signal failure gas pressure after filter in prechamber gas train*) (* OldName: new PV ; Cycle: 5;*)
		bCnt_Gas_NormM3 : BOOL; (*Normal cubic meter - Impulse*) (* OldName: NORM_M3; Cyclic: ; *)
		bCnt_Gas_OpM3 : BOOL; (*Operation cubic meter - Impulse*) (* OldName: BTRB_M3; Cyclic: ; *)
		bDeflagrationPrct : BOOL; (*Deflagration protection*) (* OldName: 	PUFF	; Cyclic: ; *)
		bDualTJ : BOOL; (*Gas mixing with two TecJet´s*) (*OldName: bDualTJ; Cycle: 2 ; *)
		bGasMixingActive : BOOL; (*TRUE = Gas mixing is active for TecJet's *) (* OldName: 	bCrossOver	; Cyclic: ; *)
		bGasSupplyOk : BOOL; (*Gas Supply OK *) (* OldName: 	GAS_OK	; Cyclic: ; *)
		bGT1_Check : BOOL; (*Gas train check 1 *) (* OldName: 	T88	; Cyclic: ; *)
		bGT1_CheckOK : BOOL; (*Gas train 1 check OK *) (* OldName: 	M_GAS1OK	; Cyclic: ; *)
		bGT1_SafeDevOK : BOOL; (*Gassafety device 1 release (From DI and task) *) (* OldName: F_GAS1	; Cyclic:5; *)
		bGT2_Check : BOOL; (*Gas train check 2 *) (* OldName: 	T90	; Cyclic: ; *)
		bGT2_CheckOK : BOOL; (*Gas train 2 check OK *) (* OldName: 	M_GAS2OK	; Cyclic: ; *)
		bGT2_SafeDevOK : BOOL; (*Gassafety device 2 release (From DI*)
		bGT2_Select : BOOL; (*Selection gas train 2 *) (* OldName: 	ANW_GST2	; Cyclic: ; *)
		bGT_DemRelGasTypSwh : BOOL; (*Demand release for gas type switching *) (* OldName: 	ANF_ENTL	; Cyclic: ; *)
		bGT_Ipol12Active : BOOL; (*Interpolation Gas1 & 2 active from CH4(or CV)*) (* OldName: 	GAS1_2	; Cyclic: ; *)
		bGT_Rel : BOOL; (*Release gas train *) (* OldName: 	FG_GST	; Cyclic: ; *)
		bGT_RelMixing : BOOL; (*Release gas mixing controller *) (* OldName: 	FG_MISCH	; Cyclic: ; *)
		bGT_SelGas1 : BOOL; (*Selection gas 1 *) (* OldName: 	M_AWGAS1	; Cyclic: ; *)
		bGT_SelGas2 : BOOL; (*Selection gas 2 *) (* OldName: 	M_AWGAS2	; Cyclic: ; *)
		bGT_SelGas3 : BOOL; (*Selection gas 3 *) (* OldName: 	M_AWGAS3	; Cyclic: ; *)
		bGT_SelGas4 : BOOL; (*Selection gas 4 *) (* OldName: 	M_AWGAS4	; Cyclic: ; *)
		bGT_TypSwhActive : BOOL; (*Gas type switching active *) (* OldName: 	GASUM	; Cyclic: ; *)
		bGT_TypSwhActiveHalt : BOOL; (*Gas type switching active, engine standstill *) (* OldName: 	GASUM_ST	; Cyclic: ; *)
		bGV_On : BOOL; (*Gas valves On *) (* OldName: 	M_GASV	; Cyclic: ; *)
		bIgnDeflPrct_Off : BOOL; (*Deflagration protection Ignition, 200ms delay*) (* OldName: 	ZUEND_PUFF	; Cyclic: ; *)
		bMsg1027 : BOOL; (*Gas train 1 failure *) (* OldName: 	M_GST1	; Cyclic: ; *)
		bMsg1029 : BOOL; (*Gas train 2 failure *) (* OldName: 	M_GST2	; Cyclic: ; *)
		bMsg1084 : BOOL; (*Measuring signal failure prechamber gas pressure*) (*OldName:M_MS_VKDR;Cyclic:5;*)
		bMsg3359 : BOOL; (*failure gas train 1 - line 2*) (*OldName: M_GST1_2; Cyclic: ; *)
		bMsg3360 : BOOL; (*failure gas train 1 - line 3*) (*OldName: M_GST1_3; Cyclic: ; *)
		bMsg3361 : BOOL; (*failure gas train 1 - line 4*) (*OldName: M_GST1_4; Cyclic: ; *)
		bPCGT_SafeDevOK : BOOL; (*DI Gassafety device Prechamber if existing*)
		bPortInject_Rel : BOOL; (*Release port injection from start/stop procedure *) (* OldName: releasePI; Cyclic:2; *)
		bSelGasTyp0 : BOOL; (*Selection of gas type 0 *) (* OldName: 	GAS1_2_MAN	; Cyclic: ; *)
		bSelGasTyp1 : BOOL; (*Selection of gas type 1 *) (* OldName: 	GAS1	; Cyclic: ; *)
		bSelGasTyp2 : BOOL; (*Selection of gas type 2 *) (* OldName: 	GAS2	; Cyclic: ; *)
		bSelGasTyp3 : BOOL; (*Selection of gas type 3 *) (* OldName: 	GAS3	; Cyclic: ; *)
		bSelGasTyp4 : BOOL; (*Selection of gas type 4 *) (* OldName: 	GAS4	; Cyclic: ; *)
		bSelGasTypAut : BOOL; (*Selection of automatic gas type switching *) (* OldName: 	AUTGAS	; Cyclic: ; *)
		bSelGasTypMix : BOOL; (*Selection of mixed gas  *) (* OldName: 	GAS1_3_MAN	; Cyclic: ; *)
		iCnt_Gas_NormM3 : DINT; (*Normal cubic meter*) (* OldName: 	; Cyclic: ; *)
		iCnt_Gas_OpM3 : DINT; (*Operation cubic meter*) (* OldName: 	; Cyclic: ; *)
		iIdx_Gtyp_Dem : INT; (*Actual gassort 1..4*) (* OldName: 	gasart	; Cyclic: ; *)
		rGasMixingRatio : REAL; (*Gas mixing ratio, old	 X_GMISCH_3 *) (* OldName: 	X_GMISCH_3	; Cyclic: ; *)
		rGT_MixSet : REAL; (*Set point for gas mixture rate [0..100%], old	 ssSetMix *) (* OldName: 	ssSetMix	; Cyclic:2; *)
		rGT_QualMix_1_2 : REAL; (*Mixture ratio bet. gas 1 and 2 [%], e.g. value 0.75 =75%*) (* OldName: 	ssMisch1_2	; Cyclic: ; *)
		rGT_RatioMix : REAL; (*Gas mixture rate after ramp fub [%], e.g. 0.5 = 50%*) (* OldName: 	ssRatioMix	; Cyclic:2; *)
		rP2s_red_1 : REAL; (* Gas pressure for power reduction gas rail [bar(abs)] *) (* OldName: new PV ; Cycle: 2 *)
		rPr_GR_filt : REAL; (*Average of 2 Inputs gas rail pressure - average filtered [bar]*) (*OldName:; Cycle:2; *)
		rPr_GR_UF : REAL; (*Unfiltered average gas rail pressure [bar]*) (* OldName: new PV ; Cycle: 2 *)
		rP_Red_CH4_Norm : REAL; (*power reduction due to CH4 low [%], e.g. 0.75 =75% power of nominal power   *) (* OldName: 	RED_CH4	; Cyclic: ; *)
		rP_Red_CV_Norm : REAL; (*power reduction due to Calorific value low [%], e.g. 0.75 =75% power of nominal power   *) (* OldName: 	RED_CV	; Cyclic: ; *)
		rP_Red_GasPr_Norm : REAL; (*power reduction due to gas pressure low [%], e.g. 0.75 =75% power of nominal power    *) (* OldName: 	RED_GD	; Cyclic: ; *)
		rP_Red_GasSwitch : REAL; (*Power reduction due to gas switching, open second gastrain [%], e.g. 0.75 = 75% power of nominal power *) (* OldName: 	new pv	; Cyclic: ; *)
		rP_Red_Pr_GR_Norm : REAL; (*Power reduction by minumum  gas pressure *) (* OldName: 	ssPowerRedVKG	; Cyclic: ; *)
		rP_Red_Pr_PCGT_Norm : REAL; (*Power reduction by pre chamber gas pressure*) (* OldName: 	ssPowerRedVKG	; Cyclic: ; *)
		rP_Red_SuctPr_Norm : REAL; (*power reduction due to suction pressure high [%], e.g. 0.75 =75% power of nominal power   *) (* OldName: 	RED_SD	; Cyclic: ; *)
		tCtr_GC_Set : HALioAo_Type; (*AO gas compressor*) (*OldName:Reg16_y; Cycle:5;*)
		tGT1_1_SafeDevice : HALioDo_Type; (*DO	 Gas safety device 1 line 1*) (* OldName: A_GAS1_1	; Cyclic:5; *)
		tGT1_2_SafeDevice : HALioDo_Type; (*DO	 Gas safety device 1 line 2*) (* OldName: A_GAS1_2	; Cyclic:5; *)
		tGT1_3_SafeDevice : HALioDo_Type; (*DO	 Gas safety device 1 line 3*) (* OldName: A_GAS1_3; Cyclic:5; *)
		tGT1_4_SafeDevice : HALioDo_Type; (*DO	 Gas safety device 1 line 4*) (* OldName: A_GAS1_4	; Cyclic:5; *)
		tGT1_SafeDevice : HALioDo_Type; (*DO	 Gas safety device 1 *) (* OldName: A_GAS1	; Cyclic:5; *)
		tGT2AB : MM2AmmBase; (*AMM structure *) (* OldName: 	pv	; Cyclic: ; *)
		tGT2PB : MM2ParaBase_type; (*Data exchange structure to ParaBase*) (* OldName: 	new structure	; Cyclic: ; *)
		tGT2_SafeDevice : HALioDo_Type; (*DO	 Gas safety device 2 *) (* OldName: A_GAS2	; Cyclic:5; *)
		tGT_Flap1_Close : HALioDo_Type; (*DO	 Close gas flap 1*) (* OldName: 	KL1ZU	; Cyclic: ; *)
		tGT_Flap1_Open : HALioDo_Type; (*DO	 Open gas flap 1*) (* OldName: 	KL1AUF	; Cyclic: ; *)
		tGT_Flap2_Close : HALioDo_Type; (*DO	 Close gas flap 2*) (* OldName: 	KL2ZU	; Cyclic: ; *)
		tGT_Flap2_Open : HALioDo_Type; (*DO	 Open gas flap 2*) (* OldName: 	KL2AUF	; Cyclic: ; *)
		tGT_GC_Dem : HALioDo_Type; (*DO	 Demand gas compressor *) (* OldName: 	ANF_GVD	; Cyclic: ; *)
		tGT_RelFlair : HALioDo_Type; (*DO	 Release flare  *) (* OldName: 	FG_FA	; Cyclic: ; *)
		tGV1Mega_Open : HALioDo_Type; (*DO	 Open mega gas valve 1 *) (* OldName: 	MGASV1	; Cyclic: ; *)
		tGV1_1_Open : HALioDo_Type; (*DO	 open gas valve 1_1 (GASV1_1)*) (* OldName: 	GASV1_1	; Cyclic:2; *)
		tGV1_2_Open : HALioDo_Type; (*DO	 open gas valve 1_1 (GASV1_2)*) (* OldName: 	GASV1_2	; Cyclic:2; *)
		tGV1_line1_Open : HALioDo_Type; (*DO open gas valve 1 line 1 *) (* OldName: DO_GASV1_1_TC1; Cyclic:2; *)
		tGV1_line2_Open : HALioDo_Type; (*DO open gas valve 1 line 2 *) (* OldName: DO_GASV1_2_TC1; Cyclic:2; *)
		tGV1_line3_Open : HALioDo_Type; (*DO open gas valve 1 line 3*) (* OldName: DO_GASV1_3_TC1; Cyclic:2; *)
		tGV1_line4_Open : HALioDo_Type; (*DO open gas valve 1 line 4*) (* OldName: DO_GASV1_4_TC1; Cyclic:2; *)
		tGV1_Open : HALioDo_Type; (*DO	 open gas valve 1 *) (* OldName: 	GASV1	; Cyclic:2; *)
		tGV2Mega_Open : HALioDo_Type; (*DO	 Open mega gas valve 2 *) (* OldName: 	MGASV2	; Cyclic: ; *)
		tGV2_Open : HALioDo_Type; (*DO	 open gas valve 2 *) (* OldName: 	GASV2	; Cyclic:2; *)
		tGV_Rel : HALioDo_Type; (*DO	 Release gas valves*) (* OldName: 	FG_GASV	; Cyclic:2; *)
		tGV_Upstream_Open : HALioDo_Type; (*	Do open External Customer Gasvalve 	 *) (*OldName: NewPV *)
		tGV_Upstream_Release : HALioDo_Type; (*	DO release External Customer Gasvalve	 *) (*OldName: NewPV *)
		tMGT_BOV : HALioDo_Type; (*DO BlowOff valve*) (*Oldname: DO_BOV_GT1_TC1; Cycle:2; *)
		tMGT_DBOV : HALioDo_Type; (*DO main gas train dome blow off valve *)
		tPCGT_SafeDevice : HALioDo_Type; (*DO Gas safety device Prechamber *) (* OldName: newPV; Cyclic:5; *)
		tPCG_DemCoolFan : HALioDo_Type; (*DO	 Pre chamber gas compressor, Demand cooling ventilator *) (* OldName: 	LUE_VERD	; Cyclic: ; *)
		tPCG_DemReliefValve : HALioDo_Type; (*DO	 Demand Relief valve *) (* OldName: 	ENTL_V	; Cyclic: ; *)
		tPCG_DemValCW : HALioDo_Type; (*DO	 Pre chamber gas compressor, Demand cooling water valve  *) (* OldName: 	VENT_VERD	; Cyclic: ; *)
		tPCG_GV_DelOpen : HALioDo_Type; (*DO	 Pre chamber gas valves with delay ON*) (* OldName: VKGV2; Cyclic:2;*)
		tPCG_GV_Open : HALioDo_Type; (*DO	 Pre chamber gas valves*) (* OldName: 	VKGV	; Cyclic:2; *)
		tPCG_BPV_Open : HALioDo_Type; (*DO Pre chamber gas bypass valve*)
		tPr_MGT_sp : HALioAo_Type; (*AO pressure gas rail set point with Offset considered*) (*OldName: AO_p_GR_sp; Cycle:2;*)
		tPr_PCGT_sp : HALioAo_Type; (*AO main gas train pressure - set point with Offset considered*) (*OldName: AO_p_PC_sp; Cycle:2;*)
		tPr_PCG_GC_Dem : HALioDo_Type; (*DO	 Demand pre champer gas compressor *) (* OldName: 	A_VKGV	; Cyclic: ; *)
		rP_Red_TJDiffPr_Norm : REAL; (*Gas proportional valve differential pressure power reduction setpoint*)
		rPr_P2s_demand_PCGT : REAL; (* Boost pressure demand for power reduction PCGT [bar(abs)] *)
		rH2 : REAL; (* H2 content, 1.0 = 100% *)
		rH2_Comp : REAL; (* H2 content for compensation, 1.0 = 100% *)
		rP_Red_H2_Norm : REAL; (* H2 content power reduction setpoint *)
		tGV_N2_Open : HALioDo_Type; (* DO Nitrogen purging valve (P.15-YCS-001) (P.15-YCS-002) *)
		tGV3_Open : HALioDo_Type; (*DO open gas valve 3 *)
		tGV4_Open : HALioDo_Type; (*DO open gas valve 4 *)
		tDCGA_GV_Open : HALioDo_Type; (*SAFETY PLC: DO open gas valve for decentral gas addition*) (*OldName: new PV; Cycle: 5;*) (*V04.25.00.00*)
	END_STRUCT;
	PERM_GT_struct : 	STRUCT  (*DO NOT SORT PERM STRUCTURE! Do not change structure order or overall size of structure!*)
		iCnt_Gas_NormM3 : DINT; (*Perm: Normal cubic meter*) (*Oldname: New PV*)
		iCnt_Gas_OpM3 : DINT; (*Perm: Operation cubic meter*) (*Oldname: New PV*)
		rDPr_MGT_SetActAdjust : REAL; (*Perm: Main gas train set-/actual-pressure adjustment *) (*Oldname: New PV*)
		rDPr_PCGT_SetActAdjust : REAL; (*Perm: Prechamber gas train set-/actual-pressure adjustment *) (*Oldname: New PV*)
	END_STRUCT;
	PERM_GT2_struct : 	STRUCT  (*DO NOT SORT PERM STRUCTURE! Do not change structure order or overall size of structure!*)
		bPr_GR_red_1_Exist : BOOL; (*Perm: Gas rail minimum pressure reduczion 2 exist*) (*Oldname: new PV*)
		bPr_GR_red_2_Exist : BOOL; (*Perm: Gas rail difference pressure reduczion 1 exist*) (*Oldname: new PV*)
		rDPr_limit_pgr_Pred : REAL; (*Perm: Gas train diff pressure limit value [default 0.7]*) (*Oldname: New PV*)
		rGT_PermValue04 : REAL; (*Perm: bTB_PermValue04*) (*Oldname: New PV*)
		rGT_PermValue05 : REAL; (*Perm: bTB_PermValue05*) (*Oldname: New PV*)
		rGT_PermValue06 : REAL; (*Perm: bTB_PermValue06*) (*Oldname: New PV*)
		rGT_PermValue07 : REAL; (*Perm: rTB_PermValue07*) (*Oldname: New PV*)
		rGT_PermValue08 : REAL; (*Perm: rTB_PermValue08*) (*Oldname: New PV*)
		rGT_PermValue09 : REAL; (*Perm: rTB_PermValue09*) (*Oldname: New PV*)
		rGT_PermValue10 : REAL; (*Perm: rTB_PermValue10*) (*Oldname: New PV*)
	END_STRUCT;
	PARA_GT_struct : 	STRUCT 
		bBiogasActive : BOOL; (*PARA [11360]: Biogas task active *) (* OldName: biogas_a; Cyclic: ; *)
		bBOP_MainGasPrep_Act : BOOL; (*PARA [13835]: Visu Plant display gas preperation main gas active*) (*OldName:newPv; Cycle:5;*)
		bCnt_GasImp_Active : BOOL; (*PARA [11361]: Impulse gas counter active*) (* OldName: 	new PV	; Cyclic: ; *)
		bCnt_Gas_NormM3 : BOOL; (*PARA [12445]: Normal cubic meter*) (*OldName: new PV; Cyclic: ; *)
		bCnt_Gas_OpM3 : BOOL; (*PARA [12446]: Operation cubic meter*) (*OldName: new PV; Cyclic: ; *)
		bCtr_GC : BOOL; (*PARA [12593]: visibility gas compressor*) (*OldName:bPlantCtr16; Cycle:5;*)
		bEGScav_Active : BOOL; (*PARA [11303]: exhaust gas scavenging active *) (*OldName:sel_EGScav;Cycle:5*)
		bGCActive : BOOL; (*PARA [11362]: Gas compressor active *) (* OldName: VERD; Cyclic: ; *)
		bGlowIgnPrevActive : BOOL; (*PARA [12089]: TRUE = glow ignition prevention activ *) (* OldName: sel_GlowIgnPrevent; *)
		bGT_AutGas_Ena : BOOL; (*PARA [11363]: Visu auto gas button *) (*OldName: bVisuAutGas; Cycle; ;*)
		bGT_CH4Active : BOOL; (*PARA [11364]: Measuring of CH4 content active *) (* OldName: 	CH4_a	; Cyclic: ; *)
		bGT_CH4TripActive : BOOL; (*PARA [11365]: Minimum shutdown active CH4 content *) (* OldName: 	CH4_A_a	; Cyclic: ; *)
		bGT_CH4WarnActive : BOOL; (*PARA [11366]: Minimum alarm and blocking active CH4 content *) (* OldName: 	CH4_W_a	; Cyclic: ; *)
		bGT_CVActive : BOOL; (*PARA [11367]: Measuring of calorific value active *) (* OldName: 	CV_a	; Cyclic: ; *)
		bGT_CVIpol12Active : BOOL; (*PARA [11368]: param.interpolation gas1 & 2 active from CV *) (* OldName: 	GAS1_2_CV	; Cyclic: ; *)
		bGT_CVTripActive : BOOL; (*PARA [11369]: Minimum shutdown active calorific value *) (* OldName: 	CV_A_a	; Cyclic: ; *)
		bGT_CVWarnActive : BOOL; (*PARA [11370]: Minimum alarm and blocking active calorific value *) (* OldName: 	CV_W_a	; Cyclic: ; *)
		bGT_Ipol12Active_Para : BOOL; (*PARA [11371]: Interpolation gas1 & 2 active from CH4(or CV)*) (* OldName: GAS1_2	; Cyclic: ; *)
		bGT_MixActive : BOOL; (*PARA [12320]: Gas mixing active *) (* OldName: 	new PV	; Cyclic: ; *)
		bGT_MixActiveEngStop : BOOL; (*PARA [12321]: Gas mixing standstill active *) (* OldName: 	new PV	; Cyclic: ; *)
		bGT_O2Active : BOOL; (*PARA [11372]: Measuring of O2 content active *) (* OldName: 	O2_a	; Cyclic: ; *)
		bGT_O2MaxTripActive : BOOL; (*PARA [11373]: Shutdown O2 content maximum active *) (* OldName: 	O2_MX_a	; Cyclic: ; *)
		bGT_SpecGasActive : BOOL; (*PARA [11374]: Visibility of special gas values *) (* OldName: 	bSpecialGas	; Cyclic: ; *)
		bMGT_SetActAdjustActive : BOOL; (*PARA [12473]: main gas train set-/actual-pressure adjustment active*) (*Oldname: New PV*)
		bMIF_Enable : BOOL; (*PARA [12190]: micro interruption filter enable*) (*OldName: sel_mi_filter_activ; Cycle; ;*)
		bMsg3327Active : BOOL; (*PARA [11375]: Gas pressure before gas compressor measuring signal failure Trip active*) (*OldName: 	new PV	; Cyclic: ; *)
		bMsg3328Active : BOOL; (*PARA [11376]: Gas temperature measuring signal failure Trip active *) (* OldName: 	new PV	; Cyclic: ; *)
		bMsg3567Active : BOOL; (*PARA [11377]: Gas compressor failure Warning active *) (*OldName: 	new PV	; Cyclic: ; *)
		bMsg3568Active : BOOL; (*PARA [11378]: Gas temperature maximum enable alarm*) (* OldName: 	new PV	; Cyclic: ; *)
		bMsg3569Active : BOOL; (*PARA [11379]: Gas pressure low before gas compressor Warning active *) (* OldName: 	new PV	; Cyclic: ; *)
		bMsg3570Active : BOOL; (*PARA [11380]: Measurement signal error Gas pressure before compressor enable*) (* OldName: 	new PV	; Cyclic: ; *)
		bPCGT_SafeDevice_Exist : BOOL; (*PARA [13264]: Gas safety device Prechamber exists*) (* OldName: sel_newPV;*)
		bPCGT_SetActAdjustActive : BOOL; (*PARA [12527]: pre chamber gas train set-/actual-pressure adjustment active*) (*Oldname: New PV*)
		bPF_CosPCtr_Diff_Ena : BOOL; (*PARA [11486]: enable differential protection monitoring*) (*Oldname:DEAKT_DIFF;Cycle:5*)
		bPr_GasPrAbsActive : BOOL; (*PARA [11388]: gas pressure measuring = absolute *) (* OldName: new PV, settings "gp_abs_sens" before; Cyclic: ; *)
		bPr_GR_II_Exist : BOOL; (*PARA [12676]: Gas rail pressure sensor 2 exist*) (*Oldname: new PV*)
		bPr_GR_I_Exist : BOOL; (*PARA [12675]: Gas rail pressure sensor 1 exist*) (*Oldname: new PV*)
		bPr_GR_red_Exist : BOOL; (*PARA [14109]: Gas rail minimum pressure exist*) (*Oldname: new PV*)
		bPr_GT1_Active : BOOL; (*PARA [11392]: gas pressure after filter measuring active*) (* OldName: 	p_GT1_a	; Cyclic: ; *)
		bPr_GT_GasPrActive : BOOL; (*PARA [11389]: Measuring of gas pressure active *) (* OldName: 	GD_a	; Cyclic: ; *)
		bPr_GT_MaxActive : BOOL; (*PARA [11390]: Gas pressure maximum switching point active *) (* OldName: 	GD_MX_a	; Cyclic: ; *)
		bPr_GT_MinActive : BOOL; (*PARA [11391]: Gas pressure minimum alarm and blocking active *) (* OldName: 	GD_MN_a	; Cyclic: ; *)
		bPr_MGT_a_Filt_Exist : BOOL; (*Para: main gas train pressure after filter exist*) (*Oldname: p_GT1_a*)
		bPr_PCGComp_Active : BOOL; (*PARA [11395]: pressure prechamber gas compressor active (*OldName:PVnew; Cycle:5;*)
		bPr_PCGT_Active : BOOL; (*PARA [11396]: pressure pre chamber gas train meas.signal active*) (* OldName: 	p_PCGT_a	; Cyclic: ; *)
		bPr_PCGT_a_Filt_Exist : BOOL; (*Para: pre chamber gas train pressure after filter exist, new with porting J920 to XT4*) (*Oldname: p_PCGT_a*)
		bPr_PCGT_Out_Exist : BOOL; (*PARA [12478]: gas pressure after pre chamber gas pressure regulator exist*) (*Oldname: New PV*)
		bPr_PCG_GC_Active : BOOL; (*PARA [11394]: Pre chamber gas compressor enable *) (* OldName: 	bAuxilGasComp	; Cyclic: ; *)
		bPr_PC_Active : BOOL; (*PARA [11393]: pressure prechamber measuring signal active*) (* OldName: 	PDIFF_a	; Cyclic: ; *)
		bPurgecycle_Active : BOOL; (*PARA [12256]: Para purge cycle enable *) (* OldName: 	bPurgecycle	; Cyclic: ; *)
		bP_GT_SuctPrActive : BOOL; (*PARA [11381]: Measuring of suction pressure active *) (* OldName: 	SD_a	; Cyclic: ; *)
		bP_Red_CH4Active : BOOL; (*PARA [11382]: Power limitation because of CH4 content active *) (* OldName: 	R_CH4_a	; Cyclic: ; *)
		bP_Red_CVActive : BOOL; (*PARA [11383]: Power limitation because of calorific value content active *) (* OldName: 	R_CV_a	; Cyclic: ; *)
		bP_Red_GasPrActive : BOOL; (*PARA [11384]: Power limitation because of gas pressure active *) (* OldName: 	R_GD_a	; Cyclic: ; *)
		bP_Red_Pr_PCG : BOOL; (*PARA [11385]: power reduction by pre chamber gas pressure active *) (* OldName: 	Pred_PCGT_act	; Cyclic: ; *)
		bP_Red_SuctPrActive : BOOL; (*PARA [11386]: Power limitation because of suction pressure active *) (* OldName: 	R_SD_a	; Cyclic: ; *)
		bSyActive : BOOL; (*PARA [12195]: synchronization active *) (* OldName: 	bSynch	; Cyclic: ; *)
		bTestEnabled : BOOL; (*Para	 Use reduced testing time TRUE = Shortened times used, FALSE = Process values used*) (* OldName: 	new PV	; Cycle: ; *)
		bTJ_Exist : BOOL; (*PARA [11400]: Gas metering with Tecjet enable *) (* OldName: 	bTecJetOn	; Cyclic: ; *)
		bT_GR_Exist : BOOL; (*PARA [12681]: Gas rail temperature exist*) (*Oldname: new PV*)
		bT_GT_Active : BOOL; (*PARA [11397]: Measuring of engine gas temperature active *) (* OldName: 	GT_a	; Cyclic: ; *)
		bT_PCGAfCo_Active : BOOL; (*PARA [11398]: temperature prechamber gas after cooler active*) (*OldName:PVnew; Cycle:5;*)
		bT_PCGT_Active : BOOL; (*PARA [11399]: temperature pre chamber gas train meas.signal active*) (* OldName: 	t_PC_a	; Cyclic: ; *)
		bVISA : BOOL; (*PARA [12259]: monitoring according to VISA*) (* OldName: 	VISA	; Cyclic: ; *)
		bVol_GT_Active : BOOL; (*PARA [11401]: Measuring of engine gas volume active *) (* OldName: 	GM_a	; Cyclic: ; *)
		iCountry : INT; (*PARA [12196]: Country specific*) (* OldName: 	PAK	; Cyclic: ; *)
		iEng_Motortype : INT; (*Para	 Motor type of the engine*) (* OldName: 	Motortype	; Cyclic: ; *)
		iGasTrain_Type : DINT; (*Para Type options of gas train  - V4.07*)
		iGasTrain_Upstream_Type : DINT; (*Para Type options of gas train  - V4.07*)
		iIdx_Gastyp : INT; (*PARA [11402]: Number of gas types *) (* OldName: 	anz_gasart	; Cyclic: ; *)
		iNum_GT : INT; (*PARA [11403]: Number of gas trains *) (* OldName: 	usNrOfGasTrains 	; Cyclic: ; *)
		iNum_GT1_Lines : INT; (*PARA [11404]: Number of lines for Gastrain 1*) (*OldName: new PV; Cycle; ;*)
		rDeflagPrct_Lim : REAL; (*PARA [11405]: Limit deflagration protection active [%]*) (* OldName: 	Z_GW_PUFF	; Cyclic: ; *)
		rDPr_GR_BOV_Open : REAL; (*PARA [12476]: main chamber difference pressure maximum - open blowoff valve [bar]*) (*Oldname: GW_dp_GR_hi1*)
		rDPr_GR_BOV_Open_Hy : REAL; (*PARA [12477]: main chamber difference pressure maximum - open blowoff valve hysteresis [bar]*) (*Oldname: HY_dp_GR_hi1*)
		rDPr_MGT_Ch_P1 : REAL; (*PARA [12464]: main gas train - set pressure - Charge pressure Point 1 [bar (abs)]*) (*Oldname: p_CM_GR_P1*)
		rDPr_MGT_Ch_P2 : REAL; (*PARA [12465]: main gas train - set pressure - Charge pressure Point 2 [bar (abs)]*) (*Oldname: p_CM_GR_P2*)
		rDPr_MGT_P1 : REAL; (*PARA [12462]: pre chamber gas train - set pressure - difference pressure Point 1 [bar]*) (*Oldname: dp_GR_P1*)
		rDPr_MGT_P2 : REAL; (*PARA [12463]: pre chamber gas train - set pressure - difference pressure Point 2 [bar]*) (*Oldname: dp_GR_P2*)
		rDPr_PCGT_Ch_P1 : REAL; (*PARA [12491]: pre chamber gas train - set pressure - Charge pressure Point 1 [bar (abs)]*) (*Oldname: p_CM_PC_P1*)
		rDPr_PCGT_Ch_P2 : REAL; (*PARA [12492]: pre chamber gas train - set pressure - Charge pressure Point 2 [bar (abs)]*) (*Oldname: p_CM_PC_P2*)
		rDPr_PCGT_P1 : REAL; (*PARA [12489]: pre chamber gas train - set pressure - difference pressure Point 1 [bar]*) (*Oldname: dp_PC_P1*)
		rDPr_PCGT_P2 : REAL; (*PARA [12490]: pre chamber gas train - set pressure - difference pressure Point 2 [bar]*) (*Oldname: dp_PC_P2*)
		rGasImp_Prescaling : REAL; (*Para Pulse per m3 gas (prescaling) -V4.07*)
		rGT_CH4Mix1 : REAL; (*PARA [11407]: CH4 content 100% gas type 1 / 0% gas type 2 *) (* OldName: 	GAS_MIX_1	; Cyclic: ; *)
		rGT_CH4Mix2 : REAL; (*PARA [11408]: CH4 content 0% gas type 1 / 100% gas type 2 *) (* OldName: 	GAS_MIX_2	; Cyclic: ; *)
		rGT_CH4TripHyMin : REAL; (*PARA [11409]: Hysteresis CH4 content minimum shutdown *) (* OldName: 	HY_CH4_A	; Cyclic: ; *)
		rGT_CH4TripLimMin : REAL; (*PARA [11410]: Switching point CH4 content minimum shutdown *) (* OldName: 	GW_CH4_A	; Cyclic: ; *)
		rGT_CH4WarnHyMin : REAL; (*PARA [11411]: Hysteresis CH4 content minimum alarm and blocking *) (* OldName: 	HY_CH4_W	; Cyclic: ; *)
		rGT_CH4WarnLimMin : REAL; (*PARA [11412]: Switching point CH4 content minimum alarm and blocking *) (* OldName: 	GW_CH4_W	; Cyclic: ; *)
		rGT_CH4_Mix_DefVal : REAL; (*PARA [11406]: Default value from CH4 for interpolation between GasType1 and GasType2 [%] *) (* OldName: 	GAS_MIX	; Cyclic: ; *)
		rGT_CV4Mix1 : REAL; (*PARA [11414]: Calorific value 100% gas type 1 / 0% gas type 3 *) (* OldName: 	GAS_MIX_1_CV	; Cyclic: ; *)
		rGT_CV4Mix2 : REAL; (*PARA [11415]: Calorific value 0% gas type 1 / 100% gas type 3 *) (* OldName: 	GAS_MIX_2_CV	; Cyclic: ; *)
		rGT_CVTripHyMin : REAL; (*PARA [11416]: Hysteresis calorific value content minimum shutdown *) (* OldName: 	HY_CV_A	; Cyclic: ; *)
		rGT_CVTripLimMin : REAL; (*PARA [11417]: Switching point Calorific value minimum shutdown *) (* OldName: 	GW_CV_A	; Cyclic: ; *)
		rGT_CVWarnHyMin : REAL; (*PARA [11418]: Hysteresis calorific value content minimum alarm and blocking *) (* OldName: 	HY_CV_W	; Cyclic: ; *)
		rGT_CVWarnLimMin : REAL; (*PARA [11419]: Switching point Calorific value minimum alarm and blocking *) (* OldName: 	GW_CV_W	; Cyclic: ; *)
		rGT_CV_Mix_DefVal : REAL; (*PARA [11413]: Default value from calorific value for interpolation between GasType1 and GasType2 [%] *) (* OldName: 	GAS_MIX_CV	; Cyclic: ; *)
		rGT_O2HyMax : REAL; (*PARA [11420]: Hysteresis O2 content maximum *) (* OldName: 	HY_O2_MX	; Cyclic: ; *)
		rGT_O2LimMax : REAL; (*PARA [11421]: Switching point O2 content maximum *) (* OldName: 	GW_O2_MX	; Cyclic: ; *)
		rN_EngNom : REAL; (*PARA [12128]: engine nominal speed*) (*OldName:n_nenn;Cycle:5*)
		rN_EngStart_HyHi : REAL; (*PARA [11295]: Hysteresis start speed limit *) (* OldName: 	HY_DREHZ	; Cyclic: ; *)
		rN_EngStart_LimHi : REAL; (*PARA [11296]: Start speed limit *) (* OldName: 	GW_DREHZ	; Cyclic: ; *)
		rN_EOP_Lim1 : REAL; (*PARA [10033]: Engine Speed 1 for oil pressure monitoring *) (* OldName: 	DR_ODR_1	; Cyclic: ; *)
		rN_PCG_EngStart_HyHi : REAL; (*PARA [11423]: Hysteresis value of limit start engine speed for release pre chamber gas valves*) (* OldName: 	HY_DREHZ1	; Cyclic: ; *)
		rN_PCG_EngStart_LimHi : REAL; (*PARA [11424]: Limit start engine speed for release pre chamber gas valves*) (* OldName: 	GW_DREHZ1	; Cyclic: ; *)
		rPr_BlowOff_LimHi : REAL; (*PARA [12891]: trigger value for prechamber difference pressure, TRUE = blow-off valve is defect *) (* OldName: sel_GlowIgnPrevent;*)
		rPr_DiffPC_HyHi : REAL; (*PARA [11440]: Hysteresis difference pressure prechamber maximum*) (*OldName: HY_PDIF_MX; Cyclic:5;*)
		rPr_DiffPC_HyLo : REAL; (*PARA [11441]: Hysteresis difference pressure prechamber minimum*) (*OldName: HY_PDIF_MN; Cyclic:5;*)
		rPr_DiffPC_LimHi_P1 : REAL; (*PARA [11442]: Limit difference pressure prechamber maximum at BoostPressure point P1 [bar]*) (*OldName: GW_PDIF_MX_P1; Cyclic:5;*)
		rPr_DiffPC_LimHi_P2 : REAL; (*PARA [11443]: Limit difference pressure prechamber maximum at BoostPressure point P2 [bar]*) (*OldName: GW_PDIF_MX_P2; Cyclic:5;*)
		rPr_DiffPC_LimLo_P1 : REAL; (*PARA [11444]: Limit difference pressure prechamber minimum at BoostPressure point P1 [bar]*) (*OldName: GW_PDIF_MN_P1; Cyclic:5;*)
		rPr_DiffPC_LimLo_P2 : REAL; (*PARA [11445]: Limit difference pressure prechamber minimum at BoostPressure point P2 [bar]*) (*OldName: GW_PDIF_MN_P2; Cyclic:5;*)
		rPr_GR_Diff_Hi : REAL; (*Para: Gas rail difference pressure max. [bar]*) (*Oldname: ssGW_WPDGR_MAX*)
		rPr_GR_Diff_HiHi : REAL; (*PARA [12679]: Gas rail difference pressure max. [bar]*) (*Oldname: ssGW_ADPGR_MAX*)
		rPr_GR_Diff_Lo : REAL; (*Para: Gas rail difference pressure min. [bar]*) (*Oldname: ssGW_WPDGR_MIN*)
		rPr_GR_Diff_LoLo : REAL; (*PARA [12680]: Gas rail difference pressure min. [bar]*) (*Oldname: ssGW_ADPGR_MIN*)
		rPr_GR_HiHi : REAL; (*PARA [12677]: Gas rail pressure max. [bar]*) (*Oldname: ssGW_AGRPR_MAX*)
		rPr_GR_LoLo : REAL; (*PARA [12678]: Gas rail pressure min. [bar]*) (*Oldname: ssGW_AGRPR_MIN*)
		rPr_GR_red_start : REAL; (*PARA [14110]: Gas rail minimum pressure reduction start. [bar]*) (*Oldname: ssGW_ADPGR_MAX*)
		rPr_GT1_LimHi1 : REAL; (*PARA [11458]: -Visu: main gas train pressure after filter maximum - error [bar]*) (*OldName: GW_p_GT1_hi1*)
		rPr_GT1_LimHi2 : REAL; (*PARA [11459]: -Visu: main gas train pressure after filter maximum - warning [bar]*) (*OldName: GW_p_GT1_hi2*)
		rPr_GT1_LimLo1 : REAL; (*PARA [11460]: -Visu: main gas train pressure after filter minimum - error [bar]*) (*OldName: GW_p_GT1_lo1*)
		rPr_GT1_LimLo2 : REAL; (*PARA [11461]: -Visu: pre chamber gas train pressure after filter minimum - warning [bar]*) (*OldName: GW_p_GT1_lo2*)
		rPr_GT_HyMax : REAL; (*PARA [11446]: Hysteresis gas pressure maximum *) (* OldName: 	HY_GD_MX	; Cyclic: ; *)
		rPr_GT_HyMin : REAL; (*PARA [11447]: Hysteresis gas pressure minimum *) (* OldName: 	HY_GD_MN	; Cyclic: ; *)
		rPr_GT_LimMax : REAL; (*PARA [11448]: Switching point gas pressure maximum *) (* OldName: 	GW_GD_MX	; Cyclic: ; *)
		rPr_GT_LimMin : REAL; (*PARA [11449]: Switching point gas pressure minimum *) (* OldName: 	GW_GD_MN	; Cyclic: ; *)
		rPr_GT_SuctPrHyMax : REAL; (*PARA [11450]: Hysteresis suction pressure maximum *) (* OldName: 	HY_SD_MX	; Cyclic: ; *)
		rPr_GT_SuctPrHyMin : REAL; (*PARA [11451]: Hysteresis suction pressure minimum *) (* OldName: 	HY_SD_MN	; Cyclic: ; *)
		rPr_GT_SuctPrLimMax : REAL; (*PARA [11452]: Switching point suction pressure maximum *) (* OldName: 	GW_SD_MX	; Cyclic: ; *)
		rPr_GT_SuctPrLimMin : REAL; (*PARA [11453]: Switching point suction pressure minimum *) (* OldName: 	GW_SD_MN	; Cyclic: ; *)
		rPr_MGT_a_Filt_Hi : REAL; (*Para: main gas train pressure after filter maximum - warning [bar]*) (*Oldname: GW_p_GT1_hi2*)
		rPr_MGT_a_Filt_HiHi : REAL; (*Para: main gas train pressure after filter maximum - error [bar]*) (*Oldname: GW_p_GT1_hi1*)
		rPr_MGT_a_Filt_Lo : REAL; (*Para: main gas train pressure after filter minimum - warning [bar]*) (*Oldname: GW_p_GT1_lo2*)
		rPr_MGT_a_Filt_LoLo : REAL; (*Para: pre chamber gas train pressure after filter minimum - error [bar]*) (*Oldname: GW_p_GT1_lo1*)
		rPr_MGT_PipeLoss_Ch_P1 : REAL; (*PARA [12471]: gas pipe pressure loss - Charge pressure Point 1 [bar (abs)]*) (*Oldname: New PV*)
		rPr_MGT_PipeLoss_Ch_P2 : REAL; (*PARA [12472]: gas pipe pressure loss - Charge pressure Point 2 [bar (abs)]*) (*Oldname: New PV*)
		rPr_MGT_PipeLoss_P1 : REAL; (*PARA [12469]: gas pipe pressure loss - Point 1 [bar]*) (*Oldname: New PV*)
		rPr_MGT_PipeLoss_P2 : REAL; (*PARA [12470]: gas pipe pressure loss - Point 2 [bar]*) (*Oldname: New PV*)
		rPr_MGT_spScalMax : REAL; (*PARA [12467]: pressure gas rail set point with Offset considered maximum*) (*Oldname: p_GR_sp_RangeEnd	*)
		rPr_MGT_spScalMin : REAL; (*PARA [12466]: pressure gas rail set point with Offset considered minimum*) (*Oldname: p_GR_sp_RangeBegin	*)
		rPr_MGT_sp_offset : REAL; (*PARA [12468]: main gas train - control spring pressure offset [bar]*) (*Oldname: New PV*)
		rPr_PCGT_a_Filt_Hi : REAL; (*Para: pre chamber gas train pressure after filter maximum - warning [bar]*) (*Oldname: GW_PCGT_hi1*)
		rPr_PCGT_a_Filt_HiHi : REAL; (*Para: pre chamber gas train pressure after filter maximum - error [bar]*) (*Oldname: GW_PCGT_hi2*)
		rPr_PCGT_a_Filt_Lo : REAL; (*Para: pre chamber gas train pressure after filter minimum - warning [bar]*) (*Oldname: GW_PCGT_lo2*)
		rPr_PCGT_a_Filt_LoLo : REAL; (*Para: main gas train pressure after filter minimum - error [bar]*) (*Oldname: GW_PCGT_low*)
		rPr_PCGT_HyLo1 : REAL; (*PARA [11472]: Visu pre chamber gas train pressure after filter minimum - limit [bar]. For bMsg1095.*) (*OldName: HY_PCGT_low*)
		rPr_PCGT_LimHi1 : REAL; (*PARA [11474]: -Visu: pre chamber gas train pressure after filter maximum - error [bar]*) (*OldName: GW_PCGT_hi1*)
		rPr_PCGT_LimHi2 : REAL; (*PARA [11475]: -Visu: pre chamber gas train pressure after filter maximum - warning [bar]*) (*OldName: GW_PCGT_hi2*)
		rPr_PCGT_LimLo1 : REAL; (*PARA [11476]: -Visu: pre chamber gas train pressure after filter minimum - error [bar]*) (*OldName: GW_PCGT_low*)
		rPr_PCGT_LimLo2 : REAL; (*PARA [11477]: -Visu: pre chamber gas train pressure after filter minimum - warning [bar]*) (*OldName: GW_PCGT_lo2*)
		rPr_PCGT_spScalMax : REAL; (*PARA [12526]: main gas train pressure - set point with Offset considered maximum*) (*Oldname: p_PC_sp_RangeEnd	*)
		rPr_PCGT_spScalMin : REAL; (*PARA [12525]: main gas train pressure - set point with Offset considered minimum*) (*Oldname: p_PC_sp_RangeBegin	*)
		rPr_PCGT_sp_offset : REAL; (*PARA [12488]: main gas train pressure  - Offset [bar]*) (*Oldname: New PV*)
		rPr_PCG_GC_HyMax : REAL; (*PARA [11464]: Hysteresis max. pre chamber gas compressor*) (*OldName: 	HY_VKMAX	; Cyclic: ; *)
		rPr_PCG_GC_HyMin : REAL; (*PARA [11465]: Hysteresis min. pre chamber gas compressor*) (*OldName: 	HY_VKMIN	; Cyclic: ; *)
		rPr_PCG_GC_LimMax : REAL; (*PARA [11466]: Pre chamber gas compressor limit max.*) (*OldName: 	GW_VKMAX	; Cyclic: ; *)
		rPr_PCG_GC_LimMin : REAL; (*PARA [11467]: Pre chamber gas compressor limit min. *) (*OldName: 	GW_VKMIN	; Cyclic: ; *)
		rPr_PCG_GC_LimOff : REAL; (*PARA [11468]: Pre chamber gas compressor limit off *) (*OldName: 	GW_VKAUS	; Cyclic: ; *)
		rPr_PCG_GC_LimOn : REAL; (*PARA [11469]: Pre chamber gas compressor Limit on*) (*OldName: 	GW_VKEIN	; Cyclic: ; *)
		rPr_PC_HyHi : REAL; (*PARA [11462]: Hysteresis pressure prechamber maximum*) (* OldName: HY_VKDR_MX; Cyclic: ; *)
		rPr_PC_LimHi : REAL; (*PARA [11463]: Switching point pressure prechamber maximum*) (* OldName: GW_VKDR_MX; Cyclic: ; *)
		rP_DeflagPrct_Hy : REAL; (*PARA [11425]: Hysteresis deflagration protection active [kW]*) (* OldName: 	HY_PUFF	; Cyclic: ; *)
		rP_DPr_GR_set : REAL; (*Para: Gas rail difference pressure set value. [bar]*) (*Oldname: ssGW_ADPGR_MAX*)
		rP_GT_SetLim : REAL; (*PARA [12322]: Power of reduction for opening second gastrain [kW] *) (* OldName: 	"ssPowerSetpointLimit SPS_REZP1 "	; Cyclic: ; *)
		rP_Pr_GR_red_rate : REAL; (*PARA [14112]: Gas rail minimum pressure reduction rate. [%]*) (*Oldname: ssGW_ADPGR_MAX*)
		rP_Red_CH4HalfLoad : REAL; (*PARA [11426]: CH4 content for power limitation to half load  *) (* OldName: 	RED_CH4_E	; Cyclic: ; *)
		rP_Red_CH4Start : REAL; (*PARA [11427]: CH4 content for start power limitation  *) (* OldName: 	RED_CH4_A	; Cyclic: ; *)
		rP_Red_CVHalfLoad : REAL; (*PARA [11428]: Calorific value content for power limitation to half load  *) (* OldName: 	RED_CV_E	; Cyclic: ; *)
		rP_Red_CVStart : REAL; (*PARA [11429]: Calorific value content for start power limitation  *) (* OldName: 	RED_CV_A	; Cyclic: ; *)
		rP_Red_GasPrHalfLoad : REAL; (*PARA [11430]: Gas pressure content for power limitation to half load  *) (* OldName: 	RED_GD_E	; Cyclic: ; *)
		rP_Red_GasPrStart : REAL; (*PARA [11431]: Gas pressure for start power limitation  *) (* OldName: 	RED_GD_A	; Cyclic: ; *)
		rP_Red_SuctPrHalfLoad : REAL; (*PARA [11434]: Suction pressure for power limitation to half load  *) (* OldName: 	RED_SD_E	; Cyclic: ; *)
		rP_Red_SuctPrStart : REAL; (*PARA [11435]: Suction pressure for start power limitation  *) (* OldName: 	RED_SD_A	; Cyclic: ; *)
		rT_GR_HiHi : REAL; (*PARA [12682]: Gas rail temperature max. [°C]*) (*Oldname: ssGW_AGRTP_MAX*)
		rT_GR_LoLo : REAL; (*PARA [12683]: Gas rail temperature min. [°C]*) (*Oldname: ssGW_AGRTP_MIN*)
		rT_GT_HyMax : REAL; (*PARA [11478]: Hysteresis gas temperature maximum *) (* OldName: 	HY_GT_MX	; Cyclic: ; *)
		rT_GT_HyMin : REAL; (*PARA [11479]: Hysteresis gas temperature minimum *) (* OldName: 	HY_GT_MN	; Cyclic: ; *)
		rT_GT_LimMax : REAL; (*PARA [11480]: Switching point gas temperature maximum *) (* OldName: 	GW_GT_MX	; Cyclic: ; *)
		rT_GT_LimMin : REAL; (*PARA [11481]: Switching point gas temperature minimum *) (* OldName: 	GW_GT_MN	; Cyclic: ; *)
		rT_PCGAfCo_HyHi : REAL; (*PARA [11482]: temperature prechamber gas after cooler hysteresis high [C]*) (*OldName:PVnew; Cycle:5;*)
		rT_PCGAfCo_LimHi : REAL; (*PARA [11483]: temperature prechamber gas after cooler limit high [C]*) (*OldName:PVnew; Cycle:5;*)
		tCtr_GC : _tGeACtrPara; (*Para controller gas compressor*) (*OldName:REG16; Cycle:5;*)
		tiBOV_Open_Max : TIME; (*PARA [12475]: main gas train blow-off-valve opening time maximum [s]*) (*Oldname: MaxOnTimeBOV*)
		tiBOV_Open_Min : TIME; (*PARA [12474]: main gas train blow-off-valve opening time minimum [s]*) (*Oldname: MinOnTimeBOV*)
		tiGT1_Delay_Mon : TIME; (*PARA [11484]: Delay monitoring gas pressure minimum [s]*) (* OldName: TW_T_GDRUW; Cyclic: ; *)
		bT_GT_NG_Exist : BOOL; (*PARA [14384]: Measuring range of gas temperature active*)
		bPr_GT_NG_Exist : BOOL; (*PARA [14387]: Measuring range of gas pressure active*)
		bVol_GT_NG_Exist : BOOL; (*PARA [14390]: Measuring range of gas volume active*)
		iTJ_DPress_PowRed_Mode : INT; (*PARA [14471]: Gas proportioning valve differential pressure control mode 0 – Function is not active	1 – Only trip active 2 – Power reduction and trip active*)
		rTJ_DPress_P_Red_Start : REAL; (*PARA [14472]: Gas proportioning valve differential pressure TO start power reduction*)
		rCtr_TJ_DPress_kp : REAL; (*PARA [14473]: Proportional gain of controller for power reduction based on gas proportioning valve differential pressure*)
		rCtr_TJ_DPress_ki : REAL; (*PARA [14474]: Integral gain of controller for power reduction based on gas proportioning valve differential pressure*)
		rTJ_DPress_Min : REAL; (*PARA [14475]: Minimum differential pressure OF gas proportioning valve*)
		tiTJ_DPress_Min_Delay : TIME; (*PARA [14476]: Time delay of minimum differential pressure of gas proportioning valve*)
		rDPr_PCGT_Set : REAL; (* PARA [14477]: Pressure regulator differential pressure prechamber gas train [bar] *)
		bGT_H2Active : BOOL; (*PARA [14901]: Measuring of H2 content active *)
		tiFilterConst_H2 : TIME; (*PARA [14902]: Filter time constant for H2 content [s] *)
		rP_Red_H2Start : REAL; (*PARA [14905]: H2 content for start of power reduction *)
		rP_Red_H2_Rate : REAL; (*PARA [14906]: Power reduction rate H2 content [%Pnom/%H2] *)
		rP_Red_H2_MSF : REAL; (*PARA [14907]: Power reduction rate in case of measurement signal failure H2 contetn [%Pnom] *)
		rGT_H2WarnLimMax : REAL; (*PARA [14908]: Switching point H2 content maximum warning [%] *)
		rGT_H2TripLimMax : REAL; (*PARA [14909]: Switching point H2 content maximum alaram [%] *)
		rGT_H2_DefVal : REAL; (*PARA [14910]: Default value from H2 content [%] *)
		bP_LoadReject_Active : BOOL; (* PARA [12890]: Load rejection funcitons active *)
		bMisfCont : BOOL; (* PARA [11063]: Misfire control active *)
		bPCG_BPV_Active : BOOL; (*PARA [15072]: Pre chamber gas bypass valve active*)
		bSA_PI_Active : BOOL; (*PARA [12120]: TRUE = SAFI port injection is enabled/active *)
		bEng_Act_H2 : BOOL; (* PARA [tbd]: H2 engine active *)
		bPr_H2_GT_b_Reg_Exist : BOOL; (* PARA [tbd]: Gas pressure before pressure regulator exist *)
		rPr_H2_GT_b_Reg_HiHi : REAL; (* PARA [tbd]: Gas pressure before pressure regulator maximum - trip *)
		bPr_H2_GT_a_Reg_Exist : BOOL; (* PARA [tbd]: Gas pressure after pressure regulator exist *)
		rPr_H2_GT_a_Reg_HiHi : REAL; (* PARA [tbd]: Gas pressure after pressure regulator maximum - trip *)
		bPr_N2_GT_Exist : BOOL; (* PARA [tbd]: Gas pressure N2 exist *)
		rPr_N2_GT_HiHi : REAL; (* PARA [tbd]: Gas pressure N2 maximum - trip *)
		rPr_N2_GT_LoLo : REAL; (* PARA [tbd]: Gas pressure N2 minimum - trip *)
		rP_Act_Norm_DPr_SP : REAL; (* PARA [tbd]: Switching point for set gas pressure - difference  *)
		rDPr_MGT_P1_bSP : REAL; (* PARA [tbd]: Set gas pressure - difference point 1 before switching point *)
		rDPr_MGT_P2_bSP : REAL; (* PARA [tbd]: Set gas pressure - difference point 2 before switching point *)
	END_STRUCT;
	VIS2MM_Struct : 	STRUCT 
		bGT_MixingEna : BOOL; (*Gas mixture active*) (*OldName: bGasMixture; Cyclic: ; *)
		bGT_QualMix_Man_Set : BOOL; (*TRUE=Gas quality setted manually*) (*OldName: bMisch1_2_Man; Cyclic: ; *)
		bGT_RatioMix_Man_Set : BOOL; (*TRUE=Gas mixing setted manually*) (*OldName: bSetMix_Man; Cyclic: ; *)
		iIdx_SelGasTyp : INT; (*Selection of gas type*) (*OldName: M_AUTGAS, M_GAS1, M_GAS2, M_GAS3, M_Gas4, M_GAS1_2, M_GAS1_3, M_GAS1_2_3; Cyclic: ; *)
		rGT_QualMix_Man_Set : REAL; (*Gas mixing quality manual setpoint [%], e.g. value 0.75 =75%*) (*OldName: ssMisch1_2_Man; Cyclic: ; *)
		rGT_RatioMix_Man_Set : REAL; (*Gas mixing ratio manual setpoint [%], e.g. value 0.75 =75%*) (*OldName: ssSetMix_Man; Cyclic: ; *)
		tCtr_GC_In : _tGeACtrIn; (*gas compressor controller*) (*OldName:REG16; Cycle:5;*)
	END_STRUCT;
	_tMeasurePoint : 	STRUCT 
		P : INT;
		t : REAL;
		w : INT;
		n : INT;
	END_STRUCT;
	gv_struct : 	STRUCT  (*BETA VERSION V4.07, - not released for general use*)
		enable : BOOL; (*from Parameter*)
		rdy : BOOL;
		on : BOOL; (*real position status*)
		off : BOOL; (*real position status*)
		man_off : BOOL; (*optional manual command*)
		man_on : BOOL; (*optional manual command*)
		release : BOOL;
		command_on : BOOL; (*command to valve*)
		command_off : BOOL; (*command to valve*)
		rel_trip : BOOL := TRUE; (*enable alarm messages*)
		alarm : BOOL; (*error status message*)
		alm_psf : BOOL; (*error status message*)
		alm_opf : BOOL; (*error status message*)
		alm_cf : BOOL; (*error status message*)
		alm_0sf : BOOL; (*error status message*)
		alm_1sf : BOOL; (*error status message*)
		alm_ol : BOOL; (*error status message*)
		gv_status : DINT := 99999; (*valve status output*)
	END_STRUCT;
	CUSTOM2GASTRAIN_Struct : 	STRUCT 
		iGC_Select_Option : DINT; (*V4.07 new*)
		rCust_GT : ARRAY[0..15]OF REAL; (*V4.07 new*)
		tiGT_TestDuration : TIME; (*V4.07 new*)
		tiGCPulse_Duration_min : TIME; (*V4.07 new*)
		tiGV_Feedback_Delay_max : TIME; (*V4.07 new*)
		tIF_Revision : Revision_type; (*Revision number  of  latest interface change *)
	END_STRUCT;
END_TYPE
