(********************************************************************
 * COPYRIGHT -- INNIO Company
 ********************************************************************
 * Program: gmv_ber
 * File: gmv_berInit.st
 * Author: 105051626
 * Created: May 10, 2012
 *******************************************************************)

PROGRAM _INIT
    xLCRPT1_FA_GMISCH.enable := TRUE;
	xLCRPT1_FA_GMISCH.t      := 0.2;
END_PROGRAM	
