
TYPE
	PARA_AG_struct : 	STRUCT 
		tiFreshOilPump_Delay : TIME := T#5s; (*PARA [15065]  OilFill V4.14*) (*OldName: NewPV V4.14*)
		iOilRefill_Type : INT; (*PARA [xxxxx]  OilFill V4.14 prepared*) (*OldName: NewPV V4.14*)
		tiPostLub_Continuous : TIME; (*PARA [14930]  Turbocharger post lubrication - Duration of the continuous phase [s]*) (*OldName: new PV; Cycle:5*) (*V04.12.00.00*)
		iNum_PostLub_Interval : INT; (*PARA [14931]  Turbocharger post lubrication - number of intervals*) (*OldName: new PV; Cycle:5*) (*V04.12.00.00*)
		tiPostLub_PumpOff : TIME; (*PARA [14932]  Turbocharger post lubrication - Duration oil pump OFF [s]*) (*OldName: new PV; Cycle:5*) (*V04.12.00.00*)
		tiPostLub_PumpOn : TIME; (*PARA [14933]  Turbocharger post lubrication - Duration oil pump ON [s]*) (*OldName: new PV; Cycle:5*) (*V04.12.00.00*)
		bOilTankMonitoring : BOOL; (*PARA [14893]  OilTank V4.12*) (*OldName: NewPV V4.12*)
		rFreshOilTank_Type : REAL; (*PARA [14867]  OilTank V4.12*) (*OldName: NewPV V4.12*)
		rFreshOilTank_Length : REAL; (*PARA [14868]  OilTank V4.12*) (*OldName: NewPV V4.12*)
		rFreshOilTank_Height : REAL; (*PARA [14869]  OilTank V4.12*) (*OldName: NewPV V4.12*)
		rFreshOilTank_Witdh : REAL; (*PARA [14870]  OilTank V4.12*) (*OldName: NewPV V4.12*)
		rFreshOilTank_SensorPos : REAL; (*PARA [14871]  OilTank V4.12*) (*OldName: NewPV V4.12*)
		rWasteOilTank_Type : REAL; (*PARA [14876]  OilTank V4.12*) (*OldName: NewPV V4.12*)
		rWasteOilTank_Length : REAL; (*PARA [14877]  OilTank V4.12*) (*OldName: NewPV V4.12*)
		rWasteOilTank_Height : REAL; (*PARA [14878]  OilTank V4.12*) (*OldName: NewPV V4.12*)
		rWasteOilTank_Witdh : REAL; (*PARA [14879]  OilTank V4.12*) (*OldName: NewPV V4.12*)
		rWasteOilTank_SensorPos : REAL; (*PARA [14880]  OilTank V4.12*) (*OldName: NewPV V4.12*)
		rFreshOilTank_VolumeTotal : REAL; (*PARA [14894]  OilTank V4.12*) (*OldName: NewPV V4.12*)
		rWasteOilTank_VolumeTotal : REAL; (*PARA [14898]  OilTank V4.12*) (*OldName: NewPV V4.12*)
		rDayOilTank_VolumeTotal : REAL; (*PARA [14899]  OilTank V4.12*) (*OldName: NewPV V4.12*)
		rDayOilTank_Type : REAL; (*PARA [14885]  OilTank V4.12*) (*OldName: NewPV V4.12*)
		rDayOilTank_Length : REAL; (*PARA [14886]  OilTank V4.12*) (*OldName: NewPV V4.12*)
		rDayOilTank_Height : REAL; (*PARA [14887]  OilTank V4.12*) (*OldName: NewPV V4.12*)
		rDayOilTank_Witdh : REAL; (*PARA [14888]  OilTank V4.12*) (*OldName: NewPV V4.12*)
		rDayOilTank_SensorPos : REAL; (*PARA [14889]  OilTank V4.12*) (*OldName: NewPV V4.12*)
		rV_FreshOilTank_LimHi : REAL; (*PARA [14875]  OilTank V4.12*) (*OldName: NewPV V4.12*)
		rV_FreshOilTank_LimLo : REAL; (*PARA [14874]  OilTank V4.12*) (*OldName: NewPV V4.12*)
		rV_DayOilTank_LimHi : REAL; (*PARA [14875]  OilTank V4.12*) (*OldName: NewPV V4.12*)
		rV_DayOilTank_LimLo : REAL; (*PARA [14874]  OilTank V4.12*) (*OldName: NewPV V4.12*)
		rV_WasteOilTank_LimHi : REAL; (*PARA [14883]  OilTank V4.12*) (*OldName: NewPV V4.12*)
		rFreshOilTank_ScalMin : REAL; (*PARA [14872] [HalIO takeover]  OilTank V24*) (*OldName: NewPV V4.12*)
		rFreshOilTank_ScalMax : REAL; (*PARA [14873] [HalIO takeover]  OilTank V24*) (*OldName: NewPV V4.12*)
		rWasteOilTank_ScalMin : REAL; (*PARA [14881] [HalIO takeover]  OilTank V24*) (*OldName: NewPV V4.12*)
		rWasteOilTank_ScalMax : REAL; (*PARA [14882] [HalIO takeover]  OilTank V24*) (*OldName: NewPV V4.12*)
		rDayOilTank_ScalMin : REAL; (*PARA [14890] [HalIO takeover]  OilTank V24*) (*OldName: NewPV V4.12*)
		rDayOilTank_ScalMax : REAL; (*PARA [14891] [HalIO takeover]  OilTank V24*) (*OldName: NewPV V4.12*)
		bER_VentColdCountryMode : BOOL; (*PARA [12246]: engine room ventilation cold country mode *) (*OldName:MRL_KL; Cycle:5*)
		bPurgecycle_Active : BOOL; (*PARA [12256]: purge cycle enable*) (*OldName:bPurgecycle; Cycle:5*)
		bVISA : BOOL; (*PARA [12259]: monitoring according VISA*) (*OldName:VISA; Cycle:5*)
		bTSTC_Exist : BOOL; (*PARA [10018]: Engine with TSTC *) (*OldName:b2StageTC; Cycle:5*)
		bEngTyp3_Prelub_Active : BOOL; (*PARA [10009]: prelubrication for engine typ 3 active *) (*OldName:BR3_VS_aktiv; Cycle:5*)
		bTC_PostLub_Active : BOOL; (*PARA [10015]: turbo charger post lubrication active *) (*OldName:new; Cycle:5*)
		bBS_Acc_Active : BOOL; (*PARA [12178]: accelerated black start active *) (*OldName:sel_black_start_15s; Cycle:5*)
		bSel_TwoN2Valves : BOOL; (*PARA [11313]: select exhaust gas scavenging with 2 nitrogen*) (* OldName:TwoN2Valves; Cycle:5*)
		bECWP_MechDriven : BOOL; (*PARA [10007]: engine cooling water pump mechanical driven*) (*OldName:sel_BR3_eMKWP; Cycle:5*)
		bTC_watercooled : BOOL; (*PARA [10016]: water cooled turbo charger *) (*OldName:ATL_H2O; Cycle:5*)
		iEng_Motortype : INT; (* Motor type of the engine *) (*OldName:iMotortyp; Cycle:5*)
		rN_ECWP_Set : REAL; (*PARA [10032]: speed engine cooling water pump setpoint *) (* OldName:GW_SP_MKWP; Cycle:5*)
		rN_EngStart_HyHi : REAL; (*PARA [11295]: speed engine start limit high hysteresis *) (*OldName:HY_DREHZ; Cycle:5*)
		rN_EngStart_HyHiHi : REAL; (*PARA [11507]: speed engine start limit high high hysteresis *) (*OldName:HY_HDREHZ; Cycle:5*)
		rN_EngStartMon_LimHi : REAL; (*PARA [12068]: speed engine start monitoring limit high*) (*OldName:GW_STRDRE; Cycle:5*) (*V04.13.00.00*)
		rN_EngStart_LimHi : REAL; (*PARA [11296]: speed engine start limit high *) (*OldName:GW_DREHZ; Cycle:5*)
		rN_EngStart_LimHiHi : REAL; (*PARA [11508]: speed engine start limit high high *) (*OldName:GW_HDREHZ; Cycle:5*)
		rPr_CC_LimHiHi : REAL; (*PARA [10060]: pressure crank case limit high high *) (*OldName:GW_p_CC_high; Cycle:5*)
		bPr_CC_MS_Exist : BOOL; (*PARA [10013]: pressure crank case measuring signal exist *) (*OldName:p_CC_a; Cycle:5*)
		rPr_Prel1EOP_LimHi : REAL; (*PARA [10076]: prelubrication pressure limit for 1 pump*) (*OldName:GW_VSD1; Cycle:5*)
		rPr_Prel1EOP_HyHi : REAL; (*PARA [10075]: prelubrication pressure limit for 1 pump hysteresis*) (*OldName:HY_VSD1; Cycle:5*)
		rPr_Prel2EOP_LimHi : REAL; (*PARA [10078]: prelubrication pressure limit for 2 pump*) (*OldName:GW_VSD2; Cycle:5*)
		rPr_Prel2EOP_HyHi : REAL; (*PARA [10077]: prelubrication pressure limit for 2 pump hysteresis*) (*OldName:HY_VSD2; Cycle:5*)
		rPr_TCOF_PrelubMin : REAL; (*PARA [10087]: TC - filter outlet prelubrication pressure minimum*) (*OldName:GW_ODTC_MI_PREL; Cycle:5*)
		rPr_TCOF_PrelubHyMin : REAL; (*PARA [10086]: filter outlet prelubrication pressure minimum hysteresis*) (*OldName:HY_ODTC_MI_PREL; Cycle:5*)
		rT_ECW_PreH_HyOFF : REAL; (*PARA [10088]: temperature engine cooling water preheating limit off hysteresis *) (*OldName:HY_VORW; Cycle:5*)
		rT_ECW_PreH_LimOFF : REAL; (*PARA [10089]: temperature engine cooling water preheating limit off *) (*OldName:GW_VORW; Cycle:5*)
		bCtr_CC : BOOL; (*PARA [12644]: visibility crank case pressure controller*) (*OldName:new; Cycle:5*)
		bCtr_ECW : BOOL; (*PARA [10005]: visibility engine cooling water controller*) (*OldName:new; Cycle:5*)
		tCtr_CC : _tGeACtrPara; (*Para controller actual speed*) (*OldName:new; Cycle:5*)
		tCtr_ECW : _tGeACtrPara; (*Para controller engine cooling water temperature*) (*OldName:new; Cycle:5*)
		bTCOP_Visible : BOOL; (*PARA [10017]: turbo charger oil pump visible*) (*OldName:bVisuTCPump; Cycle:5*)
		bEOP_AC_Visible : BOOL; (*PARA [10010]: engine oil pump prelube AC visible*) (*OldName:bVisuACPump; Cycle:5*)
		bEOP_DC_Visible : BOOL; (*PARA [10011]: engine oil pump DC visible*) (*OldName:bVisuDCPump; Cycle:5*)
		bECW_PreH_Visible : BOOL; (*PARA [10006]: engine cooling water preheating visible*) (*OldName:bPreHeat; Cycle:5*)
		bECWP_PreH_Visible : BOOL; (*PARA [10008]: engine cooling water preheating pump visible*) (*OldName:bPreHeatWatPump; Cycle:5*)
		b_EOF_DiffMonActive : BOOL; (*PARA [10002]: Oil pressure before oil filter active M.03-PI-002(NUP29)*) (*OldName:bOilFilterPressAct; Cycle:5*)
		rN_EOP_Lim1 : REAL; (*PARA [10033]: Engine Speed 1 for oil pressure monitoring*) (*OldName:DR_ODR_1; Cycle:5*)
		rPr_EOP_HyMin : REAL; (*PARA [10070]: Oil pressure mimimum hysteresis*) (*OldName:HY_ODRA; Cycle:5*)
		rPr_EOP_HyLim1 : REAL; (*PARA [10068]: Oil pressure limit 1 hysteresis*) (*OldName:HY_ODGW1; Cycle:5*)
		rPr_EOP_LimMax : REAL; (*PARA [10072]: Oil pressure maximum*) (*OldName:GW_ODR_MAX; Cycle:5*)
		rPr_EOP_HyMax : REAL; (*PARA [10069]: Oil pressure maximum hysteresis*) (*OldName:HY_ODR_MAX; Cycle:5*)
		rPr_EOP_LimSpeed2 : REAL; (*PARA [10074]: Limit oil pressure at engine speed 2*) (*OldName:GW_ODR_2; Cycle:5*)
		rN_EngNom : REAL; (*PARA [12128]: engine nominal speed*) (*OldName:n_nenn; Cycle:5*)
		rN_TCOF_Lim1 : REAL; (*PARA [10037]: TC - filter outlet pressure minimum speed scale value 1 for pressure monitoring*) (*OldName:DR_ODR_TC_1; Cycle:5*)
		rN_TCOF_Lim2 : REAL; (*PARA [10038]: TC - filter outlet pressure minimum speed scale value 2 for pressure monitoring*) (*OldName:DR_ODR_TC_2; Cycle:5*)
		rPr_TCOF_LimSpeed1 : REAL; (*PARA [10082]: TC - filter outlet pressure minimum oil limit value 1 for pressure monitoring*) (*OldName:GW_ODR_TC_1; Cycle:5*)
		rPr_TCOF_LimSpeed2 : REAL; (*PARA [10083]: TC - filter outlet pressure minimum oil limit value 2 for pressure monitoring*) (*OldName:GW_ODR_TC_2; Cycle:5*)
		rPr_TCOF_HyMin : REAL; (*PARA [10080]: TC - filter outlet pressure minimum hysteresis*) (*OldName:HY_ODTC_MI; Cycle:5*)
		rPr_TCOF_MinWarn : REAL; (*PARA [10085]: TC - filter outlet pressure minimum warning*) (*OldName:GW_ODTC_MI_W; Cycle:5*)
		rPr_TCOF_HyMinWarn : REAL; (*PARA [10081]: TC - filter outlet pressure minimum warning hysteresis*) (*OldName:HY_ODTC_MI_W; Cycle:5*)
		rPr_TCOF_Max : REAL; (*PARA [10084]: TC - filter outlet pressure maximum*) (*OldName:GW_ODTC_MA; Cycle:5*)
		rPr_TCOF_HyMax : REAL; (*PARA [10079]: TC - filter outlet pressure maximum hysteresis*) (*OldName:HY_ODTC_MA; Cycle:5*)
		rT_EO_PreheatMin : REAL; (*PARA [10093]: Limit start oil pre warning*) (*OldName:GW_OILVORW; Cycle:5*)
		rT_EO_PreheatHyMin : REAL; (*PARA [10092]: Limit start oil pre warning hysteresis*) (*OldName:HY_OILVORW; Cycle:5*)
		rT_EO_LimMin : REAL; (*PARA [10091]: Oil temperature minimum *) (*OldName:GW_OTMI; Cycle:5*)
		rT_EO_LimHyMin : REAL; (*PARA [10090]: Oil temperature minimum hysteresis*) (*OldName:HY_OTMI; Cycle:5*)
		b_TCEO_HE2Ena : BOOL; (*PARA [10004]: Activate picture for second oil heat exchanger*) (*OldName:bVisuOil2stage; Cycle:5*)
		rEOP_PreLube_Set : REAL; (*PARA [12673]: speed setpoint engine oil pump prelubrication (frequency converter)*) (*OldName:GW_SP_OILP_PREL; Cycle:5*)
		rEOP_PreHeat_Set : REAL; (*PARA [12674]: speed setpoint engine oil pump preheating (frequency converter)*) (*OldName:GW_SP_OILP_PREH; Cycle:5*)
		r_OV_LimOpen : REAL; (*PARA [10029]: Limit oil valve open*) (*OldName:GW_OELVA; Cycle:5*)
		r_OV_HyLimOpen : REAL; (*PARA [10027]: Limit oil valve open hysteresis*) (*OldName:HY_OELVA; Cycle:5*)
		r_OV_LimClose : REAL; (*PARA [10028]: Limit oil valve close*) (*OldName:GW_OELVZ; Cycle:5*)
		r_OV_HyLimClose : REAL; (*PARA [10026]: Limit oil valve close hysteresis*) (*OldName:HY_OELVZ; Cycle:5*)
		r_EO_LevelLimMax : REAL; (*PARA [10024]: Oil level maximum*) (*OldName:GW_OMAX; Cycle:5*)
		r_EO_W_LevelLimMax : REAL; (*PARA [14966]: Oil level maximum warning [%]*) (*OldName: newPV ; Cycle:5*) (*V04.13.00.00*)
		r_EO_W_LevelLimMin : REAL; (*PARA [13964]: Oil level minimum warning*) (*OldName: newPV ; Cycle:5*)
		r_EO_LevelHyLimMax : REAL; (*PARA [10022]: Oil level maximum hysteresis*) (*OldName:HY_OMAX; Cycle:5*)
		r_EO_LevelLimMin : REAL; (*PARA [10025]: Oil level minimum*) (*OldName:GW_OMIN; Cycle:5*)
		r_EO_LevelHyLimMin : REAL; (*PARA [10023]: Oil level minimum hysteresis*) (*OldName:HY_OMIN; Cycle:5*)
		rT_EOF_DiffMonRel : REAL; (*PARA [10094]: Oil filter differential pressure monitoring - Oil temperature for release [degC]*) (*OldName:ssOilFilterPOilTemp; Cycle:5*)
		rPr_EOP_LimSpeed1 : REAL; (*PARA [10073]: Limit oil pressure at engine speed 1*) (*OldName:GW_ODR_1; Cycle:5*)
		rPr_EOP_Lim1 : REAL; (*PARA [10071]: Oil pressure limit 1*) (*OldName:GW_ODGW1; Cycle:5*)
		rPr_LimHeatRel : REAL; (*PARA [12807]: Pressure limit for release heating*) (*OldName:GW_druck_heizfreigabe; Cycle:5*)
		rN_EOP_Lim2 : REAL; (*PARA [10034]: Engine Speed 2 for oil pressure monitoring*) (*OldName:DR_ODR_2; Cycle:5*)
		b_OilActive : BOOL; (*PARA [10003]: oil counter exist*) (*OldName:bExistOilCounter; Cycle:5*)
		iNum_OilPulse : INT; (*PARA [10020]: Impulse valency*) (*OldName:ssOilPulseValue; Cycle:5*)
		bCtr_EOVal_Active : BOOL; (*PARA [12615]: engine oil cooler valve controller Active*) (*OldName:new; Cycle:5*)
		rT_EOP_LimMax : REAL; (*PARA [10097]: Oil temperature maximum *) (*OldName:GW_OTMA; Cycle:5*)
		rT_EOP_HyMax : REAL; (*PARA [10095]: Oil temperature maximum hysteresis*) (*OldName:HY_OTMA; Cycle:5*)
		rT_EOP_HyRelLoad : REAL; (*PARA [10096]: Oil temperature release load, load enabling hysteresis*) (*OldName:HY_OT_LFG; Cycle:5*)
		rT_EOP_LimRelLoad : REAL; (*PARA [10098]: oil temperature release load*) (*OldName:GW_OT_LFG; Cycle:5*)
		tCtr_EOVal : _tGeACtrPara; (*Para: structure for engine oil controller*) (*OldName:new; Cycle:5*)
		rP_Red_T_Oil_Start : REAL; (*PARA [10049]: power reduction oil temp. start [°C]*) (*OldName:Pred_OT_start; Cycle:5*)
		rP_Red_T_Oil_Rate : REAL; (*PARA [10048]: power reduction oil temp.rate [%]*) (*OldName:Pred_OT_rate; Cycle:5*)
		rPr_EOF_DiffMonLimit1 : REAL; (*PARA [10065]: Oil filter differential pressure monitoring - Oil filter service life limit [bar]*) (*OldName:ssOilFilterLimit1; Cycle:5*)
		rPr_EOF_DiffMonLimit2 : REAL; (*PARA [10066]: Oil filter differential pressure monitoring - Oil filter to be replaced [bar]*) (*OldName:ssOilFilterLimit2; Cycle:5*)
		rPr_EOF_DiffMonLimit3 : REAL; (*PARA [10067]: Oil filter differential pressure monitoring - Shutdown [bar]*) (*OldName:ssOilFilterLimit3; Cycle:5*)
		i_OilRefillBlocked : DINT; (*PARA [10019]: Number of operating hours until next refill*) (*OldName:slBlockOilRefill_Bh; Cycle:5*)
		bEO_Level_Active : BOOL; (*PARA [12805]: Engine oil level measuring active*) (*OldName:ALM[2576].ENABLE; Cycle:5*)
		bPr_EOF_After_Active : BOOL; (*PARA [12722]: Oil pressure after oil filter active M.03-PI-057*) (*OldName:new PV; Cycle:5*)
		bGridCode_Active : BOOL; (*PARA [11055]: Gride Code active*) (*OldName:bGridCode; Cycle:5*)
		bPr_TCOaF_Active : BOOL; (*PARA [10014]: pressure oil turbo charger after filter signal active*) (*OldName:new; Cycle:5*)
		bCtr_EOVal_LT_Active : BOOL; (*PARA [12705]: engine oil cooler LT valve controller Active*) (*OldName:new; Cycle:5*)
		tCtr_EOVal_LT : _tGeACtrPara; (*Para: structure for engine oil controller*)
		bT_EOaPump_Active : BOOL; (*PARA [12723]: engine oil temperature after pump active*)
		bPr_Oil_LPTC_In_A : BOOL; (*PARA [12724]: oil pressure LP turbo charger A inlet measuring active*)
		bPr_Oil_LPTC_In_B : BOOL; (*PARA [12725]: oil pressure LP turbo charger B inlet measuring active*)
		bPr_f_BbFilt_Exist : BOOL; (*PARA [12566]: Druck vor Blow-by Filter aktiv, Pressure before Blow-by filter	*)
		rP_CC_MonActive_LimHi : REAL; (*PARA [10047]: -Visu only- Kurbelgehaeusedruckueberwachung aktiv, Crank Case Pressure check active [% Pnom]*) (*Oldname: GW_P_CCM, Cycle:5 *)
		rPr_CC_Lo : REAL; (*PARA [12560]: Kurbelgehaeusedruck Minimum - Warnung, Crank Case Pressure Minimum Warning [bar]*)
		rPr_CC_Hi : REAL; (*PARA [12561]: Crank case pressure high - warning [bar]*)
		rP_Red_CC : REAL; (*PARA [12564]: Power reduction by Crank case pressure [% Pnom]*)
		rPc_BbBlower_Hi : REAL; (*PARA [12565]: Operating point blow by blower maximum [%]*)
		bPr_a_BbFilt_Exist : BOOL; (*PARA [12571]: pressure after blow by filter exist*)
		rDPr_BbFilt_Pstart : REAL; (*PARA [12618]: Blow by filter difference pressure start point for monitoring [% Pnom]*)
		rDPr_BbFilt_Lo_P1 : REAL; (*PARA [12619]: Blow by filter difference pressure new filter - lower load point [bar]*)
		rDPr_BbFilt_Lo_P2 : REAL; (*PARA [12620]: Blow by filter difference pressure new filter - full load [bar]*)
		rDPr_BbFilt_Hi_P1 : REAL; (*PARA [12621]: Blow by filter difference pressure charged filter - lower load point [bar]*)
		rDPr_BbFilt_Hi_P2 : REAL; (*PARA [12622]: Blow by filter difference pressure charged filter - full load [bar]*)
		tiPr_CC_Hi : TIME; (*PARA [12562]: Crank case pressure high - time until warning [s]*)
		tiPr_CC_HiHi : TIME; (*PARA [12563]: Crank case pressure high - time until error [s]*)
		bT_EO_Pan_Active : BOOL; (*PARA [12747]: engine oil temperature oil pan active*)
		bPr_TCObF_Active : BOOL; (*PARA [12742]: turbocharger oil pressure before filter active*)
		bPr_AirStarter_Tank_Exist : BOOL; (*PARA [12648]: air starter tank pressure exist *)
		rPr_AirStarter_Tank_Lo : REAL; (*PARA [10055]: air starter tank pressure minimum [bar] *)
		bPr_AirStarter_Supply_Exist : BOOL; (*PARA [12651]: air starter supply pressure exist	*)
		rPr_AirStarter_Supply_LoLo : REAL; (*PARA [10053]: air starter supply pressure minimum - error [bar] *)
		rPr_AirStarter_Supply_HiHi : REAL; (*PARA [10052]: air starter supply pressure maximum - error [bar] *)
		bN_AirStarter_Exist : BOOL; (*PARA [12654]: air starter speed exist	*)
		tiAirStarter_OnTime : TIME; (*PARA [10119]: air starter ON Time / Engaging Time (Einspurzeit) [ms]*)
		tiTC_Postlub : TIME; (*PARA [12775]: turbo charger postlube duration for water cooled TC [ms]*)
		bManAuxCtr_Active : BOOL; (*PARA [12917]: Manual operating auxiliaries control is active*)
		tiManAuxCtr_Max : TIME; (*PARA [12916]: Maximum release time of manual operating auxiliaries control*)
		tiFreshOilPump_Intervall : TIME; (*PARA [xxxxx]: time for run time intervall fresh oil pump*) (*OldName: NewPV V4.14*)
		tiFreshOilPump_Pause : TIME; (*PARA [xxxxx]: time for stop intervall fresh oil pump*) (*OldName: NewPV V4.14  SEE ALSO -->PARA [13308]: time for run time overload fresh oil pump*)
		tiFreshOilPump_RTC_Time : TIME; (*PARA [13308]: time for run time overload fresh oil pump*)
		rP_Red_TransformerWarning_Rate : REAL; (*PARA [13270]: transformer power reduction setpoint*)
		bP_Red_TransformerWarning_Sel : BOOL; (*PARA [13269]: activation transformer power reduction*)
		bPr_f_BbFilt_A_Exist : BOOL; (*PARA [13265]: pressure before blow-by filter aktiv*)
		bPr_f_BbFilt_B_Exist : BOOL; (*PARA [13266]: pressure before blow-by filter aktiv*)
		bPr_a_BbFilt_A_Exist : BOOL; (*PARA [13267]: pressure after blow by filter exist*)
		bPr_a_BbFilt_B_Exist : BOOL; (*PARA [13268]: pressure after blow by filter exist*)
		bCDP_Active : BOOL; (*PARA [13182]: Kondensorpumpe active*)
		bPr_EOaP_Active : BOOL; (*PARA [13398]: engine oil pressure after pump active M.03-PI-007*)
		rPr_EOaP_LimHi : REAL; (*PARA [13399]: engine oil pressure after pump limit high M.03-PI-007*)
		rPr_EOaP_LimHiHi : REAL; (*PARA [13400]: engine oil pressure after pump limit high high M.03-PI-007*)
		bOilFiltUnit_Exist : BOOL; (*PARA [13470]: oil filter unit existing*)
		bPr_OFUbFilt_Active : BOOL; (*PARA [13471]: pressure oil filter unit before filter M.03-PI-011*)
		bPr_OFUaFilt_Active : BOOL; (*PARA [13474]: pressure oil filter unit after filter M.03-PI-012*)
		bServicePrelub : BOOL; (*PARA [13827]: prelube with both oil pumps - service button*)
		rPr_EObF_LimHi : REAL; (*PARA [13962]: Oil pressure filter inlet maximum warning [bar] M.03-PI-002(NUP29)*)
		rPr_EObF_LimHiHi : REAL; (*PARA [13963]: Oil pressure filter inlet maximum alarm [bar] M.03-PI-002(NUP29)*)
		bPr_OFUbCentrifuge_Active : BOOL; (*PARA [13631]: pressure oil filter unit before centrifuge M.03-PI-008*)
		rDPr_OFU_Filt_LimHi : REAL; (*PARA [13477]: difference pressure oil filter unit - limit high*)
		rPr_OFUbFilt_Hi : REAL; (*PARA [13630]: pressure oil filter unit before filter - limit high*)
		rPr_OFUbCentrifuge_Hi : REAL; (*PARA [13634]: pressure oil filter unit before centrifuge - limit high*)
		bPr_TCO_Active : BOOL; (*PARA [14114]: pressure oil before turbo charger [bar]*)
		tiFSPreL : TIME; (*PARA [14166]: permanent prelubrication minimum operating time for faststart release*)
		rPr_TCO_FSPreL_LimHi : REAL; (*PARA [14167]: pressure oil before turbo charger limit high - permanent prelubrication [bar]*)
		rPr_TCO_FSPreL_LimLo : REAL; (*PARA [14169]: pressure oil before turbo charger limit low - fast start [bar]*)
		rN_TCO_FS : REAL; (*PARA [14168]: speed point fast start [rpm]*)
		rT_EO_PreH_FS_Min : REAL; (*PARA [14170]: limit low start oil preheating warning/fast start [°C]*)
		rT_EO_PreH_FS_HyMin : REAL; (*PARA [14171]: Limit low start oil preheating warning hysteresis/fast start [°C]*)
		rPr_EO_PreH_LimLo : REAL; (*Para: engine oil pressure limit low preheating [bar]*)
		rPr_EO_FSPreL_LimLo : REAL; (*PARA [14165]: engine oil pressure limit low permanent prelubrication [bar]*)
		tiReEngage : TIME; (*PARA [14065]: delay reengagement air starter*)
		bFSPreL_Act : BOOL; (*PARA [14208]: permanent prelubrication active*)
		bBbOp_EOP : BOOL; (*PARA [14172]: blowby fan operation with engine oil pump*)
		bPreLub_Interval_Enable : BOOL; (*PARA [14066]: Interval pre lubrication enable *)
		tiPreLub_Interval : TIME; (*PARA [13965]: interval time pre lubrication *)
		rPr_PreLub_Interval_Lim : REAL; (*PARA [13966]: engine interval pre lubrication pressure limit *)
		rU_StarterBat_Lo : REAL; (*PARA [13989]: Starter battery voltage minimum (UL) while battery test*)
		rU_StarterBat_Hi : REAL; (*PARA [13990]: Starter battery voltage high*)
		bACP_Enable : BOOL; (*PARA [13984]: Enable Active Cooling *)
		rT_ACP_ECW_sp : REAL; (*PARA [13985]: Active cooling program setpoint temperature engine cooling water system *)
		rT_ACP_EO_sp : REAL; (*PARA [13986]: Active cooling program setpoint temperature engine cooling water system *)
		rT_ACP_AirER_sp : REAL; (*PARA [13987]: Active cooling program setpoint temperature engine room ventilation *)
		rT_EO_LimHiHi : REAL; (*PARA [14180]: Oil temperature high high//SWAT920/5*)
		bECW_PreH_Fast : BOOL; (*PARA [14349]: Fast ECW heat-up active*)
		rT_ECW_HydrPreH_LimLo : REAL; (*PARA [14350]: Delta hydraulic pre-heating warning [°C]*)
		iECW_PreH_Int_Visible : INT; (*PARA [11902]: Pre-heating type jacket water (formerly: Internal heating)*)
		bT_HW_Su_PreH_ECW_Active : BOOL; (*PARA [12912]: Heating water temperature supply hydraulic ECW preheating measuring active*)
		bRedHWP_Active : BOOL; (*PARA [14345]: Activate redundant pump control for heating water pump *)
		bRedCCWP_Active : BOOL; (*PARA [14347]: Activate redundant pump control for charge cooler water pump *)
		bRedCC2WP_Active : BOOL; (*PARA [14346]: Activate redundant pump control for charge cooler 2 water pump *)
		bRedEmCWP_Active : BOOL; (*PARA [14348]: Activate redundant pump control for emergency cooler water pump *)
		iCnt_TC_Inspection_Hi : DINT; (*PARA [14408]: Threshold for turbocharger inspection after number of failed post cooling cycles*)
		rPr_TC_EOF_After_Avg_Lo : REAL; (*PARA [14409]: Lower threshold average oil pressure for TC post cooling*)
		rPr_TC_Oil_CoolDownInterrupt_Lo : REAL; (*PARA [14410]: Lower threshold oil pressure for OCTC post cooling interruption*)
		bDPr_ECWP_Mon_Active : BOOL; (*PARA [14425]: Measurement cooling water difference pressure over ECW pump active*)
		rDPr_ECWP_LoLo : REAL; (*PARA [14428]: Difference pressure cooling water over ECW pump minimum*)
		tiAirST_Interrupt : TIME; (*PARA [14445]: Air starter start up time for interrupting blocked start valve*)
		bBbBlower_Off_Active : BOOL; (*PARA [14483]: Blow-by blower reduced operation mode*)
		rP_Norm_BbBlower_off : REAL; (*PARA [14484]: Engine power limit for blow by blower off [% Pnom]*)
		tiPr_CC_HiWarn : TIME; (*PARA [14485]: Crankcase pressure maximum  delay until warning [s]*)
		tiPreLube : TIME; (*PARA [14504]: Prelubrication duration (normal prelube, not permanent)*)
		bEO_Management_Active : BOOL; (*PARA [14496]: oil management function active*)
		bCW_Management_Active : BOOL; (*PARA [14497]: coolant management function active*)
		iEO_PreH_Int_Visible : INT; (*PARA [14503]: Pre-heating type engine oil (formerly: Internal heating)*)
		iBatMon_Mode : INT; (*PARA [14490]: Battery voltage monitoring mode*)
		rU_BufferBat_Lo : REAL; (*PARA [14491]: Buffer battery voltage minimum (UL) while battery test*)
		rU_BufferBat_Idle_Lo : REAL; (*PARA [14492]: Buffer battery voltage minimum idle voltage (U0)*)
		rU_StarterBat_Idle_Lo : REAL; (*PARA [14493]: Starter battery voltage minimum idle voltage (U0)*)
		rU_StarterBat_Crank_Lo : REAL; (*PARA [14494]: Starter battery voltage minimum starter cranking (UL)*)
		tiU_StarterBat_MeasDelay : TIME; (*PARA [14501]: Test begin starter battery voltage starter cranking (UL)*)
		tiU_StarterBat_MeasTime : TIME; (*PARA [14502]: Test duration starter battery voltage starter cranking (UL)*)
		rPr_OFUbCentrifuge_Lo : REAL; (*PARA [14734]: Oil pressure oil centrifuge inlet minimum warning [bar]*)
		iOQS_Config : UINT; (*PARA [14726]: Oil quality sensor configuration*)
		rOQS_OC_ScalFreshOil : REAL; (*PARA [14727]: Oil quality sensor: Oil condition value fresh oil (=100% oil quality) [%]*)
		rOQS_OC_ScalAgedOil : REAL; (*PARA [14728]: Oil quality sensor: Oil condition value aged oil (=0% oil quality) [%]*)
		rOilQual_OQS_OC_LimLo : REAL; (*PARA [14729]: Oil quality sensor: Limit oil quality warning [%]*)
		rOilQual_OQS_OC_LimLo1 : REAL; (*PARA [14731]: Oil quality sensor: Limit oil quality critical warning [%]*)
		rOilQualTendency_OQS_OC_LimHi : REAL; (*PARA [14730]: Oil quality sensor: Limit oil quality tendency warning [%/100oph]*)
		rOilQualTendency_OQS_OC_LimHi1 : REAL; (*PARA [14732]: Oil quality sensor: Limit oil quality tendency critical warning [%/100oph]*)
		iOilSamplingNomOh : DINT; (*PARA [14733]: Oil quality sensor: Regular oil sampling interval [oph]*)
		rT_OQS_LimLo : REAL; (*PARA [14921]: Oil quality sensor: Limit oil quality operating temperature [degC]*)
		rU_StarterMonTtT_LimHi : REAL; (*PARA [14927]: Starter monitoring: Tooth to tooth upper limit starter battery voltage [V]*)
		rN_StarterMonTtT_LimLo : REAL; (*PARA [14928]: Starter monitoring: Tooth to tooth lower limit engine speed [rpm]*)
		tiStarterMonDuration : TIME; (*PARA [14929]: Starter monitoring: Tooth to tooth detection duration [s]*)
		bOilRefill_MonAct : BOOL; (*PARA [14967]: Oil refill - Monitoring active*) (*OldName: newPV ; Cycle:5*) (*V04.13.00.00*)
		rVol_OilRefill_Pct_EO_Level : REAL; (*PARA [14968]: Oil refill - Refill volume per % oil level [l]*) (*OldName: newPV ; Cycle:5*) (*V04.13.00.00*)
		rPc_OilRefill_VolTolerance : REAL; (*PARA [14969]: Oil refill - Refill volume tolerance [%]*) (*OldName: newPV ; Cycle:5*) (*V04.13.00.00*)
		rU_StarterMon_LimLo : REAL; (*PARA [15015]: Starter function voltage level [V]*) (*OldName: newPV ; Cycle:5*) (*V04.13.00.00*)
		tiStarterFunDuration : TIME; (*PARA [15016]: Starter function detection time [s]*) (*OldName: newPV ; Cycle:5*) (*V04.13.00.00*)
		bEO_PreH_Active : BOOL; (*PARA [15019]: Oil preheating active*) (*OldName: newPV ; Cycle:5*) (*V04.13.00.00*)
		rT_EO_PreH_EngStart : REAL; (*PARA [15020]: Oil preheating - Target temperature for engine start [degC]*) (*OldName: newPV ; Cycle:5*) (*V04.13.00.00*)
		rVolFlow_Marg : REAL; (*PARA [15071]: Volume flow margin [%]*) (*V04.14.00.00*)
		rVolEff_CrkSpeed : REAL; (*PARA [15073]: Volumetric efficiency at cranking speed [-]*) (*V04.14.00.00*)
		iVol_MinAir_SysPurge : UDINT; (*PARA [15074]: Minimum air volume required for system purge [lt]*) (*V04.14.00.00*)
		rST_Heatup_Fact : REAL; (*PARA [15075]: Starter heatup factor [s/s]*) (*V04.14.00.00*)
		tiST_CooldownConst : TIME; (*PARA [15076]: Starter cool down time constant [s]*) (*V04.14.00.00*)
		tiST_MaxDur_OverheatPrev : TIME; (*PARA [15077]: Maximum starting duration overheat prevention [s]*) (*V04.14.00.00*)
		rST_ReqOpTiAftCooldown : REAL; (*PARA [15078]: Required starter operating time after cooldown [%]*) (*V04.14.00.00*)
		iVol_PremxInSys : UDINT; (*PARA [15079]: Premixed volume of the engine intake system [lt]*) (*V04.14.00.00*)
		iVol_TolUnbrtMxMax : UDINT; (*PARA [15080]: Maximum tolerable unburnt mixture volume [lt]*) (*V04.14.00.00*)
		bEGScav_Active : BOOL; (*PARA [11303]: exhaust gas scavenging active *) (*OldName:sel_EGScav;Cycle:5*) (*V04.14.00.00*)
		tiEO_Refill_TimeMax : TIME; (*PARA [15067]: oil refill time maximum *) (*V04.14.00.00*)
		bEGScav_ifAuxV_ok : BOOL; (*PARA [11304]: exhaust gas scavenging if auxiliaries voltage supply ok*) (*OldName:sel_EGScav_if_AuxV_ok;Cycle:5*)
	END_STRUCT;
END_TYPE
