
TYPE
	IN_CH_Struct : 	STRUCT 
		bAMM_Pr_Baro_Internal : BOOL; (*warning - value for barometric pressure not valid*) (*OldName: new PV; Cycle: 5;*) (*V04.12.00.00*)
		iCnt_OpHours : DINT; (*operating hours counter*) (*OldName: betrieb_h; Cycle: 5;*) (*V04.04.00.00*)
		iIdx_Gtyp_Dem : INT; (*actual gassort 1..4*) (*OldName: gasart; Cycle: 5;*) (*V04.00.00.00*)
		iIdx_OMSS : INT; (*operationg mode selection switch (0= OFF / 1=Hand / 2= Auto / 3=Test / 4=Spülen)*) (*OldName: BWS_HA; Cycle: 5;*) (*V04.00.00.00*)
		iSt_OpMode : UDINT; (*engine operation mode*) (*OldName: LeerlM, NetpM, InselM, StartM, StopM; Cycle: 5;*) (*V04.01.00.00*)
		rCustomizedCH : ARRAY[0..99]OF REAL; (*optional prepared customizable interface - BETA PHASE, use only in coordination with TPSS*) (*OldName: new PV; Cycle: 5;*) (*V04.05.00.00*)
		rGT_QualMix_1_2 : REAL; (*mixture ratio between gas 1 and 2 [%]*) (*OldName: ssMisch1_2; Cycle: 2; *) (*V04.00.00.00*)
		rGT_RatioMix : REAL; (*gas mixture ratio [%]*) (*OldName: ssRatioMix; Cycle: 2; *) (*V04.00.00.00*)
		rN_EngAct : REAL; (*engine speed [rpm]*) (*OldName: n_ist; Cycle: 5;*) (*V04.00.00.00*)
		rPos_CBV : REAL; (*compressor bypass valve position [%]*) (*OldName: turbo_y; Cycle: 5;*) (*V04.04.00.00*)
		rPr_Baro_Internal : REAL; (*internal value for barometric pressure [bar (abs)]*) (*OldName: new PV; Cycle: 5;*) (*V04.04.00.00*)
		rP_Act_Norm_Filt : REAL; (*actual power related to rP_Nom filtered T=1s [%Pnom]*) (*OldName: P_IST_PROM; Cycle: 5;*) (*V04.00.00.00*)
		rP_Act_Norm_Filt_TC2 : REAL; (*actual power related to rP_Nom filtered T=1s [%Pnom]*) (*OldName: P_IST_PROM; Cycle: 2;*) (*V04.05.00.00*)
		rP_Nom : REAL; (*nominal electric power, depends on gastype [kW]*) (*OldName: PN_GASART; Cycle: 5;*) (*V04.04.00.00*)
		rVE_Eng : REAL; (* Volumetric Efficiency *) (* OldName: rLieferGMotor; Cycle: 2 *) (*V04.05.00.00*)
		rVol_TotalGas_Norm : REAL; (*total gas volume flow [Nm³/h]*) (*OldName: ulFlowLong; Cycle: 5;*) (*V04.04.00.00*)
		szEng_Motorversion : STRING[17]; (*engine version *) (*OldName: new PV; Cycle: 5;*) (*V04.04.00.00*)
		tAB2CH : AmmBase2MM; (*AMM structure*) (*OldName: new PV; Cycle: 5;*) (*V04.00.00.00*)
		tDPr_AirFilt : HALioAi_Type; (*engine air inlet filter difference pressure [bar] (M.05-PID-002)*) (*OldName: new PV; Cycle: 5;*) (*V04.00.00.00*)
		tDPr_AirFilt_A : HALioAi_Type; (*engine air inlet filter difference pressure A [bar] (M.05-PID-101)*) (*OldName: AI_dp_AirInFiltA; Cycle: 5;*) (*V04.00.00.00*)
		tDPr_AirFilt_B : HALioAi_Type; (*engine air inlet filter difference pressure B [bar] (M.05-PID-201)*) (*OldName: AI_dp_AirInFiltB; Cycle: 5;*) (*V04.00.00.00*)
		tEng_Run : HALioDo_Type; (*engine is running*) (*OldName: M_BTRB; Cycle: 2;*) (*V04.00.00.00*)
		tGCB_On : HALioDi_Type; (*generator circuit breaker CLOSED*) (*OldName: GCB_ON; Cycle: 5;*) (*V04.00.00.00*)
		tN_TCHP : HALioAi_Type; (*high-pressure turbocharger speed [rpm] (E.02-SI-001)*) (*OldName: TRB_WE; Cycle: 5;*) (*V04.00.00.00*)
		tN_TCHP_A : HALioAi_Type; (*high-pressure turbocharger speed A [rpm] (E(M).02-SI-101)*) (*OldName: ssTurboSpdA_WE, TRB1_WE, ssTurboSpdA; Cycle: 5;*) (*V04.00.00.00*)
		tN_TCHP_B : HALioAi_Type; (*high-pressure turbocharger speed B [rpm] (E(M).02-SI-201)*) (*OldName: ssTurboSpdB_WE, TRB2_WE, ssTurboSpdB; Cycle: 5;*) (*V04.00.00.00*)
		tN_TCLP : HALioAi_Type; (*low-pressure turbocharger speed [rpm] (---)*) (*OldName: AI_TurboSpd_LP; Cycle: 5;*) (*V04.00.00.00*)
		tN_TCLP_A : HALioAi_Type; (*low-pressure turbocharger speed A [rpm] (M.02-SI-102)*) (*OldName: ssTurboSpd_LP_A_WE, AI_TurboSpd_LP_A, ssTurboSpd_LP_A; Cycle: 5;*) (*V04.00.00.00*)
		tN_TCLP_B : HALioAi_Type; (*low-pressure turbocharger speed B [rpm] (M.02-SI-202)*) (*OldName: ssTurboSpd_LP_B_WE, AI_TurboSpd_LP_B, ssTurboSpd_LP_B; Cycle: 5;*) (*V04.00.00.00*)
		tPB2MM : ParaBase2MM_type; (*PARA structure*) (*OldName: new PV; Cycle: 5;*) (*V04.00.00.00*)
		tPr_Ch_P1HP : HALioAi_Type; (*charge pressure p1 before high-pressure TC [bar] (M.08-PI-007)*) (*OldName: p1_HD_WE; Cycle: 2;*) (*V04.00.00.00*)
		tPr_Ch_P1HP_A : HALioAi_Type; (*charge pressure p1 before high-pressure TC A [bar] (M.08-PI-007 / M.05-PI-148)*) (*OldName: p1_HD_A_WE, ssPressP1_HD_A; Cycle: 2;*) (*V04.00.00.00*)
		tPr_Ch_P1HP_B : HALioAi_Type; (*charge pressure p1 before high-pressure TC B [bar] (M.08-PI-008 / M.05-PI-248)*) (*OldName: p1_HD_B_WE, ssPressP1_HD_B; Cycle: 2;*) (*V04.00.00.00*)
		tPr_Ch_P1LP_A : HALioAi_Type; (*charge pressure p1 before  low-pressure TC A [bar] (M.05-PI-146)*) (*OldName: new PV; Cycle: 2;*) (*V04.04.00.00*)
		tPr_Ch_P1LP_B : HALioAi_Type; (*charge pressure p1 before  low-pressure TC B [bar] (M.05-PI-246)*) (*OldName: new PV; Cycle: 2;*) (*V04.04.00.00*)
		tPr_Ch_P2 : HALioAi_Type; (*charge pressure p2 before throttle valve [bar] (E.08-PI-002)*) (*OldName: AI_P2_TC1, P2_WE; Cycle: 2;*) (*V04.00.00.00*)
		tPr_Ch_P2bFA : HALioAi_Type; (*charge pressure before flame arrester [bar] (E.08-PI-003)*) (*OldName: new PV; Cycle: 2;*) (*V04.04.00.00*)
		tPr_Ch_P2HP : HALioAi_Type; (*charge pressure after high-pressure turbocharger [bar] (E.08-PI-004)*) (*OldName: new PV; Cycle: 2;*) (*V04.04.00.00*)
		tPr_Ch_P2HP_A : HALioAi_Type; (*charge pressure after high-pressure turbocharger A [bar] (M.05-PI-149)*) (*OldName: new PV; Cycle: 2;*) (*V04.04.00.00*)
		tPr_Ch_P2HP_B : HALioAi_Type; (*charge pressure after high-pressure turbocharger B [bar] (M.05-PI-249)*) (*OldName: new PV; Cycle: 2;*) (*V04.04.00.00*)
		tPr_Ch_P2LP : HALioAi_Type; (*charge pressure after low-pressure turbocharger [bar] (M.08-PI-011)*) (*OldName: new PV; Cycle: 2;*) (*V04.04.00.00*)
		tPr_Ch_P2LP_A : HALioAi_Type; (*charge pressure after low-pressure turbocharger A [bar] (M.05-PI-147)*) (*OldName: new PV; Cycle: 2;*) (*V04.04.00.00*)
		tPr_Ch_P2LP_B : HALioAi_Type; (*charge pressure after low-pressure turbocharger B [bar] (M.05-PI-247)*) (*OldName: new PV; Cycle: 2;*) (*V04.04.00.00*)
		tPr_Ch_P2s : HALioAi_Type; (*charge pressure p2' after throttle valve [bar] (E.08-PI-001)*) (*OldName: AI_PressP2_TC1, ssPressP2WE, pl_ist, LDRIST, ANA.LDRIST; Cycle: 2;*) (*V04.00.00.00*)
		tPr_Ch_P2s_A : HALioAi_Type; (*charge pressure p2' after throttle valve A [bar] (M.05-PI-150)*) (*OldName: AI_PressP2s_A_TC1, AIPressP2s_A, rPressP2s_A; Cycle: 2;*) (*V04.00.00.00*)
		tPr_Ch_P2s_B : HALioAi_Type; (*charge pressure p2' after throttle valve B [bar] (M.05-PI-250)*) (*OldName: AI_PressP2s_B_TC1, AIPressP2s_B, rPressP2s_B; Cycle: 2;*) (*V04.00.00.00*)
		tPr_Ch_P2_A : HALioAi_Type; (*charge pressure p2 before throttle valve A [bar] (M.05-PI-151)*) (*OldName: AI_PressP2_A_TC1, AIPressP2_A, ssPressP2_A, rPressP2_A; Cycle: 2;*) (*V04.00.00.00*)
		tPr_Ch_P2_B : HALioAi_Type; (*charge pressure p2 before throttle valve B [bar] (M.05-PI-251)*) (*OldName: AI_PressP2_B_TC1, AIPressP2_B, ssPressP2_B, rPressP2_B; Cycle: 2;*) (*V04.00.00.00*)
		tP_Act : ARRAY[0..2]OF HALioAi_Type; (*actual electric power [kW]*) (*OldName: P_IST_OF; Cycle: 5;*) (*V04.04.00.00*)
		tT_Ch_T1HP : HALioAi_Type; (*charge temperature before high-pressure TC [°C] (M.08-TI-007)*) (*OldName: AI_t_CMbHPTC; Cycle: 2;*) (*V04.00.00.00*)
		tT_Ch_T1HP_A : HALioAi_Type; (*charge temperature before high-pressure TC A [°C] (M.08-TI-007 / M.05-TI-162)*) (*OldName: AI_t_CMbHPTC_A, t_CMbHPTC_A; Cycle: 2;*) (*V04.00.00.00*)
		tT_Ch_T1HP_B : HALioAi_Type; (*charge temperature before high-pressure TC B [°C] (M.08-TI-008 / M.05-TI-262)*) (*OldName: AI_t_CMbHPTC_B, t_CMbHPTC_B; Cycle: 2;*) (*V04.00.00.00*)
		tT_Ch_T1LP : HALioAi_Type; (*charge temperature before low-pressure turbocharger (= intake air) [°C] (M.05-TI-001)*) (*OldName: ssIATemp, ANA_ZLTP; Cycle: 2;*) (*V04.04.00.00*)
		tT_Ch_T1LP_A : HALioAi_Type; (*charge temperature before low-pressure turbocharger bank A (= intake air) [°C] (M.05-TI-132)*) (*OldName: new PV; Cycle: 2;*) (*V04.04.00.00*)
		tT_Ch_T1LP_B : HALioAi_Type; (*charge temperature before low-pressure turbocharger bank B (= intake air) [°C] (M.05-TI-232)*) (*OldName: new PV; Cycle: 2;*) (*V04.04.00.00*)
		tT_Ch_T2HP : HALioAi_Type; (*charge temperature after high-pressure TC [°C]*) (*OldName: new PV; Cycle: 2;*) (*V04.05.00.00*)
		tT_Ch_T2HP_A : HALioAi_Type; (*charge temperature after high-pressure TC A [°C]*) (*OldName: new PV; Cycle: 2;*) (*V04.05.00.00*)
		tT_Ch_T2HP_B : HALioAi_Type; (*charge temperature after high-pressure TC B [°C]*) (*OldName: new PV; Cycle: 2;*) (*V04.05.00.00*)
		tT_Ch_T2LP : HALioAi_Type; (*charge temperature after low-pressure turbocharger (= intake air) [°C]*) (*OldName: new PV; Cycle: 2;*) (*V04.05.00.00*)
		tT_Ch_T2LP_A : HALioAi_Type; (*charge temperature after low-pressure turbocharger bank A (= intake air) [°C]*) (*OldName: new PV; Cycle: 2;*) (*V04.05.00.00*)
		tT_Ch_T2LP_B : HALioAi_Type; (*charge temperature after low-pressure turbocharger bank B (= intake air) [°C]*) (*OldName: new PV; Cycle: 2;*) (*V04.05.00.00*)
		tT_Ch_T2s : HALioAi_Type; (*charge temperature t2' after throttle valve [°C] (E.08-TI-001)*) (*OldName: LLTP, tg_ist, ANA.LLTP; Cycle: 2;*) (*V04.00.00.00*)
		tT_Ch_T2s_A : HALioAi_Type; (*charge temperature t2' after throttle valve A [°C] (M.05-TI-150)*) (*OldName: AI_CATP_A_TC1, AI_CTAP_A, ssCTAP_A, rCTAP_A; Cycle: 2;*) (*V04.00.00.00*)
		tT_Ch_T2s_B : HALioAi_Type; (*charge temperature t2' after throttle valve B [°C] (M.05-TI-250)*) (*OldName: AI_CATP_B_TC1, AI_CATP_B, ssCTAP_B, rCTAP_B; Cycle: 2;*) (*V04.00.00.00*)
	END_STRUCT;
	MM2VIS_Struct : 	STRUCT 
		bMsg1040 : BOOL; (*Prio2: Charge temperature t2' maximum*) (*OldName: M_LLTP; Cycle: 5;*) (*V04.00.00.00*)
		bMsg1077 : BOOL; (*Prio2: Measuring signal failure charge pressure p2 (before throttle valve)*											(*OldName: M_RPSA5; Cycle: 5;*) (*OldName: ALM[1077].Q; Cycle: 5;*) (*V04.00.00.00*)
		bMsg1078 : BOOL; (*Prio2: Measuring signal failure charge pressure*) (*OldName: M_RPSA6; Cycle: 5;*) (*V04.00.00.00*)
		bMsg1105 : BOOL; (*Prio2: Speed of charge temperature t2' change maximum*) (*OldName: ALM[1105].Q; Cycle: 5;*) (*V04.00.00.00*)
		bMsg1114 : BOOL; (*Prio3: Measuring signal failure charge temperature t2'*) (*OldName: ALM[1114].Q; Cycle: 5;*) (*V04.00.00.00*)
		bMsg2215 : BOOL; (*Prio3: Measuring signal failure charge temperature t2' A - NOT USED *) (*OldName: ALM[2215].Q; Cycle: 5;*) (*V04.00.00.00*)
		bMsg2216 : BOOL; (*Prio2: Charge temperature t2' A maximum*) (*OldName: ALM[2216].Q; Cycle: 5;*) (*V04.00.00.00*)
		bMsg2217 : BOOL; (*Prio2: Rate of charge temperature t2' A change maximum*) (*OldName: ALM[2217].Q; Cycle: 5;*) (*V04.00.00.00*)
		bMsg2218 : BOOL; (*Prio3: Measuring signal failure charge temperature t2' B - NOT USED *) (*OldName: ALM[2218].Q; Cycle: 5;*) (*V04.00.00.00*)
		bMsg2219 : BOOL; (*Prio2: Charge temperature t2' B maximum*) (*OldName: ALM[2219].Q; Cycle: 5;*) (*V04.00.00.00*)
		bMsg2220 : BOOL; (*Prio2: Rate of charge temperature t2' B change maximum*) (*OldName: ALM[2220].Q; Cycle: 5;*) (*V04.00.00.00*)
		bMsg2221 : BOOL; (*Prio3: Measuring signal failure charge temperature before high-pressure TC A - NOT USED*) (*OldName: ALM[2221].Q; Cycle: 5;*) (*V04.00.00.00*)
		bMsg2222 : BOOL; (*Prio3: Measuring signal failure charge temperature before high-pressure TC B - NOT USED*) (*OldName: ALM[2222].Q; Cycle: 5;*) (*V04.00.00.00*)
		bMsg2223 : BOOL; (*Prio3: Charge temperature before high-pressure TC maximum - NOT USED >= v4.12*) (*OldName: ALM[2223].Q; Cycle: 5;*) (*V04.00.00.00*)
		bMsg2225 : BOOL; (*Prio3: High pressure turbocharger speed deviation maximum*) (*OldName: ALM[2225].Q; Cycle: 5;*) (*V04.00.00.00*)
		bMsg2226 : BOOL; (*Prio3: Low pressure turbocharger speed deviation maximum*) (*OldName: ALM[2226].Q; Cycle: 5;*) (*V04.00.00.00*)
		bMsg2236 : BOOL; (*Prio3: Charge pressure p2' deviation maximum*) (*OldName: ALM[2236].Q; Cycle: 5;*) (*V04.00.00.00*)
		bMsg2237 : BOOL; (*Prio3: High pressure turbocharger speed maximum*) (*OldName: ALM[2237].Q; Cycle: 5;*) (*V04.00.00.00*)
		bMsg2239 : BOOL; (*Prio3: Low pressure turbocharger speed maximum*) (*OldName: ALM[2239].Q; Cycle: 5;*) (*V04.00.00.00*)
		bMsg2258 : BOOL; (*Prio3: Measuring signal failure charge temperature t2 A - NOT USED*) (*OldName: ALM[2258].Q; Cycle: 5;*) (*V04.00.00.00*)
		bMsg2259 : BOOL; (*Prio3: Measuring signal failure charge temperature t2 B - NOT USED*) (*OldName: ALM[2259].Q; Cycle: 5;*) (*V04.00.00.00*)
		bMsg2278 : BOOL; (*Prio3: turbocharger speed maximum*) (*OldName: ALM[2278].Q; Cycle: 5;*) (*V04.00.00.00*)
		bMsg2279 : BOOL; (*Prio3: turbocharger speed deviation maximum*) (*OldName: ALM[2279].Q; Cycle: 5;*) (*V04.00.00.00*)
		bMsg2280 : BOOL; (*Prio3: Measuring signal failure charge temperature before high-pressure TC*) (*OldName: ALM[2280].Q; Cycle: 5;*) (*V04.00.00.00*)
		bMsg2317 : BOOL; (*Prio3: Charge temperature before TC maximum (only if no low-pressure TC exist) - NOT USED >= v4.12*) (*OldName: new PV; Cycle: 5;*) (*V04.00.00.00*)
		bMsg2318 : BOOL; (*Prio3: Measuring signal failure charge temperature before TC (only if no low-pressure TC exist)*) (*OldName: new PV; Cycle: 5;*) (*V04.00.00.00*)
		bMsg2324 : BOOL; (*Prio3: Charge temperature before turbocharger (air intake) maximum - NOT USED >= v4.12*) (*OldName: new PV; Cycle: 5;*) (*V04.05.01.00*)
		bMsg2325 : BOOL; (*Prio3: Measuring signal failure, BOTH turbocharger speed*) (*OldName: new PV; Cycle: 5;*) (*V04.05.01.00*)
		bMsg2326 : BOOL; (*Prio3: Measuring signal failure, BOTH high pressure turbocharger speed*) (*OldName: new PV; Cycle: 5;*) (*V04.05.01.00*)
		bMsg2327 : BOOL; (*Prio3: Measuring signal failure, BOTH low pressure turbocharger speed*) (*OldName: new PV; Cycle: 5;*) (*V04.05.01.00*)
		bMsg2368 : BOOL; (*Prio3: Charge temperature after high-pressure TC maximum*) (*OldName: new PV; Cycle: 5;*) (*V04.12.00.00*)
		bMsg2369 : BOOL; (*Prio3: Charge temperature after TC maximum (only if no low-pressure TC exist)*) (*OldName: new PV; Cycle: 5;*) (*V04.12.00.00*)
		bMsg2370 : BOOL; (*Prio3: Charge temperature after low-pressure TC maximum*) (*OldName: new PV; Cycle: 5;*) (*V04.12.00.00*)
		bMsg2407 : BOOL; (*Prio4: Measuring signal failure charge pressure after high-pressure turbocharger A*) (*OldName: new PV; Cycle: 5;*) (*V04.04.00.00*)
		bMsg2408 : BOOL; (*Prio4: Measuring signal failure charge pressure after high-pressure turbocharger B*) (*OldName: new PV; Cycle: 5;*) (*V04.04.00.00*)
		bMsg2409 : BOOL; (*Prio4: Measuring signal failure charge pressure after low-pressure turbocharger A*) (*OldName: new PV; Cycle: 5;*) (*V04.04.00.00*)
		bMsg2410 : BOOL; (*Prio4: Measuring signal failure charge pressure after low-pressure turbocharger B*) (*OldName: new PV; Cycle: 5;*) (*V04.04.00.00*)
		bMsg2411 : BOOL; (*Prio4: Measuring signal failure charge temperature before turbocharger (air intake)*) (*OldName: new PV; Cycle: 5;*) (*V04.04.00.00*)
		bMsg2412 : BOOL; (*Prio4: Charge temperature before turbocharger (air intake) maximum - NOT USED >= v4.12*) (*OldName: new PV; Cycle: 5;*) (*V04.04.00.00*)
		bMsg2413 : BOOL; (*Prio4: Measuring signal failure, charge temperature before turbocharger (air intake) A*) (*OldName: new PV; Cycle: 5;*) (*V04.04.00.00*)
		bMsg2414 : BOOL; (*Prio4: Measuring signal failure, charge temperature before turbocharger (air intake) B*) (*OldName: new PV; Cycle: 5;*) (*V04.04.00.00*)
		bMsg2436 : BOOL; (*Prio4: Charge temperature t2' A maximum - NOT USED*) (*OldName: new PV; Cycle: 5;*) (*V04.05.00.00*)
		bMsg2437 : BOOL; (*Prio4: Charge temperature t2'  B maximum - NOT USED*) (*OldName: new PV; Cycle: 5;*) (*V04.05.00.00*)
		bMsg2460 : BOOL; (*Prio4: Measuring signal failure charge temperature before high-pressure TC A*) (*OldName: new PV; Cycle: 5;*) (*V04.05.00.00*)
		bMsg2461 : BOOL; (*Prio4: Measuring signal failure charge temperature before high-pressure TC B*) (*OldName: new PV; Cycle: 5;*) (*V04.05.00.00*)
		bMsg2477 : BOOL; (*Prio4: Charge temperature before TC minimum (only if no low-pressure TC exist)*) (*OldName: new PV; Cycle: 5;*) (*V04.05.00.00*)
		bMsg2478 : BOOL; (*Prio4: Charge temperature before TC maximum (only if no low-pressure TC exist) - NOT USED >= v4.12*) (*OldName: new PV; Cycle: 5;*) (*V04.05.00.00*)
		bMsg2479 : BOOL; (*Prio4: Measuring signal failure charge temperature before TC A (only if no low-pressure TC exist)*) (*OldName: new PV; Cycle: 5;*) (*V04.05.00.00*)
		bMsg2480 : BOOL; (*Prio4: Measuring signal failure charge temperature before TC B (only if no low-pressure TC exist)*) (*OldName: new PV; Cycle: 5;*) (*V04.05.00.00*)
		bMsg2481 : BOOL; (*Prio4: Measuring signal failure charge temperature after low-pressure TC A*) (*OldName: new PV; Cycle: 5;*) (*V04.05.00.00*)
		bMsg2482 : BOOL; (*Prio4: Measuring signal failure charge temperature after low-pressure TC B*) (*OldName: new PV; Cycle: 5;*) (*V04.05.00.00*)
		bMsg2483 : BOOL; (*Prio4: Measuring signal failure charge temperature after high-pressure TC A*) (*OldName: new PV; Cycle: 5;*) (*V04.05.00.00*)
		bMsg2484 : BOOL; (*Prio4: Measuring signal failure charge temperature after high-pressure TC B*) (*OldName: new PV; Cycle: 5;*) (*V04.05.00.00*)
		bMsg2485 : BOOL; (*Prio4: Measuring signal failure charge temperature after TC A (only if no low-pressure TC exist)*) (*OldName: new PV; Cycle: 5;*) (*V04.05.00.00*)
		bMsg2486 : BOOL; (*Prio4: Measuring signal failure charge temperature after TC B (only if no low-pressure TC exist)*) (*OldName: new PV; Cycle: 5;*) (*V04.05.00.00*)
		bMsg2489 : BOOL; (*Prio4: Measuring signal failure charge temperature after low-pressure TC*) (*OldName: new PV; Cycle: 5;*) (*V04.05.00.00*)
		bMsg2490 : BOOL; (*Prio4: Measuring signal failure charge temperature after high-pressure TC*) (*OldName: new PV; Cycle: 5;*) (*V04.05.00.00*)
		bMsg2491 : BOOL; (*Prio4: Measuring signal failure charge temperature after TC (only if no low-pressure TC exist)*) (*OldName: new PV; Cycle: 5;*) (*V04.05.00.00*)
		bMsg2510 : BOOL; (*Prio4: Charge temperature t2' A minimum*) (*OldName: ALM[2510].Q; Cycle: 5;*) (*V04.00.00.00*)
		bMsg2511 : BOOL; (*Prio4: Charge temperature t2' A maximum*) (*OldName: ALM[2511].Q; Cycle: 5;*) (*V04.00.00.00*)
		bMsg2512 : BOOL; (*Prio4: Charge temperature t2' B minimum*) (*OldName: ALM[2512].Q; Cycle: 5;*) (*V04.00.00.00*)
		bMsg2513 : BOOL; (*Prio4: Charge temperature t2' B maximum*) (*OldName: ALM[2513].Q; Cycle: 5;*) (*V04.00.00.00*)
		bMsg2525 : BOOL; (*Prio4: Charge temperature t2' deviation maximum*) (*OldName: ALM[2525].Q; Cycle: 5;*) (*V04.00.00.00*)
		bMsg2526 : BOOL; (*Prio4: High pressure turbocharger speed maximum*) (*OldName: ALM[2526].Q; Cycle: 5;*) (*V04.00.00.00*)
		bMsg2527 : BOOL; (*Prio4: Low pressure turbocharger speed maximum*) (*OldName: ALM[2527].Q; Cycle: 5;*) (*V04.00.00.00*)
		bMsg2528 : BOOL; (*Prio4: High pressure turbocharger speed deviation maximum*) (*OldName: ALM[2528].Q; Cycle: 5;*) (*V04.00.00.00*)
		bMsg2529 : BOOL; (*Prio4: Low pressure turbocharger speed deviation maximum*) (*OldName: ALM[2529].Q; Cycle: 5;*) (*V04.00.00.00*)
		bMsg2530 : BOOL; (*Prio4: Charge pressure p2 (before throttle valve) deviation maximum*) (*OldName: ALM[2530].Q; Cycle: 5;*) (*V04.00.00.00*)
		bMsg2531 : BOOL; (*Prio4: Charge temperature before high-pressure TC minimum*) (*OldName: ALM[2531].Q; Cycle: 5;*) (*V04.00.00.00*)
		bMsg2532 : BOOL; (*Prio4: Charge temperature before high-pressure TC inclination maximum - NOT USED*) (*OldName: ALM[2532].Q; Cycle: 5;*) (*V04.00.00.00*)
		bMsg2533 : BOOL; (*Prio4: Charge temperature before high-pressure TC maximum - NOT USED >= v4.12*) (*OldName: ALM[2533].Q; Cycle: 5;*) (*V04.00.00.00*)
		bMsg2539 : BOOL; (*Prio4: Measuring signal failure charge pressure p2' A*) (*OldName: ALM[2539].Q; Cycle: 5;*) (*V04.00.00.00*)
		bMsg2540 : BOOL; (*Prio4: Measuring signal failure charge pressure p2' B*) (*OldName: ALM[2540].Q; Cycle: 5;*) (*V04.00.00.00*)
		bMsg2541 : BOOL; (*Prio4: Measuring signal failure charge pressure p2 (before throttle valve) A*) (*OldName: ALM[2541].Q; Cycle: 5;*) (*V04.00.00.00*)
		bMsg2543 : BOOL; (*Prio4: Measuring signal failure charge pressure p2 (before throttle valve) B*) (*OldName: ALM[2543].Q; Cycle: 5;*) (*V04.00.00.00*)
		bMsg2548 : BOOL; (*Prio4: Measuring signal failure air inlet filter difference pressure A*) (*OldName: ALM[2548].Q; Cycle: 5;*) (*V04.00.00.00*)
		bMsg2550 : BOOL; (*Prio4: Measuring signal failure air inlet filter difference pressure B*) (*OldName: ALM[2550].Q; Cycle: 5;*) (*V04.00.00.00*)
		bMsg2563 : BOOL; (*Prio4: Measuring signal failure high-pressure turbocharger speed A*) (*OldName: ALM[2563].Q; Cycle: 5;*) (*V04.00.00.00*)
		bMsg2564 : BOOL; (*Prio4: Measuring signal failure high-pressure turbocharger speed B*) (*OldName: ALM[2564].Q; Cycle: 5;*) (*V04.00.00.00*)
		bMsg2565 : BOOL; (*Prio4: Measuring signal failure low-pressure turbocharger speed A*) (*OldName: ALM[2565].Q; Cycle: 5;*) (*V04.00.00.00*)
		bMsg2566 : BOOL; (*Prio4: Measuring signal failure low-pressure turbocharger speed B*) (*OldName: ALM[2566].Q; Cycle: 5;*) (*V04.00.00.00*)
		bMsg2611 : BOOL; (*Prio4: Measuring signal failure charge pressure p1 before high-pressure TC A*) (*OldName: ALM[2611].Q; Cycle: 5;*) (*V04.00.00.00*)
		bMsg2612 : BOOL; (*Prio4: Measuring signal failure charge pressure p1 before high-pressure TC B*) (*OldName: ALM[2612].Q; Cycle: 5;*) (*V04.00.00.00*)
		bMsg2614 : BOOL; (*Prio4: turbocharger speed deviation maximum*) (*OldName: ALM[2614].Q; Cycle: 5;*) (*V04.00.00.00*)
		bMsg2615 : BOOL; (*Prio4: Measuring signal failure turbocharger speed*) (*OldName: ALM[2615].Q; Cycle: 5;*) (*V04.00.00.00*)
		bMsg2616 : BOOL; (*Prio4: Measuring signal failure high-pressure turbocharger speed*) (*OldName: ALM[2616].Q; Cycle: 5;*) (*V04.00.00.00*)
		bMsg2617 : BOOL; (*Prio4: Measuring signal failure low-pressure turbocharger speed*) (*OldName: ALM[2617].Q; Cycle: 5;*) (*V04.00.00.00*)
		bMsg2618 : BOOL; (*Prio4: Measuring signal failure charge pressure p1 before high-pressure TC*) (*OldName: ALM[2618].Q; Cycle: 5;*) (*V04.00.00.00*)
		bMsg2619 : BOOL; (*Prio4: Measuring signal failure charge temperature t2' A*) (*OldName: ALM[2619].Q; Cycle: 5;*) (*V04.00.00.00*)
		bMsg2620 : BOOL; (*Prio4: Measuring signal failure charge temperature t2' B*) (*OldName: ALM[2620].Q; Cycle: 5;*) (*V04.00.00.00*)
		bMsg2621 : BOOL; (*Prio4: Measuring signal failure air inlet filter difference pressure*) (*OldName: ALM[2621].Q; Cycle: 5;*) (*V04.00.00.00*)
		bMsg2626 : BOOL; (*Prio4: Air inlet filter difference pressure low *) (*OldName: new PV; Cycle: 5;*) (*V04.04.00.00*)
		bMsg2668 : BOOL; (*Prio4: Measuring signal failure charge pressure after low-pressure turbocharger*) (*OldName: new PV; Cycle: 5;*) (*V04.04.00.00*)
		bMsg2669 : BOOL; (*Prio4: Measuring signal failure charge pressure after high-pressure turbocharger*) (*OldName: new PV; Cycle: 5;*) (*V04.04.00.00*)
		bMsg2670 : BOOL; (*Prio4: Measuring signal failure charge pressure before flame arrester*) (*OldName: new PV; Cycle: 5;*) (*V04.04.00.00*)
		bMsg2671 : BOOL; (*Prio4: Differential pressure over low-pressure charge cooler maximum*) (*OldName: new PV; Cycle: 5;*) (*V04.04.00.00*)
		bMsg2672 : BOOL; (*Prio4: Differential pressure over high-pressure charge cooler maximum*) (*OldName: new PV; Cycle: 5;*) (*V04.04.00.00*)
		bMsg2673 : BOOL; (*Prio4: Differential pressure over flame arrester maximum*) (*OldName: new PV; Cycle: 5;*) (*V04.04.00.00*)
		bMsg2700 : BOOL; (*Prio4: Charge air filter difference pressure maximum*) (*OldName: new PV; Cycle: 5;*) (*V04.04.00.00*)
		bMsg2779 : BOOL; (*Prio4: Measuring signal failure charge pressure p1 before  low-pressure TC A*) (*OldName: new PV; Cycle: 5;*) (*V04.04.00.00*)
		bMsg2780 : BOOL; (*Prio4: Measuring signal failure charge pressure p1 before  low-pressure TC B*) (*OldName: new PV; Cycle: 5;*) (*V04.04.00.00*)
		bMsg3411 : BOOL; (*Prio4: Charge temperature t2' maximum*) (*OldName: ALM[3411].Q; Cycle: 5;*) (*V04.00.00.00*)
		bMsg3522 : BOOL; (*Prio4: Measuring signal failure turbocharger speed A*) (*OldName: ALM[3522].Q; Cycle: 5;*) (*V04.00.00.00*)
		bMsg3523 : BOOL; (*Prio4: Measuring signal failure turbocharger speed B*) (*OldName: ALM[3523].Q; Cycle: 5;*) (*V04.00.00.00*)
		bMsg3524 : BOOL; (*Prio4: Turbocharger speed maximum*) (*OldName: ALM[3524].Q; Cycle: 5;*) (*V04.00.00.00*)
		bMsg3562 : BOOL; (*Prio4: Charge temperature t2' minimum*) (*OldName: ALM[3562].Q; Cycle: 5;*) (*V04.00.00.00*)
		bMsg3597 : BOOL; (*Prio4: Charge air filter difference pressure  low A*) (*OldName: new PV; Cycle: 5;*) (*V04.04.00.00*)
		bMsg3598 : BOOL; (*Prio4: Charge air filter difference pressure high A*) (*OldName: new PV; Cycle: 5;*) (*V04.04.00.00*)
		bMsg3599 : BOOL; (*Prio4: Charge air filter difference pressure  low B*) (*OldName: new PV; Cycle: 5;*) (*V04.04.00.00*)
		bMsg3600 : BOOL; (*Prio4: Charge air filter difference pressure high B*) (*OldName: new PV; Cycle: 5;*) (*V04.04.00.00*)
		bMsg9237 : BOOL; (*Prio4: Measuring signal failure, charge pressure after turbocharger*) (*OldName: new PV; Cycle: 5;*) (*V04.07.00.00*)
		bMsg9238 : BOOL; (*Prio4: Measuring signal failure, charge pressure after turbocharger A*) (*OldName: new PV; Cycle: 5;*) (*V04.07.00.00*)
		bMsg9239 : BOOL; (*Prio4: Measuring signal failure, charge pressure after turbocharger B*) (*OldName: new PV; Cycle: 5;*) (*V04.07.00.00*)
		bMsg9240 : BOOL; (*Prio4: Measuring signal failure, charge pressure before turbocharger*) (*OldName: new PV; Cycle: 5;*) (*V04.07.00.00*)
		bMsg9241 : BOOL; (*Prio4: Measuring signal failure, charge pressure before turbocharger A*) (*OldName: new PV; Cycle: 5;*) (*V04.07.00.00*)
		bMsg9242 : BOOL; (*Prio4: Measuring signal failure, charge pressure before turbocharger B*) (*OldName: new PV; Cycle: 5;*) (*V04.07.00.00*)
		bMsg9243 : BOOL; (*Prio4: Charge cooler differential pressure high*) (*OldName: new PV; Cycle: 5;*) (*V04.07.00.00*)
		bMsg9370 : BOOL; (*Prio4: Intercooler inlet temperature not definable*) (*OldName: new PV; Cycle: 5;*) (*V04.12.00.00*)
		rDPr_AirFilt : REAL; (*engine air inlet filter difference pressure [bar] (M.05-PID-002)*) (*OldName: new PV; Cycle: 5;*) (*V04.00.00.00*)
		rDPr_AirFilt_A : REAL; (*engine air inlet filter difference pressure A [bar] (M.05-PID-101)*) (*OldName: AI_dp_AirInFiltA; Cycle: 5;*) (*V04.00.00.00*)
		rDPr_AirFilt_B : REAL; (*engine air inlet filter difference pressure B [bar] (M.05-PID-201)*) (*OldName: AI_dp_AirInFiltB; Cycle: 5;*) (*V04.00.00.00*)
		rDPr_Ch_FA : REAL; (*difference pressure over flame arrester [bar]*) (*OldName: new PV; Cycle: 2;*) (*V04.04.00.00*)
		rDPr_Ch_HPCooler : REAL; (*difference pressure over high-pressure charge cooler [bar]*) (*OldName: new PV; Cycle: 2;*) (*V04.04.00.00*)
		rDPr_Ch_LPCooler : REAL; (*difference pressure over  low-pressure charge cooler [bar]*) (*OldName: new PV; Cycle: 2;*) (*V04.04.00.00*)
		rN_TCHP : REAL; (*high-pressure turbocharger speed [rpm] (E.02-SI-001)*) (*OldName: rN_TCHP; Cycle: 5;*) (*V04.00.00.00*)
		rN_TCHP_A : REAL; (*high-pressure turbocharger speed A [rpm] (E(M).02-SI-101)*) (*OldName: rN_TCHP_A, ssTurboSpdA; Cycle: 5;*) (*V04.00.00.00*)
		rN_TCHP_B : REAL; (*high-pressure turbocharger speed B [rpm] (E(M).02-SI-201)*) (*OldName: rN_TCHP_B, ssTurboSpdB; Cycle: 5;*) (*V04.00.00.00*)
		rN_TCLP : REAL; (*low  pressure turbocharger speed [rpm] (---)*) (*OldName: rN_TCLP, ssTurboSpd_LP; Cycle: 5;*) (*V04.00.00.00*)
		rN_TCLP_A : REAL; (*low  pressure turbocharger speed A [rpm] (M.02-SI-102)*) (*OldName: rN_TCLP_A, ssTurboSpd_LP_A; Cycle: 5;*) (*V04.00.00.00*)
		rN_TCLP_B : REAL; (*low  pressure turbocharger speed B [rpm] (M.02-SI-202)*) (*OldName: rN_TCLP_B, ssTurboSpd_LP_B; Cycle: 5;*) (*V04.00.00.00*)
		rPr_Ch_P1HP : REAL; (*charge pressure p1 before high-pressure TC [bar] (M.08-PI-007)*) (*OldName: p1_HD_WE; Cycle: 2;*) (*V04.00.00.00*)
		rPr_Ch_P1HP_A : REAL; (*charge pressure p1 before high-pressure TC A [bar] (M.08-PI-007 / M.05-PI-148)*) (*OldName: p1_HD_A_WE, ssPressP1_HD_A; Cycle: 2;*) (*V04.00.00.00*)
		rPr_Ch_P1HP_Avg : REAL; (*average charge pressure before high-pressure turbocharger [bar]*) (*OldName: new PV; Cycle: 2;*) (*V04.07.00.00*)
		rPr_Ch_P1HP_B : REAL; (*charge pressure p1 before high-pressure TC B [bar] (M.08-PI-008 / M.05-PI-248)*) (*OldName: p1_HD_B_WE, ssPressP1_HD_B; Cycle: 2;*) (*V04.00.00.00*)
		rPr_Ch_P1LP_A : REAL; (*charge pressure p1 before  low-pressure TC A [bar] (M.05-PI-146)*) (*OldName: new PV; Cycle: 2;*) (*V04.04.00.00*)
		rPr_Ch_P1LP_Avg : REAL; (*average charge pressure before low-pressure turbocharger [bar]*) (*OldName: new PV; Cycle: 2;*) (*V04.07.00.00*)
		rPr_Ch_P1LP_B : REAL; (*charge pressure p1 before  low-pressure TC B [bar] (M.05-PI-246)*) (*OldName: new PV; Cycle: 2;*) (*V04.04.00.00*)
		rPr_Ch_P2 : REAL; (*charge pressure p2 before throttle valve [bar] (E.08-PI-002)*) (*OldName: P2_WE, P2, ANA_P2; Cycle: 2;*) (*V04.00.00.00*)
		rPr_Ch_P2bFA : REAL; (*charge pressure before flame arrester [bar] (E.08-PI-003)*) (*OldName: new PV; Cycle: 2;*) (*V04.04.00.00*)
		rPr_Ch_P2HP : REAL; (*charge pressure after high-pressure turbocharger [bar] (E.08-PI-004)*) (*OldName: new PV; Cycle: 2;*) (*V04.04.00.00*)
		rPr_Ch_P2HP_A : REAL; (*charge pressure after high-pressure turbocharger A [bar] (M.05-PI-149)*) (*OldName: new PV; Cycle: 2;*) (*V04.04.00.00*)
		rPr_Ch_P2HP_Avg : REAL; (*average charge pressure after high-pressure turbocharger [bar]*) (*OldName: new PV; Cycle: 2;*) (*V04.07.00.00*)
		rPr_Ch_P2HP_B : REAL; (*charge pressure after high-pressure turbocharger B [bar] (M.05-PI-249)*) (*OldName: new PV; Cycle: 2;*) (*V04.04.00.00*)
		rPr_Ch_P2LP : REAL; (*charge pressure after low-pressure turbocharger [bar] (E.08-PI-011)*) (*OldName: new PV; Cycle: 2;*) (*V04.04.00.00*)
		rPr_Ch_P2LP_A : REAL; (*charge pressure after low-pressure turbocharger A [bar] (M.05-PI-147)*) (*OldName: new PV; Cycle: 2;*) (*V04.04.00.00*)
		rPr_Ch_P2LP_Avg : REAL; (*average charge pressure after low-pressure turbocharger [bar]*) (*OldName: new PV; Cycle: 2;*) (*V04.07.00.00*)
		rPr_Ch_P2LP_B : REAL; (*charge pressure after low-pressure turbocharger B [bar] (M.05-PI-247)*) (*OldName: new PV; Cycle: 2;*) (*V04.04.00.00*)
		rPr_Ch_P2s : REAL; (*charge pressure p2' after throttle valve [bar] (E.08-PI-001)*) (*OldName: pl_ist, LDRIST, ANA.LDRIST; Cycle: 2;*) (*V04.00.00.00*)
		rPr_Ch_P2s_A : REAL; (*charge pressure p2' after throttle valve A [bar] (M.05-PI-150)*) (*OldName: ssPressP2s_A, rPressP2s_A; Cycle: 2;*) (*V04.00.00.00*)
		rPr_Ch_P2s_Avg : REAL; (*average charge pressure p2' [bar]*) (*OldName: new PV; Cycle: 2;*) (*V04.03.00.00*)
		rPr_Ch_P2s_A_UF : REAL; (*charge pressure p2' after throttle valve A [bar] (M.05-PI-150) - UNFILTERED*) (*OldName: new PV; Cycle: 2;*) (*V04.07.00.00*)
		rPr_Ch_P2s_B : REAL; (*charge pressure p2' after throttle valve B [bar] (M.05-PI-250)*) (*OldName: ssPressP2s_B, rPressP2s_B; Cycle: 2;*) (*V04.00.00.00*)
		rPr_Ch_P2s_B_UF : REAL; (*charge pressure p2' after throttle valve B [bar] (M.05-PI-250) - UNFILTERED*) (*OldName: new PV; Cycle: 2;*) (*V04.07.00.00*)
		rPr_Ch_P2s_UF : REAL; (*charge pressure p2' after throttle valve [bar] (E.08-PI-001) - UNFILTERED*) (*OldName: new PV; Cycle: 2;*) (*V04.07.00.00*)
		rPr_Ch_P2_A : REAL; (*charge pressure p2 before throttle valve A [bar] (M.05-PI-151)*) (*OldName: ssPressP2_A, rPressP2_A; Cycle: 2;*) (*V04.00.00.00*)
		rPr_Ch_P2_Avg : REAL; (*average charge pressure p2 before throttle valve [bar]*) (*OldName: new PV; Cycle: 2;*) (*V04.07.00.00*)
		rPr_Ch_P2_B : REAL; (*charge pressure p2 before throttle valve B [bar] (M.05-PI-251)*) (*OldName: ssPressP2_B, rPressP2_B; Cycle: 2;*) (*V04.00.00.00*)
		rT_Ch_T1HP : REAL; (*charge temperature before high-pressure TC [°C] (M.08-TI-007)*) (*OldName: AI_t_CMbHPTC; Cycle: 2;*) (*V04.00.00.00*)
		rT_Ch_T1HP_A : REAL; (*charge temperature before high-pressure TC A [°C] (M.08-TI-007 / M.05-TI-162)*) (*OldName: AI_t_CMbHPTC_A, t_CMbHPTC_A; Cycle: 2;*) (*V04.00.00.00*)
		rT_Ch_T1HP_Avg : REAL; (*average charge temperature before high-pressure turbocharger [°C]*) (*OldName: new PV; Cycle: 2;*) (*V04.07.00.00*)
		rT_Ch_T1HP_B : REAL; (*charge temperature before high-pressure TC B [°C] (M.08-TI-008 / M.05-TI-262)*) (*OldName: AI_t_CMbHPTC_B, t_CMbHPTC_B; Cycle: 2;*) (*V04.00.00.00*)
		rT_Ch_T1LP : REAL; (*charge temperature before low-pressure turbocharger (= intake air) [°C] (M.05-TI-001)*) (*OldName: ssIATemp, ANA_ZLTP; Cycle: 2;*) (*V04.04.00.00*)
		rT_Ch_T1LP_A : REAL; (*charge temperature before low-pressure turbocharger bank A (= intake air) [°C] (M.05-TI-132)*) (*OldName: new PV; Cycle: 2;*) (*V04.04.00.00*)
		rT_Ch_T1LP_Avg : REAL; (*average charge temperature before low-pressure turbocharger (= engine intake air) [°C]*) (*OldName: new PV; Cycle: 2;*) (*V04.04.00.00*)
		rT_Ch_T1LP_B : REAL; (*charge temperature before low-pressure turbocharger bank B (= intake air) [°C] (M.05-TI-232)*) (*OldName: new PV; Cycle: 2;*) (*V04.04.00.00*)
		rT_Ch_T2HP : REAL; (*charge temperature after high-pressure TC [°C]*) (*OldName: new PV; Cycle: 2;*) (*V04.05.00.00*)
		rT_Ch_T2HP_A : REAL; (*charge temperature after high-pressure TC A [°C]*) (*OldName: new PV; Cycle: 2;*) (*V04.05.00.00*)
		rT_Ch_T2HP_B : REAL; (*charge temperature after high-pressure TC B [°C]*) (*OldName: new PV; Cycle: 2;*) (*V04.05.00.00*)
		rT_Ch_T2HP_Calc : REAL; (*Calculated value - charge temperature after high-pressure TC [°C]*) (*OldName: new PV; Cycle: 2;*) (*V04.12.00.00*)
		rT_Ch_T2LP : REAL; (*charge temperature after low-pressure turbocharger*) (*OldName: new PV; Cycle: 2;*) (*V04.05.00.00*)
		rT_Ch_T2LP_A : REAL; (*charge temperature after low-pressure turbocharger bank A*) (*OldName: new PV; Cycle: 2;*) (*V04.05.00.00*)
		rT_Ch_T2LP_B : REAL; (*charge temperature after low-pressure turbocharger bank B*) (*OldName: new PV; Cycle: 2;*) (*V04.05.00.00*)
		rT_Ch_T2LP_Calc : REAL; (*Calculated value - charge temperature after low-pressure TC [°C]*) (*OldName: new PV; Cycle: 2;*) (*V04.12.00.00*)
		rT_Ch_T2s : REAL; (*charge temperature t2' after throttle valve [°C] (E.08-TI-001)*) (*OldName: LLTP, tg_ist, ANA.LLTP; Cycle: 2;*) (*V04.00.00.00*)
		rT_Ch_T2s_A : REAL; (*charge temperature t2' after throttle valve A [°C] (M.05-TI-150)*) (*OldName: ssCTAP_A, rCTAP_A; Cycle: 2;*) (*V04.00.00.00*)
		rT_Ch_T2s_Avg : REAL; (*average charge temperature t2' [°C]*) (*OldName: new PV; Cycle: 2;*) (*V04.03.00.00*)
		rT_Ch_T2s_B : REAL; (*charge temperature t2' after throttle valve B [°C] (M.05-TI-250)*) (*OldName: ssCTAP_B, rCTAP_B; Cycle: 2;*) (*V04.00.00.00*)
		rVol_Ch_Engine_Norm : REAL; (*normalized engine mixture volume flow [Nm³/h]*) (*OldName: new PV; Cycle: 5;*) (*V04.05.00.00*)
		szPr_Ch_OoR : STRING[120]; (*Warning 9399 associated string for pressure signals out of range in standstill*)
		bMsg9399 : BOOL; (*Prio4: Boost pressure signal not plausible*) (*OldName: new PV; Cycle: 5;*) (*V04.14.00.00*)
	END_STRUCT;
	OUT_CH_Struct : 	STRUCT 
		bAMM_Pr_Ch_P1HP_Avg : BOOL; (*collective warning - average charge pressure before high-pressure turbocharger*) (*OldName: new PV; Cycle: 2;*) (*V04.07.00.00*)
		bAMM_Pr_Ch_P1LP_Avg : BOOL; (*collective warning - average charge pressure before low-pressure turbocharger*) (*OldName: new PV; Cycle: 2;*) (*V04.04.00.00*)
		bAMM_Pr_Ch_P2HP_Avg : BOOL; (*collective warning - average charge pressure after high-pressure turbocharger*) (*OldName: new PV; Cycle: 2;*) (*V04.07.00.00*)
		bAMM_Pr_Ch_P2LP_Avg : BOOL; (*collective warning - average charge pressure after low-pressure turbocharger*) (*OldName: new PV; Cycle: 2;*) (*V04.07.00.00*)
		bAMM_Pr_Ch_P2s_Avg : BOOL; (*collective warning - average charge pressure p2' *) (*OldName: new PV; Cycle: 2;*) (*V04.04.00.00*)
		bAMM_Pr_Ch_P2_Avg : BOOL; (*collective warning - average charge pressure p2 before throttle valve*) (*OldName: new PV; Cycle: 2;*) (*V04.07.00.00*)
		bAMM_T_Ch_T1HP_Avg : BOOL; (*collective warning - average charge temp. before high-pressure TC*) (*OldName: new PV; Cycle: 2;*) (*V04.07.00.00*)
		bAMM_T_Ch_T1LP_Avg : BOOL; (*collective warning - average charge temp. before low-pressure TC (= engine intake air)*) (*OldName: new PV; Cycle: 2;*) (*V04.04.00.00*)
		bAMM_T_Ch_T2s_Avg : BOOL; (*collective warning - average charge temp. t2'  *) (*OldName: new PV; Cycle: 2;*) (*V04.04.00.00*)
		bMsg1078 : BOOL; (*measuring signal failure charge pressure*) (*OldName: ALM[1078].Q; Cycle: 5;*) (*V04.01.00.00*)
		bRelEngStart_Ch_T2 : BOOL; (*release engine start from charge temperature after TC*) (*OldName: new PV; Cycle: 2;*) (*V04.12.00.00*)
		rCustomizedCH : ARRAY[0..99]OF REAL; (*optional prepared customizable interface - BETA PHASE, use only in coordination with TPSS*) (*OldName: new PV; Cycle: 5;*) (*V04.05.00.00*)
		rN_TCHP_HiHi : REAL; (*Interpolated high-pressure turbocharger speed maximum - trip [rpm]*) (*OldName: new PV; Cycle: 5;*) (*V04.10.00.00*)
		rN_TCLP_HiHi : REAL; (*Interpolated low-pressure turbocharger speed maximum - trip [rpm]*) (*OldName: new PV; Cycle: 5;*) (*V04.10.00.00*)
		rPr_Ch_P1HP_Avg : REAL; (*average charge pressure before high-pressure turbocharger [bar]*) (*OldName: new PV; Cycle: 2;*) (*V04.07.00.00*)
		rPr_Ch_P1HP_Max : REAL; (*maximum charge pressure before high-pressure turbocharger [bar]*) (*OldName: new PV; Cycle: 2;*) (*V04.12.00.00*)
		rPr_Ch_P1LP_Avg : REAL; (*average charge pressure before low-pressure turbocharger [bar]*) (*OldName: new PV; Cycle: 2;*) (*V04.04.00.00*)
		rPr_Ch_P1LP_Max : REAL; (*maximum charge pressure before low-pressure turbocharger [bar]*) (*OldName: new PV; Cycle: 2;*) (*V04.12.00.00*)
		rPr_Ch_P2HP_Avg : REAL; (*average charge pressure after high-pressure turbocharger [bar]*) (*OldName: new PV; Cycle: 2;*) (*V04.07.00.00*)
		rPr_Ch_P2HP_Max : REAL; (*maximum charge pressure after high-pressure turbocharger [bar]*) (*OldName: new PV; Cycle: 2;*) (*V04.12.00.00*)
		rPr_Ch_P2LP_Avg : REAL; (*average charge pressure after low-pressure turbocharger [bar]*) (*OldName: new PV; Cycle: 2;*) (*V04.07.00.00*)
		rPr_Ch_P2LP_Max : REAL; (*maximum charge pressure after low-pressure turbocharger [bar]*) (*OldName: new PV; Cycle: 2;*) (*V04.12.00.00*)
		rPr_Ch_P2s_A : REAL; (*charge pressure p2' A [bar]*) (*OldName: ssPressP2s_A, rPressP2s_A; Cycle: 2;*) (*V04.03.00.00*)
		rPr_Ch_P2s_Avg : REAL; (*average charge pressure p2' [bar]*) (*OldName: new PV; Cycle: 2;*) (*V04.03.00.00*)
		rPr_Ch_P2s_Avg_UF : REAL; (*unfiltered average charge pressure p2' [bar]*) (*OldName: new PV; Cycle: 2;*) (*V04.03.00.00*)
		rPr_Ch_P2s_A_UF : REAL; (*unfiltered charge pressure p2' A [bar]*) (*OldName: new PV; Cycle: 2;*) (*V04.03.00.00*)
		rPr_Ch_P2s_B : REAL; (*charge pressure p2' B [bar]*) (*OldName: ssPressP2s_B, rPressP2s_B; Cycle: 2;*) (*V04.03.00.00*)
		rPr_Ch_P2s_B_UF : REAL; (*unfiltered charge pressure p2' B [bar]*) (*OldName: new PV; Cycle: 2;*) (*V04.03.00.00*)
		rPr_Ch_P2s_Max : REAL; (*maximum charge pressure p2' [bar]*) (*OldName: new PV; Cycle: 2;*) (*V04.12.00.00*)
		rPr_Ch_P2_Avg : REAL; (*average charge pressure p2 before throttle valve [bar]*) (*OldName: new PV; Cycle: 2;*) (*V04.07.00.00*)
		rPr_Ch_P2_Max : REAL; (*maximum charge pressure p2 before throttle valve [bar]*) (*OldName: new PV; Cycle: 2;*) (*V04.12.00.00*)
		rP_Red_Ch_T2HP_Norm : REAL; (*power reduction by charge temperatur T2 after high-pressure TC related to rP_Nom*) (*OldName:new PV;Cycle:2;*) (*V04.12.00.00*)
		rP_Red_Ch_T2LP_Norm : REAL; (*power reduction by charge temperatur T2 after low-pressure TC related to rP_Nom*) (*OldName:new PV;Cycle:2;*) (*V04.12.00.00*)
		rP_Red_Ch_T2s_Norm : REAL; (*power reduction by charge temperature T2'[%Pnom]*) (*OldName: ssPowerRedGemisch; Cycle: 2;*) (*V04.00.00.00*)
		rP_Red_TC_Norm : REAL; (*power reduction by turbocharger speed [%Pnom]*) (*OldName: ssPowerRedTurboSpd; Cycle: 5;*) (*V04.00.00.00*)
		rT_Ch_T1HP_Avg : REAL; (*average charge temperature before high-pressure turbocharger [°C]*) (*OldName: new PV; Cycle: 2;*) (*V04.07.00.00*)
		rT_Ch_T1LP_Avg : REAL; (*average charge temperature before low-pressure turbocharger (= engine intake air) [°C]*) (*OldName: new PV; Cycle: 2;*) (*V04.04.00.00*)
		rT_Ch_T2s_A : REAL; (*charge temperature t2' A [°C]*) (*OldName: ssCTAP_A, rCTAP_A; Cycle: 2;*) (*V04.03.00.00*)
		rT_Ch_T2s_Avg : REAL; (*average charge temperature t2' [°C]*) (*OldName: new PV; Cycle: 2;*) (*V04.03.00.00*)
		rT_Ch_T2s_Avg_UF : REAL; (*unfiltered average charge temperature t2' [°C]*) (*OldName: new PV; Cycle: 2;*) (*V04.03.00.00*)
		rT_Ch_T2s_B : REAL; (*charge temperature t2' B [°C]*) (*OldName: ssCTAP_B, rCTAP_B; Cycle: 2;*) (*V04.03.00.00*)
		rVol_Ch_Engine_Norm : REAL; (*normalized engine mixture volume flow [Nm³/h]*) (*OldName: new PV; Cycle: 5;*) (*V04.05.00.00*)
		tCH2AB : MM2AmmBase; (*AMM structure*) (*OldName: new PV; Cycle: 5;*) (*V04.00.00.00*)
		tCH2PB : MM2ParaBase_type; (*PARA structure*) (*OldName: new PV; Cycle: 5;*) (*V04.00.00.00*)
	END_STRUCT;
	PARA_CH_Struct : 	STRUCT 
		bCh_T2Calc_Active : BOOL; (*PARA [14936]: Charge temperature after turbocharger - Calculation active*) (*OldName: new PV; Cycle: 5;*) (*V04.12.00.00*)
		bDPr_AirFilt_A_Exist : BOOL; (*PARA [10120]: sensor difference pressure air inlet filter A exist*) (*OldName: dp_AirInFiltA_a; Cycle: 5;*) (*V04.00.00.00*)
		bDPr_AirFilt_B_Exist : BOOL; (*PARA [10121]: sensor difference pressure air inlet filter B exist*) (*OldName: dp_AirInFiltB_a; Cycle: 5;*) (*V04.00.00.00*)
		bDPr_AirFilt_Exist : BOOL; (*PARA [10122]: sensor difference pressure air inlet filter exist*) (*OldName: new PV; Cycle: 5;*) (*V04.00.00.00*)
		bDPr_AirFilt_PitotTube_Exist : BOOL; (*PARA [14335]: charge air filter difference pressure - measurement with pitot tube*) (*OldName: new PV; Cycle: 5;*) (*V04.07.00.00*)
		bN_TCHP_A_Exist : BOOL; (*PARA [10123]: speed measuring high-pressure turbocharger A exist*) (*OldName: bTurboSpdA_Act, bN_TCHP_A_Exist; Cycle: 5;*) (*V04.00.00.00*)
		bN_TCHP_B_Exist : BOOL; (*PARA [10124]: speed measuring high-pressure turbocharger B exist*) (*OldName: bTurboSpdB_Act, bN_TCHP_B_Exist; Cycle: 5;*) (*V04.00.00.00*)
		bN_TCHP_Exist : BOOL; (*PARA [10125]: speed measuring high-pressure turbocharger exist*) (*OldName: new PV; Cycle: 5;*) (*V04.00.00.00*)
		bN_TCLP_A_Exist : BOOL; (*PARA [10126]: speed measuring low-pressure turbocharger A exist*) (*OldName: bTurboSpd_LP_A_Act, bN_TCLP_A_Exist; Cycle: 5;*) (*V04.00.00.00*)
		bN_TCLP_B_Exist : BOOL; (*PARA [10127]: speed measuring low-pressure turbocharger B exist*) (*OldName: bTurboSpd_LP_B_Act, bN_TCLP_B_Exist; Cycle: 5;*) (*V04.00.00.00*)
		bN_TCLP_Exist : BOOL; (*PARA [10128]: speed measuring low-pressure turbocharger exist*) (*OldName: bN_TCLP_Exist; Cycle: 5;*) (*V04.00.00.00*)
		bPr_Ch_P1HP_A_Exist : BOOL; (*PARA [10129]: sensor charge pressure p1 before high-pressure TC A exist*) (*OldName: bPr_Ch_P1HP_A_Exist; Cycle: 2;*) (*V04.00.00.00*)
		bPr_Ch_P1HP_B_Exist : BOOL; (*PARA [10130]: sensor charge pressure p1 before  high-pressure TC B exist*) (*OldName: bPr_Ch_P1HP_B_Exist; Cycle: 2;*) (*V04.00.00.00*)
		bPr_Ch_P1HP_Exist : BOOL; (*PARA [10131]: sensor charge pressure p1 before high-pressure TC exist*) (*OldName: bPr_Ch_P1HP_Exist; Cycle: 2;*) (*V04.00.00.00*)
		bPr_Ch_P1LP_A_Exist : BOOL; (*PARA [13489]: sensor charge pressure p1 before  low-pressure TC A exist*) (*OldName: new PV; Cycle: 2;*) (*V04.04.00.00*)
		bPr_Ch_P1LP_B_Exist : BOOL; (*PARA [13490]: sensor charge pressure p1 before  low-pressure TC B exist*) (*OldName: new PV; Cycle: 2;*) (*V04.04.00.00*)
		bPr_Ch_P2bFA_Exist : BOOL; (*PARA [13478]: sensor charge pressure before flame arrester exist*) (*OldName: new PV; Cycle: 2;*) (*V04.04.00.00*)
		bPr_Ch_P2HP_A_Exist : BOOL; (*PARA [13828]: sensor charge pressure after high-pressure turbocharger A exist*) (*OldName: new PV; Cycle: 2;*) (*V04.04.00.00*)
		bPr_Ch_P2HP_B_Exist : BOOL; (*PARA [13829]: sensor charge pressure after high-pressure turbocharger B exist*) (*OldName: new PV; Cycle: 2;*) (*V04.04.00.00*)
		bPr_Ch_P2HP_Exist : BOOL; (*PARA [13481]: sensor charge pressure after high-pressure turbocharger exist*) (*OldName: new PV; Cycle: 2;*) (*V04.04.00.00*)
		bPr_Ch_P2LP_A_Exist : BOOL; (*PARA [13830]: sensor charge pressure after  low-pressure turbocharger A exist*) (*OldName: new PV; Cycle: 2;*) (*V04.04.00.00*)
		bPr_Ch_P2LP_B_Exist : BOOL; (*PARA [13831]: sensor charge pressure after  low-pressure turbocharger B exist*) (*OldName: new PV; Cycle: 2;*) (*V04.04.00.00*)
		bPr_Ch_P2LP_Exist : BOOL; (*PARA [13484]: sensor charge pressure after  low-pressure turbocharger exist*) (*OldName: new PV; Cycle: 2;*) (*V04.04.00.00*)
		bPr_Ch_P2s_A_Exist : BOOL; (*PARA [10135]: sensor charge pressure p2' A exist*) (*OldName: bPr_Ch_P2s_A_Exist; Cycle: 2;*) (*V04.00.00.00*)
		bPr_Ch_P2s_B_Exist : BOOL; (*PARA [10136]: sensor charge pressure p2' B exist*) (*OldName: bPr_Ch_P2s_B_Exist; Cycle: 2;*) (*V04.00.00.00*)
		bPr_Ch_P2s_Exist : BOOL; (*PARA [10137]: sensor charge pressure p2' exist*) (*OldName: bPr_Ch_P2_Exist; Cycle: 2;*) (*V04.00.00.00*)
		bPr_Ch_P2_A_Exist : BOOL; (*PARA [10132]: sensor charge pressure p2 A exist*) (*OldName: bPr_Ch_P2_A_Exist; Cycle: 2;*) (*V04.00.00.00*)
		bPr_Ch_P2_B_Exist : BOOL; (*PARA [10133]: sensor charge pressure p2 B exist*) (*OldName: bPr_Ch_P2_B_Exist; Cycle: 2;*) (*V04.00.00.00*)
		bPr_Ch_P2_Exist : BOOL; (*PARA [10134]: sensor charge pressure p2 exist*) (*OldName: bPr_Ch_P2_Exist; Cycle: 2;*) (*V04.00.00.00*)
		bTSTC_Exist : BOOL; (*PARA [10018]: Engine with two stage turbo charger is assembled*) (*OldName: b2StageTC; Cycle:5*) (*V04.05.04.00*)
		bT_Ch_T1HP_A_Exist : BOOL; (*PARA [10138]: sensor charge temperature t1 high-pressure before TC A exist*) (*OldName: t_CMbHPTC_A_a; Cycle: 2;*) (*V04.00.00.00*)
		bT_Ch_T1HP_B_Exist : BOOL; (*PARA [10139]: sensor charge temperature t1 high-pressure before TC B exist*) (*OldName: t_CMbHPTC_B_a; Cycle: 2;*) (*V04.00.00.00*)
		bT_Ch_T1HP_Exist : BOOL; (*PARA [10140]: sensor charge temperature t1 high-pressure before TC exist*) (*OldName: new PV; Cycle: 2;*) (*V04.00.00.00*)
		bT_Ch_T1LP_A_Exist : BOOL; (*PARA [13840]: sensor charge temperature before TC bank A (air intake) exist*) (*OldName: new PV; Cycle: 2;*) (*V04.04.00.00*)
		bT_Ch_T1LP_B_Exist : BOOL; (*PARA [13839]: sensor charge temperature before TC bank B (air intake) exist*) (*OldName: new PV; Cycle: 2;*) (*V04.04.00.00*)
		bT_Ch_T1LP_Exist : BOOL; (*PARA [13838]: sensor charge temperature before TC (air intake) exist*) (*OldName: bT_InAirER_Active; Cycle: 2;*) (*V04.04.00.00*)
		bT_Ch_T2HP_A_Exist : BOOL; (*PARA [14149]: sensor charge temperature t2 high-pressure after TC A exist*) (*OldName: new PV; Cycle: 2;*) (*V04.05.00.00*)
		bT_Ch_T2HP_B_Exist : BOOL; (*PARA [14150]: sensor charge temperature t2 high-pressure after TC B exist*) (*OldName: new PV; Cycle: 2;*) (*V04.05.00.00*)
		bT_Ch_T2HP_Exist : BOOL; (*PARA [14148]: sensor charge temperature t2 high-pressure after TC exist*) (*OldName: new PV; Cycle: 2;*) (*V04.05.00.00*)
		bT_Ch_T2LP_A_Exist : BOOL; (*PARA [14146]: sensor charge temperature after low-pressure TC bank A exist*) (*OldName: new PV; Cycle: 2;*) (*V04.05.00.00*)
		bT_Ch_T2LP_B_Exist : BOOL; (*PARA [14147]: sensor charge temperature after low-pressure TC bank B exist*) (*OldName: new PV; Cycle: 2;*) (*V04.05.00.00*)
		bT_Ch_T2LP_Exist : BOOL; (*PARA [14145]: sensor charge temperature after low-pressure TC exist*) (*OldName: new PV; Cycle: 2;*) (*V04.05.00.00*)
		bT_Ch_T2s_A_Exist : BOOL; (*PARA [10141]: sensor charge temperature t2' A exist*) (*OldName: new PV; Cycle: 2;*) (*V04.00.00.00*)
		bT_Ch_T2s_B_Exist : BOOL; (*PARA [10142]: sensor charge temperature t2' B exist*) (*OldName: new PV; Cycle: 2;*) (*V04.00.00.00*)
		bT_Ch_T2s_Exist : BOOL; (*PARA [10143]: sensor charge temperature t2' exist*) (*OldName: new PV; Cycle: 2;*) (*V04.00.00.00*)
		iEng_Motortype : INT; (*PARA [00000]: Motortype of the engine*) (*OldName: Motortype; Cycle: 5;*) (*V04.04.00.00*)
		rDPr_AirFilt_DynPress : REAL; (*PARA [14336]: charge air filter difference pressure - dynamic pressure at power nominal [mbar]*) (*OldName: new PV; Cycle: 5;*) (*V04.07.00.00*)
		rDPr_AirFilt_Hi : REAL; (*PARA [10144]: charge air inlet filter difference pressure - nominal load volume flow [bar]*) (*OldName: GW_dp_AirInFilt_hi; Cycle: 5;*) (*V04.00.00.00*)
		rDPr_AirFilt_Hi_incr : REAL; (*PARA [13495]: charge air inlet filter difference pressure - increase [bar]*) (*OldName: new PV; Cycle: 5;*) (*V04.04.00.00*)
		rDPr_AirFilt_Lo : REAL; (*PARA [13494]: charge air inlet filter difference pressure of new filter - nominal load volume flow [bar]*) (*OldName: new PV; Cycle: 5;*) (*V04.04.00.00*)
		rDPr_Ch_FA_Hi : REAL; (*PARA [13492]: difference pressure over charge flame arrester maximum - warning [bar] *) (*OldName: new PV; Cycle: 2;*) (*V04.04.00.00*)
		rDPr_Ch_HPCooler_Hi : REAL; (*PARA [13493]: difference pressure over high-pressure charge cooler maximum - warning [bar] *) (*OldName: new PV; Cycle: 2;*) (*V04.04.00.00*)
		rDPr_Ch_LPCooler_Hi : REAL; (*PARA [13491]: difference pressure over  low-pressure charge cooler maximum - warning [bar] *) (*OldName: new PV; Cycle: 2;*) (*V04.04.00.00*)
		rDPr_Ch_T2Calc_AirFilt : REAL; (*PARA [14941]: Difference pressure air filter [mbar]*) (*OldName: new PV; Cycle: 5;*) (*V04.12.00.00*)
		rDPr_Ch_T2Calc_HP_Cooler : REAL; (*PARA [14939]: Difference pressure intercooler [mbar]*) (*OldName: new PV; Cycle: 5;*) (*V04.12.00.00*)
		rDPr_Ch_T2Calc_LP_Cooler : REAL; (*PARA [14940]: Difference pressure intercooler - Low pressure [mbar]*) (*OldName: new PV; Cycle: 5;*) (*V04.12.00.00*)
		rN_EngStart_HyHi : REAL; (*PARA [11295]: speed engine start limit high hysteresis [rpm]*) (*OldName: HY_DREHZ; Cycle: 5;*) (*V04.00.00.00*)
		rN_EngStart_LimHi : REAL; (*PARA [11296]: speed engine start limit high [rpm]*) (*OldName: GW_DREHZ; Cycle: 5;*) (*V04.00.00.00*)
		rN_TCHP_Hi : REAL; (*PARA [10146]: Turbocharger HP speed maximum - trip [rpm]*) (*OldName: ssTurboSpdALim, rN_TCHP_Hi; Cycle: 5;*) (*V04.00.00.00*)
		rN_TCHP_HiHi : REAL; (*PARA [14359]: Turbocharger speed maximum - trip (at TC inlet temperature warning) [rpm]*) (*OldName: new PV; Cycle: 2;*) (*V04.07.00.00*)
		rN_TCHP_TempLimit_Hi : REAL; (*PARA [13857]: Turbocharger speed maximum - warning (at TC inlet temperature shut down) [rpm]*) (*OldName: new PV; Cycle: 2;*) (*V04.05.00.00*)
		rN_TCHP_TempLimit_HiHi : REAL; (*PARA [13933]: Turbocharger speed maximum - warning (at TC inlet temperature warning) [rpm]*) (*OldName: new PV; Cycle: 2;*) (*V04.05.00.00*)
		rN_TCLP_Hi : REAL; (*PARA [10147]: Turbocharger LP speed maximum - trip [rpm]*) (*OldName: ssTurboSpd_LP_Lim, rN_TCLP_Hi; Cycle: 5;*) (*V04.00.00.00*)
		rN_TCLP_HiHi : REAL; (*PARA [14360]: Low-pressure turbocharger speed maximum - trip (at TC inlet temperature warning) [rpm]*) (*OldName: new PV; Cycle: 2;*) (*V04.07.00.00*)
		rN_TCLP_TempLimit_Hi : REAL; (*PARA [14177]: Low-pressure turbocharger speed maximum - warning (at TC inlet temperature shut down) [rpm]*) (*OldName: new PV; Cycle: 2;*) (*V04.05.01.00*)
		rN_TCLP_TempLimit_HiHi : REAL; (*PARA [14176]: Low-pressure turbocharger speed maximum - warning (at TC inlet temperature warning) [rpm]*) (*OldName: new PV; Cycle: 2;*) (*V04.05.01.00*)
		rN_TC_Diff_Hi : REAL; (*PARA [10145]: TC speed deviation maximum  (Abweichung zwischen Bank A & B) [rpm]*) (*OldName: ssTurboIncLim, rN_TC_Diff_Hi; Cycle: 5;*) (*V04.00.00.00*)
		rPc_Ch_T2Calc_HP_Eff : REAL; (*PARA [14937]: Turbocharger efficiency [%]*) (*OldName: new PV; Cycle: 5;*) (*V04.12.00.00*)
		rPc_Ch_T2Calc_LP_Eff : REAL; (*PARA [14938]: Turbocharger efficiency - Low pressure [%]*) (*OldName: new PV; Cycle: 5;*) (*V04.12.00.00*)
		rPr_Ch_P2s_Diff_HiHi : REAL; (*PARA [10154]: charge pressure p2' deviation limit high alarm [bar]*) (*OldName: rPr_Ch_P2s_Diff_HiHi; Cycle: 2;*) (*V04.00.00.00*)
		rP_Red_Ch_T2s : ARRAY[0..4]OF REAL; (*PARA [10149]: value for power reduction by charge temperature t2' [%Pnom/°C]*) (*OldName: dp_gr; Cycle: 2;*) (*V04.00.00.00*)
		rP_Red_TC : REAL; (*PARA [10153]: value for power reduction by TC speed related to rP_Nom [%Pnom]*) (*OldName: ssTurboSpdRedPwr, rP_Red_TC; Cycle: 5;*) (*V04.00.00.00*)
		rP_Red_TC_reset : REAL; (*PARA [14178]: value for reset of power reduction by TC speed related to rP_Nom [%Pnom]*) (*OldName: new PV; Cycle: 2;*) (*V04.05.01.00*)
		rT_Ch_T1HP_Hi : REAL; (*PARA [10155]: Turbocharger speed maximum - TC inlet temperature warning [°C]*) (*OldName: GW_t_CMbHPTC_hi; Cycle: 2;*) (*V04.00.00.00*)
		rT_Ch_T1HP_HiHi : REAL; (*PARA [14358]: Turbocharger speed maximum - TC inlet temperature shut down [°C]*) (*OldName: new PV; Cycle: 2;*) (*V04.07.00.00*)
		rT_Ch_T1HP_Lo : REAL; (*PARA [10156]: charge temperature t1 HP before TC minimum [°C]*) (*OldName: GW_t_CMbHPTC_lo; Cycle: 2;*) (*V04.00.00.00*)
		rT_Ch_T1LP_Hi : REAL; (*PARA [13841]: Low-pressure turbocharger speed maximum - TC inlet temperature warning [°C]*) (*OldName: rT_InAirER_LimHi; Cycle: 2;*) (*V04.04.00.00*)
		rT_Ch_T1LP_HiHi : REAL; (*PARA [14179]: Low-pressure turbocharger speed maximum - TC inlet temperature shut down [°C]*) (*OldName: new PV; Cycle: 2;*) (*V04.05.01.00*)
		rT_Ch_T2HP_HiHi : REAL; (*PARA [14934]: Charge temperature after turbocharger maximum (intercooler limit) [°C]*) (*OldName: new PV; Cycle: 5;*) (*V04.12.00.00*)
		rT_Ch_T2LP_HiHi : REAL; (*PARA [14935]: Charge temperature after low-pressure turbocharger maximum (intercooler limit) [°C]*) (*OldName: new PV; Cycle: 5;*) (*V04.12.00.00*)
		rT_Ch_T2s_Diff_Hi : REAL; (*PARA [10157]: charge temperature t2' inclination maximum (Abweichung zw. Bank A und Bank B) [°C]*) (*OldName: ssGW_CATPI_MAX; Cycle: 2;*) (*V04.00.00.00*)
		rT_Ch_T2s_Hi : ARRAY[0..4]OF REAL; (*PARA [10158]: charge temperature t2' maximum [°C]*) (*OldName: gem_red; Cycle: 2;*) (*V04.00.00.00*)
		rT_Ch_T2s_HiHi : REAL; (*PARA [10162]: charge temperature t2' maximum [°C]*) (*OldName: GW_LLTP; Cycle: 2;*) (*V04.00.00.00*)
		rT_Ch_T2s_Lo : REAL; (*PARA [10163]: charge temperature t2' minimum warning [°C]*) (*OldName: GW_LLTP_low; Cycle: 2;*) (*V04.00.00.00*)
		rT_Ch_T2s_Roc_HiHi : REAL; (*PARA [10164]: charge temperature t2' rate of change maximum (Änderungsgeschwindigkeit) [°C/s]*) (*OldName: GW_DLLTP; Cycle: 2;*) (*V04.00.00.00*)
		ucLiefer : USINT; (*PARA [11289]: volumetric efficiency *) (*OldName: ucLiefer; Cycle: 5;*) (*V04.04.00.00*)
	END_STRUCT;
	PermAirF_typ : 	STRUCT 
		iCnt_OpHours_LastCalib : DINT; (*Perm: actual operating hours at time of calibration*) (*OldName: new PV; Cycle: 5;*) (*V04.04.00.00*)
		rP_Act_LastCalib : REAL; (*Perm: actual electric power at time of calibration [kW]*) (*OldName: new PV; Cycle: 5;*) (*V04.04.00.00*)
		rVol_Ch_AirFilt_Pnom : REAL; (*Perm: extrapolated value for operation volume flow at nominal power [m³/h]*) (*OldName: new PV; Cycle: 5;*) (*V04.04.00.00*)
	END_STRUCT;
END_TYPE
