(********************************************************************
 * COPYRIGHT -- INNIO Company
 ********************************************************************
 * Package: Opstate_Pkg
 * File: module_Opstate.typ
 * Author: Mario Graus
 * Created: October 19, 2011
 ********************************************************************
 * Data types 	of package Opstate_Pkg
 ********************************************************************)

TYPE
	PROGRAMMER_INFO : 	STRUCT 
		DO_NOT_SORT_PARA : STRING[40] := 'DO NOT CHANGE PARA SORTING!'; (*DO NOT CHANGE PARAMETER SORTING!*) (*ADD NEW PARAMETER ONLY AT THE END EOF THE Para STRUCTURE. DO NOT DELETE existing Para items.*)
		DO_NOT_SORT_PERM : STRING[40] := 'DO NOT CHANGE PERM SORTING OR LENGHT!'; (*DO NOT CHANGE PERM ITEM SORTING OR PERM LENGHT!*) (*ADD NEW ITEMS ONLY BY REPLACING SPARE ITEMS with same size! When no more spare items are available, you shoud generate a NEW INDEPENDENT PERM TYPE with independent new datamodule!*)
	END_STRUCT;
	OUT_Opstate_Struct : 	STRUCT 
		bEng_Aux_Dem_CDR : BOOL; (* FOR NOT CHANGING ALL OTHER MODULES, THIS EXISTS BESIDE HAL-OUT - engine auxiliaries demand with cool down run *) (*OldName:ANFHBT;Cycle:2;*)
		bIgn_Dem : BOOL; (* FOR NOT CHANGING ALL OTHER MODULES, THIS EXISTS BESIDE HAL-OUT - demand ignition *) (*OldName:ZUEND;Cycle:2;*)
		iSt_OpMode : UDINT; (* engine operation mode *) (*OldName:LeerlM,NetpM,InselM,StartM,StopM;Cycle:2;*)
		tOMSS_MAT : HALioDo_Type; (* operation mode selector switch - MANUAL AUTO TEST *) (*OldName:BWS_HA;Cycle:2;*)
		bEng_Aux_Dem_TOF : BOOL; (* engine auxiliaries demand TOF for cool down run *) (*OldName:T12;Cycle:2;*)
		tEng_Aux_Dem_CDR : HALioDo_Type; (* engine auxiliaries demand with cool down run *) (*OldName:ANFHBT;Cycle:2;*)
		tEng_Aux_Dem_CDR2 : HALioDo_Type; (* engine auxiliaries demand with cool down run *) (*OldName:ANFHBT;Cycle:2;*)
		tEng_Aux_Dem_CDR3 : HALioDo_Type; (* engine auxiliaries demand with cool down run *) (*OldName:ANFHBT;Cycle:2;*)
		bRel_Sync_Load : BOOL; (* release of synchronization and load *) (*OldName:SY_LFG;Cycle:2;*)
		tRel_Sync_Load : HALioDo_Type; (* DO: release of synchronization and load *) (*OldName:SY_LFG;Cycle:2;*)
		rN_Set_Norm : REAL; (* speed setpoint speed controller related to rN_EngNom *) (*OldName:n_soll;Cycle:2;*)
		tLSL_Out : HALioAo_Type; (* AO load sharing line *) (*OldName:LasttOut;Cycle:2;*)
		rP_Red_Norm : REAL; (* power reduction related to rP_Nom *) (*OldName:RedPowerProm;Cycle:2;*)
		iIdx_Pred_Type : INT; (* Index for type of power reduction *) (*OldName:gas_info;Cycle:2;*)
		bP_Red_Active : BOOL; (* power reduction active - any kind - Module Output and Visu *) (*OldName:PredAkt;Cycle:2;*)
		tP_Red_Active : HALioDo_Type; (* power reduction active - any kind - HALIO Output *) (*OldName:PredAkt;Cycle:2;*)
		rP_Set_Norm : REAL; (* power setpoint related to rP_Nom *) (*OldName:p_soll;Cycle:2;*)
		iIdx_OMSS : INT; (* inex of operation mode selector switch - 0..OFF, 1..MAN, 2..AUTO, 3..TEST, 4..SCAVENGING *) (*OldName:new PV;Cycle:2;*)
		iIdx_RSS : INT; (* inex of request selector switch - 0..OFF, 1..ON, 2..REMOTE *) (*OldName:new PV;Cycle:2;*)
		bP_Rmp_Frz : BOOL; (* freeze raising power ramp if control deviation of power exceeds 5% of nominal power *) (*OldName:bPowerRampFreeze;Cycle:2;*)
		bBlocDelay_ManStart : BOOL; (* blocking of next manual start by delay *) (*OldName:T26;Cycle:2;*)
		bEng_Dem_EPS : BOOL; (* demand emergency operation *) (*OldName:M_NANF;Cycle:2;*)
		bEng_Bloc : BOOL; (* blocking engine *) (*OldName:M_BLOCK;Cycle:2;*)
		bEng_Dem_Aut : BOOL; (* demand automatic mode *) (*OldName:M_ANF_A;Cycle:2;*)
		bEng_Dem_Man : BOOL; (* demand manual mode *) (*OldName:M_ANF_H;Cycle:2;*)
		bEng_Aux_Dem : BOOL; (* demand auxillaries *) (*OldName:M_ANFHBT;Cycle:2;*)
		bEng_Rel : BOOL; (* release engine *) (*OldName:M_FG_MOT;Cycle:2;*)
		bEng_SU_Man : BOOL; (* manual start *) (*OldName:M_HSTART;Cycle:2;*)
		bEng_Rel_SU : BOOL; (* engine starting *) (*OldName:M_MOST;Cycle:2;*)
		bEng_Rdy_Aut : BOOL; (* ready for automatic mode *) (*OldName:M_BERAUT;Cycle:2;*)
		bEng_Rdy_Man : BOOL; (* ready for manual mode *) (*OldName:M_STBT_H;Cycle:2;*)
		bEng_SUpE : BOOL; (* start up exitation *) (*OldName:M_USYLFG;Cycle:2;*)
		bEng_Dem : BOOL; (* demand engine *) (*OldName:M_AGFD;Cycle:2;*)
		bEng_RPSDem : BOOL; (* demand RPS *) (*OldName:M_AGRPS;Cycle:2;*)
		tEng_Run : HALioDo_Type; (* engine running *) (*OldName:BTRB,M_BTRB;Cycle:2;*)
		bEng_SU_Aut : BOOL; (* automatic start up *) (*OldName:M7_6;Cycle:2;*)
		bEng_RSBoc : BOOL; (* restart blocking *) (*OldName:STR_BLO;Cycle:2;*)
		bEng_CDR : BOOL; (* cool down run *) (*OldName:T10;Cycle:2;*)
		bEng_Stop_Man : BOOL; (* manual stop *) (*OldName:M_STOP;Cycle:2;*)
		bEng_Dem_Bloc : BOOL; (* blocking release of engine *) (*OldName:ANFBLO;Cycle:2;*)
		tIgn_Dem : HALioDo_Type; (* demand ignition *) (*OldName:ZUEND;Cycle:2;*)
		bEng_Dem_Aut_SUpF : BOOL; (* demand automatic for start up failure *) (*OldName:BRI;Cycle:2;*)
		bEng_MonOff : BOOL; (* engine monitoring off *) (*OldName:T9;Cycle:2;*)
		bGV_Rel : BOOL; (* release gas valves *) (*OldName:ZUEND_WEG;Cycle:2;*)
		bEng_Rdy_Aut_Exc : BOOL; (* engine ready for automatic operation information for the excitation system *) (*OldName:BERAUT;Cycle:2;*)
		tEng_Rdy_Rem : HALioDo_Type; (* Ready for Remote Operation *) (*OldName:BERZLT;Cycle:2;*)
		bGasTyp1_Act : BOOL; (* gas type 1 active *) (*OldName:AN_GAS1;Cycle:2;*)
		bGasTyp2_Act : BOOL; (* gas type 2 active *) (*OldName:AN_GAS2;Cycle:2;*)
		bGasTyp3_Act : BOOL; (* gas type 3 active *) (*OldName:AN_GAS3;Cycle:2;*)
		bGasTyp4_Act : BOOL; (* gas type 4 active *) (*OldName:AN_GAS4;Cycle:2;*)
		bGasTypMix1_2_Act : BOOL; (* gas type mix 1-2 active *) (*OldName:AN_GAS1_2;Cycle:2;*)
		bGV_Open_Opstate : BOOL; (* gas valve open - from opstate module *) (*OldName:ZM_GASV;Cycle:2;*)
		tP_Red_Norm : HALioAo_Type; (* power reduction *) (*OldName:RedPowerProm;Cycle:2;*)
		rP_Nom : REAL; (* nominal electric power [KW], depends on gastype *) (*OldName:PN_GASART;Cycle:2;*)
		rP_Act_Norm : REAL; (* actual power related to rP_nom *) (*OldName:new PV;Cycle:2;*)
		rP_Act_Norm_Filt : REAL; (* actual power related to rP_nom filtered T=1s *) (*OldName:P_IST_PROM;Cycle:2;*)
		rP_Set : REAL; (* power setpoint value [KW] *) (*OldName:p_soll;Cycle:2;*)
		bImp_UnitOpHour : BOOL; (* impulse for unit operation hour counter *)
		tImp_OpHour : HALioDo_Type; (* impulse for engine operation hour counter *) (*OldName:M_BTRIMP,H_IMP;Cycle:2;*)
		bImp_Start : BOOL; (* impulse for start counter *) (*OldName:T25,M_STRTIMP;Cycle:2;*)
		bEng_Dem_Man_SUpF : BOOL; (* demand manual for start up failure *) (*OldName:BRI_H;Cycle:2;*)
		iCnt_Starts : DINT; (* start counter *) (*OldName:start_z;Cycle:2;*)
		iCnt_UnitOpHours : DINT; (* unit operating hours counter *)
		iCnt_OpHours : DINT; (* engine operating hours counter *) (*OldName:betrieb_h;Cycle:2;*)
		bMsg1108 : BOOL; (* actual power deviation maximum *) (*OldName:M_PDIFF;Cycle:2;*)
		iIdx_Pset_Type : INT; (* power setpoint type *) (*OldName:usPowerSetpTyp;Cycle:5;*)
		bP_Ramp_Target_Reached : BOOL; (* ramp of power set value has reached the target value *) (*OldName:new PV;Cycle:2;*)
		rP_Set_Unred_Norm : REAL; (* normed power set value without reductions *) (*OldName:P_UNRED;Cycle:5;*)
		tOP2AB : MM2AmmBase;
		tOP2PB : MM2ParaBase_type;
		rP_Ramp_IncGrad_All_Norm : REAL; (*gradient for increase of power ramp in grid mode [1/s]*) (*OldName:t_upALL; Cycle:2;*)
		rP_Set_GEN2_Norm : REAL; (* power setpoint for GEN2 *) (*OldName:ssSetpointPowerkW_BDC; Cycle:2;*)
		tP_LimitSon_Gh : ARRAY[0..4]OF HALioDo_Type; (*Loadstep feedback*) (* Oldname: new PV; Cycle: 2 *)
		tP_max_LSL : HALioAo_Type; (* power reduction *) (*OldName:RedPowerProm;Cycle:2;*)
		rP_Ramp_DecGrad_All_Norm : REAL; (*gradient for decrease of power ramp in grid mode [1/s]*)
		rP_Set_Unred_Norm_ohne_FC : REAL; (* normed power set value without reductions AND without (P)FC *)
		bStop : BOOL; (*WinMOD*) (*OldName:; Cycle:5;*)
		bStart : BOOL; (*WinMOD*) (*OldName:; Cycle:5;*)
		bGEN2_UseFastRamp : BOOL; (*Force GEN2 to a faster decreasing Ramp*)
		bFastPowRed : BOOL; (* fast power reduction, due knock or glowign *) (*OldName:newPV; Cycle:2;*)
		tP_Red_EU_Norm : HALioAo_Type; (* Power reduction from EU (feedback) *)
		tP_Avail_Norm : HALioAo_Type; (* Available power *)
		tExecute_BS : HALioDo_Type; (* Execute black out start *)
		rP_set_vis_Norm : REAL; (* setpoint value for power from visu [%Pnom] *)
		rP_Ramp_IncGrad_Norm : REAL; (*gradient for increase of power ramp in grid mode denpending on gastype [1/s]*)
		rP_Ramp_DecGrad_Norm : REAL; (*gradient for decrease of power ramp in grid mode denpending on gastype [1/s]*)
		rP_Act_Norm_Filt_LS : REAL; (* actual power related to rP_nom filtered T=cust for load sharing *)
		iCnt_FastStarts : DINT; (* fast start counter *)
		rP_set_myPlant_Norm : REAL; (* setpoint value from myPlant [%Pnom] *)
		iIdx_Eng_State : INT; (* state of engine *)
		rP_Set_Min_Norm : REAL; (*minimum power setpoint p.u.*)
	END_STRUCT;
	IN_Opstate_Struct : 	STRUCT 
		iCnt_OpHours_Set : DINT; (*new V4.13 for ParaBase Counter Set*)
		iCnt_UnitOpHours_Set : DINT; (*new V4.13 for ParaBase Counter Set*)
		iCnt_Starts_Set : DINT; (*new V4.13 for ParaBase Counter Set*)
		iCnt_FastStarts_Set : DINT; (*new V4.13 for ParaBase Counter Set*)
		rP_Set_Ctr_Mns_Norm : REAL; (*! new V4.5 2017 !  (Mains Power Controller)*)
		bP_Set_Ctr_Mns_Enable : BOOL; (*! new V4.5 2017 !  (Mains Power Controller)*)
		tDI_Dem_EU_Block : HALioDi_Type; (*external request from utility (evu). power reduction *) (*OldName: DI_EVU; Cycle: 5;*)
		bGV_On : BOOL; (*Gas valves On*) (*OldName:M_GASV;Cycle:2;*)
		bEng_Start : BOOL; (*engine start*) (*OldName:M_STRT;Cycle:2;*)
		bLeanox_Man : BOOL; (*TRUE = leanox controller in manual*) (*OldName:l_einst_a;Cycle:2;*)
		bLeanox_Active : BOOL; (* TRUE = leanox controller is active *) (* OldName: bLeanoxActive; Cycle:2; *)
		tEng_SUExc_Rel : HALioDi_Type; (*start-up excitation release*) (*OldName:U_SY_LFG;Cycle:2;*)
		tMCB_On : HALioDi_Type; (*mains circuit breaker closed*) (*OldName:MCB_ON;Cycle:2;*)
		tMnsOk : HALioDi_Type; (*DI mains ok*) (*OldName:DI_MNS_OK;Cycle:2;*)
		bReq_PowMod : BOOL; (*request power operation mode - overwritten in Customization*) (*OldName:DI_DMND_PM;Cycle:2;*)
		tReq_PowMod : HALioDi_Type; (*request power operation mode*) (*OldName:DI_DMND_PM;Cycle:2;*)
		rN_EngAct : REAL; (*Engine Speed (1/min)*) (*OldName:ZDGSpeed;Cycle:2;*)
		tGCB_On : HALioDi_Type; (*generator circuit breaker closed*) (*OldName:GCB_ON;Cycle:2;*)
		bMCB_DemSy : BOOL; (*mains circuit breaker demand synchronization*) (*OldName:ARSYANW;Cycle:5;*)
		bGCB_DemSy : BOOL; (*generator circuit breaker demand synchronization*) (*OldName:ASYANW;Cycle:5;*)
		tReq_PeakLoad : HALioDi_Type; (*request peak load*) (*OldName:ANF_SP;Cycle:2;*)
		bBB_dead : BOOL; (*bus bar dead*) (*OldName:SS_OSP;Cycle:5;*)
		bJmpPLTime : BOOL; (*jump prelubrication time in case of emergency power supply*) (*OldName:UB_VORS;Cycle:5;*)
		bRelEngOp_Aux : BOOL; (*release engine operation from auxiliaries with dropout delay*) (*OldName:T6;Cycle:5;*)
		bDemScavVa : BOOL; (*demand scavenging valve*) (*OldName:ANF_SPKL;Cycle:5;*)
		bMsg1031 : BOOL; (*safety loop*) (*OldName:M_SIS;Cycle:5;*)
		bT_ECW_RelLoad : BOOL; (*temperature engine cooling water release load*) (*OldName:AN_LFG;Cycle:5;*)
		bT_ECW_Hi : BOOL; (*temperature engine cooling water limit high*) (*OldName:AN_KTMA;Cycle:5;*)
		tReq_Test : HALioDi_Type; (*request test mode*) (*OldName:ANF_LP;Cycle:2;*)
		bMsg1218 : BOOL; (*generator circuit breaker opening failure*) (*OldName:S_AUS_GS;Cycle:5;*)
		bSynchDem : BOOL; (*synchronization demanded*) (*OldName:SynchAnf;Cycle:5;*)
		bDSyLine : BOOL; (*demand synchline*) (*OldName:M_SYL;Cycle:5;*)
		tLSL_In : HALioAi_Type; (*AI load sharing line*) (*OldName:LasttIn;Cycle:2;*)
		rP_Red_Knck_Norm : REAL; (*power reduction by knocking related to rP_Nom*) (*OldName:new PV;Cycle:2;*)
		rP_Red_Knck_Norm_TC2 : REAL; (*power reduction by knocking related to rP_Nom to Task Class 2*) (*OldName:new PV;Cycle:2;*)
		rP_Red_Ch_T2s_Norm : REAL; (*power reduction by charge temperatur T2' related to rP_Nom*) (*OldName:new PV;Cycle:2;*)
		rP_Red_Ch_T2s_Norm_TC5 : REAL; (*power reduction by charge temperatur T2' related to rP_Nom*) (*OldName:new PV;Cycle:2;*)
		rP_Red_Misf_Norm : REAL; (*power reduction by misfire related to rP_Nom*) (*OldName:new PV;Cycle:2;*)
		rP_Red_EGT_Norm : REAL; (*power reduction by exhaust gas temp. related to rP_Nom*) (*OldName:new PV;Cycle:2;*)
		rP_Red_T_InAirER_Norm : REAL; (*power reduction by engine room inlet air temperature related to rP_Nom*) (*OldName:new PV;Cycle:5;*)
		rP_Red_Leanox_Norm : REAL; (*power reduction by leanox related to rP_Nom*) (*OldName:new PV;Cycle:2;*)
		rP_Red_CH4_Norm : REAL; (*power reduction due to CH4 low related to rP_Nom*) (*OldName:new PV;Cycle:2;*)
		rP_Red_GasPr_Norm : REAL; (*power reduction due to gas pressure low related to rP_Nom*) (*OldName:new PV;Cycle:2;*)
		rP_Red_SuctPr_Norm : REAL; (*power reduction due to suction pressure high related to rP_Nom*) (*OldName:new PV;Cycle:2;*)
		rP_Red_TC_Norm : REAL; (*power reduction by turbo charger speed related to rP_Nom*) (*OldName:new PV;Cycle:5;*)
		rP_Red_T_HWR_Norm : REAL; (*power reduction heat water return temperature high related to rP_Nom*) (*OldName:new PV;Cycle:5;*)
		rP_Red_T_ECW_Norm : REAL; (*power reduction engine cooling water temperature high related to rP_Nom*) (*OldName:new PV;Cycle:5;*)
		rP_Red_T_Oil_Norm : REAL; (*power reduction by oil temp. max related to rP_Nom*) (*OldName:new PV;Cycle:5;*)
		rP_Red_Ch_T2HP_Norm : REAL; (*power reduction by charge temperatur T2 after high-pressure TC related to rP_Nom*) (*OldName:new PV;Cycle:2;*)
		rP_Red_Ch_T2LP_Norm : REAL; (*power reduction by charge temperatur T2 after low-pressure TC related to rP_Nom*) (*OldName:new PV;Cycle:2;*)
		rP_Red_Pr_PCGT_Norm : REAL; (*power redutcion by pre chamber gas pressure related to rP_Nom*) (*OldName:new PV;Cycle:2;*)
		rP_Red_CosPCtr_U_Norm : REAL; (*power reduction by generator voltage related to rP_Nom*) (*OldName:new PV;Cycle:2;*)
		rP_Red_CosPCtr_F_Norm : REAL; (*power reduction by generator frequency related to rP_Nom*) (*OldName:new PV;Cycle:2;*)
		rP_Red_CosPCtr_T_Norm : REAL; (*power reduction by generator winding temperature related to rP_Nom*) (*OldName:new PV;Cycle:2;*)
		tF_N_DI_Inc : HALioDi_Type; (* synch. digital in increase speed *) (*OldName:SynchNH;Cycle:2;*)
		tF_N_DI_Dec : HALioDi_Type; (* synch. digital in decrease speed *) (*OldName:SynchNL;Cycle:2;*)
		tF_MMD_Synch1 : ARRAY[0..2]OF HALioAi_Type; (* *) (*OldName:usSynch1Frequency;Cycle:2;*)
		tF_MMD_Synch2 : ARRAY[0..2]OF HALioAi_Type; (* *) (*OldName:usSynch2Frequency;Cycle:2;*)
		bP_Set_ExtAI_Enable : BOOL; (* enable external power setpoint via analog input *) (*OldName:AW_EXPSH_AI;Cycle:5;*)
		rP_Set_ExtAI_Norm : REAL; (* external power setpoint via analog input related to rP_Nom *) (*OldName:ssNominalPowerAnalog;Cycle:5;*)
		rP_Set_Dem_Ctr_Mns_Norm : REAL; (*! new V4.5 2017 !  (Prepared)*)
		bP_Set_Dem_Ctr_Mns_Enable : BOOL; (*! new V4.5 2017 ! *)
		bP_Set_ExtDI_Cust_Enable : BOOL; (* enable external power setpoint via digital input *) (*OldName:AW_EXPSH_DI;Cycle:5;*)
		bP_Set_ExtDI_Enable : BOOL; (* enable external power setpoint via digital input *) (*OldName:AW_EXPSH_DI;Cycle:5;*)
		rP_Set_ExtDI_Norm : REAL; (*OUTDATED INTERFACE! DO NOT USE ANYMORE, stated for backwarda compatibility only*) (*OldName:Dig_P_SOLL;Cycle:5;*)
		rP_Set_ExtDI_Cust_Norm : REAL; (*external power setpoint via digital input  (replacement for  rP_Set_ExtDI_Norm)*) (*OldName:Dig_P_SOLL;Cycle:5;*)
		bP_Set_ExtBus_Enable : BOOL; (* enable external power setpoint via bus *) (*OldName:AW_EXPSB;Cycle:5;*)
		rP_Set_ExtBus_Norm : REAL; (* external power setpoint via bus related to rP_Nom *) (*OldName:B_P_SOLL;Cycle:5;*)
		bN_Set_ExtAI_Enable : BOOL; (* enable external speed setpoint via analog input *) (*OldName:AW_EXDSH;Cycle:5;*)
		rN_Set_ExtAI_Norm : REAL; (* external speed setpoint via analog input related to rN_EngNom *) (*OldName:Dig_N_SOLL;Cycle:5;*)
		bN_Set_ExtBus_Enable : BOOL; (* enable external speed setpoint via bus *) (*OldName:AW_EXDSB;Cycle:5;*)
		rN_Set_ExtBus_Norm : REAL; (* external speed setpoint via bus related to rN_EngNom *) (*OldName:B_N_SOLL;Cycle:5;*)
		bP_Red_Sp_Lim1Act : BOOL; (* power setpoint limit 1 activ *) (*OldName:bPowerSetpointLimit1;Cycle:5;*)
		bP_Red_Sp_Lim2Act : BOOL; (* power setpoint limit 2 activ *) (*OldName:bPowerSetpointLimit2;Cycle:5;*)
		bP_Red_Sp_Lim3Act : BOOL; (* power setpoint limit 3 activ *) (*OldName:bPowerSetpointLimit3;Cycle:5;*)
		rP_Red_Sp_Lim1_Norm : REAL; (* power setpoint limit 1  related to rP_Nom *) (*OldName:ssPowerSetpointLimit1;Cycle:5;*)
		rP_Red_Sp_Lim2_Norm : REAL; (* power setpoint limit 2  related to rP_Nom *) (*OldName:ssPowerSetpointLimit2;Cycle:5;*)
		rP_Red_Sp_Lim3_Norm : REAL; (* power setpoint limit 3  related to rP_Nom *) (*OldName:ssPowerSetpointLimit3;Cycle:5;*)
		bP_Red_CosPCtr_U_Hi : BOOL; (* power reduction by generator voltage high active *) (*OldName:bPowRedGenSpgH;Cycle:2;*)
		bP_Red_CosPCtr_U_Lo : BOOL; (* power reduction by generator voltage low active *) (*OldName:bPowRedGenSpgL;Cycle:2;*)
		bP_Red_CosPCtr_F_Hi : BOOL; (* power reduction by generator frequency high active *) (*OldName:bPowRedGenFrqH;Cycle:2;*)
		bP_Red_CosPCtr_F_Lo : BOOL; (* power reduction by generator frequency low active *) (*OldName:bPowRedGenFrqL;Cycle:2;*)
		rP_Red_EVU_Norm : REAL; (* power redutcion by utility related to rN_EngNom*) (*OldName:new PV;Cycle:5;*)
		rP_Red_AI_Norm : REAL; (* power reduction by analog input related to rN_EngNom*) (*OldName:new PV;Cycle:5;*)
		rP_Red_ExtBus_Norm : REAL; (* power redutcion by primary control related to rN_EngNom*) (*OldName:new PV;Cycle:2;*)
		rPos_CBV : REAL; (*compressor bypass valve position*) (*OldName:turbo_y;Cycle:2;*)
		bPurgeER_Rdy : BOOL; (* purge cycle ready *) (*OldName:purge_rdy;Cycle:5;*)
		bScavFinished : BOOL; (* scavenging cycle finished  *) (*OldName:SPUEL_AB;Cycle:5;*)
		tRel_ER_PurgeCycle : HALioDi_Type; (* DI release from engine room purge cycle  *) (*OldName:DI_Rel_PurgeC;Cycle:2;*)
		bRel_ScavN2 : BOOL; (* conditions for scavenge with N2 *) (*OldName:FG_N2;Cycle:5;*)
		bN2_ScavCoStarterOn : BOOL; (* N2 scavening command starter ON *) (*OldName:STARTER_SC;Cycle:5;*)
		b_ST_DemIgn : BOOL; (* Demand starter from ignition *) (*OldName:STARTER_IgnST;Cycle:5;*)
		bIgn_Run : BOOL; (* Ignition in Operation *) (*OldName:ZIB;Cycle:5;*)
		tScavVaClosed : HALioDi_Type; (* scavenging valve closed *) (*OldName:SPK_ZU;Cycle:2;*)
		tN2_GV2_Closed : HALioDi_Type; (* N2 gas valve 2 closed status *) (*OldName:N2V2_ZU;Cycle:2;*)
		tN2_GV1_Closed : HALioDi_Type; (* N2 gas valve 1 closed status *) (*OldName:N2V1_ZU;Cycle:2;*)
		tEng_Dem_EPS_Ext : HALioDi_Type; (* engine demand emergency power supply from external *) (*OldName:N_ANF;Cycle:2;*)
		bEng_Dem_EPS_Sy : BOOL; (* engine demand emergency power supply from synchronization *) (*OldName:ANF_NSB;Cycle:5;*)
		bPr_N2_LoTon : BOOL; (*pressure N2 low with TON*) (*OldName:ZM_GDMI_N2;Cycle:5;*)
		bRel_IgnOn : BOOL; (*release ignition ON*) (*OldName:AT5;Cycle:5;*)
		bOnly_Island : BOOL; (*only island operation*) (*OldName:REIN_INSEL;Cycle:5;*)
		bOtherGenParallel : BOOL; (*other generator parallel*) (*OldName:PARALLEL;Cycle:5;*)
		bRelEngOpFromSy : BOOL; (*release engine operation from synchronization*) (*OldName:M_FBLO;Cycle:5;*)
		tDemEngOpExt : HALioDi_Type; (*external demand of engine operation*) (*OldName:ANF;Cycle:2;*)
		bMaxPreLubeTime : BOOL; (*maximum engine prelubrication time*) (*OldName:T86;Cycle:5;*)
		bSmoothDischarge : BOOL; (*smooth engine discharge*) (*OldName:SANFT;Cycle:5;*)
		bMsg1022 : BOOL; (*overspeed relais*) (*OldName:M_UEDZ;Cycle:5;*)
		bMsg1026 : BOOL; (*shut down failure*) (*OldName:M_ANSTAB;Cycle:5;*)
		bIgnDeflPrct_Off : BOOL; (*Deflagration protection Ignition, 200ms delay*) (*OldName:ZUEND_PUFF;Cycle:2;*)
		bN_EngStartDrop : BOOL; (*Engine start-up speed drop down*) (*OldName:M_STRDRE;Cycle:2;*)
		tSelGasTyp : HALioDi_Type; (* DI: Selection gastype - general *) (*OldName:AW_GASART;Cycle:2;*)
		tSelGasTyp2 : HALioDi_Type; (* DI: Selection gastype 2 *) (*OldName:GAS_2;Cycle:2;*)
		tSelGasTyp3 : HALioDi_Type; (* DI: Selection gastype 3 *) (*OldName:GAS_3;Cycle:2;*)
		tSelGasTyp4 : HALioDi_Type; (* DI: Selection gastype 4 *) (*OldName:GAS_4;Cycle:2;*)
		bGT_Ipol12Active : BOOL; (*Interpolation gas1 & 2 active from CH4(or CV)*) (*OldName:GAS1_2;Cycle:2;*)
		bGT_TypSwhActive : BOOL; (*Gas type switching active*) (*OldName:GASUM;Cycle:2;*)
		bGT_TypSwhActiveHalt : BOOL; (*Gas type switching active, engine standstill*) (*OldName:GASUM_ST;Cycle:2;*)
		bSelGasTypAut : BOOL; (*Selection of automatic gas type switching*) (*OldName:AUTGAS;Cycle:2;*)
		bSelGasTyp0 : BOOL; (*Selection of gas type 0*) (*OldName:GAS1_2MAN;Cycle:2;*)
		bSelGasTyp1 : BOOL; (*Selection of gas type 1*) (*OldName:GAS1;Cycle:2;*)
		bSelGasTyp2 : BOOL; (*Selection of gas type 2*) (*OldName:GAS2;Cycle:2;*)
		bSelGasTyp3 : BOOL; (*Selection of gas type 3*) (*OldName:GAS3;Cycle:2;*)
		bSelGasTyp4 : BOOL; (*Selection of gas type 4*) (*OldName:GAS4;Cycle:2;*)
		bGT_SelGas1 : BOOL; (*Selection gas 1*) (*OldName:M_AWGAS1;Cycle:2;*)
		bGT_SelGas2 : BOOL; (*Selection gas 2*) (*OldName:M_AWGAS2;Cycle:2;*)
		bGT_SelGas3 : BOOL; (*Selection gas 3*) (*OldName:M_AWGAS3;Cycle:2;*)
		bGT_SelGas4 : BOOL; (*Selection gas 4*) (*OldName:M_AWGAS4;Cycle:2;*)
		bGT_DemRelGasTypSwh : BOOL; (*Demand release for gas type switching*) (*OldName:ANF_ENTL;Cycle:2;*)
		bGT2_Select : BOOL; (*Selection gas train 2*) (*OldName:ANW_GST2;Cycle:2;*)
		bMsg3583 : BOOL; (*Warning: cylinder exhaust gas temperature absolute value high*) (*OldName:ATMA_W;Cycle:2;*)
		bMsg3584 : BOOL; (*Warning: Cylinder exhaust gas temperature deviation from average value*) (*OldName:ABMW_W;Cycle:2;*)
		bGasSupplyOk : BOOL; (* Gas Supply OK *) (*OldName:GAS_OK;Cycle:2;*)
		tGV_Rel : HALioDo_Type; (* DO: Release gas valves *) (*OldName:FG_GASV;Cycle:2;*)
		bMainsReturn : BOOL; (* mains return *) (*OldName:NWK;Cycle:5;*)
		tRel_MasCtr : HALioDi_Type; (* release from master control *) (*OldName:FRG;Cycle:2;*)
		bRel_Island : BOOL; (* release island operation *) (*OldName:FG_INSEL;Cycle:5;*)
		bRel_IslandAfMITime : BOOL; (* jump release island op.after mi-filter time *) (*OldName:T79;Cycle:5;*)
		bIgn2_Sel : BOOL; (* TRUE = Double Ignition Selected *) (*OldName:IIXZUEND;Cycle:2;*)
		bEngDSS_Mains : BOOL; (*activate task for engine demand from mains power control*) (*OldName:ANF_NB;Cycle:2;*)
		bT_EOP_RelLoad : BOOL; (*oil temperature release load*) (*OldName:OT_LFG;Cycle:5;*)
		bEGScav_Rdy : BOOL; (*exhaust gas scavenging ready*) (*OldName:T_VERZ_ANF;Cycle:5;*)
		bBus_Dem : BOOL; (*demand fieldbus*) (*OldName:BUS_ANF;Cycle:5;*)
		bDeflagrationPrct : BOOL; (*deflagration protection*) (*OldName:PUFF;Cycle:2;*)
		bTestBenchModeIsland : BOOL; (*test bench mode - island mode*) (*OldName:PRF_I;Cycle:5;*)
		tEVU_PowerSet3Dem : HALioDi_Type; (*demand module blocked by utility*) (*OldName:DI_EVU_3;Cycle:2;*)
		tT_ECW : HALioAi_Type; (* cooling water temperature *) (*OldName:ANA.KWT;Cycle:2;*)
		tP_Act : ARRAY[0..2]OF HALioAi_Type; (* actual electric power [KW] *) (*OldName:ssPAct;Cycle:2;*)
		iIdx_Gtyp_Dem : INT; (* actual gassort 1..4 *) (*OldName:gasart;Cycle:5;*)
		tAB2OP : AmmBase2MM;
		tPB2MM : ParaBase2MM_type;
		rP_Red_Hum_Norm : REAL; (*power redutcion by humidity related to rP_Nom*) (*OldName:new PV;Cycle:2;*)
		rP_Red_PBC_Norm : REAL; (*power redutcion by PBC related to rP_Nom*) (*OldName:new PV;Cycle:2;*)
		bEng_Block_Customized : BOOL; (*  = 	BLOCK_NB	-	Engine shutdown by customized module *)
		bEng_Block_EVU : BOOL; (* = 	BLOCK_EVU Engine shutdown by external utility(evu)demand *)
		bP_Set_EU_Enable : BOOL; (* power setpoint OF EU active *) (*OldName:bPset_EVU_aktiv;Cycle:5;*)
		rP_Set_EU_Norm : REAL; (* setpoint power EU *) (*OldName:ssSetpointPowerkW_EVU;Cycle:5;*)
		bP_Set_PFC_Enable : BOOL; (* power setpoint PFC aktiv *) (*OldName:new PV;Cycle:5;*)
		rP_Set_PFC_Norm : REAL; (* power setpoint PFC *) (*OldName:ssOffsetPowerkW_PFC;Cycle:5;*)
		bP_Red_EU_Enable : BOOL; (* Power reduction EU (AI or BUS) aktiv *) (*OldName:new PV;Cycle:5;*)
		rP_Red_EU_Norm : REAL; (* Power reduction EU (AI or BUS) *) (*OldName:ssPowRed_EVU_HWBUS;Cycle:5;*)
		bP_Red_PFC_Enable : BOOL; (* PFC aktiv *) (*OldName:bPFC_aktiv;Cycle:5;*)
		rP_Red_PFC_Norm : REAL; (* PFC Absolute Power Limitation *) (*OldName:ssLimitPowerPFC_PROM;Cycle:5;*)
		bP_Red_RMC_Enable : BOOL; (* RMC aktiv *) (*OldName:bRMC_aktiv;Cycle:5;*)
		rP_Red_RMC_Norm : REAL; (* power limitation RMC *) (*OldName:ssSetpointPowerkW_RMC;Cycle:5;*)
		rP_Ramp_IncGrad_GR_Norm : REAL; (* gradient for increase OF power ramp from grid modul *) (*OldName:new PV;Cycle:5;*)
		rP_Ramp_DecGrad_GR_Norm : REAL; (* gradient for decrease OF power ramp from grid modul *) (*OldName:new PV;Cycle:5;*)
		bP_Ramp_IncGrad_GR_Enable : BOOL; (* enable gradient for increase OF power ramp from grid modul *) (*OldName:new PV;Cycle:5;*)
		bP_Ramp_DecGrad_GR_Enable : BOOL; (* enable gradient for decrease OF power ramp from grid modul *) (*OldName:new PV;Cycle:5;*)
		bGV_Start_ScaveBlock : BOOL; (*block gas valves from startup procedure*)
		rP_Red_Knck_Opti_Norm : REAL; (* power redutcion by  timing point optimizing related to rP_Nom  *) (* OldName: klreg_opti_dp; Cycle:2; *)
		tCustDigIn : ARRAY[0..200]OF HALioDi_Type; (*new, reserved for Project specific use*) (*OldName: new PV	; Cycle: 5;*)
		iIdx_SyOMSS : INT; (* synchronization operating mode selection *) (*OldName:new PV;Cycle:5;*)
		bSelfTestRunning : BOOL;
		rGT_QualMix_1_2 : REAL; (*Mixture ratio bet. gas 1 and 2 [%], e.g. value 0.75 =75%*) (* OldName: 	ssMisch1_2	; Cycle: ; *)
		rGT_RatioMix : REAL; (*Gas mixture rate after ramp fub [%], e.g. 0.5 = 50%*) (* OldName: 	ssRatioMix	; Cycle:2; *)
		bGasMixingActive : BOOL; (*TRUE = Gas mixing is active for TecJet's *) (* OldName: 	bCrossOver	; Cycle: ; *)
		rP_Red_HiCtr_Norm : REAL; (* power reduction by hierarchic controller *) (*OldName:new PV;Cycle:5;*)
		tCustAnaIn : ARRAY[0..120]OF HALioAi_Type; (*Replacement for RAN_KANAL...*) (*OldName: ANA_RAN	; Cycle: 5;*)
		rP_RedDI_EU_Norm : REAL; (*Power reduction EU from DIs*) (* OldName: RED_EVU; Cycle: 5 *)
		bLockAckStarter : BOOL; (* lockout acknowledgement by starter temperature *) (*OldName:AT4_BLOCK; Cycle:5*)
		tP_GenC_Bloc : HALioDo_Type; (* DO: internal blocking signal*) (* OldName: DO_RM_EVU_0; Cycle: 5 *)
		tERDF_BLOCK : HALioDo_Type; (* DO: Block von ERDF *) (* OldName: DI_EVU_BLOCK ; Cycle: 5 *)
		bOpMsg_Plim_ERDF_ABF_SOnOf : BOOL; (* P0 DEIE activ / not active *) (*OldName: ;Cycle:5;*)
		rCust_SparePara : ARRAY[0..200]OF REAL; (*SPS_REZP1 to SPS_REZP200	*) (* OldName: SPS_REZP1, SPS_REZP2, SPS_REZP70; Cycle: 5; *)
		bEng_Bloc_SGM : BOOL; (*SGM blocks engine start because reference procedure is active *) (* OldName: M_GM_Ref; Cyclic:5; *)
		bSG_Eng_Block_EGT : BOOL; (* W3529 - Blockierung fuer x[min] nach 30min Betrieb (Sondergas) *) (* OldName: bBLOCK_ABGTEMP; Cycle:2; *)
		bSG_FPR : BOOL; (* Special Gas: Fast Power Reduction *) (* OldName: bPredMessage; Cycle:2; *)
		rP_Red_SG_Norm_Pred : REAL;  (* power reduction by glow ignition max number exceeded*) 
		rP_Red_SG_Norm_FPR : REAL;  (* power reduction by glow ignition*)
		rP_Red_Pr_CC_Norm : REAL; (*power reduction due to crank case pressure*) (*OldName:ssPowerRed_Pr_CC; Cycle:5*)
		bEng_Bloc_EC : BOOL; (* blocking engine from EC Modul *) (*OldName: new PV;Cycle:2;*)
		bSAFIPBCConfNotOK : BOOL; (* blocking of start because SAFI PBC parameter are not valid *) (* OldName:bSAFIPBCConfNotOK; Cycle:2 *)
		tTCOP_UPS_CB_On : HALioDi_Type; (*prelubrication pump turbo charger USV circuit breaker on*) (*OldName:DI_TCOP_USV_OK; Cycle:5;*)
		tUPS_Ok : HALioDi_Type; (*uninterrupted power supply ok/alarm*) (*OldName:DI_USV_OK; Cycle:5*)
		bGen2_Act : BOOL; (* TRUE = Gen2 Controller active*) (* Oldname: BDC_ON; Cycle: 2 *)
		rP_GEN2_Norm : REAL; (* power trajectory SimSo P_d/1000/IN_EC.rP_Nom *) (* Oldname: P_d; Cycle: *)
		ti_MisfShutDown : TIME; (* Engine is shuting down in X second because of misfire*) (* Oldname: new PV; Cycle: 2 *)
		bFastRamp_Rel : BOOL; (* release fast load ramp  *) (* OldName: bFreigabeSchnelleRampe; Cycle:2; *)
		rP_Set_Offset_PFC_Norm : REAL; (*! new 2015 ! TODO: connect local function*)
		bP_Set_Offset_PFC_Enable : BOOL; (*! new 2015 ! TODO: connect local function*)
		tGCB_OGP : HALioDi_Type; (*DI generator circuit breaker other generator parallel*) (*OldName: DI_EVU; Cycle: 5;*)
		bRelMainsConnect : BOOL; (*Blocking module*) (*OldName:newPv; Cycle:5;*)
		rP_Red_TempMax_GenCB_Norm : REAL; (*Setpoint power reduction temperature max generator switch gear*) (*OldName:newPv; Cycle:5;*)
		bP_Red_TempMax_GenCB_Sel : BOOL; (*Set power reduction temperature max generator switch gear*) (*OldName:newPv; Cycle:5;*)
		rP_Red_TransformerWarning_Norm : REAL; (*Transformer power reduction setpoint*) (*OldName:new; Cycle:5*)
		bP_Red_TransformerWarning_Sel : BOOL; (*Transformer power reduction active*) (*OldName:new; Cycle:5*)
		rP_Ramp_FS_Norm : REAL; (* fast start ramp from EC *) (*OldName:new PV;Cycle:2;*)
		bsy_lfg_SG : BOOL; (*sy- loadrelease from EC:specialgas (just for p2s based idle mode lambda controller)*)
		rP_Red_T_GenAirIn_Norm : REAL; (*generator air inlet temperature power reduction*)
		bP_Set_FC_Enable : BOOL; (* power setpoint FC active *)
		rP_Set_FC_Norm : REAL; (*generator power setpoint by frequency control*)
		bSimWinMOD_Active : BOOL; (* WinMOD simulation active *) (* OldName:new PV; Cycle:5*)
		bSimWinMOD_FastStart : BOOL; (* WinMOD fast start of engine*) (* OldName:new PV; Cycle:5*)
		tECWP_FC_Rdy : HALioDi_Type; (* DI engine cooling water pump frequency converter ready for operation *) (*OldName:MKP_FU_rdy; Cycle:5*)
		tEOP_FC_Rdy : HALioDi_Type; (*DI: engine oil pump freq.converter operation/ready*) (*OldName:VSP_FU_rdy; Cycle:5*)
		tBbBlower_FC_Rdy : HALioDi_Type; (*DI Blow-by Blower FC ready *) (* Oldname:new PV , Cycle:5 *)
		tScavFanFC_Rdy : HALioDi_Type; (*exhaust gas scavenging fan frequency converter ready for operation*) (*OldName:SPV_FU_rdy;Cycle:5*)
		bFS_Act : BOOL; (* FastStart activated (enabled and required from customer) *)
		bRelEngStart_OilSkid : BOOL; (*release engine start from Oil Skid*) (*OldName:NewPv;Cycle:2*)
		bAMM_Pr_MGT_a_Filt_BlockStart : BOOL; (*Block engine start after 5 times W2462 Measuring signal failure gas pressure after filter in main gas train*) (* OldName: new PV ; Cycle: 5;*)
		bAMM_Pr_PCGT_a_Filt_BlockStart : BOOL; (*Block engine start after 5 times W2462 Measuring signal failure gas pressure after filter in prechamber gas train*) (* OldName: new PV ; Cycle: 5;*)
		rP_Red_Pr_GR_Norm : REAL; (*Power reduction by minimum gas pressure *)
		bPBC_Active : BOOL; (* PBC is active, since activation power is reached *)
		bP_Set_PU_Enable : BOOL; (*P(U) - power set activated and ready to use by powersel*)
		rP_Set_PU_Norm : REAL; (*Power setpoint from P(U) function (p.u.)*)
		tHW_Switches : OpMode_Switches; (*Hardware operation mode switches*)
		bBloc_SY_FS : BOOL; (* TRUE = SY Blockieren -> warten um Turbo aufzuheizen *)
		tF_MMD_BusBar : ARRAY[0..2]OF HALioAi_Type; (*Bus bar frequency*)
		bReady4VeryFastStart : BOOL; (* Ready for very fast start *)
		bReady4FastStart : BOOL; (* Ready for fast start *)
		bVeryFastStart_Prep : BOOL; (* very fast start preperation running *)
		bFastStart_Prep : BOOL; (* fast start preperation running *)
		iStartCount : UINT; (*Number of Start*)
		bMsg1995 : BOOL; (*Beta V24: Blockierung Motor bei Perm Fehler*)
		bMsg9214 : BOOL; (*Engine turn equipment active, SWAT920/5*) (*OldName:newPV;Cycle:5;*)
		bMsg1165 : BOOL; (*exhaust gas scavenging fan failure, SWAT920/5*) (*OldName:newPV;Cycle:5;*)
		rP_Red_CppInt_Norm : REAL; (* Power reduction by Cylinder Peak Pressure Integrator *) (*OldName: newPV; Cycle: 5; *)
		rP_Red_CV_Norm : REAL; (*power reduction due to Calorific value low [%], e.g. 0.75 =75% power of nominal power   *) (* OldName: 	RED_CV	; Cyclic: ; *)
		tAuxV_Aux_ok : HALioDi_Type; (*DI: Auxiliaries voltage auxiliaries panel OK*)
		tAuxV_Eng_ok : HALioDi_Type; (*DIauxiliariesvoltageengineok*)
		tAuxV_ModIf_ok : HALioDi_Type; (*DI: Auxiliaries voltage module interface OK*)
		tAuxV_Supply_Ok : HALioDi_Type; (*DIauxiliaryvoltagesupplyok*)
		bCust_Dem : BOOL; (* Remote Engine demand from CU module *)
		tP_Droop_Set : HALioAi_Type; (* Droop Offset Setpoint via AI *)
		rP_Droop_Set_Bus_Norm : REAL; (* Droop Offset Setpoint via Bus [%Pnom] *)
		bP_Droop_Set_Bus : BOOL; (* Enable Droop Offset Setpoint via Bus *)
		rN_Offs_Cust : REAL; (* Speed offset setpoint from CU module [rpm] *)
		tPF_Act : ARRAY[0..2]OF HALioAi_Type; (* actual cos phi value TC1*) (*ssCosPhi_TC1; Cycle:2; *)
		bMsg9249 : BOOL; (*exhaust gas pressure fast measurement signal failure*) (*OldName:newPV;Cycle:5;*)
		bRelSy_Customized : BOOL; (*Freigabe Syncronisierungl vo Customized Modul*)
		bSel_DeExc : BOOL; (* DeExcitation selected *)
		bERV_NotRdy : BOOL; (*engine room ventilation not ready - block engine start*)
		bMsg2524 : BOOL; (*engine oil preheating temperature min / no start release*) (*OldName:newPV; Cycle:5;*)
		bEng_Bloc_GR : BOOL; (* blocking engine from GR Modul, data structure failure *)
		tEngBlock_PlantCtr : HALioDi_Type; (* DI: Module blocked by plant control *)
		bBloc_SY_ProtTest : BOOL; (*blocking synchr./load release by protection test*)
		tScavFanCB_trip : HALioDi_Type; (*exhaust gas scavenging fan circuit breaker tripped*)
		tGenIF_CB_On : HALioDi_Type; (*Generator interface panel circuit breaker tripped*)
		bAMM_OilSkid_PumpLP_CB : BOOL; (*Oilskid low pressure oil pump circuit breaker tripped*)
		bAMM_OilSkid_PumpHP_CB : BOOL; (*Oilskid high pressure oil pump circuit breaker tripped*)
		bAMM_OilSkid_MCB : BOOL; (*Oilskid main switch auxiliaries opened*)
		tECWP_CB_On : HALioDi_Type; (*DI Engine cooling water pump circuit breaker on*)
		bSyncSlipMode : ARRAY[0..2]OF BOOL; (* MMD synchronization with slip mode *) (*OldName:bSyncSlipMode;Cycle:5;*)
		bBloc_SY_Rel_Cust : BOOL; (* Remote Synchronization / load release from CU module *) (*OldName:newPV; Cycle:5;*)
		bRel_P_Red_I_Bus : BOOL; (*IF720: Release automatic power reduction in island operation*) (*OldName:newPV; Cycle:5;*)
		bReq_PowMod_Ext : BOOL; (*External power mode selection*) (*OldName:newPV; Cycle:5;*)
		iFastStart : USINT; (* Type of Start: 0=normal start, 1=fast start, 2=very fast start, 5=5min start *)
		rP_Red_TJDiffPr_Norm : REAL; (*Gas proportional valve differential pressure power reduction setpoint*)
		bMsg1054 : BOOL; (*Alarm 1054 Fire alarm*)
		bFastChange : BOOL; (* Special Gas: Fast Gas Quality Change *)
		bEngBloc_EX : BOOL; (*engine blockage from EX*)
		bP_Droop_Set_AI : BOOL; (* Enable Droop power setpoint by Analog input *)
		rP_Droop_Set_AI_Norm : REAL; (* Droop Offset Setpoint via AI [%Pnom] *)
		iSource_F_N_OffsSet : INT; (* F/N Setpoint: 0= no setpoint, 1= Droop, 2= External, 3= LSL *)
		bFastStart_ready_running : BOOL; (* Fast start running *)
		rP_Red_SAErr_Norm : REAL; (* Power reduction by CAN communication failure for half or more SAFI or too many SAFI reboots*) (*OldName: newPV; Cycle: 5; *)
		bSA_CfgDone : BOOL; (*All SAFI in operation mode*)
		bIC_OperationState : BOOL; (*Ignition system in operation state*)
		rP_Red_H2_Norm : REAL; (* H2 content power reduction setpoint *)
		tLineCB_On : HALioDi_Type; (*DI Line circuit breaker*)
		bOtherGeneratorsInLSL : BOOL; (*LSL: FALSE if there are no other other generators in parallel with this generator that are actively participating in the LSL*)
		bServiceMode : BOOL;  (* Service mode *) 
		bExtendedOpRangeRel : BOOL; (*Release for extended operating range*)
		rP_Set_Min_Norm_Ext : REAL; (*customized minimum power setpoint in p.u. related to Pnom*)
		bGCB_OGP_Bus : BOOL; (* Other generator parallel via bus *)
		bEvent_Change : BOOL; (* Trigger bit for event change in case of power set point via bus *)
		bEng_Dem_EPS_Bus : BOOL; (*Custom engine demand EPS via BUS from CU modul*)
		bOM_Bus : BOOL; (* External power setpoint activation in AUTO/ON *)
		rSetPointPW : REAL; (* External power setpoint in AUTO/ON *)
		bUseEventBased_P_Set : BOOL; (* Use event based power setpoint from CU module *)
		rP_Set_Norm_EventBased : REAL; (* Event based external power setpoint via bus related to rP_Nom *)
		bGCB_psf_EngStop : BOOL; (*GCB position failure when engine is stopped*)
		rP_Red_Eta_Gen_Norm	: REAL; (*power reduction due to Cosphi <1 [p.u.]*)
		bSt_RelAuxOff_STT_op : BOOL; (*Starter temperature release off for op_state*)
		bBlock_WG_CAN_Conf : BOOL; (*WG CAN configuration in progress*)
		bRelEngStart_Ch_T2 : BOOL; (*release engine start from charge temperature after TC*)
	END_STRUCT;
	Para_Opstate_Struct : 	STRUCT 
		rN_Start_Trig : REAL; (*PARA [12092]: start up speed trigger value *) (*OldName:n_start;Cycle:5;*)
		rN_EngNom : REAL; (*PARA [12128]: nominal speed *) (*OldName:n_nenn;Cycle:5;*)
		rP_Nom_Gastype : ARRAY[0..4]OF REAL; (*engine nominal power array [KW] *) (*OldName:p_nenn;Cycle:5;*)
		rP_StCtr_Grad : REAL; (*PARA [12109]: gradient for static controller at loadsharing with statics control *) (*OldName:pr_pgrad;Cycle:5;*)
		rP_Island_Split : REAL; (*PARA [12093]: power devide in island mode *) (*OldName:pr_p;Cycle:5;*)
		rP_Set_Min_Norm : REAL; (*PARA [12108]: minimal power setpoint related to rP_nom *) (*OldName:p_min;Cycle:5;*)
		rP_Island_Split_IncGrad_Norm : ARRAY[0..4]OF REAL; (*gradient for increase of load sharing line output *) (*OldName:new PV;Cycle:5;*)
		rP_Island_Split_DecGrad_Norm : ARRAY[0..4]OF REAL; (*gradient for decrease of load sharing line output *) (*OldName:new PV;Cycle:5;*)
		rP_Ramp_IncGrad_Norm : ARRAY[0..4]OF REAL; (*gradient for increase of power ramp in grid mode *) (*OldName:t_up;Cycle:5;*)
		rP_Ramp_DecGrad_Norm : ARRAY[0..4]OF REAL; (*gradient for decrease of power ramp in grid mode *) (*OldName:t_down;Cycle:5;*)
		rN_BS_Acc_LimHi : REAL; (*PARA [12202]: speed limit for black start 15s *) (*OldName:bs_15s_rpm_lim_hi;Cycle:5;*)
		bBS_Acc_Active : BOOL; (*PARA [12178]: black start active *) (*OldName:sel_black_start_15s;Cycle:5;*)
		rT_ECW_LimLo : REAL; (*PARA [11944]: cooling water temperature low limit *) (*OldName:GW_KTMI;Cycle:5;*)
		rT_ECW_HyLo : REAL; (*PARA [11938]: cooling water temperature low hysteresis *) (*OldName:HY_KTMI;Cycle:5;*)
		bRemoteReqActive : BOOL; (*PARA [12091]: Para remote request active *) (*OldName:bRemoteReqAct;Cycle:5;*)
		bGlowIgnPrevActive : BOOL; (*PARA [12089]: Para glow ignition prevention active *) (*OldName:sel_GlowIgnPrevent;Cycle:5;*)
		rN_EngStart_LimHi : REAL; (*PARA [11296]: Limit start engine speed *) (*OldName:GW_DREHZ;Cycle:5;*)
		rN_EngStart_HyHi : REAL; (*PARA [11295]: hysteresis value of limit start engine speed *) (*OldName:HY_DREHZ;Cycle:5;*)
		iEng_Motortype : INT; (*motortype of engine *) (*OldName:new PV;Cycle:5;*)
		bPurgecycle_Active : BOOL; (*PARA [12256]: Para purge cycle enable  *) (*OldName:bPurgecycle;Cycle:5;*)
		bSel_TwoN2Valves : BOOL; (*PARA [11313]: Para select exhaust gas scavenging with 2 nitrogen(N2) gas valves *) (*OldName:sel_TwoN2Valves;Cycle:5;*)
		tCBV_CDS_Power : tSimPID_DS_typ; (*parameter structure for xSimPID for the compressor bypass in grid mode *) (*OldName:tp;Cycle:5;*)
		rP_HyLo : REAL; (*PARA [12206]: Para power signal missing limit low hysteresis *) (*OldName:HY_LSA;Cycle:5;*)
		rP_LimLo : REAL; (*PARA [12208]: Para power signal missing limit low  *) (*OldName:GW_LSA;Cycle:5;*)
		iIdx_Gastyp : INT; (*PARA [11402]: Number of gas types *) (*OldName:anz_gasart;Cycle:5;*)
		bSyActive : BOOL; (*PARA [12195]: synchronization active *) (*OldName:bSynch;Cycle:5;*)
		iNum_GT : INT; (*PARA [11403]: Number of gas trains *) (*OldName:usNrOfGasTrains;Cycle:5;*)
		rP_Dev_LimHi : REAL; (*PARA [12260]: Para power deviation (actual value/reduced set value) limit high [%/P_nom] *) (*OldName:Z_GW_PDIFF;Cycle:5;*)
		tiP_Dev_LimHi_Delay : TIME; (*PARA [12295]: Para power deviation (actual value/reduced set value) high, delay time *) (*OldName:TSW_PDIFF;Cycle:5;*)
		bEngTyp3_Prelub_Active : BOOL; (*PARA [10009]: Para prelubrication for engine typ 3 active *) (*OldName:BR3_VS_aktiv;Cycle:5;*)
		bSA_PBC_Active : BOOL; (*PARA [12119]: TRUE = SAFI PBC function is enabled/active*) (*OldName:bSAFIDMR_Act;Cycle:5;*)
		bIgnP_Opt_Exist : BOOL; (*PARA [11057]: TRUE =  igniton timing point optimisation is active *) (* OldName: bCylOpt; Cycle: 2 *)
		zz_V4_0_ParaVersionEnd : REAL := 4.0; (*! ADD NEW PARAMETER ONLY BELOW THIS LINE ! This is the end of base version parameter and has to stay unchanged. DO NOT CHANGE SORT ORDER of Para!*) (* OldName: new PV; Cycle: 5; *)
		bSA_PI_Active : BOOL; (*PARA [12120]: TRUE = SAFI port injection is enabled/active  *) (* OldName: bSAFIPI_Act; Cycle: 2 *)
		ti_OpTi_MisCyl_Trig : TIME; (*PARA [12802]:operating time treshold until shutdown request*) (*OldName:new PV; Cycle:5*)
		rF_Nom : ARRAY[0..2]OF REAL; (*Para: nominal frequency [48..62Hz] *) (* OldName: usFreqNenn[1]; Cycle: 5*)
		rN_Offs_Sync : REAL; (*PARA [12883]: Engine Speed Offset for Synchronization [rpm] *) (*OldName:new PV; Cycle:2*)
		bP_GhStep_Ena : BOOL; (*PARA [13273]: Activates Loadstep feedback*) (*OldName:new PV; Cycle:2*)
		rP_GhStep_Lim_Norm : ARRAY[0..4]OF REAL; (*Loadsteps*) (*OldName:new PV; Cycle:2*)
		rP_Drift_Rel_Norm : REAL; (*PARA [13326]: Release power adjustment limit in% power*) (*OldName:n_start;Cycle:5;*)
		iNum_Eng_LSL : INT; (*PARA [13325]: amount of engines in Island operation*) (*OldName:anz_mod;Cycle:5;*)
		bP_drift_GH_Ena : BOOL; (*PARA [13324]: p_drift active (Greenhouse application)*) (*OldName:p_grad_akt;Cycle:5;*)
		bP_max_GH_Ena : BOOL; (*PARA [13322]: p_max active (Greenhouse application)*) (*OldName:p_grad_akt;Cycle:5;*)
		bRej2houseload : BOOL; (*PARA [14079]: Fangen im Eigenbedarf aktiv?*)
		bDeAct_EarlyGV_opening : BOOL; (*PARA [13983]: FALSE: Use early Gas Valve Opening (XT4-standard) | TRUE: Deactivate early Gas Valve Opening e.g. for XT4-light upgrades*)
		rEta_Gen_PF1 : REAL; (*PARA [14343]: Generator Efficiancy at power factor 1.0*)
		rEta_Gen_PF08 : REAL; (*PARA [14344]: Generator Efficiancy at power factor 0.8 overexcited*)
		rP_Red_T_ECW_Low_Norm : REAL; (*PARA [14363]: max engine load if ECWT is low e.g. 0.4 *)
		rP_Lim_T_ECW_Low_Norm : REAL; (*PARA [14362]: min engine load if ECWT is low e.g. 0.2 *)
		bEna_OpInfo : BOOL; (*PARA [14361]: Enables additional Opstate Information on the HMI *)
		bPRed_Island_Active : BOOL; (*PARA [14364]: Power reductions active in island mode *)
		tiFilt_P_Act_LS : TIME; (*PARA [14382]: Filter time constant for power signal in load sharing *)
		rP_Ramp_IncGrad_Norm_Max : REAL; (*PARA [14508]: Power increase ramp maximum *)
		rP_Ramp_DecGrad_Norm_Max : REAL; (*PARA [14509]: Power decrease ramp maximum *)
		rTi_SetCorr_SpdFilt_ms : REAL; (* PARA [14602] Compatibility to Microgrid Ctrl: speed filter time [ms]*)
		bP_SetCorr_FreqDroop : BOOL; (* PARA [14603] Compatibility to Microgrid Ctrl: Pset adaption by speed droop *)
		bP_SetCorr_extNoffset : BOOL; (* PARA [14604]Compatibility to Microgrid Ctrl: Pset adaption by ext. speed offs. *)
		bN_SpdSetRed_Overload : BOOL; (* PARA [14607] Overload Protection Isolated Operation: Activation Reduction Speed Reference*)
		rP_SpdSetRed_LimNorm : REAL; (* PARA [14608] Overload Protection Isolated Operation: normalized power overload limit*)
		rN_SpdSetRed_delta : REAL; (* PARA [14609]Overload Protection Isolated Operation: Maximum Speed Reference Reduction [rpm]*)
		rTi_SpdSetRed_Ramp : REAL; (* PARA [14610] Overload Protection Isolated Operation: ramp time for reaching min speed*)
		iSource_F_N_OffsSet : INT; (* PARA [14300] F/N Setpoint: 0= no setpoint, 1= Droop, 2= External, 3= LSL *)
		bRemoteReqMyPlantActive : BOOL; (*PARA [14634]: Para remote request via myPlant active *)
		bRemotePSetHasPrio : BOOL; (*PARA [14635]: TRUE = remote power setpoint overrules local ones *)
		tiFilt_LSL_In : TIME; (*PARA [14383]: Filter time constant for load sharing line input signal*) (* Oldname: newPv, Cycle:*)
		rK_LoadProt : REAL; (*PARA [14923]: Gain of ovlerload and reverse power limit controller*)
		rK_LoadProt_N : REAL; (*PARA [14924]: Speed deviation dependent gain of ovlerload  limit controller*)
		tiFilt_P_Act_LoadProt : TIME; (*PARA [14922]: Filter time constant of power filter for limit controller*)
		bN_SpdSetInc_ReversePower : BOOL; (*PARA [14925] Reverse Power Protection Isolated Operation: Activate Raise of Speed Reference*)
		tiLSL_Correction : TIME; (*PARA [14965] Integral action time for LSL signal error compensation *)
		iSel_Customer : DINT; (*PARA [14950]: 0 = no special, 1 = AB Energy, 2 = Aggreko, 3 = 2G, etc.... *)
	END_STRUCT;
	MM2VIS_Opstate_Struct : 	STRUCT 
		M_ANF : BOOL; (* engine demand *) (*OldName:M_ANF;Cycle:5;*)
		iSt_OpMode_Main : INT; (* engine operation - main mode *) (*OldName:new PV;Cycle:5;*)
		rN_Set : REAL; (* speed setpoint speed controller *) (*OldName:n_soll;Cycle:5;*)
		rP_Act_Filt : REAL; (* actual power filtered T=1s *) (*OldName:p_ist;Cycle:5;*)
		rP_Set : REAL; (* power setpoint *) (*OldName:p_soll;Cycle:5;*)
		P_UNRED : REAL; (* power setpoint without any reduction for visual display system *) (*OldName:P_UNRED;Cycle:5;*)
		bP_Red_Active : BOOL; (* power setpoint without any reduction for visual display system *) (*OldName:PredAkt;Cycle:5;*)
		RedPower : REAL; (* power reduction [KW] *) (*OldName:RedPowerkW;Cycle:5;*)
		iIdx_Eng_State : INT; (* state of engine *) (*OldName:HPTSCHL;Cycle:5;*)
		iIdx_Pred_Type : INT; (* Index for type of power reduction *) (*OldName:usPowerRedTyp;Cycle:5;*)
		iSt_OpMode_Sub : INT; (* engine operation - sub mode *) (*OldName:new PV;Cycle:5;*)
		iSt_OpMode_Deg : INT; (* engine operation - degradation mode *) (*OldName:new PV;Cycle:5;*)
		rP_Nom : REAL; (* nominal electric power [KW], depends on gastype *) (*OldName:PN_GASART;Cycle:5;*)
		iIdx_Pset_Type : INT; (* power setpoint type *) (*OldName:usPowerSetpTyp;Cycle:5;*)
		bMainMode_Idle : BOOL; (* engine operation - main mode idle *) (*OldName:LeerM;Cycle:5;*)
		bMainMode_Grid : BOOL; (* engine operation - main mode grid *) (*OldName:NetpM;Cycle:5;*)
		bMainMode_Island : BOOL; (* engine operation - main mode island *) (*OldName:InselM;Cycle:5;*)
		bEng_Aux_Dem_CDR : BOOL; (*engine auxiliaries demand with cool down run*) (*OldName:ANFHBT;Cycle:5;*)
		bEng_RPSDem : BOOL; (* demand RPS *) (*OldName:M_AGRPS;Cycle:5;*)
		bEng_Rdy_Aut_Exc : BOOL; (* engine ready for automatic operation information for the excitation system *) (*OldName:BERAUT;Cycle:5;*)
		rP_Red_EGT : REAL; (*	power reduction by exhaust gas temp. [KW]	*) (*OldName:ssPowerRedAbgas;Cycle:5;*)
		rP_Red_Misf : REAL; (*	power reduction by misfire [KW]	*) (*OldName:ssPowerRedAussetz;Cycle:5;*)
		rP_Red_Leanox : REAL; (*	power redutcion by LEANOX [KW]	*) (*OldName:ssPowerRedLeanox;Cycle:5;*)
		rP_Red_CH4 : REAL; (*	power reduction due to CH4 low [KW]	*) (*OldName:ssPowerRedCH4;Cycle:5;*)
		rP_Red_EVU : REAL; (*	power redutcion by utility [KW]	*) (*OldName:ssPowRed_Utility;Cycle:5;*)
		rP_Red_GasPr : REAL; (*	power reduction due to gas pressure low [KW]	*) (*OldName:ssPowerRedGD;Cycle:5;*)
		rP_Red_SuctPr : REAL; (*	power reduction due to suction pressure high [KW]	*) (*OldName:ssPowerRedSD;Cycle:5;*)
		rP_Red_AI : REAL; (*	power reduction by analog input [KW]	*) (*OldName:ssPowerRedAnalog;Cycle:5;*)
		rP_Red_CosPCtr_F : REAL; (*	power reduction by generator frequency [KW]	*) (*OldName:ssPowerRedGenFrq;Cycle:5;*)
		rP_Red_CosPCtr_U : REAL; (*	power reduction by generator voltage [KW]	*) (*OldName:ssPowerRedGenSpg;Cycle:5;*)
		rP_Red_CosPCtr_T : REAL; (*	power reduction by generator winding temperature [KW]	*) (*OldName:ssPowerRedGenTemp;Cycle:5;*)
		rP_Red_TC : REAL; (*	power reduction by turbo charger speed [KW]	*) (*OldName:ssPowerRedTurboSpd;Cycle:5;*)
		rP_Red_Sp_Lim1 : REAL; (*	power setpoint limit 1  [KW]	*) (*OldName:ssPowerSetpointLimit1;Cycle:5;*)
		rP_Red_Sp_Lim2 : REAL; (*	power setpoint limit 2  [KW]	*) (*OldName:ssPowerSetpointLimit2;Cycle:5;*)
		rP_Red_Sp_Lim3 : REAL; (*	power setpoint limit 3  [KW]	*) (*OldName:ssPowerSetpointLimit3;Cycle:5;*)
		rP_Red_Knck : REAL; (*	power reduction by knocking [KW]	*) (*OldName:ssPowerRedKlopf;Cycle:5;*)
		rP_Red_Ch_T2s : REAL; (*	power reduction by mixture temperatiure [KW]	*) (*OldName:ssPowerRedGemisch;Cycle:5;*)
		rP_Red_T_HWR : REAL; (*	power redutcion by heat water return temp. max [KW]	*) (*OldName:ssPowerRedRLT;Cycle:5;*)
		rP_Red_T_ECW : REAL; (*	power redutcion by engine cooling water temp. max [KW]	*) (*OldName:ssPowerRedKWT;Cycle:5;*)
		rP_Red_T_Oil : REAL; (*	power redutcion by oil temp. max [KW]	*) (*OldName:ssPowerRedOLT;Cycle:5;*)
		rP_Red_Ch_T2HP : REAL; (*power reduction by charge temperature after high-pressure turbo charger [KW] *) (*OldName:new PV;Cycle:5;*)
		rP_Red_Ch_T2LP : REAL; (*power reduction by charge temperature after low-pressure turbo charger [KW] *) (*OldName:new PV;Cycle:5;*)
		rP_Red_Pr_PCGT : REAL; (*	power redutcion by pre chamber gas pressure [KW]	*) (*OldName:ssPowerRedVKG;Cycle:5;*)
		rP_Red_ExtBus : REAL; (*	power redutcion by primary control [KW]	*) (*OldName:ssPowerRedZLT;Cycle:5;*)
		rP_Red_T_InAirER : REAL; (*	power reduction by intake air engine room temperature [KW]	*) (*OldName:ssPowerRedIntakeAirT;Cycle:5;*)
		rP_Red_Hum : REAL; (*power redutcion by humidity [KW] *) (*OldName:new PV;Cycle:5;*)
		rP_Red_PBC : REAL; (*power redutcion by PBC [KW] *) (*OldName:new PV;Cycle:5;*)
		rP_Red_Knck_Opti : REAL; (*power redutcion by  timing point optimizing [KW] *) (*OldName:new PV;Cycle:5;*)
		rP_Red_SG : REAL; (*power redutcion by  glow ignition [KW] *) (*OldName:new PV;Cycle:5;*)
		rP_Red_Pr_CC : REAL; (*power redutcion by  crank case [KW] *) (*OldName:new PV;Cycle:5;*)
		rP_Red_HiCtr : REAL; (*power redutcion by hierarchic controller [KW] *) (*OldName:new PV;Cycle:5;*)
		rP_Red_SG_Norm : REAL; (*Power reduction by minimum gas pressure*) (*OldName:new PV;Cycle:5;*)
		rP_Red_Pr_GR : REAL; (*Power reduction by minimum gas pressure*) (*OldName:new PV;Cycle:5;*)
		rP_Set_Min : REAL; (*minimal power setpoint [KW]*) (*OldName:p_min;Cycle:5;*)
		rP_RedDelta_Knck_Norm : REAL; (* power reduction by knocking related to Pnom *) (*OldName:new PV;Cycle:5;*)
		rP_RedDelta_Ch_T2s_Norm : REAL; (* power reduction by mixture temperatiure related to Pnom *) (*OldName:gem_dp;Cycle:5;*)
		rP_RedDelta_Misf_Norm : REAL; (* power reduction by misfire related to Pnom *) (*OldName:ausetz_dp;Cycle:5;*)
		rP_RedDelta_EGT_Norm : REAL; (* power reduction by exhaust gas temp. related to Pnom *) (*OldName:abgas_dp;Cycle:5;*)
		rP_RedDelta_T_InAirER_Norm : REAL; (* power reduction by intake air engine room temperature related to Pnom *) (*OldName:IATemp_dp;Cycle:5;*)
		rP_RedDelta_Leanox_Norm : REAL; (* power reduction by leanox related to Pnom *) (*OldName:leanox_dp;Cycle:5;*)
		rP_RedDelta_CH4_Norm : REAL; (* power reduction due to CH4 low related to Pnom *) (*OldName:RED_CH4;Cycle:5;*)
		rP_RedDelta_GasPr_Norm : REAL; (* power reduction due to gas pressure low related to Pnom *) (*OldName:RED_GD;Cycle:5;*)
		rP_RedDelta_SuctPr_Norm : REAL; (* power reduction due to suction pressure high related to Pnom *) (*OldName:RED_SD;Cycle:5;*)
		rP_RedDelta_TC_Norm : REAL; (* power reduction by turbo charger speed related to Pnom *) (*OldName:new PV;Cycle:5;*)
		rP_RedDelta_T_HWR_Norm : REAL; (* power reduction by heat water return temperature related to Pnom *) (*OldName:RED_RLT;Cycle:5;*)
		rP_RedDelta_T_ECW_Norm : REAL; (* power reduction by engine cooling water temperature related to Pnom *) (*OldName:RED_KWT;Cycle:5;*)
		rP_RedDelta_T_Oil_Norm : REAL; (* power redutcion by oil temp. max related to Pnom *) (*OldName:RED_OLT;Cycle:5;*)
		rP_RedDelta_Ch_T2HP_Norm : REAL; (* power reduction according charge temperature after high-pressure turbo charger related to Pnom *) (*OldName:new PV;Cycle:5;*)
		rP_RedDelta_Ch_T2LP_Norm : REAL; (* power reduction according charge temperature after low-pressure turbo charger related to Pnom *) (*OldName:new PV;Cycle:5;*)
		rP_RedDelta_Pr_PCGT_Norm : REAL; (* power redutcion by pre chamber gas pressure related to rP_Nom *) (*OldName:RED_VKG;Cycle:5;*)
		rP_RedDelta_CosPCtr_U_Norm : REAL; (* power reduction by generator voltage related to Pnom *) (*OldName:ssPowRedGenSpg;Cycle:5;*)
		rP_RedDelta_CosPCtr_F_Norm : REAL; (* power reduction by generator frequency related to Pnom *) (*OldName:ssPowRedGenFrq;Cycle:5;*)
		rP_RedDelta_CosPCtr_T_Norm : REAL; (* power reduction by generator winding temperature related to Pnom *) (*OldName:ssPowRedGenTemp;Cycle:5;*)
		rP_RedDelta_Sp_Lim1_Norm : REAL; (* power setpoint limit 1 related to rP_Nom *) (*OldName:new PV;Cycle:5;*)
		rP_RedDelta_Sp_Lim2_Norm : REAL; (* power setpoint limit 2 related to rP_Nom *) (*OldName:new PV;Cycle:5;*)
		rP_RedDelta_Sp_Lim3_Norm : REAL; (* power setpoint limit 3 related to rP_Nom *) (*OldName:new PV;Cycle:5;*)
		rP_RedDelta_EVU_Norm : REAL; (* power redutcion by utility related to Pnom *) (*OldName:RED_EVU;Cycle:5;*)
		rP_RedDelta_AI_Norm : REAL; (* power reduction by analog input related to Pnom *) (*OldName:analog_dp;Cycle:5;*)
		rP_RedDelta_ExtBus_Norm : REAL; (* power redutcion by primary control related to Pnom *) (*OldName:B_P_RED;Cycle:5;*)
		rP_RedDelta_Hum_Norm : REAL; (*power redutcion by humidity related to rP_Nom *) (*OldName:new PV;Cycle:5;*)
		rP_RedDelta_PBC_Norm : REAL; (*power redutcion by PBC related to rP_Nom *) (*OldName:new PV;Cycle:5;*)
		rP_RedDelta_Knck_Opti_Norm : REAL; (*power redutcion by  timing point optimizing related to rP_Nom*) (*OldName:new PV;Cycle:5;*)
		rP_RedDelta_SG_Norm : REAL; (*power redutcion by  glow ignition related to rP_Nom*) (*OldName:new PV;Cycle:5;*)
		rP_RedDelta_Pr_CC_Norm : REAL; (*power redutcion by  crank case related to rP_Nom*) (*OldName:new PV;Cycle:5;*)
		rP_RedDelta_HiCtr_Norm : REAL; (*power redutcion by hierarchic controller related to rP_Nom*) (*OldName:new PV;Cycle:5;*)
		rP_RedDelta_Pr_GR_Norm : REAL; (*Power reduction by differential gas pressure*) (*OldName:new PV;Cycle:5;*)
		bEng_Run : BOOL; (* engine running *) (*OldName:BTRB,M_BTRB;Cycle:5;*)
		bMsg1108 : BOOL; (* actual power deviation maximum *) (*OldName:M_PDIFF;Cycle:5;*)
		bMsg2125 : BOOL; (*P reduction by knocking (diagn.msg RPS)*) (*OldName:bAMM[2125];Cycle:5;*)
		bMsg2126 : BOOL; (*P reduction by mixture temp. (diagn.msg RPS)*) (*OldName:bAMM[2126];Cycle:5;*)
		bMsg2127 : BOOL; (*P reduction by misfiring (diagn.msg RPS)*) (*OldName:bAMM[2127];Cycle:5;*)
		bMsg2128 : BOOL; (*P reduction by external(analoge) (diagn.msg RPS)*) (*OldName:bAMM[2128];Cycle:5;*)
		bMsg2129 : BOOL; (*P reduction by external(bus) (diagn.msg RPS)*) (* bAMM[2129];Cycle:5;*)
		bMsg2130 : BOOL; (*P reduction by frequency low (diagn.msg RPS)*) (* bAMM[2130];Cycle:5;*)
		bMsg2131 : BOOL; (*maximum output limit*) (* bAMM[2131];Cycle:5;*)
		bMsg2132 : BOOL; (*P reduction by cyl.temp. (diagn.msg RPS)*) (* bAMM[2132];Cycle:5;*)
		bMsg2143 : BOOL; (*P reduction by air intake temp. (diagn.msg RPS)*) (* bAMM[2143];Cycle:5;*)
		bMsg2144 : BOOL; (*P reduction by turbo charger speed high (diagn.msg RPS)*) (* bAMM[2144];Cycle:5;*)
		bMsg2146 : BOOL; (*P reduction by pressure based control (PBC)*) (* bAMM[2146];Cycle:5;*)
		bMsg2147 : BOOL; (*P reduction by leanox ctrl.deviation high (diagn.msg RPS)*) (* bAMM[2147];Cycle:5;*)
		bMsg2148 : BOOL; (*diagn.msg RPS 28*) (* bAMM[2148];Cycle:5;*)
		bMsg2149 : BOOL; (*diagn.msg RPS 29*) (* bAMM[2149];Cycle:5;*)
		bMsg2150 : BOOL; (*diagn.msg RPS 30*) (* bAMM[2150];Cycle:5;*)
		bMsg2152 : BOOL; (*P reduction by voltage low  (diagn.msg RPS)*) (* bAMM[2152];Cycle:5;*)
		bMsg2153 : BOOL; (*P reduction by voltage high (diagn.msg RPS)*) (* bAMM[2153];Cycle:5;*)
		bMsg2154 : BOOL; (*P reduction by frequency high (diagn.msg RPS)*) (* bAMM[2154];Cycle:5;*)
		bMsg2155 : BOOL; (*P reduction by gen.winding temp. (diagn.msg RPS)*) (* bAMM[2155];Cycle:5;*)
		bMsg2158 : BOOL; (*P reduction by jacket water temperature (diagn.msg RPS)*) (* bAMM[2158];Cycle:5;*)
		bMsg2159 : BOOL; (*P reduction by oil temperature (diagn.msg RPS)*) (* bAMM[2159];Cycle:5;*)
		bMsg2160 : BOOL; (*P reduction by heating water return temperature (diagn.msg RPS)*) (* bAMM[2160];Cycle:5;*)
		bMsg2161 : BOOL; (*P reduction by pressure pre chamber gas train (diagn.msg RPS)*) (* bAMM[2161];Cycle:5;*)
		bMsg2163 : BOOL; (*Power reduction by utility*) (* bAMM[2163];Cycle:5;*)
		bMsg2164 : BOOL; (*Power limitation by air humidity*) (* bAMM[2164];Cycle:5;*)
		bMsg2170 : BOOL; (*Power redutcion by  high level controller*) (* OldName:new PV;Cycle:5;*)
		bMsg2169 : BOOL; (*Power redutcion by  timing point optimizing*) (* OldName:new PV;Cycle:5;*)
		bMsg2803 : BOOL; (*Power reduction by charge temperature before TC (diagn.msg RPS)  -> NOT USED >= v4.12*) (* bAMM[2803];Cycle:5;*)
		bMsg3229 : BOOL; (*P reduction by CH4 content (diagn.msg RPS)*) (* bAMM[3229];Cycle:5;*)
		bMsg3230 : BOOL; (*P reduction by gas pressure (diagn.msg RPS)*) (* bAMM[3230];Cycle:5;*)
		bMsg3231 : BOOL; (*P reduction by suction pressure (diagn.msg RPS)*) (* bAMM[3231];Cycle:5;*)
		bMsg2140 : BOOL; (*demand for island operation*) (* bAMM[2140];Cycle:5;*)
		bMsg3506 : BOOL; (*Power reduction in isolated operation*) (* bAMM[3506];Cycle:5;*)
		bMsg2082 : BOOL; (*Warning: Parameters missing*) (* bAMM[2082];Cycle:5;*)
		bMsg1188 : BOOL; (*Warning: Release by station missing*) (* bAMM[1188];Cycle:5;*)
		bMsg2097 : BOOL; (*Warning: Power setpoint deviation maximum*) (* bAMM[2097];Cycle:5;*)
		bMsg1225 : BOOL; (* B1225 service seletion switch off *) (* bAMM[1225];Cycle:5;*)
		bMsg1226 : BOOL; (* B1226 service seletion switch manual *) (* bAMM[1226];Cycle:5;*)
		bMsg1227 : BOOL; (* B1227 service seletion switch automatic *) (* bAMM[1227];Cycle:5;*)
		bMsg1228 : BOOL; (* B1228 service seletion switch test *) (* bAMM[1228];Cycle:5;*)
		bMsg1229 : BOOL; (* B1229 engine ready for automatic on  *) (* bAMM[1229];Cycle:5;*)
		bMsg1230 : BOOL; (* B1230 engine ready for automatic off *) (* bAMM[1230];Cycle:5;*)
		bMsg1231 : BOOL; (* B1231 engine demand on  *) (* bAMM[1231];Cycle:5;*)
		bMsg1232 : BOOL; (* B1232 engine demand off *) (* bAMM[1232];Cycle:5;*)
		bMsg1233 : BOOL; (* B1233 engine operation on  *) (* bAMM[1233];Cycle:5;*)
		bMsg1234 : BOOL; (* B1234 engine operation off *) (* bAMM[1234];Cycle:5;*)
		bMsg1237 : BOOL; (* B1237 demand for island operation on  *) (* bAMM[1237];Cycle:5;*)
		bMsg1238 : BOOL; (* B1238 demand for island operation off *) (* bAMM[1238];Cycle:5;*)
		bMsg1241 : BOOL; (* B1241 selection gas type 1  *) (* bAMM[1241];Cycle:5;*)
		bMsg1242 : BOOL; (* B1242 selection gas type 2  *) (* bAMM[1242];Cycle:5;*)
		bMsg1243 : BOOL; (* B1243 selection gas type 3  *) (* bAMM[1243];Cycle:5;*)
		bMsg1244 : BOOL; (* B1244 selection gas type 4  *) (* bAMM[1244];Cycle:5;*)
		bMsg2122 : BOOL; (* B2122 *)
		bMsg2123 : BOOL; (* B2123 *)
		bMsg2124 : BOOL; (* B2124 *)
		bMsg2133 : BOOL; (* B2133 *)
		bMsg2134 : BOOL; (* B2134 *)
		bMsg2135 : BOOL; (* B2135 *)
		bMsg2136 : BOOL; (* B2136 *)
		bMsg2137 : BOOL; (* B2137 *)
		bMsg2138 : BOOL; (* B2138 *)
		bMsg2813 : BOOL; (* B2813 - message power setpoint by digital input *)
		bMsg2961 : BOOL; (* B2961 Power Reduction by Cylinder Peak Pressure Integrator *)
		iSt_VIS_Porgress : DINT; (* progress indication of engine operation for VIS *) (*OldName:new PV;Cycle:5;*)
		bEng_Rdy_Aut : BOOL; (* ready for automatic mode *) (*OldName:M_BERAUT;Cycle:2;*)
		bP_Red_Sp_Lim1Act : BOOL; (* power setpoint limit 1 activ *) (*OldName:bPowerSetpointLimit1;Cycle:5;*)
		bP_Red_Sp_Lim2Act : BOOL; (* power setpoint limit 2 activ *) (*OldName:bPowerSetpointLimit2;Cycle:5;*)
		bP_Red_Sp_Lim3Act : BOOL; (* power setpoint limit 3 activ *) (*OldName:bPowerSetpointLimit3;Cycle:5;*)
		bMsg2875 : BOOL; (*B2875 Power reduction by crank case pressure  *)
		bEng_Rdy_Rem : BOOL; (*Ready for Remote Operation *) (*OldName:BERZLT;Cycle:2;*)
		bEng_Aux_Dem : BOOL; (*demand auxillaries *) (*OldName:M_ANFHBT;Cycle:2;*)
		bImp_UnitOpHour : BOOL;
		bImp_OpHour : BOOL; (*impulse for operation hour counter *) (*OldName:M_BTRIMP,H_IMP;Cycle:2;*)
		bImp_Start : BOOL; (*impulse for start counter *) (*OldName:T25,M_STRTIMP;Cycle:2;*)
		bMsg1283 : BOOL; (*B1283*)
		bMsg1284 : BOOL; (*B1284*)
		bMsg1285 : BOOL; (*B1285*)
		bMsg1286 : BOOL; (*B1286*)
		bMsg1287 : BOOL; (*B1287*)
		rP_Red_T_Transformer : REAL; (*power redutcion by trafo [KW] *) (*OldName:new PV;Cycle:5;*)
		rP_RedDelta_T_Transformer_Norm : REAL; (*power redutcion by trafo related to rP_Nom*) (*OldName:new PV;Cycle:5;*)
		rP_Red_T_GenSwitchCab : REAL; (*power redutcion by GenSWCab [KW] *) (*OldName:new PV;Cycle:5;*)
		rP_RedDelta_T_GenSwitchCab_Norm : REAL; (*power redutcion by GenSWCab related to rP_Nom*) (*OldName:new PV;Cycle:5;*)
		bMsg2162 : BOOL; (*B2162 - power reduction by transformator*)
		bMsg2167 : BOOL; (*B2167 - power reduction by generator switch*)
		rP_RedDelta_T_GenAirIn_Norm : REAL; (*generator air inlet temperature power reduction (%)*)
		rP_Red_T_GenAirIn : REAL; (*generator air inlet temperature power reduction (kW)*)
		bMsg2168 : BOOL; (*Power reduction by generator air inlet temperature*)
		bMsg2936 : BOOL; (*Power reduction by gas pressure min.*)
		bDont_show_switches : BOOL; (*TRUE = no Switches shown on HMI - Hardware schwiches are used*)
		bMsg2925 : BOOL; (*B2925 Warm up operation *)
		bF_N_DI_Inc : BOOL; (* DI synch.increase speed *)
		bF_N_DI_Dec : BOOL; (* DI synch.decrease speed *)
		bMsg2983 : BOOL; (* Request mode switch OFF *)
		bMsg2984 : BOOL; (* Request mode switch ON *)
		bMsg2985 : BOOL; (* Request mode switch REMOTE *)
		rP_RedDelta_CV_Norm : REAL; (*Power reduction due calorific value *)
		rP_Red_CV : REAL; (*Power reduction due calorific value *)
		bMsg2989 : BOOL; (*B2989 Power redutcion by generator power factor cos phi <1*)
		rP_RedDelta_Eta_Gen_Norm : REAL; (*Power redutcion by generator power factor cos phi <1*)
		rP_Red_Eta_Gen : REAL; (*Power redutcion by generator power factor cos phi <1*)
		rP_Ramp_IncGrad_All_Norm : REAL; (*gradient for increase of power ramp in grid mode [1/s]*)
		rP_Ramp_DecGrad_All_Norm : REAL; (*gradient for decrease of power ramp in grid mode [1/s]*)
		bEng_Bloc : ARRAY[0..50]OF BOOL; (* Module blocked array: 1 = blocked *)
		bEng_Bloc_Show : BOOL; (* Show Module blocked array *)
		bSync_Rel : ARRAY[0..15]OF BOOL; (* Sync release array: 1 = release*)
		bSync_Rel_Show : BOOL; (* Show Sync release array *)
		bEng_SU : ARRAY[0..6]OF BOOL; (* Start up release array: 1 = release*)
		bEng_SU_Show : BOOL; (* Show Start up release array *)
		bGV_Open : ARRAY[0..7]OF BOOL; (* Open gas valve: 0 = blocked *)
		bGV_Open_Show : BOOL; (* Show Open gas valve array *)
		bReq_Dem : ARRAY[0..7]OF BOOL; (* Request demanded: 1 = demanded *)
		bReq_Dem_Show : BOOL; (* Show Request demanded array *)
		bReq_Bloc : ARRAY[0..6]OF BOOL; (* Request blocked: 1 = blocked *)
		bReq_Bloc_Show : BOOL; (* Show Request blocked array *)
		bReq_A : ARRAY[0..5]OF BOOL; (* Request automatic: 1 = demanded *)
		bReq_A_Show : BOOL; (* Show Request automatic array *)
		bEng_Dem_A : ARRAY[0..9]OF BOOL; (* Engine demanded: 1 = demanded *)
		bEng_Dem_A_Show : BOOL; (* Show Engine demanded array *)
		bIgn_Dem : ARRAY[0..5]OF BOOL; (* Ignition demanded: 1 = demanded *)
		bIgn_Dem_Show : BOOL; (* Show Ignition demanded array *)
		tF_Stat : _tXY_Stat; (* Frequency static XY Diagram*)
		iIdx_Droop_Offs : INT; (* Enumeration for Droop Offset *)
		rP_Droop_Offs : REAL; (* Actual Droop Offset Setpoint *)
		bMsg9024 : BOOL; (* B9024 - Isolated operation - Speed / Isochronous Mode *)
		bMsg9025 : BOOL; (* B9025 - Isolated operation - Droop Mode *)
		bMsg9026 : BOOL; (* B9026 - Isolated operation - Load sharing line *)
		bMsg2982 : BOOL; (* B2982 Power reduction calorific value *)
		rP_RedDelta_CppInt_Norm : REAL; (*Power reduction due Cylinder peak pressure integrator *)
		rP_Red_CppInt : REAL; (*Power reduction due Cylinder peak pressure integrator *)
		bMsg9284 : BOOL; (* W9284 Measuring signal failure External power set point for Speed droop mode *)
		bMsg2972 : BOOL; (* B2972 Power Mode on*)
		bMsg2973 : BOOL; (* B2973 Power Mode off*)
		rP_RedDelta_DPr_TJ_Norm : REAL; (*Power reduction by proportional valve differential pressure*)
		rP_Red_DPr_TJ : REAL; (*Power reduction by proportional valve differential pressure*)
		bMsg9051 : BOOL; (* B9051 Droop Mode for Power Controller *)
		bMsg9052 : BOOL; (* B9052 external speed reference offset Mode for Power Controller *)
		bMsg9057 : BOOL; (* B9057 - Isolated operation - external speed reference offset *)
		bMsg9058 : BOOL; (* B9058 - message power setpoint by Bus input Droop *)
		bMsg9059 : BOOL; (* B9059 - message power setpoint by analog input Droop *)
		bMsg9060 : BOOL; (* B9060 - message power setpoint by internal HMI value Droop *)
		bMsg9061 : BOOL; (* B9061 - speed setpoint reduction overload active *)
		bMsg9062 : BOOL; (* B9062 - speed setpoint reduction overload deactivated *)
		iMyPlant_Remote_Ready : INT; (*Signal for myPlant about the status of the remote function 0=not active / 1=Active but not ready / 2=ready or running*)
		bMsg9063 : BOOL; (* B9063 - Power setpoint input - external (myPlant) *)
		bMsg9064 : BOOL; (* B9064 - Request module on (myPlant) *)
		rP_RedDelta_SAErr_Norm : REAL; (*Power reduction due CAN communication failure for half or more SAFI or too many SAFI reboots*)
		rP_Red_SAErr : REAL; (*Power reduction due CAN communication failure for half or more SAFI or too many SAFI reboots*)
		bMsg2935 : BOOL; (*B2935 Power reduction CAN communication failure for half or more SAFI or too many SAFI reboots*)
		bMsg9075 : BOOL; (*Power reduction by charge temperature after TC *)
		bMsg9076 : BOOL; (*Power reduction by charge temperature after low-pressure TC *)
		rP_Red_H2 : REAL; (* power reduction due to H2 high [KW] *)
		rP_RedDelta_H2_Norm : REAL; (* power reduction due to H2 high related to Pnom *)
		bMsg9072 : BOOL; (* B9072 - Power reduction by H2 content *)
	END_STRUCT;
	VIS2MM_Opstate_Struct : 	STRUCT 
		bStart : BOOL; (* START (Button) of VISU *) (*OldName:START;Cycle:5;*)
		bStop : BOOL; (* STOP (Button) of VISU *) (*OldName:STOP;Cycle:5;*)
		iIdx_OMSS : DINT; (* index of operation mode selector switch *) (*OldName:new PV;Cycle:5;*)
		iIdx_RSS : DINT; (* index of request selector switch *) (*OldName:new PV;Cycle:5;*)
		bRemoteReq : BOOL; (* Remote Request (Button) of VISU *) (*OldName:FERN_ANF,A_ANF;Cycle:2;*)
		rP_set_vis : REAL; (* setpoint value for power from visu *) (*OldName:p_soll_vis;Cycle:2;*)
		iCnt_Starts : DINT; (* start counter *) (*OldName:start_z;Cycle:2;*)
		iCnt_OpHours : DINT; (* Engine operating hours counter *) (*OldName:betrieb_h;Cycle:2;*)
		iCnt_DemHours : DINT; (* demand hours counter *) (*OldName:new PV;Cycle:2;*)
		iCnt_NetPHours : DINT; (* net parallel operating hours counter *) (*OldName:new PV;Cycle:2;*)
		iCnt_IslandHours : DINT; (* island operating hours counter *) (*OldName:new PV;Cycle:2;*)
		iCnt_UnitOpHours : DINT; (* Unit operating hours counter *)
		bP_Droop_Set_Man : BOOL; (* Enable Droop Offset via HMI *)
		rP_Droop_Set_Man : REAL; (* Droop Offset via HMI *)
		iCnt_FastStarts : DINT; (* fast start counter *)
		bRemoteReq_myPlant : BOOL; (* Remote Request from myPlant *)
		rP_set_myPlant : REAL; (* setpoint value for power from myPlant [kW] *)
		iCnt_OpLowLoad : DINT; (* Low load operation counter [min] *)
	END_STRUCT;
	tSimPID_DS_typ : 	STRUCT 
		ssMethodType : SINT;
		P : REAL; (*Proportional gain*)
		I : REAL; (*Integral gain*)
		wxmin : LREAL; (*minimum input*)
		deadband : LREAL; (*deadband*)
		D : REAL; (*Derivative gain*)
		N : REAL; (*Filter number*)
		umax : REAL; (*Upper saturation level*)
		umin : REAL; (*Lower saturation level*)
		Kt : REAL; (*Tracking Gain*)
		wxmax : LREAL; (*maximum input*)
		mode : USINT; (*Manual*)
		u_man : REAL; (*Manual Value*)
		a : REAL; (*feed forward*)
		invert : BOOL; (*invert*)
		w : REAL; (*reference*)
		x : REAL; (*control variable*)
		reset : BOOL; (*Reset bit*)
		I0 : REAL; (*Integrator value at reset*)
		D0 : REAL; (*Filter value at reset*)
		u : REAL; (*Controller output*)
		up : REAL; (*proportional output*)
		ui : REAL; (*integral output*)
		ud : REAL; (*differential output*)
		u_tr : REAL; (*tracking output*)
		fbk_mode : USINT; (*Anti Windup Feedback Mode*)
		u_fbk : REAL; (*External Anti Windup Feedback*)
	END_STRUCT;
	PERM_OP_Struct : 	STRUCT 
		iCnt_Starts : DINT; (* start counter *) (*OldName:start_z;Cycle:2;*)
		iCnt_OpHours : DINT; (* operating hours counter *) (*OldName:betrieb_h;Cycle:2;*)
		iIdx_OMSS : DINT; (* operation mode selector switch *) (*OldName:new PV;Cycle:2;*)
		iIdx_RSS : DINT; (* remote selectro switch *) (*OldName:new PV;Cycle:2;*)
		rP_set_vis : REAL; (* setpoint value for power in KW *) (*OldName:new PV;Cycle:2;*)
		iCnt_IslandHours : DINT; (* island operating hours counter*) (*OldName:new PV;Cycle:2;*)
		iCnt_NetPHours : DINT; (*net parallel operating hours counter*) (*OldName:new PV;Cycle:2;*)
		iCnt_DemHours : DINT; (*demanded hours counter*) (*OldName:new PV;Cycle:2;*)
		rTB_PermValue07 : REAL; (*spare permanent value for testbench- replace with new vars of same lenght, when needed*) (*OldName:new PV;Cycle:2;*)
		rTB_PermValue08 : REAL; (*spare permanent value for testbench- replace with new vars of same lenght, when needed*) (*OldName:new PV;Cycle:2;*)
		rTB_PermValue09 : REAL; (*spare permanent value for testbench- replace with new vars of same lenght, when needed*) (*OldName:new PV;Cycle:2;*)
		rTB_PermValue10 : REAL; (*spare permanent value for testbench- replace with new vars of same lenght, when needed*) (*OldName:new PV;Cycle:2;*)
		iCnt_UnitOpHours : DINT; (* unit operating hours counter *)
		iCnt_FastStarts : DINT; (* fast start counter *)
		iCnt_OpLowLoad : DINT; (* Low load operation counter [min] *)
	END_STRUCT;
	AverageProcessStep_typ : 	STRUCT 
		iDuration : DINT; (*running average duration*) (*OldName:new PV;Cycle:5;*)
		iCounts : DINT; (*count of running average samples*) (*OldName:new PV;Cycle:5;*)
	END_STRUCT;
	OpMode_Switches : 	STRUCT 
		iIdx_OMS_Hw : INT; (* index of hardware operation mode selector switch *)
		iIdx_RMS_Hw : INT; (* index of hardware request mode selector switch *)
		iIdx_SyOMS_Hw : INT; (* index of hardware synchronisation operation mode selector switch *)
		bGoodQual : BOOL; (* Global GoodQual Bit for all 3 hw-switches *)
	END_STRUCT;
END_TYPE
