(*******************************************************************************
default		value set

This code is confidential and proprietary to the INNIO Company.
It may not be used in any form, or reproduced in any manner,
without the express written permission of the INNIO Company.
Copyright, INNIO Company, 2019
 
Customized modifications: -
------------------------
 
History:
-------
V0.00.0	24.04.2012	lettenb.	new
V3.99.0	07.03.2013	lettenb.	cleanup
																																		
Instructions for use:
--------------------
Outstandings:
------------
*******************************************************************************)
PROGRAM _CYCLIC

	(* default TRUE setting for not existing Di's *)
//	IN_AB.x.Di		:=	IN_AB.x.Di		OR	NOT IN_AB.x.GoodQual;

END_PROGRAM
