
TYPE
	PROGRAMMER_INFO : 	STRUCT 
		DO_NOT_SORT_PARA : STRING[40] := 'DO NOT CHANGE PARAMETER SORTING!'; (*DO NOT CHANGE PARAMETER SORTING!*) (*ADD NEW PARAMETER ONLY AT THE END OF THE Para STRUCTURE. DO NOT DELETE existing Para items.*)
	END_STRUCT;
	PARA_IC_Struct : 	STRUCT 
		iEng_Motortype : INT; (*PARA: engine motortype*) (*OldName:motortyp; Cycle:;*)
		rCA_AdvTimeLim : REAL; (*PARA [12065]: advanced ignition timing 1/10 deg *) (*OldName:AdvTimLi; Cycle:;*)
		b_IgnIC_SpdTrig2Inv : BOOL; (*PARA [12053]: TRUE=inverse speed trig 2 output *) (*OldName:bSpeedTrig2; Cycle:;*)
		rIgnIC_PowLev : REAL; (*PARA [12056]: ignition system energy level in % *) (*OldName:EnergLev; Cycle:;*)
		b_IgnIC_900Active : BOOL; (*PARA [12062]: TRUE=CAN ignition system is used *) (*OldName:ic900_vis; Cycle:;*)
		r_IgnIC_OutpMon : REAL; (*PARA [12054]: ignition output failure rate para. *) (*OldName:OutFailR; Cycle:;*)
		rN_OvrSpeed : REAL; (*PARA [12129]: Ignition overspeed limit*) (*OldName:OvrSpeed; Cycle:;*)
		r_IgnIC_ResPosIC : REAL; (*PARA [12055]: ignition reset pickup position *) (*OldName:r_IgnIC_ResPosIC; Cycle:;*)
		rCA_RetTimeLim : REAL; (*PARA [12066]: ignition retard timing limit *) (*OldName:RetTimLi; Cycle:;*)
		rN_IgnIC_SecSpeed : REAL; (*PARA [12059]: ignition system security speed *) (*OldName:SecSpeed; Cycle:;*)
		rN_IgnIC_HySpeed1 : REAL; (*PARA [12057]: hysteresis ign. speed trigger 1 *) (*OldName:SpeedHys1; Cycle:;*)
		rN_IgnIC_HySpeed2 : REAL; (*PARA [12058]: hysteresis ign. speed trigger 2 *) (*OldName:SpeedHys2; Cycle:;*)
		rN_IgnIC_SpeedTrig1 : REAL; (*PARA [12060]: ignition system speed trigger 1 *) (*OldName:SpeedTrig1; Cycle:;*)
		rN_IgnIC_SpeedTrig2 : REAL; (*PARA [12061]: ignition system speed trigger 2 *) (*OldName:SpeedTrig2; Cycle:;*)
		zz_V4_0_ParaVersionEnd : REAL := 4.0; (*! ADD NEW PARAMETER ONLY BELOW THIS LINE ! This is the end of base version parameter and has to stay unchanged. DO NOT CHANGE SORT ORDER of Para!*) (* OldName: new PV; Cycle: 5; *)
		bSEMIC_Active : BOOL; (*PARA[14519]: Ignition controller SEMIC*)
		rNum_IC_RelFwVer : REAL; (*PARA[14520]: Released SEMIC firmware version*)
		iNum_IC_PUMode : USINT; (*PARA[14521]: Pickup mode*)
		iNum_IC_CoilType : USINT; (*PARA[14522]: SEMIC coil type*)
		iTi_IC_TimeToPeak : UINT; (*PARA[14523]: Time to peak voltage [us]*)
		iI_IC_CoilCurrMax : USINT; (*PARA[14524]: Maximum primary coil current [A]*)
		iNum_IC_IgnEnergyMax : UINT; (*PARA[14525]: Maximum energy for firing event [mJ]*)
		iSpd_IC_PUMon : UINT; (*PARA[14526]: Speed to activate pickup monitoring [rpm]*)
		rU_IC_PUMin : REAL; (*PARA[14527]: Minimum pickup voltage [V]*)
		rSA_SparkDuration : REAL; (*PARA [12152]: SAFI spark duration  *)
		rSA_DurTol : REAL; (*PARA [12134]: spark duration deviation limit *) (* OldName:ucDurTol; Cycle: *)
		rSA_SparkCurChar : REAL; (*PARA [12150]: spark current characteristic*)
		rSA_SparkCurLev : REAL; (*PARA [12151]: spark current level *) (* OldName:ucSparkCurLev; Cycle: *)
		bDynSparkDuration : BOOL; (*PARA [13646]: Variable spark duration active *) (* OldName:newPV; Cycle: *)
		rP_Act_DynSpark_Limit_Nom : REAL; (*PARA [13648]: Spark duration below power threshold *) (* OldName:newPV; Cycle: *)
		usDurationIdle : UINT; (*PARA [13647]: Spark duration below power threshold *) (* OldName:newPV; Cycle: *)
		tSA_Ign_0 : IC_CurrPmmReal; (*PARA [12165]: SAFI ionization duration*) (* OldName:SAFICurr0PMM; Cycle: *)
		tSA_Ign_1 : IC_CurrPmmReal; (*PARA [12166] & PARA [12167] SAFI ignition current / duration setting 1 *) (* OldName:SAFICurr1PMM; Cycle: *)
		tSA_Ign_2 : IC_CurrPmmReal; (*PARA [12168] & PARA [12169]: SAFI ignition current / duration setting 2 *) (* OldName:SAFICurr2PMM; Cycle: *)
		tSA_Ign_3 : IC_CurrPmmReal; (*PARA [12170] & PARA [12171]: SAFI ignition current / duration setting 3 *) (* OldName:SAFICurr3PMM; Cycle: *)
		tSA_Ign_4 : IC_CurrPmmReal; (*PARA [12172] & PARA [12173]: SAFI ignition current / duration setting 4 *) (* OldName:SAFICurr4PMM; Cycle: *)
		tSA_Ign_5 : IC_CurrPmmReal; (*PARA [12174] & PARA [12175]: SAFI ignition current / duration setting 5 *) (* OldName:SAFICurr5PMM; Cycle: *)
		tSA_Ign_6 : IC_CurrPmmReal; (*PARA [12176]: SAFI ignition current setting 6 *) (* OldName:SAFICurr6PMM; Cycle: *)
		rNum_IC_TPCSCx1 : REAL; (*PARA[14528]: Breakpoint of secondary current axis for the target primary current 2D-MAP - X1*)
		rNum_IC_TPCSCx2 : REAL; (*PARA[14529]: Breakpoint of secondary current axis for the target primary current 2D-MAP - X2*)
		rNum_IC_TPCSCx3 : REAL; (*PARA[14530]: Breakpoint of secondary current axis for the target primary current 2D-MAP - X3*)
		rNum_IC_TPCSCx4 : REAL; (*PARA[14531]: Breakpoint of secondary current axis for the target primary current 2D-MAP - X4*)
		iNum_IC_TPCAPVy1 : USINT; (*PARA[14532]: Breakpoint of accumulated primary voltage axis for the target primary current 2D-MAP - Y1*)
		iNum_IC_TPCAPVy2 : USINT; (*PARA[14533]: Breakpoint of accumulated primary voltage axis for the target primary current 2D-MAP - Y2*)
		iNum_IC_TPCAPVy3 : USINT; (*PARA[14534]: Breakpoint of accumulated primary voltage axis for the target primary current 2D-MAP - Y3*)
		iNum_IC_TPCAPVy4 : USINT; (*PARA[14535]: Breakpoint of accumulated primary voltage axis for the target primary current 2D-MAP - Y4*)
		iI_IC_TPCx1y1 : USINT; (*PARA[14536]: Target primary current 2D-MAP data point - X1Y1*)
		iI_IC_TPCx1y2 : USINT; (*PARA[14537]: Target primary current 2D-MAP data point - X1Y2*)
		iI_IC_TPCx1y3 : USINT; (*PARA[14538]: Target primary current 2D-MAP data point - X1Y3*)
		iI_IC_TPCx1y4 : USINT; (*PARA[14539]: Target primary current 2D-MAP data point - X1Y4*)
		iI_IC_TPCx2y1 : USINT; (*PARA[14540]: Target primary current 2D-MAP data point - X2Y1*)
		iI_IC_TPCx2y2 : USINT; (*PARA[14541]: Target primary current 2D-MAP data point - X2Y2*)
		iI_IC_TPCx2y3 : USINT; (*PARA[14542]: Target primary current 2D-MAP data point - X2Y3*)
		iI_IC_TPCx2y4 : USINT; (*PARA[14543]: Target primary current 2D-MAP data point - X2Y4*)
		iI_IC_TPCx3y1 : USINT; (*PARA[14544]: Target primary current 2D-MAP data point - X3Y1*)
		iI_IC_TPCx3y2 : USINT; (*PARA[14545]: Target primary current 2D-MAP data point - X3Y2*)
		iI_IC_TPCx3y3 : USINT; (*PARA[14546]: Target primary current 2D-MAP data point - X3Y3*)
		iI_IC_TPCx3y4 : USINT; (*PARA[14547]: Target primary current 2D-MAP data point - X3Y4*)
		iI_IC_TPCx4y1 : USINT; (*PARA[14548]: Target primary current 2D-MAP data point - X4Y1*)
		iI_IC_TPCx4y2 : USINT; (*PARA[14549]: Target primary current 2D-MAP data point - X4Y2*)
		iI_IC_TPCx4y3 : USINT; (*PARA[14550]: Target primary current 2D-MAP data point - X4Y3*)
		iI_IC_TPCx4y4 : USINT; (*PARA[14551]: Target primary current 2D-MAP data point - X4Y4*)
		rNum_IC_PVOTRPCx1 : REAL; (*PARA[14552]: Breakpoint of spark current axis for the primary voltage off time reference 1D-TABLE - X1*)
		rNum_IC_PVOTRPCx2 : REAL; (*PARA[14553]: Breakpoint of spark current axis for the primary voltage off time reference 1D-TABLE - X2*)
		rNum_IC_PVOTRPCx3 : REAL; (*PARA[14554]: Breakpoint of spark current axis for the primary voltage off time reference 1D-TABLE - X3*)
		rNum_IC_PVOTRPCx4 : REAL; (*PARA[14555]: Breakpoint of spark current axis for the primary voltage off time reference 1D-TABLE - X4*)
		rNum_IC_PVOTRPCx5 : REAL; (*PARA[14556]: Breakpoint of spark current axis for the primary voltage off time reference 1D-TABLE - X5*)
		rNum_IC_PVOTRx1 : REAL; (*PARA[14557]: Duty cycle reference 1D-TABLE data point - X1*)
		rNum_IC_PVOTRx2 : REAL; (*PARA[14558]: Duty cycle reference 1D-TABLE data point - X2*)
		rNum_IC_PVOTRx3 : REAL; (*PARA[14559]: Duty cycle reference 1D-TABLE data point- X3*)
		rNum_IC_PVOTRx4 : REAL; (*PARA[14560]: Duty cycle reference 1D-TABLE data point- X4*)
		rNum_IC_PVOTRx5 : REAL; (*PARA[14561]: Duty cycle reference 1D-TABLE data point- X5*)
		iNum_IC_APVCF : USINT; (*PARA[14562]: Accumulated primary voltage compensation factor. Used for target primary current compensation for non nominal secondary voltage*)
		iI_IC_MPCPVOff : USINT; (*PARA[14617]: Calibration parameter for spark diagnostics. Minimum primary current after 250us spark duration if no 80v is applied*)
		iI_IC_MPCPVOn : USINT; (*PARA[14618]: Calibration parameter for spark diagnostics. Minimum primary current after 250us spark duration if 80v is applied for 250us*)
	END_STRUCT;
END_TYPE
